Copter: Change the immediate value to the defined name
ArduPilot/ardupilot pull request #11906
Opened 2019-07-29 14:46 UTC by muramura

I think that the definition name is easier to understand than 1.

2019-07-29 23:30 UTC, rmackay9 commented
Should this be an enum maybe?

2019-07-30 09:20 UTC, peterbarker commented
`enum class` :-)

2019-07-30 15:37 UTC, muramura commented
@rmackay9 san, @peterbarker san.
I changed the definition to enum class.

2019-07-31 02:06 UTC, peterbarker commented on ArduCopter/mode_throw.cpp
> +        if (g.throw_motor_start == (int8_t)Parameters::THROW_MOTOR_START::RUNNING) {
```suggestion
        if (g.throw_motor_start == (uint8_t)Parameters::THROW_MOTOR_START::RUNNING) {
```

2019-07-31 02:07 UTC, peterbarker commented on ArduCopter/mode_throw.cpp
> +        if (g.throw_motor_start == (int8_t)Parameters::THROW_MOTOR_START::RUNNING) {
```suggestion
        if (g.throw_motor_start == (uint8_t)Parameters::THROW_MOTOR_START::RUNNING) {
```

2019-07-31 22:56 UTC, muramura commented
@peterbarker san.. I understand the type. Thank you for the type change.

2019-08-01 22:20 UTC, peterbarker commented on ArduCopter/Parameters.h
> +    enum class THROW_MOTOR_START : uint8_t {
Argh.  Sorry, I neglected to suggest changing the class name; we tend to use mixed-caps for the enum-class name:

```suggestion
    enum class ThrowMotorStart : uint8_t {
```

2019-08-01 22:20 UTC, peterbarker commented on ArduCopter/mode_throw.cpp
> +        if (g.throw_motor_start == (uint8_t)Parameters::THROW_MOTOR_START::RUNNING) {
```suggestion
        if (g.throw_motor_start == (uint8_t)Parameters::ThrowMotorStart::RUNNING) {
```

2019-08-01 22:21 UTC, peterbarker commented on ArduCopter/mode_throw.cpp
> +        if (g.throw_motor_start == (uint8_t)Parameters::THROW_MOTOR_START::RUNNING) {
```suggestion
        if (g.throw_motor_start == (uint8_t)Parameters::ThrowMotorStart::RUNNING) {
```

2019-08-01 22:21 UTC, peterbarker commented on ArduCopter/Parameters.cpp
> +    GSCALAR(throw_motor_start, "THROW_MOT_START", (uint8_t)Parameters::THROW_MOTOR_START::STOPPED),
```suggestion
    GSCALAR(throw_motor_start, "THROW_MOT_START", (uint8_t)Parameters::ThrowMotorStart::STOPPED),
```

2019-08-02 21:50 UTC, muramura commented
@peterbarker san..
As I understood, enum class name does not use "_", it is written in capital letters.

2019-08-05 06:52 UTC, peterbarker commented
I've just realised the commits need squashing here.

2020-10-27 06:13 UTC, peterbarker requested changes
This should only be a single commit.

2020-10-27 06:13 UTC, peterbarker commented on ArduCopter/Parameters.h
> +    enum class ThrowMotorStart : uint8_t {
This should be within the throw mode, not in the parameters class.

2020-12-05 09:55 UTC, peterbarker commented
Replaced by https://github.com/ArduPilot/ardupilot/pull/15982 - thanks!

2020-12-05 09:55 UTC, closed without merging