GCS_Mavlink: Uniform GCS_MAVLINK_Parameters across all platforms
ArduPilot/ardupilot pull request #13343
Opened 2020-01-20 21:21 UTC by giacomo892

2020-02-18 22:27 UTC, peterbarker commented
This is a significant behavioural change for all of our vehicles - *most* notable Copter which traditionally hasn't spoken unless requested.

Consistency is good, but it would require all vehicle maintainers to be happy with this change.

Notionally it would be possible to retain the current behaviour by having the vehicles make several defines then `#include` a file from the base class - we do something similar in `RC_Channels_VarInfo.h` - it's kind of awful, 'though.

We should probably discuss this at a devcall.

2020-02-24 08:16 UTC, giacomo892 commented
The PR still has some compilation errors, but yeah would be nice to hear from the team before doing more work on it.

2020-02-25 01:05 UTC, tridge commented
build for replay needs fixing, and commit needs splitting with Tools/gittools/git-subsystems-split

2020-02-27 04:15 UTC, peterbarker requested changes
@giacomo892 do you know how to use the subsystem-split tool to make this a commit/directory?

@giacomo892 do you know how to go about fixing Replay?

2020-02-27 04:15 UTC, peterbarker commented on libraries/GCS_MAVLink/GCS_MAVLink.cpp
> +    AP_GROUPINFO("ADSB",   9, GCS_MAVLINK_Parameters, streamRates[9],  5),
Please change this to zero.

2020-02-27 08:25 UTC, giacomo892 commented on libraries/GCS_MAVLink/GCS_MAVLink.cpp
> +    AP_GROUPINFO("ADSB",   9, GCS_MAVLINK_Parameters, streamRates[9],  5),
Sure

2020-02-27 08:29 UTC, giacomo892 commented
@peterbarker I've tried to run subsystem-split tool but it does nothing to split the commits.

Regarding the missing issue, if you want to take over and continue my work the proper way I would be happy.

2020-02-27 09:34 UTC, peterbarker commented
I've done the subsystem split.

Commands were basically `git commit --amend` to trim off the (incorrect) directory entry fromthe commit message, then:

```
pbarker@bluebottle:~/rc/ardupilot(giacomo892-streamRates)$ ./Tools/gittools/git-subsystems-split 
rm: cannot remove '/tmp/tmp.xoVD3xh0X5': No such file or directory
Reseting changes in order to add files separately...
Adding and committing subsystems...
[giacomo892-streamRates 1ff519b399] GCS_MAVLink: uniform GCS_MAVLINK_Parameters across all platforms
 Author: giacomo892 <giacomo892@users.noreply.github.com>
 1 file changed, 97 insertions(+)

[giacomo892-streamRates 326170173f] AntennaTracker: uniform GCS_MAVLINK_Parameters across all platforms
 Author: giacomo892 <giacomo892@users.noreply.github.com>
 1 file changed, 87 deletions(-)

[giacomo892-streamRates 9ef4c6c461] APMrover2: uniform GCS_MAVLINK_Parameters across all platforms
 Author: giacomo892 <giacomo892@users.noreply.github.com>
 1 file changed, 97 deletions(-)

[giacomo892-streamRates 0e143de336] ArduCopter: uniform GCS_MAVLINK_Parameters across all platforms
 Author: giacomo892 <giacomo892@users.noreply.github.com>
 1 file changed, 94 deletions(-)

[giacomo892-streamRates 83cb855524] ArduPlane: uniform GCS_MAVLINK_Parameters across all platforms
 Author: giacomo892 <giacomo892@users.noreply.github.com>
 1 file changed, 97 deletions(-)

[giacomo892-streamRates 87876c4b78] ArduSub: uniform GCS_MAVLINK_Parameters across all platforms
 Author: giacomo892 <giacomo892@users.noreply.github.com>
 1 file changed, 76 deletions(-)

pbarker@bluebottle:~/rc/ardupilot(giacomo892-streamRates)$ 
```

2020-02-27 09:55 UTC, peterbarker commented
I've also fixed Replay's build issue.

2020-02-27 10:14 UTC, giacomo892 commented
Thanks, I was running that command but it was returning just my last commit and stopped there.
When you are happy, you can merge this I guess.

2020-02-28 09:28 UTC, giacomo892 commented
Thanks @peterbarker for your work!

2020-02-28 09:37 UTC, peterbarker commented
@giacomo892 no worries :-)

2020-03-03 01:13 UTC, rmackay9 commented
Thanks very much for this work.  As discussed on the dev call, we've decided that we need to avoid these kind of stuctural changes for the next month or so as we focus on clearing off issues that have come out of the Copter/Plane-4.0 releases.

We're not closing this PR but we are putting off merging for now.

2020-12-16 10:13 UTC, amilcarlucas commented
Now that 4.0 is out, this can be revisited. @giacomo892 are you willing to rebase this on top of master?

2020-12-16 17:16 UTC, giacomo892 commented
> Now that 4.0 is out, this can be revisited. @giacomo892 are you willing to rebase this on top of master?

Rebased. Looks like replay needs to be fixed. Can someone address it?

2026-07-09 05:18 UTC, peterbarker commented
@giacomo892 thanks for your work on this.  It did influence the way we did things, but we've now got the equivalent to this code in master.

Thanks!

2026-07-09 05:18 UTC, closed without merging