Correct handling of -1 in RC overrides
ArduPilot/ardupilot pull request #13370
Opened 2020-01-24 07:12 UTC by peterbarker

This is a PR against master achieving the same effect as 
https://github.com/ArduPilot/ardupilot/pull/13356 is achieving for stable.

The logic as it currently stands is too complicated; this attempts to simplify it.

Also adds a test to ensure this doesn't get broken.  The tests fails before either patch and passes after either.

2020-01-24 08:17 UTC, rmackay9 commented
It would be nice if we could merge rrr's PR in order to let him get credit for finding the issue..

2020-01-24 08:42 UTC, peterbarker commented
@rmackay9 I've approved his PR.  I'm happy to rebase this on top of master if you *also* want to merge that other patch to master too.

2020-01-27 10:24 UTC, rmackay9 commented
I've pushed rrr's PR in so feel free to rebase.

2021-01-05 00:19 UTC, tridge requested changes

2021-01-05 00:19 UTC, tridge commented on libraries/RC_Channel/RC_Channel.h
> +    uint32_t override_timeout_ms() const {
bool with reference would be better

2021-01-05 09:40 UTC, peterbarker commented on libraries/RC_Channel/RC_Channel.h
> +    uint32_t override_timeout_ms() const {
Done

2021-01-06 07:32 UTC, tridge approved these changes

2021-01-06 07:33 UTC, merged