Rover: Update AP_Notify of GCS failsafe
ArduPilot/ardupilot pull request #13747
Opened 2020-03-06 18:13 UTC by ashvath100

sets AP_Notify flag for GCS failsafe for Rover
AP_Notify will beep and/or flash when the GCS failsafe (aka Telemetry Failsafe) has triggered.

2020-03-09 09:54 UTC, amilcarlucas commented
Can this be done for other vehicles? Shouln't this be moved to AP_Vehicle ?

2020-03-09 10:01 UTC, Pedals2Paddles commented
It's already in Copter. Right now it is a vehicle specific function. Making this apply to all vehicles would be a huge scope creep for this, probably a topic for another PR.

2020-03-12 10:07 UTC, peterbarker commented
@ashvath100 could you do a quick scoping out on how much work you think it would be to move this code up rather than copy it sideways, please?

2020-03-12 16:19 UTC, ashvath100 commented
> @ashvath100 could you do a quick scoping out on how much work you think it would be to move this code up rather than copy it sideways, please?
@peterbarker  I'm sorry ,I don't exactly understand what is expected

2020-03-13 11:39 UTC, peterbarker commented
@ashvath100 the suggestion from @amilcarlucas was to make this available to all vehicles - to handle it in the parent class.

This would generally be implementing a pure-virtual function to get some piece of information from the vehicle - the gcs timeout value, perhaps - and the using the AP_Notify singleton object to do the deed itself.

If that's too much for you to attack - doesn't matter.  We don't *need* to scope creep it on you :-)

2021-02-04 11:29 UTC, peterbarker approved these changes
OK, so I had a bit of a play with this myself.

Turns out moving it up is absolutely non-trivial - I've made some baby-steps towards it with this PR: https://github.com/ArduPilot/ardupilot/pull/16515

We'd basically need to have common failsafe routines on AP_Vehicle to do this properly.  I think it is quite reasonable to merge this until we get all of that sorted out - it's a straight-forward change and brings some functionality which the user desired.

I've tested this in SITL with the help of `--rgbled` - and it makes the thing flash when the GCS goes away where it doesn't in master.

2021-02-04 13:11 UTC, khancyr approved these changes
LGTM

2021-02-05 00:14 UTC, rmackay9 requested changes
I guess I'm a bit of a stickler but this should probably be in the failsafe_trigger() which is where the actions are.  Otherwise the LEDs will start flashing before the timeout has passed.

put another way, the actions for a failsafe are done inside of failsafe_trigger.

2021-02-05 02:41 UTC, peterbarker commented
@rmackay9 's right - the actions we take should be within that other method.  The fact Copter doesn't do it like that at the moment is unfortunate (i.e. this PR makes it look like Copter, we're suggesting it should be done better.

@ashvath100 did you want to press on with this PR?

2021-02-05 02:48 UTC, rmackay9 commented
@peterbarker, one thing though is that Copter doesn't have a functional issue because it doesn't have this odd two-stage timeout that Rover has.  Structurally Copter could perhaps be done better but it wouldn't make a functional difference.

2021-02-18 17:58 UTC, closed without merging