Copter: Set the landing waiting time at fail safe to the set value
ArduPilot/ardupilot pull request #13852
Opened 2020-03-21 03:30 UTC by muramura

I don't know why failsafe is fixed at 4 seconds.
I think it would be better to be able to change 4 seconds.

2020-03-21 23:13 UTC, muramura commented
@khancyr san. Comment Thanks.

I live in Japan. In Japan, telemetry information cannot be viewed on the radio.
I don't know why to wait 4 seconds in failsafe.
If there is a process that takes 4 seconds after detecting fail safe, I think that it is good as it is.

In Japan, the radio cannot receive telemetry by itself.
Many telemetry messages of ArduPilot are useless in Japan.
In Japan, alarms, LED lights, blinks, and colors are often used.

I am fail safe and want to decide whether to wait 4 seconds or immediately.

2021-01-04 05:08 UTC, peterbarker requested changes

2021-01-04 05:08 UTC, peterbarker commented on ArduCopter/mode_land.cpp
> +        if(land_pause && millis()-land_start_time >= static_cast<uint32_t>(copter.g.land_delay_time)) {
This isn't a `uint32_t`.  Our pattern is usually `.get()`.

Similarly elsewhere.

2021-01-04 05:08 UTC, peterbarker commented on ArduCopter/Parameters.cpp
> +    // @DisplayName: Waiting time to land
```suggestion
    // @DisplayName: Land Pause Delay
```

2021-01-04 05:08 UTC, peterbarker commented on ArduCopter/Parameters.cpp
> +    // @Description: Waiting time to land
```suggestion
    // @Description: When switching to land mode due to a failsafe the vehicle will pause for this many milliseconds before starting to descend
```

2021-01-04 05:08 UTC, peterbarker commented on ArduCopter/Parameters.cpp
> +    GSCALAR(land_delay_time, "LAND_DELAY_TIME", LAND_WITH_DELAY_MS),
We may want 
```suggestion
    GSCALAR(land_delay_time, "LAND_DELAY_MS", LAND_WITH_DELAY_MS),
```

2021-01-05 00:12 UTC, rmackay9 commented
I'm not sure that this is really worth the cost of a new parameter.  Each new parameter takes up some flash and more importantly adds complexity for the user.  I think if the delay is too long or too short you can perhaps adds a #define into APM_Config.h.  Txs anyway

2021-01-05 00:12 UTC, closed without merging