AP_IOMCU: check last-checked-time before asserting iomcu has rebooted
ArduPilot/ardupilot pull request #14728
Opened 2020-07-01 08:49 UTC by peterbarker

The new printf in this message will be emitted if you "flashbootloader" a CubeOrange when it needs to update the bootloader.

The CPU is entirely locked out while flashing the bootloader.  This includes the IOMCU reset checking process.  It will see a significantly different time back from the IOMCU when it comes back to life - so we had better make sure our own scheduling is sane before blaming someone else.

Probably doesn't show up on non-F7 boards due to page size stuff.

I was in two minds about having the `printf`, but came down in favour of it; if we have problems elsewhere it might give us a hint.

2020-11-24 11:45 UTC, peterbarker commented
Closed #14723

2020-11-25 08:00 UTC, tridge commented
can we use in_expected_delay(), and do we need to add some lattitude on the end of an expected delay, maybe 10ms?

2020-11-25 08:02 UTC, tridge requested changes
use in_expected_delay if possible

2020-12-07 23:25 UTC, peterbarker commented
Closing in favour of https://github.com/ArduPilot/ardupilot/pull/15987

2020-12-07 23:25 UTC, closed without merging