AP_OSD: add rangefinder panel
ArduPilot/ardupilot pull request #14749
Opened 2020-07-04 15:21 UTC by vierfuffzig

2021-03-13 17:26 UTC, khancyr requested changes
We should rework this to remove the rangefinder backend dependency and use the right rangefinder functions ! And rebased

![image](https://user-images.githubusercontent.com/705341/111038464-66505b80-8429-11eb-9b17-4876c29b2c24.png)


![image](https://user-images.githubusercontent.com/705341/111038430-1f626600-8429-11eb-924a-bb65e0451f4a.png)

2021-03-13 17:26 UTC, khancyr commented on libraries/AP_OSD/AP_OSD_Screen.cpp
> +    } else if  (!sensor->has_data()) {
if (rangefinder.status_orient(ROTATION_PITCH_270) != RangeFinder::Status::NoData) {

2021-03-13 17:26 UTC, khancyr commented on libraries/AP_OSD/AP_OSD_Screen.cpp
> +    } else if  (!sensor->has_data()) {
This will remove the dependency on the AP_RangeFinder_Backend and get the right rangefinder that is assume to be the altitude one's

2021-03-13 17:26 UTC, khancyr commented on libraries/AP_OSD/AP_OSD_Screen.cpp
> +    backend->write(x, y, false, "RNGF:%2.2f%c", u_scale(DISTANCE, (sensor->distance_cm() * 0.01f)), u_icon(DISTANCE));
rangefinder.distance_cm_orient(ROTATION_PITCH_270)

2021-05-05 04:06 UTC, peterbarker commented
@vierfuffzig are you planning on pursuing this PR?

2021-05-05 06:21 UTC, vierfuffzig commented
@peterbarker i really need to check my notification alert settings. i‘ll get this updated asap. and sorry, can‘t see why i keep missing notifications that reference my iwn PRs...

2021-05-05 09:00 UTC, vierfuffzig commented
@peterbarker @khancyr done, appreciate your review.

2021-05-12 15:57 UTC, vierfuffzig commented
rebased again while other changes to OSD have gone in. 
@khancyr could you take a look if time permits?

2021-05-13 13:50 UTC, khancyr commented on libraries/AP_OSD/AP_OSD_Screen.cpp
> +    if (rangefinder->status_orient(ROTATION_PITCH_270) == RangeFinder::Status::NoData) {
```suggestion
    if (rangefinder->status_orient(ROTATION_PITCH_270) <= RangeFinder::Status::NoData) {
```
That would also handle the not connected case. For out-of-bound, I don't remember what is the behavior, so we could keep the latest_value returned.

2021-05-13 14:02 UTC, vierfuffzig commented
@khancyr thanks, done.

2021-05-13 15:40 UTC, Hwurzburg commented
Personally using RNGF: as a label uses up too much screen space....what about simply a RF in front of the distance? like GS and AS ?

2021-05-13 16:27 UTC, vierfuffzig commented
@Hwurzburg yup, been thinking so too the longer i‘ve been looking at it. will shorten to RF

2021-05-13 17:25 UTC, vierfuffzig commented
added a single char rangefinder symbol tosave screenspace:
![image](https://user-images.githubusercontent.com/9342253/118162334-e6db0a80-b420-11eb-983e-dfa3bbf5a6e7.png)

2021-05-25 14:33 UTC, khancyr approved these changes
LGTM

2021-05-26 09:01 UTC, tridge requested changes

2021-05-26 09:01 UTC, tridge commented on libraries/AP_OSD/AP_OSD_Screen.cpp
> +    RangeFinder *rangefinder = RangeFinder::get_singleton();
needs to check for null ptr

2021-05-26 09:01 UTC, tridge commented on libraries/AP_OSD/AP_OSD_Screen.cpp
> +    backend->write(x, y, false, "%c%2.2f%c", SYM_RNGFD, u_scale(DISTANCE, (rangefinder->distance_cm_orient(ROTATION_PITCH_270) * 0.01f)), u_icon(DISTANCE));
fix indent

2021-05-26 20:52 UTC, vierfuffzig commented on libraries/AP_OSD/AP_OSD_Screen.cpp
> +    RangeFinder *rangefinder = RangeFinder::get_singleton();
done

2021-05-26 20:53 UTC, vierfuffzig commented on libraries/AP_OSD/AP_OSD_Screen.cpp
> +    RangeFinder *rangefinder = RangeFinder::get_singleton();
done

2021-05-26 20:53 UTC, vierfuffzig commented on libraries/AP_OSD/AP_OSD_Screen.cpp
> +    backend->write(x, y, false, "%c%2.2f%c", SYM_RNGFD, u_scale(DISTANCE, (rangefinder->distance_cm_orient(ROTATION_PITCH_270) * 0.01f)), u_icon(DISTANCE));
done

2021-05-26 20:55 UTC, vierfuffzig commented
@tridge thanks for your review, requested changes done, rebased and added updated font images.

2021-05-26 21:00 UTC, tridge approved these changes

2021-06-01 01:33 UTC, merged

2021-06-01 01:33 UTC, peterbarker commented
Merged, thanks!

2021-06-02 20:44 UTC, vierfuffzig commented
thanks for merging @peterbarker