AP_GPS: Add NMEA THS message.
ArduPilot/ardupilot pull request #14762
Opened 2020-07-06 19:12 UTC by phamelin

Add support for NMEA THS message, which is basically the same as HDT but with a data qualifier.

2020-07-07 01:51 UTC, peterbarker commented
Doesn't this kind of break things for people running devices not emitting this message?

2020-07-07 12:51 UTC, khancyr commented
@peterbarker, it doesn't seems to break the previous behavior, just add the parsing of another message.

@phamelin could you split your commit in two : one for AP_GPS, the other for AP_HAL_SITL ?

I am not knowledgable enough on NMEA but I don't think we should change the SITL part.

2020-07-07 13:10 UTC, phamelin commented
@khancyr I was also concerned with the SITL part. Currently, the HDT message is sent even if there's no gps lock. That's why I replaced HDT with THS in SITL because this one has a data qualifier. It would be nice if we could generate either HDT or THS in SITL, but this would imply additionnal SIM_* parameters. What we could do is replace SIM_GPS_HDG with two parameters: SIM_GPS_HDT and SIM_GPS_THS. I don't know if we want to go that way. Anyway, I will split the commit and then we will be able to discuss the modifications.

2020-07-07 19:34 UTC, phamelin commented
The pull request is now splitted in two commits.

2020-07-16 16:42 UTC, yanivasy commented
I think the time/week bug in NMEA parsing should be fixed as well
https://github.com/ArduPilot/ardupilot/issues/14298

2021-03-08 13:26 UTC, phamelin commented
@WickedShell Other than resolving the conflict with the master branch, is there anything I can do to make this pull request go ahead?

2021-03-09 09:05 UTC, khancyr commented
@phamelin could you rebase it ? I will bring it on devcall tomorrow. Hopefully, the NMEA part could be merge easily, and we could discuss the SITL part.

2021-03-19 12:51 UTC, phamelin commented
@khancyr I apologize for the late reply. I have been very busy recently. I just did the rebase. Thank you for handling this.

2021-04-07 08:23 UTC, tridge requested changes

2021-04-07 08:23 UTC, tridge commented on libraries/AP_GPS/AP_GPS_NMEA.h
> +    uint32_t _last_HDT_THS_ms{0};
we don't need to init this to zero as we auto-init all allocated objects to zero. Adding the init consumes flash space unnecessarily

2021-04-07 08:23 UTC, tridge commented on libraries/AP_HAL_SITL/sitl_gps.cpp
> +        _gps_nmea_printf(instance, "$GPTHS,%.2f,%c,T", d->yaw, d->have_lock ? 'A' : 'V');
let's make it so that SIM_GPS_HDG==1 means HDT and SIM_GPS_HDG==2 means THS, so we can test both

2021-04-07 08:24 UTC, tridge commented
also, can you add a comment in the code explaining which GPS vendor includes the THS message?

2021-04-12 12:34 UTC, phamelin commented
@tridge I just pushed the requested changes. Thank you.

2021-04-13 12:01 UTC, khancyr approved these changes
seems good

2021-04-14 07:19 UTC, tridge approved these changes

2021-04-14 07:20 UTC, merged

2021-04-14 07:20 UTC, tridge commented
nice PR, thanks!