Support VTOL_LAND options
ArduPilot/ardupilot pull request #14874
Opened 2020-07-21 20:22 UTC by WickedShell

This allows the GCS to make a `NAV_VTOL_LAND` either do the circle to land or a normal straight in land. It should have always been done this way instead of as a `Q_OPTIONS` bit, but I took the fast path originally.

This also allows us to specify a straight in approach with automatic detransition which we currently aren't supporting. The reason to not use a Q_OPTIONS bit is the same mission may want to use both a spiral landing and a specified approach heading.

2020-07-29 11:28 UTC, tridge commented
see also an alternative approach (pun intended) here: #14938

2022-06-30 23:57 UTC, WickedShell commented
Updated, and SITL tested. MAVLink commit is an easy thing to resolve the conflict on, but I'm actually happy with that being a blocker until the change is merged into the sub module.

2022-07-04 23:11 UTC, tridge commented
@WickedShell looks good, we just need to get the mavlink changes in first, then ensure the mavlink git hash points to the master HEAD in this PR
thanks!

2022-07-25 20:55 UTC, WickedShell commented
Updated the MAVLink submodule now that the MAVLink repo has the message, and fixed the conflicts.

2022-07-25 23:01 UTC, tridge commented
@WickedShell failing lots of tests, looks like mavlink not updated correctly?

2022-08-01 20:40 UTC, WickedShell commented
> @WickedShell failing lots of tests, looks like mavlink not updated correctly?

Sorry, bad rebasing, I've fixed it.

2022-08-01 23:24 UTC, tridge approved these changes

2022-08-01 23:25 UTC, tridge requested changes
ok to merge when soaring changes backed out

2022-08-01 23:25 UTC, tridge commented on libraries/AP_Soaring/AP_Soaring.cpp
> +#pragma GCC diagnostic ignored "-Wuninitialized"
these changes are not needed any more as the warnings have been fixed

2022-08-16 00:05 UTC, merged