Fix handling of higher-numbered channels in RC_CHANNELS_OVERRIDE
ArduPilot/ardupilot pull request #15065
Opened 2020-08-16 04:16 UTC by peterbarker

Yes yes, mavlink changes would need to go upstream :-)

I can't help but think a `release_override` method might be a nice idea here.

2020-12-22 00:29 UTC, tridge commented
i like this approach

2020-12-26 04:28 UTC, magicrub commented
Yes, I like this approach too. This feature would have definitely come in handy on previous projects I've worked on

2020-12-29 00:13 UTC, amilcarlucas requested changes
there is a small typo on line 3660 of common.xml. val1ue instead of value

2020-12-29 00:20 UTC, tridge approved these changes

2020-12-29 04:03 UTC, merged