GCS_MAVLink: Matches MAVLink's Mission Upload protocol specification
ArduPilot/ardupilot pull request #15067
Opened 2020-08-16 05:37 UTC by muramura

When the GCS sends MISSION_COUNT to the FC, the FC requests it with MISSION_REQUEST.
In the MAVLINK specification, the FC requests it with MISSION_REQUEST_INT.
I think it's better to match the MAVLINK specification.

MAVLink Spec:
https://mavlink.io/en/services/mission.html#uploading_mission

2020-08-16 05:51 UTC, muramura commented
I re-opened MISSION_ITEM because it is deprecated and I thought it would be better to conform to the recommended specifications.

MAVLink Spec:
Deprecated Types: MISSION_ITEM
The legacy version of the protocol also supported MISSION_REQUEST for requesting that a mission be sent as a sequence of MISSION_ITEM messages.
Both MISSION_REQUEST and MISSION_ITEM messages are now deprecated, and should no longer be sent. If MISSION_REQUEST is recieved the system should instead respond with MISSION_ITEM_INT items (as though it received MISSION_REQUEST_INT).

https://mavlink.io/en/services/mission.html#command_message_type

2020-08-16 15:55 UTC, WickedShell commented
This breaks older ground stations, whereas the current version still allows them to cope, and since we will handle the requests, I'm not convinced we should be changing anything.

2020-08-16 21:38 UTC, muramura commented
@WickedShell san.   The development of a new GCS must respond to the message of deprecation.
SITL is responding to the deprecation.
I suggest a way to determine if you want to support an older GCS by system ID.
I would have MISSION PLANNER, APM PLANNER2, QGROUNDCONTROL and SITL send MISSION_REQUEST_INT messages.
For other GCSs, make them send a MISSION_REQUEST message.

2020-08-17 02:02 UTC, peterbarker commented
@muramura changing behaviour based on sysid is a recipe for vast amounts of confusion - likewise for component-id.  The sysid references to apm planner2 and MissionPlanner are bogus - other GCSs use those sysids, and apm planner2 and MissionPlanner can both use other sysids.

It would be nice to be able to make this change, but before we do so we have to ensure we're not going to wholesale break vast numbers of clients.  Off the top of my head, that would include QGC, MissionPlanner, APMPlanner2, MAVProxy, Solex, UGCS, dronekit-python and the other dronekits.  Some of those are embedded in companion computer images like APSync - dronekit-python, for example - so current images of those would need to be checked to see if the versions installed are good.

Moving forward can be painful :-(

Notionally - and I wouldn't go coding until discussion has been had - we could request `MISSION_ITEM_INT` and if that times out fall back to requesting `MISSION_ITEM` - and emit a really harsh warning that the client needs to be updated!  That's a chunk of painful compatibility code to carry around for a couple of years, 'though.

2020-08-21 04:39 UTC, davidbuzz commented
if we can find a way to make this backward compatible, then i'd support it. Perhaps the best solution for right now is to send both , and let the GCS's respond to whichever they understand.?

2021-02-03 04:01 UTC, peterbarker requested changes
As-is this will break every MAVProxy install.

2021-02-03 04:03 UTC, peterbarker commented
... by a quick scan of MissionPlanner it will break it as well (@meee1).

2021-05-05 04:01 UTC, peterbarker commented
@muramura are you planning on pursuing this PR?

2021-05-05 06:10 UTC, muramura commented
@peterbarker sa.
I found that, difficult to adapt to the MAVLINK protocol.
I would like to change it so that it can support both.

2024-09-04 06:45 UTC, peterbarker commented
We changed the protocol; it's all MISSION_REQUEST_INT now, and we're supposed to send ITEM_INT now.

Thanks anyway!

2024-09-04 06:45 UTC, closed without merging