[AP_OLC] Add pluscode element to OSD
ArduPilot/ardupilot pull request #15107
Opened 2020-08-19 19:17 UTC by giacomo892

This PR adds the AP_OLC library that allows to generate OLC (open location codes) from a give latitude and longitude pair and  a new OSD element, PLUSCODE, that allow to display the +code on the OSD screen using less space than the current lat/lon pair.
More info on: https://github.com/google/open-location-code

Thanks @shellixyz for the help and @fiam for the original code in INAV.

2020-08-26 12:03 UTC, Gone4Dirt commented
Interesting.  Forgive my ignorance but what is the use case here?  I am curious, other than reduced space on the OSD what does using OLC give you over using lat long.

2020-08-26 16:54 UTC, giacomo892 commented
> Interesting. Forgive my ignorance but what is the use case here? I am curious, other than reduced space on the OSD what does using OLC give you over using lat long.

It uses much less space on the screen

2020-08-31 13:42 UTC, giacomo892 commented
![image](https://user-images.githubusercontent.com/20860004/91726443-88c30b80-eba0-11ea-9bd0-77cca5b2fdc8.png)
Tested on SITL, you can see in the bottom part of the OSD which are the benefits of this PR

2020-09-14 08:37 UTC, peterbarker requested changes
I haven't delved into the mechanics of this yet.

I'm not sure the "why" question has been adequately answered.  Is the proposal that users can stop displaying lat/lng and start displaying the pluscode instead?  It looks like it fulfils the same role - does the pluscode implementation here give as much precision as the replaced lat/lon?

2020-09-14 08:37 UTC, peterbarker commented on libraries/AP_OLC/AP_OLC.cpp
> +static constexpr int SEPARATOR_POS = 8;
Please stick to stdint types as much as possible - e.g. `uint8_t` here.

2020-09-14 08:37 UTC, peterbarker commented on libraries/AP_OLC/AP_OLC.cpp
> +bool AP_OLC::inited = false;
No need for this to be a static.

2020-09-14 08:37 UTC, peterbarker commented on libraries/AP_OLC/AP_OLC.cpp
> +    olc_coord_t initial_exponent = floorf(logf(2 * (LON_MAX / OLC_DEG_MULTIPLIER)) / logf(ENCODING_BASE));
These looks like a constant to me.

They ought to be calculated ahead of time?

2020-09-14 08:37 UTC, peterbarker commented on libraries/AP_OLC/AP_OLC.h
> +static int olc_encode(olc_coord_t lat, olc_coord_t lon, size_t length, char *buf, size_t bufsize);
Indenting needs fixing.  I suggest running our astyle tool over this.

2020-09-14 08:37 UTC, peterbarker commented on libraries/AP_OLC/AP_OLC.h
> +#include <AP_Common/AP_Common.h>
What are we using out of this?

2020-09-14 08:37 UTC, peterbarker commented on libraries/AP_OLC/AP_OLC.h
> +static int olc_encode(olc_coord_t lat, olc_coord_t lon, size_t length, char *buf, size_t bufsize);
External interfaces should probably be using type of what we expect.  We'll just be throwing `int32_t`s in...

2020-09-14 08:37 UTC, peterbarker commented on libraries/AP_OSD/AP_OSD.h
> +
New whitespace?

2020-09-14 08:37 UTC, peterbarker commented on libraries/AP_OSD/AP_OSD_Screen.cpp
> +    // @Description: Displays total flight time
This parameter description needs some help...

2020-09-14 08:52 UTC, giacomo892 commented on libraries/AP_OSD/AP_OSD.h
> +
Actually there is none added

2020-09-14 10:02 UTC, Gone4Dirt commented
Just to add to my original question.  I don't understand what the use case for displaying position on OSD is.  whether is it lat/lng or OLC.  I just don't see how it is useful to see position as a number/code on an OSD.  Happy to be corrected, I just feel that it needs to a have reasonable usecase, and its not clear to me what that is.  So could you explain the use case please?

2020-09-14 10:21 UTC, giacomo892 commented
Hi @peterbarker thanks for your review. I should have addressed your concerns. Let me know what do you think.

Regarding the usefulness of this PR (so I can reply to @Gone4Dirt too) I think it is nice to have. Won't add any precision but it allows to display the position of the machine on the OSD using just less space (half of it?) than the LAT/LON combo. 
I think having the position displayed on the OSD is always useful as it gives another way to find the machine in case of an unfortunate crash.

2020-09-15 06:56 UTC, peterbarker commented
Marked this for DevCallEU, @andyp1per

2020-09-15 07:11 UTC, andyp1per commented
Seems like a lot of code for a feature I don't think I would use. Is this coding quite common? I agree that printing lat/lng is mostly useless - unless you crash a long way away.

2020-09-16 07:10 UTC, tridge requested changes
please find flash cost, and look at checking for HAL_MINIMIZE_FEATURES, cleanup namespace usage

2020-09-16 07:10 UTC, tridge commented on libraries/AP_OLC/AP_OLC.cpp
> +char alphabet[] = "23456789CFGHJMPQRVWX";
const and not global

2020-09-16 07:10 UTC, tridge commented on libraries/AP_OLC/AP_OLC.h
> +typedef int32_t olc_coord_t;
just use int32_t, like we use elsewhere

2020-09-16 07:10 UTC, tridge commented on libraries/AP_OLC/AP_OLC.h
> +    static olc_coord_t adjust_latitude(olc_coord_t lat, size_t code_len);
use int32_t

2020-09-16 08:40 UTC, giacomo892 commented
@tridge I should have addressed your review.
The flash usage is 816bytes on F405-STD comparing this branch with current master

2020-09-23 07:12 UTC, tridge requested changes

2020-09-23 07:12 UTC, tridge commented on libraries/AP_OLC/AP_OLC.h
> +typedef int32_t int32_t;
odd typedef ....

2020-09-23 07:12 UTC, tridge commented on libraries/AP_OLC/AP_OLC.h
> +
add in this:
```
#ifndef HAL_PLUSCODE_ENABLE
#define HAL_PLUSCODE_ENABLE !HAL_MINIMIZE_FEATURES && BOARD_FLASH_SIZE > 1024
#endif
```
then use in AP_OSD and the class definition

2020-09-23 07:12 UTC, tridge commented on libraries/AP_OLC/AP_OLC.h
> +static constexpr int32_t OLC_DEG_MULTIPLIER = 10000000; // 1e7
move that const to inside the AP_OLC class

2020-09-23 07:12 UTC, tridge commented on libraries/AP_OSD/AP_OSD_Screen.cpp
> +    AP_GPS & gps = AP::gps();
use
#if HAL_PLUSCODE_ENABLE for this

2020-09-23 07:12 UTC, andyp1per requested changes

2020-09-23 07:12 UTC, andyp1per commented on libraries/AP_OLC/AP_OLC.cpp
> +    constexpr uint8_t SEPARATOR_CHAR = '+';
I think these should be in the class

2020-09-23 07:12 UTC, andyp1per commented on libraries/AP_OLC/AP_OLC.cpp
> +    int32_t initial_exponent = floorf(logf(2 * (LON_MAX / OLC_DEG_MULTIPLIER)) / logf(ENCODING_BASE));
these should be const

2020-09-23 07:12 UTC, andyp1per commented on libraries/AP_OLC/AP_OLC.cpp
> +    if (lat < -LAT_MAX) {
use constrain_int32_t here

2020-09-30 08:21 UTC, tridge approved these changes

2020-09-30 08:27 UTC, peterbarker commented on libraries/AP_OLC/AP_OLC.cpp
> +float AP_OLC::compute_precision_for_length(int length)
This should be unsigned; there are other cases of non-stdint type in here, too.

2020-09-30 08:28 UTC, tridge approved these changes

2020-09-30 08:29 UTC, peterbarker approved these changes

2020-09-30 23:40 UTC, merged

2020-09-30 23:40 UTC, peterbarker commented
Merged, thanks!

2020-10-01 17:11 UTC, amilcarlucas commented
How do I set the HAL_PLUSCODE_ENABLE to false? is it a waf command line option?

2020-10-01 17:27 UTC, giacomo892 commented
It's off by default on boards with 1MB flash. To enable it just set HAL_PLUSCODE_ENABLE 1 in the hwdef