GCS_MAVLink: avoid catching up on sending messages when sending disrupted
ArduPilot/ardupilot pull request #15146
Opened 2020-08-24 03:17 UTC by peterbarker

The code here was never meant to maintain an "average" streamrate.  It
was designed so that we would maintain a consistent clock in the face of
minor scheduling anomalies (like an EKF fusion step).

The way this is written, however, makes us spit out a message for each
of the intervals we missed - clearly not intended behaviour.

This was tested by inserting the following code:

```
 void GCS_MAVLINK::update_send()
 {
+    const uint32_t xnow = AP_HAL::millis();
+    if (xnow > 10000 &&
+        xnow < 20000) {
+        return;
+    }
+
```

After fix:
![image](https://user-images.githubusercontent.com/7077857/91000140-d7eec680-e60b-11ea-8bbf-2b16a1a826e7.png)

Before fix:
![image](https://user-images.githubusercontent.com/7077857/91000230-09679200-e60c-11ea-90df-1c331ec32d73.png)

Zooming in:
![image](https://user-images.githubusercontent.com/7077857/91000267-1be1cb80-e60c-11ea-82e1-ef7ce7f0064f.png)

2020-09-15 00:36 UTC, tridge requested changes

2020-09-15 00:36 UTC, tridge commented on libraries/GCS_MAVLink/GCS_Common.cpp
> +                if (start16 - deferred_message[next].last_sent_ms > interval_ms) {
I'm pretty sure we need a cast for uint16_t subtraction

2020-09-15 00:39 UTC, tridge commented on libraries/GCS_MAVLink/GCS_Common.cpp
> +                if (start16 - deferred_message_bucket[sending_bucket_id].last_sent_ms > interval_ms) {
same here

2020-09-15 10:33 UTC, tridge commented
This is not working correctly. It is achieving the average rate, but it is sending messages much too close together
I have setup RAW_IMU for 50Hz, and see this from mavproxy messagerate status:
RAW_IMU: 45.0/s
but if I graph the instantaneous rate I see:
![image](https://user-images.githubusercontent.com/831867/93200055-a2fd0c00-f792-11ea-8917-ae90d34af9ea.png)
some RAW_IMU msgs are being sent just 40usec after the previous one

2020-09-15 10:45 UTC, tridge commented
if instead we use the much simpler method of:
```
                deferred_message_bucket[sending_bucket_id].last_sent_ms = start16;
```
then I see this:
RAW_IMU: 41.2/s
![image](https://user-images.githubusercontent.com/831867/93200546-3cc4b900-f793-11ea-8479-c5847468d0d9.png)
which is actually a lot more useful!

2020-09-25 05:39 UTC, tridge commented
@peterbarker where are we at with this? Even if it's not perfect I think we should merge soon then improve later. Right now high rate msgs for tuning and control are not really useful, and this at least makes them more usable

2020-09-26 08:27 UTC, peterbarker commented
What happens when you try MAVProxy's default 4Hz with this patch?

2020-10-12 02:47 UTC, tridge commented
> What happens when you try MAVProxy's default 4Hz with this patch?

it's fine at 4Hz

2020-10-12 02:48 UTC, tridge approved these changes

2020-10-12 02:48 UTC, merged

2020-10-12 02:48 UTC, tridge commented
merged, it's not perfect, but a big improvement