AP_Scripting: update loging to file example to work on real hardware
ArduPilot/ardupilot pull request #15234
Opened 2020-09-04 11:41 UTC by IamPete1

Fixes #14617

Lua writing to a file example now works on real hardware, its seems real hardware is more fussy bout leaving the file open than SITL. Tested on Cube Orange.

2020-09-04 16:52 UTC, WickedShell commented
What happens if we leave the file open? We should be able to do that, and if we can't that actually sounds like a bug in the HAL

2020-09-04 18:08 UTC, IamPete1 commented
@WickedShell didn't occur to me that it might be a hal bug. It currently creates the file but fails to put anything in it. This change to open, write then close seems to fix. Both old and new work in SITL. Maybe related to leaving the file open between calls to the script?

If we can fix the hal then the current script is nicer.

2020-09-11 23:16 UTC, IamPete1 commented
@

2020-09-11 23:19 UTC, IamPete1 commented
@WickedShell I wonder if this SD issue is the same one that is causing the REPL to be broken on real hardware but working in SITL

2020-09-11 23:34 UTC, WickedShell commented
@IamPete1 so REPL works on real hardware, although the old version of MP I was using to test with it doesn't, so I'm actually pretty sure this is a mission planner breakage (or a HAL one). I have a CubeOrange on the bench here, starting a REPL from MP just seems to hang, but if I then restart just MP (not the cube), and FTP in I can see the REPL folder with the out file is there, if I upload an in file with some REPL input it processes it, and writes the outfile back for me. These uploads/reads were done with the FTP client, so it looks like it's an error with the client more then anything else.

2020-09-23 19:46 UTC, Notorious811 commented
Yup, i have confirmed too by testing this PR on pixhawk 2.4.8, this PR will fix this issue #14617, thanks

2020-09-23 19:59 UTC, Notorious811 commented
> What happens if we leave the file open? We should be able to do that, and if we can't that actually sounds like a bug in the HAL
@IamPete1 @WickedShell 
I think i recently faced similar issue with AP_Filesystem too, but not sure, have to check it again, when i kept somewhat longer delay before writing to file using AP_Filesystem API on real hardware, then example program seems to hang

2020-10-17 09:54 UTC, davidbuzz commented
this PR appears to be a reasonable work-around to as-yet-unresolved lower-level problem, but it also harmless, so i recommend it goes in until we have a better solution.

2020-10-18 16:40 UTC, Notorious811 commented
i am not sure about it but does watchdog has anything to do related with leaving the file open when using lua scripting

2020-10-19 23:44 UTC, tridge requested changes
i'd like us to find and fix the real bug

2020-11-11 00:54 UTC, tridge commented
fixed properly in #15769

2020-11-11 00:54 UTC, closed without merging