autotest: retrieve sim_time from lots of different messages
ArduPilot/ardupilot pull request #15282
Opened 2020-09-08 23:31 UTC by peterbarker

Based on tridge's work here: https://github.com/ArduPilot/ardupilot/pull/15281/files

2020-09-15 15:01 UTC, khancyr requested changes
doesn't work as our current pattern is 
````
        tstart = self.get_sim_time()
        while True:
            self.wait_heartbeat()
            tdelta = self.get_sim_time_cached() - tstart
````
so we never have update ... unless we put a hook somewhere to always update self.mav.autotest_uptime for each message with time info ...

2021-03-16 17:10 UTC, khancyr approved these changes
@peterbarker that seems good ? any thing that should be tested ?

2021-03-16 17:12 UTC, khancyr commented on Tools/autotest/common.py
> +        if 'usec' in msg.__dict__:
shouldn't we check self.mav.sysid here too ?

2021-03-27 02:47 UTC, peterbarker commented
It turns out that it is a far better idea to poll the ardupilot instance for the relevant message than to get timestamps from many messages; you can get a response to your poll in a very, very short period of time and not have to wait for the streams to kick in and send you a relevant message.

Making that change, however, shows up many issues - so that's something to do another day.

2021-03-27 02:47 UTC, closed without merging