AC_Circle: add Circle options
ArduPilot/ardupilot pull request #15286
Opened 2020-09-09 08:22 UTC by IamPete1

This adds some options to Circle mode. There is a change in behavior in that now the rate and radius will be re-set to the values from the parms when you enter circle mode. The current behavior is to change the params with RC override. 

This also changes the name of CIRCLE_CONTROL to a CIRCLE_OPTIONS bitmask. 

This then adds 3 options:

- Face in the direction of travel, copter will face along the tangent of the circle.

- Init at center, the copter will put the center of the circle at the current location rather than one radius ahead.

- Constant speed. The copter will change its rate automatically as the radius is changed to maintain a constant ground speed.

2020-09-11 19:49 UTC, IamPete1 commented
rebased to try and get passed failing sub test

2020-09-15 14:55 UTC, IamPete1 commented
Backed out the constant speed change, there is a strange interaction with Auto loiter turns waypoints.

Turns out setting the radius for loiter turns in auto will also change you circle radius the next time you circle. To fix that this was turning in to a massive patch.

2020-09-30 07:58 UTC, tridge requested changes

2020-09-30 07:58 UTC, tridge commented on libraries/AC_WPNav/AC_Circle.h
> +    enum CircleOptions {
enum class

2020-09-30 07:58 UTC, merged