Use cleaner conditional compilation for the various OSD options
ArduPilot/ardupilot pull request #15304
Opened 2020-09-10 20:52 UTC by andyp1per

Tested on CubeOrange with and w/o OSD, KakuteF7 and KakuteF7Mini
All ended up with the symbols I expected

2020-09-10 22:01 UTC, tridge commented
much nicer, thanks!

2020-09-12 20:59 UTC, andyp1per commented
Using this to setup appropriate defaults for different vehicles

2020-09-12 22:05 UTC, tridge commented
build error on MatekF405-Wing:
```
[1402/2260] Compiling libraries/AP_RCTelemetry/AP_RCTelemetry.cpp
../../libraries/AP_OSD/AP_OSD_ParamScreen.cpp:286:98: error: conflicting declaration 'const AP_OSD_ParamSetting AP_OSD_ParamScreen::param_defaults [2][9]'
 const AP_OSD_ParamSetting AP_OSD_ParamScreen::param_defaults[AP_OSD_NUM_PARAM_SCREENS][NUM_PARAMS] = {
```

2020-09-13 07:48 UTC, andyp1per commented
Fun fact - moving to the compact initializer has saved 100 bytes of flash even though the number of defaults has increased.

2020-09-13 23:29 UTC, peterbarker requested changes
This is much nicer :-)

2020-09-13 23:29 UTC, peterbarker commented on libraries/AP_OSD/AP_OSD.h
> +    AP_OSD_ParamScreen param_screen[AP_OSD_NUM_PARAM_SCREENS] = { 0, 1 };
```suggestion
    AP_OSD_ParamScreen param_screen[AP_OSD_NUM_PARAM_SCREENS] { 0, 1 };
```

2020-09-13 23:29 UTC, peterbarker commented on libraries/AP_OSD/AP_OSD_ParamScreen.cpp
> +static const AP_OSD_ParamSetting::Initializer PARAM_DEFAULTS[AP_OSD_NUM_PARAM_SCREENS][AP_OSD_ParamScreen::NUM_PARAMS] = {
```suggestion
static const AP_OSD_ParamSetting::Initializer PARAM_DEFAULTS[AP_OSD_NUM_PARAM_SCREENS][AP_OSD_ParamScreen::NUM_PARAMS] {
```

(hopefully ;-) )

2020-09-16 08:11 UTC, tridge approved these changes

2020-09-16 08:11 UTC, peterbarker approved these changes

2020-09-16 08:11 UTC, merged