AC_Avoid, AC_Fence: Hide params with enable flags
ArduPilot/ardupilot pull request #15305
Opened 2020-09-10 22:32 UTC by IamPete1

I assumed fence was enabled because I could see all the params, it wasn't, this fixes.

2020-09-10 23:23 UTC, rmackay9 commented
I'm totally happy with the avoidance change but I think we should leave fence out of it because it's quite commonly used.  At least this was the decision we made a couple of years ago when we last discussed hiding fence's parameters.

2020-09-11 04:58 UTC, rmackay9 requested changes
Let's remove the change to AC_Fence..

2020-09-11 07:13 UTC, IamPete1 commented
I think its actually clearer for users if the params are hidden, it falls in line will the majority of the other librarys. As I say I was confused because I saw all the params so I assumed It was enabled.

Ironically the avoidance change actually does nothing for most people as the default is for it to be enabled.

2020-09-11 07:46 UTC, amilcarlucas approved these changes
YES!!! Enable Flags as much as possible!!!

2020-09-11 23:18 UTC, rmackay9 commented
No, we will receive huge numbers of support calls from users asking why the MP fence fields are greyed out.

2020-09-13 10:35 UTC, IamPete1 commented
I wasn't aware of the fence tab, I found it

![image](https://user-images.githubusercontent.com/33176108/93015865-d2eeb880-f5b4-11ea-8684-4b23771ccbc1.png)

Yeah, they are grayed out, the enable button its quite clear tho. It looks like  mission planner actually trys to go and fetch the prams when you hit enable, but its failing for me. I guess if we could get that working then there is no disadvantage to this.

In the mean time I have dropped the fence change.

2020-09-13 23:54 UTC, merged

2020-09-13 23:54 UTC, rmackay9 commented
Merged, thanks!