Copter/Sub: replace use print with printf and change the position of new line
ArduPilot/ardupilot pull request #15318
Opened 2020-09-12 06:41 UTC by tatsuy

This is NFC, but I will fix it because I see it every time I started SITL.

Copter
![image](https://user-images.githubusercontent.com/16643069/92988966-7a171580-f50b-11ea-9128-4e11fb9db06b.png)

Sub
![image](https://user-images.githubusercontent.com/16643069/92988967-7c796f80-f50b-11ea-948b-b4b8c24aedd5.png)

In Copter, "*" is here. and this is also displayed in Rover. I will leave it because I couldn't decide if it was necessary.
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_InertialSensor/AP_InertialSensor.cpp#L1233

By the way, send_text is used in the other three vehicles. I think it's okay to unify to send_text.

AntennaTracker
https://github.com/ArduPilot/ardupilot/blob/master/AntennaTracker/system.cpp#L82
> gcs().send_text(MAV_SEVERITY_INFO,"Ready to track");

ArduPlane
https://github.com/ArduPilot/ardupilot/blob/master/ArduPlane/system.cpp#L214
> gcs().send_text(MAV_SEVERITY_INFO,"Ground start complete");

Rover
https://github.com/ArduPilot/ardupilot/blob/master/Rover/system.cpp#L170
> gcs().send_text(MAV_SEVERITY_INFO, "Ready to drive");

2020-09-13 02:07 UTC, peterbarker approved these changes
I like it.

I'm a bit worried by the prospect of people pattern-matching this.  But... I also don't think we need to hold up for that.

2020-09-14 13:14 UTC, tatsuy commented
I think there is no problem because I haven't changed the string in this PR.

2020-09-14 22:11 UTC, peterbarker commented
@tatsuy line-endings... people might be matching on the line endings...

2020-09-14 23:13 UTC, rmackay9 commented
I think we mostly put the line feed at the end everywhere else so it makes sense to move them to the end.

2020-09-14 23:22 UTC, tridge requested changes

2020-09-14 23:22 UTC, tridge commented on ArduCopter/system.cpp
> -    hal.console->printf("\nReady to FLY ");
i think we should make this a send_text with "ArduPilot Ready" in libraries/AP_Vehicle and remove the printf from all vehicles

2020-09-14 23:27 UTC, rmackay9 commented
As discussed on the dev call, I think the suggestion from Tridge is a good idea but if it's too difficult I'm happy to merge the Copter change as-is because it's not dangerous and is slightly helpful.

2020-09-15 00:30 UTC, tatsuy commented
Thank you for the review!
It's a better idea than mine.
I moved the message to AP_Vehicle.
The timing of displaying it is a bit changed but I think it is more suitable.

I tested this in SITL with all vehicles.

Tracker
```
INITIALISING> Mode INITIALISING
APM: AntennaTracker V1.2.0-dev (b34bdfda)
APM: 3d94fc2306a24139bb795d3de9ba3d0c
Received 785 parameters (ftp)
APM: Barometer 1 calibration complete
APM: ArduPilot Ready
ARMED
AUTO> Mode AUTO
Arming checks disabled
fence breach
APM: EKF2 IMU0 initial yaw alignment complete
APM: EKF2 IMU1 initial yaw alignment complete
```

Copter
```
STABILIZE> Mode STABILIZE
APM: Barometer 1 calibration complete
Init Gyro**APM: ArduCopter V4.1.0-dev (b34bdfda)
APM: 3d94fc2306a24139bb795d3de9ba3d0c
APM: Frame: QUAD
*Received 1154 parameters (ftp)

APM: ArduPilot Ready
APM: SaveWaypoint LOW
APM: EKF2 IMU0 initial yaw alignment complete
APM: EKF2 IMU1 initial yaw alignment complete
```

Plane
```
INITIALISING> Mode INITIALISING
APM: ArduPlane V4.1.0dev (b34bdfda)
APM: 3d94fc2306a24139bb795d3de9ba3d0c
APM: Barometer 1 calibration complete
APM: Airspeed 1 calibration started
APM: ArduPilot Ready
MANUAL> APM: Throttle failsafe off
Received 1199 parameters (ftp)
APM: Airspeed 1 calibrated
Mode MANUAL
APM: GPS 1: detected as u-blox at 230400 baud
APM: EKF2 IMU0 initial yaw alignment complete
APM: EKF2 IMU1 initial yaw alignment complete
```

Sub
```
MANUAL> Mode MANUAL
APM: Barometer 1 calibration complete
APM: ArduPilot Ready
APM: ArduSub V4.1.0dev (b34bdfda)
APM: 3d94fc2306a24139bb795d3de9ba3d0c
Received 1064 parameters (ftp)
Flight battery 100 percent
APM: EKF2 IMU0 initial yaw alignment complete
APM: EKF2 IMU1 initial yaw alignment complete
```

Rover
```
INITIALISING> Mode INITIALISING
APM: ArduRover V4.1.0-dev (b34bdfda)
APM: 3d94fc2306a24139bb795d3de9ba3d0c
Received 1067 parameters (ftp)
APM: Barometer 1 calibration complete
APM: <startup_ground> Ground start
APM: Beginning INS calibration. Do not move vehicle
Init Gyro***
APM: INS: alloc 6144 bytes for ISB (free=131072)
APM: ArduPilot Ready
MANUAL> Mode MANUAL
APM: EKF2 IMU0 initial yaw alignment complete
APM: EKF2 IMU1 initial yaw alignment complete
```

2020-09-15 01:00 UTC, rmackay9 commented
This looks good to me but I'll leave it to @peterbarker and/or @tridge to make the final decision/merge.

2020-09-15 04:41 UTC, peterbarker requested changes
It's definitely going to break https://github.com/ardupilot/ardupilot/blob/master/Tools/scripts/runfliptest.py#L40 :-)

2020-09-15 04:41 UTC, peterbarker commented
Should also nudge @jaxxzer on this.

2020-09-15 05:16 UTC, tatsuy commented
@peterbarker 
Thank you for your checking.
I also found this.
https://github.com/ArduPilot/ardupilot/blob/master/Tools/LogAnalyzer/DataflashLog.py#L672

I will test these tools with changing the string.

2020-09-16 13:51 UTC, tatsuy commented
@peterbarker 
Are these two files still in use?
  Tools/scripts/runfliptest.py
  Tools/scripts/runplanetest.py

If it is used for autotest, I would like to move it to Tools/autotest folder and replace mavproxy.expect with the wait_statustext function.
We already have a test for Flip mode in Tools/autotest/arducopter.py, so I think we don't need it.

About runplanetest.py, it hasn't worked because the message is called by send_text.
https://github.com/ArduPilot/ardupilot/blob/master/Tools/scripts/runplanetest.py#L40

2020-09-17 10:47 UTC, peterbarker commented
On Wed, 16 Sep 2020, Tatsuya Yamaguchi wrote:

> @peterbarker
> Are these two files still in use?
> Tools/scripts/runfliptest.py
> Tools/scripts/runplanetest.py

Yes.  Those are tridge's toys, unrelated to autotest :-)

Sorry, I don't think they can be moved - but they will almost certainly 
bitrot by accident.  Glad we caught it this time!

2020-09-18 00:36 UTC, tatsuy commented
Should I survive these files?
I can only think of copying the wait_statustext function to these.
Could you give me some advice for merging?

2020-09-18 03:58 UTC, peterbarker commented
On Thu, 17 Sep 2020, Tatsuya Yamaguchi wrote:

> I can only think of copying the wait_statustext function to these.

Probably just update the string in these files

2020-09-18 14:30 UTC, tatsuy commented
@peterbarker Thank you!
I've realized that I should add APM :.

2020-09-19 03:09 UTC, peterbarker commented
> @peterbarker Thank you!
> I've realized that I should add APM :.

No, no you shouldn't :-)

We're trying to get away from `APM` as much as possible as it continues to tie us to outdated, unsupported and now-vexing hardware.

MAVProxy's actually the main offender ATM - we need to change out from `APM` to something else, but need something really short.

Going from `APM: the vehicle wants to be on fire` => `ArduPilot: the vehicle wants to be on fire` is bad (too long, flightstack-specific).

Going from `APM: the fire wants to be on-vehicle` => `AutoPilot: the fire wants to be on-vehicle` is kind of tool long and doesn't scan all that well.

Perhaps we could say, `Vehicle:`?

Anyways.  That's a digression.  `APM` shouldn't happen.

2020-09-19 12:56 UTC, tatsuy commented
OK. How about `AP:` ?

2020-09-19 23:41 UTC, peterbarker commented
@tatsuy The `APM:` is put there by MAVProxy.  You don't emit it as part of the string, and the expect strings won't need it.

2020-09-20 00:37 UTC, tatsuy commented
I misunderstood that an exact match including `APM:` was necessary.
I am sorry for wasting your time.
I've tested that both scripts work fine.

2020-09-21 02:07 UTC, tridge approved these changes

2020-09-21 23:52 UTC, merged