Fix XCode 11.7 clang errors
ArduPilot/ardupilot pull request #15349
Opened 2020-09-15 15:56 UTC by andyp1per

Clang got more picky

2020-09-15 21:08 UTC, khancyr approved these changes
good find ! 
the issue with the const on the ringbuffer is weird ... I wonder why it doesn't fail to compile with GCC...

2020-09-15 21:08 UTC, khancyr commented on libraries/GCS_MAVLink/GCS_Common.cpp
> +    if (uint32_t(_base_mode) & MAV_MODE_FLAG_CUSTOM_MODE_ENABLED) {
nitpick : uint16_t should be enough !

2020-09-15 23:09 UTC, peterbarker commented
@WickedShell are we still really, really trying to avoid changing the LUA source?

2020-09-16 06:16 UTC, andyp1per commented
@peterbarker it's either change the source or change the compile options. -Werror has to go if we don't want to change the source.

2020-09-16 08:35 UTC, tridge approved these changes

2020-09-16 08:36 UTC, tridge commented
looks fine to me, but we will see what @WickedShell thinks

2020-09-17 23:34 UTC, peterbarker commented
@WickedShell would prefer we modify the flags we use when compiling the LUA source. 

Precedent is here, apparently: https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_GPS/wscript

 @andyp1per are you up to doing those modifications?

2020-09-18 08:11 UTC, andyp1per commented
Mods done, warnings squashed

2020-09-18 20:01 UTC, andyp1per commented
@peterbarker @tridge this works but the CFLAGS leak into the rest of the build. Fixing this is beyond me I am afraid.

2020-09-19 17:27 UTC, WickedShell approved these changes
I'm fine with the scripting changes as this at least doesn't make the existing conflict situation any worse. Ideally we take the time in the future to do a real wscript for the lua/src folder, but till then this works.

2020-09-21 22:56 UTC, tridge requested changes

2020-09-21 22:56 UTC, tridge commented on libraries/AP_Scripting/lua_boxed_numerics.cpp
> +        if (success && v >= 0 && v <= float(UINT32_MAX)) {
we need to check this really works, especially for values close to UINT32_MAX. Can you please check that coercing UINT32_MAX doesn't produce an error?

2020-09-21 23:36 UTC, tridge commented on libraries/AP_Scripting/lua_boxed_numerics.cpp
> +        if (success && v >= 0 && v <= float(UINT32_MAX)) {
@WickedShell says he is happy with this

2020-09-21 23:37 UTC, merged