Plane: Use AHRS for groundspeed/groundcourse
ArduPilot/ardupilot pull request #15357
Opened 2020-09-16 06:22 UTC by magicrub

Use AHRS for groundspeed/groundcourse instead of GPS

2020-10-31 09:31 UTC, khancyr approved these changes
This looks good.
But it induce a breaking change as now if you don't have valid gps speed estimation you can still use the airspeed.
In case both airspeed and gps speed aren't availabe, the behavior isn't changed as ahrs will return (0,0) vector and there are only speed checks !

2020-10-31 09:31 UTC, khancyr commented on ArduPlane/servos.cpp
> +            has_ground_movement) { // definite gps movement
you could remove gps here in the comment

2020-10-31 09:31 UTC, khancyr commented on libraries/AP_AHRS/AP_AHRS.h
> +        return wrap_360(degrees(groundspeed_vector().angle()));
what would be the difference between this and using the yaw_sensor like in other place ? (like in https://github.com/ArduPilot/ardupilot/blob/master/libraries/GCS_MAVLink/GCS_Common.cpp#L2631)

2020-11-03 00:32 UTC, rmackay9 commented
@khancyr in general I think for the core devs we should let them add the devCallTopic topic when they're ready to discuss in the weekly dev call.

2020-11-03 00:37 UTC, tridge requested changes
I'd like to see evidence of each of the changes having been thought through carefully for safety considerations

2020-11-03 00:41 UTC, magicrub commented
I thought I flew with this change with an auto-takeoff without GPS.. but the autotakeoff code clearly requires a 3D lock so there must have been something different about my test flight. I'll check the hash in my log and report back.

@tridge has a particular concern about using ahrs instead of gps for takeoff.

2020-11-19 04:33 UTC, magicrub commented
This PR is probably not worth the trouble to pursue. I was trying to clean things up but it got complicated so I'll just close.

2020-11-19 04:33 UTC, closed without merging