AP_RCProtocol: don't include CRSF header / remove init code for CRSF
ArduPilot/ardupilot pull request #15402
Opened 2020-09-22 07:24 UTC by peterbarker

We don't build CRSF on iofirmware, so don't pull in the header file and
don't include the rather-specific serial port initialisation.

I do not have CRSF hardware to test this on.

2020-09-22 09:29 UTC, andyp1per requested changes

2020-09-22 09:29 UTC, andyp1per commented on libraries/AP_RCProtocol/AP_RCProtocol.cpp
> +#if !APM_BUILD_TYPE(APM_BUILD_iofirmware)
I think this probably means you need to change the phase check below to eliminate CONFIG_420000_8N1 on IOMCU

2020-09-22 11:09 UTC, peterbarker commented
On Tue, 22 Sep 2020, Andy Piper wrote:

> > @@ -243,13 +243,15 @@ void AP_RCProtocol::check_added_uart(void)
>              added.uart->set_options(added.uart->get_options() | AP_HAL::UARTDriver::OPTION_RXINV);
>              break;
>          case CONFIG_420000_8N1:
> +#if !APM_BUILD_TYPE(APM_BUILD_iofirmware)
> 
> I think this probably means you need to change the phase check below to eliminate CONFIG_420000_8N1 on IOMCU

ARGH!  This is why we have "LAST" things in enumerations....

Or iterate over arrays....

This just got way, way ickier.

2020-11-24 11:14 UTC, peterbarker commented
I might just pretend this one didn't happen ;-)

2020-11-24 11:14 UTC, closed without merging