This allows user to set the surface positions for the aeroterminate
ArduPilot/ardupilot pull request #15413
Opened 2020-09-23 17:46 UTC by QuPsi

Values can vary from -100% to 100% deflection.

2020-09-24 00:42 UTC, peterbarker commented
What's the use case here?

2020-09-24 00:43 UTC, peterbarker commented
I've rebased this branch as it was wedged in CI.

2020-09-24 03:04 UTC, magicrub requested changes

2020-09-24 03:04 UTC, magicrub commented on libraries/AP_AdvancedFailsafe/AP_AdvancedFailsafe.cpp
> +    AP_GROUPINFO("TERM_POS_AIL",   23, AP_AdvancedFailsafe, _term_pos_ail,    100),
index should be 21.
Units should be ```// @Units: %```
Add ```// @Range: -100 100```
Description should mention that 0 means neutral deflection and could also mention the default
Display name would be better to say ``Aeroterminate Position for Aileron'' so Aileron is at the end so the param names and descriptions only have that one attribute different on the end.

2020-09-24 03:04 UTC, magicrub commented on libraries/AP_AdvancedFailsafe/AP_AdvancedFailsafe.h
> +    AP_Int8  _term_pos_ail;
the other terminate variables start with ``_terminate_`` so please follow that pattern.

2020-09-24 03:04 UTC, magicrub commented on libraries/AP_AdvancedFailsafe/AP_AdvancedFailsafe.cpp
> +    AP_GROUPINFO("TERM_POS_AIL",   23, AP_AdvancedFailsafe, _term_pos_ail,    100),
Also, the word "Aeroterminate" is new. Let's keep the vocabulary consistent and name it ```Terminate Aileron Position```

2020-09-24 03:33 UTC, tridge commented
we need some good justification for why these parameters are needed

2020-09-24 07:09 UTC, auturgy commented
The params should be hidden under AFS_ENABLE, so not visible to most users.


> On 24 Sep 2020, at 1:34 pm, Andrew Tridgell <notifications@github.com> wrote:
> 
> ﻿
> we need some good justification for why these parameters are needed
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-09-25 19:35 UTC, QuPsi commented
In some aircraft, because of channel reversal the aircraft will pitch up instead of down during aeroterminate. This allows the user to set the positions for the aeroterminate. I am reviewing the other comments and will do my best incorporate them.

2020-09-25 19:51 UTC, QuPsi commented
> The params should be hidden under AFS_ENABLE, so not visible to most users.

How do I accomplish this?

2020-09-25 21:15 UTC, magicrub commented
> > The params should be hidden under AFS_ENABLE, so not visible to most users.
> 
> How do I accomplish this?

I think @auturgy was just telling @tridge that this param will be hidden when ADFS_ENABLE=0 via AP_PARAM_FLAG_ENABLE so this new param won't even show up for most users

2020-09-28 20:39 UTC, closed without merging

2020-09-28 20:45 UTC, QuPsi commented
Continued below:

https://github.com/ArduPilot/ardupilot/pull/15458