Fix H7 FDCAN driver's filter configuration and other minor fixes
ArduPilot/ardupilot pull request #15438
Opened 2020-09-26 20:20 UTC by bugobliterator

Tested with and without SLCAN on both CubeBlack and CubeOrange.

The failure was happening when we were trying to put H7 FDCAN in init mode, this was a truly bizarre issue, and I wasn't able to find out why that was happening. As a workaround for cases where we enable filters I don't finish initialisation until configure Filter is called. That seems to fix the issue, and also tested that filter is working.

But still there is an unknown as to why we can't put FDCAN in init mode the second time.

2020-09-26 20:25 UTC, tridge requested changes

2020-09-26 20:25 UTC, tridge commented on Tools/ardupilotwaf/boards.py
> -            '-Wframe-larger-than=1024',
we don't want to remove this globally or we will end up with large stack fns and get stack overflows

2020-09-26 20:25 UTC, tridge commented on libraries/AP_Compass/CompassCalibrator.cpp
> +    // correct sample
what is this doing in a CAN PR?

2020-09-26 20:25 UTC, bugobliterator commented on Tools/ardupilotwaf/boards.py
> -            '-Wframe-larger-than=1024',
we already have another flag in this array

2020-09-26 20:25 UTC, bugobliterator commented on libraries/AP_Compass/CompassCalibrator.cpp
> +    // correct sample
by mistake, already removed

2020-10-07 08:09 UTC, tridge requested changes
can be merged after trivial newline fixed

2020-10-07 08:09 UTC, tridge commented on libraries/AP_HAL_ChibiOS/hwdef/CubeBlack-periph/hwdef.dat
> +define HAL_CAN_DRIVER_DEFAULT 1
missing newline

2020-10-07 22:31 UTC, merged

2020-10-07 22:31 UTC, peterbarker commented
Merged, thanks!