AP_UAVCAN - Allow sending negative values to ESCs over UAVCAN
ArduPilot/ardupilot pull request #15459
Opened 2020-09-28 22:51 UTC by jmachuca77

This is a very rough draft to allow sending negative values over UAVCAN to allow reverse. This is needed in skid steer rovers to allow in place turning and reverse. 

This PR removes a constrain to only send positive values, and scales the output from 1000 (full reverse), 1500 (stop), 2000 (full forward), to a value between -cmd_max to +cmd_max to the ESC.

This was tested on a VESC with very good results.

2020-09-28 22:51 UTC, jmachuca77 commented
This still needs lots of changes it is not meant to be merged as is, but is more meant as a starting point for discussion.

2020-09-29 01:36 UTC, tridge requested changes

2020-09-29 01:36 UTC, tridge commented on libraries/AP_UAVCAN/AP_UAVCAN.cpp
> +                // scaled = constrain_float(scaled, 0, cmd_max);
no commented out code please

2020-09-29 01:36 UTC, tridge commented on libraries/AP_UAVCAN/AP_UAVCAN.cpp
> +                float scaled = cmd_max * (hal.rcout->scale_esc_to_unity(_SRV_conf[i].pulse));
this must be a parameter

2020-09-29 01:50 UTC, rmackay9 commented
Parameter names suggested on the dev call:

- SERVO_REMASK
- SERVO_REVMASK
- SERVO_REVERSEABLE

2021-05-20 07:41 UTC, amilcarlucas commented
FETtec ESCs can also be reversed. It would be good to use global parameters for setting that up.

2024-09-11 11:19 UTC, peterbarker commented
We merged support for reversible ESCs in https://github.com/ArduPilot/ardupilot/pull/24386

Thanks for the attempt, 'though!

2024-09-11 11:19 UTC, closed without merging