AP_Volz_Protocol scaling bugfix
ArduPilot/ardupilot pull request #15451
Opened 2020-09-28 07:34 UTC by lazarovtsvetozar

->Fixed incorrect scaling betwen PWM values and Volz protocol values
->In the scaling formula are hardcoded PWM values min=1000 and max=2000. The idea behind this is to be able to change Volz range, when you use SERVOn_MIN and SERVOn_MAX parameters.

2020-09-28 07:58 UTC, rmackay9 commented on libraries/AP_Volz_Protocol/AP_Volz_Protocol.h
> +#define PWM_POSITION_MIN 					1000
We should probably name these definitions starting with VOLZ_.  So perhaps VOLZ_PWM_MIN and VOLZ_PWM_MAX.  Aleternatively move them to the .cpp file to keep their scope small but I think from a readers point of view it is nice to have all the definitions together.

2020-09-28 07:58 UTC, rmackay9 commented on libraries/AP_Volz_Protocol/AP_Volz_Protocol.cpp
> +
a small white space issue here.  We should remove the blank line under the comment and indent the lines to the same amount.

2020-09-28 08:02 UTC, rmackay9 requested changes
It's great to see that someone is actually using this library so that we know that it's being used.

A few small change requests:

- remove the change to the mavlink submodule
- the commit should be changed to "AP_Volz_Protocol: scaling bugfix".  Please note that I'm talking about the commit itself, not the PR title.
- fixup the whitespace issue
- add VOLZ_ to the front of the new definitions

Also if you could confirm what testing you've done that would be helpful in getting this merged, thanks!

2020-09-28 12:02 UTC, lazarovtsvetozar commented
Tests done so far: 
1. Scaling correction: 
We tested with cube black autopilot connected to Mission Planner. We configured one of the VOLZ Channels (servo3) as a Throttle. Then connected to an oscilloscope with which we translate the message from the autopilot and confirm that the scaling method was working after the change.
2. Hard-coded VOLZ_PWM_MIN / VOLZ_PWM_MAX
In this case when we change the lower value of the SERVO3_MIN = 1200 (for example) the minimum value of the VOLZ_Protocol shifts with 20%, as we have hard coded values of 1000 for minimum scaling factor and 2000 for maximum scaling factor for calculating the Volz limits.

2020-12-06 01:56 UTC, peterbarker commented
@lazarovtsvetozar this one needs a rebase.

I'd do it for you, but it looks like you've PR'd from your master branch rather than a git topic branch.

Could you rebase this, please?

2020-12-07 09:44 UTC, lazarovtsvetozar commented
> 
> 
> @lazarovtsvetozar this one needs a rebase.
> 
> I'd do it for you, but it looks like you've PR'd from your master branch rather than a git topic branch.
> 
> Could you rebase this, please?

Hi Peter (@peterbarker), 
Well I`m kind of new here in git hub and I`m not so well knowledgeable of the terminology of the Git Hub community. Could you please give a hint how to do it, because I thought I was doing the right thing but actually I did it wrong.  Or if you have the time to do it instead of me it would be great ?! 
Thank you in advance, I will appreciate if this change happen in the near future!
Have a nice day !

2020-12-08 00:57 UTC, rmackay9 commented
I think this change is OK although I don't have any servos to test with.

2020-12-08 02:14 UTC, peterbarker commented
@lazarovtsvetozar I've rebased this one for you.

Generally you don't want to make changes to your master branch - you create a git topic branch (based on master) and work on that, push that branch up to github and create a PR from that.  google will help you find more information on topic branches.

git is ridiculously powerful - I suggest you invest some time in getting to know it :-)

2020-12-08 03:59 UTC, rmackay9 approved these changes

2020-12-08 04:03 UTC, merged

2020-12-08 04:03 UTC, peterbarker commented
Merged, thanks @lazarovtsvetozar

2020-12-08 13:20 UTC, lazarovtsvetozar commented
Hi Peter (@peterbarker), 
Let me thank you for the quick respond! I will do my best with git hub as soon as it is possible to me! 
I would like to ask one more question even though it may not be relevant to be ask here but we struggle with [this](https://github.com/ArduPilot/ardupilot/issues/15563) 
Is there by any chance this to be changed ?
Wish you all the best!
Thank you in advanced!