AP_Filesystem: add support for listing @SYS files
ArduPilot/ardupilot pull request #15493
Opened 2020-10-03 21:05 UTC by bugobliterator

2020-10-07 07:53 UTC, tridge requested changes

2020-10-07 07:53 UTC, tridge commented on libraries/AP_Filesystem/AP_Filesystem_Sys.cpp
> +    strcpy(dtracker->curr_file.d_name, sysfs_file_list[dtracker->file_offset].name);
strncpy please

2020-10-07 07:53 UTC, tridge commented on libraries/AP_Filesystem/AP_Filesystem_Sys.cpp
> +    int pos = file_in_sysfs(&pathname[1]);
stdint types

2020-10-07 07:53 UTC, tridge commented on libraries/AP_Filesystem/AP_Filesystem_Sys.cpp
> +    }
should memset 0 for other fields

2020-10-07 07:53 UTC, tridge commented on libraries/AP_Filesystem/AP_Filesystem_Sys.cpp
> +int AP_Filesystem_Sys::file_in_sysfs(const char *fname) {
comments please

2020-10-07 07:53 UTC, tridge commented on libraries/AP_Filesystem/AP_Filesystem_Sys.cpp
> +    dtracker->file_offset = 0;
don't need zero

2020-10-17 09:25 UTC, davidbuzz commented
looks like a good change to me, not sure if this impacts ram usage etc tho.

2020-10-21 07:13 UTC, tridge approved these changes

2020-10-21 07:16 UTC, tridge approved these changes

2020-10-21 07:16 UTC, merged