AP_MATH: Remove isnan check for non-float type
ArduPilot/ardupilot pull request #15577
Opened 2020-10-14 22:32 UTC by patrickelectric

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

2020-10-14 23:08 UTC, peterbarker requested changes
Commit message needs fixing - `AP_Math: only check floating point numbers for isnan`

2020-10-14 23:08 UTC, peterbarker commented on libraries/AP_Math/AP_Math.cpp
> +    if (!std::is_integral<T>::value) {
Why not `is_floating_point`?

2020-10-15 13:53 UTC, patrickelectric commented on libraries/AP_Math/AP_Math.cpp
> +    if (!std::is_integral<T>::value) {
done.

2020-10-15 22:22 UTC, merged

2020-10-15 22:22 UTC, peterbarker commented
Tweaked the commit message (AP_Math vs AP_MATH) and merged.

Thanks!