Add option to param_parse.py to emit SITL-only parameters
ArduPilot/ardupilot pull request #15584
Opened 2020-10-16 01:52 UTC by peterbarker

Our SITL parameter documentation (essentially anything under `SIM_`) is very poor.

Partly this is due to poor tooling (but mostly due to apathy).

This is an attempt to fix the former, given recent fixes for the latter.

It adds a "--sitl" option to `param_parse.py`.  If that is not set then the tool's output is byte-for-byte for current master's.

If it *is* set then we skip any parameter which doesn't have an annotation of `  // @HAL: SITL` as one of its fields, and we end up with an (JSON) output file like this:

```
{
  "Copter": {
    "SIM_BARO_GLITCH": {
      "Description": "user-settable 1st-barometer glitch",
      "DisplayName": "Baro Glitch",
      "HAL": "SITL",
      "Units": "m",
      "User": "Advanced"
    },
    "SIM_BARO_RND": {
      "Description": "amount of (evenly-distributed) noise injected into the 1st baro",
      "DisplayName": "Baro Noise",
      "HAL": "SITL",
      "Units": "m",
      "User": "Advanced"
    },
    "SIM_GRPE_ENABLE": {
      "Description": "Allows you to enable (1) or disable (0) the gripper servo simulation",
      "DisplayName": "Gripper servo Sim enable/disable",
      "HAL": "SITL",
      "User": "Advanced",
      "Values": {
        "0": "Disabled",
        "1": "Enabled"
      }
    },
    "SIM_GRPE_PIN": {
      "Description": "The pin number that the gripper emp is connected to. (start at 1)",
      "DisplayName": "Gripper emp pin",
      "HAL": "SITL",
      "Range": {
        "high": "15",
        "low": "0"
      },
```

This might be suitable for including in the "wiki" at https://ardupilot.org/dev/docs/simulation-2.html

I have a slight preference here for NOT adding this argument to `param_parse.py`, and simply including the extra information in the metadata.  This has the advantage of simplicity, but has the disadvantage that until tools catch up the user interfaces might be cluttered by the extra parameters.  For example, in MAVProxy we might need to filter out ` // HAL: SITL` parameters unless `--sitl` has been passed on the command-line.  Another example would be the Wiki, which would need to do the splitting as part of building the Wiki.  At the moment Tracker's Wiki actually does have some SITL parameters in it: https://ardupilot.org/antennatracker/docs/parameters.html#sim-grpe-parameters

@brunoolivieri what do you think about the concept of splitting the parameter data based on `HAL`?

@meee1 how would this work in with MP?  I'm guessing you'd prefer everything in the one file with the extra annotations?

2020-10-19 23:33 UTC, brunoolivieri commented
Well, I am not quite comfortable dealing with the Tools/autotest/param_metadata/ parser code. I guess there were some breaks, and the updated version can not parse some old firmware versions (and vice-e-versa). Retro compatibility is a constraint once patches can insert parameters in old versions (maybe ser could stop to do that in versions before 4.x.x in a future))

The wiki parameter versioning stuff uses the exact "param_parse.py" (and Emiters()) for each commit ID found on firmware folders in the autotest server.

Anyway, I guess using "--sitl" would enable a smooth update on the site documentation. I will do some tests with this PR with the wiki as soon as I can.

2020-10-20 00:51 UTC, tridge requested changes
i don't think the @HAL tag is worth it

2021-04-07 13:04 UTC, peterbarker commented
This has been changed up to simply filter one way or the other based on `SIM_`.

Output without `--sitl` has changed only to remove the `SIM_` parameters which crept in.

New `.rst` file is produced which we should be able to suck into the Wiki. (@Hwurzburg )

2021-04-10 01:28 UTC, merged

2021-04-15 23:15 UTC, rmackay9 commented
As mentioned just for accountability this broke the MP parameter parser.  Adding multiple parameters on the same line in the @Param line is not supported by MP.  Actually I'm surprised it's supported by the AP parser.