AP_Scripting: add DIR_DISABLE param to disable loading scripts from given directory
ArduPilot/ardupilot pull request #15621
Opened 2020-10-21 13:19 UTC by IamPete1

This allows to disable loading scripts from a directory based on a bit mask param. The use-case being if you have a script loaded in ROMFS that you don't want to run but you do need to run one of the SD card.

Fixes https://github.com/ArduPilot/ardupilot/issues/14644#

2020-10-26 23:58 UTC, tridge requested changes

2020-10-26 23:58 UTC, tridge commented on libraries/AP_Scripting/AP_Scripting.cpp
> +    #define DIR_DISABLE_DEFAULT AP_Scripting::SCR_DIR::ROMFS
should not default off on linux or sitl

2020-10-27 01:09 UTC, IamPete1 commented on libraries/AP_Scripting/AP_Scripting.cpp
> +    #define DIR_DISABLE_DEFAULT AP_Scripting::SCR_DIR::ROMFS
default now 0 on anything.

2020-10-28 08:22 UTC, tridge approved these changes

2020-10-28 08:22 UTC, merged

2020-10-28 08:23 UTC, rmackay9 commented on libraries/AP_Scripting/AP_Scripting.cpp
> +    AP_GROUPINFO("DIR_DISABLE", 9, AP_Scripting, _dir_disable, 0),
I would have preferred an ENABLE parameter probably..