Bi-directional DShot
ArduPilot/ardupilot pull request #15636
Opened 2020-10-23 20:27 UTC by andyp1per

WIP PR to add support for bi-directional dshot.

No idea whether this will work!

2020-10-23 23:31 UTC, tridge commented
good luck with this!

2020-11-21 21:16 UTC, andyp1per commented
Squashed

2020-11-23 23:01 UTC, tridge requested changes
this is only a partial review, ran out of time

2020-11-24 02:50 UTC, tridge commented on libraries/AP_HAL_ChibiOS/RCOutput.cpp
> +    static const uint32_t decode[32] = {
this really needs an explanation :-)

2020-11-24 02:53 UTC, tridge commented
a few general comments:
 - please test this with --enable-asserts
 - we need to look at the impact of this change on DMA mappings on current boards

2020-11-24 08:09 UTC, andyp1per commented
Thanks for the feedback @tridge !
- I have done all the development with --enable-asserts
- My plan is to make the resolver feature triggered by HAL_BIDIR_DSHOT and then work through boards that people are willing to test to get the DMA mappings correct

2020-11-25 13:07 UTC, andyp1per commented on libraries/AP_BLHeli/AP_BLHeli.cpp
> +    AP_GROUPINFO("OPTS",  11, AP_BLHeli, options, 0),
Added BDMASK

2020-11-25 13:08 UTC, andyp1per commented on libraries/AP_BLHeli/AP_BLHeli.h
> +    AP_Int8 options;
Fixed

2020-11-25 13:08 UTC, andyp1per commented on libraries/AP_HAL/RCOutput.h
> +    virtual float get_erpm_error_rate(uint8_t chan) const { return 0.0f; }
Added to logging

2020-11-25 13:09 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/RCOutput.cpp
> +    static const uint32_t decode[32] = {
Added

2020-11-28 16:20 UTC, andyp1per commented on libraries/AP_BLHeli/AP_BLHeli.cpp
> +    if (hal.util->get_soft_armed() && ocount++ % 200 == 0) {
Removed in favour of updating the existing debug and adding logging

2020-12-07 22:11 UTC, amilcarlucas commented
How much memory does this cost for a CubeBlack? Will it work on the normal PWM1-8 outputs, or does it need to use the PWM_AUX pins?

2020-12-08 08:24 UTC, andyp1per commented
Memory use unknown at this point, but not a lot - it will cost some flash. It needs to be on the AUX pins. Unlikely that we would do this for cube black - its EOL and I don't think @bugobliterator wants the support queries 😄

2020-12-09 09:01 UTC, tridge requested changes
i'd like a comparison of existing hwdef.h using configure_all.py

2020-12-11 23:09 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/RCOutput.h
> +        const stm32_dma_stream_t *ic_dma[4];
Fixed

2020-12-11 23:09 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/RCOutput.h
> +    // handling of bi-directional dshot
Fixed

2020-12-11 23:09 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/RCOutput.h
> +    uint16_t _erpm_errors[max_channels] {};
Removed

2020-12-11 23:09 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/RCOutput_bdshot.cpp
> +bool RCOutput::setup_group_ic_DMA(pwm_group &group)
Fixed

2020-12-11 23:09 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/RCOutput_bdshot.cpp
> +        hal.console->printf("TELEM: %d <%d Hz, %.1f%% err>", group.erpm[chan], group.telem_rate[chan],
its a bit too involved for that

2020-12-11 23:09 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/RCOutput_bdshot.cpp
> +        return 120000 * 5 / 4;
Fixed

2020-12-12 16:17 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
> -#endif\n''' % (n, n, n, n, n, n))
sid has fixed this

2020-12-13 18:30 UTC, andyp1per commented
Flash cost is 3.7k
Memory cost is 1.3k

2020-12-16 07:59 UTC, tridge commented
test plan:
 - [ ] believer with dshot telem (james, tridge, peter)
 - [ ] small quad without dshot
 - [ ] peter bixler
 - [ ] andy will fly quad with dshot telem

2020-12-16 07:59 UTC, tridge commented
> Flash cost is 3.7k
> Memory cost is 1.3k

can you check these costs without bi-dshot enabled

2020-12-16 09:39 UTC, andyp1per commented
So interestingly the flash cost is still 1.5k with this compiled out - so I need to figure out why that is.

2020-12-16 19:44 UTC, andyp1per commented
Compiled out on a Pixracer works fine. Here is the log from a hover in my office: 
[00000286.zip](https://github.com/ArduPilot/ardupilot/files/5705129/00000286.zip)

2020-12-16 20:52 UTC, andyp1per commented
I have compiled out a bit more so that BDMASK is no longer available unless the features is compiled in. Flash increase is down to 1k, which seems ok for the additional complexity that doing everything will entail - but can do it if necessary.

2020-12-17 15:17 UTC, andyp1per commented
Did some hard flying on a 3" KakuteF7Min-based quad. All was perfect - no issues at all. Couple of logs below:
[bidir-20-12-17_10-47-34.zip](https://github.com/ArduPilot/ardupilot/files/5710322/bidir-20-12-17_10-47-34.zip)
[bidir-20-12-17_11-43-34.zip](https://github.com/ArduPilot/ardupilot/files/5710323/bidir-20-12-17_11-43-34.zip)

2020-12-18 07:39 UTC, andyp1per commented
> test plan:
> 
>     * [ ]  believer with dshot telem (james, tridge, peter)
> 
>     * [X]  small quad without dshot
> 
>     * [ ]  peter bixler
> 
>     * [X]  andy will fly quad with dshot telem
> 
>     * [ ]  iomcu build test (likely will need to disable fport2 in iomcu code)

2020-12-22 15:51 UTC, andyp1per commented
IOMCU on Durandal builds and runs fine with this change (I tested that there was output)
I have also now ported to a Pixracer quad and flown successfully with that

2020-12-24 12:22 UTC, andyp1per commented
Did 12 flights today - 6 on the Kakute and 6 on the Pixracer. All worked fine no issues at all - can post logs if necessary

2020-12-29 12:04 UTC, andyp1per commented
Rebuilt IOMCU and flew on my Y6B / Durandal with PWM/IOMCU outputs without issue

2020-12-30 08:14 UTC, tridge approved these changes

2020-12-30 08:14 UTC, merged

2021-01-01 17:36 UTC, davidbitton commented
Does this addition pave the way towards RPM filtering?

2021-01-01 17:52 UTC, andyp1per commented
@davidbitton we already support RPM filtering

2021-01-01 20:37 UTC, davidbitton commented
@andyp1per thanks. I found some/the filtering code in `AP_BLHeli.cpp`.

2021-01-05 09:16 UTC, andyp1per commented
![image](https://user-images.githubusercontent.com/2893260/103628280-af21fa80-4f36-11eb-80ef-d502f6a6577f.png)