UAVCAN heading support
ArduPilot/ardupilot pull request #15714
Opened 2020-11-03 02:38 UTC by meee1

2020-11-03 03:08 UTC, magicrub commented
Does UAVCAN upstream know about this new msg?

2020-11-03 04:11 UTC, meee1 commented
> Does UAVCAN upstream know about this new msg?

no it does not

2020-12-09 05:41 UTC, tridge requested changes
nice feature!
if changing the dsdl now is an issue then we can keep the float32, just seems a shame to make it 2 pkts

2020-12-09 05:41 UTC, tridge commented on libraries/AP_UAVCAN/dsdl/ardupilot/gnss/20002.Heading.uavcan
> +float32 heading
it would be nice to fit in one can pkt, if we use int16 in centi-degrees (or float16) then we can make it fit I think

2020-12-09 05:41 UTC, tridge commented on libraries/AP_GPS/AP_GPS_UAVCAN.cpp
> +    if (interim_state.gps_yaw_configured == false)
please follow style guide in parentheses

2020-12-09 06:32 UTC, tridge commented
please also follow style guide for commit msgs, so "AP_GPS: support yaw for UAVCAN GPS'

2021-01-07 04:55 UTC, tridge approved these changes

2021-01-07 04:56 UTC, merged

2021-01-09 00:59 UTC, rmackay9 commented
This is causing a compile error for me because of this include in AP_GPS_UAVCAN.cpp. #include <ardupilot/gnss/Heading.hpp>