AP_Baro: add low pass filter for ground pressure calibration
ArduPilot/ardupilot pull request #15776
Opened 2020-11-11 14:07 UTC by khancyr

Add a low pass filter on baro ground pressure calibration. 
This prevent sudden change on calibration due to windgust or propeller/fan etc.
Beside of Copter this will be used on all vehicle when they update home as they do baro calibration. Copter doesn't do the calibration and only use the 5 samples from start

2020-11-11 22:59 UTC, rmackay9 commented
I think we should try and keep the number of parameters to a minimum so I think we should be able to add this feature without adding a parameter.

2020-11-12 16:12 UTC, magicrub requested changes
Generally speaking, this is absolutely overkill. However, I agree with the intent of the PR to apply a smoothed ground pressure.
- Param is not needed, just hardcode that.
- using the LowPassFilterFloat class is overkill and a waste of memory. This whole thing can be replaced with a memory footprint of a single float and muuuch less cpu complexity

2020-11-12 16:12 UTC, magicrub commented on libraries/AP_Baro/AP_Baro.cpp
> +    AP_GROUPINFO("AVG_TAU", 18, AP_Baro, _filter_tau, 5.0f),
I agree with Randy. A param is definitely not needed for this

2020-11-12 16:12 UTC, magicrub commented on libraries/AP_Baro/AP_Baro.cpp
> +        sensor_.avg_pressure_filter.reset(101325.0f);  // default to 1013.25 hPa
never initialize to a fixed value like this. Reset it to the first sample

2021-02-03 02:28 UTC, peterbarker commented
@khancyr now conflicting.

Did you want to chase this?

2021-07-06 12:56 UTC, closed without merging