AP_PiccoloCAN: Add support for CBS can servo
ArduPilot/ardupilot pull request #15782
Opened 2020-11-11 22:40 UTC by SchrodingersGat

This PR adds support for the CBS range of CAN servos developed by Currawong Engineering:

https://www.currawong.aero/servos-escs/can-servo/

For reference, it follows on from integration of support for the Velocity ESC - https://github.com/ArduPilot/ardupilot/pull/15425

The following functionality is provided

- Support for the servo CAN protocol
- Individual selection of servo channels to be pushed out over CAN
- Reception of telemetry data for the servos
- Logging support for servo telemetry

2020-11-11 22:48 UTC, SchrodingersGat commented
@tridge @bugobliterator please let me know if you want any higher-level discussions of this PR or our CAN servo tech.

2020-11-11 22:58 UTC, SchrodingersGat commented
I also have a couple of questions regarding implementation of "smart" servo devices. If the following questions are better addressed elsewhere, please let me know.

### Telemetry

Currently it appears there is no option for sending servo telemetry back to the GCS via Mavlink, which is possible for ESCs. Is this something that could be implemented? Or is it already implemented and I just have not been able to find it?

### Status Flags

Both the Velocity ESC and the CBS Servo have a rich set of status flags available in the telemetry data which (at the very least) would be useful to have in the flight logs. Could the logger data structures (for both the ESC and the Servo) be extended to allow "generic" status flags (as different manufacturers would have different status bits). For example it could be just a few unsigned integer fields?

2021-02-03 02:34 UTC, peterbarker commented
> Currently it appears there is no option for sending servo telemetry back to the GCS via Mavlink, which is possible for ESCs. Is this something that could be implemented? Or is it already implemented and I just have not been able to find it?

That's the `ESC_TELEMETRY_x_TO_y` message set:

https://github.com/ardupilot/ardupilot/blob/master/libraries/AP_KDECAN/AP_KDECAN.cpp#L712

> ### Status Flags
> 
> Both the Velocity ESC and the CBS Servo have a rich set of status flags available in the telemetry data which (at the very least) would be useful to have in the flight logs. Could the logger data structures (for both the ESC and the Servo) be extended to allow "generic" status flags (as different manufacturers would have different status bits). For example it could be just a few unsigned integer fields?

I'm loathe to introduce vendor-specific-for-semantics bitmasks into the logger messages.  But there are options - for example, logging a separate message if flag changes are detected, or mapping from the vendor-specific flag set into a more generic flag set.  If you can provide a link to the set of flags you're currently thinking about I might be able to reason more...
\

2021-02-11 23:22 UTC, SchrodingersGat commented on libraries/AP_PiccoloCAN/piccolo_protocol/ServoDefines.h
> +}Servo_StatusBits_t;
@peterbarker for example these status bits (and the warning and error bits below)

2021-02-11 23:23 UTC, SchrodingersGat commented
> That's the ESC_TELEMETRY_x_TO_y message 

That applies for ESC but it appears there are no downlink messages specific for servos?

> I'm loathe to introduce vendor-specific-for-semantics bitmasks into the logger messages. But there are options - for example, logging a separate message if flag changes are detected, or mapping from the vendor-specific flag set into a more generic flag set. If you can provide a link to the set of flags you're currently thinking about I might be able to reason more...

See the code I tagged you in above.

2021-05-12 07:48 UTC, SchrodingersGat commented
@peterbarker any chance you could spare some time to have another look at this?

2021-05-21 09:34 UTC, bugobliterator commented
@SchrodingersGat please resolve the conflict, I will review and raise this PR on the next EU DevCall.

2021-06-06 05:12 UTC, bugobliterator requested changes
Generally this looks good to me. There are few minor issues, I have made inline review comments for them.

2021-06-06 23:43 UTC, SchrodingersGat commented
@bugobliterator changes made as requested :)

2021-06-07 03:35 UTC, bugobliterator approved these changes

2021-06-07 03:49 UTC, SchrodingersGat commented
Thanks @bugobliterator - once this is merged I'll submit a documentation PR :)

2021-06-24 05:51 UTC, merged

2021-06-24 05:52 UTC, SchrodingersGat commented
Thanks Tridge!