Mavftp disable option
ArduPilot/ardupilot pull request #15806
Opened 2020-11-14 01:59 UTC by Hwurzburg

Allows user to disable MAVftp and reclaim 13.2K of RAM....the F4 1MB boards are getting low again on RAM....
Master with defaults is only 18.9K...add several backends and you can run out of memory and start getting watchdogs...I did playing with servo gimbal stuff on the bench with a naked OmnibusF4pro....

tested on OmnibusF4pro with master, stable, and Tridges font PR code...

PS. not sure if I did the accessor correctly but it works...

2020-11-14 02:04 UTC, tridge requested changes
nice!
missing same change here:
https://github.com/ardupilot/ardupilot/blob/master/libraries/GCS_MAVLink/GCS_Common.cpp#L5065
so we don't announce it as a capability

2020-11-14 02:12 UTC, Hwurzburg commented
fixed...thanks!

2020-11-14 03:17 UTC, tridge approved these changes

2020-11-15 04:04 UTC, Hwurzburg commented
@tridge should this be tagged for dev cal or are you going to just merge?

2020-11-15 07:16 UTC, tridge commented
@Hwurzburg I've marked it for dev call

2020-11-16 23:42 UTC, merged