RCOutput_PCA9685: allow different external clock frequencies
ArduPilot/ardupilot pull request #15834
Opened 2020-11-17 18:32 UTC by jaxxzer

The PCA9685 may use an external clock 0~50MHz
Specify the external clock frequency in constructor arguments for each board HAL, so different boards may use different external oscillators.

2020-11-17 22:33 UTC, amilcarlucas requested changes

2020-11-18 03:15 UTC, jaxxzer commented on libraries/AP_HAL_Linux/RCOutput_PCA9685.cpp
> -#define PCA9685_EXTERNAL_CLOCK 24576000.f
There would need to be a define for each board in HAL_Linux_Class.cpp, in the same place as the `static RCOutput_PCA9685` declaration. That appears redundant, unless I am misunderstanding the suggestion.

The idea with this patch is that we are developing the navigator board, and having a single definition for 24.576MHz places an unnecessary constraint on our part selection for the external oscillator, so we would like the option to use a different value for the navigator.

2020-11-18 03:16 UTC, jaxxzer commented on libraries/AP_HAL_Linux/RCOutput_PCA9685.cpp
> -#define PCA9685_EXTERNAL_CLOCK 24576000.f
It would be a smaller patch, so if I got the suggestion right, let me know and I will update it.

2020-11-18 08:19 UTC, amilcarlucas commented on libraries/AP_HAL_Linux/RCOutput_PCA9685.cpp
> -#define PCA9685_EXTERNAL_CLOCK 24576000.f
Good point

2020-11-21 08:20 UTC, lucasdemarchi approved these changes

2020-11-21 08:24 UTC, lucasdemarchi commented
FYI I often filter pending PRs by "Linux" label to review. Feel free to add it in future when it's for a Linux board.

2020-11-21 08:25 UTC, merged