Copter: support MAV_FRAME_LOCAL_NED in MISSION_ITEM for auto mode #8748 (rebased)
ArduPilot/ardupilot pull request #15854
Opened 2020-11-20 08:21 UTC by roackb2

This is based on the work of @chobitsfan with branch and issue #8748.
I've done the rebase on master branch and need someone to check the logic is correct.
@amilcarlucas may I kindly request for your review?

2020-11-20 08:27 UTC, amilcarlucas requested changes
remove the temp.cpp file

2020-11-20 08:32 UTC, roackb2 commented
My bad, removed it.

2020-11-20 13:23 UTC, roackb2 commented
And now it fails on cloning MAVProxy....
Any idea?

```
Installing MAVProxy
/tmp /__w/ardupilot/ardupilot
+ for t in $CI_BUILD_TARGET
+ '[' sitltest-tracker == sitltest-heli ']'
+ '[' sitltest-tracker == sitltest-copter-tests1 ']'
+ '[' sitltest-tracker == sitltest-copter-tests1a ']'
+ '[' sitltest-tracker == sitltest-copter-tests1b ']'
+ '[' sitltest-tracker == sitltest-copter-tests1c ']'
+ '[' sitltest-tracker == sitltest-copter-tests1d ']'
+ '[' sitltest-tracker == sitltest-copter-tests1e ']'
+ '[' sitltest-tracker == sitltest-copter-tests2 ']'
+ '[' sitltest-tracker == sitltest-copter-tests2a ']'
+ '[' sitltest-tracker == sitltest-copter-tests2b ']'
+ '[' sitltest-tracker == sitltest-can ']'
+ '[' sitltest-tracker == sitltest-plane ']'
+ '[' sitltest-tracker == sitltest-quadplane ']'
+ '[' sitltest-tracker == sitltest-rover ']'
+ '[' sitltest-tracker == sitltest-tracker ']'
+ run_autotest Tracker build.Tracker test.Tracker
+ NAME=Tracker
+ BVEHICLE=build.Tracker
+ RVEHICLE=test.Tracker
+ cat /proc/cpuinfo
+ '[' 0 -eq 0 ']'
+ echo 'Installing MAVProxy'
+ pushd /tmp
+ git clone --recursive https://github.com/ardupilot/MAVProxy
Cloning into 'MAVProxy'...
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

2020-11-20 14:10 UTC, roackb2 commented
@amilcarlucas finally it passed all the checks lolllllll
This is my first time doing a PR, but I'm wondering that is an nondeterministic CI/CD pipeline a common phenomenon?

2020-11-20 14:30 UTC, amilcarlucas commented
Nice. yes, sometimes the CI is non-deterministic.

2020-12-05 10:37 UTC, roackb2 commented
@amilcarlucas I've tested this feature with a copter for many times. It is really very helpful for my current project on hand, and I believe it would also be needed for many others studying indoor flight. To support those who might need this, I listed some information as following:

Here's the [video](https://youtu.be/fm_W8DlqdkU)
This is the [flight plan](https://www.dropbox.com/s/xk4rsuaxvxkiv2e/L-line-2.plan?dl=0)
And this is the [parameters](https://www.dropbox.com/s/da6vyfaay2bf9ql/vision_master.params?dl=0) I use

2020-12-05 14:30 UTC, amilcarlucas requested changes

2020-12-05 14:30 UTC, amilcarlucas commented on ArduCopter/mode_auto.cpp
> +	// set waypoint controller target
The indentation looks messed up

2020-12-05 14:30 UTC, amilcarlucas commented on libraries/AP_Mission/AP_Mission.cpp
> +            packet.z = cmd.content.location.alt / 100.0f;   // cmd alt in cm to m
Please use a multiplication instead of a division here.

2020-12-06 18:59 UTC, roackb2 commented
@amilcarlucas Thanks for your quick response.  I got some errors consistently while running tests multiple times (listed below).

I dig into the code of test cases, looks like the test failed because of the difference in altitude of mission result. The code states that `max_allowed_delta` is 0.000009 for counter 4 ~ 10 in QGC WPL 110 file. The error points out that counter 10, which represents altitude, has difference of 0.000976999999693362 (1085.900391 - 11085.899414), which exceeds the max allowed delta. However, no related error shows up in last commit, and the only change in this PR that relates to altitude is to change the sign, since local frame is NED. The difference in this commit compared to prior one in `AP_Mission.cpp` is to change division to multiplication as you suggested. May there be any reason that this arithmetic change will result in the difference in mission execution? What kind of action should I take?  I'm also curious about that do real vehicle driving or flying could achieve such kind of altitude accuracy?
Thanks.

```
AT-0142.2: Stopping SITL
AT-0143.3: Failing tests:
  DriveMission (Drive Mission balancebot1.txt) (Files have different (float) content: (/vagrant/Tools/autotest/ArduRover_Tests/DriveMission/balancebot1.txt) and (test.Rover/logs/2020-12-06/flight2/way.txt) (2	03	16	0.000000	0.000000	0.000000	0.000000	40.071083	-105.230026	11085.900391	1 vs 2	0	3	16	0.000000	0.000000	0.000000	0.000000	40.071083	-105.230026	11085.899414	1) (11085.900391 vs 11085.899414) (0.0009770000) (count=10)) (see /tmp/buildlogs/Rover-DriveMission.txt)
>>>> FAILED STEP: test.BalanceBot at Sun Dec  6 18:13:27 2020
Failure Summary:
  test.Rover:
    DriveMission (Drive Mission rover1.txt) (Files have different (float) content: (/vagrant/Tools/autotest/ArduRover_Tests/DriveMission/rover1.txt) and (test.Rover/logs/2020-12-06/flight1/way.txt) (2	0	316	0.000000	0.000000	0.000000	0.000000	40.071289	-105.230057	11085.900391	1 vs 2	0	3	16	0.000000	0.000000	0.000000	0.000000	40.071289	-105.230057	11085.899414	1) (11085.900391 vs 11085.899414) (0.0009770000) (count=10)) (see /tmp/buildlogs/Rover-DriveMission.txt)
  test.BalanceBot:
    DriveMission (Drive Mission balancebot1.txt) (Files have different (float) content: (/vagrant/Tools/autotest/ArduRover_Tests/DriveMission/balancebot1.txt) and (test.Rover/logs/2020-12-06/flight2/way.txt) (2	03	16	0.000000	0.000000	0.000000	0.000000	40.071083	-105.230026	11085.900391	1 vs 2	0	3	16	0.000000	0.000000	0.000000	0.000000	40.071083	-105.230026	11085.899414	1) (11085.900391 vs 11085.899414) (0.0009770000) (count=10)) (see /tmp/buildlogs/Rover-DriveMission.txt)
FAILED 2 tests: ['test.Rover', 'test.BalanceBot']
```

2021-01-07 12:55 UTC, amilcarlucas commented
I did the fixes and created a new PR #16259

2021-01-07 13:09 UTC, amilcarlucas commented
#16259 is cleaner (no temp file), rebased, squashed and passes all CI tests

2021-01-07 13:09 UTC, closed without merging

2021-01-07 16:36 UTC, roackb2 commented
@amilcarlucas ok thanks for your work