Emit an EKF status report per core
ArduPilot/ardupilot pull request #15983
Opened 2020-12-05 10:46 UTC by peterbarker

I intend this to replace https://github.com/ArduPilot/ardupilot/pull/11901

One limitation this still has is that it doesn't nominate which EKF the cores belong to.

So if you're running EK3 as ride-along then you won't get its status reports.

We could add another field to the message to nominate the EKF, or permute the core numbers for the inactive estimators.

We emit the primary core last so that it's the last thing you'd see in things like `status EKF_STATUS_REPORT --verbose`

2020-12-08 17:11 UTC, WickedShell requested changes
This doesn't do the send buffer space checking, and we need to only try and send a single report per time in the queue. When we don't do this it leads to subtle bugs on the GCS such as were recently fixed for BATTERY_STATUS and the MAG_CAL messages. To make it even worse, the current implementation will send your primary last, which is the one you care the most about, and that is the least likely one to be sent to you.

2020-12-08 17:11 UTC, WickedShell commented on libraries/AP_NavEKF2/AP_NavEKF2.cpp
> +        core[i].send_status_report(chan);
Ahhh, please no! This dies so badly with full links. This is violating the single message per interval rule again on us. What this ends up doing is on a full link. Even worse though you missed that your only space checking is up in the GCS_MAVLink class.... All your later messages will corrupt the MAVLink stream, and lead to packet loss.

2020-12-08 17:12 UTC, WickedShell commented
> We emit the primary core last so that it's the last thing you'd see in things like `status EKF_STATUS_REPORT --verbose`

You can't actually count on that though because the link is lossy, and for the reasons I identified above. Just send them in order and rely upon the primary flag.... Attempts to be clever here will instead lead to just losing the message.

2020-12-08 21:38 UTC, peterbarker commented
@WickedShell thanks for looking at this - I'd missed the space-check, and was wondering whether you'd pick up on the rate thing :-)

We shouldn't lose the primary, and it is kind of important for mavproxy to show you the most important information in `status`.

It was also decided on the DevCall that we couldn't actually do this without having a parameter to control it.  Any GCS not understanding the new field will get very confused, ascribing all of the messages to core-0.  So there's a bit of work to be done here...

2020-12-08 23:14 UTC, WickedShell commented
I think the primary should just be sent out in it's slot when we get to it,
rather then anything fancier...

Is there a plan for GCSs which don't know about the extension? All I've
come up with is flag abuse, and I suspect there isn't enough free bits to
make it work...

On Tue, Dec 8, 2020, 15:38 Peter Barker <notifications@github.com> wrote:

> @WickedShell <https://github.com/WickedShell> thanks for looking at this
> - I'd missed the space-check, and was wondering whether you'd pick up on
> the rate thing :-)
>
> We shouldn't lose the primary, and it is kind of important for mavproxy to
> show you the most important information in status.
>
> It was also decided on the DevCall that we couldn't actually do this
> without having a parameter to control it. Any GCS not understanding the new
> field will get very confused, ascribing all of the messages to core-0. So
> there's a bit of work to be done here...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ArduPilot/ardupilot/pull/15983#issuecomment-741074558>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEKTCFHGA62OZT4PWUTFMLST2MGLANCNFSM4UOOZIUQ>
> .
>

2020-12-09 01:18 UTC, peterbarker commented
On Tue, 8 Dec 2020, WickedShell wrote:

> 
> I think the primary should just be sent out in it's slot when we get to it,
> rather then anything fancier...
> 
> Is there a plan for GCSs which don't know about the extension? All I've
> come up with is flag abuse, and I suspect there isn't enough free bits to
> make it work...

"Don't set the BRD_EKF_STATUS_MANY parameter if you don't really mean it".

We did discuss adding a new message instead...

2021-03-02 16:28 UTC, amilcarlucas commented
Needs a rebase, but otherwise this is OK to merge, or?

2021-03-31 02:57 UTC, peterbarker commented
Merging this will break existing setups that don't understand the extension field.

The question of transmitting for cores we would never switch to (e.g. sending both EK2 and EK3 core information) is also unresolved.

2021-03-31 02:57 UTC, closed without merging