This commit fixes some grammatical errors found in the README.md file
ArduPilot/ardupilot pull request #16028
Opened 2020-12-10 20:17 UTC by arshPratap

Fixed some grammatical errors found in the readme file

2020-12-10 21:01 UTC, khancyr approved these changes
I am not english, but that seems good

2020-12-10 23:50 UTC, rmackay9 commented
Looks good, can you change the commit line to be "README: fixes some grammatical errors"?  to be clear I mean fix the commit description itself not the PR's description.

2020-12-11 03:13 UTC, peterbarker commented
`README.md: fix some grammatical errors`

2020-12-11 10:35 UTC, arshPratap commented
Thank you @khancyr, @peterbarker, @rmackay9 for your tips and suggestions. I have made the necessary changes and am looking forward to contribute to Ardupilot.

2020-12-11 10:38 UTC, khancyr commented
Hello,

Thank you. You are close to get it right. We don't use the merge commit, so you will need to do a rebase on our master branch to get rid of it and keep only your commit !

You can look on our wiki on how to do that, in the dev section

2020-12-11 13:51 UTC, arshPratap commented
Sir, I have done the necessary changes

2020-12-11 13:52 UTC, arshPratap commented
Please take a look..Thanks a lot in advance

2020-12-11 15:22 UTC, eric-wieser commented on README.md
> +airplanes, multirotors, and helicopters, to boats and even submarines. And is now being expanded to provide
```suggestion
airplanes, multirotors, and helicopters, to boats and even submarines. It is now being expanded to provide
```

2020-12-11 15:36 UTC, Hwurzburg requested changes

2020-12-11 15:36 UTC, Hwurzburg commented on README.md
> +airplanes, multirotors, and helicopters, to boats and even submarines. And is now being expanded to provide
if we are going to update, might as well make it up to date on vehicle support also...
```suggestion
airplanes, quadplanes, multirotors, and helicopters, to rovers, boats, balancebots, and even submarines. And is now being expanded to provide
```

2020-12-11 15:36 UTC, Hwurzburg commented on README.md
>  support for new emerging vehicle types such as quad-planes and compound helicopters.
```suggestion
support for new emerging vehicle types such as compound helicopters.
```

2020-12-11 18:34 UTC, magicrub commented
This is 3 commits for 2 lines (one chunk) of text. Needs to be squashed.

2020-12-11 19:10 UTC, arshPratap commented
OK sir, I will squash the commits

2020-12-11 19:55 UTC, arshPratap commented
Sir, I have squashed the above commits into one commit and I want to thank @eric-wieser and @Hwurzburg for suggesting the changes.

2020-12-11 21:27 UTC, merged

2020-12-11 21:27 UTC, magicrub commented
Merged, thank you!