AP_Button: expand info in metadata
ArduPilot/ardupilot pull request #16068
Opened 2020-12-15 17:49 UTC by Hwurzburg

2020-12-15 23:24 UTC, peterbarker approved these changes
LGTM., thanks!

2020-12-27 03:00 UTC, Hwurzburg commented
@peterbarker can you merge?

2020-12-29 00:11 UTC, IamPete1 requested changes

2020-12-29 00:11 UTC, IamPete1 commented on libraries/AP_Button/AP_Button.cpp
> -    // @User: Standard
we have lost the user here

2020-12-29 00:11 UTC, tridge approved these changes

2020-12-29 00:11 UTC, merged