StreamRates: param "SRn" count to match MAVLINK_COMM_NUM_BUFFER
ArduPilot/ardupilot pull request #16121
Opened 2020-12-22 22:51 UTC by magicrub

Right now we have SR0,1,2,3 but if you're using Serial4 for MAVLink then you have no Stream Rate params. It makes sense to have as many SR params as you have MAVLINK_COMM_NUM_BUFFER. The memory for this has always been allocated because the streamrate array is of size MAVLINK_COMM_NUM_BUFFER but we didn't have any params defined to adjust them. This adds that.

2020-12-22 22:56 UTC, andyp1per commented
@magicrub I didn't think that was how it worked - SR1/SR2/SR3 correspond to the serial channels with *mavlink enabled* not to the same numbered channel

2020-12-23 00:23 UTC, magicrub commented
@andyp1per really? Are you sure? Where in the code is that logic applied?

2020-12-28 23:20 UTC, meee1 commented on AntennaTracker/Parameters.cpp
> +    // @Group: S6_
SR6_?

2020-12-28 23:21 UTC, tridge requested changes

2020-12-28 23:21 UTC, tridge commented on AntennaTracker/Parameters.cpp
> +    // @Group: S6_
typo, SR6

2020-12-28 23:23 UTC, magicrub commented on AntennaTracker/Parameters.cpp
> +    // @Group: S6_
whoops!

2020-12-29 05:57 UTC, magicrub commented on AntennaTracker/Parameters.cpp
> +    // @Group: S6_
fixed

2020-12-29 05:57 UTC, magicrub commented on AntennaTracker/Parameters.cpp
> +    // @Group: S6_
fixed

2020-12-29 05:58 UTC, magicrub commented
the typo was fixed. Per the dev call, this is ready to merge after it passes CI

2020-12-29 14:52 UTC, merged