AP_HAL_ChibiOS: add support for Pixracer-periph
ArduPilot/ardupilot pull request #16139
Opened 2020-12-26 16:47 UTC by ukmook

2020-12-26 17:08 UTC, magicrub commented
I worked with @ukmook on this and he's tested it thoroughly.. as usual :)

2020-12-26 17:09 UTC, magicrub commented
@pkocmoud  This might be of interest to you

2020-12-26 17:30 UTC, pkocmoud commented
How did you decide on the board ID? I typically precede this step with a commit to: https://github.com/ArduPilot/ardupilot/blob/master/Tools/AP_Bootloader/board_types.txt

2020-12-26 17:35 UTC, magicrub commented
@pkocmoud yes, good call. The ID was chosen by @ukmook , so we'll see what he says, but you're write that it should be added to that list.

2020-12-26 17:37 UTC, magicrub commented
@pkocmoud do you have any suggestions or preference on the board ID? Do we have a convention?

2020-12-26 17:37 UTC, pkocmoud commented
Typically just the next is sequence.

2020-12-26 17:38 UTC, pkocmoud commented
You might want to add this as well. I will confirm there are no other pins that require assignment to prevent increased current draw.

# default to all pins low to avoid ESD issues
DEFAULTGPIO OUTPUT LOW PULLDOWN

2020-12-26 17:40 UTC, magicrub commented
It would be nice if we could have this sort of line in the hwdef:
```APJ_BOARD_ID AP_HW_MRO_PIXRACER_PRO_PERIPH```

2020-12-26 18:45 UTC, ukmook commented
> @pkocmoud yes, good call. The ID was chosen by @ukmook , so we'll see what he says, but you're write that it should be added to that list.

I chose the next id following on from Cube*_periph, clearly an error on my part

2020-12-26 18:46 UTC, magicrub commented
@ukmook not necessarily.

2020-12-26 18:55 UTC, magicrub commented
looking at that board ID list, I only see two periph's defined: ```AP_HW_F103_PERIPH``` and ```AP_HW_F303_PERIPH```. I'm tempted to say lets not add it to this PR quite yet because we may want to figure out something special for vehicle boards that are being converted to ap-periph. I'll tag this for a dev call topic but we might get it resolved sooner

2020-12-26 19:37 UTC, tridge commented
for boards that normally normally run ardupilot flight control firmware I don't think we want a separate board ID. If we use a separate ID then we can't load the firmware using the normal bootloader as the bootloader refuses firmware without the right board ID. The board ID is about hw compatibility and a periph fw is just like another vehicle type, so doesn't change hw compat

2020-12-26 19:52 UTC, magicrub commented
That's true as long as the same bootloader can work for both systems. In the case of 16kb bootloader, can and usb don't fit well together. For example, cube black bootloader needs to be bigger and this requires a different id

2020-12-26 20:54 UTC, magicrub commented
@tridge for example, the pixracer DOES NOT define FLASH_RESERVE_START_KB so it uses the default 16. This hwdef uses FLASH_RESERVE_START_KB 64. Therefore, loading AP_Periph app on a standard pixracer will cause the app to not run properly (and vice versa)

2020-12-26 22:17 UTC, tridge commented
@magicrub right, if it is a single sector F4 bootloader then we have to have a different ID if we want to use a CAN bootloader

2020-12-28 23:25 UTC, tridge requested changes

2020-12-28 23:25 UTC, tridge commented on libraries/AP_HAL_ChibiOS/hwdef/Pixracer-periph/hwdef-bl.dat
> +APJ_BOARD_ID 1402
please add patch to board_types.txt

2020-12-29 05:58 UTC, magicrub commented on libraries/AP_HAL_ChibiOS/hwdef/Pixracer-periph/hwdef-bl.dat
> +APJ_BOARD_ID 1402
added

2020-12-29 05:59 UTC, magicrub commented
Added this, and the Cube-periph BoardIDs. Per the dev call, this is ready to merge after it passes CI

2020-12-29 14:52 UTC, merged