Plane: Unify tilt servo names
ArduPilot/ardupilot pull request #16149
Opened 2020-12-27 13:32 UTC by Hwurzburg

2020-12-27 21:32 UTC, khancyr requested changes
41:TiltMotor,45:TiltMotorRear  -->  41:TiltMotorsFront,45:TiltMotorsRear
75:TiltMotorLeft,  -->  75:TiltMotorFrontLeft
76:Tilt MotorRight  --> 76:Tilt MotorFrontRight

Shouldn't the space on 76 be removed to be consistent with 75:TiltMotorFrontLeft ?

2020-12-27 21:37 UTC, Hwurzburg commented
> 41:TiltMotor,45:TiltMotorRear --> 41:TiltMotorsFront,45:TiltMotorsRear
> 75:TiltMotorLeft, --> 75:TiltMotorFrontLeft
> 76:Tilt MotorRight --> 76:Tilt MotorFrontRight
> 
> Shouldn't the space on 76 be removed to be consistent with 75:TiltMotorFrontLeft ?

yes...just switched to ATOM editor and have trouble seeing spaces at the end of a line wrap, wish it would highlight the ending white spaces when it wraps a line...fixed...thanks

2020-12-29 17:10 UTC, khancyr reviewed
From a syntax point of view that is OK.
But I got no idea if the changes are right or not

2020-12-30 10:21 UTC, tridge approved these changes

2020-12-30 10:21 UTC, merged