GCS_MAVLink: Strictly check extensions.
ArduPilot/ardupilot pull request #16155
Opened 2020-12-28 13:25 UTC by muramura

I'm missing a check when comparing strings by character count.
For example, strncmp("@PARAM/param.pck1", "@PARAM/param.pck", 16) will be equal.
Therefore, you need to make sure that they are the same string.

2021-01-02 11:33 UTC, peterbarker requested changes

2021-01-02 11:33 UTC, peterbarker commented on libraries/GCS_MAVLink/GCS_FTP.cpp
> +                        if (strlen((const char *)request.data) == 16 && (strncmp((const char *)request.data, "@PARAM/param.pck", 16) == 0)) {
```suggestion
                        if (strnlen((const char *)request.data, ARRAY_SIZE(request.data)) == 16 && (strncmp((const char *)request.data, "@PARAM/param.pck", 16) == 0)) {
```

This is a good fix.  But we don't want to over-read `request.data` if we've been passed garbage in.

2021-03-02 16:24 UTC, amilcarlucas commented
@muramura can you address Peter's comments?

2021-05-04 13:54 UTC, khancyr commented
close by https://github.com/ArduPilot/ardupilot/pull/17353

2021-05-04 13:54 UTC, closed without merging