Copter: don't report initial mode switch as failsafe mode change
ArduPilot/ardupilot pull request #16189
Opened 2020-12-31 08:43 UTC by khancyr

If you didn't change the initial_mode value then we go through the else cause and trigger 
AP_Notify::events.failsafe_mode_change = 1; that use a tone at start ... we definitely don't want that at start.

This can be checked on SITL with --tonealarm

2020-12-31 09:13 UTC, andyp1per approved these changes

2021-01-01 07:03 UTC, rishabsingh3003 commented
Was this the issue causing 4 beeps at start up?

2021-01-02 10:55 UTC, peterbarker approved these changes

2021-01-04 23:33 UTC, rmackay9 requested changes
can you make it still play the user_mode_change_failed event?  This should be inside the "if" though.

2021-01-08 22:28 UTC, peterbarker approved these changes
This is what was asked for at the DevCall.

2021-01-08 23:28 UTC, merged

2021-01-08 23:28 UTC, rmackay9 commented
Merged, thanks!