add support for VS Code tasks to do build and upload
ArduPilot/ardupilot pull request #16234
Opened 2021-01-05 22:48 UTC by bugobliterator

First step in getting betting integration of ardupilot with VSCode. The extension being developed for this:
https://github.com/bugobliterator/ardupilot_vscode_extension

2021-01-06 07:17 UTC, tridge requested changes

2021-01-06 07:17 UTC, tridge commented on Tools/AP_Periph/wscript
> +    with open(os.path.join(sys.path[0], "../AP_Periph/targets.txt"), "r") as f:
there is bld.srcpath or a __FILE__ equivalent

2021-01-06 07:17 UTC, tridge commented on Tools/AP_Periph/wscript
> +        targets = f.read().split('\n')
readlines ?

2021-01-06 07:17 UTC, tridge commented on wscript
> +            with open(os.path.join(sys.path[0], "../AP_Periph/targets.txt"), "r") as periphtargets:
same issues

2021-01-06 11:17 UTC, khancyr commented on Tools/AP_Periph/wscript
> +    with open(os.path.join(sys.path[0], "../AP_Periph/targets.txt"), "r") as f:
isn't just make a get_targets() function simpler ?

2021-01-20 08:27 UTC, tridge requested changes

2021-01-20 08:27 UTC, tridge commented on wscript
> +                    task['targets'] = ['antennatracker', 'copter', 'heli', 'plane', 'rover', 'sub', 'bootloader', 'replay']
replay is not linux any more, it's normally sitl but can do any board. Maybe list as only sitl

2021-01-21 18:42 UTC, tridge approved these changes

2021-01-21 18:42 UTC, merged