AP_Proximity: when multiple rangefinder/sonar are present the upward …
ArduPilot/ardupilot pull request #16266
Opened 2021-01-08 10:48 UTC by amilcarlucas

…distance sensor is not the primary instance

2021-01-08 13:56 UTC, khancyr commented on libraries/AP_Proximity/AP_Proximity.cpp
> +        if (get_orientation(i) == ROTATION_PITCH_90) {
better MAV_SENSOR_ROTATION_PITCH_90

2021-01-08 16:25 UTC, khancyr approved these changes
LGTM

2021-01-13 08:11 UTC, tridge requested changes

2021-01-13 08:11 UTC, tridge commented on libraries/AP_Proximity/AP_Proximity.cpp
> +        if (get_orientation(i) == MAV_SENSOR_ROTATION_PITCH_90) {
that is not what get_orientation() means in AP_Proximity

2021-01-13 08:12 UTC, tridge commented on libraries/AP_Proximity/AP_Proximity.cpp
> +        if (get_orientation(i) == MAV_SENSOR_ROTATION_PITCH_90) {
should be an AP_Enum<uint8_t>

2021-01-13 08:13 UTC, closed without merging