Proximity avoidance must obey enable flags
ArduPilot/ardupilot pull request #16273
Opened 2021-01-08 16:20 UTC by amilcarlucas

2021-01-09 21:24 UTC, khancyr commented on libraries/AC_Avoidance/AC_Avoid.cpp
> +        if (fence && (fence->get_enabled_fences() & AC_FENCE_TYPE_ALT_MAX) > 0) {
this part ins't good as in case we don't have fence or it is disable, we will now waste time on get the z pos.

2021-01-09 21:32 UTC, khancyr requested changes
the first commit isn't NFC as it change the behavior slightly.
the renaming change is ok.

The second commit is ok, it ensure that we have enable the proximity enable and setted to be used before trying to use upward limitation

2021-02-18 10:43 UTC, amilcarlucas commented
re-trigger test now that https://github.com/ArduPilot/ardupilot/pull/16651 got merged. I should use that one as a template to test this one :)

2024-02-20 15:41 UTC, amilcarlucas commented
Bitrot, so closing it.

2024-02-20 15:41 UTC, closed without merging