Autotest: check for empty message before trying to use it
ArduPilot/ardupilot pull request #16389
Opened 2021-01-20 11:09 UTC by khancyr

2021-01-20 11:48 UTC, amilcarlucas approved these changes
good catch. LGTM

2021-01-21 05:45 UTC, peterbarker requested changes
Looks good apart from one I'd like to keep for the moment.

2021-01-21 05:45 UTC, peterbarker commented on Tools/autotest/common.py
> -                if verbose:
This one was entirely intentional.  I'd prefer to keep it for the time being.

2021-01-21 14:25 UTC, khancyr commented
change done !

2021-02-03 01:55 UTC, peterbarker approved these changes

2021-02-03 01:56 UTC, merged

2021-02-03 01:56 UTC, peterbarker commented
Merged, thanks!