Plane swarm
ArduPilot/ardupilot pull request #16417
Opened 2021-01-22 05:50 UTC by shreya-kulsh

This set of code implements follow-mode for ArduPlane. Note that is does not include a robust velocity controller, but should be able to maintain offsets between multiple vehicles.

2021-01-22 08:16 UTC, khancyr requested changes
Hello, 
Thanks for this, that is nice !
It will need some rework and little corrections ! 
The Follow mode implementation is correct as based on the guided mode. We can live without the velocity controller for now !
The mode implementation is covered by an autotest that is the same the copter one.

The commits need some squashing and cleanup.
We are regrouping commit by feature and files changes.
So you should have as commits : 
- Plane: add Follow mode
- Autotest: move global_position_int_for_location to common.py
- Autotest: plane: add Follow test 
- SITL: add plane follow example scripts
You can use the instructions on https://ardupilot.org/dev/docs/git-interactive-rebase.html for how to do it. Ask on Discord for assistance on git rebasing if you need !

2021-01-22 08:16 UTC, khancyr commented on ArduPlane/mode_follow.cpp
> +        if (now - last_notify > 1000) {
this is just dead code now !

2021-01-22 08:16 UTC, khancyr commented on Tools/autotest/arduplane.py
>          self.fly_home_land_and_disarm()
this shouldn't be removed from the loiter test !

2021-01-22 08:16 UTC, khancyr commented on Tools/autotest/arduplane.py
> +    def fly_follow_mode(self):
this is the same as copter one. Maybe we could transfer it to common.py

2021-01-22 08:16 UTC, khancyr commented on libraries/SITL/examples/test/swarm_test1.sh
> +#!/bin/bash
same

2021-01-22 08:16 UTC, khancyr commented on libraries/SITL/examples/test/plane_sim.sh
> +# three plane swarm (no set formaiton)
this file is useless we could remove it

2021-01-22 08:16 UTC, khancyr commented on libraries/SITL/examples/test/plane_formation.sh
> +# three plane swarm (x offset formation)
move the plane into the follow directory, and rename to plane_3_formation or something like that

2021-01-22 08:16 UTC, khancyr commented on libraries/SITL/examples/test/swarm_test1.sh
> +# two plane swarm (x offset formation)
move to follow directory and rename to plane_2_follow or something like that

2021-02-17 11:41 UTC, EosBandi commented
Apparently, your code does not handle offsets at all. The get_target_location_and_velocity just returns the estimated location and velocity of the lead plane, but then offsets are not added anywhere. So all follow planes just chasing the lead plane, without any offsets.....

2021-07-14 07:27 UTC, khancyr commented
Hello,

There is a lot to be done to address review. I will close this for now. Feel free to reopen when you something more ready to merge.
thanks anyway

2021-07-14 07:27 UTC, closed without merging