AP_UAVCAN: Broadcast ArmingStatus regularly
ArduPilot/ardupilot pull request #16423
Opened 2021-01-22 22:30 UTC by WickedShell

This allows us to regularly broadcast the `ArmingStatus` message for UAVCAN nodes to use to make decisions. I'm looking to use this on AP_Periph nodes for example to dictate what they should be doing.

Validated on a CubeOrange using SLCAN.

2021-01-22 22:34 UTC, tridge requested changes
indentation looks odd?

2021-01-22 22:34 UTC, tridge commented on libraries/AP_UAVCAN/AP_UAVCAN.cpp
> +            return;
needs to be a break?

2021-01-22 22:35 UTC, tridge commented on libraries/AP_UAVCAN/AP_UAVCAN.cpp
> +    ardupilot::indication::SafetyState safety_msg;
could be inside the {}

2021-01-22 22:43 UTC, WickedShell commented on libraries/AP_UAVCAN/AP_UAVCAN.cpp
> +            return;
Fixed.

2021-01-22 22:43 UTC, WickedShell commented on libraries/AP_UAVCAN/AP_UAVCAN.cpp
> +    ardupilot::indication::SafetyState safety_msg;
Fixed.

2021-01-22 23:52 UTC, WickedShell commented
I've added the `AP_Periph` hook to set the soft armed state. This allows the AP_Periph build to do things like unmount the GPS's SD card if `GPS_RAW_DATA` is set to 2. We still need to do somethings to improve the remounting, but this is much better for the general single flight mapping case.

2021-02-01 23:57 UTC, tridge approved these changes

2021-02-01 23:57 UTC, merged