Copter Mode enum class
ArduPilot/ardupilot pull request #16444
Opened 2021-01-26 12:14 UTC by khancyr

This change Copter mode enum to enum class and move them to the mode class to limit their scope.

This is mostly a renaming, that doesn't bring changes. The enum class bring scope and type safety on compile time. The move into the class scope should reduce compile time.

Those change are covered by the compiler and autotest

2021-01-26 13:35 UTC, amilcarlucas commented
Can the value of those enums be validated against Mavlink enum values using static asserts on a separated PR?

2021-01-26 20:16 UTC, khancyr commented
those internal mode and aren't related to mavlink

2021-01-26 23:02 UTC, rmackay9 requested changes
In general it looks good but a few things I noticed:

- S-curves is getting close so I'd prefer we don't make any changes to mode_auto.cpp until that goes in
- Having classes called "ModeGuided" and "GuidedMode" seems confusing and although it is at least partially an existing issue I think we should call these sub modes.
- If we change from camel case to all caps or small let's use underscores between words.  I.e PathFollow should become PATH_FOLLOW or path_follow.

Txs!

2021-01-27 00:23 UTC, peterbarker commented
On Tue, 26 Jan 2021, Randy Mackay wrote:

>  *  Having classes called "ModeGuided" and "GuidedMode" seems confusing and although it is at least partially an existing issue I think we should call
>     these sub modes.

I thought the same thing....

ModeGuided::SubMode::TAKEOFF?

2021-04-13 15:49 UTC, khancyr commented
rebased, cleanup, switch to SubMode syntax and separate words !
I have remove Guided mode changes to not collide with https://github.com/ArduPilot/ardupilot/pull/17162

2021-04-29 10:07 UTC, peterbarker requested changes
I really do like this change.

... but it does show the downside of doing a global replace without checking every substitution.

2021-04-29 10:07 UTC, peterbarker commented on ArduCopter/mode_rtl.cpp
> +// rtl_LOITER_AT_HOME_start - initialise return to home
Well, the initial comment was wrong - I'm not sure if this is wronger or not.

2021-04-29 10:07 UTC, peterbarker commented on ArduCopter/mode_rtl.cpp
> +// rtl_RETURN_HOME_run - return home
Even more wrongerer.  Not even the name of the function here.

2021-04-29 10:16 UTC, khancyr commented
Comments rename corrected !

2021-04-29 10:20 UTC, peterbarker requested changes
Comment incorrect.  Should fix it while we're here.

2021-04-29 10:20 UTC, peterbarker commented on ArduCopter/mode_rtl.cpp
> +// land_run - return home
```suggestion
// land_run - run the landing controllers to put the aircraft on the ground
```

2021-04-29 10:25 UTC, peterbarker approved these changes
LGTM

2021-04-29 10:29 UTC, peterbarker commented
Labelled it DevCall in case Randy doesn't see it before then

2021-04-30 00:40 UTC, rmackay9 requested changes
I think it's confusing to have different enums with the same name in each class especially because they are public.  I think we should either make the SubMode enum private or change its name to make it different for each mode.  I.e. RTLSubMode or make it private.

2021-04-30 01:53 UTC, peterbarker commented
On Thu, 29 Apr 2021, Randy Mackay wrote:

> I think it's confusing to have different enums with the same name in each class especially because they are public. I think we should either make the SubMode enum private or change its name to make it different for each mode. I.e. RTLSubMode or make it private.

*Everywhere* outside - from an enforced, C++, perspective would have
to reference the enumeration values as ModeRTL::RTLSubMode::LAND - nobody 
outside ModeRTL can use its submode without having ModeRTL:: on the front. 
That's the advantage of having it inside the ModeRTL class definition, 
after all.

public/private is actually irrelevant here.  If you're not a function in 
ModeRTL then you can ONLY reference its SubMode by include "ModeRTL" in 
the enumeration value name.

2021-04-30 02:04 UTC, rmackay9 commented
I think there's still an argument for making the submode private because there should be no need for an external user to know about it.

2021-04-30 10:02 UTC, khancyr commented
I think that won't be an issue to put the enum in private, I will do it

2021-05-01 04:13 UTC, peterbarker commented
On Fri, 30 Apr 2021, Pierre Kancir wrote:

> I think that won't be an issue to put the enum in private, I will do it

Pretty sure you can't as places outside the class are using it.  But they 
*must* prefix it with ModeRTL:: so there's no confusion.

2021-05-04 07:16 UTC, khancyr commented
Hum, we cannot put them into private anyways. And as Peter said that is scope constraint to class access so that shouldn't be an issue

2021-05-12 07:02 UTC, rmackay9 approved these changes
OK, sorry for the delay, approved thanks!

2021-05-12 07:50 UTC, merged