Altframe hooks
ArduPilot/ardupilot pull request #16452
Opened 2021-01-27 19:13 UTC by QuPsi

Introduces ability to set the fence max altitude frame. Also includes @peterbarker's param-validate functionality.

2021-01-27 20:24 UTC, amilcarlucas commented
Looks like you are reverting some changes from master by accident. My guess is that a couple of merge conflicts went south.
You should fix that first

2021-02-03 01:24 UTC, peterbarker requested changes
I can see some uses, but I am curious - what is your need to be able to specify the altitude frame of the altitude fences?

2021-02-03 01:24 UTC, peterbarker commented on libraries/AP_Common/Location.cpp
> +bool Location::get_spec_alt_cm(AltFrame current_frame, AltFrame desired_frame, int32_t alt_conv, int32_t &ret_alt_cm) const
```suggestion
bool Location::convert_altitude_frame(AltFrame current_frame, AltFrame desired_frame, int32_t alt_in_cm, int32_t &alt_out_cm) const
```

2021-02-03 01:24 UTC, peterbarker commented on libraries/AP_Common/Location.h
> +    bool get_spec_alt_cm(AltFrame current_frame, AltFrame desired_frame, int32_t _alt_conv, int32_t &ret_alt_cm) const;
This should be static, yes?

2021-02-03 01:24 UTC, peterbarker commented on libraries/AP_Param/AP_Param.cpp
> +#include <signal.h>
Why is this included?

2021-02-03 01:24 UTC, peterbarker commented on ArduCopter/system.cpp
> +    if ((int)newframe > 3 || (int)newframe < 0) {
This would be better done as a `switch`, enumerating the valid values.

2021-02-03 01:24 UTC, peterbarker commented on ArduCopter/system.cpp
> +    } else {
Pointless `else`

2021-02-03 01:24 UTC, peterbarker commented on ArduCopter/system.cpp
> +        return AP::fence()->conv_max_alt_frame((int)newframe);
These validation routines were never meant to modify values - only validate them.

Coupling parmeters like this is going to lead to all sorts of confusion.  Pretty sure we want to leave it up to the user to set both the frame and altitude at the same time.

2021-02-03 01:24 UTC, peterbarker commented on ArduPlane/Parameters.cpp
> -#if MAVLINK_COMM_NUM_BUFFERS >= 2
These are the changes you're reverting when you shouldn't be.

2021-02-03 01:24 UTC, peterbarker commented on libraries/AC_Fence/AC_Fence.h
> +        AP_Param::set_and_save_by_name("FENCE_ALT_FRAME", AC_FENCE_ALT_FRAME_DEFAULT);
This definitely doesn't look right.  What happened to people's persistence here?!

2021-02-03 01:24 UTC, peterbarker commented on libraries/AP_Param/AP_Param.h
> +#define AP_PARAM_FLAG_NO_SHIFT           (1<<3)
Bad whitespace change.

2021-02-03 01:24 UTC, peterbarker commented on libraries/AP_Param/AP_Param.h
> +#include <stdio.h>
Why?

2021-02-03 01:24 UTC, peterbarker commented on libraries/GCS_MAVLink/GCS_Param.cpp
> -    while (count && _queued_parameter != nullptr && get_last_txbuf() > 50) {
Another master change reverted.  Not good.

2021-02-17 17:31 UTC, amilcarlucas commented
Do not merge master into this branch. Instead rebase this branch on top of master.
Instructions are here: https://ardupilot.org/dev/docs/git-interactive-rebase.html

2021-08-25 04:07 UTC, peterbarker commented
Closing in favour of https://github.com/ArduPilot/ardupilot/pull/18038

2021-08-25 04:07 UTC, closed without merging