move handling of last-seen-SYSID_MYGCS up to GCS base class
ArduPilot/ardupilot pull request #16515
Opened 2021-02-04 11:27 UTC by peterbarker

2021-02-04 11:27 UTC, peterbarker commented
Needs to be split into multiple commits.

2021-04-01 09:12 UTC, peterbarker commented
SITL-tested.

Tested that normal GCS failsafes work across Rover (including manual_control messages), Plane and Copter.

Checked that AFS works in Plane.

2021-04-06 00:04 UTC, tridge requested changes

2021-04-06 02:43 UTC, peterbarker reviewed
All fixed.

2021-04-06 02:43 UTC, peterbarker commented on ArduCopter/GCS_Mavlink.cpp
> +        gcs().sysid_myggcs_seen(AP_HAL::millis());
Fixed

2021-04-06 02:43 UTC, peterbarker commented on ArduPlane/GCS_Mavlink.cpp
> +        gcs().sysid_myggcs_seen(AP_HAL::millis());
Fixed

2021-04-06 02:43 UTC, peterbarker commented on ArduPlane/system.cpp
> +    const uint32_t gcs_last_seen_ms = gcs().sysid_myggcs_last_seen_time_ms();
Fixed

2021-04-06 02:43 UTC, peterbarker commented on libraries/AP_AdvancedFailsafe/AP_AdvancedFailsafe.cpp
> +    const uint32_t last_heartbeat_ms = gcs().sysid_myggcs_last_seen_time_ms();
Done

2021-04-07 07:53 UTC, tridge approved these changes

2021-04-07 07:54 UTC, merged