Add RTL_CLIMB_MIN test for ArduPlane
ArduPilot/ardupilot pull request #16565
Opened 2021-02-09 02:27 UTC by peterbarker

This clearly reproduces the flight characteristics in https://github.com/ArduPilot/ardupilot/issues/16532

![image](https://user-images.githubusercontent.com/7077857/107307137-3fc19c80-6ada-11eb-81b6-25d965dabb2c.png)

The test *fails* as it is expected the vehicle should maintain the higher altitude.  The code is quite clear clear - we only add the extra altitude until we've finished the climb:
```
        if (control_mode == &mode_rtl && !rtl.done_climb && g2.rtl_climb_min > 0) {
            // ensure we do the initial climb in RTL. We add an extra
            // 10m in the demanded height to push TECS to climb
            // quickly
            target_alt = MAX(target_alt, prev_WP_loc.alt + (g2.rtl_climb_min+10)*100);
        }
```

2021-02-09 02:33 UTC, WickedShell commented
Personally I'd rather have this be a bit more copter like where it was actually a `RTL_MIN_ALTITUDE` where it will climb to that height above home at a minimum and do so quickly with the roll limit, or climb to the RTL altitude whichever was higher and hold it.

Also if we are asking for scope creep I'd *very strongly* prefer that if we have a climb commanded by RTL we do it at max climb rate rather then build a slope to the rally point like we currently do. It makes planning around tall obstructions difficult.

2021-02-09 03:41 UTC, peterbarker commented
On Mon, 8 Feb 2021, WickedShell wrote:

> Also if we are asking for scope creep I'd very strongly prefer that if we have a climb commanded by RTL we do it at max climb rate rather then build a

There's no scope creep here at all.  All I've done is replicated the 
flight behaviour, not attempted to fix it :-P

I'm not even sure that the current behaviour isn't what the original 
author envisaged!

2021-02-09 14:46 UTC, skorokithakis commented
I *think* this is a bug in the original code. I believe the original author meant to only add the 10m during the initial climb so that the TECS climbs faster, but then didn't realize that the new target altitude needed to account for the extra addition after the climb was done.

2021-02-10 01:56 UTC, peterbarker commented
I've added a change to the ArduPlane code in this PR now.  Now the flight profile looks like this:

![image](https://user-images.githubusercontent.com/7077857/107453525-3f3f0980-6b9f-11eb-9484-79064663cac0.png)

So after the climb is done we reset the previous wp location to our current location and recalculate our glide slope home.

i.e. we do NOT maintain our new altitude all the way home; we descend linearly to our parameterised RTL altitude.

2021-02-10 07:30 UTC, tridge requested changes

2021-02-10 07:30 UTC, tridge commented on Tools/autotest/arduplane.py
> +        expected_alt = self.get_parameter("ALT_HOLD_RTL")/100.0
maybe check half way if it is within a margin of mid-point of RTL alt and climb min + start alt

2021-02-10 07:33 UTC, skorokithakis commented
Thanks, that's what I would expect. What's the reason for the bump in the graph, instead of completely linear descent?

2021-02-10 08:03 UTC, peterbarker commented
> Thanks, that's what I would expect. What's the reason for the bump in the graph, instead of completely linear descent?

Poor TECS tuning on the simulated aircraft is our guess.

2021-02-12 20:54 UTC, skorokithakis commented
Is there anything else that needs to be done here? Can I help?

2021-02-13 08:34 UTC, peterbarker commented
@skorokithakis tridge just asked for the test to be augmented, which I've now done.  

I'm going to merge this - but if you can test fly it and report it fixes the problem, please do :-)

2021-02-13 08:34 UTC, merged

2021-02-13 09:40 UTC, skorokithakis commented
Thank you, I can! Is master in a stable state/safe to fly, generally?

2021-02-14 07:32 UTC, peterbarker commented
On Sat, 13 Feb 2021, Stavros Korokithakis wrote:

> Thank you, I can! Is master in a stable state/safe to fly, generally?

Generally, if you're a confident manual pilot, yes.  Just remember your 
"two mistakes high" :-)  (we don't generally tell people to fly master, 
but its generally fine)

2021-02-14 09:48 UTC, skorokithakis commented
Ah good, I do usually fly manual, so it should be okay. I just won't stray out of video range, thanks!