Add flake8 checking to CI tests
ArduPilot/ardupilot pull request #16592
Opened 2021-02-11 01:18 UTC by peterbarker

This adds a step in our CI testing that checks Python files pass flake8 tests.

Only files including a special `AP_FLAKE8_CLEAN` marker are checked for cleanliness.

I've added `AP_FLAKE8_CLEAN` to the new CI script itself(!), and to `autotest.py` after tidying it up (again).  I expect more to grow this marker as they're cleaned up.

I've also added a script here which can be used as a git pre-commit hook.  It checks `.py` files which are staged (for either create or modify) with flake8 and fails the commit if they are not compliant.  This can stop bad Python getting into your commits in the first place.

Note that we already have some flake8 tests (supposedly?) running on Semaphore, so the use of the pre-commit hook could already save aggravation.

2021-02-16 00:00 UTC, rmackay9 commented on Tools/autotest/common.py
> +                self.last_heartbeat_time_wc_s = now_wc
this looks like a real bug fix which seems good.

2021-02-16 00:04 UTC, tridge requested changes

2021-02-16 00:04 UTC, tridge commented on Tools/autotest/common.py
> +        self.dataid_GPS_ALT_BP          = 0x01  # noqa
i don't think we want this

2021-02-16 00:04 UTC, tridge commented on Tools/autotest/common.py
> +        self.SENSOR_ID_VARIO             = 0x00 # Sensor ID  0  # noqa
avoid noqa

2021-02-17 00:06 UTC, peterbarker commented on Tools/autotest/common.py
> +        self.dataid_GPS_ALT_BP          = 0x01  # noqa
Removed.

2021-02-17 00:07 UTC, peterbarker commented on Tools/autotest/common.py
> +        self.SENSOR_ID_VARIO             = 0x00 # Sensor ID  0  # noqa
done

2021-02-17 00:08 UTC, peterbarker commented on Tools/autotest/common.py
> +        if (
fixed.

2021-02-17 00:31 UTC, peterbarker commented
```
pbarker@bluebottle:~/rc/ardupilot(pr/flake8-clean)$ ./Tools/scripts/run_flake8.py 
****** Checking (Tools/scripts/run_flake8.py)
****** Checking (Tools/gittools/pre-commit.py)
****** Checking (Tools/autotest/arduplane.py)
****** Checking (Tools/autotest/ardusub.py)
****** Checking (Tools/autotest/rover.py)
****** Checking (Tools/autotest/common.py)
****** Checking (Tools/autotest/autotest.py)
****** Checking (Tools/autotest/antennatracker.py)
pbarker@bluebottle:~/rc/ardupilot(pr/flake8-clean)$ 
```

2021-02-17 07:47 UTC, tridge commented
happy to merge when passes CI

2021-02-17 07:47 UTC, tridge approved these changes

2021-02-17 23:43 UTC, merged