Update analog.cpp
ArduPilot/ardupilot pull request #16607
Opened 2021-02-12 11:14 UTC by rotorman

IMO the fivision should be with 4095, instead of 4096, as max value with 12-bit ADC is 4095.

2021-02-12 11:49 UTC, amilcarlucas commented
Please change the commit message to:
"AP_IOMCU: 12-bit ADC scaling-division should be with 4095, instead of 4096, as max value is 4095"

2021-02-12 11:51 UTC, amilcarlucas commented
Can you please edit the description of the first github comment to add:

Closes #16600

2021-02-12 12:37 UTC, khancyr requested changes
I am pretty sure that the 4096 is right as that the number of step between values.

Until somebody more experienced than me review this, could you also change the value line 77 that should match ?

2021-02-12 13:15 UTC, rotorman commented
@khancyr Please consider the following example of what the output would be if the adc_sample_channel(channel) returns 4095 (12-bit ADC max value): `4095 * 9900 / 4096` = 9897 if math.floored (what uint will do), or 9898 when nicely explicitly rounded.
Both are incorrect, as what we want is the max value to output 9900.

2021-02-12 13:18 UTC, rotorman commented
And true, the same applies to couple of lines above (I was working only with RSSI, did not notice the other issue in the same file as well):
https://github.com/ArduPilot/ardupilot/blob/f107ce395190f25e4189a163c2bdccefa73262b5/libraries/AP_IOMCU/iofirmware/analog.cpp#L78

2021-02-12 13:21 UTC, amilcarlucas commented
Thanks for fixing the PR title.

But my comment was towards the git commit message.

2021-02-12 13:24 UTC, rotorman commented
Too dumb to find option to change the commit message (tip would be appreciated, glad to do it).
Does squash mean join? How to do that? I'm working directly via GitHub WebGUI.

2021-02-12 13:27 UTC, amilcarlucas commented
https://ardupilot.org/dev/docs/git-interactive-rebase.html#git-interactive-rebase

2021-02-12 13:41 UTC, rotorman commented
I tried my very best, probably did mess smth up as now I see 4 commits instead of desired 1...

2021-02-12 13:53 UTC, olliw42 commented
you should do * 9903/4096 and not * 9900/4095 ...

;)

2021-02-13 15:33 UTC, rotorman commented
@olliw42 9900/4095 is more easy for human to understand and also gives the correct output. 4095 is the highest value output from the ADC and this should be used as the divisor to reach 1.0 before multiplying with the new range (=9900).

@amilcarlucas I am terribly sorry for apparently not able to fix the GIT commits. I tried also the _git rebase -i "HEAD~1"_ d option just to remove the commit, but it did not seem to work as I expected - my naive idea was to remove the commit altogether and then recreate it. I have years of experience with SVN, but close to nil with GIT and even though the basic concepts are similar, the details are very different.
In case there is no "god" mode from you to do it, what I can offer is to close this PR and recreate it from scratch including both edited lines included from the start. Let me know if this is something that would be OK? Or if not, would it be possible you to instruct me with the commands to issue?

2021-02-13 17:31 UTC, olliw42 commented
> @olliw42 9900/4095 is more easy for human to understand and also gives the correct output. 4095 is the highest value output from the ADC and this should be used as the divisor to reach 1.0 before multiplying with the new range (=9900).

LOL ... you completely miss the point
anyways

2021-02-13 17:47 UTC, rotorman commented
Enlighten me please

2021-02-15 09:58 UTC, amilcarlucas commented
You need to do "git rebase -i" like explained in the link I posted.

2021-02-15 11:37 UTC, rotorman commented
I tried the git _rebase -i "HEAD~10"_ now for the third time, selecting both my _Update analog.cpp_ lines, marking with s instead of pick and saving. Then did the pull. Is it now in a desired state?

2021-02-15 11:52 UTC, amilcarlucas commented
You should only keep commit  9516214 and discard ALL others
@rotorman please give me permissions to write on your repository. Then I can fix it.

2021-02-15 13:18 UTC, rotorman commented
@amilcarlucas Thank you for trying to help me. I tried again _git rebase -i "HEAD~10"_ this time marking with d all other commits, saving the file and doing a push. But I have likely still not understood how rebasing works, as these changes do not not seem to come up to github. I do need to push after rebasing, don't I?
Anyhow, I have invited you to be a collaborator (I guess this is what you meant with write access)?

2021-02-15 13:33 UTC, amilcarlucas commented
yes you need to do:
git push -f

After the rebase

2021-02-15 13:47 UTC, rotorman commented
That worked, thanks! I guess the **-f** option was the magic I was missing (was not written unfortunately in the [docu ](https://ardupilot.org/dev/docs/git-interactive-rebase.html#git-interactive-rebase) you linked).
Previously I was using TortoiseGit, it does not seem to have a force option in the push menu at all, so probably the method only works from command line.

2021-02-15 13:56 UTC, amilcarlucas commented
@rotorman yes, now it is clean.

@olliw42 can you answer the question?

2021-02-15 19:30 UTC, rotorman commented
I discovered much bigger issue related to RSSI handling with IO_MCU, so will do a new PR including further bugfixes. Not only was the division wrong, it is completely unnecessary, also the code processing this in main flight µC handles the RSSI data wrong here:
https://github.com/ArduPilot/ardupilot/blob/97c1445bce447488eee42f53b8976ef0d50a368b/libraries/AP_HAL_ChibiOS/AnalogIn.cpp#L331

This all now explains the issue #16451 that triggered me to look into it. Give me some time to propose a fix for this all.

2021-02-15 20:20 UTC, rotorman commented
The latest rebase should now fix not only the issue with division, but much bigger problem of analog RSSI being fully saturated at 1.36V on 3.3V scale when using IOMCU (see #16451), e.g. Holybro Durandal with H743 main CPU and STM32F100 I/O MCU.

My proposal first fixes the conversion of the input signal to the range of 0 to 3300 (instead of previously fully meaningless 0 to 9897) (see changed lines of libraries/AP_IOMCU/iofirmware/analog.cpp)

This IOMCU value is passed via internal UART communication to FMU main processor and read with:
https://github.com/ArduPilot/ardupilot/blob/97c1445bce447488eee42f53b8976ef0d50a368b/libraries/AP_IOMCU/AP_IOMCU.h#L87
that converts the (0 to 3300 value) to range of 0 to 3.3 [V] (finally SI units...)

This gets converted back to 0 to 4095 by:
https://github.com/ArduPilot/ardupilot/blob/97c1445bce447488eee42f53b8976ef0d50a368b/libraries/AP_HAL_ChibiOS/AnalogIn.cpp#L331

@khancyr and @tridge please review my modified 2 files - thank you!

2021-02-15 21:05 UTC, rotorman commented
@khancyr in the discussion above, you had doubts about my suggestion of division with 4095 being correct.

Please also see e.g.:
https://github.com/ArduPilot/ardupilot/blob/97c1445bce447488eee42f53b8976ef0d50a368b/libraries/AP_HAL_Linux/AnalogIn_IIO.h#L14-L19
also there 4095 is used. The goal for the division is to normalize the input (thus scale it from 0 to 1.0). Division with 4096 would not give 1.0 with max ADC output -> 4095/4096 is less than 1.0f.

2021-02-16 07:07 UTC, rotorman commented
Hold on, just had a look at Holybro Durandal I/O MCU board. Although the change is correct for RSSI (3.3V gets directly input to STM32F100 PA5, the servo rail is sampled via voltage divider circuit (33K and 16K9), which means it's scaling is other. I will fix this ASAP.

2021-02-16 07:28 UTC, rotorman commented
Now with correct conversion for the VSERVO rail as well (has 33K/16K9 voltage divider circuit in-between STM32F100 PA4 and VDD_SERVO), thus ADC full scale is reached with 3.3*(33+16.9)/16.9 = 9.744V. Whereas RSSI signal is directly sampled with PA5 pin (just 10K protective resistor between).

2021-02-16 11:19 UTC, rotorman commented
sitltest-plane fails for FrSky SPort mode, I did not find any hints on how my changes proposed might have something to do with FrSky Sport. @amilcarlucas Can you help out? How can I trigger to rerun the sitltest-plane?

2021-02-16 19:02 UTC, rotorman commented
I just tested my proposal on real hardware (Holybro Durandal) and it now works as expected - full RSSI range (0 to 3.3V is now used).

But it was very tricky to flash the I/O MCU via FMU. I did not manage to flash it with ArduPilot, by holding the Safety Button, it just did not work.

So I flashed PX4 fw, put the custom compiled iofirmware_lowpolh.bin onto a microsd card and opened nsh shell.
There with issuing `px4io forceupdate 14662 /fs/microsd/iofirmware_lowpolh.bin` I was able to flash it. Then flashed back custom compiled ArduPlane fw and tested rxrssi with Mission Planner - finally works as expected.

But this means there is something wrong in the internal AP_IOMCU flashing routine of ArduPilot as well, as flashing was NOT possible with it.

2021-02-16 19:41 UTC, rotorman commented
Something is wrong with the tests here in GitHub.
I did change only a comment in the last rebase and now sitltest-plane passes (where it previously failed) and sitltest-copter-tests2b fails???

2021-02-17 16:34 UTC, rotorman commented
Fun fact, just changed a comment and now all checks passed... so there was something funky going on with the tests the last 2 days.

2021-02-18 20:37 UTC, rotorman commented
@khancyr you added a flag "Needs answer" and removed "bug". Would you please clarify if you need an answer from me, or from Tridge, who you sent this PR to review?

As I verified my proposed changes by flashing them to Durandal I/O MCU, and they surely fix the analog RSSI issue, so I wonder if you could reconsider putting back the "Bug" label?

2021-03-07 11:49 UTC, rotorman commented
I will close this PR and will redo a new one with less chatter in it in the hopes of getting more attention by a project maintainer. The code change works on Holybro Durandal (verified on hardware), but possibly the long discussion here is disturbing. I will also clearly point out in the new PR title that it is for Durandal (not tested with others).

2021-03-07 11:49 UTC, closed without merging