AP_ParticleMatter: Add I2C driver for Panasonic SN-GCJA5
ArduPilot/ardupilot pull request #16628
Opened 2021-02-15 19:10 UTC by jmachuca77

This PR add support for the [Panasonic SN-GCJA5](https://www.sparkfun.com/products/17123) Laser Type Particle Matter sensor. It adds a log message to log the readings from the sensor so that it can be used in surveys.
![17123-Particle_Sensor_-_SN-GCJA5-01](https://user-images.githubusercontent.com/1664405/107984090-5ce7e680-6f84-11eb-9fa6-aa813800e72f.jpg)

This has been flight tested by Oliver Wolkman on plane and rover.

2021-02-15 19:40 UTC, WickedShell commented
I don't see a path where this helps any of the core flight code. I think this is probably best done by using @IamPete1's I2C bindings for scripting and leaving the logging of the sensor as a script, rather then adding it to ArduPilot as a core library/dependency we have to maintain.

2021-02-15 20:11 UTC, khancyr requested changes
The SITL backend isn't write.

As @WickedShell said, this doesn't bring any value to the autopilot. I understand it can be useful on a rover to map the PM density in a house but it doesn't serve on general purpose.
Now that we have LUA script, IOT sensor should be on LUA

2021-02-15 20:11 UTC, khancyr commented on ArduCopter/Copter.cpp
> +    SCHED_TASK_CLASS(AP_PM_SNGCJA5,       &copter.sngcja5,          update,          1,  100),
this should at least be unclosed by some #if to not be included by default

2021-02-15 20:11 UTC, khancyr commented on libraries/AP_ParticleMatter/AP_PM_SNGCJA5.cpp
> +    gcs().send_text(MAV_SEVERITY_INFO, "No SNGCJA5 found");
this will spam

2021-02-15 20:11 UTC, khancyr commented on libraries/AP_ParticleMatter/AP_PM_SNGCJA5.cpp
> +    double  PM1_0  = (ALL_REGS[0] | ALL_REGS[1] << 8 | ALL_REGS[2] << 16 | ALL_REGS[3] << 24);
pretty sure we don't need double here ?

2021-02-15 20:11 UTC, khancyr commented on libraries/AP_ParticleMatter/AP_PM_SNGCJA5.cpp
> +    int     PC0_5  = (ALL_REGS[12] | ALL_REGS[13] << 8);
int16_t ?

2021-02-15 20:11 UTC, khancyr commented on libraries/AP_ParticleMatter/AP_PM_SNGCJA5.cpp
> +    dev->register_periodic_callback(1000000, FUNCTOR_BIND_MEMBER(&AP_PM_SNGCJA5::read_frames, void));
so we get it from the thread and from the vehicle code at 1Hz ?

2021-02-15 23:14 UTC, tridge commented
This driver should be done as a Lua script. The driver as written uses flash space on all boards, whereas if done as a lua script then it only gets used on boards where it is installed.
The general answer if we don't think drivers for sensors that have nothing to do with flight control should be in the core firmware, instead they should be done as example lua scripts.

2021-02-16 01:18 UTC, rmackay9 commented
@jmachuca77, by the way, PeterB added a PR a few months ago that added support for a air quality sensor and we didn't merge it for the same reason.  So you're not alone, but I guess for now at least, we're hoping developers will be ok with writing a lua script for sensors that aren't used directly for flight control.

2021-02-16 07:08 UTC, rmackay9 commented
I think I will close this if that's OK.  Of course there's a lot of work that's gone into this so it is a bit of a shame in that way but as mentioned above at this time we're not looking to add support for drivers that aren't used in some way for flight control.  I'll be monitoring responses of course and so happy to re-open if more discussion is required.

2021-02-16 07:08 UTC, closed without merging