Remove separate calls to get delta-times for vel and ang
ArduPilot/ardupilot pull request #16622
Opened 2021-02-14 23:01 UTC by peterbarker

It is almost always going to be an error to use the delta-angle without the corresponding delta-angle-dt, so make the caller get both.

This shows up places where we *aren't* using both; the AP_AHRS_DCM case is interesting as we *do* use the delta-velocity-dt but don't use the delta-angle-dt.  We should probably be dividing by dellta_angle_dt then multipling by our own _dt (or similar).

I just moved the logic from the time-getters into the value-getters.

I haven't fixed any of the callers as this should be essentially NFC.

2021-02-15 23:23 UTC, tridge requested changes

2021-02-15 23:23 UTC, tridge commented on ArduCopter/mode_flowhold.cpp
> +    float delta_vel_dt;  // FIXME: this should be used!
why should it be used? It wants the change in velocity. It doesn't want the rate of change, so the time doesn't matter

2021-02-17 00:41 UTC, peterbarker commented
I have removed the `FIXME` comments from this PR.

2021-02-17 07:59 UTC, tridge approved these changes

2021-03-13 00:29 UTC, peterbarker commented
Merging after flight-testing on a Copter.

2021-03-13 00:29 UTC, merged