Push SITL reboot ACK out before exec'ing
ArduPilot/ardupilot pull request #16676
Opened 2021-02-19 22:30 UTC by peterbarker

I've seen instances where the process goes away before the ACK arrives at the autotest process.  Try really hard to make sure it's been sent.

2021-02-22 23:52 UTC, tridge requested changes

2021-02-22 23:52 UTC, tridge commented on libraries/AP_HAL_SITL/UARTDriver.cpp
> +    uint32_t available;
no infinite loops please

2021-03-01 03:15 UTC, peterbarker commented on libraries/AP_HAL_SITL/UARTDriver.cpp
> +    uint32_t available;
Fixed.

2021-04-04 03:15 UTC, peterbarker commented
Infinite loops removed.

2021-04-06 00:21 UTC, tridge approved these changes

2021-04-06 00:21 UTC, merged