Handle MAV_CMD_DO_SET_MISSION_CURRENT
ArduPilot/ardupilot pull request #16687
Opened 2021-02-21 08:41 UTC by peterbarker

We have a normal message which we use to do this, relying on the `CURRENT_CURRENT` message to provide confirmation of the change.

There does exist this MAV_CMD_DO_SET_MISSION_CURRENT message which will provide an acknowledgement, however neither QGC nor the `PX4 Firmware` project appear to have support for it in their master branch.

It is a state change on the aircraft, and those are supposed to be accomplished with commands rather than messages....

2021-02-22 23:34 UTC, tridge requested changes

2021-02-22 23:34 UTC, tridge commented on libraries/GCS_MAVLink/GCS_Common.cpp
> +    if (!mission->set_current_cmd(seq)) {
does this handle seq==0 for resetting mission?

2021-02-22 23:34 UTC, davidbuzz commented
might be worth a comment in the code that this is an alternative to a more common packet.?

2021-02-22 23:37 UTC, tridge approved these changes

2021-02-23 04:10 UTC, peterbarker commented
I've added some comments to clarify old and new methods.

I've added the extra handling for Plane for when the waypoint is changed via mavlink.

I've got concerns about scripting's access to the mission library; it may not reset Plane's state correctly if it is only dealing with the Mission library's set-waypoint command.

2021-03-02 00:13 UTC, tridge approved these changes

2021-03-04 00:59 UTC, merged