AC_Circle: Add RESTORE_RADIUS in CIRCLE_OPTIONS
ArduPilot/ardupilot pull request #16757
Opened 2021-02-26 20:14 UTC by giacomo892

Allow the pilot to reload the circle radius from the parameters every time CIRCLE mode is enabled.

It is nice from a safety point of view. Had my copter heading towards a tree because I supposed the circle to be 10m in radius, instead it was much higher due to me having adjusted it with the pitch stick in a previous use of CIRCLE mode.

2021-02-26 23:29 UTC, rmackay9 commented
nice work.  I'd like to hear from other devs but I think the circle radius should **always** be restored by re-entering circle mode.  This would avoid the need for the new option or at least it should be defaulted to 1.  The equivalent in Auto mode is the WPNAV_SPEED.  If the user exits Auto and enters again the target speed will be reset to the parameter value.

So if we go with this then we probably need to change AC_CIRCLE so it doesn't directly use the _radius variable but instead has another radius parameter which is used.  set_radius() should only update this temporary value leaving the _radius parameter value unchanged.

2021-02-27 06:56 UTC, giacomo892 commented
Thanks @rmackay9 . Let's wait for other opinions. In the meanwhile i've flight tested this and it works as expected.

I'm not quite sure we should reset the radius every time, since if you start from the perimeter then it might be actually good to keep the user set radius and just continue the circle from where it was stopped.

I guess a good compromise could be to reset the radius by default when the user choose to start the circle from the centre of it since if you start at the perimeter you expect the moves of the machine (going CW or CCW), while if you start from the center of the circle, the machine has to reposition itself and it might head very quickly toward and obstacle. What do you think?

2021-04-07 08:09 UTC, IamPete1 reviewed
Just need to make sure were still using the right radius and not the param value for circles via auto and guided.

2021-04-07 15:22 UTC, giacomo892 commented
@IamPete1 looks like Loiter with turns is broken on master, but this PR will let it use the radius it needs.

@tridge @rmackay9 I've reworked this as discussed. Good for you?

2021-04-07 15:22 UTC, shellixyz commented
Tested with SITL, LGTM :+1:

2021-04-07 19:20 UTC, IamPete1 requested changes
This breaks auto circles, they are done at the param radius rather than the radius given in the mission. I suspect your not testing it correctly because they also seem to be fine on master for me.

To fix I think you just need to set the param value not the internal variable in the set rad call.

https://github.com/ArduPilot/ardupilot/blob/f7da853adbe381481c54441e19f64b1841abc5a6/libraries/AC_WPNav/AC_Circle.cpp#L150

2021-04-07 19:20 UTC, IamPete1 commented on libraries/AC_WPNav/AC_Circle.cpp
> +    _radius=_radius_parm;
```suggestion
    _radius = _radius_parm;
```

2021-04-07 19:20 UTC, IamPete1 commented on libraries/AC_WPNav/AC_Circle.cpp
> +
```suggestion

```

2021-04-07 19:20 UTC, IamPete1 commented on libraries/AC_WPNav/AC_Circle.cpp
> +    _radius=_radius_parm;
```suggestion
{
    //initialize radius from params
    _radius = _radius_parm;
```

2021-04-07 19:20 UTC, IamPete1 commented on libraries/AC_WPNav/AC_Circle.h
> +    AP_Float    _radius;        // radius of circle in cm
```suggestion
    float _radius;        // radius of circle in cm
```
should also be down with the internal variables

2021-04-07 19:24 UTC, IamPete1 commented
Actually my suggestion will break updating the radius from sticks in a mission. You probably need a `set_radius` call that sets the param and a `update_radius` call to change the internal variable. 

Of course this change also means that you cant just change the radius param and have it update in real time. You would have to exit and re-enter circle mode. Not a complaint, just a observation.

2021-04-07 20:28 UTC, giacomo892 commented
Thanks for the review @IamPete1 
I've addressed what you have pointed out and now the radius from AUTO mode should be set correctly. Only when CIRCLE is called as a mode we restore the radius.
What mission element is CIRCLE? Loiter Turns? If I try it in SITL, the copter arrives to the WP and waits there forever.

2021-04-07 20:33 UTC, IamPete1 commented
@giacomo892 Yeah, Loiter turns, you need to give it a number of turns and a radius.

2021-04-08 15:12 UTC, giacomo892 commented
Tested on SITL, working as expected beside https://github.com/ArduPilot/ardupilot/issues/17126

2021-04-09 03:22 UTC, rmackay9 commented on libraries/AC_WPNav/AC_Circle.h
> +    float    _radius;        // radius of circle in cm
Let's move this definition lower down with the other non-parameters.

nitpick: let's get the alignment of comments fixed too. txs!

2021-04-09 03:24 UTC, rmackay9 commented
I thought there was an issue with the get_radius() needing to check if init() had been called or not because there is a code path that calls get_radius() before init is called.  I think it's when the Loiter-turns command has a lat,lon specified.

2021-04-09 06:30 UTC, giacomo892 commented
> I thought there was an issue with the get_radius() needing to check if init() had been called or not because there is a code path that calls get_radius() before init is called. I think it's when the Loiter-turns command has a lat,lon specified.

Thanks for the review. Looks like it is not the case, it seems all good to me.

2021-04-28 08:13 UTC, tridge commented
add _last_radius? @IamPete1 will do a new PR

2021-04-28 10:36 UTC, IamPete1 approved these changes
Re-tested in SITL, works great, Thank you

2021-04-28 10:36 UTC, merged