AP_Vehicle: log internal error and report bitmask to GCS
ArduPilot/ardupilot pull request #16763
Opened 2021-02-28 02:12 UTC by nkruzan

Attempt at resolving https://github.com/ArduPilot/ardupilot/issues/15461 

I have an issue using the sendtext, local build sitl require %x but other board need %lx ? 

I also do not know best way to test, if someone could please advise.

2021-03-01 02:09 UTC, peterbarker commented
> I have an issue using the sendtext, local build sitl require %x but other board need %lx ?

Cast the parameter to `(unsigned)`

> I also do not know best way to test, if someone could please advise.

You can trigger internal errors using MAVProxy:
```
STABILIZE> hardfault_autopilot IREALLYMEANIT
STABILIZE> Sending corruption command
```

This is best done on a real board as typically in SITL we dump you into a debugger or similar, whereas a real board will come back up but instantly throw an internal error.

2021-03-06 01:13 UTC, nkruzan commented
i get these messages in gcs after triggering the hardfault.

`3/5/2021 5:15:00 PM : WDG: T18 SL0 FL127 FT3 FAE000ED38 FTP180 FLR806888
3/5/2021 5:14:50 PM : 5 FICSR2051 MM76 MC246 IE0 IEC0 TN:Ardu
3/5/2021 5:14:50 PM : WDG: T18 SL0 FL127 FT3 FAE000ED38 FTP180 FLR806888
3/5/2021 5:14:40 PM : 5 FICSR2051 MM76 MC246 IE0 IEC0 TN:Ardu
3/5/2021 5:14:40 PM : WDG: T18 SL0 FL127 FT3 FAE000ED38 FTP180 FLR806888
3/5/2021 5:14:34 PM : IMU0: fast sampling enabled 8.0kHz/1.0kHz
3/5/2021 5:14:34 PM : RCOut: PWM:1-10
3/5/2021 5:14:34 PM : MatekF405-Win 0045001F 55535017 2039305
3/5/2021 5:14:34 PM : ChibiOS: a14aa6b0
3/5/2021 5:14:34 PM : ArduPlane V4.1.0dev (e1bd11a6)
3/5/2021 5:14:33 PM : IMU0: fast sampling enabled 8.0kHz/1.0kHz
3/5/2021 5:14:33 PM : RCOut: PWM:1-10
3/5/2021 5:14:33 PM : MatekF405-Win 0045001F 55535017 2039305
3/5/2021 5:14:33 PM : ChibiOS: a14aa6b0
3/5/2021 5:14:33 PM : ArduPlane V4.1.0dev (e1bd11a6)
3/5/2021 5:14:33 PM : 5 FICSR2051 MM76 MC246 IE0 IEC0 TN:Ardu
3/5/2021 5:14:33 PM : WDG: T18 SL0 FL127 FT3 FAE000ED38 FTP180 FLR806888
3/5/2021 5:14:33 PM : 5 FICSR2051 MM76 MC246 IE0 IEC0 TN:Ardu
3/5/2021 5:14:33 PM : WDG: T18 SL0 FL127 FT3 FAE000ED38 FTP180 FLR806888
3/5/2021 5:14:33 PM : Flight mode = 11
3/5/2021 5:14:33 PM : Flight mode = 1
3/5/2021 5:14:33 PM : Failsafe. Short event on: type=1/reason=3
3/5/2021 5:14:33 PM : Throttle failsafe on
3/5/2021 5:14:33 PM : Internal Errors 800`

i have a log but i am not sure where to see the log entry
[1 12-31-1969 6-00-00 PM.bin.log](https://github.com/ArduPilot/ardupilot/files/6094462/1.12-31-1969.6-00-00.PM.bin.log)

2021-08-18 05:42 UTC, peterbarker requested changes
This is what I had in mind.

Some tidy up to do.

@nkruzan were you still interested in chasing this?  Apologies for the delayed review.

2021-08-18 05:42 UTC, peterbarker commented on libraries/AP_Logger/AP_Logger.cpp
> +
We can do without this wrapper; just call `AP::logger().Write_Error` directly

2021-08-18 05:42 UTC, peterbarker commented on libraries/AP_Vehicle/AP_Vehicle.cpp
> +    }
```suggestion
    const uint32_t new_internal_errors = AP::internalerror().errors();
    if(_last_internal_errors != new_internal_errors) {
        AP::logger().Write_Error(LogErrorSubsystem::INTERNAL_ERROR, LogErrorCode::INTERNAL_ERRORS_DETECTED);
        gcs().send_text(MAV_SEVERITY_CRITICAL, "Internal Errors %x", (unsigned)new_internal_errors);
        _last_internal_errors = new_internal_errors;
    }
```

(avoid calling method multiple times, simplify)

2021-08-18 05:42 UTC, peterbarker commented on libraries/AP_Vehicle/AP_Vehicle.cpp
> +void AP_Vehicle::send_internal_error_statustext(uint32_t internal_errors_bitmask)
We can do without this.

2021-08-28 16:22 UTC, nkruzan commented
@peterbarker I think I have addressed your issues/suggestions. Please advise if I have missed anything. Thank you for your time.

2021-08-30 05:18 UTC, peterbarker approved these changes
Tested on a CubeBlack here.

2021-08-30 12:09 UTC, nkruzan commented on libraries/AP_Vehicle/AP_Vehicle.cpp
> +    _last_internal_errors = AP::internalerror().errors() ; // get initial bitmask so we can know if it has changed
I am not sure what bss means in this context, could you elaborate. Thank you

2021-08-31 05:54 UTC, merged

2021-08-31 05:54 UTC, peterbarker commented
Merged, thanks @nkruzan !

2021-08-31 05:55 UTC, peterbarker commented on libraries/AP_Vehicle/AP_Vehicle.cpp
> +    _last_internal_errors = AP::internalerror().errors() ; // get initial bitmask so we can know if it has changed
https://en.wikipedia.org/wiki/.bss