AP_Frsky_Telem: added passthrough frame 0x500B with height above terrain
ArduPilot/ardupilot pull request #16829
Opened 2021-03-06 18:27 UTC by yaapu

This adds a new frame 0x500B with height above terrain, it's sent only when terrain is enabled.

For proper testing I also added mavlink message ALTITUDE [#141](https://mavlink.io/en/messages/common.html#ALTITUDE) to stream 3 of all vehicles

2021-03-07 00:00 UTC, peterbarker requested changes
Looking really good!

2021-03-07 00:00 UTC, peterbarker commented on libraries/GCS_MAVLink/GCS_Common.cpp
> +    AP_Terrain &terrain = AP::terrain();
`const` (if we can)

2021-03-07 08:36 UTC, yaapu commented on ArduCopter/GCS_Mavlink.cpp
> +    MSG_ALTITUDE,
ok, makes sense, fixed

2021-03-07 08:38 UTC, yaapu commented on Tools/autotest/common.py
> +        alt_above_terrain_dm = self.bit_extract(value, 2, 10) * (10 ^ self.bit_extract(value, 0, 2)) * 0.1 * (self.bit_extract(value, 12, 1) == 1 and -1 or 1)  # noqa
you mean a structure or class to incapsulate passthrough "wild" encoding?

2021-03-07 08:51 UTC, yaapu commented on libraries/GCS_MAVLink/GCS_Common.cpp
> +        { MAVLINK_MSG_ID_ALTITUDE,          MSG_ALTITUDE},
ok fixed

2021-03-07 08:51 UTC, yaapu commented on libraries/GCS_MAVLink/GCS_Common.cpp
> +    float bottom_clearance;
will do

2021-03-07 08:51 UTC, yaapu commented on libraries/GCS_MAVLink/GCS_Common.cpp
> +        WITH_SEMAPHORE(_baro.get_semaphore());
yep, thanks

2021-03-07 08:52 UTC, yaapu commented on libraries/GCS_MAVLink/GCS_Common.cpp
> +        // fall back to baro altitude
ok, so my solution is to wait for ahrs to have a position, no fall back

2021-03-07 08:56 UTC, yaapu commented on libraries/GCS_MAVLink/GCS_Common.cpp
> +    RangeFinder *rangefinder = RangeFinder::get_singleton();
fixed

2021-03-07 08:56 UTC, yaapu commented on libraries/GCS_MAVLink/GCS_Common.cpp
> +    AP_Terrain &terrain = AP::terrain();
fixed

2021-03-07 09:14 UTC, yaapu commented on libraries/AP_Frsky_Telem/AP_Frsky_SPort_Passthrough.cpp
> +#if AP_TERRAIN_AVAILABLE
...now I did :-)

2021-03-07 09:18 UTC, yaapu commented on libraries/AP_Frsky_Telem/AP_Frsky_SPort_Passthrough.cpp
> +#if AP_TERRAIN_AVAILABLE
but on real hardware for undefining it breaks SITL

```
[632/833] Compiling libraries/SITL/SIM_Airspeed_DLVR.cpp
../../libraries/SITL/SIM_Aircraft.cpp: In constructor ‘SITL::Aircraft::Aircraft(const char*)’:
../../libraries/SITL/SIM_Aircraft.cpp:66:20: error: ‘terrain’ is not a member of ‘AP’
     terrain = &AP::terrain();

```

2021-03-17 07:15 UTC, tridge commented
we can use TERRAIN_STATUS message to test terrain data

2021-03-17 21:33 UTC, yaapu commented
> we can use TERRAIN_REPORT message to test terrain data

OK, updated autotest to use TERRAIN_REPORT.

2021-03-18 10:43 UTC, merged

2021-03-18 10:44 UTC, peterbarker commented
Merged, thanks!

Apologies for the whole `ALTITUDE` thing; I'd forgotten we reported terrain-alt this way.

2021-03-18 10:51 UTC, yaapu commented
> Apologies for the whole `ALTITUDE` thing; I'd forgotten we reported terrain-alt this way.

no worries, thanks for merging