Plane: tailsitter.input_type bugfix
ArduPilot/ardupilot pull request #16841
Opened 2021-03-08 00:40 UTC by kd0aij

@IamPete1 This is the quick & easy fix you suggested.
I'm not clear enough on the intended use of control_in vs. norm_input to understand why tailsitter_check_input was implemented the way it is, but it does seem like that logic would be better localized to a tailsitter-specific function.

2021-03-08 00:54 UTC, IamPete1 approved these changes
This fixes the bug I added in https://github.com/ArduPilot/ardupilot/pull/16675

The issue is because we use `set_control_in` here:
https://github.com/ArduPilot/ardupilot/blob/4abae23306282ec77031d996eaf14cb08358a597/ArduPlane/tailsitter.cpp#L299

The change to norm_input broke this functionality.

TBH I think `set_control_in` even existing in the first place is asking for trouble, but that has nothing to do with this PR.

2021-03-08 22:22 UTC, tridge requested changes
also need to check QACRO mode, I suspect it has the same issue

2021-03-08 22:22 UTC, tridge commented on ArduPlane/mode_qstabilize.cpp
> +    const float roll_input = plane.channel_roll->get_control_in() / 4500.0f;
please change pitch to be consistent, and add a note on why we're using get_control_in() (ie. because of the tailsitter swapping of axes)

2021-03-08 22:48 UTC, kd0aij commented
@tridge QACRO always uses body frame controls 
also, ModeQStabilize::update() is not used in QACRO mode

2021-03-09 20:10 UTC, kd0aij commented
@tridge Changed pitch to also use control_in for consistency (although your original implementation also used norm_input) and added a comment warning about taisitter_check_input's behavior.

2021-03-19 15:50 UTC, kd0aij commented
size comparison:
```
Binary           text           data         bss           total
---------------  -------------  -----------  ------------  -------------
ardusub          0 (0.0000%)    0 (0.0000%)  0 (0.0000%)   0 (0.0000%)
arducopter       0 (0.0000%)    0 (0.0000%)  0 (0.0000%)   0 (0.0000%)
ardurover        0 (0.0000%)    0 (0.0000%)  0 (0.0000%)   0 (0.0000%)
arduplane        36 (+0.0023%)  0 (0.0000%)  4 (+0.0031%)  40 (+0.0023%)
arducopter-heli  0 (0.0000%)    0 (0.0000%)  0 (0.0000%)   0 (0.0000%)
antennatracker   0 (0.0000%)    0 (0.0000%)  0 (0.0000%)   0 (0.0000%)
```

2021-03-23 00:53 UTC, tridge approved these changes

2021-03-23 00:54 UTC, merged