Copter: constrain throttle before setting deadband
ArduPilot/ardupilot pull request #16863
Opened 2021-03-10 04:36 UTC by birm

Fixes #16860

Move deadband calculations after constraining the throttle.

2021-03-10 10:44 UTC, rishabsingh3003 requested changes
Thanks for this!
While the changes seem to be correct, can you please squash the two commits into 1? 
Also, please rename the single commit as: "Copter: constrain throttle before setting deadband" . I.e add the word "Copter" in the front as you've done in the PR title.

2021-03-10 10:44 UTC, rishabsingh3003 commented on ArduCopter/Attitude.cpp
> +    float deadband_bottom = mid_stick - g.throttle_deadzone;
we might as well also "Const" deadband_top, deadband_bottom, mid_stick

2021-03-13 11:35 UTC, khancyr approved these changes
It makes sens

2021-03-17 00:10 UTC, merged

2021-03-17 00:10 UTC, rmackay9 commented
Merged, thanks!