Plane: move tailsitter_check_input out of RC_Channel
ArduPilot/ardupilot pull request #16885
Opened 2021-03-12 19:54 UTC by kd0aij

Move handling of tailsitter.input_type from class RC_Channel to quadplane code since it is only relevant to ModeQStabilize::update() and QuadPlane::get_pilot_input_yaw_rate_cds().

This is preferable to tailsitter_input_check() since swapping RC_Channel control_in values creates confusion because the results of norm_input and get_control_in don't return values for the same channel.

2021-03-12 22:39 UTC, IamPete1 requested changes
I do like this approach better, but there are so many edge cases. For example I think it breaks Qloiter and Qautotune.

https://github.com/ArduPilot/ardupilot/blob/0414929310e07d8d178f0aa3e143b1a6cf7ee818/ArduPlane/qautotune.cpp#L32

https://github.com/ArduPilot/ardupilot/blob/0414929310e07d8d178f0aa3e143b1a6cf7ee818/ArduPlane/quadplane.cpp#L1196

also weather vanning.

`set_control_in` is such a powerful function its very hard to ever stop using it, we would have to add this check to every place we call `get_control_in`

2021-03-12 23:22 UTC, kd0aij commented
@IamPete1 Thanks, I'll do a more thorough check to see if I can identify every case where pilot input for roll and yaw are used.

I think I only need to look at places where pilot input for roll and yaw should depend on tailsiter.input_type, but this is a good time to mention that input_type==TAILSITTER_INPUT_PLANE would more properly have been implemented as a separate mode, since it changes the meaning of the control sticks.

You're right about Qloiter, I only tested the response to roll stick in SITL. So get_pilot_lean_angles cares about input_type too, which makes sense. And I hadn't thought about autotune... it has a get_pilot_desired_rp_yrate_cd method.

2021-03-13 15:48 UTC, kd0aij commented
tailsitter.input_type should affect only these Q control modes:
QSTABILIZE, QHOVER, QLOITER, QLAND, QRTL? and QAUTOTUNE

It should not affect QACRO or any non-Q mode.
 
QSTABILIZE, QHOVER, QLOITER, QLAND, QRTL modes all get pilot roll input via ModeQStabilize::update() which is invoked by task update_control_mode at 400 Hz.

QSTABILIZE mode gets pilot yaw input via hold_stabilize (via task stabilize at 400Hz: call chain: Plane::stabilize > quadplane.control_run > quadplane.control_stabilize)
QHOVER mode gets pilot yaw input via hold_hover.
hold_stabilize and hold_hover both use get_desired_yaw_rate_cds()

QLOITER, QLAND run control_loiter  (via task stabilize at 400Hz) which also gets pilot roll input via get_pilot_desired_lean_angles which appears to create a race conditon (which get_pilot_desired_lean_angles seems to win)
control_loiter also gets pilot yaw via get_desired_yaw_rate_cds

QRTL uses control_qrtl which does not appear to use pilot inputs

QAUTOTUNE uses AC_AutoTune::run() which calls get_pilot_desired_rp_yrate_cd which uses get_tailsitter_pilot_input_roll_yaw()

So pilot roll input is handled by either ModeQStabilize::update(), get_pilot_desired_lean_angles() or get_pilot_desired_rp_yrate_cd all of which call get_tailsitter_pilot_input_roll_yaw, which checks mode and tailsitter.input_type, covering all affected modes.

Pilot yaw input for all affected modes is handled in all cases by get_desired_yaw_rate_cds which also calls get_tailsitter_pilot_input_roll_yaw.

QLOITER mode trace: RC read interval: 20 msec, (update_control_mode, stabilize, set_servos) interval 4 msec

82168: RC_roll: 0.573248, RC_pitch: -0.360934
82168: ModeQStabilize::update: roll: 1337, pitch: -3592
82168: get_pilot_lean_angles: roll: 221.936661, pitch: -541.333374
82168: servo_out: ail: -197, elev: -543
82172: ModeQStabilize::update: roll: 1337, pitch: -3592
82172: get_pilot_lean_angles: roll: 221.936661, pitch: -541.333374
82172: servo_out: ail: -198, elev: -541
82175: ModeQStabilize::update: roll: 1337, pitch: -3592
82175: get_pilot_lean_angles: roll: 221.936661, pitch: -541.333374
82175: servo_out: ail: -198, elev: -541
82178: ModeQStabilize::update: roll: 1337, pitch: -3592
82178: get_pilot_lean_angles: roll: 221.936661, pitch: -541.333374
82178: servo_out: ail: -196, elev: -543
82182: ModeQStabilize::update: roll: 1337, pitch: -3592
82182: get_pilot_lean_angles: roll: 221.936661, pitch: -541.333374
82182: servo_out: ail: -194, elev: -544
82185: ModeQStabilize::update: roll: 1337, pitch: -3592
82185: get_pilot_lean_angles: roll: 221.936661, pitch: -541.333374
82185: servo_out: ail: -192, elev: -542
82188: RC_roll: 0.573248, RC_pitch: -0.360934
82188: ModeQStabilize::update: roll: 1337, pitch: -3592
82188: get_pilot_lean_angles: roll: 221.936661, pitch: -541.333374
82188: servo_out: ail: -189, elev: -538
82192: ModeQStabilize::update: roll: 1337, pitch: -3592
82192: get_pilot_lean_angles: roll: 221.936661, pitch: -541.333374
82192: servo_out: ail: -186, elev: -534
82195: ModeQStabilize::update: roll: 1337, pitch: -3592
82195: get_pilot_lean_angles: roll: 221.936661, pitch: -541.333374
82195: servo_out: ail: -184, elev: -532
82198: ModeQStabilize::update: roll: 1337, pitch: -3592
82198: get_pilot_lean_angles: roll: 221.936661, pitch: -541.333374
82198: servo_out: ail: -182, elev: -531
82202: ModeQStabilize::update: roll: 1337, pitch: -3592
82202: get_pilot_lean_angles: roll: 221.936661, pitch: -541.333374
82202: servo_out: ail: -178, elev: -528
82205: ModeQStabilize::update: roll: 1337, pitch: -3592
82205: get_pilot_lean_angles: roll: 221.936661, pitch: -541.333374
82205: servo_out: ail: -175, elev: -525
82208: RC_roll: 0.573248, RC_pitch: -0.360934

2024-07-25 07:00 UTC, peterbarker commented
Looks like @IamPete1 did this in 2bc2b9533b29a44814fbc886f97c493a148fdc76 .

Thanks anyway!

2024-07-25 07:00 UTC, closed without merging