Copter:Mission Restarts in auto mode
ArduPilot/ardupilot pull request #16896
Opened 2021-03-14 15:07 UTC by arshPratap

This PR attempts to solve the issue raised in #16805.The user can arm and restart a mission after successful completion of a mission.Thanks !
As suggested [here](https://github.com/ArduPilot/ardupilot/issues/16805) following the same steps:-
1.)created a mission with wp editor
![wp_editor](https://user-images.githubusercontent.com/62841337/111073379-74bf7580-8504-11eb-9b62-7fe858e6b7ff.png)
2.)make sure auto_options=3
![auto_options](https://user-images.githubusercontent.com/62841337/111073407-8a349f80-8504-11eb-8b5d-dbf7c9062ad5.png)
3.)switched to auto mode
![auto](https://user-images.githubusercontent.com/62841337/111073433-acc6b880-8504-11eb-937b-090797a653a0.png)
4.)arm throttle(1st time)
![arm1](https://user-images.githubusercontent.com/62841337/111073466-d384ef00-8504-11eb-8f6a-32487cd3150c.png)
5.)arm throttle (2nd time)
![arm2](https://user-images.githubusercontent.com/62841337/111073474-d849a300-8504-11eb-88a7-388ff4c4d0f2.png)

2021-03-14 15:08 UTC, arshPratap commented
Wanted to know the thoughts of the devs on this issue thats why used a draft for this one. Thanks a lot in advance

2021-03-15 09:43 UTC, peterbarker requested changes
Random whitespace changes aren't fun, sorry :-)

2021-03-15 09:43 UTC, peterbarker commented on ArduCopter/mode_auto.cpp
> -#endif
We've lost this.  Not good.

2021-03-15 09:43 UTC, peterbarker commented on ArduCopter/mode_auto.cpp
>          copter.landinggear.retract_after_takeoff();
Not a good change.

2021-03-15 10:25 UTC, rmackay9 commented
I think PR https://github.com/ArduPilot/ardupilot/pull/16808 is probably the way to go so we might not want to keep going with this PR.  It's a good attempt though!

2021-03-15 17:13 UTC, arshPratap commented
@peterbarker,@rmackay9 thanks for looking into this.I will start working on the suggestions ASAP

2021-04-10 00:47 UTC, rmackay9 commented
I think we can close this because we've merged https://github.com/ArduPilot/ardupilot/pull/16808

2021-04-10 00:47 UTC, closed without merging