Fix Ignored MAV_FRAME Parameter
ArduPilot/ardupilot pull request #16903
Opened 2021-03-15 12:25 UTC by obicons

MAVLink's obstacle distance message supports the value of MAV_FRAME_BODY_FRD for the MAV_FRAME parameter (see https://mavlink.io/en/messages/common.html#OBSTACLE_DISTANCE). Currently, `handle_obstacle_distance_msg` ignores this option. I updated `handle_obstacle_distance_msg` to behave the same as `handle_obstacle_distance_3d_msg` when given a MAV_FRAME_BODY_FRD frame.

2021-03-19 06:41 UTC, peterbarker requested changes
@obicons its a reasonable patch, and I considered this when we were implementing `obstacle_distance_3d`

The main problem with this is that we may break people's existing, working, setups by rejecting their previously-working (if mis-framed) messages.

Still, we should take this to a devcall.

Before merge the commit message will need to be fixed; something like `AP_Proximity: reject invalid frames for OBSTACLE_DISTANCE" would be appropriate.

2021-03-19 12:54 UTC, rishabsingh3003 commented
It looks fine to me, but I have the same worry as @peterbarker . We might even need to go back and change some of our old d4xx_to_mavlink scripts..

2021-03-22 11:54 UTC, obicons commented
Thanks for the feedback @peterbarker and @rishabsingh3003! I reworded the commit message.

2021-03-23 01:03 UTC, rmackay9 commented
This came up on the dev call and we decided that this would add a new barrier for use of this message without adding any real benefit at least at the moment... so although this change seems correct we shouldn't cause pain for users unless there's a good reason.

2021-03-23 01:03 UTC, closed without merging

2021-03-23 01:03 UTC, peterbarker commented
@obicons did the current behaviour cause you trouble?

2021-03-23 01:56 UTC, obicons commented
I understand the desire to avoid breaking working setups. Perhaps this is something can be revisited on a later release? In the meantime, would this community value a project to try to document this kind of irregularity? From experience, this is the kind of issue that takes *forever* to debug when you run into it. Documenting this knowledge might help others that encounter this behavior unexpectedly.

2021-03-23 02:07 UTC, rmackay9 commented
@obicons,

yes to both suggestions I think.  We should probably document some of this in our MAVLink Interfaces wiki area. https://ardupilot.org/dev/docs/mavlink-commands.html

2021-03-23 04:27 UTC, peterbarker commented
On Mon, 22 Mar 2021, obicons wrote:

> I understand the desire to avoid breaking working setups. Perhaps this is
> something can be revisited on a later release? In the meantime, would this
> community value a project to try to document this kind of irregularity? From
> experience, this is the kind of issue that takes forever to debug when you
> run into it. Documenting this knowledge might help others that encounter
> this behavior unexpectedly.

I suggested on the DevCall that we could emit a warning to the user via 
mavlink in the case someone *does* send us stuff in the wrong frame - so 
they can fix their stuff.  That suggestion was not looked upon kindly.

Apparently we'll just document ourselves out of the hole (in the release 
notes) if we ever do start supporting the FRAME field.

Again - did you actually try a different frame and find it ignored that 
frame without telling you?