USE Mavlink typemask
ArduPilot/ardupilot pull request #16925
Opened 2021-03-16 17:29 UTC by khancyr

Rework from https://github.com/ArduPilot/ardupilot/pull/15986
close https://github.com/ArduPilot/ardupilot/pull/15986

This is cover by autotest

2021-03-19 06:31 UTC, peterbarker requested changes
Values must match - until we decide we need to fix these.

I've only checked the one value.

2021-03-19 06:31 UTC, peterbarker commented on Rover/GCS_Mavlink.cpp
> -        0xFFF8, // ignore everything except the x/y/z components
```
>>> hex(mavutil.mavlink.POSITION_TARGET_TYPEMASK_VX_IGNORE | mavutil.mavlink.POSITION_TARGET_TYPEMASK_VY_IGNORE | mavutil.mavlink.POSITION_TARGET_TYPEMASK_VZ_IGNORE | mavutil.mavlink.POSITION_TARGET_TYPEMASK_AX_IGNORE | mavutil.mavlink.POSITION_TARGET_TYPEMASK_AY_IGNORE | mavutil.mavlink.POSITION_TARGET_TYPEMASK_AZ_IGNORE | mavutil.mavlink.POSITION_TARGET_TYPEMASK_FORCE_SET | mavutil.mavlink.POSITION_TARGET_TYPEMASK_YAW_IGNORE| mavutil.mavlink.POSITION_TARGET_TYPEMASK_YAW_RATE_IGNORE | POSITION_TARGET_TYPEMASK_BIT_12)
'0x1ff8'
```

2021-03-23 10:51 UTC, khancyr reviewed
```
from pymavlink import mavutil
POSITION_TARGET_TYPEMASK_LAST = 0xF000

hex(mavutil.mavlink.POSITION_TARGET_TYPEMASK_VX_IGNORE | mavutil.mavlink.POSITION_TARGET_TYPEMASK_VY_IGNORE | mavutil.mavlink.POSITION_TARGET_TYPEMASK_VZ_IGNORE | mavutil.mavlink.POSITION_TARGET_TYPEMASK_AX_IGNORE | mavutil.mavlink.POSITION_TARGET_TYPEMASK_AY_IGNORE | mavutil.mavlink.POSITION_TARGET_TYPEMASK_AZ_IGNORE | mavutil.mavlink.POSITION_TARGET_TYPEMASK_FORCE_SET | mavutil.mavlink.POSITION_TARGET_TYPEMASK_YAW_IGNORE| mavutil.mavlink.POSITION_TARGET_TYPEMASK_YAW_RATE_IGNORE | POSITION_TARGET_TYPEMASK_LAST) 

Out[14]: '0xfff8'
```


```
In [15]: hex(mavutil.mavlink.POSITION_TARGET_TYPEMASK_VX_IGNORE | mavutil.mav
    ...: link.POSITION_TARGET_TYPEMASK_VY_IGNORE | mavutil.mavlink.POSITION_T
    ...: ARGET_TYPEMASK_VZ_IGNORE | mavutil.mavlink.POSITION_TARGET_TYPEMASK_
    ...: AX_IGNORE | mavutil.mavlink.POSITION_TARGET_TYPEMASK_AY_IGNORE | mav
    ...: util.mavlink.POSITION_TARGET_TYPEMASK_AZ_IGNORE | mavutil.mavlink.PO
    ...: SITION_TARGET_TYPEMASK_FORCE_SET | mavutil.mavlink.POSITION_TARGET_T
    ...: YPEMASK_YAW_IGNORE| mavutil.mavlink.POSITION_TARGET_TYPEMASK_YAW_RAT
    ...: E_IGNORE)                                                           
Out[15]: '0xff8'
```

```
In [16]: hex(mavutil.mavlink.POSITION_TARGET_TYPEMASK_X_IGNORE | mavutil.mavl
    ...: ink.POSITION_TARGET_TYPEMASK_Y_IGNORE | mavutil.mavlink.POSITION_TAR
    ...: GET_TYPEMASK_Z_IGNORE | mavutil.mavlink.POSITION_TARGET_TYPEMASK_AX_
    ...: IGNORE | mavutil.mavlink.POSITION_TARGET_TYPEMASK_AY_IGNORE | mavuti
    ...: l.mavlink.POSITION_TARGET_TYPEMASK_AZ_IGNORE | mavutil.mavlink.POSIT
    ...: ION_TARGET_TYPEMASK_FORCE_SET | mavutil.mavlink.POSITION_TARGET_TYPE
    ...: MASK_YAW_IGNORE| mavutil.mavlink.POSITION_TARGET_TYPEMASK_YAW_RATE_I
    ...: GNORE)                                                              
Out[16]: '0xfc7'
```

I```
n [17]: hex(mavutil.mavlink.POSITION_TARGET_TYPEMASK_AX_IGNORE | mavutil.mav
    ...: link.POSITION_TARGET_TYPEMASK_AY_IGNORE | mavutil.mavlink.POSITION_T
    ...: ARGET_TYPEMASK_AZ_IGNORE | mavutil.mavlink.POSITION_TARGET_TYPEMASK_
    ...: FORCE_SET | mavutil.mavlink.POSITION_TARGET_TYPEMASK_YAW_IGNORE| mav
    ...: util.mavlink.POSITION_TARGET_TYPEMASK_YAW_RATE_IGNORE)              
Out[17]: '0xfc0'
```

2021-04-07 07:34 UTC, tridge commented
waiting for review confirmation from @peterbarker

2021-04-21 00:39 UTC, peterbarker requested changes
Bad rebase?

Needs to compile

2021-04-21 17:05 UTC, khancyr commented
corrected !

2021-05-07 08:12 UTC, peterbarker approved these changes
I've done the maths on each of these now and it works out.

2021-05-10 23:53 UTC, tridge approved these changes

2021-05-10 23:53 UTC, merged