Plane: add optional initial level to tailsitter VTOL transition
ArduPilot/ardupilot pull request #16935
Opened 2021-03-17 17:14 UTC by Hwurzburg

if LEVEL_TRANSITION option bit is set, this holds off pitch up demand for a second to allow wings to level out of a hard bank before starting
increased timeout to allow for this, but will next add params for this timeout and back transition angle

2021-03-18 03:06 UTC, kd0aij requested changes

2021-03-18 03:06 UTC, kd0aij commented on ArduPlane/tailsitter.cpp
> +	return true;
tabs -> spaces

2021-03-18 13:00 UTC, Hwurzburg commented on ArduPlane/Attitude.cpp
> +	roll_limit_cd = MIN(roll_limit_cd, g.level_roll_limit*100);
yeah, on my list....I just copy and pasted the level trans code from another place...

2021-03-18 13:01 UTC, Hwurzburg commented on ArduPlane/tailsitter.cpp
> +	return true;
will fix

2021-03-20 04:01 UTC, Hwurzburg commented
after alot of SITL, I dont think this really provides a lot of benefit...closing

2021-03-20 04:01 UTC, closed without merging