Fix occasional problems with SPL06
ArduPilot/ardupilot pull request #16964
Opened 2021-03-22 13:06 UTC by zhouzhiwen2000

Sometimes SPL06 has init problems, that's due to failure of reading using SPI for the first time. The SPL06 is a dual protocol sensor(I2C and SPI), sometimes it takes one SPI operation to convert it to SPI mode after it starts up.

2021-03-22 16:09 UTC, shellixyz commented
Odd, it never failed for me

2021-03-22 17:17 UTC, zhouzhiwen2000 commented
> Odd, it never failed for me

Are you using it under SPI bus?

2021-03-22 17:17 UTC, zhouzhiwen2000 commented
It works find under I2C bus.

2021-03-22 17:21 UTC, zhouzhiwen2000 commented
Whoami reads used to be 255 sometimes before modification.

2021-03-22 19:56 UTC, shellixyz commented
I am using it on SPI on some aircrafts and I²C on others

2021-03-22 21:46 UTC, peterbarker requested changes
Looks good.  Will take this to today's DevCall for more comment.

2021-03-22 21:46 UTC, peterbarker commented on libraries/AP_Baro/AP_Baro_SPL06.cpp
> +    bool is_SPL06=false;
```suggestion
    bool is_SPL06 = false;
```

2021-03-22 21:46 UTC, peterbarker commented on libraries/AP_Baro/AP_Baro_SPL06.cpp
> +    while (retries-->0) { //Try multiple times to determine whether it is a SPL06.
```suggestion
    for (uint8_t i=0; i<5; i++) {
```

2021-03-22 21:46 UTC, peterbarker commented on libraries/AP_Baro/AP_Baro_SPL06.cpp
> +    uint8_t retries=5;
```suggestion
// Sometimes SPL06 has init problems, that's due to failure of reading using SPI for the first time. The SPL06 is a dual
// protocol sensor(I2C and SPI), sometimes it takes one SPI operation to convert it to SPI mode after it starts up.
```

(but probably line-wrapped differently)

2021-03-22 21:46 UTC, peterbarker commented on libraries/AP_Baro/AP_Baro_SPL06.cpp
> +            }
```suggestion
            is_SPL06=true;
            break;
        }
```

2021-03-22 23:31 UTC, peterbarker commented
devcall outcome was that retries in init code are fine if it definitely fixes a problem for you reliably.

2021-03-23 03:50 UTC, zhouzhiwen2000 commented
May be it's because I am using it with other sensors on the same bus? May be it's due to differences between revisions of the sensor? I am not quite sure. It solves my problem reliably though.

2021-03-23 04:29 UTC, peterbarker approved these changes
A few minor formatting things, but not worth holding up for.

2021-03-24 00:26 UTC, peterbarker commented
Rebased this on top of some CI fixes.

2021-03-24 03:29 UTC, merged

2021-03-24 03:29 UTC, peterbarker commented
Merged, thanks!