Plane: add option do do a VTOL approach RTL
ArduPilot/ardupilot pull request #16977
Opened 2021-03-23 21:34 UTC by IamPete1

This adds a option to do a VTOL approach RTL. The vehicle will RTL at the RTL alt. Then loiter with a radius of  FW_LND_APR_RAD down to the q rtl alt. It will then transition into the wind and switch into QRTL. Like a [NAV_VTOL_LAND](https://ardupilot.org/plane/docs/quadplane-auto-mode.html#auto-vtol-landing) with the "Use a fixed wing approach" Q option set.

The idea being to minimize long descents from the RTL alt in QRTL.

Funded by ARACE.

2021-03-25 22:46 UTC, tridge requested changes
looks like a useful feature

2021-03-25 22:46 UTC, tridge commented on ArduPlane/mode_rtl.cpp
> +        if (plane.quadplane.available() && (plane.quadplane.rtl_mode == 2)) {
let's make rtl_mode an enum

2021-03-26 17:25 UTC, Hwurzburg commented
https://user-images.githubusercontent.com/6076534/112669815-224c5600-8e2e-11eb-859c-63723d4b53e8.mp4

test flown....aside from my Convergence having a lousy TECs tune (for some reason the demanded alt overshoots), this functioned perfectly including facing the wind for the VTOL descent...

2021-03-26 19:02 UTC, IamPete1 commented on ArduPlane/mode_rtl.cpp
> +        if (plane.quadplane.available() && (plane.quadplane.rtl_mode == 2)) {
done

2021-03-26 19:28 UTC, IamPete1 commented
A little demo in realflight https://youtu.be/PnTI_ll-6gU

Tune is quite bad because my realflight was struggling to get a good frame rate, hopefully the operation is clear.

2021-03-27 13:48 UTC, IamPete1 commented
rebased and fixed a spelling error

2021-03-29 00:29 UTC, tridge approved these changes

2021-03-29 00:29 UTC, merged