AP_EFI: use enum class for protocol
ArduPilot/ardupilot pull request #16988
Opened 2021-03-24 07:34 UTC by peterbarker

2021-03-28 18:47 UTC, WickedShell reviewed
Does actually make the build larger. Have you checked if making the enum class specified as being stored in a `int8_t` keeps the size the same? (Basically means no real casting on the comparisons to the params)

2021-03-29 22:46 UTC, tridge requested changes
should use AP_Enum I think

2021-03-29 22:46 UTC, tridge commented on libraries/AP_EFI/AP_EFI.h
> +    enum class Type {
should be uint8_t size

2021-03-29 22:57 UTC, peterbarker commented on libraries/AP_EFI/AP_EFI.h
> +    enum class Type {
Done.

2021-03-29 22:57 UTC, peterbarker commented
> should use AP_Enum I think

Done

2021-03-29 23:01 UTC, tridge approved these changes

2021-03-29 23:33 UTC, WickedShell commented
Still larger :)

Out of curiosity swapping from AP_Int8 to AP_Enum is lossless for anyone who already set it? What's the advantage of AP_Enum at that point?

2021-03-30 10:40 UTC, merged