AC_Avoidance: fixes to work with SCurves
ArduPilot/ardupilot pull request #17003
Opened 2021-03-25 03:24 UTC by rmackay9

This PR builds on the SCurves PR https://github.com/ArduPilot/ardupilot/pull/15896 to fixup Dijkstra's and BendyRuler's performance when using SCurves.

Only the 16 commits after, "Tools: Copter.fly_square descends more quickly" are new to this PR.  The changes include:

- AP_Math's control gets several new "input shaping" helper functions.  "input shaping" means we limit the inputs to a controller so as no to request impossible or inconsistent positions, velocities or accelerations.
- AC_PosControl get new input_pos_vel_xy/z and input_vel_xy/z methods that accept target position and velocity targets.  My understanding is that these are improved versions of what happens in Copter's Guide mode's posvel controller and will eventually replace it.
- AC_Avoidance's BendyRuler uses the above mentioned AC_PosControl methods instead of the higher level AC_WPNav::set_destination() method.  This gets around SCurves's unhappiness with receiving new targets at a high rate and also performs better (or so it seems in SITL testing)
- AC_Avoidance's PathPlanner returns what planner was used in the generation of a new intermediate target. This is required so that AC_WPNav_OA knows how to handle the target.  E.g. if the target is from Dijkstra's it uses AC_WPNav, if it's from BendyRuler then it sends the target to AC_PosControl.

There are also some changes to formatting and spelling.

This has been tested in SITL.

2021-03-25 03:55 UTC, lthall approved these changes
All good!

2021-03-25 06:19 UTC, rishabsingh3003 commented
Things are looking good! Everything working same as Master on the simulators. Will fly it soon :)

2021-06-17 02:35 UTC, peterbarker commented
This one needs a rebase.

2021-06-17 02:39 UTC, rmackay9 commented
@peterbarker, it'll need a lot more than that actually .. don't worry about this one for now, I've got it on my to-do list to update it once Leonard's finalised his changes to Guided mode.

2021-07-06 10:44 UTC, rishabsingh3003 commented
https://discuss.ardupilot.org/t/i-have-a-problem-with-object-avoidance-with-bendy-ruler-4-1-0-beta-3-firmware/73361
Some more evidence apart from my testing

2021-07-14 10:18 UTC, rishabsingh3003 requested changes

2021-07-14 10:18 UTC, rishabsingh3003 commented on libraries/AC_WPNav/AC_WPNav_OA.cpp
> +        } // switch (oa_retstate)
Some left over commented out code

2021-07-14 11:26 UTC, rmackay9 commented on libraries/AC_WPNav/AC_WPNav_OA.cpp
> +        } // switch (oa_retstate)
removed, thanks.

2021-07-21 18:39 UTC, rishabsingh3003 approved these changes
Tested this quite a bit
https://www.youtube.com/watch?v=d1EYWhcK2OA

It looks okay to me, but the reactions are rather twitchy at times (some of the twitches were there before also). This can be seen on real vehicles too.. It's a step forward because as of now, scurves totally breaks OA, but there is scope for improvement I guess..

2021-07-21 23:51 UTC, merged

2021-07-21 23:51 UTC, rmackay9 commented
@rishabsingh3003 thanks for the testing!

Merged!

2021-07-22 02:11 UTC, hendjoshsr71 commented
It also fixed the issue with vertical bendy climbing between waypoints when terrain following is on.