Copter: Prearm check MOT_THST_HOVER isn't set too high mistakenly
ArduPilot/ardupilot pull request #17038
Opened 2021-03-29 09:56 UTC by SergeyBokhantsev

User can set mistakenly MOT_THST_HOVER to a dangerously high value, example 35 instead of 0.35
So then after switching to altitude-controlled flight mode vehicle will go into the sky.

2021-03-29 10:49 UTC, rmackay9 commented
Txs for this.  I think it would be good for this to be in the AP_Arming_Copter::parameter_checks() section instead of the mandatory_checks().

Perhaps a better alternative would be to change AP_MotorsMulticopter::get_throttle_hover() so it never returns a value above AP_MOTORS_THST_HOVER_MAX and change AP_MotorsHeli::get_throttle_hover() to never return higher than AP_MOTORS_HELI_COLLECTIVE_HOVER_MAX.

2021-03-29 10:49 UTC, rmackay9 requested changes
thanks for this.  I've written an alternative change in another comment.

2021-03-29 11:08 UTC, SergeyBokhantsev commented
@rmackay9 
>>Perhaps a better alternative would be to change AP_MotorsMulticopter::get_throttle_hover() so it never returns a value above AP_MOTORS_THST_HOVER_MAX and change AP_MotorsHeli::get_throttle_hover() to never return higher than AP_MOTORS_HELI_COLLECTIVE_HOVER_MAX.

I think this way the fix will not add any safety, because 1.0 is still extremely high value. A value > 1.0 is a sign of user error, so user needs to correct it.

>>I think it would be good for this to be in the AP_Arming_Copter::parameter_checks() section instead of the mandatory_checks().

My idea was to always to perform this check, because parameter_checks() will not run if ARMING_CHECKS=0 (as users often do on a new vehicle initial fly tests). That's why I putted the check into mandatory_checks(). But now I see that mandatory_checks() will not run if ARMING_CHECKS!=0. 
So I propose to move the check into new mandatory_parameter_checks(). So this method will be called from both parameter_checks() and mandatory_checks().

2021-03-29 11:13 UTC, rmackay9 commented
@SergeyBokhantsev I think adding the constraint to get_throttle_hover() is actually safer because it means the hover throttle can't be set too high and can't cause the vehicle to fly off because the altitude controller's I-term will always be large enough to overpower it... and then the hover throttle will likely be learned back to a correct value.

So, I think the constrain is actually the better option but a parameter check is certainly an improvement so I'll  merge it if it's moved to the parameter arming checks.

Txs for uncovering this issue.

2021-03-29 11:39 UTC, SergeyBokhantsev commented
>and can't cause the vehicle to fly off because the altitude controller's I-term will always be large enough to overpower it

@rmackay9 ok, if so then I can fix that way.
But I'm not sure should we do 
     constrain_float(_throttle_hover, AP_MOTORS_THST_HOVER_MIN, AP_MOTORS_THST_HOVER_MAX);
or
     constrain_float(_throttle_hover, 0, AP_MOTORS_THST_HOVER_MAX);
because AP_MOTORS_THST_HOVER_MIN = 0.125f and maybe someone want to have zero _throttle_hover for some reason.

2021-03-30 01:36 UTC, rmackay9 commented
@lthall is going to respond on this one..

2021-03-30 23:53 UTC, lthall commented
Adding this to the get_throttle_hover() function is the way to go: constrain_float(_throttle_hover, AP_MOTORS_THST_HOVER_MIN, AP_MOTORS_THST_HOVER_MAX);

2021-03-31 19:33 UTC, SergeyBokhantsev commented
Closing this prior to https://github.com/ArduPilot/ardupilot/pull/17070

2021-03-31 19:33 UTC, closed without merging