Plane: Push the TECS to climb in all circumstances
ArduPilot/ardupilot pull request #17031
Opened 2021-03-28 20:33 UTC by skorokithakis

I noticed today that the climb-before-turn climbing issue that I thought was fixed was actually not.

The issue is that, when climbing to RTL altitude to turn, ArduPlane willl actually level off just before reaching the target altitude, and will take a very long time to reach the final few meters, all the while flying away from you.

This PR changes the target altitude so the extra 10m of RTL_CLIMB_MIN are added to climb-before-turn as well, thus instructing the craft to climb to ALT_HOLD_RTL+10m, making it climb the last few meters faster.

Unfortunately I don't have a craft to test this on yet, and the SITL is not sensitive enough to test this on. I would appreciate it if someone could test this feature.

2021-04-01 14:38 UTC, skorokithakis commented
This feature was tested and works as intended.

2021-04-05 22:59 UTC, skorokithakis commented
Tested more extensively this weekend as well, works great.

2021-04-06 00:32 UTC, peterbarker requested changes
Commit message needs fixing

2021-04-06 00:35 UTC, tridge requested changes

2021-04-06 00:35 UTC, tridge commented on ArduPlane/ArduPlane.cpp
> +            target_alt = MAX(target_alt, prev_WP_loc.alt) + (g2.rtl_climb_min+10)*100;
looks like we are mixing relative and AMSL altitudes

2021-04-06 02:00 UTC, tridge approved these changes

2021-04-06 11:37 UTC, merged