AP_HAL_ChibiOS: H7 set SRAM4 to no cache and allow DMA
ArduPilot/ardupilot pull request #17081
Opened 2021-04-01 12:52 UTC by IamPete1

This is a change to mark SRAM4 as no cache and allow DMA. This allows lots of LEDs again. I have not tested all output types. H7 boards only.

2021-04-01 13:34 UTC, andyp1per approved these changes

2021-04-01 15:51 UTC, ukmook commented
By applying this PR along with @andyp1per suggestion of changing order of sram3 and sram4 in STM32H743xx.py has made the flight controller bootable using SPI6 which has BMI088 connected.

2021-04-04 21:56 UTC, IamPete1 commented
I have swapped SRAM3 and 4 so it will work for @ukmook 's setup, seems not to make any difference for my LEDs

2021-04-06 00:50 UTC, tridge commented
please see this post:
http://forum.chibios.org/viewtopic.php?t=4140&start=130
I think we need to go back to SRAM4 only for general purpose DMA, and we need to re-enable the cache on SRAM3, and disable cache on SRAM4

2021-04-06 00:53 UTC, tridge requested changes
see comment on SRAM4

2021-04-06 00:54 UTC, tridge commented
we should copy the table from my posting into STM32H7xx.py

2021-04-06 01:09 UTC, tridge commented
this is the table, the key is that I2C4 and SPI6 can't use SRAM3
```
- can't use ITCM or DTCM for any DMA
- SPI1 to SPI5 can use AXI SRAM, SRAM1 to SRAM3 and SRAM4 for DMA
- SPI6, I2C4 and ADC3 can use SRAM4 on BDMA (I didn't actually test ADC3)
- UARTS can use AXI SRAM, SRAM1 to SRAM3 and SRAM4 for DMA
- I2C1, I2C2 and I2C3 can use AXI SRAM, SRAM1 to SRAM3 and SRAM4 with DMA
- timers can use AXI SRAM, SRAM1 to SRAM3 and SRAM4 with DMA
- ADC12 can use AXI SRAM, SRAM1 to SRAM3 and SRAM4
- SDMMC can use AXI SRAM, SRAM1 to SRAM3 with IDMA (cannot use SRAM4)
```

2021-04-07 05:07 UTC, tridge commented
I've pushed a patch to use SRAM4 and re-enable cache on SRAM3

2021-04-07 06:56 UTC, andyp1per approved these changes

2021-04-07 07:10 UTC, tridge approved these changes

2021-04-07 07:10 UTC, merged