Plane: fix terrain following in loiter and QRTL
ArduPilot/ardupilot pull request #17098
Opened 2021-04-04 19:41 UTC by IamPete1

This fixes and adds a test for loiter terrain following in plane. I think that is fairly clear.

Slightly less clear is the fix for QRTL. It seems there is a split between some-places using `plane.next_WP_loc.terrain_alt` as the flag for terrain following and others using `target_altitude.terrain_following`. Its all very confusing, I would be un-surprised if terrain following is also broken in a bunch of other modes.

2021-04-04 23:15 UTC, IamPete1 commented
The new auto test is failing to load terrain correctly, some tests have comments saying they load MAVProxy to make it more reliable, that does not seem to help locally tho. @peterbarker any ideas?

2021-04-06 00:58 UTC, tridge requested changes

2021-04-06 00:58 UTC, tridge commented on ArduPlane/quadplane.cpp
> +            if (plane.next_WP_loc.terrain_alt && plane.terrain.height_terrain_difference_home(terrain_altitude_offset, true)) {
how does this handle rally points?

2021-04-06 00:58 UTC, peterbarker commented on Tools/autotest/arduplane.py
> +        default_rad = self.get_parameter("WP_LOITER_RAD")
Shouldn't we really start MAVProxy here to supply the terrain?

2021-04-06 01:03 UTC, tridge commented
we could have the pre-generated terrain dat file in git, and copy to terrain directory in sitl

2021-04-07 17:46 UTC, IamPete1 commented
I think I finally have this right now. Plane was previously calling stuff relative to terrain but in reality it was still relative to home. Its all a massive mess that it impossible to understand. I would be completely un-surprised if terrain following was broken in a bunch of other modes.

2021-04-21 08:20 UTC, tridge requested changes
the patch looks half finished?

2021-04-21 08:20 UTC, tridge commented on ArduPlane/quadplane.cpp
> +            if (poscontrol.slow_descent && 0) {
did you really want that && 0 ??

2021-04-21 10:04 UTC, IamPete1 commented on ArduPlane/quadplane.cpp
> +            if (poscontrol.slow_descent && 0) {
no, left over from testing, removed.

2021-04-28 08:06 UTC, tridge requested changes

2021-04-28 08:06 UTC, tridge commented on ArduPlane/quadplane.cpp
> +            pos_control->set_alt_target_with_slew(target_altitude_cm, plane.G_Dt);
might need diff between home and origin ?

2021-04-28 08:06 UTC, tridge commented on ArduPlane/quadplane.cpp
> +    // defualt back to old method
speeeling

2021-04-28 08:06 UTC, tridge commented on ArduPlane/quadplane.cpp
> +            float terrain_altitude_offset_cm;
should be _m not _cm

2021-05-02 08:51 UTC, tridge approved these changes

2021-05-02 08:51 UTC, merged