RC_Channel: correct metadata for fence enable and rst mode
ArduPilot/ardupilot pull request #17217
Opened 2021-04-18 14:04 UTC by Hwurzburg

2021-04-18 14:29 UTC, khancyr approved these changes
LGTM

2021-04-19 00:04 UTC, rmackay9 requested changes
It seems that RCx_OPTION =96 is only implemented for Plane.  So we should either implement it for all vehicles or we should remove the item for Copter and shouldn't add the item for Rover.

By the way, this can be tested in SITL by setting RC6_OPTION to 6 and then the message, "Invalid channel option (96) appears"

2021-04-20 00:37 UTC, joshanne commented
Fence LGTM.

2021-04-20 01:45 UTC, peterbarker approved these changes

2021-04-20 06:14 UTC, merged