AP_OSD: Add fence indicator panel
ArduPilot/ardupilot pull request #17303
Opened 2021-04-29 17:50 UTC by Hwurzburg

Adds Fence status icon panel to OSD....shows if enabled, disabled, or in breach....works even if in Reporting Only mode for breaches, if fence is enabled...

2021-04-30 18:24 UTC, Hwurzburg commented
other options for a fence icon:
![Screenshot from 2021-04-30 13-13-49](https://user-images.githubusercontent.com/6076534/116737929-6e536300-a9b7-11eb-8f18-d2ff561d8737.png)
![Screenshot from 2021-04-30 13-14-40](https://user-images.githubusercontent.com/6076534/116737931-6eebf980-a9b7-11eb-8638-232b6d49fdf6.png)
![Screenshot from 2021-04-30 13-15-55](https://user-images.githubusercontent.com/6076534/116737932-6eebf980-a9b7-11eb-9d5b-7274dd525092.png)
![Screenshot from 2021-04-30 13-17-54](https://user-images.githubusercontent.com/6076534/116737934-6eebf980-a9b7-11eb-94a0-44b177348310.png)
![Screenshot from 2021-04-30 13-20-16](https://user-images.githubusercontent.com/6076534/116737935-6f849000-a9b7-11eb-9525-33e6b0e74613.png)

2021-04-30 23:28 UTC, peterbarker requested changes
Found the problem.  It is actually relatively straight forward from the test output in CI - once you can catch the subtlety!

2021-04-30 23:28 UTC, peterbarker commented on libraries/AP_OSD/AP_OSD_Screen.cpp
> +    AP_SUBGROUPINFO(fence, "FENCE", 59, AP_OSD_Screen, AP_OSD_Setting),
```suggestion
    // @Param: FENCE_EN_Y
    // @DisplayName: FENCE_EN_Y
    // @Description: Vertical position on screen
    // @Range: 0 15
    AP_SUBGROUPINFO(fence, "FENCE_EN", 59, AP_OSD_Screen, AP_OSD_Setting),
```

2021-05-01 04:39 UTC, peterbarker reviewed
*Sigh*.  Maybe this time?

Its almost like we need to have `FENEN` rather than `FENCE` here, so

`FENEN_EN`, `FENEN_X`, `FENEN_Y` rather than `FENCE_EN`, `FENCE_X` and `FENCE_Y`

But that's a different argument.

2021-05-01 04:39 UTC, peterbarker commented on libraries/AP_OSD/AP_OSD_Screen.cpp
> +    // @DisplayName: FENCE_EN_X
```suggestion
    // @Param: FENCE_X
    // @DisplayName: FENCE_X
```

2021-05-01 04:39 UTC, peterbarker commented on libraries/AP_OSD/AP_OSD_Screen.cpp
> +    // @DisplayName: FENCE_EN_Y
```suggestion
    // @Param: FENCE_Y
    // @DisplayName: FENCE_Y
```

2021-05-01 12:18 UTC, Hwurzburg commented
@peterbarker if it works I will squash before devcall, which I wont make....on the road for 5 days

2021-05-02 11:33 UTC, Hwurzburg commented
@peterbarker darn! still not emitting! this beast will not die!

2021-05-03 00:13 UTC, peterbarker requested changes

2021-05-03 00:13 UTC, peterbarker commented on libraries/AP_OSD/AP_OSD.h
> +    AP_OSD_Setting fence{true,14,9};
```suggestion
    AP_OSD_Setting fence{true, 14, 9};
```

2021-05-03 00:13 UTC, peterbarker commented on libraries/AP_OSD/AP_OSD_Screen.cpp
> +    AP_SUBGROUPINFO(fence, "FENCE_EN", 59, AP_OSD_Screen, AP_OSD_Setting),
```suggestion
    AP_SUBGROUPINFO(fence, "FENCE", 59, AP_OSD_Screen, AP_OSD_Setting),
```

I think this was my first wild-assed solution - which was wrong and needs to be reverted.

2021-05-03 00:13 UTC, peterbarker commented on libraries/AP_OSD/AP_OSD_Screen.cpp
> +    backend->write(x, y, fenceptr->get_breaches(), "%c", SYM_FENCE_ENABLED);
```suggestion
        backend->write(x, y, fenceptr->get_breaches(), "%c", SYM_FENCE_ENABLED);
```

2021-05-03 00:13 UTC, peterbarker commented on libraries/AP_OSD/AP_OSD_Screen.cpp
> +    backend->write(x, y, false, "%c", SYM_FENCE_DISABLED);
```suggestion
        backend->write(x, y, false, "%c", SYM_FENCE_DISABLED);
```

2021-05-03 12:12 UTC, Hwurzburg commented
@peterbarker so line 187,the macro, has a requirement for spaces in the arguments? that was the culprit?
in the dev-call, once everyone decides on the icon, I will change and squash and then someone merge after the CI passes again, if agreed..

2021-05-04 00:15 UTC, tridge commented
I like the diagonal FEN myself, I think it is clearer

2021-05-05 01:07 UTC, peterbarker requested changes
DevCall outcome was a request to move from the little fence picture to the diagonal `FEN` picture.

2021-05-06 21:48 UTC, peterbarker approved these changes
LGTM.

The travis failure can be ignored.

2021-05-10 23:36 UTC, tridge approved these changes

2021-05-10 23:36 UTC, merged