ACC & GYR move log structs to AP_InertialSensor & remove redundant nullptr check
ArduPilot/ardupilot pull request #17310
Opened 2021-04-30 08:18 UTC by hendjoshsr71

This moves the `GYR` & `ACC` log structs from `AP_Logger` to `AP_IntertialSensor`. And places the logging to `AP_IntertialSensor_Logging.cpp`

Removes a redundant logger nullptr check that is already covered in `should_log_imu_raw()`.

**Before PR**
![before_pr_x_z](https://user-images.githubusercontent.com/69225461/116668014-e0518b00-a96a-11eb-8e0b-07d1cfcbd99e.png)

**After PR**
![after_pr_x_z](https://user-images.githubusercontent.com/69225461/116668051-eba4b680-a96a-11eb-8782-7193fd2dbc33.png)

2021-04-30 09:54 UTC, khancyr approved these changes
LGTM

2021-04-30 11:55 UTC, peterbarker requested changes
I'd have merged this right now if the nullptr check was still in there.

Just because someone is *currently* making the nullptr check doesn't mean they will be in the future.  or that someone else will call it.

I think it's all kind of crap anyway - shouldn't be checking the pointer and then using the singleton, really.

Its something we should fix in another PR - not this one.  If we can guarantee that AP::logger() will either fail to compile or gives you a valid reference then we can remove the check entirely (and from many other places probably).

Please throw the check back in..

2021-05-01 04:15 UTC, peterbarker approved these changes

2021-05-01 04:15 UTC, merged

2021-05-01 04:16 UTC, peterbarker commented
Thanks @hendjoshsr71 .

Merged it.

2022-03-02 22:03 UTC, Udik2021 approved these changes