autotest:Copter test fix for some frames
ArduPilot/ardupilot pull request #17321
Opened 2021-05-01 08:47 UTC by arshPratap

provided a solution for some of the frames listed here #17318.
Thanks !!

2021-05-01 16:36 UTC, khancyr commented on Tools/autotest/default_params/copter-octaquad-cwx.parm
> +FRAME_TYPE     14
I doubt that is the same as hexa

2021-05-02 05:04 UTC, peterbarker requested changes
@arshPratap please correct the frame types.  You're after the `motor_frame_type` enumeration from `AP_Motors_Class.h`

2021-05-17 10:32 UTC, peterbarker commented
Nudge @arshPratap

2021-05-19 23:05 UTC, arshPratap commented
> @arshPratap please correct the frame types. You're after the `motor_frame_type` enumeration from `AP_Motors_Class.h`

@peterbarker  Sir, am a little confused with the exact configuration to use.Based on the #17318 , I thought we had to use the frame type configuration for each file.

2021-05-20 00:47 UTC, jmachuca77 commented
Looks like you need both FRAME_CLASS and FRAME_TYPE parameters 
https://ardupilot.org/copter/docs/parameters.html#frame-class-frame-class
https://ardupilot.org/copter/docs/parameters.html#frame-type-frame-type-x-v-etc

2021-05-20 02:45 UTC, arshPratap commented
I have made the suggested changes. @peterbarker  sir, please take a look thanks

2021-06-08 06:50 UTC, peterbarker approved these changes
LGTM

2021-06-08 06:50 UTC, merged

2021-06-08 06:50 UTC, peterbarker commented
Merged, thanks!