AC_AutoTune:  Disable variables that are overwritten
ArduPilot/ardupilot pull request #17341
Opened 2021-05-04 00:46 UTC by muramura

FALLTHROUGH implements the following CASE process.
Therefore, the setting of the MODE variable will be overwritten.
Therefore, I commented it out.

2021-05-04 10:10 UTC, khancyr approved these changes
LGTM.
That save one assignment.

2021-05-04 23:26 UTC, rmackay9 requested changes
OK interesting.  We normally don't leave commented out code in place though so we should remove all four lines so that FAILED is directly above UNINITIALISED.

2021-05-05 00:25 UTC, peterbarker requested changes
Looks innocuous, but we're now passing through the backup_gains_and_initialise() function in a different mode.

The comment above the modified line is now out-of-date, too.

2021-05-05 00:41 UTC, rmackay9 commented
As discussed offline with @peterbarker backup_gains_and_initialise() doesn't use the mode so that part of it should be ok for now and we can look for problems in the future if that method is changed.

2021-05-05 09:53 UTC, peterbarker commented
I've removed the extra line and marked this as MergeOnCIPass

2021-05-06 02:02 UTC, merged