AP_Frsky_Telem: new parameter for the default FRSky passthrough sensor ID
ArduPilot/ardupilot pull request #17362
Opened 2021-05-05 09:39 UTC by yaapu

This is a followup to [this](https://discuss.ardupilot.org/t/passthrough-telemetry-id/70825) user request to allow changing ArduPilot's default passthrough sensor ID which is hardcoded at 0x1B.
A new parameter **FRSKY_DNLINK_ID** has been added which allows customization.

- [ ]  waiting for user confirmation that this fixes the issue

2021-05-12 07:42 UTC, tridge requested changes

2021-05-12 07:42 UTC, tridge commented on libraries/AP_Frsky_Telem/AP_Frsky_Parameters.cpp
> +    AP_GROUPINFO("DNLINK_ID",  2, AP_Frsky_Parameters, _dnlink_id, 27),
should move to next id

2021-06-02 08:00 UTC, tridge approved these changes

2021-06-03 03:58 UTC, merged

2021-06-03 03:59 UTC, peterbarker commented
Merged, thanks!