AP_RCProtocol: Disable the process because the slot ID is not checked
ArduPilot/ardupilot pull request #17385
Opened 2021-05-08 12:42 UTC by muramura

I did not check the slot IDs, so I disabled the process.
I described the rules for slot IDs.

2021-05-08 12:54 UTC, andyp1per commented
I'd be inclined to delete the code - we have git history

2021-05-08 13:44 UTC, muramura commented
@andyp1per san. Leave the rules for slot IDs in frame[24].

2021-05-08 20:43 UTC, tridge commented
> I'd be inclined to delete the code - we have git history

I agree, let's just remove it

2021-05-09 11:34 UTC, peterbarker requested changes
Changes were requested.

2021-05-10 13:20 UTC, muramura commented
@peterbarker san.  I will remove the invalid Slot ID check.

2023-06-16 10:33 UTC, peterbarker approved these changes
LGTM, this is what was asked for.

2023-06-19 23:06 UTC, merged