AP_RPM: added and RPM driver for BLHeli ESC telemetry
ArduPilot/ardupilot pull request #17392
Opened 2021-05-09 15:10 UTC by yaapu

This adds a new RPM driver based on BLHeli esc telemetry.
To enable set RPM_TYPE = 5.
A new parameter RPM_ESC_MASK allows the selection of which channels will be averaged to calculate the RPM value.

For a VTOL with 1 forward and 4 vertical motors one would set: 
RPM_TYPE=5
RPM_ESC_MASK=1 (assuming forward is channel 1)
RPM2_TYPE=5
RPM2_ESC_MASK=30 (assuming lift motors are 2,3,4,5)

flown on a kakuteF7 with tekko32 blheli32 esc.

2021-05-12 07:36 UTC, tridge requested changes

2021-05-12 07:36 UTC, tridge commented on libraries/AP_RPM/AP_RPM.cpp
> +    // @Values: 0:None,1:PWM,2:AUXPIN,3:EFI,4:Harmonic Notch,5:ESC Telemetry
maybe add type 6 as "average of vtol motor RPM" and type 7 as "average of fwd motors"?

2021-05-12 09:48 UTC, amilcarlucas commented
Can you use the new AT_ESC_Telem API instead of only supporting BL_Heli?

2021-05-12 10:03 UTC, yaapu commented
@amilcarlucas yep, was discussed during the call, will swith to the new API for sure!

2021-06-01 21:02 UTC, yaapu commented
Flight tested on MatekH743 tilt quadplane vtol

2021-06-02 07:57 UTC, tridge requested changes
the vtol/fwd functionality got a bit too complex, let's simplify a bit and see if we can get some basic functionality in

2021-06-02 07:57 UTC, tridge commented on libraries/AP_ESC_Telem/AP_ESC_Telem.cpp
> +    return get_average_motor_rpm(0) * 0.0166; // rpm/60
0 mask means no motors

2021-06-02 07:57 UTC, tridge commented on libraries/AP_RPM/AP_RPM.cpp
> +        if (type == RPM_TYPE_ESC_TELEM||type == RPM_TYPE_ESC_VTOL_LIFT||type == RPM_TYPE_ESC_VTOL_FORWARD) {
whitespace

2021-06-02 07:57 UTC, tridge commented on libraries/AP_RPM/RPM_ESC_Telem.cpp
> +    if (AP_Param::get(param_name,motor_mask)) {
much too slow to be doing on main thread at runtime
could use a param pointer, or get once at startup

2021-06-30 08:29 UTC, tridge requested changes

2021-06-30 08:29 UTC, tridge commented on libraries/AP_RPM/RPM_ESC_Telem.cpp
> +#ifdef HAL_WITH_ESC_TELEM
needs to be an #if

2021-07-02 05:35 UTC, merged

2021-07-02 05:35 UTC, peterbarker commented
@yaapu usually we'd want that last commit squashed in.  I merged this anyway - thanks :-)