Blimp: Remove comment out
ArduPilot/ardupilot pull request #17415
Opened 2021-05-11 20:27 UTC by muramura

I am unclear about the valid process by commenting out the process.
For example, I could not find #17412.
I will remove the processing comment-out.

2021-05-18 03:50 UTC, MichelleRos requested changes

2021-05-18 03:50 UTC, MichelleRos commented on Blimp/GCS_Mavlink.cpp
> -        // case PID_TUNING_ROLL:
As mentioned in my comment on #17412, I am currently implementing this code. If you want to remove this part from the PR then the rest looks ok.
Thanks.

2021-05-18 04:19 UTC, rmackay9 commented
If @MichelleRos is actively looking at implementing this code I think we should leave it in place.

@muramura is correct that we normally don't leave commented out code in place but I think we made an exception for Blimp so that it could be merged to master sooner.

I hope it's ok but I'm going to close this.  Thanks @muramura as always.

2021-05-18 04:35 UTC, MichelleRos commented
@rmackay9 Apologies for the slight misunderstanding - of this PR's changes I am only using the PID tuning code (lines 207-218). 
The rest I don't mind if it gets removed - I'll be neatening up all of it soon in any case. 🙂

2021-05-18 06:49 UTC, rmackay9 commented
@muramura, OK, if you'd like to just leave the commented-out code around the PID code then we can merge.txs!

2021-06-29 03:10 UTC, tridge commented
replaced by #17805

2021-06-29 03:10 UTC, closed without merging