Copter: Add WP front notifications to ZIGZAG mode
ArduPilot/ardupilot pull request #17456
Opened 2021-05-16 05:30 UTC by muramura

The distance from point A to point B in ZIGZAG mode will be several tens of meters to several hundred meters.
In this case, the operator will not know until the WP is reached.
In Japan, the assistant will notify the distance between the WP and the vehicle by transceiver.
The auxiliary notifies 10 meters, 5 meters, and 0 meters before the WP.
I would like to add this notification to ZIGZAG.

2021-05-16 06:22 UTC, khancyr reviewed
Adding this much parameters for optional notifications is a no go for me

2021-05-16 08:26 UTC, muramura commented
@Kametor san.
The parameters that could be reduced are 2 and 3.
In this case, if the distance to be notified can be calculated from the flight speed and the distance to the WP, and if the distance can be notified within 10m or 5m, I think 2 and 3 can be removed.
Is there a problem with my idea?
1. Suppression of message notification
2. 10 meter message notification distance
3. 5 meter message notification distance

2021-05-16 09:33 UTC, muramura commented
@khancyr san.
I made a decision based on the expected distance 500 milliseconds after the flight speed.
The 500 milliseconds takes into account the time it takes for the GCS to receive the message and provide voice notification.

2021-05-17 03:28 UTC, peterbarker commented
This information can be conveyed in the `NAV_CONTROLLER_OUTPUT` message instead.

Implement 
```
    virtual int32_t wp_bearing() const { return 0; }
    virtual uint32_t wp_distance() const { return 0; }
```

on mode_zigzag instead.

This information is presented in the MAVProxy interface you've pasted in anbove.

2021-05-17 03:33 UTC, peterbarker requested changes
Use `NAV_CONTROLLER_OUTPUT` instead.

2021-05-17 21:54 UTC, muramura commented
@peterbarker san.  I would change it to NAV_CONTROLLER_OUTPUT.

2021-05-17 23:25 UTC, muramura commented
I added the following methods.
I was able to get distance, direction and cross error in telemetry.

    uint32_t wp_distance() const override { return wp_nav->get_wp_distance_to_destination(); }
    int32_t wp_bearing() const override { return wp_nav->get_wp_bearing_to_destination(); }
    float crosstrack_error() const override { return wp_nav->crosstrack_error(); }

![Screenshot from 2021-05-18 08-07-58](https://user-images.githubusercontent.com/646194/118568352-9c57e600-b7b2-11eb-8246-c093de0a9d5c.png)

2021-05-18 06:55 UTC, khancyr approved these changes
Excellent, that is much better !

2021-05-20 00:21 UTC, peterbarker commented
Much nicer :-)

![image](https://user-images.githubusercontent.com/7077857/118900622-c0532d00-b954-11eb-92ea-f6da5772c868.png)

One caveat -  we send the `NAV_CONTROLLER_OUTPUT` all the time, and the packet doesn't have a field to indicate if it is in use.  That means MAVProxy has a fixed list of modes in which to display the `NAV_CONTROLLER_OUTPUT` message, and `ZIGZAG` isn't on that list.  I added it to take that screenshot.

What this means is that while being piloted in manual mode the distance-to-waypoint message will update to grow - as we're moving away from the previous target.

Still, this is much better than statustexts :-)

2021-05-20 00:22 UTC, peterbarker approved these changes

2021-05-24 23:44 UTC, rmackay9 commented
I'm not super keen on how it points towards the last waypoint when the pilot is flying the manually flying the vehicle.  I think we need to find a way so that the GCSs (especially MP) don't show the line pointing back to the last waypoint.  Could you try setting the distance to zero and see how the GCSs handle this?

2021-05-24 23:48 UTC, peterbarker commented on ArduCopter/mode.h
> +    float crosstrack_error() const override { return wp_nav->crosstrack_error(); }
We should send back zero for all of these while in the pilot-controlled aspect of zigzag.

2021-07-14 07:29 UTC, khancyr commented
@muramura hello, could you address Peter request ?

2023-09-21 13:32 UTC, closed without merging

2023-09-21 13:32 UTC, khancyr commented
closed by https://github.com/ArduPilot/ardupilot/pull/23327