AP_Motors: add throttle factor to MotorsMatrix
ArduPilot/ardupilot pull request #17461
Opened 2021-05-16 22:58 UTC by IamPete1

This adds throttle factor to motors matrix allowing GC offsets to be accounted for, a better approach than  https://github.com/ArduPilot/ardupilot/pull/17455. The new factors can only be set via scripting and the scripting matrix frame class. They would need to be calculated on a per vehicle basis. 

There is no clever handling of ranges, this should be done prior to setting from the script. If one just wants all out thrust at the expense of the CG offset at high throttle they should be scaled such that the min value is 1. If the offset should be accounted for at full throttle they should be scaled with the max value as 1.

We could potently do a better job of priority, but that would be a extensive re-write, it is expected the throttle factors should be close to 1, any larger deviation should be fixed in hardware.

2021-05-24 15:16 UTC, lthall commented
When we use scripting to define the motors, how do we ensure the motors are normalised properly after being set?
Do we need checks as we add each motor to ensure the values are not out of range?

2021-05-24 15:36 UTC, IamPete1 commented
@lthall Scripting has its own init function that does the normalization. 

https://github.com/ArduPilot/ardupilot/blob/16ba99149b495db68836dc464bbcfe5cc8b8b8be/libraries/AP_Motors/AP_MotorsMatrix.cpp#L43

Once the init is successful it locks out changing any of the factors.

2021-05-24 15:44 UTC, lthall requested changes

2021-05-24 15:44 UTC, lthall commented on libraries/AP_Motors/AP_MotorsMatrix.h
> +    void                add_motor_raw(int8_t motor_num, float roll_fac, float pitch_fac, float yaw_fac, uint8_t testing_order, float throttle_factor = 1);
We use 1.0f in these libraries.

2021-05-25 00:01 UTC, merged

2021-05-25 00:01 UTC, rmackay9 commented
Merged, thanks!