Add FF tuning items for Quadplane TX tuning
ArduPilot/ardupilot pull request #17521
Opened 2021-05-21 21:00 UTC by Hwurzburg

this is wip

2021-06-28 23:02 UTC, tridge requested changes

2021-06-28 23:02 UTC, tridge commented on ArduPlane/tuning.cpp
> +    case TUNING_RATE_PITCH_FF:
missing roll and yaw cases here

2021-06-28 23:06 UTC, Hwurzburg commented on ArduPlane/tuning.cpp
> +    case TUNING_RATE_PITCH_FF:
added...thanks

2021-07-05 23:00 UTC, tridge approved these changes

2021-07-05 23:00 UTC, merged