GCS_MAVLink: increase statustext queue size to 7 on low-mem boards
ArduPilot/ardupilot pull request #17549
Opened 2021-05-25 06:58 UTC by peterbarker

... and SITL....

Copter currently spits out so many messages on a banner-send (e.g what
we do when parameters are fetched) that it puses the first sent message
straight out of the queue before it gets a chance to be sent from the
queue.

Each entry is currently 88 bytes long, so this costs us 176 bytes of RAM on every board.

Closes https://github.com/ArduPilot/ardupilot/issues/17515

Note that a more elaborate fix here would be to run some sort of state machine which is reset any time we'd currently send all of these banner messages out.  It would then issue the statustexts only when the queue was empty or not full (or something).  That would likely cost us several hundred bytes of flash.

2021-05-26 05:52 UTC, rmackay9 commented
@peterbarker, looks like some kind of compile error involving a static assert.. no pressure but I'm keen on this one now that it resolves a 4.1 issue.

2021-05-26 08:55 UTC, tridge requested changes

2021-05-26 08:55 UTC, tridge commented on libraries/GCS_MAVLink/GCS.cpp
> +assert_storage_size<GCS::StatusTextQueue, 40> _assert_statustextqueue_size;
asserting the semaphore size??

2021-05-27 02:39 UTC, merged

2021-05-27 03:43 UTC, rmackay9 commented
Thanks very much for this.  One more 4.1 issue off the list!