Correct metadata that has BOTH range and value entries
ArduPilot/ardupilot pull request #17568
Opened 2021-05-26 16:06 UTC by Hwurzburg

having both screws up the GSC displays since it only expects one or the other to display....otherwise it concatenates both....have only checked Copter/Heli....will check other vehicles when time permits...

2021-05-31 05:40 UTC, magicrub approved these changes

2021-05-31 23:51 UTC, tridge commented
this is the issue:
![image](https://user-images.githubusercontent.com/831867/120249649-e8308200-c2be-11eb-8060-214af7f5fec9.png)

2021-05-31 23:53 UTC, rmackay9 requested changes
I think this is really a mission planner display issue.  Users should be able to select from the list or provide a specific value.

2021-06-01 00:05 UTC, rmackay9 commented
I've created a MP issue here https://github.com/ArduPilot/MissionPlanner/issues/2630 so I'm going to close this if that's OK.  We can always revisit / re-open if this isn't the correct decision.

2021-06-01 00:05 UTC, closed without merging