SITL: support ride along instances via JSON
ArduPilot/ardupilot pull request #17613
Opened 2021-05-31 21:23 UTC by IamPete1

This allows a primary SITL instance to share its physics model with slave instances. This is equivalent to two flight controllers being mounted to the same vehicle. This can be done with:

`./Tools/autotest/sim_vehicle.py -v ArduCopter --console --map --slave 1`

`./Tools/autotest/sim_vehicle.py -v ArduCopter -f json:0.0.0.0 -I1`

Both instances will then be lock-steeped together.

2021-06-28 23:05 UTC, tatsuy commented on Tools/autotest/sim_vehicle.py
> +                     help="Set the numver of JSON slave")
mistype. number

2021-06-28 23:10 UTC, davidbuzz commented
i added wiki needed, as this will need a little bit of documentation for user/s to know how to use, esp more than one slave, etc.

2021-06-28 23:17 UTC, tridge requested changes

2021-06-28 23:17 UTC, tridge commented on libraries/SITL/SIM_JSON_Master.cpp
> +void JSON_Master::receve(struct sitl_input &input)
spelling

2021-06-28 23:17 UTC, tridge commented on libraries/SITL/SIM_JSON_Master.cpp
> +JSON_Master::JSON_Master(const int32_t &num_slaves)
why a reference? implies it can change

2021-06-28 23:17 UTC, tridge commented on libraries/SITL/SIM_JSON_Master.cpp
> +        printf("Slave %u: listening on %u\n", list->instance, port);
check for return of bind and report error

2021-06-28 23:17 UTC, tridge commented on libraries/SITL/SIM_JSON_Master.cpp
> +    int length = asprintf(&send_buffer,"\n{\"timestamp\":%f,\"imu\":{\"gyro\":[%f,%f,%f],\"accel_body\":[%f,%f,%f]},\"position\":[%f,%f,%f],\"quaternion\":[%f,%f,%f,%f],\"velocity\":[%f,%f,%f],\"no_t
memory leak

2021-07-16 23:29 UTC, IamPete1 commented
Some fixes, some more still to be done.

2021-07-17 18:43 UTC, IamPete1 commented
Fixed up remaining issues and re-tested.

2021-08-02 23:20 UTC, rmackay9 commented on Tools/autotest/sim_vehicle.py
> +        cmd.extend(["--slave", str(opts.slave)])
should we avoid the use of the word "slave" these days?

2021-08-02 23:22 UTC, tridge approved these changes

2021-08-02 23:22 UTC, merged