Fix HAL_WITH_ESC_TELEM = 0 (ready for merge, but untested by CI)
ArduPilot/ardupilot pull request #17700
Opened 2021-06-08 09:03 UTC by amilcarlucas

- [x] Fixes compilation when HAL_WITH_ESC_TELEM = 0
- [x] Saves 8224 bytes on a Durandal ArduCopter build.
- [x]  Saves 3720 bytes on a SkyViper v2450 ArduCopter build.
- [x] Uses an empty AP_ESC_Telem_Backend class to minimize the patch size
- [ ] passes CI.

This is just #17511 without the last commit. That last commit makes CI test these changes, but confuses the heck out of the reviewers, so I omitted it here. #17511 was never meant to be committed, it was meant for reviewing and CI testing.

This PR does not use CI to test if it compiles with the changes, that was done by #17511

2021-06-08 10:10 UTC, tridge approved these changes

2021-06-08 11:22 UTC, andyp1per requested changes

2021-06-08 11:22 UTC, andyp1per commented on libraries/AP_BLHeli/AP_BLHeli.h
> -#ifndef HAL_WITH_ESC_TELEM
I don't think you can do this?

2021-06-09 11:42 UTC, merged

2021-06-09 11:42 UTC, peterbarker commented
Merged, thanks!