Rover: Set the waypoint hold time setting to 0 or more(Fix #17488)
ArduPilot/ardupilot pull request #17704
Opened 2021-06-08 15:12 UTC by muramura

Fix #17488

I determine if the message is a floating value and negative because it is a floating value.
I would prefer not to implement it differently from the MAVLINK specification.

2021-06-08 20:12 UTC, hendjoshsr71 requested changes
This a much better solution than what I had. And  it covers rover, copter, and sub too. 

One comment about catching the case if a user inputs something `>UINT16_MAX`.  As when the float gets cast to uint16 it will wrap to a much smaller value than a user would expect. 

I tested it using sitl on mission planner and QGC.

2021-06-14 22:18 UTC, hendjoshsr71 commented
@muramura Would you change, the title please? Something like, "AP_Mission: Set the waypoint hold time setting to 0 or more(Fix #17488)" As this effects more than just rover.

Tested this again in sitl
Mission Planner with -1, splines and WPs (copter/rover)
![image](https://user-images.githubusercontent.com/69225461/121823099-1031c500-cc71-11eb-8e1d-cd0a20ea1506.png)

QGC: (copter/rover)

![image](https://user-images.githubusercontent.com/69225461/121944331-8e997000-cd20-11eb-89d7-474a5a6cf43c.png)

MavProxy: (copter/rover)
It doesn't seem to notify the user of the failure to upload invalid waypoints. And uploads only the waypoints up to the the invalid point.

2021-06-19 06:58 UTC, muramura commented
@hendjoshsr71 san. I have changed the title.

2021-06-21 06:49 UTC, rmackay9 requested changes
Thanks for this.

Let's not reject the whole command if the delay is negative, instead let's just use it as zero.

I understand the desire to want to tell the user they've made a mistake so they can fix it but many times the user just doesn't care, they just want the vehicle to get moving so we need to be more forgiving.

2021-06-21 07:21 UTC, peterbarker commented
I'd prefer to reject netgative values.  The metadata contains sufficient information to reject the input on the GCS side - i.e. we shouldn't ever be passed these by a GCS.

This allows negative values to take on some new meaning in the future without leading to nasty outcomes for users whose missions we're "just coping with".

2021-06-21 08:04 UTC, rmackay9 commented
@peterbarker, I think this PR affects mission commands, not real-time commands sent by the ground station.

I think rejecting a mission that is uploaded is going to be difficult for users to handle.  They will struggle to determine which mission command is causing the problem I think.

2021-06-21 08:43 UTC, hendjoshsr71 commented
In the screenshots above I thought it was pretty apparent which command failed? (QGC gives Command # and Param Value)
Though both QGC and Mission Planner could take a few elements from each other to display this a bit better. 

Yeah the GCSs really could already filter the negative values for us with the metadata...

2021-06-21 12:26 UTC, muramura commented
@rmackay9 san. fc judges each mission by handshaking.  Since the result is returned to gcs each time, processing can be interrupted in real time.  Since the processing result is binary, it is easy for gcs to process.

2021-06-21 12:56 UTC, rmackay9 commented
Really?  Do you all really think this is going to do anything besides waste users time?

2021-06-21 14:06 UTC, muramura commented
In the sanity_check_params method of the mavlink_int_to_mission_cmd method, if NAN is set in the parameter, a parameter error is returned in the response.
After this, it is a good sequence to check the parameters of each command.
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Mission/AP_Mission.cpp#L858

2021-06-21 23:38 UTC, tridge commented
I prefer treating -1 as no delay

2021-06-21 23:45 UTC, tridge commented
checking for NaN would make sense though

2021-06-21 23:50 UTC, rmackay9 commented
We discussed this on the dev call and although it wasn't unanimous we decided that rejecting the command (and thus the mission) because the delay is negative is only going to cause user pain without a lot of benefit.

We also agreed that the GCSs should be checking that the fields are within the appropriate range.

2021-11-17 05:38 UTC, hendjoshsr71 commented
@muramura Are able to get this one fixed according to the above comments? If not I can do so?

2021-11-19 23:52 UTC, muramura commented
@hendjoshsr71 san
I dealt with it in Missopn Planner and merged it into Master.
I know that, by this merge, Mission Planner does not send negative values.
I will close this PR.

https://github.com/ArduPilot/MissionPlanner/pull/2679

2021-11-19 23:52 UTC, closed without merging

2021-11-22 20:03 UTC, hendjoshsr71 commented
@muramura san Thank you for your efforts to fix it on Mission Planner. However, I presume the issue still exists on MAVPRoxy and QGC? Also there other GCSs out there as well: UGCS for example. 

I still think there is value in adding this to protect against NANs and to ensure reasonable behavior for this case?

If you want I can do this?

2021-11-24 01:06 UTC, muramura commented
@hendjoshsr71 san

I think it's good to check with fc.  There is no guarantee that the parameters of the mavlink command will not be set to negative values.