AP_HAL_ChibiOS: remove bl embed in MatekF405-Wing
ArduPilot/ardupilot pull request #17719
Opened 2021-06-09 08:48 UTC by bugobliterator

Target         Text    Data  BSS     Total  
--------------------------------------------
bin/arduplane  955440  1900  129256  1086596

Target         Text    Data  BSS     Total  
--------------------------------------------
bin/arduplane  943896  1900  129256  1075052

saves 11.5KB

2021-06-13 14:06 UTC, nkruzan commented
Does this mean the "arduXXX_with_bl.hex" will not be generated? Used as described here https://ardupilot.org/plane/docs/common-loading-firmware-onto-chibios-only-boards.html#download-the-ardupilot-firmware

2021-06-13 15:31 UTC, bugobliterator commented
> Does this mean the "arduXXX_with_bl.hex" will not be generated? Used as described here https://ardupilot.org/plane/docs/common-loading-firmware-onto-chibios-only-boards.html#download-the-ardupilot-firmware

No, this will not do that. This just removes bl copy that we maintain inside the firmware.

2021-06-16 08:37 UTC, tridge requested changes
i think this should be an option for the custom fw server, but not enabled yet

2021-06-23 01:14 UTC, peterbarker requested changes
Resolution at the call was add the infrastructure but remove the use of it, I think?

2021-06-23 01:14 UTC, peterbarker commented on libraries/AP_HAL_ChibiOS/hwdef/MatekF405-Wing/hwdef.dat
> +BOOTLOADER_EMBED 0
```suggestion
```

2021-06-23 05:24 UTC, peterbarker commented
Needs a rebase somehow

2021-06-23 05:25 UTC, peterbarker commented
Could we also fix this to have a single ommit, `AP_HAL_ChibiOS: allow embedded bootloader to be excluded` ?

2021-06-23 08:15 UTC, tridge approved these changes

2021-06-23 22:36 UTC, merged