Copter: Append the flight mode number to the message
ArduPilot/ardupilot pull request #17754
Opened 2021-06-12 16:20 UTC by muramura

There is a time lag between the response to the MAVLINK message and the GCS message.
I can convert the GCS message to a flight name if there is a flight mode number in the message.

![Screenshot from 2021-06-13 01-11-43](https://user-images.githubusercontent.com/646194/121782632-81c43180-cbe5-11eb-96c4-ba70f48aaaf1.png)

2021-06-12 22:34 UTC, peterbarker requested changes
Equivalent change should be made in Blimp.  Let's try not to have *5* different versions of the same stuff.

For reference, Plane says
```
        gcs().send_text(MAV_SEVERITY_INFO, "Error: invalid mode number: %u", (unsigned)new_mode);
```

and Tracker/Sub/Rover say nothing.

We should be consistent across all our vehicles with this error message.

Plane's error wording is better but shouldn't have `Error:` in front of it if we're sending it as `MAV_SEVERITY_INFO` :-)

2021-06-12 22:34 UTC, peterbarker commented on ArduCopter/mode.cpp
> +        gcs().send_text(MAV_SEVERITY_WARNING,"No such mode %d", uint8_t(mode));
```suggestion
        gcs().send_text(MAV_SEVERITY_WARNING,"No such mode %u", uint8_t(mode));
```

2021-06-12 22:46 UTC, muramura commented
@peterbarker san.
In case of INFO at GCS message level, QGC does not give voice notification.
This is coded to, voice notification of GCS messages above NOTICE.
We want this PR message to be voice-delivered, so we will leave it as it is.

2021-06-14 23:52 UTC, peterbarker requested changes
Please move Plane's no-such-mode function up to AP_Vehicle and call that instead.

2021-06-19 06:36 UTC, muramura commented
@peterbarker san. I have reflected on the review comments.

2022-01-11 16:35 UTC, closed without merging