AC_AttitudeControl:AC_PosControl: vibration failsafe fix
ArduPilot/ardupilot pull request #17837
Opened 2021-06-22 14:45 UTC by lthall

This PR fixes#17834

2021-06-22 14:50 UTC, amilcarlucas requested changes

2021-06-22 14:50 UTC, amilcarlucas commented on libraries/AC_AttitudeControl/AC_PosControl.cpp
>      // add velocity error to current velocity
Comment must be updated

2021-06-22 15:21 UTC, lthall commented on libraries/AC_AttitudeControl/AC_PosControl.cpp
>      // add velocity error to current velocity
Thanks, done.

2021-06-23 01:26 UTC, rmackay9 approved these changes
I've tested in SITL and this fixes the vibration failsafe, thanks!
![before-vs-after](https://user-images.githubusercontent.com/1498098/123020595-8242a080-d40d-11eb-9859-0e50492d03c4.png)

2021-06-23 01:29 UTC, merged