GCS_MAVLink: Do not operate on variables with NAN set
ArduPilot/ardupilot pull request #17865
Opened 2021-06-26 16:59 UTC by muramura

The variable value that NAN was set to was set to an integer type variable.
This setting caused SITL to stop processing.
I expect ArduPilot to work properly even when NAN is set in GCS.
I know that the GCS developers do not understand the source of ArduPilot.

2021-07-14 08:37 UTC, tridge requested changes
it isn't clear that silencing these is the right thing to do given QGC now may send these. I think this PR would stop the SITL fault, but wouldn't leave us with right behaviour

2021-07-14 08:37 UTC, tridge commented on libraries/GCS_MAVLink/GCS_Common.cpp
> +    if (isnan(packet.param1)) {
this would deny on commands that don't use any of the parameters, that doesn't seem reasonable

2021-07-14 08:37 UTC, tridge commented on libraries/GCS_MAVLink/GCS_Common.cpp
> +    out.param1 = isnan(in.param1)?std::numeric_limits<double>::quiet_NaN():in.param1;
what impact does this change make?
and why double?

2021-07-14 08:37 UTC, tridge commented on libraries/GCS_MAVLink/GCS_Common.cpp
> +        out.x = isnan(in.param5)?std::numeric_limits<double>::quiet_NaN():in.param5;
this is putting a nan into an int?

2021-09-18 00:12 UTC, rmackay9 commented
A discussion about AP's handle of NANs came up here in the 4.1.0 beta testing category https://discuss.ardupilot.org/t/copter-4-1-0-rc1-released-for-beta-testing/75878/32

2023-06-16 10:53 UTC, peterbarker commented
NeedRework since 2021; please re-open if you want to pursue, having addressed the review comments.

2023-06-16 10:53 UTC, peterbarker commented
NeedRework since 2021; please re-open if you want to pursue, having addressed the review comments.

2023-06-16 10:53 UTC, closed without merging