Send new BATTERY_EXTENDED_STATUS message
ArduPilot/ardupilot pull request #17870
Opened 2021-06-27 05:33 UTC by peterbarker

Supposed to contain lower-rate data.

Alternative to https://github.com/ArduPilot/ardupilot/pull/17869 which @WickedShell has reservations about due to bandwidth issues.

2021-06-27 05:40 UTC, peterbarker commented
```
STABILIZE> 976: BATTERY_EXTENDED_STATUS {id : 0, internal_resistance : 0.000883447122760117}
```

2021-06-28 23:47 UTC, tridge commented
using a new OPTIONS bit per battery to ask it to send the resting voltage estimate over mavlink would be simpler in many ways

2021-06-28 23:48 UTC, tridge requested changes

2021-06-28 23:48 UTC, tridge commented on libraries/GCS_MAVLink/GCS_Common.cpp
> +        CHECK_PAYLOAD_SIZE(BATTERY_EXTENDED_STATUS);
only for batteries that can monitor both voltage and current

2021-06-29 13:24 UTC, nkruzan commented on libraries/GCS_MAVLink/GCS_Common.cpp
> +        return true;
doesn't this only report the first battery? comment is "returns true if all battery instances were reported" but seems to return true after first message sent.

2022-10-28 06:10 UTC, closed without merging