AP_Frsky_Telem: added an airspeed OPTIONS flag to frame 0x5005
ArduPilot/ardupilot pull request #17894
Opened 2021-06-29 06:24 UTC by yaapu

added a new parameter FRSKY_OPTIONS to enable sending airspeed and groundspeed on the same frame 0x5005

2021-06-30 08:41 UTC, tridge requested changes

2021-06-30 08:41 UTC, tridge commented on libraries/AP_Frsky_Telem/AP_Frsky_Parameters.cpp
> +    // @Param: _OPTIONS
remove the leading _ in OPTIONS

2021-07-07 01:52 UTC, peterbarker reviewed
Looks reasonable, but the naming here could be better.

2021-07-07 01:52 UTC, peterbarker commented on libraries/AP_Frsky_Telem/AP_Frsky_Backend.h
> +    };
```suggestion
    enum class Option : uint8_t {
        AIRSPEED_AND_GROUNDSPEED = 1U<<0,
    };
```

2021-07-07 01:52 UTC, peterbarker commented on libraries/AP_Frsky_Telem/AP_Frsky_SPort_Passthrough.cpp
> +    bool option_airspeed_enabled = (_frsky_parameters->_options & frsky_options_e::OPTION_AIRSPEED_AND_GROUNDSPEED) != 0;
```suggestion
    bool option_airspeed_enabled = (_frsky_parameters->_options & Option::AIRSPEED_AND_GROUNDSPEED) != 0;
```

2021-07-07 01:53 UTC, merged

2021-07-07 01:53 UTC, peterbarker commented
Merged, thanks!

2021-07-07 11:45 UTC, Hwurzburg commented
Sorry, I am just seeing this and commenting.....but Alex, why wouldnt you always send this , and if airspeed not available send it as -1 and let the script or script config option decide to display? that way the default is enabled....can possibly even not have a parameter for this.....otherwise it requires the user to know about this and adjust the parameter.....

2021-07-07 13:12 UTC, yaapu commented
@Hwurzburg  flightdeck does not understand it and would display in the same spot airspeed and groundspeed alternating, pretty confusing for a user, so to guarantee retro compatibility I had to make it an option which on Hoprus class radios I can eventually toggle automatically using mavlite