AP_Landing: enable deepstall landing to be compiled out of the code
ArduPilot/ardupilot pull request #17918
Opened 2021-07-02 01:09 UTC by peterbarker

2021-07-02 01:30 UTC, peterbarker commented
We probably want a prearm check that the landing type configured in `LAND_TYPE` is valid before this goes in.

2021-07-02 07:18 UTC, khancyr approved these changes
LGTM

2021-07-06 00:08 UTC, tridge requested changes

2021-07-06 00:08 UTC, tridge commented on libraries/AP_Landing/AP_Landing_Deepstall.cpp
> +#endif
add // HAL_LANDING_DEEPSTALL_ENABLED

2021-07-06 01:31 UTC, peterbarker commented on libraries/AP_Landing/AP_Landing_Deepstall.cpp
> +#endif
Done

2021-07-06 02:38 UTC, merged