Copter: Correct yaw expo range limit
ArduPilot/ardupilot pull request #17914
Opened 2021-07-01 11:58 UTC by lthall

This PR addresses the incorrect range limitation on yaw expo as discussed here:
https://discuss.ardupilot.org/t/valid-range-of-acro-y-expo-mismatch-between-source-code-and-documentation/73139

2021-07-01 22:38 UTC, khancyr reviewed
maybe adding a negative values in the param description would be great too ?

2021-07-01 23:43 UTC, rmackay9 requested changes
Great, thanks.  As @khancyr says the param description range should be updated as well to match.

2021-07-02 05:38 UTC, lthall commented
The param range does match:

    // @Param: ACRO_Y_EXPO
    // @DisplayName: Acro Yaw Expo
    // @Description: Acro yaw expo to allow faster rotation when stick at edges
    // @Values: 0:Disabled,0.1:Very Low,0.2:Low,0.3:Medium,0.4:High,0.5:Very High
    // @Range: -0.5 1.0
    // @User: Advanced
    AP_GROUPINFO("ACRO_Y_EXPO", 9, ParametersG2, acro_y_expo, ACRO_Y_EXPO_DEFAULT),

2021-07-02 07:06 UTC, merged

2021-07-02 07:06 UTC, rmackay9 commented
ok then! merged

2021-07-02 07:15 UTC, khancyr commented
I was thinking at @Values: -0.5: ? <-- I don't know what inverted expo does

2021-07-02 11:22 UTC, rmackay9 commented
@khancyr,  it bends the other way.. check out the link from Leonard's original discussion above and you'll see he's posted a picture..