waf: allow overriding uploader script with custom uploader script
ArduPilot/ardupilot pull request #17946
Opened 2021-07-06 16:17 UTC by bugobliterator

This allows for writing an alternate uploader script. 
My particular use case is to do development and builds on a Better Compute remote machine over SSH on my notebook. And still be able to upload firmware using --upload command with hardware connected to my notebook.

2021-07-07 07:40 UTC, tridge requested changes

2021-07-07 07:40 UTC, tridge commented on Tools/ardupilotwaf/chibios.py
> +        if 'AP_OVERRIDE_UPLOAD_CMD' in os.environ:
a comment, would be good as to what the script needs to be

2021-07-07 12:09 UTC, bugobliterator commented
Added reference script for upload via macos over SSH.

2021-07-09 08:18 UTC, tridge approved these changes

2021-07-09 08:19 UTC, merged