Copter and Plane: Allow alt-frames to be set
ArduPilot/ardupilot pull request #17957
Opened 2021-07-07 18:51 UTC by sjw58194

Applies to fence max altitude frame and min altitude frame.

References this PR: https://github.com/ArduPilot/ardupilot/pull/16452

2021-07-07 18:54 UTC, mday299 commented
+1

2021-07-08 09:19 UTC, amilcarlucas requested changes
drive-by review

2021-07-08 09:19 UTC, amilcarlucas commented on libraries/AP_Param/AP_Param.cpp
> +            // great idx 0 as 63 for duplicates. See group_id()
you added a typo here

2021-07-08 09:19 UTC, amilcarlucas commented on ArduPlane/Parameters.cpp
> -#if MAVLINK_COMM_NUM_BUFFERS >= 3
These look like unrelated changes.

2021-07-08 09:19 UTC, amilcarlucas commented on libraries/AC_Fence/AC_Fence.cpp
> +    // @Range: 0 1 2
Instead of range, I think you should use @values here, and add a text to each value.

2021-07-08 09:19 UTC, amilcarlucas commented on libraries/AC_Fence/AC_Fence.cpp
> +        case 1: // Relative
Use defines instead of hardcoding

2021-07-08 09:19 UTC, amilcarlucas commented on libraries/AC_Fence/AC_Fence.cpp
> +        case 1: // Relative
Again, use defines

2021-07-08 09:19 UTC, amilcarlucas commented on libraries/AC_Fence/AC_Fence.cpp
> +{
whitespace change

2021-07-08 09:19 UTC, amilcarlucas commented on libraries/AC_Fence/AC_Fence.h
> +
Why the new line

2021-07-08 09:19 UTC, amilcarlucas commented on libraries/AC_Fence/AC_Fence.h
> +    bool pre_arm_check_alt(const char* &fail_msg)  const;
Why the whitespace

2021-07-08 09:19 UTC, amilcarlucas commented on libraries/AC_Fence/AC_Fence.h
> +    AP_Int8         _alt_frame;             //
Please add a comment

2021-07-08 09:19 UTC, amilcarlucas commented on libraries/AP_Common/Location.cpp
> +
whitespace

2021-07-12 23:37 UTC, rmackay9 commented on ArduPlane/system.cpp
> +            ::fprintf(stderr, "Requested frame: ORIGIN\n");
let's not provide the option to set the fence alt above ekf origin.  just msl, origin and terrain for now would be good.

2021-07-12 23:37 UTC, rmackay9 commented on libraries/AC_Fence/AC_Fence.cpp
> +    // @Values: 0:MSL,1:REL/HOME,2:ORIGIN,3:TERRAIN
Let's change this to "0:MSL, 1:Relative To Hoem, 3:Terrain"

2021-07-12 23:39 UTC, tridge requested changes
randy suggests reducing the scope of the first version of the PR to home and AMSL, then add terrain later. The PR needs a lot of cleanup with the printf calls, and needs an autotest suite

2021-07-12 23:39 UTC, tridge commented on libraries/AC_Fence/AC_Fence.cpp
> +    // @Values: 0:MSL,1:REL/HOME,2:ORIGIN,3:TERRAIN
only AMSL, home and terrain

2021-07-12 23:39 UTC, tridge commented on libraries/AC_Fence/AC_Fence.cpp
> +    AP_GROUPINFO_FLAGS_FRAME("ALT_FRAME", 11, AC_Fence, _alt_frame, AC_FENCE_ALT_FRAME_DEFAULT, AP_PARAM_FLAG_SETHOOKS, AP_PARAM_FRAME_COPTER | AP_PARAM_FRAME_SUB | AP_PARAM_FRAME_TRICOPTER | AP_PARA
I don't understand why the SETHOOKS is needed?

2021-07-12 23:40 UTC, rmackay9 commented
I really like the idea and I'm sure users would appreciate this change.

2021-07-13 14:44 UTC, mday299 commented
@rmackay9 What test suite would you like @sjw58194 to use? GTest? Can you point us to any tutorials?

Thanks ahead of time.

2021-07-14 01:31 UTC, peterbarker commented
On Tue, 13 Jul 2021, Michael Day wrote:

> @rmackay9 What test suite would you like @sjw58194 to use? GTest? Can you point us to any tutorials?

Unit tests can be written using gtest 
(https://github.com/ardupilot/ardupilot/blob/master/libraries/AP_Common/tests/test_location.cpp#L1

autotests showing the vehicle behaving as appropriate can be written using 
the autotest framework 
(https://ardupilot.org/dev/docs/the-ardupilot-autotest-framework.html)

2021-07-16 13:57 UTC, closed without merging