Implement read() in terms of read(buffer, len)
ArduPilot/ardupilot pull request #17974
Opened 2021-07-09 03:25 UTC by peterbarker

2021-07-13 23:53 UTC, peterbarker commented
Serial-pass-through still works (tested on CubeBlack with USB+usb-tty adapter from telem1)

2021-07-14 00:04 UTC, peterbarker commented
slcan pass-through still works fine

2021-07-14 02:37 UTC, peterbarker commented
linux (navio2) still works just fine

2021-07-14 08:16 UTC, tridge requested changes
needs to be smaller or faster :-)

2021-07-14 08:16 UTC, tridge commented on libraries/AP_HAL/utility/BetterStream.h
> +    int16_t read() {
should be in cpp

2022-07-13 08:42 UTC, closed without merging