Dual GPS Heading support via AP_Periph and UAVCAN lib
ArduPilot/ardupilot pull request #17983
Opened 2021-07-09 18:48 UTC by bugobliterator

After the implementation one will be able to use two CAN AP_Periph GPS modules as dual heading CAN and also be able to combine them with Serial Ublox Compasses as Rover or Base

Tests:
- [ ]  HerePro(base) + HerePro(rover)
- [ ]  HerePro(base) + CubeOrange Serial GPS(rover)
- [ ]  CubeOrange Serial GPS(base) + HerePro(rover)

2021-07-22 10:47 UTC, MallikarjunSE commented
Hey @bugobliterator 
I tried this branch with 2×F412 CAN nodes with F9P.
As soon as I sent GPS_TYPE=22, 23, Mission planner stops showing GPS fix. When set as 9(UAVCAN), I get both GPS fix. 
I can see GPS config on nodes is changed to GPS_TYPE=17, 18.
Is there a way to check whether my setup is right?
Will mission planner output any error messages?
Thank you!

2021-07-23 19:05 UTC, bugobliterator commented
> Hey @bugobliterator
> I tried this branch with 2×F412 CAN nodes with F9P.
> As soon as I set GPS_TYPE=22, 23, Mission planner stops showing GPS fix(Goes to no fix). When set as 9(UAVCAN), I get both GPS fix.
> I can see GPS config on nodes is changed to GPS_TYPE=17, 18.
> Is there a way to check whether my setup is right?
> Will mission planner output any error messages?
> Thank you!

Did you set define GPS_MOVING_BASELINE 1 in your hwdef? Also need to update Cube firmware built from this PR.

2021-07-24 06:20 UTC, MallikarjunSE commented
Yes. I did. And I built Cube orange firmware from this PR. 
I'll try the updated PR again. Thank you!

2021-07-28 07:13 UTC, tridge requested changes
need to update AP_GPS::gps_yaw_deg() to play the same instance trick as used for ublox backend

2021-08-11 08:08 UTC, tridge requested changes

2021-08-11 08:08 UTC, tridge commented on libraries/AP_GPS/AP_GPS.cpp
> +            if (_mbl_data_cb != nullptr) {
i think this is simpler by exposing clear_RTCMv3() on AP_GPS, and then AP_Periph calls gps.get_RTCMv3(instance, rtcm_data, rtcm_len) and then calls the clear

2021-08-19 04:20 UTC, tridge approved these changes

2021-08-19 04:20 UTC, merged

2021-10-05 08:54 UTC, MallikarjunSE commented
Hey @bugobliterator 
Should I have to build firmware for Cube from this PR or Latest master will work fine?
For AP-Periph I have built from latest master. Is that okay?
Thank you!

2021-10-05 09:03 UTC, bugobliterator commented
> Hey @bugobliterator 
> Should I have to build firmware for Cube from this PR or Latest master will work fine?
> For AP-Periph I have built from latest master. Is that okay?
> Thank you!
> 

Yes, you need to build firmware for all hardware involved using latest master.

2021-10-05 09:23 UTC, MallikarjunSE commented
Thanks. I tried with all hardware on latest master. I couldn't get it to work. EKF3 still waiting for GPS config data messages. I have set CAN order, GPS_TYPE to 22, 23. GPS auto config to 2, using EKF3, EK3_SRC1_YAW is 2.

2021-10-05 11:07 UTC, MallikarjunSE commented
I built from your PR. MP shows "no fix" with both GPS detected. I don't get fix even though I get fix in GPS when checked from UAVCAN monitor. But F412 node hangs on AP-Periph built from your PR. 
Any suggestions?
Thank you!

2021-10-06 06:11 UTC, MallikarjunSE commented
Hey @bugobliterator 
Should both of these need to be defined? 
define GPS_MOVING_BASELINE 1
define GPS_UBLOX_MOVING_BASELINE TRUE
Also same goes on Cube hwdef?

2021-10-11 16:21 UTC, bugobliterator commented
@MallikarjunSE I will double check. I need to find time to prepare a wiki page for it.

2022-08-12 15:48 UTC, Hwurzburg commented
@bugobliterator @tridge 
the last comments from a user was that this was not working for him....we need a wiki page update! what was he doing wrong...from my reading he seemed to have things setup correctly...is it a connection issue? 

my reading of the above is that the CAN port on the autopilot needs a splitter to attach to both GPS so that they are on the same physical CAN bus, and that the two GPS must be connected together on their second bus...is this correct?
what, if any, other params not stated above in original comment must be setup?

also, to allow this to be used on an F9P UAVCAN GPS (like taking an MatekL431 and attaching the F9P GPS to it), the latest stable periph firmware must be used and MB_CAN_PORT set to ? under what conditions do you set 1 or 2?