Implementation of CRSF v3
ArduPilot/ardupilot pull request #17990
Opened 2021-07-10 13:47 UTC by andyp1per

2021-07-10 21:18 UTC, Hwurzburg commented
can we get an accessor for RX link quality...for both CRSF v2 and v3? for OSD support

2021-07-13 20:39 UTC, andyp1per commented
Code is now correct, but baud rate change step causes the RC to lose connection.

2021-07-16 15:40 UTC, yaapu approved these changes

2021-07-21 07:27 UTC, tridge requested changes

2021-07-21 07:27 UTC, tridge commented on libraries/AP_RCProtocol/AP_RCProtocol_CRSF.cpp
> +    _link_status.rssi = link->rssi_percent * 255.0f / 100.0f;
* 0.01

2021-07-21 07:27 UTC, tridge commented on libraries/AP_RCProtocol/AP_RCProtocol_CRSF.cpp
> +    _link_status.rssi = link->rssi_percent * 255.0f / 100.0f;
* 0.01

2021-08-03 18:53 UTC, andyp1per commented on libraries/AP_RCProtocol/AP_RCProtocol_CRSF.cpp
> +    _link_status.rssi = link->rssi_percent * 255.0f / 100.0f;
Fixed

2021-08-03 18:53 UTC, andyp1per commented on libraries/AP_RCProtocol/AP_RCProtocol_CRSF.cpp
> +    _link_status.rssi = link->rssi_percent * 255.0f / 100.0f;
Fixed

2021-08-03 18:54 UTC, andyp1per commented
Now flown with fw 6.07 - all working fine

2021-08-04 07:25 UTC, tridge approved these changes

2021-08-04 07:26 UTC, merged