Add support for Passthrough via USB with baud changes propagating to other port
ArduPilot/ardupilot pull request #17992
Opened 2021-07-10 18:22 UTC by bugobliterator

This allows for doing firmware updates to F9P via passthrough among other potential use cases.

2021-07-10 19:22 UTC, bugobliterator commented on libraries/AP_HAL_ChibiOS/Util.h
> +
```suggestion

```

2021-07-14 07:19 UTC, tridge requested changes

2021-07-14 07:19 UTC, tridge commented on libraries/AP_HAL_ChibiOS/hwdef/common/usbcfg.c
> +cdc_linecoding_t linecoding = {
should be static

2021-07-14 07:19 UTC, tridge commented on libraries/AP_HAL_ChibiOS/hwdef/common/usbcfg_dualcdc.c
> +cdc_linecoding_t linecoding = {
can be static

2021-07-14 07:19 UTC, tridge commented on libraries/AP_HAL_ChibiOS/hwdef/common/usbcfg_dualcdc.c
> +cdc_linecoding_t linecoding2 = {
static

2021-07-14 07:19 UTC, tridge commented on libraries/AP_HAL_ChibiOS/hwdef/common/usbcfg_dualcdc.c
> +cdc_linecoding_t linecoding2 = {
should be an array of 2 
linecoding[2]

2021-07-14 07:19 UTC, tridge commented on libraries/AP_HAL_ChibiOS/hwdef/common/usbcfg_dualcdc.c
> +  if ((usbp->setup[0] & USB_RTYPE_TYPE_MASK) == USB_RTYPE_TYPE_CLASS && usbp->setup[4] == 0x02 && usbp->setup[5] == 0x00) {
can remove the dup code if we make it an array

2021-07-14 07:19 UTC, tridge commented on libraries/AP_HAL_ChibiOS/hwdef/common/usbcfg_dualcdc.c
> +  if ((usbp->setup[0] & USB_RTYPE_TYPE_MASK) == USB_RTYPE_TYPE_CLASS && usbp->setup[4] == 0x02 && usbp->setup[5] == 0x00) {
const uint8_t key = usbp->setup[4]/2;

2021-07-21 07:06 UTC, tridge approved these changes

2021-07-21 07:06 UTC, merged

2022-02-26 01:28 UTC, rmackay9 commented
I struggled trying to add this to the 4.2 release notes because the description is so short.