Plane: QuadPlane: move tailsitter to class and hide params if not enabled
ArduPilot/ardupilot pull request #18015
Opened 2021-07-14 21:13 UTC by IamPete1

Part 2 of QuadPlane tidy up, this moves tailsitter to its own class with a enable that hides params when not in use. Apart from that this should be NFC.

The other big win here is that is is now very clear what is a tailsitter and what is not. Currently there are three params that can change that, Q_FRAME_CLASS, Q_TAILSIT_MOTMX, Q_TILT_TYPE.  Now we just have a enable, so its clear cut.

I would like to do this for tiltrotors too, but one thing at a time. 

The longer term goal is to have a separate tailsitter transition logic, hopefully that will simplify both. Would be nice to have different transition strategies that could be selected.

I have also lengthened the config error buffer so we can fit more useful messages. 

There are probably one or two other variables and such like that could be moved to the new class, but I wanted to keep to a minimum change set.

2021-07-14 23:33 UTC, IamPete1 commented
```
Binary           text            data         bss          total
---------------  --------------  -----------  -----------  --------------
antennatracker   0 (0.0000%)     0 (0.0000%)  0 (0.0000%)  0 (0.0000%)
arducopter       0 (0.0000%)     0 (0.0000%)  0 (0.0000%)  0 (0.0000%)
arducopter-heli  0 (0.0000%)     0 (0.0000%)  0 (0.0000%)  0 (0.0000%)
ardurover        0 (0.0000%)     0 (0.0000%)  0 (0.0000%)  0 (0.0000%)
arduplane        632 (+0.0377%)  0 (0.0000%)  0 (0.0000%)  632 (+0.0326%)
blimp            0 (0.0000%)     0 (0.0000%)  0 (0.0000%)  0 (0.0000%)
ardusub          0 (0.0000%)     0 (0.0000%)  0 (0.0000%)  0 (0.0000%) 
```

2021-07-15 00:23 UTC, IamPete1 commented on ArduPlane/quadplane.h
> +class Tailsitter; //forward declaration
Don't need this

2021-07-17 22:00 UTC, kd0aij commented on ArduPlane/quadplane.cpp
> +    // Set tailsitter enable flag based on old huristics
s/huristics/heuristics/

2021-07-17 22:04 UTC, IamPete1 commented on ArduPlane/tailsitter.cpp
> +    // @Description: This enables Sailboat functionality
Oops

2021-07-17 22:08 UTC, kd0aij commented on ArduPlane/quadplane.cpp
> +    // Set tailsitter enable flag based on old huristics
```suggestion
    // Set tailsitter enable flag based on old heuristics
```

2021-07-17 22:14 UTC, kd0aij reviewed
Good idea to shorten quadplane.cpp
Can't comment on the parameter move/conversion stuff, since I don't know how it works :)
Will passing autotest be sufficient to prove this is NFC?

2021-07-17 23:10 UTC, IamPete1 commented
I have just finished testing on lots of stuff in real-fligh:, Alti, griffin, convergence, Skycat, Cat and Striker. So have covered quadplanes, tilt rotors, TVBS, none-vectored tailsitters and copter tailsitters.

All seems to work as expected.

2021-07-20 13:42 UTC, IamPete1 commented
Rebased, dropped the board config error buffer change and shortened the error message.

2021-07-21 08:41 UTC, tridge requested changes

2021-07-21 08:41 UTC, tridge commented on ArduPlane/tailsitter.cpp
> +    if (!enabled() || plane.quadplane.motor_test.running) {
a quadplane reference would be nice in the constructor

2021-07-26 23:08 UTC, merged