AP_GPS: add binary CRC message parser abstract class
ArduPilot/ardupilot pull request #18012
Opened 2021-07-14 03:04 UTC by Femtomes

1. Add binary CRC message parser abstract class, 
2. Update nova driver use the parser

2021-07-14 21:40 UTC, amilcarlucas commented on libraries/AP_GPS/AP_GPS_BinaryCRCMessageParser.h
> +    const uint32_t CRC32_POLYNOMIAL = 0xEDB88320L;
static constexp

2021-07-14 21:47 UTC, amilcarlucas requested changes
Does this save memory? Will it be reused? What is the use case?

2021-07-14 21:47 UTC, amilcarlucas commented on libraries/AP_GPS/AP_GPS_BinaryCRCMessageParser.h
> +    uint8_t _decode_step = 0;   // step number of message decode
No need to init variables with 0. It is done automatically

2021-07-14 21:47 UTC, amilcarlucas commented on libraries/AP_GPS/AP_GPS_BinaryCRCMessageParser.cpp
> +    for ( i = 8 ; i > 0; i-- ) {
reduce the scope of the i variable, declare it inside the for loop

2021-07-14 21:47 UTC, amilcarlucas commented on libraries/AP_GPS/AP_GPS_BinaryCRCMessageParser.cpp
> +    return( crc );
why the parentheses?

2021-07-16 13:09 UTC, amilcarlucas approved these changes

2021-07-16 16:27 UTC, amilcarlucas requested changes

2021-07-16 16:27 UTC, amilcarlucas commented on libraries/AP_GPS/AP_GPS_BinaryCRCMessageParser.h
> +    static const uint32_t CRC32_POLYNOMIAL = 0xEDB88320L;
```suggestion
    static constexpr uint32_t CRC32_POLYNOMIAL = 0xEDB88320L;
```

2021-07-16 16:27 UTC, amilcarlucas commented on libraries/AP_GPS/AP_GPS_NOVA.cpp
> +    AP_GPS_BinaryCRCMessageParser({0xaa,0x44,0x12},4,sizeof(nova_msg.header),sizeof(nova_msg.data))
```suggestion
    AP_GPS_BinaryCRCMessageParser({0xaa,0x44,0x12}, 4, sizeof(nova_msg.header), sizeof(nova_msg.data))
```

2021-07-30 11:39 UTC, Femtomes commented
Are there any other issues?

2021-08-17 03:15 UTC, Vkd4U2NtVkZOVg commented
Hi @Femtomes , I have a question about this crc code. and also I test it on the nova driver, why can we use crc_crc32 from the AP_Math instead of write a new one?

2021-08-17 03:28 UTC, Femtomes commented
> Hi @Femtomes , I have a question about this crc code. and also I test it on the nova driver, why can we use crc_crc32 from the AP_Math instead of write a new one?

Oh! I don't know that the common source code of crc32 is already in the project. If it can match Nova's crc, I would prefer to use it.

2021-09-18 04:27 UTC, Femtomes commented
Reorganized code at #18690

2021-09-18 04:27 UTC, closed without merging