AP_BattMonitor: smbus remove unused returns on reads
ArduPilot/ardupilot pull request #18025
Opened 2021-07-15 08:09 UTC by hendjoshsr71

Removes the unused bool returns on the SMBus read register functions. 
Removes an unneeded temporary variable in `read_full_charge_capacity`.

Saves 64-72B depending on vehicle

2021-07-15 10:30 UTC, khancyr requested changes
Not really NFC as some logic were moved.
We truely don't use the return on those functions and it doesn't seems very usefull to have since most function are re-entrant and does correct checking.

2021-07-15 10:30 UTC, khancyr commented on libraries/AP_BattMonitor/AP_BattMonitor_SMBus.cpp
> +        _has_temperature = false;
miss a return here

2021-07-15 10:30 UTC, khancyr commented on libraries/AP_BattMonitor/AP_BattMonitor_SMBus.cpp
> +    read_word(BATTMONITOR_SMBUS_FULL_CHARGE_CAPACITY, _full_charge_capacity);
let's be pedantic here and keep checking the read_word return, that is cheaper than the *= anyway

2021-07-16 02:01 UTC, WickedShell requested changes
The temperature reading stuff is a bit of a preexsisting bug which your PR highlights, but it only slightly improves the failure case, and in some ways makes it worse. I think the suggestions will fix it. I'm good with the changes after the handling of `_has_temperature` gets looked at more.

2021-07-16 03:02 UTC, hendjoshsr71 commented on libraries/AP_BattMonitor/AP_BattMonitor_SMBus.cpp
> +    _state.temperature = ((float)(data - 2731)) * 0.1f;
Done.

2021-07-16 03:07 UTC, hendjoshsr71 commented on libraries/AP_BattMonitor/AP_BattMonitor_SMBus.cpp
> +    _has_temperature = (AP_HAL::millis() - _state.temperature_time) <= AP_BATT_MONITOR_TIMEOUT;
Done.

2021-07-16 03:07 UTC, hendjoshsr71 commented on libraries/AP_BattMonitor/AP_BattMonitor_SMBus.cpp
> +        return;
Fixed. I should have been thinking a step beyond to what the full intent of the code was even if the conversion I did was ok.

2021-07-16 03:10 UTC, hendjoshsr71 commented
Addressed the changes requested above.

2021-07-16 04:37 UTC, WickedShell approved these changes
> I should have been thinking a step beyond to what the full intent of the code was even if the conversion I did was ok.

No worries, it's one of those things that was much more apparent in the review, and when you are just refactoring it's easier to miss. Thanks for making the changes.

2021-07-18 23:12 UTC, peterbarker approved these changes
These should probably be `update_temp_reading` now.  But meh.

2021-07-18 23:13 UTC, merged