Emit event when EKF data source changed from primary/secondary/tertiary
ArduPilot/ardupilot pull request #18033
Opened 2021-07-16 02:30 UTC by peterbarker

This is an excerpt from a `test.Copter.GPSViconSwitching` log:

```
2021-07-16 12:24:46.640 SRC=250/250:AT-0021.5: SIM_VICON_FAIL is now 0.000000
2021-07-16 12:24:46.940 EKFPosSource MIDDLE
2021-07-16 12:24:46.940 Event: 86
2021-07-16 12:24:46.942 EKF3 IMU1 yaw aligned
```

The source was changed using a switch (the "MIDDLE" line), and the event indicating is then emitted.  

MAVProxy has a static map from number to description which will need updating.

2021-07-16 03:30 UTC, tridge approved these changes

2021-07-16 03:30 UTC, tridge commented
this is useful, but if you change before you arm then you don't get it. A field in a streaming msg would be good

2021-07-16 03:31 UTC, tridge requested changes
better to add a field to XKFS, which the the source selection log msg

2021-07-16 04:00 UTC, peterbarker commented
> better to add a field to XKFS, which the the source selection log msg

Alternatively, we could emit it at log startup.

Calling it out as an event means much lower logging for something maybe 0.01% of our users will ever realise exists.  It also has the advantage in log analysis that events are displayed prominently in both MAVProxy and MissionPlanner.

2021-07-16 04:08 UTC, tridge commented
> Calling it out as an event means much lower logging for something maybe 0.01% of our users will ever realise exists.

it's one byte in XKFS, and that is where we put all the other sensor selection. Will be much less flash too

2021-07-16 04:08 UTC, peterbarker commented
> > Calling it out as an event means much lower logging for something maybe 0.01% of our users will ever realise exists.
> 
> it's one byte in XKFS, and that is where we put all the other sensor selection. Will be much less flash too

I'm working that change up now for comparison....

2021-07-16 04:29 UTC, peterbarker commented
```
Binary           text           data         bss          total
---------------  -------------  -----------  -----------  -------------
antennatracker   32 (+0.0025%)  0 (0.0000%)  0 (0.0000%)  32 (+0.0021%)
arducopter       32 (+0.0019%)  0 (0.0000%)  0 (0.0000%)  32 (+0.0017%)
arducopter-heli  32 (+0.0019%)  0 (0.0000%)  0 (0.0000%)  32 (+0.0017%)
ardurover        32 (+0.0021%)  0 (0.0000%)  0 (0.0000%)  32 (+0.0018%)
arduplane        32 (+0.0019%)  0 (0.0000%)  0 (0.0000%)  32 (+0.0017%)
blimp            32 (+0.0026%)  0 (0.0000%)  0 (0.0000%)  32 (+0.0022%)
ardusub          32 (+0.0021%)  0 (0.0000%)  0 (0.0000%)  32 (+0.0018%)
```

2021-07-16 04:31 UTC, peterbarker commented
While we could add facility to log this state on log open, it would increase flash size and it wouldn't solve the problem that events can simply be lost if your SD card is bad.  The other PR is probably preferable.

2021-07-16 04:53 UTC, rmackay9 commented
how about we do both?

2021-08-11 10:28 UTC, rmackay9 approved these changes

2021-08-11 10:28 UTC, merged

2021-08-11 10:28 UTC, rmackay9 commented
Merged, thanks!