Restructure AHRS in preparation for frontend/backend split
ArduPilot/ardupilot pull request #18072
Opened 2021-07-20 12:41 UTC by peterbarker

This renames `AP_AHRS.*` to `AP_AHRS_Backend.*` and then `AP_AHRS_NavEKF.*` to `AP_AHRS.*`, and renames `AP_AHRS` -> `AP_AHRS_Backend` and then `AP_AHRS_NavEKF` -> `AP_AHRS`

Small adjustments were made for things like moving parameters to the new `AP_AHRS`.

There's now just AP_AHRS - no AP_AHRS_NavEKF object or AP::ahrs_navekf() accessor.

It also stops `AP_Vehicle` from giving the option to instantiate an `AP_AHRS_DCM` - on the assumption that the new `AP_AHRS` will cut all irrelevant stuff out based on `HAL_NAVEKF2_ENABLED` etc.

Rough plan for future PR making the split:
  - make `AP_AHRS_DCM` an actual backend
    - `AP_AHRS` stops inheritting from `AP_AHRS_DCM` and instead encapsulates an instance of `AP_AHRS_DCM`
      - all methods have `override` removed.  Where we were relying on behaviour from `AP_AHRS_DCM` or `AP_AHRS_Backend` we call a method on the `AP_AHRS_DCM _dcm;` object
      - `AP_AHRS_DCM`'s `get_position` method loses `virtual`.  The frontend will need smarts for this method, or we add a `allow_dead_reckoning` `bool` to `get_location` instead
  - make SITL an actual `AP_AHRS_Backend`
  - make External an actual `AP_AHRS_Backend`
  - make `NavEKF2` and `NavEKF3` backends
  - change all switch statements to work on an `*_active_ekf`
  - add a _backends array to iterate over, use it

Structure:
![image](https://user-images.githubusercontent.com/7077857/126324627-988b8a26-b745-4145-b47c-7709bbb4126f.png)

2021-07-20 12:43 UTC, peterbarker commented
Note that this patch really isn't actually all that big.  The renames aren't being handled well.

2021-07-20 23:40 UTC, peterbarker commented
```
                     master: bin/arduplane  1595548  2436  194380  1792364
                    This PR: bin/arduplane  1595560  2436  194376  1792372
 master / no EKF*_AVAILABLE: bin/arduplane  1350964  2432  194380  1547776
This PR / no EKF*_AVAILABLE: bin/arduplane  1350960  2432  194376  1547768
```

2021-07-21 06:28 UTC, peterbarker commented
I removed the `AP_AHRS_NAVEKF_AVAILABLE` with this PR.  I thought I'd do a build with that set to zero to see what size difference that made.  It doesn't compile, and not by a small amount for Plane (quadplane...).  Rover also has tie-ins to the EKF which make compiling it out difficult (ekf_checks).

The exercise did show that removing `AP_AHRS_NAVEKF_AVAILABLE` isn't a terrible thing.

It also showed that `get_filter_status` should probably be pure-virtual on the new `AP_AHRS_Backend` class and implemented by DCM.

2021-07-21 07:42 UTC, tridge requested changes

2021-07-21 07:42 UTC, tridge commented on ArduCopter/AP_Arming.cpp
> +    const AP_AHRS &ahrs = AP::ahrs();
i'd prefer "const auto &ahrs = AP::ahrs();"

2021-07-21 08:17 UTC, peterbarker commented on ArduCopter/AP_Arming.cpp
> +    const AP_AHRS &ahrs = AP::ahrs();
Done.

2021-07-21 08:17 UTC, peterbarker commented
It was agreed on the call this could be merged once the `auto` keyword was used and it passed CI.

2021-07-21 11:01 UTC, merged