AP_BoardConfig: Enable to specify the upper board voltage
ArduPilot/ardupilot pull request #18079
Opened 2021-07-21 04:53 UTC by muramura

Depending on the FC, there is also an upper limit to the guaranteed operating voltage.
The ArduPilot is fixed at 5.8V.
I would like to set the upper limit depending on the FC.
For example, CUAV V5+ is 5.4V.

https://ardupilot.org/copter/docs/common-cuav-v5plus-overview.html

AFTER:
![Screenshot from 2021-07-21 13-34-43](https://user-images.githubusercontent.com/646194/126432935-f4a4a527-f701-4493-92e7-139c981c55d8.png)

2021-07-21 07:00 UTC, khancyr reviewed
I don't think that is necessary, if we pass the max we burn the board, so no report possible.

2021-07-21 07:58 UTC, muramura commented
@khancyr san
I can tell in the flight log the voltage at which an electronic device is destroyed.
I think it is important to warn people about this, because sometimes it is not broken.
If the voltage is too high, it is putting a strain on the electronic device.

2021-07-28 08:37 UTC, tridge requested changes
we discussed on the call, and decided it would be better to just use:
```
#ifndef AP_ARMING_BOARD_VOLTAGE_MAX
#define AP_ARMING_BOARD_VOLTAGE_MAX     5.8f
#endif
```
in AP_Arming.cpp, and add the define to hwdef.dat for the boards that need this

2024-09-27 11:44 UTC, peterbarker commented
Ping @muramura suggestions on changes that would be accepted have been made.

Are you intending to pursue this?

2025-06-05 00:58 UTC, peterbarker commented
Closing this one now.

If you want to pursue this, please re-open with the suggested changes made.

2025-06-05 00:58 UTC, closed without merging