AP_OSD: correct horizon display for TRIM_PITCH_CD in Plane
ArduPilot/ardupilot pull request #18108
Opened 2021-07-25 14:16 UTC by Hwurzburg

Avoid protocol confusion with normal CRSF RC/Telem

2021-07-25 23:23 UTC, tridge requested changes

2021-07-25 23:23 UTC, tridge commented on libraries/AP_OSD/AP_OSD_Screen.cpp
> +#if APM_BUILD_TYPE(APM_BUILD_ArduPlane)
as discussed, this should be an AP_Vehicle method, get_display_pitch_rad()

2021-07-25 23:25 UTC, IamPete1 commented on libraries/AP_OSD/AP_OSD_Screen.cpp
> +        param->get("TRIM_PITCH_CD",value);
Its probably better to get it once at boot, look up by string is expensive. You can grab a pointer to the param so it will still update in real time.

2021-07-26 18:22 UTC, Hwurzburg commented
closing in favor of #18131 rework

2021-07-26 18:22 UTC, closed without merging