[AP_OSD] Add option to disable Crosshair on OSD horizon element
ArduPilot/ardupilot pull request #18144
Opened 2021-07-28 09:03 UTC by giacomo892

2021-08-10 08:34 UTC, giacomo892 commented
Forced to rebase due to #18247 which came 10 days after my PR.

2021-08-10 11:13 UTC, khancyr approved these changes
LGTM.
doesn't impact much the rest and the crosshair is always at the same pos. So the change is simple

2021-08-10 11:14 UTC, khancyr requested changes
@giacomo892 there is just a small change to ajust the commit message, it should be :

AP_OSD: Add option to disable Crosshair on horizon element

2021-08-11 08:42 UTC, tridge approved these changes

2021-08-11 08:42 UTC, merged