Initialize backends after all mounts were added
ArduPilot/ardupilot pull request #18147
Opened 2021-07-28 12:06 UTC by olliw42

setups with two mounts are not in the limelight, but ArduPilot supports that - in principle.

This change initializes the mounts only after they all were created, which is needed so they realize what the state of affairs is.

2021-07-28 14:27 UTC, khancyr requested changes
Mostly good
We don't use one line if so we need to enclose with {}

We are quite pedantic on commit message, it should start with the library name, so : 
AP_Mount: initialize backends after all mounts were added
You can use the script Tools/gittools/git-subsystem-split to append it for you !

2021-07-28 14:27 UTC, khancyr commented on libraries/AP_Mount/AP_Mount.cpp
> +        if (_backends[instance] != nullptr) _backends[instance]->init();
```suggestion
        if (_backends[instance] != nullptr) {
            _backends[instance]->init();
        }
```

2021-07-28 14:52 UTC, olliw42 commented on libraries/AP_Mount/AP_Mount.cpp
> +        if (_backends[instance] != nullptr) _backends[instance]->init();
fair enough. done.

2021-07-29 01:16 UTC, peterbarker commented
@olliw42 seems a reasonable patch.

What problems were occurring that this fixes?

2021-07-29 05:24 UTC, olliw42 commented
none of the current backends would work as they are right now, so in this sense it doesn't solve anything

when you want to modify a backend so it can handle a dual mounts, or add one, you likely need this, e.g. if you want some level of self configuration. The practical example would be two mavlink speaking gimbals, which are identified by id, and do not in addition need to be identified by serial port.

btw, I do have this code snippet in use for nearly a year now, so it's not coming out of a sudden gut feeling... I just thought, hey, why not
it is such a simple change that I couldn't think about a reason why one would object it, so I PRed it
if you don't like it, no problem, I certainly can live with it ;)

2021-08-24 15:09 UTC, olliw42 commented
superseded by https://github.com/ArduPilot/ardupilot/pull/18440
hence closing

2021-08-24 15:09 UTC, closed without merging