AP_GPS: Support SBF GPS Yaw message
ArduPilot/ardupilot pull request #18172
Opened 2021-07-31 04:44 UTC by Vkd4U2NtVkZOVg

2021-07-31 15:28 UTC, Vkd4U2NtVkZOVg commented
@tridge Could you please review this?

2021-08-02 00:13 UTC, tatsuy commented
We already have a PR (#12429) that includes the same functionality.

2021-08-05 10:58 UTC, Abner0907 commented on libraries/AP_GPS/AP_GPS_SBF.cpp
> +    }
why not ?
```
if (temp.Mode && (temp.Heading > -200000)) {
            state.have_gps_yaw = true;
            state.gps_yaw_configured = true;
            state.gps_yaw = (float)(temp.Heading);
            state.have_gps_yaw_accuracy = true;
            break;
      } else {
          state.have_gps_yaw = false;
          state.gps_yaw_configured = false;
          state.have_gps_yaw_accuracy = false;
          break;
      }
```

2021-08-12 22:20 UTC, WickedShell requested changes
@Vkd4U2NtVkZOVg How are you handling the configuration string? AttEuler should be removed from the messages being sent at the moment if auto configuration is enabled (which it should be). I think we will need a flag to the GPS constructor to indicate we want to use GPS attitude and add AttEuler to the config string. That should be a pretty small addition, but I'm not sure how this was tested without that.

2021-08-12 22:20 UTC, WickedShell commented on libraries/AP_GPS/AP_GPS_SBF.h
> +        AttEuler       = 5938
```suggestion
        AttEuler       = 5938,
```

Adding the comma just keeps future diffs shorter.

2021-08-12 22:21 UTC, WickedShell commented
> We already have a PR (#12429) that includes the same functionality.

That PR is a bit stalled. The most up to date is actually my branch that's in a comment, but the SBF driver underwent a signficant rewrite since then to the point that adding from scratch may be the easier path at the moment.

2021-08-14 02:18 UTC, Vkd4U2NtVkZOVg commented
@WickedShell I just disable the autoconfig for now, the only reason to add AttEuler is we want to use the gps yaw, so can we use have_gps_yaw flag and just add the AttEuler to config string?

2021-08-16 21:13 UTC, WickedShell commented
Yes, you will want the covariance to get the yaw accuracy, as it makes a difference within the data processing.


>I just disable the autoconfig for now, the only reason to add AttEuler is we want to use the gps yaw, so can we use have_gps_yaw flag and just add the AttEuler to config string?

I'm pretty sure we can't always add the AttEuler, because I don't think it's always enabled or known. You will need a new GPS type (SBF_With_Yaw) and then use that to flag that the AttEuler should be added to the config string.

2021-08-17 03:22 UTC, Vkd4U2NtVkZOVg commented
@WickedShell Thanks, I think It's the good way. And also I try to add the novatel's dual antenna GPS support GPS yaw, I could use the same way to do that!

2021-09-04 06:53 UTC, closed without merging