Move ahrs home and origin to frontend
ArduPilot/ardupilot pull request #18173
Opened 2021-07-31 04:52 UTC by peterbarker

Home is the same for all backends.

origin *should* be - but it is likely to be a call onto the backends for quite some time yet.

Built on top of #18171 which fixes home restore behaviour

2021-08-04 08:39 UTC, tridge requested changes

2021-08-04 08:39 UTC, tridge commented on libraries/AP_Common/tests/test_location.cpp
> +    // bool set_origin(const Location &loc) override WARN_IF_UNUSED {
use #if 0

2021-08-04 08:39 UTC, tridge commented on libraries/AP_Common/tests/test_location.cpp
> +    // bool set_origin(const Location &loc) override WARN_IF_UNUSED {
or remove it

2021-08-04 08:39 UTC, tridge commented on libraries/AP_Common/tests/test_location.cpp
> +    // for (auto current_frame = Location::AltFrame::ABSOLUTE;
remove

2021-08-05 00:37 UTC, peterbarker commented on libraries/AP_Common/tests/test_location.cpp
> +    // bool set_origin(const Location &loc) override WARN_IF_UNUSED {
Removed.

2021-08-05 00:37 UTC, merged