Update 2D PID filter param names
ArduPilot/ardupilot pull request #18203
Opened 2021-08-03 04:10 UTC by lthall

This change makes these filter parameter names consistent with our other controller naming conventions.

2021-08-03 04:53 UTC, rmackay9 commented
I think this has been missed:

AC_PosControl.cpp line 242, "// @Param: _VELXY_FILT" should probably be "_VELXY_FLTE"

2021-08-09 07:49 UTC, rmackay9 commented on Tools/Frame_params/Sub/bluerov2-4_0_0.params
> -PSC_VELXY_D_FILT,5.0
We shouldn't change the bluerov-4.0 parameter names because these are for use with 4.0 that will use the old param names.

2021-08-09 07:50 UTC, rmackay9 commented on Tools/Frame_params/TradHeli_Copter36_Setup-MP.param
> -PSC_VELXY_D_FILT, 5
This param file (Tools/Frame_params/TradHeli_Copter36_Setup-MP.param) also has 3.6 in the name so I don't think it should be changed either.

2021-08-09 10:19 UTC, rmackay9 requested changes
Let's remove the changes to default param files that have a version number in their filename.

I've tested that the parameter conversion from 4.0 to 4.1 still works.
![randy-lthall-velxy-filt-rename](https://user-images.githubusercontent.com/1498098/128692047-fa03091f-c5bb-4309-9f82-b75a9f0cfd1d.png)

2021-08-09 23:31 UTC, tridge approved these changes

2021-08-09 23:33 UTC, merged

2021-08-09 23:34 UTC, rmackay9 commented
Merged, thanks!

2021-08-10 12:52 UTC, Hwurzburg commented
guess I got lucky....none of these are documented...no build errors...   ;-)

2021-08-10 14:14 UTC, lthall commented
> guess I got lucky....none of these are documented...no build errors... ;-)

What do you mean Henry?

2021-08-10 14:39 UTC, Hwurzburg commented
Changing a parameter name that is documented causes a wicked build error. I have all parameters that are mentioned in the wiki linked.

2021-08-11 04:29 UTC, lthall commented
> Changing a parameter name that is documented causes a wicked build error. I have all parameters that are mentioned in the wiki linked.

Is there anything I should be doing to make it easier for you to document these parameters?

2021-08-11 18:34 UTC, Hwurzburg commented
unfortunately , no....if you can give a heads up so that I find them before I catch them in the quasi-daily build I do to check for build errors, that would help, but nothing can be done otherwise....I have to manually change the params in the wiki and/or highlite them and unlink....thanks though