ArduPlane: correct Mission Reset override behaviour in Plane
ArduPilot/ardupilot pull request #18228
Opened 2021-08-05 14:27 UTC by Hwurzburg

fixes a few issues with current override (thanks to @tridge for helping find this):
1. any switch position change triggers it, instead of >1800us
2. it always sets MISSION_RUNNING since it uses mission->start() instead of reset() which prevents a mission->clear() from occurring in any mode until the mission is completed. Should be able to clear a mission in any not AUTO mode.

new(actually old) behavior:
will reset the mission pointer to the first WP any time aux switch  transitions to high, either while armed in any non-auto mode or while armed in auto, causing the mission to restart at its beginning....disarming resets the mission also

SITL tested

2021-08-05 14:27 UTC, Hwurzburg commented
actually since this is now the same as the library function, shouldn't I just remove it?

2021-08-05 14:31 UTC, IamPete1 commented
Yeah, since this is now the same as the standard `RC_Channel.cpp` function you can just remove the plane copy. You can also remove the virtual from main function since there is no longer any overrides.

2021-08-05 14:33 UTC, khancyr requested changes
Yes, that is the same as the base function. So it is better to use the base function and to remove the override completely if nobody else is using it

2021-08-05 16:02 UTC, Hwurzburg commented
so just reverted to common mission reset....SITL tested

2021-08-06 00:17 UTC, tridge approved these changes

2021-08-06 00:17 UTC, merged