GCS_MAVLink: fix always 0 division.
ArduPilot/ardupilot pull request #18319
Opened 2021-08-13 07:28 UTC by khancyr

7/8 into array range bracket will be integral type, therefore 7/8 is reported as always 0.

2021-08-13 07:33 UTC, khancyr commented
it maybe worth removing the division for a +1

2021-08-14 00:05 UTC, peterbarker requested changes

2021-08-14 00:05 UTC, peterbarker commented on libraries/GCS_MAVLink/MissionItemProtocol_Fence.cpp
> +    _updated_mask = new uint8_t[(_item_count + static_cast<uint8_t>(7.0/8.0))];
```suggestion
    _updated_mask = new uint8_t[(_item_count + 7)/8.0)];
```

This is attempting to round up.

2021-08-25 00:57 UTC, peterbarker commented
I've made the change I recommended and force-pushed up

2021-08-25 06:49 UTC, peterbarker commented
Need to run this through Valgrind

2022-10-21 03:12 UTC, peterbarker commented
I've run this through Valgrind on Rover and it doesn't find any issues.

2022-10-21 23:41 UTC, WickedShell approved these changes

2022-10-22 00:11 UTC, merged

2022-10-22 00:12 UTC, peterbarker commented
Merged, thanks @khancyr !

2022-11-17 02:47 UTC, rmackay9 commented
This is included in Copter-4.3.1-rc1