AP_Vehicle: add AIS
ArduPilot/ardupilot pull request #18332
Opened 2021-08-14 21:34 UTC by IamPete1

Follow up to https://github.com/ArduPilot/ardupilot/pull/13839 moving into AP_Vehicle, still only enabled for rover by default but can now be enabled on other vehicles with the define.

2021-08-15 01:27 UTC, IamPete1 commented
I'm not sure what has gone wrong with semaphore, its passing that check locally.

2021-08-16 03:34 UTC, rmackay9 commented
@IamPete1,

Semaphore looks like it's complaining about this, "libraries/AP_Vehicle/AP_Vehicle.h: library header uses vehicle-dependent macros".  I think this is a real limitation we've added so either we need to remove that check or fix it

2021-08-22 12:19 UTC, IamPete1 commented
rebased to see if it will get past semaphore.

2022-01-04 23:56 UTC, IamPete1 commented on libraries/AP_Vehicle/AP_Vehicle.cpp
> +#endif
@peterbarker @hendjoshsr71 I have reworked this to the dummy methods approach as in airspeed, any thoughts about how to get round the param table? Everything else works, not sure the flash cost yet......

2022-01-04 23:57 UTC, IamPete1 commented on libraries/AP_Vehicle/AP_Vehicle.cpp
> +#endif
We could change to a pointer table of course and load at init, but that seems overly complex.

2022-07-03 11:41 UTC, IamPete1 commented
The dummy methods cost us a bit on 2M boards,
```
Binary Name      Text [B]        Data [B]     BSS (B)        Total Flash Change [B] (%)      Flash Free After PR (B)
---------------  --------------  -----------  -------------  ----------------------------  -------------------------
arduplane        172 (+0.0098%)  0 (0.0000%)  4 (+0.0015%)   172 (+0.0098%)                                   206080
ardurover        -8 (-0.0005%)   0 (0.0000%)  0 (0.0000%)    -8 (-0.0005%)                                    363032
arducopter-heli  356 (+0.0200%)  0 (0.0000%)  -4 (-0.0015%)  356 (+0.0199%)                                   180144
arducopter       388 (+0.0219%)  0 (0.0000%)  4 (+0.0015%)   388 (+0.0218%)                                   187976
antennatracker   300 (+0.0221%)  0 (0.0000%)  4 (+0.0015%)   300 (+0.0220%)                                   604096
blimp            244 (+0.0188%)  0 (0.0000%)  4 (+0.0015%)   244 (+0.0187%)                                   663332
ardusub          204 (+0.0131%)  0 (0.0000%)  4 (+0.0015%)   204 (+0.0130%)                                   401900
```

No flash cost on 1M boards.

```
Binary Name      Text [B]          Data [B]     BSS (B)       Total Flash Change [B] (%)      Flash Free After PR (B)
---------------  ----------------  -----------  ------------  ----------------------------  -------------------------
arduplane        0 (0.0000%)       0 (0.0000%)  0 (0.0000%)   0 (0.0000%)                                        9400
ardurover        -4444 (-0.5189%)  0 (0.0000%)  4 (+0.0031%)  -4444 (-0.5184%)                                 130264
arducopter-heli  0 (0.0000%)       0 (0.0000%)  0 (0.0000%)   0 (0.0000%)                                       288
arducopter       0 (0.0000%)       0 (0.0000%)  0 (0.0000%)   0 (0.0000%)                                       47528
antennatracker   0 (0.0000%)       0 (0.0000%)  0 (0.0000%)   0 (0.0000%)                                      319584
blimp            0 (0.0000%)       0 (0.0000%)  0 (0.0000%)   0 (0.0000%)                                      301620
ardusub          0 (0.0000%)       0 (0.0000%)  0 (0.0000%)   0 (0.0000%)                                      169268
```
This does remove on Rover 1M boards, but I think that's OK. Currently this does not do any param conversion for rover, we could add it, AIS has now been out in a stable, @rmackay9 what do you think?

2022-07-03 11:51 UTC, auturgy commented
I think we should really have this in ArduSub by default, and selfishly I'd like it in copter and plane too, although probably as a compile option.
@peterbarker

2022-07-04 23:22 UTC, tridge requested changes
this will need wiki work to get the AIS docs in copter and plane, with a note on how to enable it with custom build server

2022-07-04 23:22 UTC, tridge commented on Tools/scripts/build_options.py
> +    Feature('Ident', 'AIS', 'AP_AIS_ENABLED', 'Enable AIS', 0, None),
maybe make AP_AIS_ENABLED=1 enable the full feature, and =2 enable the dummy only, and then in the header file default to dummy

2022-07-04 23:23 UTC, tridge commented
@Hwurzburg note the doc changes needed to make AIS docs in copter and plane with note on how to enable in custom build server

2022-07-04 23:24 UTC, tridge commented on libraries/AP_AIS/AP_AIS.cpp
> +
add comment explaining this dummy code (why its needed)

2022-07-11 23:39 UTC, peterbarker approved these changes

2022-07-11 23:39 UTC, tridge approved these changes

2022-07-11 23:39 UTC, merged