Copter: always check GPS in super simple modes
ArduPilot/ardupilot pull request #18334
Opened 2021-08-15 01:14 UTC by IamPete1

Fixes #1338

Currently it is possible to get into stab supper simple with no GPS, in which case the yaw rotation based on GPS position doesn't work. This fixes that. 

Of course we will still not trip a EKF fail-safe, but I think that is a different discussion.

2021-08-16 03:46 UTC, rmackay9 approved these changes
This looks good to me.  You've tested it in SITL of course?

2021-08-16 08:49 UTC, khancyr approved these changes
yep, that is right.

Would it be possible to add it on test_arm_feature() after the interlock test ?

2021-08-16 10:27 UTC, IamPete1 commented
Yep, tested in SITL

2021-08-18 08:11 UTC, peterbarker requested changes

2021-08-18 08:11 UTC, peterbarker commented on ArduCopter/AP_Arming.cpp
> +    bool mode_requires_gps = copter.flightmode->requires_GPS() || fence_requires_gps || (copter.simple_mode == Copter::SimpleMode::SUPERSIMPLE);
Really bad variable name.

```suggestion
    const bool gps_required = copter.flightmode->requires_GPS() || fence_requires_gps || (copter.simple_mode == Copter::SimpleMode::SUPERSIMPLE);
```

2021-08-18 08:13 UTC, merged

2021-08-18 08:14 UTC, rmackay9 commented
Merged, thansk!