MS525 driver fix conversion when temperature <20C or pressure negative
ArduPilot/ardupilot pull request #18363
Opened 2021-08-17 09:41 UTC by hendjoshsr71

This fixes the MS525 airspeed driver and sitl driver for the case when the sensor temperature <20deg C or the pressure is negative. This is likely not a problem for users currently since the sensor temperature from logs I pulled from users tends to be around 40deg C.

This causes an insanely high airspeed and temperature to be reported on plane startup and ends in arithmetic errors in multiple places. 

There are lots of silent promotions happening here and I switched to using floats for the driver to match the behavior of the MS5611 driver for intermediate steps.

The PR also adds unit tests for these cases for these drivers. However, I'm not sure how to get the unit test to build and test under the Linux board type that is used by the build server?

2021-08-23 23:59 UTC, tridge requested changes

2021-08-23 23:59 UTC, tridge commented on libraries/AP_Airspeed/AP_Airspeed_MS5525.cpp
> +    float OFF =  (prom[2])*(1L<<Q2) + ((prom[4])*dT)/(1L<<Q4);
looks like an intermediate value could overflow 32 bits here?

2021-09-07 01:10 UTC, tridge commented
worth testing with 32 bit SITL

2021-09-08 04:49 UTC, hendjoshsr71 commented
I tested this using SITL_32bit using this PR https://github.com/ArduPilot/ardupilot/pull/18601 These driver changes worked fine in Plane SITL and passed the attached Unit tests under 32bit and 64bit sitl.

2021-09-20 23:30 UTC, tridge approved these changes

2021-09-20 23:30 UTC, merged