Move from HAL_NO_GCS to HAL_GCS_ENABLED
ArduPilot/ardupilot pull request #18381
Opened 2021-08-18 12:52 UTC by peterbarker

... and move away from "defined" to "truth" for the value

Tested AP_Periph by ensuring checksums of HerePro and f303-periph matched before/after this patch.

2021-09-17 14:21 UTC, magicrub commented
I'm certainly in favor of this. That existing define haunts me. @bugobliterator should take a look.

2021-09-22 08:53 UTC, tridge requested changes

2021-09-22 08:53 UTC, tridge commented on libraries/AP_MSP/AP_MSP_Telem_Backend.cpp
> -#ifndef HAL_NO_GCS
backards

2021-09-22 09:01 UTC, peterbarker commented on libraries/AP_MSP/AP_MSP_Telem_Backend.cpp
> -#ifndef HAL_NO_GCS
Fixed

2021-09-22 11:37 UTC, merged