Add safe new macro to ensure we always handle allocation failures
ArduPilot/ardupilot pull request #18405
Opened 2021-08-20 09:23 UTC by bugobliterator

2021-08-20 13:42 UTC, davidbuzz commented
Isn't it generally considered ok for a new that fails and returns a nullptr to be tested as a boolean with a ternary or coalescing operator ...?
auto c = a ?: b;

2021-08-25 08:05 UTC, tridge requested changes

2021-09-01 07:07 UTC, tridge requested changes

2021-09-01 07:07 UTC, tridge commented on libraries/AP_GPS/AP_GPS_UAVCAN.cpp
> +        AP_HAL::panic("AP_GPS_UAVCAN: Unable to allocate memory for gnss_fix subscriber");
a wrapper around config_error() called allocation_error() that just takes a string for the item being allocated would save flash, and allow users to disable the failing subsystem

2021-09-15 07:34 UTC, tridge requested changes

2021-09-15 07:34 UTC, tridge commented on libraries/AP_BoardConfig/AP_BoardConfig.cpp
> +void AP_BoardConfig::allocation_error(const char *fmt, ...)
better to have a common method _config_error() that takes a const char *prefix

2021-09-22 07:33 UTC, tridge requested changes

2021-09-22 07:33 UTC, tridge commented on libraries/AP_Param/AP_Param.cpp
> +#pragma GCC diagnostic ignored "-Wformat-security"
should be "%s", buf

2021-09-22 08:11 UTC, peterbarker approved these changes

2021-09-22 08:13 UTC, tridge approved these changes

2021-09-22 11:36 UTC, merged