AP_Math: fix vectorN ctor warning by using C++11 brace initilization …
ArduPilot/ardupilot pull request #18451
Opened 2021-08-25 10:45 UTC by khancyr

…in all cases

2021-08-25 10:46 UTC, peterbarker commented
I dunnno.  I think this is a case where we should pragma it away for performance reasons....

2021-08-30 23:34 UTC, tridge requested changes

2021-08-30 23:34 UTC, tridge commented on libraries/AP_Math/vectorN.h
> +        for (auto i = 0; i < N; i++) {
in other places we've fixed this with a (void*) cast

2021-08-30 23:35 UTC, tridge commented
@khancyr what compiler was this with?

2021-09-21 09:52 UTC, khancyr commented
@tridge gcc version 10.3.0 (Ubuntu 10.3.0-1ubuntu1)
I am not that fine with the void cast as it is just hidding the warning away. From the size analysis, it moves some init from bss to text so that looks like a win even in term of performance

2021-09-21 10:51 UTC, tridge approved these changes

2021-09-21 10:51 UTC, tridge commented
looks like the compiler does deal with it decently, thanks

2021-09-21 10:51 UTC, merged