AP_Scripting: re-emit error messages every 10 seconds 10 times
ArduPilot/ardupilot pull request #18463
Opened 2021-08-26 00:34 UTC by IamPete1

Very easy to miss scripting error messages because they happen so soon after boot. This re-prints them every 10 seconds so you can catch them if you missed them first time.

2021-09-21 20:40 UTC, IamPete1 commented
even saves flash!
```
Binary           text            data         bss          total
---------------  --------------  -----------  -----------  --------------
ardusub          -40 (-0.0026%)  0 (0.0000%)  0 (0.0000%)  -40 (-0.0022%)
arduplane        -40 (-0.0023%)  0 (0.0000%)  0 (0.0000%)  -40 (-0.0020%)
blimp            -40 (-0.0032%)  0 (0.0000%)  0 (0.0000%)  -40 (-0.0026%)
arducopter-heli  -40 (-0.0023%)  0 (0.0000%)  0 (0.0000%)  -40 (-0.0020%)
antennatracker   -40 (-0.0030%)  0 (0.0000%)  0 (0.0000%)  -40 (-0.0025%)
ardurover        -40 (-0.0026%)  0 (0.0000%)  0 (0.0000%)  -40 (-0.0022%)
arducopter       -40 (-0.0023%)  0 (0.0000%)  0 (0.0000%)  -40 (-0.0020%)
```

2021-09-22 08:21 UTC, tridge commented on libraries/AP_Scripting/lua_scripts.cpp
> +                IGNORE_RETURN(asprintf(&error_msg_buf[0], "Syntax error in %s", filename));
we need a lua_asprintf() which uses the lua heap, or a heap_asprintf() which takes a heap argument 
see https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_HAL_ChibiOS/stdio.cpp#L66

2021-09-22 08:22 UTC, tridge requested changes
needs a lua_asprintf() or a heap_asprintf() to keep memory isolated

2021-09-23 01:22 UTC, IamPete1 commented on libraries/AP_Scripting/lua_scripts.cpp
> +                IGNORE_RETURN(asprintf(&error_msg_buf[0], "Syntax error in %s", filename));
Done, seems to work, but certainly needs a check over by someone.

2021-09-28 21:10 UTC, IamPete1 commented
No longer saves flash. Not too bad tho.
```
Binary           text           data         bss            total
---------------  -------------  -----------  -------------  -------------
ardusub          52 (+0.0034%)  0 (0.0000%)  -4 (-0.0015%)  48 (+0.0027%)
arduplane        52 (+0.0030%)  0 (0.0000%)  4 (+0.0015%)   56 (+0.0028%)
blimp            52 (+0.0041%)  0 (0.0000%)  4 (+0.0015%)   56 (+0.0037%)
arducopter-heli  52 (+0.0030%)  0 (0.0000%)  -4 (-0.0015%)  48 (+0.0024%)
antennatracker   52 (+0.0039%)  0 (0.0000%)  -4 (-0.0015%)  48 (+0.0030%)
ardurover        52 (+0.0033%)  0 (0.0000%)  -4 (-0.0015%)  48 (+0.0026%)
arducopter       52 (+0.0030%)  0 (0.0000%)  4 (+0.0015%)   56 (+0.0028%)
```

2021-09-28 21:11 UTC, IamPete1 commented
The `lua_asprintf` needs checking over.

2021-09-29 07:09 UTC, tridge approved these changes

2021-09-29 07:11 UTC, peterbarker approved these changes

2021-09-29 07:11 UTC, merged