Plane: move mount and gear to end of init
ArduPilot/ardupilot pull request #18480
Opened 2021-08-28 00:50 UTC by IamPete1

Fixes #16264

I have no idea why, but this fixes the initial servo outputs. Unlike most servo outs the landing gear and mount are one time sets at init until something happens. Something in the quadplane setup code wipes this initial value to 0. Moving the init after avoideds the wipe. This is not noticed in most outputs as they are continually set.

2021-08-29 04:17 UTC, magicrub commented
I think I've seen this problem in the past too and couldn't figure it out and moved on. Since this appears to be placed at this location arbitrarily... Moving out to another arbitrary location should be fine. Sadly, we now know it's not arbitrary but don't know why. If that's true, how do we know this doesn't break anything else? I'm in favor of it merging if we can figure out it doesn't break anything else.

2021-08-30 23:56 UTC, tridge requested changes
this moves it after gyro cal, which is a very long delay.
I think we need to understand the real cause

2021-08-31 12:40 UTC, IamPete1 commented
Found a more correct fix, the function mask was getting cleared/lost/never-set. Sill not sure the exact cause of this on quadplane but not plane, but this fixes.

2021-09-01 08:34 UTC, tridge approved these changes

2021-09-01 08:34 UTC, merged