Generate board list
ArduPilot/ardupilot pull request #18502
Opened 2021-08-30 03:37 UTC by peterbarker

When adding a board we currently have to add it to several places.  This *might* reduce it to just adding the hwdef.

This walks the hwdef directory in the same way that the uploader.py script does to find hwdef files.

The output for this script is the same before/after this patch - but to do that I've had to hard-code some blacklists.  I'm quite sure there are things on that list that shouldn't be there.  If there really are boards that shouldn't be built by the autotest server that should be marked in the hwdef file.

Sometime in the future `chibios_hwdef.py` should be rewritten to factor out its parsing.

2021-08-31 00:05 UTC, peterbarker commented
Need to check the custom build server

2021-08-31 00:06 UTC, tridge commented
need to also test autotest server

2021-08-31 00:08 UTC, peterbarker commented
Put an example of using the brand etc in

2021-08-31 06:02 UTC, peterbarker commented
I've now tested this with `build_binaries.py` and it works.

2021-08-31 06:26 UTC, peterbarker commented
Added information to Pixracer Pro's configuration file and it appears in the apj:

```
pbarker@bluebottle:~/rc/ardupilot(pr/board_list-generate)$ tail build/mRoPixracerPro/bin/arducopter.apj
    "version": "0.1",
    "image_size": 1700108,
    "flash_total": 1966080,
    "flash_free": 265972,
    "git_identity": "05da9677",
    "board_revision": 0,
    "USBID": "0x1209/0x5740",
    "manufacturer": "mRo",
    "brand_name": "Pixracer Pro"
}pbarker@bluebottle:~/rc/ardupilot(pr/board_list-generate)$ 
```

2021-08-31 06:36 UTC, peterbarker commented
I've verified that this value makes its way into the manifest

2021-09-20 23:38 UTC, tridge commented
pending test with custom build server

2021-12-27 00:45 UTC, peterbarker commented
This works OK for the custom build server.  On a Vagrant VM it is very slow, however.

2022-01-03 23:27 UTC, tridge requested changes

2022-01-03 23:27 UTC, tridge commented on Tools/scripts/board_list.py
> +            "mRo-M10095",
mRo-M10095 should be built

2022-01-03 23:27 UTC, tridge commented on Tools/scripts/board_list.py
> +            "HerePro",
HerePro should be built

2022-01-04 03:39 UTC, peterbarker commented on Tools/scripts/board_list.py
> +            "mRo-M10095",
I've re-added this one.

2022-01-04 03:39 UTC, peterbarker commented on Tools/scripts/board_list.py
> +            "HerePro",
I'll do this as a separate PR.

2022-01-04 03:39 UTC, peterbarker commented
I've verified that the output from the script is identical in master and in this branch.

Weird things will now tend to stick out like sore thumbs - like the HerePro thing.

2022-01-04 03:41 UTC, peterbarker commented
@bugobliterator @proficnc do either of you know why we don't build HerePro on our build server?

This PR preserves that behaviour, but unless there's a good reason I was going to create a PR to start building it.

@magicrub mentioned the possibility there might be custom scripts running in your images meaning we should make them on the build server.

2022-01-07 11:46 UTC, merged