AP_Logger: log transfer: add error message if armed
ArduPilot/ardupilot pull request #18512
Opened 2021-08-30 13:49 UTC by IamPete1

Fixes #8914

This is used on all vehicles, although the issue is just for rover.

Currently log related mavlink stuff will silently fail if armed. Will also fail if `!WritesEnabled()` but in that case AP will be printing "Initialising ArduPilot" every 5 seconds, so I don't think we need another message.

2021-08-30 13:55 UTC, IamPete1 commented
Note that if you arm during a log download the GCS might keep trying (MAVProxy does), in which case this message is printed a lot.  Maybe we should be refusing to arm in log download.

2021-08-30 14:07 UTC, IamPete1 commented
Added a arming check for log downloading.

2021-09-06 23:39 UTC, tridge requested changes

2021-09-06 23:39 UTC, tridge commented on libraries/AP_Arming/AP_Arming.cpp
> +            check_failed(ARMING_CHECK_LOGGING, report, "Downloading logs");
better to only output msg once per arming

2021-09-07 00:52 UTC, IamPete1 commented
Now will only send one message warning to disarm for logging.

2021-09-08 07:38 UTC, tridge approved these changes

2021-09-08 07:38 UTC, merged