Fail to arm if in RC_Calibration
ArduPilot/ardupilot pull request #18514
Opened 2021-08-30 16:01 UTC by IamPete1

Fixes #8735

Although as far as I can tell QGC no longer sets that bit. I think it would be a nice enhancement to all the GCSs tho.

I'm not sure on the exact way to use the pram. 

https://mavlink.io/en/messages/common.html#MAV_CMD_PREFLIGHT_CALIBRATION

Says: 
     1: radio RC calibration, 2: RC trim calibration

Currently I have 1 = running 0 = stop. But that means we cant ack the stop. Maybe it should be a continues set and timeout. Or a toggle. 

Since QGC seems not to send it anymore we have no base line to compare to....

2021-09-03 16:57 UTC, IamPete1 commented
Looks like QGC should be sending it, https://github.com/mavlink/qgroundcontrol/blob/27533e57a862288a22f6880f5591aa3c1c057cb2/src/Vehicle/Vehicle.cc#L3221

2021-09-03 18:13 UTC, IamPete1 commented
Plane and rover are already using this param, but both are using a value of 1 for copy trim where as the spec says that should be 2

https://github.com/ArduPilot/ardupilot/blob/8462ce4e2e32edcd6beaed28bdc6d892cad02059/Rover/GCS_Mavlink.cpp#L575

https://github.com/ArduPilot/ardupilot/blob/8462ce4e2e32edcd6beaed28bdc6d892cad02059/ArduPlane/GCS_Mavlink.cpp#L626

2021-09-06 23:40 UTC, rmackay9 commented on libraries/RC_Channel/RC_Channel.h
> +    bool is_calibrating;
can we clarify this boolean's name?  maybe gcs_in_RC_calibration or something like that.

2021-09-06 23:43 UTC, tridge requested changes

2021-09-06 23:43 UTC, tridge commented on ArduCopter/AP_Arming.cpp
> +    return result & AP_Arming::mandatory_checks(display_failure);
&& for boolean and

2021-09-06 23:43 UTC, tridge commented on Blimp/AP_Arming.cpp
> +    return result & AP_Arming::mandatory_checks(display_failure);
&& for boolean

2021-09-06 23:53 UTC, tridge requested changes

2021-09-06 23:53 UTC, tridge commented on ArduPlane/GCS_Mavlink.cpp
> +    if (is_equal(packet.param4,2.0f)) {
better to remove trim_radio()

2021-11-01 23:04 UTC, tridge approved these changes

2021-11-01 23:05 UTC, merged