Linux: OBAL Board
ArduPilot/ardupilot pull request #18537
Opened 2021-09-01 03:27 UTC by HefnySco

"Open Board Architecture for Linux"  OBAL is a raspberry pi Linux-based Ardupilot FCB.
The vision is to provide that:

- Is a simple board that is easy to solder and assembled at home.
- Can be customized and upgraded easily.
- Acts as a developing and/or test platform to enable developers, engineer & hobbyist who are interested in understanding Ardupilot hardware/software.
- Complete Open-Source Hardware/Software and works on native Ardupilot code with no extra drivers.

Draft [Manual](https://docs.google.com/document/d/1LQQPN2N1uzzyUMNiwTzN192PXrR_le1TTzY7jH85Pw8/edit#heading=h.4xqnc03ds2zd)

[video 1](https://youtu.be/Exp-KAa3uoQ)
[video 2](https://youtu.be/EINo2wLM9Qw)

OBAL name is inspired by OPAL where there are many colors and shapes. OBAL can be customized in many ways.

2021-09-07 04:41 UTC, tridge requested changes
we need to cleanup commits per the code style requirements:
 - squash fixup commits
 - split across subsystems

also needs to pass CI tests

2021-09-07 05:24 UTC, HefnySco commented
@tridge please note that  [AP_HAL_Linux: missing define when compile for RZero](https://github.com/ArduPilot/ardupilot/pull/18537/commits/d45ba6364c657a3c7d1668aa90a7bbed6a17c01d)  is needed here to compile to RPI-Zero.
Although I already put it in another [PR-18503](https://github.com/ArduPilot/ardupilot/pull/18503) as it is a compiler related issue not only with this board. I faced the issue whenever I make cross compile for Ardupilot to run on  RZero boards.

2021-09-09 22:17 UTC, tridge approved these changes

2021-09-09 22:17 UTC, merged

2021-10-09 05:45 UTC, rmackay9 commented
I've added this to the 4.1 projects at @HefnySco's request.