AP_HAL_ChibiOS: update default params for SWAN-K1
ArduPilot/ardupilot pull request #18551
Opened 2021-09-02 18:49 UTC by Hwurzburg

Some modifications:
- change to new copter surfaceless tailsitter enable param
- adjust rudder extremes to allow stick arm/disarm in T10 transmitter...it limits rudder a bit at lowest throttle
- create throttle trim to accommodate #18516 when merged...no change to behavior if not merged
- put full tune params for reset to default to get back to base tune
- backtransition rate lower to stop time out
- add RC option for QRTL to be normal button in T10 transmitters...may need discussion
- add TRIM_THROTTLE target for #18516

2021-09-03 21:17 UTC, tridge requested changes

2021-09-03 21:17 UTC, tridge commented on libraries/AP_HAL_ChibiOS/hwdef/Swan-K1/defaults.parm
> +RC8 4
typo, RC8_OPTION

2021-09-03 21:36 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/Swan-K1/defaults.parm
> +RC8 4
fixed per our discussion

2021-09-05 14:23 UTC, IamPete1 commented
All seems fine, since it has been flowing IRL. I'm slightly hesitant about having RC trim/min/max in the defaults I'm not sure how similar they would end up over different vehicles, possibly there are different transmitter options.

2021-09-05 20:18 UTC, Hwurzburg commented
> All seems fine, since it has been flowing IRL. I'm slightly hesitant about having RC trim/min/max in the defaults I'm not sure how similar they would end up over different vehicles, possibly there are different transmitter options.

this is a vehicle hwdef...it comes with transmitters....their trims and ranges are known....you would only use this with the Swan K1 RTF setups

2021-09-05 21:16 UTC, Hwurzburg commented
per our conv...going back to original Single/Dual

2021-09-05 22:07 UTC, tridge approved these changes

2021-09-05 22:07 UTC, merged