Honour WPNAV_SPEED changes during flight
ArduPilot/ardupilot pull request #18568
Opened 2021-09-04 02:07 UTC by peterbarker

I thought we already did this years ago.

Closes https://github.com/ArduPilot/ardupilot/issues/6193

I'm not sure we should actually do this, but perhaps add information to the parameter description indicating we only "sample" `WPNAV_SPEED` at the beginning of the mission or similar.

2021-09-04 03:03 UTC, rmackay9 commented
It's very valid to ask if we should actually do this.  If we want to this implementation seems good to me.

2021-09-04 05:11 UTC, lthall commented
If we are going to do this for horizontal speed shouldn't we do it with SPEED_UP and SPEED_DN too?

2021-09-04 06:04 UTC, peterbarker commented
On Fri, 3 Sep 2021, Leonard Hall wrote:

> If we are going to do this for horizontal speed shouldn't we do it with SPEED_UP and SPEED_DN too?

Once a user notices?  :-)

I was also wondering about WPNAV_ACCEL.

2021-09-04 08:25 UTC, lthall commented
>> I was also wondering about WPNAV_ACCEL.

No, we can only change the speed during a leg. Accel can't be changed until the next segment without effectively reinitialising WPNav at the moment.

>> Once a user notices?  :-)
I think we need to keep this consistent with all the speeds. They are all done exactly the same way so it is a copy past job.

2021-09-04 23:20 UTC, lthall requested changes
To be consistent we should add Speed Up and Speed Down.

2021-09-06 02:09 UTC, peterbarker commented
Tagged DevCallTopic to answer the question of "Do we want to do this?" before I invest more time into doing down/up for consistency.

2021-09-06 02:27 UTC, rmackay9 commented
I think it would be nice for users to have this actually.. Maybe it's not the "right" way to do it in some ways but it is easy so I think users will appreciate it.

2021-09-06 03:05 UTC, lthall commented
I agree, it is a good feature.

2021-09-07 01:04 UTC, merged

2021-09-10 01:11 UTC, rmackay9 commented
This needed to be included in Copter-4.1.0-rc1 to avoid merge conflicts

2022-09-14 13:53 UTC, sulakshanarya commented
@rmackay9 Is there a way the GCS can request the set speed from the flight controller after the DO_CHANGE_SPEED changes the vehicle's speed during the flight?