Plane: Quadpalne: move tiltrotor functionality to own class
ArduPilot/ardupilot pull request #18579
Opened 2021-09-04 23:00 UTC by IamPete1

Makes quadplane slightly cleaner and lets us hide tilt params. Removes remaining confusion between tailsitters and tiltrotors.

2021-09-05 20:00 UTC, IamPete1 commented
All seems to work as expected with the Griffin in RF

2021-09-08 15:11 UTC, IamPete1 commented
rebased on mode changes and re-tested param conversion.

2021-09-13 23:49 UTC, tridge requested changes
queue this after peters quadplane enable PR

2021-09-13 23:49 UTC, tridge commented on ArduPlane/tiltrotor.cpp
> +    if (!enable.configured() && ((tilt_mask > 0) || (type == TILT_TYPE_BICOPTER))) {
!= 0 for mask

2021-09-16 02:26 UTC, tridge submitted a review, later dismissed
@IamPete1 testing fails badly on Griffin model in RF9. The motors end up tilting down:
![image](https://user-images.githubusercontent.com/831867/133539175-cec360c4-c32e-45e5-b0d5-2161f65699fe.png)
it tries to take off like that and does a nose down
parameters attached
[griffin.txt](https://github.com/ArduPilot/ardupilot/files/7174480/griffin.txt)

2021-09-16 15:47 UTC, IamPete1 commented
I had "fixed" all of those `tilt_mask > 0`  checks to `tilt_mask != 0` including the `tilt_mask < 0` that should have been `tilt_mask == 0` for early return. 

I have done it properly now.

2021-09-16 22:17 UTC, tridge approved these changes

2021-09-16 22:24 UTC, merged