AP_GPS: add support for SBF, novatel and unicore dual antenna GPS
ArduPilot/ardupilot pull request #18615
Opened 2021-09-09 04:03 UTC by Vkd4U2NtVkZOVg

I close those two PR: #18172 #18492 , and combine to this one.

2021-10-02 07:24 UTC, Vkd4U2NtVkZOVg commented
rebase to the master.

2021-10-14 02:23 UTC, Vkd4U2NtVkZOVg commented
tested in the real flight，both GPS's yaw works fine.

2021-10-20 08:02 UTC, timsonemma commented
> Has this been tested with Septentrio Mosaic-H or just AsteRx series hardware from them?

Yes this has been tested with Mosaic-H

2021-10-22 04:37 UTC, timsonemma commented
> @timsonemma anything else should we do before merge this pr?

seems good to me!

2021-11-02 19:09 UTC, WickedShell requested changes
Please don't combine PR's like this. The pair of combined PR's are actually very different, and merging them like this makes it take longer to actually get in, as well as makes it harder to track the history.

Has the modified novatel driver been run against novatel hardware after the changes?

You also need to add the new options to the GPS_TYPE parameter descriptions in AP_GPS.cpp.

I may come back and try and split the SBF PR back out, later with changes, unless you beat me to it.

2021-11-02 19:09 UTC, WickedShell commented on libraries/AP_GPS/AP_GPS_SBF.cpp
> +                                    if (asprintf(&config_string, "sso,Stream%d,COM%d,PVTGeodetic+DOP+ReceiverStatus+VelCovGeodetic+BaseVectorGeod,msec100\n",
The alternate form of this that would use less flash is to pass the extra arguments as a %s at the end of the string like this: `"sso,Stream%d,COM%d,PVTGeodetic+DOP+ReceiverStatus+VelCovGeodetic+BaseVectorGeod%s,msec100\n"` then pass a string that is either empty "" or contains "AttEuler+AttCovEuler" depending on which type it is (which can be done as a separate switch before the asprintf call.  This is both quite readable, reduces flash cost, and most importantly it makes it easier to add (or remove) more required terms from all the driver cases, without having to duplicate it into every string manually.

2021-11-02 19:09 UTC, WickedShell commented on libraries/AP_GPS/AP_GPS_NOVA.cpp
> +                    state.gps_yaw_accuracy = (float)(headingu.hdgstddev);
Why do these need casts to float? The struct member is float as far as I can see.

2021-11-02 19:09 UTC, WickedShell commented on libraries/AP_GPS/AP_GPS_NOVA.cpp
> +            {
Unneeded extra line

2021-11-02 19:09 UTC, WickedShell commented on libraries/AP_GPS/AP_GPS_NOVA.cpp
> +    if(messageid == 971 || messageid == 2042)
I think you need to actually only enter this if it's unicore and 971 or, novatel and 2042.

2021-11-02 19:09 UTC, WickedShell commented on libraries/AP_GPS/AP_GPS_NOVA.cpp
> +    if (now - state.gps_yaw_time_ms > 500) {
Too long a timeout period.

2021-11-02 19:09 UTC, WickedShell commented on libraries/AP_GPS/AP_GPS_NOVA.cpp
> +            {
This should be on the same line as above.

2021-11-03 23:44 UTC, Vkd4U2NtVkZOVg commented on libraries/AP_GPS/AP_GPS_NOVA.cpp
> +                    port->write((const uint8_t *)nova_heading_init_blob, strlen(nova_heading_init_blob));
I think I can handle the split job. I'm gonna remove the novatel driver's modification and focus to the sbf driver as you suggested.

2021-11-04 17:10 UTC, WickedShell commented on libraries/AP_GPS/AP_GPS_SBF.cpp
> +            state.gps_yaw_accuracy = (float)(sqrt(temp.Cov_HeadHead));
You also need to check for the DNU value before trying this.

2021-11-04 17:11 UTC, WickedShell commented on libraries/AP_GPS/AP_GPS_SBF.cpp
> +            state.gps_yaw = (float)(temp.Heading);
Check for DNU before copying it in.

2021-11-06 07:52 UTC, closed without merging