Plane: loiter altitude control like FBWB
ArduPilot/ardupilot pull request #18624
Opened 2021-09-09 23:10 UTC by IamPete1

This makes loiter work like everyone thinks it should. 

https://discuss.ardupilot.org/t/loiter-altitude-behaviour/75856
Fixes #7388
Fixes #9792

https://inavfixedwinggroup.com/rc-news/i-betrayed-inav-with-ardupilot-and-i-almost-dont-regret-it/
"I cannot change the altitude in LOITER mode by default. When I pitch down it sinks like in FBWA mode but climbs back when I release the stick. What! That makes no sense to me."

This is a change in behavior but I have added a `FLIGHT_OPTION` so you can go back to the old way.

2021-09-21 00:00 UTC, tridge requested changes
needs to be gated behind STICK_MIXING enabled, so that if RC trim is off plane does not change altitude

2021-11-01 23:11 UTC, tridge commented
need to check works with terrain following

2022-02-02 00:18 UTC, kniuk commented
@IamPete1 @tridge guys I believe this one is worth getting back to.

2022-04-28 22:58 UTC, Hwurzburg commented
@IamPete1 verified that terrain following LOITER does not work on this one...

2022-05-22 09:18 UTC, IamPete1 commented
Closed by https://github.com/ArduPilot/ardupilot/pull/20695

2022-05-22 09:18 UTC, closed without merging