Add support for controlling HerePro LEDs using lua scripts
ArduPilot/ardupilot pull request #18691
Opened 2021-09-17 14:39 UTC by bugobliterator

2021-09-21 14:35 UTC, IamPete1 submitted a review, later dismissed
Scripting additions look good.  But I suspect we need to add `depends !defined(HAL_BUILD_AP_PERIPH)` to the majority of the existing methods. Because I guess they won't work on periph. Should save a bunch of flash too.

I like the new `handle_rgb_id` would nice to add support for that to the serial LED notify back-ends in the future too.

2021-09-22 07:58 UTC, tridge requested changes

2021-09-22 07:58 UTC, tridge commented on libraries/AP_HAL_ChibiOS/hwdef/HerePro/hwdef.dat
> +ROMFS scripts/hereproled.lua libraries/AP_Scripting/examples/hereproled.lua
better to put in scripts folder under hwdef folder for board

2021-09-22 07:58 UTC, tridge commented on libraries/AP_UAVCAN/AP_UAVCAN.cpp
> +void AP_UAVCAN::notify_state_send()
need a state rate parameter? or use one of the new option bits

2021-09-22 07:58 UTC, tridge commented on libraries/AP_UAVCAN/AP_UAVCAN.cpp
> +    hal.console->printf("NotifyState: yaw_cd=%d, float_yaw=%f\n", yaw_cd, AP::ahrs().get_yaw());
debug print should be removed?

2021-09-22 07:58 UTC, tridge commented on libraries/AP_UAVCAN/AP_UAVCAN.cpp
> +    for (uint8_t i=0; i<2; i++) {
better having a const uint8_t *data = (uint8_t *)&yaw_cd;

2021-09-22 08:00 UTC, tridge commented
need to check change in fw size for f1 and f3 firmwares

2021-09-29 07:34 UTC, bugobliterator commented
F103-GPS and F303-GPS has no flash size change whatsoever.

2021-09-29 07:35 UTC, bugobliterator commented
> Scripting additions look good. But I suspect we need to add `depends !defined(HAL_BUILD_AP_PERIPH)` to the majority of the existing methods. Because I guess they won't work on periph. Should save a bunch of flash too.
> 
> I like the new `handle_rgb_id` would nice to add support for that to the serial LED notify back-ends in the future too.

Would like to this, but as a separate PR. It would need to be based on separate PERIPH ENABLE flags as well.

2021-09-29 08:40 UTC, tridge approved these changes

2021-09-29 22:52 UTC, merged

2021-09-29 22:52 UTC, peterbarker commented
Merged, thanks!