Plane: split transition in to separate class for SLT, tailsitter and tiltrotor
ArduPilot/ardupilot pull request #18697
Opened 2021-09-17 23:32 UTC by IamPete1

Still needs testing, just want to get some feedback on the approach.

Tailsitter is completely removed from separate lift thrust, tilt rotor and STL still share lots of logic. 

This more or less the bare minimum to allow the split, there is more that can be done to make the split cleaner.

2021-09-22 08:10 UTC, tridge commented
on the right track, lots of testing needed!

2021-10-04 21:28 UTC, IamPete1 commented
Tested on tailsitter, SLT and tiltrotor in realflight.

2021-10-05 00:08 UTC, IamPete1 commented on ArduPlane/quadplane.cpp
> +bool SLT_Transition::set_FW_roll_limit(int32_t& roll_limit_cd) {
new line for `{`

2021-10-05 00:12 UTC, tridge requested changes
main thing is needs testing, and if possible avoid reboot on enable of different backend

2021-10-05 00:12 UTC, tridge commented on ArduPlane/quadplane.cpp
> +bool SLT_Transition::set_FW_roll_limit(int32_t& roll_limit_cd) {
code style

2021-10-29 19:05 UTC, IamPete1 commented
This has now had some real world testing on a tailsitter thanks to @robustini.

https://youtu.be/OO6rGn3Rljs

[00000012.ZIP](https://github.com/ArduPilot/ardupilot/files/7444371/00000012.ZIP)
[00000013.ZIP](https://github.com/ArduPilot/ardupilot/files/7444373/00000013.ZIP)

2021-11-01 23:14 UTC, tridge approved these changes

2021-11-01 23:14 UTC, merged