AP_HAL_ChibiOS: IOMCU digital out
ArduPilot/ardupilot pull request #18723
Opened 2021-09-20 14:18 UTC by IamPete1

This work is supported by CubePilot.

This adds support outputs via the IOMCU. For relay ect.

We could theoretically also do inputs, but there is a one way buffer preventing it in hardware.

2021-09-21 11:03 UTC, tridge requested changes
really nice, thanks! just minor issues
did you use 10.2 compiler to build IO fw?

2021-09-21 11:03 UTC, tridge commented on libraries/AP_HAL_ChibiOS/GPIO.cpp
> +                GPIO_mask |= 1 << i;
I prefer 1U << i so it is clearly unsigned. Doesn't matter in this case, but good habit

2021-09-21 12:21 UTC, IamPete1 commented
Io-firmware built with `g++ 10.2.1`. just re-tested on CubeOrange

2021-09-21 20:26 UTC, tridge approved these changes

2021-09-21 21:56 UTC, IamPete1 commented
Costs `184` bytes on the IOfirmware, now up to `47984`

2021-09-22 07:26 UTC, tridge commented
check memory usage, is it still allocation all the RC backends?

2021-09-22 09:26 UTC, IamPete1 commented
As far as I can tell this uses no more memory than before. `IOMC.Mem` is 704 on both master and this.

2021-09-27 23:40 UTC, tridge approved these changes

2021-09-27 23:40 UTC, merged