Update board_types.txt
ArduPilot/ardupilot pull request #18828
Opened 2021-10-03 00:11 UTC by nweaver

Developing a CM4-based carrier board, reserving a board ID.

2021-10-03 00:13 UTC, peterbarker requested changes
Please take 1049 instead - we're filling that gap in for some reason....

Commit message needs to nominate the directory, and actually be informative... something like `Tools: board_types.txt: reserve ID for ICSI Kestrel`

Let me know if you'd like me to do that for you.

2021-10-03 00:29 UTC, nweaver commented
Sure, please change ID to whichever you like.  Actual # doesn't matter for my purposes.

2021-10-04 01:50 UTC, peterbarker commented
@nweaver I've made that change and marked this for DevCall in case it doesn't get merged sooner.

2021-10-05 00:23 UTC, peterbarker approved these changes

2021-10-05 00:23 UTC, merged