RCOutput: fix full throttle bug causing motors to stop
ArduPilot/ardupilot pull request #18834
Opened 2021-10-03 16:46 UTC by shellixyz

Fix bug introduced in a51e58022f causing throttle > 99% to stop motors with DSHOT caused by the code sending values in range [49:2048] instead of [48:2047]

2021-10-03 19:00 UTC, andyp1per commented
Hi @shellixyz nice catch! The patch is not quite right - the dshot range should be 48 (for zero throttle) - 2047 (max throttle) so the bug only exists at the upper end. If the pwm value is 1 then the throttle should be 49. We deliberately changed this to not send values at all at PWM 0. The real problem is that dshot accepts 1000 steps of throttle resolution (48 - 2047) but we generate 1001 steps (0-1000). I think probably the right fix is to constrain value to be 0-999.

2021-10-03 19:00 UTC, andyp1per requested changes
See comment

2021-10-03 19:02 UTC, andyp1per commented
@rmackay9 this is a crash-o-matic bug

2021-10-03 19:16 UTC, shellixyz commented
> Hi @shellixyz nice catch! The patch is not quite right - the dshot range should be 48 (for zero throttle) - 2047 (max throttle) so the bug only exists at the upper end. If the pwm value is 1 then the throttle should be 49. We deliberately changed this to not send values at all at PWM 0. The real problem is that dshot accepts 1000 steps of throttle resolution (48 - 2047) but we generate 1001 steps (0-1000). I think probably the right fix is to constrain value to be 0-999.

Sounds like a better solution to constrain the values to [0:999] indeed

2021-10-03 19:52 UTC, shellixyz commented
Well in the end what I just changed the patch to is what makes the most sense in my opinion. Constraining `value` to max 1999 because otherwise limiting `pwm` to max 1999 means value will only get up to 2046 instead of 2047. What do you think @andyp1per ?

2021-10-03 20:08 UTC, andyp1per approved these changes
If it works, fine with me!

2021-10-03 21:05 UTC, rmackay9 commented
@andyp1per,

can you check if this crash-o-matic bug is in the 4.1 branch?  If it is then we're forced to do yet another release candidate.  Better that of course than a serious bug in our stable release though.

2021-10-03 21:35 UTC, andyp1per commented
@rmackay9 looks like its only in master

2021-10-04 07:27 UTC, giacomo892 commented
Tested on my side too, all good. Thanks @shellixyz . 
I guess it should be merged ASAP, master users can see their copters falling down the sky if one motor saturates even for a brief moment, on plane it is less scary, but completely loosing propulsion when full throttle is demanded can lead to a crash for instance on a go around procedure.

2021-10-05 00:46 UTC, tridge approved these changes

2021-10-05 00:47 UTC, merged