Copter 4.1
ArduPilot/ardupilot pull request #18841
Opened 2021-10-04 14:30 UTC by hathach23

I have added the new driver and datasheet for mcp9600 sensor, that uses I2C. Please help me check my code especially at the init() and read() and 3 write()-function. Thank you in advance.

2021-10-04 21:39 UTC, tridge commented
pull requests need to be against master. Then we will separately consider if the change is suitable to be backported to 4.1 release after it has been accepted into master

2021-10-04 21:43 UTC, tridge requested changes
this will need a bit of work to make a frontend/backend split for temperature sensors first

2021-10-04 21:43 UTC, tridge commented on ArduCopter/Copter.cpp
> +    SCHED_TASK(mcpUpdate, 10, 75),
new sensors should be hooked into AP_Vehicle, not Copter, so they work on all vehicle types

2021-10-04 21:43 UTC, tridge commented on libraries/AP_TemperatureSensor/AP_MCP9600.h
> +/*
before we add this we will need to do a frontend/backend split in AP_TemperatureSensor, like we have done for other driver types, so we have a TSENS_TYPE parameter to select which type of temperature sensor to enable

2021-10-04 21:44 UTC, tridge commented
@peterbarker we should discuss who will do the frontend/backend split, and if we do i2c simulators for these two sensor types

2021-10-04 21:47 UTC, tridge commented
or should we stick to lua scripts for temperature? Note that sub has support for one sensor type already

2021-10-04 23:01 UTC, magicrub commented
https://github.com/ArduPilot/ardupilot/pull/17627

2022-09-07 17:47 UTC, magicrub commented
closed in favor of https://github.com/ArduPilot/ardupilot/pull/21662

2022-09-07 17:47 UTC, closed without merging