AP_AHRS: make ExternalAHRS an AP_AHRS_Backend
ArduPilot/ardupilot pull request #18860
Opened 2021-10-06 09:27 UTC by peterbarker

This starts to make all our existing backends inherit from AP_AHRS_Backend - rather than just AP_AHRS_DCM.

Future PRs make SITL and the EKFs backends as well.

 - [ ] We should probably test this on an actual ExternalAHRS, rather than trusting the simulated one.

2021-10-06 12:17 UTC, amilcarlucas commented
```
Binary           text             data         bss           total
---------------  ---------------  -----------  ------------  ---------------
arduplane        1228 (+0.0706%)  0 (0.0000%)  4 (+0.0015%)  1232 (+0.0615%)
arducopter       728 (+0.0419%)   0 (0.0000%)  0 (0.0000%)   728 (+0.0364%)
ardurover        812 (+0.0520%)   0 (0.0000%)  4 (+0.0015%)  816 (+0.0447%)
antennatracker   764 (+0.0575%)   0 (0.0000%)  4 (+0.0015%)  768 (+0.0483%)
arducopter-heli  736 (+0.0429%)   0 (0.0000%)  0 (0.0000%)   736 (+0.0372%)
ardusub          792 (+0.0518%)   0 (0.0000%)  0 (0.0000%)   792 (+0.0442%)
blimp            676 (+0.0535%)   0 (0.0000%)  4 (+0.0015%)  680 (+0.0446%)
```

2021-10-07 09:05 UTC, khancyr commented
yep, much better than bloatly !

2023-05-29 23:14 UTC, tridge requested changes
need updated flash cost

2023-05-29 23:14 UTC, tridge commented on libraries/AP_AHRS/AP_AHRS.cpp
> +        break;
break inside #if ?

2023-05-31 07:15 UTC, tridge requested changes

2023-05-31 07:15 UTC, tridge commented on libraries/AP_AHRS/AP_AHRS_External.cpp
> +bool AP_AHRS_External::get_vert_pos_rate(float &velocity) const
change to pos_down_rate and fix sagetech user

2023-05-31 07:16 UTC, tridge approved these changes
approved as long as sagetech and api fixed in followup PR

2023-06-01 02:45 UTC, merged