AP_BatteryMoniter: add mask param to sum battery backend.
ArduPilot/ardupilot pull request #18975
Opened 2021-10-19 02:09 UTC by IamPete1

Adds mask parameter to sum battery backed. This allows https://github.com/ArduPilot/ardupilot/pull/18938 except we can report the reading used, and it works for all other used cases too. 

Of course compass will still need a param, but now it can just be a battery index not a mask. 

Could even re-use `COMPASS_MOTCT` something like:

0:Disabled
1:Use Throttle,
2:Use Current form batt mon 1
3: bat mon 2
4: bat mon 4
ect

2021-11-01 16:28 UTC, IamPete1 commented
This now includes a breaking change to SMBus param as there indexes have moved. There new location is not in stable, only master. The param conversation still works from stable to this. Just current master to this will not work.

2021-11-01 18:11 UTC, hendjoshsr71 requested changes
Looks good.  Small changes and one question about docs generation.

The conversion worked me with the EEPROM save I used before. 

Thanks this looks like a much better approach to this code! Less code & should be some less space, :) Assuming we never need for more than 10 params per level (which seems reasonable).  

The only issue I could see is we will need to eventually extend the group to continue doing this beyond the first few monitors_types with their own params.  

The only other approach I could see easily is adding a another backend_var_info (meh) for all non-dynamic param groups.  And have a separate backend_var_info for each distinct dynamic group. But that is a lot more space and more code to maintain especially with 9 monitors.

2021-11-01 18:11 UTC, hendjoshsr71 commented on libraries/AP_BattMonitor/AP_BattMonitor_Sum.cpp
> +    // Param indexes must be between 20 and 29 to avoid conflict with other battery moniter param tables loaded by pointer
```suggestion
    // Param indexes must be between 20 and 29 to avoid conflict with other battery monitor param tables loaded by pointer
```

2021-11-01 19:26 UTC, IamPete1 commented on libraries/AP_BattMonitor/AP_BattMonitor.cpp
> +    AP_SUBGROUPVARPTR(drivers[0], "_", 41, AP_BattMonitor, backend_var_info[0]),
I don't understand these index changes. I just changed the variable name from `backend_analog_var_info` to `backend_var_info` Why would the index change?

2021-11-01 19:32 UTC, hendjoshsr71 commented on libraries/AP_BattMonitor/AP_BattMonitor.cpp
> +    AP_SUBGROUPVARPTR(drivers[0], "_", 41, AP_BattMonitor, backend_var_info[0]),
We wouldn't be using index 32-40 then at all. If you look at the deleted indexes of the smbus_var_infos you will see that. Sorry for the mess....

2021-11-01 19:43 UTC, IamPete1 commented on libraries/AP_BattMonitor/AP_BattMonitor.cpp
>      // @Path: AP_BattMonitor_Analog.cpp
nearly, had to add `// @Group:` to each one, its not that painful tho.

2021-11-01 19:44 UTC, IamPete1 commented on libraries/AP_BattMonitor/AP_BattMonitor.cpp
> +    AP_SUBGROUPVARPTR(drivers[0], "_", 41, AP_BattMonitor, backend_var_info[0]),
I think its better to have the gap, this at least means that we won't loose the analog params people had setup on master.

2021-11-01 19:47 UTC, hendjoshsr71 commented on libraries/AP_BattMonitor/AP_BattMonitor.cpp
> +    AP_SUBGROUPVARPTR(drivers[0], "_", 41, AP_BattMonitor, backend_var_info[0]),
True enough. Then we would need to add a comment about why 9 indices got lost forever...

2021-11-01 20:07 UTC, IamPete1 commented on libraries/AP_BattMonitor/AP_BattMonitor.cpp
> +    AP_SUBGROUPVARPTR(drivers[0], "_", 41, AP_BattMonitor, backend_var_info[0]),
They have not been out in a stable, it would probably be OK to re-use them in the future.

2021-11-01 22:35 UTC, IamPete1 commented
Saves flash on the f405 wing.
```
Binary           text           data         bss            total
---------------  -------------  -----------  -------------  -------------
arduplane        92 (+0.0095%)  0 (0.0000%)  4 (+0.0031%)   96 (+0.0087%)
arducopter       92 (+0.0099%)  0 (0.0000%)  4 (+0.0031%)   96 (+0.0090%)
ardurover        92 (+0.0111%)  0 (0.0000%)  -4 (-0.0031%)  88 (+0.0091%)
antennatracker   92 (+0.0141%)  0 (0.0000%)  4 (+0.0031%)   96 (+0.0122%)
arducopter-heli  92 (+0.0100%)  0 (0.0000%)  4 (+0.0031%)   96 (+0.0091%)
ardusub          92 (+0.0115%)  0 (0.0000%)  -4 (-0.0031%)  88 (+0.0094%)
blimp            92 (+0.0137%)  0 (0.0000%)  -4 (-0.0031%)  88 (+0.0109%)
```

2021-11-02 00:12 UTC, tridge approved these changes

2021-11-02 00:12 UTC, merged