Add CrashCatcher in ChibiOS firmware to debug HardFaults
ArduPilot/ardupilot pull request #19008
Opened 2021-10-21 10:58 UTC by bugobliterator

This PR works towards resolving https://github.com/ArduPilot/ardupilot/issues/18674
Aim of this work is to simplify tracking down Hardfault, which are faults caused by bad access to memory, bad floating point or arithmetic operations.

This PR adds CrashCatcher library, a marvellous project https://github.com/adamgreen/CrashCatcher that allows dumping all info needed to do stack trace and pin point the location which invoked the HardFault. Paired with https://github.com/adamgreen/CrashDebug we can now automatically detect, and give back the backtrace which led to hardfault. 

We support two types of fault dumps, first is a dump on the Serial port and second way is to dump in a dedicated flash page.

## Steps for getting fault dump via Serial:

All one needs to do is connect the First USART(not OTG) in the SERIAL_ORDER of the board via FTDI. In the case of CubeOrange that is Telem1 and for most boards that should be the case as well. Once connected run following command:
```
./Tools/debug/crash_debugger.py /path/to/elf --ser-debug --ser-port /dev/ttyxxx path/to/elf/file --dump-filename logfile.txt
```
Additionally the logfile.txt contains a memory dump, which can be shared along with elf file. And devs can then just start up gdb using following command, and do all the analysis that needs done.

```
arm-none-eabi-gdb -nx path/to/elf/file -ex "set target-charset ASCII" -ex "target remote | modules/CrashDebug/bins/lin64/CrashDebug --elf path/to/elf/file --dump logfile.txt"
```

## Steps for getting fault dump via Flash:
If a fault happens the information gets recorded in flash sector defined in hwdef `define HAL_CRASH_DUMP_FLASHPAGE xx` .

Only one crash will be recorded per flash cycle. At every new firmware update the flash will be ready again to record the crash log. Maybe we can erase the crash flash page via a parameter or maybe right after we fetch the crash_dump.bin.
To fetch the crash dump `@SYS/crash_dump.bin` can be fetched via MAVFTP.

Once fetched one can either use the following command to immediately dump backtrace with locals:
```
./Tools/debug/crash_debugger.py  /path/to/elf --dump-debug --dump-filein crash_dump.bin
```

or to open in gdb for further postmortem do the following:
```
arm-none-eabi-gdb -nx path/to/elf/file -ex "set target-charset ASCII" -ex "target remote | modules/CrashDebug/bins/lin64/CrashDebug --elf path/to/elf/file --dump crash_dump.bin"
```

## Steps for debugging faults using GDB:
* Connect hardware over SWD
* Place breakpoint at hardfault using `b *&HardFault_Handler`
* If one is lucky process stack remained untouched one can do `set $sp = $psp`
* Now you can simply run `backtrace` and potentially reach the fault
* If fault happens at startup one can `run` and then wait for breakpoint hit at HardFault_Handler
* and the set sp and do backtrace
* One can also log the RAM, refer crash_debugger app and Tools/debug/crash_dump.scr for the same.

Ref.
https://interrupt.memfault.com/blog/cortex-m-fault-debug
https://github.com/adamgreen/CrashCatcher/tree/c8e801225bfa12da70c01ea25b58090b2b7a2e0a
http://www.cyrilfougeray.com/2020/07/27/firmware-logs-with-stack-trace.html

2021-10-22 03:29 UTC, adamgreen commented
If you didn't have enough FLASH to store a copy of all RAM, you might be able to just dump the crashing stack and optionally the stacks of the other threads as well. So you could get a dump of the call stacks from GDB but you wouldn't have access to globals or dynamically allocated data structures. This is harder to do though as you need to be able to walk the RTOSs thread list and figure out the current stack address range for each one.

2021-10-29 21:15 UTC, tridge requested changes

2021-10-29 21:15 UTC, tridge commented on libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
> +        return get_config('FLASH_SIZE_KB', type=int)/128
should be // for integer division

2021-10-29 21:15 UTC, tridge commented on libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
> +        return get_config('FLASH_SIZE_KB', type=int)/2
should be //

2021-10-30 07:55 UTC, tridge approved these changes

2021-10-30 08:24 UTC, merged