ChibiOS: get crash dump info on main thread lockup
ArduPilot/ardupilot pull request #19092
Opened 2021-10-31 10:41 UTC by tridge

2021-11-02 03:36 UTC, bugobliterator approved these changes

2023-06-16 12:15 UTC, peterbarker requested changes
This was approved but not merged, and there's no reason given here why we shouldn't merge it.  The "crash dump is too short" thing applies to CrashDumper regardless of how it is triggered.  Something is still probably better than nothing, and boards with heaps of free space might do better with this in than out.

Does need the define name changed, 'though.

2023-06-16 12:15 UTC, peterbarker commented on libraries/AP_HAL_ChibiOS/Scheduler.cpp
> +#if HAL_CRASHDUMP_ENABLE
```suggestion
#if AP_CRASHDUMP_ENABLED
```

2023-06-16 21:01 UTC, tridge commented on libraries/AP_HAL_ChibiOS/Scheduler.cpp
> +#if HAL_CRASHDUMP_ENABLE
fixed

2023-06-16 21:03 UTC, tridge commented
@peterbarker thanks, fixed

2023-06-17 01:24 UTC, merged