libraries: add hygrometer sensor
ArduPilot/ardupilot pull request #19101
Opened 2021-11-01 06:57 UTC by gitfishup

The flight controller receive the hygrometer message from CAN device and flight controller send hygrometer message to the ground station.

background:
CUAV developed a new airspeed sensor that can be heated.The airspeed sensor heats up according to the set temperature, so as to prevent airspeed failure due to ice on the head of the airspeed sensor when the fixed-wing UAV is used in high and cold places.The temperature and humidity sensor is used to detect the temperature and humidity of the pitot tube head. If the measured temperature is lower than the set temperature, the airspeed sensor will enable heating to prevent ice.

The value shows in MissionPlanner.
![lQLPDhrQcGhJCznNAhzNAaaw9Ik0twoGiU8Bgr_Y7EAcAA_422_540](https://user-images.githubusercontent.com/69180601/139632528-44a10d54-3aa4-4a12-bfd6-3b55f1f7a09c.png)

Logging:
[hygrometer_log.zip](https://github.com/ArduPilot/ardupilot/files/7451226/hygrometer_log.zip)
 
parameters for setting:
HYGROx_TYPE:  0 for none , 1 for uavcan. Note: HYGRO2_TYPE can be set after HYGRO1_TYPE is set to 1;
HYGRO_PRIMARY: to select the primary one.
![image](https://user-images.githubusercontent.com/69180601/139632782-e7e4c0ee-de23-4651-bc9b-29afc218fcad.png)

2021-11-01 09:30 UTC, gitfishup commented
@peterbarker Could you please have a review?

2021-11-02 11:54 UTC, peterbarker requested changes
This is a partial review only.

I think you need to comment in here somewhere how the data moves around, and what the protections are.

Often what you will have is your `::update()` function (which runs on the main thread) will call each `backend[i].update()` which takes a sempahore and copies data from backend-private data into `state[i]`.  You're kind of doing that here, but mixing it with the logging function :-)  Please split those apart.

I haven't looked through the UAVCAN driver yet.

2021-11-02 11:54 UTC, peterbarker commented on libraries/AP_Hygrometer/AP_Hygrometer.cpp
> +                break;
```suggestion
#if HAL_ENABLE_LIBUAVCAN_DRIVERS    
             case Type::UAVCAN:
                sensor[i] = AP_Hygrometer_UAVCAN::probe(*this, i, state[i], param[i]);
                break;
#endif
```

2021-11-02 11:54 UTC, peterbarker commented on libraries/AP_Hygrometer/AP_Hygrometer.h
> +        UAVCAN=1,
```suggestion
#if HAL_ENABLE_LIBUAVCAN_DRIVERS
        UAVCAN=1,
#endif
```

This makes it harder to leave code in accidentally :-)

2021-11-02 11:54 UTC, peterbarker commented on libraries/AP_Hygrometer/AP_Hygrometer.cpp
> +        if (sensor[i] && !sensor[i]->init()) {
```suggestion
        if (sensor[i] == nullptr) {
            continue;
        }
        if (!sensor[i]->init()) {
```

2021-11-02 11:54 UTC, peterbarker commented on libraries/AP_Hygrometer/AP_Hygrometer.cpp
> +        }
```suggestion
            continue;
        }
```

2021-11-02 11:54 UTC, peterbarker commented on libraries/AP_Hygrometer/AP_Hygrometer.cpp
> +        }
```suggestion
        num_sensors = i+1;
```

2021-11-02 11:54 UTC, peterbarker commented on libraries/AP_Hygrometer/AP_Hygrometer.cpp
> +    return false;
```suggestion
    if (sensor[i] == nullptr) {
        return false;
    }

    return sensor[i]->get_humidity(humidity);
```

2021-11-02 11:54 UTC, peterbarker commented on libraries/AP_Hygrometer/AP_Hygrometer.cpp
> +    return false;
```suggestion
    if (sensor[i] == nullptr) {
        return false;
    }

    return sensor[i]->get_temperature(temperature);
```

2021-11-02 11:54 UTC, peterbarker commented on libraries/AP_Hygrometer/AP_Hygrometer.cpp
> +
```suggestion
```

Unused

2021-11-02 11:54 UTC, peterbarker commented on libraries/AP_Hygrometer/AP_Hygrometer.cpp
> +    for (uint8_t i=0; i<HYGROMETER_MAX_SENSORS; i++) {
```suggestion
    for (uint8_t i=0; i<num_sensors; i++) {
```

2021-11-02 11:54 UTC, peterbarker commented on libraries/AP_Hygrometer/AP_Hygrometer.cpp
> +            temperature = 0;
```suggestion
            temperature = AP::logger().quiet_nanf();
```

2021-11-02 11:54 UTC, peterbarker commented on libraries/AP_Hygrometer/AP_Hygrometer.cpp
> +            humidity = 0;
```suggestion
            humidity = AP::logger().quiet_nanf();
```

2021-11-02 11:54 UTC, peterbarker commented on libraries/AP_Hygrometer/AP_Hygrometer.cpp
> +
```suggestion
```

Logging function should not be modifying state.  If you want to grab data from the backends, do it as another function call out of your `::update` function - and only use (e.g.) `state[i].temperature` in here.

2021-11-02 11:54 UTC, peterbarker commented on libraries/AP_Hygrometer/AP_Hygrometer.cpp
> +#endif // HAL_HYGROMETER_ENABLED
```suggestion
#endif // HAL_HYGROMETER_ENABLED
```

2021-11-02 11:54 UTC, peterbarker commented on libraries/AP_Hygrometer/AP_Hygrometer.cpp
> +#endif // HAL_HYGROMETER_ENABLED
Please ensure all files have a lf at the end

2021-11-02 11:54 UTC, peterbarker commented on libraries/AP_Hygrometer/AP_Hygrometer.h
> +#endif
```suggestion
#ifndef AP_HYGROMETER_MAX_SENSORS
#define AP_HYGROMETER_MAX_SENSORS  2
#endif
```

2021-11-02 11:54 UTC, peterbarker commented on libraries/AP_Hygrometer/AP_Hygrometer.h
> +
```suggestion
```

2021-11-02 11:54 UTC, peterbarker commented on libraries/AP_Hygrometer/AP_Hygrometer.h
> +        // return true if hygrometer is enabled
```suggestion
    // return true if hygrometer is enabled
```

2021-11-02 11:54 UTC, peterbarker commented on libraries/AP_Hygrometer/AP_Hygrometer.h
> +    uint8_t get_primary(void) const { return primary; }
We probably don't need an accessor for this.

2021-11-02 11:54 UTC, peterbarker commented on libraries/AP_Hygrometer/AP_Hygrometer.h
> +    uint8_t primary;
You've got this and `primary_sensor` - pretty sure that's not right.

2021-11-02 11:54 UTC, peterbarker commented on libraries/AP_Hygrometer/AP_Hygrometer_UAVCAN.cpp
> +{}
We probably do not need this.  See comment in header file

2021-11-02 11:54 UTC, peterbarker commented on libraries/AP_Hygrometer/AP_Hygrometer_Backend.h
> +    float get_temperature() const { return state.temperature; }
```suggestion
    virtual float get_humidity() const = 0;
    virtual float get_temperature() const = 0;
```

2021-11-22 00:52 UTC, closed without merging