Clean up short failsafe
ArduPilot/ardupilot pull request #19122
Opened 2021-11-02 20:19 UTC by Hwurzburg

replaces #19093...
-missed that Qplane short failsafe did not return the mode....fixed
-changed mode restore check to use last mode reason, so becomes universal for ANY modes changes made while in RC failsafe, gcs, battery, etc.
-added mode change reason for restoring from short failsafe
-cleaned up GS messaging to be sent only on mode change and made restore of mode clear to gcs

tested for several hours in SITL, but needs to be flight tested....

2021-11-02 22:40 UTC, peterbarker requested changes
- the new failsafe recovery enum  value is great and could be a separate PR
 - there's a check against mode in FBWB in Attitude.cpp line 94 which looks pretty dodgy
 - several places in the code are calling `failsafe_short_off_event` with what is now the wrong code (RADIO_FAILSAFE` rather than `RADIO_FAILSAFE_RECOVERY`)

I was thinking we might be being a bit more ambitious, but this has been tested thoroughly, so I'm not going to push on that.  An example of what that might look like is here: https://github.com/ArduPilot/ardupilot/compare/master...peterbarker:pr/shortfailsafe-more?expand=1

Most notable conclusion I'm drawing out of this is that we are clearly undertaking short failsafe actions when the action is clearly set to "disabled"!  That option might need to be renamed.

2021-11-02 23:35 UTC, Hwurzburg commented on libraries/AP_Vehicle/ModeReason.h
> +  FAILSAFE_MODE_RECOVERY = 48,
np ....will change

2021-11-02 23:36 UTC, Hwurzburg commented on ArduPlane/Plane.h
> +        bool restore_mode_on_recovery;
np...will change

2021-11-02 23:37 UTC, Hwurzburg commented on ArduPlane/events.cpp
> +    failsafe.saved_mode_number = control_mode->mode_number();
if we ever desire to have a new mode in the future and want to return to entry mode, even if we have changed modes (scripting?) while in the short fs period, not storing would be a problem...this way is more mistake proof in the future I think

2021-11-02 23:40 UTC, Hwurzburg commented on ArduPlane/events.cpp
> +            set_mode(mode_circle, reason); // cicle if action = 0 or 1
I would need help here because pointers are not my strong suit....primarily becuase I dont have a monkey-see monkey-do example to plagiarize

2021-11-02 23:54 UTC, Hwurzburg commented
"there's a check against mode in FBWB in Attitude.cpp line 94 which looks pretty dodgy"
   I doubt its needed since failsafe forces controls to neutral and there is no rc to change them...if it did then this statement would need to be extended for long fs FBWA glides also...
"several places in the code are calling failsafe_short_off_event with what is now the wrong code (RADIO_FAILSAFErather thanRADIO_FAILSAFE_RECOVERY`)"
  I think you are confusing other vehicles...plane only calls on and off event once in system.cpp.....your mileage might vary with other vehicles and their handling of rc failsafe however...
"Most notable conclusion I'm drawing out of this is that we are clearly undertaking short failsafe actions when the action is clearly set to "disabled"! That option might need to be renamed."
   short failsafe on event is only called if fs_short_act does not equal "disabled" (3)

2021-11-03 23:54 UTC, tridge commented on ArduPlane/events.cpp
> +            set_mode(mode_circle, reason); // cicle if action = 0 or 1
> Further, they should only be setting a `Plane::Mode *new_mode` pointer value, not calling `set_mode`. That will be good or some bytes. Setting the `restore_mode_on_recovery` flag should be directly above or below that call to `set_mode`.

why avoid set_mode()? Wouldn't we lose all the init logic?

2021-11-03 23:57 UTC, peterbarker commented on ArduPlane/events.cpp
> +            set_mode(mode_circle, reason); // cicle if action = 0 or 1
Apologies.  I meant create a local `new_mode` pointer for the clauses to populate; if set a single place at the bottom of the logic sets the new mode and the state for us to revert to hte original mode.  The PR I referenced above shows this structure.

2021-11-24 23:57 UTC, tridge requested changes

2021-11-24 23:57 UTC, tridge commented on ArduPlane/events.cpp
> +        failsafe.restore_mode_on_failsafe_recovery = true;
i'm a bit concerned that a 2nd call to failsafe_short_on_event() while still in a first failsafe will end up saving the wrong mode

2021-12-02 21:38 UTC, tridge approved these changes

2021-12-05 04:23 UTC, peterbarker commented on ArduPlane/events.cpp
> +            set_mode(mode_circle, reason); // cicle if action = 0 or 1
```suggestion
            set_mode(mode_circle, reason); // circle if action = 0 or 1 
```

2021-12-05 04:23 UTC, peterbarker commented on ArduPlane/events.cpp
> +            set_mode(mode_fbwb, reason);
Indenting
```suggestion
                set_mode(mode_fbwb, reason);
```

2021-12-05 04:23 UTC, peterbarker commented on ArduPlane/events.cpp
> +    if( _last_reason == ModeReason::RADIO_FAILSAFE) {
```suggestion
    if ( _last_reason == ModeReason::RADIO_FAILSAFE) { 
```

2021-12-05 04:23 UTC, peterbarker commented on ArduPlane/events.cpp
> +        if(g.fs_action_short != FS_ACTION_SHORT_BESTGUESS) { // if acton = 0 this group of modes take no action
```suggestion
        if (g.fs_action_short != FS_ACTION_SHORT_BESTGUESS) { // if action is BESTGUESS then this group of modes take no action
```

2021-12-05 04:23 UTC, peterbarker commented on ArduPlane/events.cpp
> +       set_mode_by_number(failsafe.saved_mode_number, ModeReason::RADIO_FAILSAFE_RECOVERY);
We could just as easily use `Mode *saved_mode`.

2021-12-05 13:34 UTC, Hwurzburg commented
dont understand the last comment, but changed all the rest...thanks

2021-12-06 23:09 UTC, merged