Allow notch update to be configurable
ArduPilot/ardupilot pull request #19246
Opened 2021-11-14 08:42 UTC by andyp1per

2021-11-16 00:54 UTC, tridge approved these changes
note that:
_last_notch_update_ms = now
shuld happen before update_dynamic_notch();

2021-11-16 00:55 UTC, tridge requested changes
need to fix AP_Vehicle::update_dynamic_notch_at_specified_rate() to set timestamp first

2021-11-16 00:55 UTC, tridge commented
also needs to not call millis() unless needed

2021-11-16 07:26 UTC, andyp1per commented
Ok, fixed

2021-11-17 08:01 UTC, tridge approved these changes

2021-11-17 13:35 UTC, merged