Copter: Refactoring the code
ArduPilot/ardupilot pull request #19252
Opened 2021-11-14 22:05 UTC by muramura

Stop making more decisions in order to have one layer of code.
It is true that the more layers, the harder it is to understand.
However, with this code, I think it would be better to make it a layer.

2021-11-15 08:27 UTC, amilcarlucas approved these changes

2021-11-22 01:07 UTC, peterbarker requested changes
Commit comment needs fixing:

`Copter: remove redundant checks when calculating SYS_STATUS flags`

2021-11-22 01:07 UTC, peterbarker commented on ArduCopter/GCS_Copter.cpp
> -        control_sensors_health |= MAV_SYS_STATUS_SENSOR_OPTICAL_FLOW;
This exact same code is present in Plane *and* Sub.  After this change we'll have two different versions of the code.

I do prefer your new formulation here.

.... but I also think we should probably put OpticalFlow on AP_Vehicle, especially now we can play with scheduler tables priority a bit better.

2021-11-22 01:08 UTC, peterbarker commented
... sorry, I should say you don't need to move OpticalFlow up as part of this PR!

2024-07-24 10:13 UTC, peterbarker commented
This code has been moved up into `GCS_MAVLink/GCS.cpp` and is shared across all vehicles.  It uses a callback to determine the failsafe status, so I think this is all good now.

Thanks anyway!

2024-07-24 10:13 UTC, closed without merging