AP_TECS: Log input height demands.
ArduPilot/ardupilot pull request #19275
Opened 2021-11-16 15:56 UTC by samuelctabor

I think there is value in logging the input altitude demands to the TECS. This exposes some some problems with the altitude handling in altitude.cpp that are not otherwise obvious.

2021-11-16 17:28 UTC, hendjoshsr71 requested changes

2021-11-16 17:28 UTC, hendjoshsr71 commented on libraries/AP_TECS/AP_TECS.cpp
> +                       "Qffffffff",
Shouldn't this be meters in the units format code?
You could also do the `* 0.01` using code `B` in the scaling bit but doesn't matter either way. 

```suggestion
    AP::logger().WriteStreaming("TEC2", "TimeUS,pmax,pmin,KErr,PErr,EDelta,LF,hdem1,hdem2",
                       "s------mm",
                       "F--------",
                       "Qffffffff",
```

2021-11-18 16:21 UTC, hendjoshsr71 approved these changes
LGTM

Not for this PR: Just one note on variable naming that was confusing to me here.
We have hgt_dem_cm (the input) & _hgt_dem ( rate-limited input) _hgt_dem could use  a rename one day. (`_hgt_dem_rate_limited`) perhaps.

2021-11-22 00:43 UTC, peterbarker approved these changes

2021-11-23 00:14 UTC, tridge approved these changes

2021-11-23 00:15 UTC, merged

2021-11-24 23:23 UTC, kniuk commented
@samuelctabor nice idea. something like `hgt_dem_raw` and `hgt_dem_limited` would be more descriptive.
I believe we could decrease averaging if input `hgt_dem`raw` is fed into TECS