Copter: Add support for pausing and continuing auto missions
ArduPilot/ardupilot pull request #19317
Opened 2021-11-20 14:40 UTC by mustafa-gokce

This pull request adds support MAV_CMD_DO_PAUSE_CONTINUE command in AUTO mode for Copter. When copter receives pause command `command_int GLOBAL MAV_CMD_DO_PAUSE_CONTINUE 0 0 0 0 0 0 0 0 0` it loiters, and when it receives continue command `command_int GLOBAL MAV_CMD_DO_PAUSE_CONTINUE 0 0 1 0 0 0 0 0 0` it resumes the mission.

2021-11-20 16:17 UTC, amilcarlucas commented
Thanks, it is much better now

2021-11-22 01:00 UTC, peterbarker requested changes
I quite like this, and I think we should merge this functionality without expanding on it.

However, I will point out that the description of the mavlink command states that it should work in any GPS-controlled position mode, and I think it would make sense to honour that in at least `GUIDED` mode, too.

This command would also be appropriate in all of our other vehicles, but I can't see that they could share any code at this point.

2021-11-22 01:00 UTC, peterbarker commented on ArduCopter/GCS_Mavlink.cpp
> +    case MAV_CMD_DO_PAUSE_CONTINUE:
The code in here should be factored out into a `handle_command_pause_continue` method, and also be available from `handle_command_long_packet`.

2021-11-22 01:28 UTC, rmackay9 commented
This looks pretty OK to me.  This has been tested in SITL of course?

2021-11-22 10:55 UTC, mustafa-gokce commented
@peterbarker now MAV_CMD_PAUSE_CONTINUE commands can be sent with both as COMMAND_LONG and COMMAND_INT commands.
I testes this in SITL by sending commands like:
```
AUTO> command_int GLOBAL MAV_CMD_DO_PAUSE_CONTINUE 0 0 0 0 0 0 0 0 0
AUTO> command_int GLOBAL MAV_CMD_DO_PAUSE_CONTINUE 0 0 1 0 0 0 0 0 0
AUTO> long MAV_CMD_DO_PAUSE_CONTINUE 0 0 0 0 0 0 0
AUTO> long MAV_CMD_DO_PAUSE_CONTINUE 1 0 0 0 0 0 0
```
It is working properly on SITL.

2021-11-24 07:08 UTC, peterbarker commented
@mustafa-gokce thanks for fixing this up.

We don't allow merge commits into ArduPilot, however - please do a rebase on top of master to remove it.

2021-11-24 08:04 UTC, peterbarker requested changes
Need the scope here or some poor person in the future gets an error... ("jump to case label" or something)

2021-11-24 08:04 UTC, peterbarker commented on ArduCopter/GCS_Mavlink.cpp
> +    case MAV_CMD_DO_PAUSE_CONTINUE:
```suggestion
    case MAV_CMD_DO_PAUSE_CONTINUE: {
```

2021-11-24 08:04 UTC, peterbarker commented on ArduCopter/GCS_Mavlink.cpp
> +
```suggestion
    }
```

2021-11-24 10:49 UTC, peterbarker commented
This looks well-formed as a PR now - thanks for reworking it!

2021-11-24 10:54 UTC, mustafa-gokce commented
@peterbarker, thanks for your guidance.
I started working to support this command in GUIDED mode and other vehicles.
And when it is done, I will post it.
Have a nice day.

2021-11-24 11:08 UTC, rmackay9 commented
@mustafa-gokce,

Can you test what happens in these situations?

**Situation 1**
1. missiion is stopped using the new command
2. user switches out of auto and then back into auto
expected result: mission should restart

**Situation 2**
1. missiion is stopped using the new command
2. user changes active waypoint to some other command (e.g. "wp set 3")
3. user restarts mission with the new command
expected result: mission should restart at command 3 (?)

**Situation 3**
1. mission is stopped using the new command
2. user restarts the mission using the MISSION_START command
expected result: mission should start but I'm unsure whether it will resume or restart.  It may depend upon the WPNAV_RESTART param value.

2021-11-24 11:36 UTC, peterbarker commented
... I'm curious to know what happens if you include this as a mission item in a mission, @mustafa-gokce - we might need to guard against it.

2021-11-24 11:37 UTC, peterbarker commented
@mustafa-gokce I've added an autotest here to ensure the basic functionality never dies.

2021-11-24 11:46 UTC, mustafa-gokce commented
@rmackay9 hello sir.
I used this mission to test it.
```
QGC WPL 110
0	0	0	16	0.000000	0.000000	0.000000	0.000000	-35.363262	149.165237	584.049988	1
1	0	3	16	0.000000	0.000000	0.000000	0.000000	-35.359349	149.164783	100.000000	1
2	0	3	16	0.000000	0.000000	0.000000	0.000000	-35.363506	149.160206	100.000000	1
3	0	3	16	0.000000	0.000000	0.000000	0.000000	-35.367981	149.166408	100.000000	1
4	0	3	16	0.000000	0.000000	0.000000	0.000000	-35.362578	149.171537	100.000000	1
5	0	0	177	1.000000	1000.000000	0.000000	0.000000	0.000000	0.000000	0.000000	1
```
I loaded the mission and did the following:
```
mode GUIDED
arm throttle
takeoff 100
mode AUTO
```
**Situation 1**
1. Did `command_int GLOBAL MAV_CMD_DO_PAUSE_CONTINUE 0 0 0 0 0 0 0 0 0` and vehicle stopped.
2. Did `mode GUIDED` and the vehicle is still loitering.
3. Did `mode AUTO` and vehicle resuming the mission where is it left off because MIS_RESTART=0, but when set MIS_RESTART=1 and do all steps, after the 3rd step, the vehicle starts the mission from the beginning as it supposed to.
So I think it passes the first situation.

**Situation 2**
1. I loaded the mission, took off, and changed the mode to AUTO.
2. I did `command_int GLOBAL MAV_CMD_DO_PAUSE_CONTINUE 0 0 0 0 0 0 0 0 0` and vehicle holds position.
3. I did wp set 2 (while it waiting between 3 and 4).
4. I did `command_int GLOBAL MAV_CMD_DO_PAUSE_CONTINUE 0 0 1 0 0 0 0 0 0` and vehicle starts to move 2nd wp.
So I think it passes the second situation.

**Situation 3**
1. I loaded the mission, took off, and changed the mode to AUTO.
2. I did `command_int GLOBAL MAV_CMD_DO_PAUSE_CONTINUE 0 0 0 0 0 0 0 0 0` and vehicle holds position.
3. I did `long MAV_CMD_MISSION_START 0 0 0 0 0 0 0 0` and the mission resumes where it left off because MIS_RESTART=0, but when set MIS_RESTART=1 and run it again, it starts from the beginning of the mission.
So I think it passes the third situation.

2021-11-24 11:51 UTC, mustafa-gokce commented
> @mustafa-gokce I've added an autotest here to ensure the basic functionality never dies.

@peterbarker I think we have a problem.
When I add command to the mission, SITL crashed, 
> PANIC: Mission command with ID 193 has no string

2021-11-24 12:15 UTC, mustafa-gokce commented
@peterbarker I added string for MAV_CMD_PAUSE_CONTINUE and now SITL works fine.
When I add MAV_CMD_PAUSE_CONTINUE in the auto mission list, it says it is an invalid command, skipping and resuming the mission without interrupting.

2021-11-24 12:40 UTC, rmackay9 approved these changes
@mustafa-gokce, thanks very much for doing that testing.

2021-11-24 20:29 UTC, peterbarker approved these changes
LGTM

2021-11-24 23:18 UTC, merged

2021-11-24 23:18 UTC, rmackay9 commented
Merged, thanks!

2022-06-07 10:48 UTC, BV-OpenSource commented
> @peterbarker I added string for MAV_CMD_PAUSE_CONTINUE and now SITL works fine. When I add MAV_CMD_PAUSE_CONTINUE in the auto mission list, it says it is an invalid command, skipping and resuming the mission without interrupting.

Should it not be working on mission mode?

I opened the discussion [here](https://discuss.ardupilot.org/t/about-the-copter-4-2-category/82459/2?u=bv-opensource) if you want to continue there.

2022-06-07 10:53 UTC, rmackay9 commented
@BV-OpenSource, txs for the report.  I've replied in the discussion.

2022-06-07 11:04 UTC, mustafa-gokce commented
@BV-OpenSource thanks for your interest, I replied in [here](https://discuss.ardupilot.org/t/about-the-copter-4-2-category/82459/5?u=mustafa_gokce)