Copter: 4.1.2-rc1 beta release
ArduPilot/ardupilot pull request #19328
Opened 2021-11-22 00:33 UTC by rmackay9

This is the PR to update the Copter-4.1 branch for the 4.1.2-rc1 beta release.  This is "double rebased" on the Plane-4.1 branch making it pretty much equivalent to the Plane-4.1.3 release with these additions:

- AP_Motors: change H_COLL_HOVER to H_COL_HOVER https://github.com/ArduPilot/ardupilot/pull/19295
- Copter: surface tracking timeout fix https://github.com/ArduPilot/ardupilot/pull/19207
- Add FETtec OneWire (ESC telemetry) support https://github.com/ArduPilot/ardupilot/pull/18631

2021-11-22 07:07 UTC, tridge commented
@rmackay9 we need to check if adding FETTec support takes us over the flash limit - we still use the old compiler for stable releases

2021-11-22 08:28 UTC, amilcarlucas commented
All CI tests pass. :)

2021-11-22 08:33 UTC, rmackay9 commented
@amilcarlucas,

I suspect that the CI tests always use the latest compiler regardless of version so we may need to more specifically test that it builds using the correct compiler.

2021-11-22 08:35 UTC, amilcarlucas requested changes

2021-11-22 08:35 UTC, amilcarlucas commented on ArduCopter/ReleaseNotes.txt
> +4) Bug Fixes
```suggestion
4) Added support for FETtec One wire protocol - a single UART serial ESC with telemetry
5) Bug Fixes
```

2021-11-22 11:13 UTC, rmackay9 commented
@andyp1per suggests we should add these bug fixes as well

- https://github.com/ArduPilot/ardupilot/pull/19166
- https://github.com/ArduPilot/ardupilot/pull/19246

2021-11-23 07:07 UTC, rmackay9 commented on ArduCopter/ReleaseNotes.txt
> +4) Bug Fixes
added, thanks

2021-11-24 04:42 UTC, rmackay9 commented
@tridge has offered to check that this fits with the older compiler that we use for 4.1 so once that is confirmed we will merge this.

2021-11-29 10:02 UTC, merged