Copter: Add support for MAV_CMD_DO_PAUSE_CONTINUE in GUIDED mode
ArduPilot/ardupilot pull request #19379
Opened 2021-11-27 20:18 UTC by mustafa-gokce

This PR adds pause/continue methods to mode auto and mode guided.
Pause/continue logic of the DO_FOLLOW and DO_REPOSITION commands in guided mode is implemented.
I will also implement other commands' pause/continue logic.

2021-11-27 20:23 UTC, peterbarker commented
I asked @mustafa-gokce to create this so we can discuss it more easily.

I'm currently objecting to the current implementation as we can enter and use guided mode in ways *other* than receiving a mavlink command (e.g. via scripting).

There are two ways I can currently think of to do this better
 - have another SubMode of "pause" - but will we need to work out how to reinitialise old submode when we `continue`?
 - scribble down the values of every entry point into guided and have an enumeration for which one to call with we `continue`

@rmackay9 's input required.

2021-12-01 07:59 UTC, rmackay9 commented
I guess we should clarify what behaviour we want in Guided mode's various sub modes.

In the case where the pilot has triggered a takeoff or has provided a Location I think pausing and the restoring the target makes sense.  For the submodes where the vehicle is constantly being sent new targets from a Lua script or a companion computer we probably do **not** want to restore the old target.  Any submode with a timeout should not have the previous target restarted.

Another question is do we want to reject new commands passed in (from a Lua script or companion computer) if the vehicle has been "paused" in Guided mode?  I'm unsure if rejecting new commands would be useful or just annoying.

2021-12-01 09:30 UTC, mustafa-gokce commented
> Any submode with a timeout should not have the previous target restarted.

@rmackay9 I thought it too but didn't sure about it. If a submode is without a timeout, should restart the behavior (should disable the mode for continuing or reissuing again). And also we should not resume the second latest submode command that has a timeout, I think.
> Another question is do we want to reject new commands passed in (from a Lua script or companion computer) if the vehicle has been "paused" in Guided mode? I'm unsure if rejecting new commands would be useful or just annoying.

@rmackay9 I think we should reset pause/continue when a new command is received (or we can say, started a new submode that is started by the method other than continuing) so the command will be accepted anyway.

I am open to all other suggestions, @rmackay9, @peterbarker.
Thanks for your time...

2021-12-01 11:13 UTC, mustafa-gokce commented
With 51801b3, I removed support for pause/continue of the submodes that have no timeout.
Also without pausing first, any of the previous submodes will not be resumed.
Pausing a submode does not cause rejecting new commands.
In a mode or submode change, pause/continue will be restarted so resume can be only issued if submode is paused first.

2021-12-07 02:36 UTC, peterbarker requested changes
Would be nice to get an autotest for this.

2021-12-07 02:36 UTC, peterbarker commented on ArduCopter/mode_auto.cpp
> +    mission.stop();
I wonder if we should do this *after* doing loiter_start....

2021-12-07 02:36 UTC, peterbarker commented on ArduCopter/Copter.h
> +    // previous commands from GCS
This state should all be contained within the ModeGuided class.

Same with prevCmd enum

2021-12-07 02:36 UTC, peterbarker commented on ArduCopter/mode.cpp
> +    prev_cmd.paused = false;
Should go into Guided's "exit_mode" code.

2021-12-07 02:36 UTC, peterbarker commented on ArduCopter/mode_guided.cpp
> +    copter.prev_cmd.paused = false;
```suggestion
    prev_cmd.prev_cmd_type = Copter::PrevCmd::DO_USER_TAKEOFF_START;
    prev_cmd.takeoff_alt_cm = takeoff_alt_cm;
    prev_cmd.paused = false;
```

similarly elsewhere

2021-12-07 02:36 UTC, peterbarker commented on ArduCopter/mode_guided.cpp
> +        }
```suggestion
```

Omitting this forces someone who adds a PrevCmd entry to deal with the continue case.  Generally when a value is constrained to being within an enumeration then we omit the `default` clause.

2021-12-07 08:36 UTC, mustafa-gokce commented
> Would be nice to get an autotest for this.

Done.

2021-12-07 11:24 UTC, peterbarker commented on ArduCopter/mode_guided.cpp
> +// previous commands from GCS
```suggestion
// current command information
```

2021-12-07 11:26 UTC, peterbarker commented
Looking good.  Need @rmackay9 to weigh in again now.  He would probably like an outline of how you've tested this.

2021-12-07 12:18 UTC, mustafa-gokce commented
To test this feature in GUIDED mode, I created an autotest.
What it does is:
1. Takeoff to an altitude in GUIDED mode.
2. Send move to a location command in GUIDED mode.
3. Wait some time to move away from home.
4. Send pause command.
5. Wait for ground speed to be zero.
6. Send continue command.
7. Wait vehicle to reach its destination.
8. Land and disarm.

2022-01-04 23:32 UTC, peterbarker requested changes
Please have a look at https://github.com/ArduPilot/ardupilot/commit/77fcef6ffedcb7ea32bf523827d79eb6ed707ced

It adds some degree of type-safety to this recording/replaying of parameters to the functions.  It's only half done; eventually no destination components should exist outside the per-destination-type structs.

2022-01-04 23:32 UTC, peterbarker commented on ArduCopter/mode_guided.cpp
> +    if(init(true)) {
```suggestion
    if (init(true)) {
```

2022-01-04 23:32 UTC, peterbarker commented on Tools/autotest/arducopter.py
> +        destination = mavutil.location(-35.361286, 149.161107, 30, 0)
This shouldn't really be hard-coded.  You can get a relative position with 
```
                loc = self.home_relative_loc_ne(n, e)
```

2022-01-04 23:32 UTC, peterbarker commented on Tools/autotest/arducopter.py
> +
I'd like to see more of the different destination types tested in here, and that changing out of guided / back into guided works appropriately.

2022-01-29 22:05 UTC, mustafa-gokce commented on ArduCopter/GCS_Mavlink.cpp
> +#if defined(MODE_AUTO_ENABLED) && defined(MODE_GUIDED_ENABLED)
I am not sure whether
`#if defined(MODE_GUIDED_ENABLED) && defined(MODE_AUTO_ENABLED)
`
or
`#if defined(MODE_GUIDED_ENABLED) || defined(MODE_AUTO_ENABLED)`

2022-02-24 12:22 UTC, closed without merging