Cube Black, Purple, Solo: Set EKF_IMU_MASK_DEFAULT 7
ArduPilot/ardupilot pull request #19431
Opened 2021-12-04 06:54 UTC by hendjoshsr71

This PR is for discussion not merging.

In https://github.com/ArduPilot/ardupilot/pull/19392. I made Cube Orange & Yellow have a default EKF_IMU_MASK_DEFAULT 7 to use all IMUs.

Initially I had set this for every Cube type but removed it from Cube Black, Purple, & Solo with constrained resources (RAM and CPU) based on feedback.

I'm bringing this back for discussion due to the insistence of the manufacturer to include this see the comment [here](https://github.com/ArduPilot/ardupilot/pull/19392#issuecomment-982550526) from @proficnc.

The reason for forcing the issue is due to the possibility of having the Isolated IMUs flex connector fail/disconnect and thus the aircraft have no viable IMUs because the third non-isolated IMU is not being used. (This type of failure recently happened to a development only cube orange of mine.) 

**Issue: Resource Utilization will be too high and features need to be removed** 
IMU_MASK 7: Users who are already resource constrained will need to go in and change this back or remove features. But will do so after being very unhappy and confused. It would need another campaign to let users know this is happening. (Yes, they should already be using EKF IMU_MASK 7 but many are not.  And safety vs resource utilization is up to the user) However, defaults in my opinion should be conservative in terms of safety. 

**Compromise?** 
An option could be defaulting to using say IMU_MASK 5 or 6 be to provide for some safety for the case where the vibe isolated IMUs fail. This would not take additional computational resources? But this then compromises the EKF solution for one lane somewhat?

There really isn't a great solution either way...

2021-12-07 00:14 UTC, tridge requested changes

2021-12-07 00:14 UTC, tridge commented on libraries/AP_HAL_ChibiOS/hwdef/CubeBlack/hwdef.dat
> +define HAL_EKF_IMU_MASK_DEFAULT 7
F427 doesn't have the ram or cpu to support this

2021-12-07 00:15 UTC, tridge commented
it already fails over to the 3rd IMU correctly, and even handles the biases correctly

2021-12-14 08:42 UTC, hendjoshsr71 commented
Closing.

Relevant PR referenced above that flight tested IMU failover is here, https://github.com/ArduPilot/ardupilot/pull/11720

2021-12-14 08:42 UTC, closed without merging