AP_InertialSensor: added support for IIM-42652 and ICM-40605 sensors
ArduPilot/ardupilot pull request #19506
Opened 2021-12-13 04:45 UTC by QioTek

AP_InertialSensor: added support for IIM-42652 and ICM-40605 sensors

2021-12-13 18:36 UTC, hendjoshsr71 requested changes
LGTM: besides the small whitespace errors

I will take it to the call to make sure everyone else is ok with the structure.

2021-12-13 18:36 UTC, hendjoshsr71 commented on libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.cpp
> +
nitpick: extra white space

2021-12-13 18:36 UTC, hendjoshsr71 commented on libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.cpp
> +
nitpick: extra white space

2021-12-13 18:36 UTC, hendjoshsr71 commented on libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.h
> +
nitpick: extra white space

2021-12-13 18:36 UTC, hendjoshsr71 commented on libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.h
> -    /* Read samples from FIFO */
nitpick: you removed one space here

2021-12-13 18:42 UTC, hendjoshsr71 commented
Oh one important GIT note. You should never commit changes to your `master branch` like you did here. You should create a branch `add_iim42652_imu` for example and commit to that branch.

2021-12-13 22:40 UTC, tridge commented
I have fixed up the whitespace issues

2021-12-13 22:46 UTC, tridge approved these changes

2021-12-14 00:38 UTC, merged

2021-12-15 03:06 UTC, QioTek commented
> Oh one important GIT note. You should never commit changes to your `master branch` like you did here. You should create a branch `add_iim42652_imu` for example and commit to that branch.

Thanks for reminding me. I'll create a new branch next time.