AP_InertialSensor: added support for more ADIS IMUs
ArduPilot/ardupilot pull request #19513
Opened 2021-12-14 02:49 UTC by tridge

support 32 bit delta angles and velocities

2021-12-22 07:56 UTC, andyp1per approved these changes

2021-12-22 08:00 UTC, andyp1per requested changes

2021-12-22 08:00 UTC, andyp1per commented on libraries/AP_InertialSensor/AP_InertialSensor_Backend.cpp
> +#if 0
debug flag?

2021-12-27 22:20 UTC, tridge commented on libraries/AP_InertialSensor/AP_InertialSensor_Backend.cpp
> +#if 0
fixed

2021-12-27 22:20 UTC, tridge commented on libraries/AP_InertialSensor/AP_InertialSensor_Backend.cpp
> +#if 1
fixed, thanks

2021-12-27 22:29 UTC, tridge commented on libraries/AP_InertialSensor/AP_InertialSensor_Backend.cpp
> +  handle a delta-angle sample from the backend. This assumes FIFO style sampling and
why notch changes? The new delta_angle function does handle the notch calls

2021-12-27 22:29 UTC, tridge commented on libraries/AP_InertialSensor/AP_InertialSensor_Backend.cpp
> + */
done

2021-12-27 22:29 UTC, tridge commented on libraries/AP_InertialSensor/AP_InertialSensor_Backend.cpp
> +#if 0
fixed

2021-12-27 22:30 UTC, tridge commented on libraries/AP_InertialSensor/AP_InertialSensor_Backend.cpp
> +#if 1
fixed

2021-12-29 07:24 UTC, peterbarker approved these changes

2021-12-29 07:25 UTC, merged