Rover: Add support for MAV_CMD_DO_PAUSE_CONTINUE command in GUIDED and AUTO modes
ArduPilot/ardupilot pull request #19552
Opened 2021-12-17 14:53 UTC by mustafa-gokce

Implemented MAV_CMD_DO_PAUSE_CONTINUE command handling in GUIDED and AUTO modes in Rover.
Can be tested using:
`./Tools/autotest/autotest.py build.Rover test.Rover.PauseContinue --map`
`./Tools/autotest/autotest.py build.Rover test.Rover.PauseContinue --map`

2022-01-05 01:00 UTC, peterbarker requested changes
Still looks good.

Same comment that I mentioned in the Copter PR about using structures to record information for each type of destination applies.

2022-01-05 01:00 UTC, peterbarker commented on Rover/mode_auto.cpp
> +    // stop the mission
pointless comment

2022-01-05 01:00 UTC, peterbarker commented on Rover/mode_auto.cpp
> +    // resume the mission
pointless comment

2022-01-19 07:26 UTC, tridge commented
@rmackay9 needs approval from you

2022-02-01 11:45 UTC, mikerob commented
Hi, interested in this functionality but have a couple of questions:
1) When you pause, does the vehicle continue following the waypoint path until it stops?  Does it gracefully handle passing waypoints as it slows?
2) When it resumes, does it return to the WP_SPEED or the last DO_CHANGE_SPEED?

2022-02-01 12:14 UTC, mustafa-gokce commented
@mikerob 

> 1. When you pause, does the vehicle continue following the waypoint path until it stops?  Does it gracefully handle passing waypoints as it slows?

No. It is just an interim solution for pausing. It should be implemented with SCurves later for gracefully stopping along the path.



> 2\. When it resumes, does it return to the WP_SPEED or the last DO_CHANGE_SPEED?

I need to test this but probably resumes with the last DO_CHANGE_SPEED since the above logic doesn't enforce, save or change anything related to speed.

2022-02-01 12:28 UTC, mustafa-gokce commented on Rover/mode_guided.cpp
> +    prev_cmd.u.set_desired_location.next_leg_bearing_cd = next_leg_bearing_cd;
I forgot to save this, so updated the PR.

2022-09-20 10:33 UTC, closed without merging