KDECAN: rewrite driver to use CANSensor and add to AP_Periph
ArduPilot/ardupilot pull request #19629
Opened 2021-12-29 07:10 UTC by magicrub

rewrite driver to use CANSensor and add to AP_Periph

2021-12-29 19:14 UTC, magicrub commented
there's a few minor tweaks I need to apply to restrict it from compiling on non-vehicles and such

2022-01-03 02:16 UTC, peterbarker requested changes
As you say, there are per-vehicle problems here.  Last time I tried to make an `AP_KDECAN_ENABLED` define I discovered that there was a dependence on a motors library which not all vehicles supplied....

Sorry, didn't look at this in depth at all.  You've correctly tagged Sid :-)

2022-01-03 02:16 UTC, peterbarker commented on libraries/AP_KDECAN/AP_KDECAN.h
> +#ifndef HAL_KDECAN_ENABLED
```suggestion
#ifndef AP_KDECAN_ENABLED
```

2022-01-03 02:16 UTC, peterbarker commented on libraries/AP_KDECAN/AP_KDECAN.h
> +#define KDECAN_USE_EVENTS (CONFIG_HAL_BOARD == HAL_BOARD_CHIBIOS && CH_CFG_USE_EVENTS == TRUE)
```suggestion
#define AP_KDECAN_USE_EVENTS (CONFIG_HAL_BOARD == HAL_BOARD_CHIBIOS && CH_CFG_USE_EVENTS == TRUE)
```

2022-01-03 03:19 UTC, rmackay9 commented
We should be sure that this is tested on real hardware as well before merging.

2022-01-03 21:03 UTC, magicrub commented
> We should be sure that this is tested on real hardware as well before merging.

I have two that I've tested with on the same network. What I haven't tested thoroughly is the enumeration stuff but I've tested it with how I think it's supposed to work. Would be nice to get someone else who uses KDECAN enumeration to test that

2022-01-03 21:13 UTC, magicrub commented on libraries/AP_KDECAN/AP_KDECAN.h
> +#define KDECAN_USE_EVENTS (CONFIG_HAL_BOARD == HAL_BOARD_CHIBIOS && CH_CFG_USE_EVENTS == TRUE)
sure, that's a reasonable thing to do.

2022-01-03 21:13 UTC, magicrub commented on libraries/AP_KDECAN/AP_KDECAN.h
> +#ifndef HAL_KDECAN_ENABLED
sure, that's a reasonable thing to do.

2022-01-03 23:17 UTC, magicrub commented on libraries/AP_KDECAN/AP_KDECAN.h
> +#ifndef HAL_KDECAN_ENABLED
fixed

2022-01-03 23:17 UTC, magicrub commented on libraries/AP_KDECAN/AP_KDECAN.h
> +#define KDECAN_USE_EVENTS (CONFIG_HAL_BOARD == HAL_BOARD_CHIBIOS && CH_CFG_USE_EVENTS == TRUE)
fixed

2022-01-03 23:21 UTC, magicrub commented
> Last time I tried to make an AP_KDECAN_ENABLED define I discovered that there was a dependence on a motors library which not all vehicles supplied....

I just added a self-defining enable in AP_Motors_Class.cpp so this sort of thing can get abstracted and detected at runtime. It causes a potential compile-order issue but it's at least working right now. Better solution would be for waf to detect if AP_Motors is included in the build and then set the define.. but this already has a bit of feature-creep as it is

Now my KDECAN has this in the arming check:
#if defined(AP_MOTORS_ENABLE) && AP_MOTORS_ENABLE == 1

2022-01-04 03:15 UTC, magicrub commented
I've pulled out some AP_Perioph infrastructure changes into it's own PR https://github.com/ArduPilot/ardupilot/pull/19672 so we can see more of what adding KDECAN is will less feature-creep infrastructure changes

2023-03-24 05:49 UTC, magicrub commented
closing in favor of https://github.com/ArduPilot/ardupilot/pull/23238

2023-03-24 05:49 UTC, closed without merging