Tidy Notch filter logging
ArduPilot/ardupilot pull request #19642
Opened 2021-12-31 04:06 UTC by peterbarker

This was a bit weird, with the vehicle calling the library and the library calling the vehicle.  This makes it less weird.

Tested in SITL by running the GyroFFT test and checking the logs still contained the `FTN` message.

Better still would be to pass the log-bitmask-bit (e.g. `MASK_LOG_CTUN`) into the AP_InertialSensor library and have it do the relevant logging.  It's a pattern we use elsewhere.

2021-12-31 09:21 UTC, andyp1per approved these changes
It was weirder before

2021-12-31 16:53 UTC, hendjoshsr71 approved these changes
LGTM.

2022-01-04 00:17 UTC, tridge requested changes

2022-01-04 00:17 UTC, tridge commented on libraries/AP_InertialSensor/AP_InertialSensor_Logging.cpp
> +    AP::logger().Write(
should be WriteStreaming

2022-01-04 01:17 UTC, peterbarker commented on libraries/AP_InertialSensor/AP_InertialSensor_Logging.cpp
> +    AP::logger().Write(
Done

2022-01-05 05:34 UTC, merged