AP_Arming: Implement ARMING_REQUIRE 3 aka AUTO_ARM_FORCE_CHECKS
ArduPilot/ardupilot pull request #19645
Opened 2021-12-31 14:15 UTC by Jaaaky

This mode tries to automatically arm as soon as all checks are passed
    It run on a low priority thread to avoid imu_reset/possible watchdog
    reset when INS_FAST_SAMPLE is enabled

I tried to keep changes as minimal as possible that's why I used is_armed() as a start point.

Suggestions are welcome.

2021-12-31 14:17 UTC, Jaaaky commented
I could theoretically call arm() directly with bouncing but found that this causes stuck threads on actual hardware as mentioned.

2021-12-31 15:46 UTC, IamPete1 commented
Really not a fan of this. it means that the vehicle will suddenly arm with zero notice. As implemented It also means that you can't disarm, it will just arm again. 

What is the use case?

2021-12-31 16:04 UTC, Jaaaky commented
> Really not a fan of this. it means that the vehicle will suddenly arm with zero notice. As implemented It also means that you can't disarm, it will just arm again.

I think the same objection can be said for ARMING_REQUIRE 0 , though it's there.
And actually you can always keep Safety switch on - vehicle is safe -

> What is the use case?

It's so useful for:
1. simulation, it's really time saving, I do not have to skip all checks and start with EKF getting crazy.
2. vehicles with ICE, where you simply can wait for the ARM notification so you can start the engine that its vibration may delay ARMing checks too much.
3. Fully autonomous mapping mission, where you simply wait until everything is ready then simply press Safety switch and let it go

2021-12-31 17:32 UTC, IamPete1 commented
> I think the same objection can be said for ARMING_REQUIRE 0 , though it's there.

Not the same at all. In that case you know it is always going to be armed if it is powered up. So you know to always treat it the same. The danger is it going from disarmed to armed with no warning. 

1. For the simulation use case you can just use AHRS type 10, turn off the EKF and never have to wait for checks.

2. What arming checks would the vibration delay?

3. The safety switch should not be used as a substitute for starting the mission, that would be very dangerous. For that to work the vehicle would have to be armed and actively trying to take-off, it will go from 0 to high throttle as soon as the button is pressed, there will be no time for the operator to get clear. In that case you want actually want button arming which is already possible via AP_Button.

2021-12-31 17:34 UTC, IamPete1 requested changes
I don't think this is safe.

2021-12-31 21:24 UTC, khancyr commented
I agree that the first use case can be interesting, but we have now scripting and enough pymavlink example to do this.

But as I said on discord it put a hight risk on usage specially as user will end setting this as default.
We already had the case with ARMING_REQUIRE=0 and it is always a pain to manage this case.

Here we also go auto rearm after disarm what will put everything at risk. I didn't check mission with takeoff but I expect that the mission will now loop infinitivly until battery failsafe.

The arming checks and all the arming sequence is design to be safe and try to prevent accident. This will mostly bypass safety for usage that are not that worthy.
I can provide a pymalink script on need to auto arm, or somebody will be able to do the same in LUA, but I don't think we should set this as an option.

2022-01-03 12:23 UTC, Jaaaky commented
I still see it useful and as being an option it cannot be considered as unsafe.. 
ARMING_REQUIRE = 0 could be more dangerous as it can allow the vehicle to launch in a very bad state - gyro badly calibrated for example - and this can be much more dangerous than my considerably safe implementation - considering the changes suggested to make it safer - of automatically arming 

I think 2 changes should be applied to it:
1. Make sure it does not re-arm - arming automatically only once after startup as long as vehicle was never armed before
2. Safety switch is forced to ON state - vehicle is safe - if this option is used

2022-01-04 00:21 UTC, tridge commented
i'm not a fan of this, I'd prefer to remove ARMING_REQUIRE

2022-01-04 00:22 UTC, IamPete1 commented
This is the equivalent lua script:
```
function update() 
  if arming:is_armed()
    return -- kill script after first arm
  end
  arming:arm() -- try and arm every 5 seconds
  return update, 5000
end
return update, 10000```

2022-01-04 00:24 UTC, rmackay9 commented
Looks like Peter Hall has provided a lua script to accomplish the same thing so I think we should close this.  Sorry, it's just that safety is something we really need to be careful of.

2022-01-04 00:24 UTC, closed without merging