Kakute H7 Mini
ArduPilot/ardupilot pull request #19646
Opened 2021-12-31 17:24 UTC by andyp1per

2022-01-02 21:46 UTC, tridge approved these changes

2022-01-02 21:47 UTC, tridge requested changes
thanks!
needs some commits squashing and added to Tools/scripts/board_list.py

2022-01-02 22:46 UTC, andyp1per commented
> needs some commits squashing and added to Tools/scripts/board_list.py

Also needs testing, LOL - I haven' received the board yet, Tuesday hopefully ...

2022-01-10 23:58 UTC, tridge approved these changes

2022-01-10 23:58 UTC, merged

2022-01-13 11:02 UTC, bys1123 commented
Thanks, small ardupilot drone available again.