Plane: quadplane: add transition failure action
ArduPilot/ardupilot pull request #19664
Opened 2022-01-03 19:53 UTC by IamPete1

This adds a new param `Q_TRANS_FAIL_ACT`, this allows the user to select either QLAND, QRTL or warning only actions to take when `Q_TRANS_FAIL` time runs out. 

The force complete option still works for tiltrotors, they will now take the new action if the ground speed threshold is not met.

I have added a new case to QRTL to jump straight to POS2 if the mode reason is `VTOL_FAILED_TRANSITION`.

Tested in SITL by setting `THR_MAX` 0

2022-01-05 08:15 UTC, tridge requested changes

2022-01-05 08:15 UTC, tridge commented on ArduPlane/quadplane.cpp
> +        ((now - transition_start_ms) > ((uint32_t)quadplane.transition_failure.timeout * 1000))) {
dodgy integer wrap ....

2022-01-05 08:20 UTC, IamPete1 commented on ArduPlane/quadplane.cpp
> +        ((now - transition_start_ms) > ((uint32_t)quadplane.transition_failure.timeout * 1000))) {
fixed

2022-01-06 13:20 UTC, IamPete1 commented
reworked so it now works if the action is QRTL and the transition fails in QRTL, previously it would skip the mode change and therefore miss the special case init. Now is always forces to QPOS1.

2022-01-11 00:01 UTC, tridge approved these changes

2022-01-11 00:02 UTC, merged