Tools: add script returning build options
ArduPilot/ardupilot pull request #19667
Opened 2022-01-03 22:32 UTC by peterbarker

2022-01-04 00:54 UTC, amilcarlucas requested changes

2022-01-04 00:54 UTC, amilcarlucas commented on Tools/scripts/build_options.py
> +    Feature('Other', 'AC_OAPATHPLANNER', 'AC_OAPATHPLANNER_ENABLED', 'Enable Object Avoidance Path Planner', 0, None),
```suggestion
    Feature('Safety', 'AC_OAPATHPLANNER', 'AC_OAPATHPLANNER_ENABLED', 'Enable Object Avoidance Path Planner', 0, None),
```

2022-01-04 00:54 UTC, amilcarlucas commented on Tools/scripts/build_options.py
> +    Feature('Other', 'GENERATOR', 'HAL_GENERATOR_ENABLED', 'Enable Generator', 0, None),
```suggestion
    Feature('ICE', 'GENERATOR', 'HAL_GENERATOR_ENABLED', 'Enable Generator', 0, None),
```

2022-01-04 00:54 UTC, amilcarlucas commented on Tools/scripts/build_options.py
> +    Feature('Other', 'TORQEEDO', 'HAL_TORQEEDO_ENABLED', 'Enable Torqeedo Motors', 0, None),
```suggestion
    Feature('ESC', 'TORQEEDO', 'HAL_TORQEEDO_ENABLED', 'Enable Torqeedo Motors', 0, None),
    Feature('ESC', 'FETTEC_ONEWIRE', 'AP_FETTEC_ONEWIRE_ENABLED', 'Enable FETtec OneWire ESCs', 0, 'HAL_WITH_ESC_TELEM'),
    Feature('ESC', 'ESC_TELEMETRY', 'HAL_WITH_ESC_TELEM', 'Enable ESC telemetry', 0, None),
```

2022-01-04 01:14 UTC, amilcarlucas requested changes

2022-01-04 01:14 UTC, amilcarlucas commented on Tools/scripts/build_options.py
> +    Feature('Other', 'SOARING', 'HAL_SOARING_ENABLED', 'Enable Soaring', 0, None),
```suggestion
    Feature('Plane', 'SOARING', 'HAL_SOARING_ENABLED', 'Enable Soaring', 0, None),
```

2022-01-04 01:14 UTC, amilcarlucas commented on Tools/scripts/build_options.py
> +    Feature('Other', 'DEEPSTALL', 'HAL_LANDING_DEEPSTALL_ENABLED', 'Enable Deepstall Landing', 0, None),
```suggestion
    Feature('Plane', 'DEEPSTALL', 'HAL_LANDING_DEEPSTALL_ENABLED', 'Enable Deepstall Landing', 0, None),
```

2022-01-04 01:14 UTC, amilcarlucas commented on Tools/scripts/build_options.py
> +    Feature('Other', 'SPRAYER', 'HAL_SPRAYER_ENABLED', 'Enable Sprayer', 0, None),
```suggestion
    Feature('Payload', 'SPRAYER', 'HAL_SPRAYER_ENABLED', 'Enable Sprayer', 0, None),
```

2022-01-04 01:14 UTC, amilcarlucas commented on Tools/scripts/build_options.py
> +    Feature('Other', 'GRIPPER', 'GRIPPER_ENABLED', 'Enable Gripper', 0, None),
```suggestion
    Feature('Payload', 'GRIPPER', 'GRIPPER_ENABLED', 'Enable Gripper', 0, None),
```

2022-01-04 01:14 UTC, amilcarlucas commented on Tools/scripts/build_options.py
> +    Feature('Other', 'WINCH', 'WINCH_ENABLED', 'Enable Winch', 0, None),
```suggestion
    Feature('Payload', 'WINCH', 'WINCH_ENABLED', 'Enable Winch', 0, None),
```

2022-01-04 03:35 UTC, peterbarker commented
@amilcarlucas thanks for the review.

I would prefer not to change the data I'm moving from the other tree as part of this PR.  I think your suggestions there are good - maybe another PR against master once this is merged?

2022-01-04 09:46 UTC, amilcarlucas commented
OK.

2022-01-04 13:37 UTC, khancyr commented on Tools/scripts/build_options.py
> +    Feature('Other', 'AC_OAPATHPLANNER', 'AC_OAPATHPLANNER_ENABLED', 'Enable Object Avoidance Path Planner', 0, None),
Avoidance/avoid, but not safety !

2022-01-04 21:19 UTC, Hwurzburg commented
Thanks for completing this

2022-01-05 01:36 UTC, peterbarker commented
@Hwurzburg were you able to test?

2022-01-05 08:25 UTC, tridge approved these changes

2022-01-05 08:25 UTC, merged