1MB plane build reduce
ArduPilot/ardupilot pull request #19696
Opened 2022-01-05 12:01 UTC by magicrub

For Plane this saves 14k Flash on fmuv2

Mega squash of a bunch of # if stuff to isolate a few libraries. @peterbarker Discuss! Lets figure out what we want and such and then I'll bring them out into individual library commits

This is part of the effort in https://github.com/ArduPilot/ardupilot/issues/19068

2022-01-05 18:46 UTC, hendjoshsr71 commented
Output for Durandal Build Size: Rover & Tracker increased by 5kB...?
![image](https://user-images.githubusercontent.com/69225461/148268185-62f6b17b-fe59-43c3-9afd-9d5522b7d6d7.png)

Just a note the difference between boards with  `HAL_MINIMIZE_FEATURES 1` && <1MB and those just <1MB is around -7kB

There are only 9 boards that define `HAL_MINIMIZE_FEATURES 1`. Are we getting closer to a point where HAL_MINIMIZE_FEATURES  should just mean anything less <=1MB for certain vehicles?

2022-01-05 19:01 UTC, hendjoshsr71 commented
Trolling through the list of every where we have `!HAL_MINIMIZE_FEATURES` I'd surmise most of those items could become `BOARD_SIZE > 1024` instead.

There are a few majors ones that should not: OSD, DLVR sensors, Telemetry protocols

2022-01-05 19:32 UTC, tridge requested changes
thanks Tom!
A few things to do:
 - each of the options where we now disable needs to be in the custom build server build list in Tools/scripts/build_options.py so users have a way to re-enable if needed
 - we need to understand why the build size on 2M boards is reduced. What code has been removed?

2022-01-05 21:28 UTC, peterbarker commented on ArduPlane/config.h
> + # define ADVANCED_FAILSAFE (!HAL_MINIMIZE_FEATURES && BOARD_FLASH_SIZE > 1024)
We'd like to remove `HAL_MINIMIZE_FEATURES`.... 

Like parachute, I'm not sure we should start to compile out safety-critical features.

2022-01-05 21:35 UTC, peterbarker requested changes
Would be nice to not increase the usage of `MINIMIZE_FEATURES`.

2022-01-05 21:35 UTC, peterbarker commented on libraries/AP_KDECAN/AP_KDECAN.cpp
> +#if defined(AP_MOTORS_ENABLE) && AP_MOTORS_ENABLE
```suggestion
#if defined(AP_MOTORS_ENABLED) && AP_MOTORS_ENABLED
```

2022-10-11 00:28 UTC, magicrub commented
This is stale.. closing

2022-10-11 00:28 UTC, closed without merging