Add support for better timing with DroneCAN GPS
ArduPilot/ardupilot pull request #19824
Opened 2022-01-18 10:48 UTC by bugobliterator

2022-01-18 19:20 UTC, nkruzan commented on Tools/AP_Periph/AP_Periph.h
> +    bool saw_lock_once;
nitpick - I'd rather see this as saw_gps_lock_once

2022-01-19 07:15 UTC, tridge requested changes

2022-01-19 07:15 UTC, tridge commented on libraries/AP_GPS/AP_GPS.cpp
> +            tnow = state[instance].last_corrected_gps_time_us/1000;
1000U

2022-01-19 07:15 UTC, tridge commented on libraries/AP_GPS/AP_GPS_UAVCAN.cpp
> +#if 0
maybe #if GPS_PPS_EMULATION

2022-01-19 07:51 UTC, tridge requested changes

2022-01-19 07:51 UTC, tridge commented on libraries/AP_GPS/AP_GPS_UAVCAN.cpp
> +    next_toggle = (cb.msg->timestamp.usec) + (1000000 - ((cb.msg->timestamp.usec) % 1000000));
unsigned

2022-01-19 07:51 UTC, tridge commented on libraries/AP_GPS/GPS_Backend.cpp
> +            float lag_s = (now - (state.last_corrected_gps_time_us/1000)) * 0.001;
unsigned

2022-01-19 07:52 UTC, tridge commented
happy to merge when the trivial changes are fixed and passes CI

2022-01-20 06:26 UTC, tridge approved these changes

2022-01-20 06:26 UTC, merged