AP_ROMFS: Enable/fix mavlink ftp ListDirectory for @ROMFS top level
ArduPilot/ardupilot pull request #19865
Opened 2022-01-24 06:29 UTC by pap9ck

The AP_ROMFS had a dir list method added a while back, but it does not work to show the top level files in the ROMFS. For example, the mavproxy command "ftp list @ROMFS" or "ftp list @ROMFS/" doesn't work. The existing code expects a directory name after the backend @ROMFS/ string, e.g @ROMFS/models. 

With the suggested change, "ftp list @ROMFS" will return a list of all files in the romfs embedded file. The previous behavior is retained as well and "ftp list @ROMFS/models" will only list the files with a name starting with models/ and stripping the directory part.

2022-03-07 22:43 UTC, khancyr requested changes
That is interesting and usefull.
it is working as advertised.

I am not qualifed enough to review this thus.
The commit would need to be splitted and have the lib name added on the start of the commit message. Using Tools/gittools/git-subsystems-split  would do it for you

2022-04-06 07:27 UTC, tridge requested changes

2022-04-06 07:27 UTC, tridge commented on libraries/AP_Filesystem/AP_Filesystem.cpp
> +    { "@ROMFS", fs_romfs },
it would be nicer to fix it so we don't need to list it twice. Just list it as @ROMFS and cope with the '/'
we should fix @SYS in the same way too

2024-03-17 14:13 UTC, IamPete1 commented
Closed by https://github.com/ArduPilot/ardupilot/pull/26225

2024-03-17 14:13 UTC, closed without merging