hwdef: Create f405-MatekAirspeed
ArduPilot/ardupilot pull request #19906
Opened 2022-01-28 04:21 UTC by hendjoshsr71

This creates a hwdef specifically for the f405-Matek DLVR sensor. Previously, they shared the same hwdef. Note the airspeed sensor shares a board ID with the GPS.  @MATEKSYS 

The benefit of this is we can turn off by default some of the enabled functionality such as the compass and battmonitor so we do not flood the CAN network with traffic for sensors that aren't attached. A user still can go into the DroneCAN GUI Tool to change use a BATT_Monitor when desired.

Also added are a few defines so that disabling baro and compass can be done from the hwdef file.
Cleaned up some of the duplication in the GPS's defaults.parm

Note to set the default rangefinder port correctly #19905 is needed.

![image](https://user-images.githubusercontent.com/69225461/151486643-dd869125-df50-4613-b5a9-1ac5c089b3cc.png)

2022-02-02 08:41 UTC, tridge requested changes

2022-02-02 08:41 UTC, tridge commented on libraries/AP_HAL_ChibiOS/hwdef/f405-MatekAirspeed/defaults.parm
> +OUT7_FUNCTION 120
the real board doesn't have a neopixel

2022-02-02 08:41 UTC, tridge commented on libraries/AP_HAL_ChibiOS/hwdef/f405-MatekGPS/hwdef.dat
> +# disable ADSB by default
lets remove ADSB from this build

2022-02-02 09:14 UTC, hendjoshsr71 commented on libraries/AP_HAL_ChibiOS/hwdef/f405-MatekAirspeed/defaults.parm
> +OUT7_FUNCTION 120
Removed

2022-02-02 09:14 UTC, hendjoshsr71 commented on libraries/AP_HAL_ChibiOS/hwdef/f405-MatekGPS/hwdef.dat
> +# disable ADSB by default
Removed

2022-02-07 23:40 UTC, tridge approved these changes

2022-02-07 23:41 UTC, merged