AC_Avoidance: get Vector3f when checking all components of relpos
ArduPilot/ardupilot pull request #19927
Opened 2022-01-29 13:11 UTC by peterbarker

2022-01-29 20:15 UTC, hendjoshsr71 requested changes
looks good with the small fixup

2022-01-29 20:15 UTC, hendjoshsr71 commented on libraries/AC_Avoidance/AP_OADatabase.cpp
> +        if (current_pos.length_xy() < AP_OADATABASE_DISTANCE_FROM_HOME) {
```suggestion
        if (current_pos.xy().length() < AP_OADATABASE_DISTANCE_FROM_HOME) {
```

2022-01-30 03:42 UTC, peterbarker commented on libraries/AC_Avoidance/AP_OADatabase.cpp
> +        if (current_pos.length_xy() < AP_OADATABASE_DISTANCE_FROM_HOME) {
Fixed

2022-01-30 05:56 UTC, hendjoshsr71 approved these changes

2022-01-31 00:25 UTC, peterbarker commented
Tested in SITL by enabling the RPi simulation and checking avoidance still worked in guided / _min_alt is honoured

2022-02-02 07:22 UTC, rishabsingh3003 approved these changes

2022-02-02 08:09 UTC, merged