AP_Filesystem: Change the judgment null of methods that return nullptr
ArduPilot/ardupilot pull request #19925
Opened 2022-01-29 13:06 UTC by muramura

I found myself using NULL in the decision of a method that returns NULLPTR.
I believe there is a difference between NULL and NULLPTR.
I will change the decision value from NULL to NULLPTR.

2022-01-29 20:20 UTC, hendjoshsr71 commented on libraries/AP_Filesystem/AP_Filesystem_FATFS.cpp
> +    if ( fh == nullptr ) {
```suggestion
    if (fh == nullptr) {
```

2022-01-29 20:20 UTC, hendjoshsr71 commented on libraries/AP_Filesystem/AP_Filesystem_FATFS.cpp
> +    if ( fh == nullptr ) {
```suggestion
    if (fh == nullptr) {
```

2022-01-29 20:26 UTC, hendjoshsr71 requested changes
Looks fine.

But you missed a few in the file. You might as well do them all at once. (I got 17 when I looked, Lines 67-80, Line 107.)

If you wanted to, there are a few style fixups you could do on a few lines since you changed the lines anyways.

2022-01-30 01:23 UTC, muramura commented
@hendjoshsr71 san
Thanks for the comment.
I agreed.
I've adapted the style.

2022-01-30 06:04 UTC, hendjoshsr71 reviewed
Sorry if I was confusing. I meant there are still others spots with `== NULL` you could replace in this file. Using VSCode and this search `== NULL`  I find the following still left. 
Line 67
Line 69
Line 74
Line 80
Line107
Line 161

2022-01-30 10:29 UTC, muramura commented
@hendjoshsr71 sam
The lines you mentioned are as follows.
The element value of the table and the return value of the method are null.
In particular, the C language methods are NULL.
The ArduPilot uses the return value of the method to make a decision.

Line 67: file_table[] returns NULL.
Line 69: The calloc method returns NULL.
Line 74: The calloc method returns NULL.
Line 80: The malloc method returns NULL.
Line 107: file_table[] returns NULL.
Line 161: file_table[].fh returns NULL.

2022-02-02 09:37 UTC, hendjoshsr71 commented
I'm not a C++ expert, but I did come across this https://stackoverflow.com/questions/53532697/c-style-when-using-c-function-in-c-should-i-check-for-null-or-nullptr

Either seems fine and what you have here is better than before :) 

But lets ask @peterbarker since I've heard he is a resident C++ expert recently ;)

2022-02-02 10:52 UTC, khancyr reviewed
yep, that would be great to get rid of the NULL from the codebase.
On nice things, beside off some cpp compile time check is that it also remove a lot of noise on static analysers!

2022-02-02 22:03 UTC, magicrub approved these changes

2022-02-14 23:13 UTC, tridge approved these changes

2022-02-14 23:14 UTC, hendjoshsr71 approved these changes

2022-02-14 23:14 UTC, merged