AP_Camera: use of AP_Camera checks HAL_CAMERA_ENABLED
ArduPilot/ardupilot pull request #20020
Opened 2022-02-07 08:03 UTC by tatsuy

I added HAL_CAMERA_ENABLED so that AP_Camera can be disabled.
I removed CAMERA and use only HAL_CAMERA_ENABLED.

CubeOrange
```
Target          Text (B)  Data (B)  BSS (B)  Total Flash Used (B)  Free Flash (B)
---------------------------------------------------------------------------------
bin/arducopter   1776568      3172   259184               1779740          186328 // master (ab8c40d9)
bin/arducopter   1776568      3172   259184               1779740          186328 // HAL_CAMERA_ENABLED = 1
bin/arducopter   1772548      3172   259188               1775720          190344 // HAL_CAMERA_ENABLED = 0
```

In Sub, CAMERA was DISABLE by default, but this change will enable it.
I'm not sure if I should use the different default value according to vehicle types.

2022-04-15 05:57 UTC, tatsuy commented
rebased

2022-04-15 06:30 UTC, peterbarker requested changes

2022-04-15 06:30 UTC, peterbarker commented on ArduCopter/Copter.cpp
> +#if HAL_CAMERA_ENABLED == ENABLED
```suggestion
#if AP_CAMERA_ENABLED
```

2022-04-16 07:15 UTC, tatsuy commented on ArduCopter/Copter.cpp
> +#if HAL_CAMERA_ENABLED == ENABLED
fixed it

2022-04-16 07:15 UTC, tatsuy commented
@peterbarker 
Thank you for your review!
I fixed.

2022-09-22 00:27 UTC, tatsuy commented
Closed by #20891

2022-09-22 00:27 UTC, closed without merging