Copter: Change the process for errors
ArduPilot/ardupilot pull request #20048
Opened 2022-02-10 11:14 UTC by muramura

It's a meaningless process for build warnings.
I declare that I will not use the result in the preprocessor.

2022-02-10 11:24 UTC, IamPete1 requested changes

2022-02-10 11:24 UTC, IamPete1 commented on ArduCopter/GCS_Mavlink.cpp
> +#pragma GCC diagnostic pop
```suggestion
            IGNORE_RETURN(copter.set_home_to_current_location(true));
```

2022-02-11 01:10 UTC, peterbarker commented
There's *also* `UNUSED_RESULT`.... which is implemented differently... yay.  Marking for DevCall so we can choose just one to go forward with - both naming and implementation.

@lucasdemarchi was there an advantage in using the attribute rather than just chucking it into an `if()` like `IGNORE_RETURN` does?

2022-02-11 09:09 UTC, lucasdemarchi commented
At the time that was written it was replacing the usual method of doing `(void)function();` - cast to void to ignore the result. The problem was that functions with the attribute to warn unused results was triggering the warn - see gcc bug mentioned in the commit.

As for the difference in IGNORE_RETURN vs UNUSED_RESULT, I'm not sure one is better than the other. We'd probably need to check the end result for  IGNORE_RETURN to confirm the compiler is not emitting additional code there. UNUSED_RESULT is also much older in the codebase: it was added by 8a58c06adb3604bcd59ce2ec5c78b58e71f0cdc5  (2016) vs b8f9f171e06c273e0fdd5d5d19eddcc0744fd26f (2020) for IGNORE_RETURN

2022-02-14 23:33 UTC, tridge approved these changes

2022-02-14 23:35 UTC, peterbarker commented
@muramura please rebase to get CI run again

2022-02-28 21:12 UTC, hendjoshsr71 commented
@muramura san I've rebased this for you.

2022-03-08 22:36 UTC, merged