Copter/Plane:  Judge by return value
ArduPilot/ardupilot pull request #20057
Opened 2022-02-11 15:33 UTC by muramura

The angle_error variable is used only once.
I make the decision in the return value of the method, which eliminates the need for this variable.

2022-02-11 20:49 UTC, hendjoshsr71 reviewed
I'm tempted to close this as it doesn't make a material difference and the compiler removes the extra variable anyway. (Thus the zero size change.)

It doesn't really change the clarity of the code for the better or worse. It does add one more step during debugging though.  

@rmackay9 is the code style master though so his call?

2022-02-14 20:51 UTC, hendjoshsr71 requested changes

2022-02-14 20:51 UTC, hendjoshsr71 commented on ArduCopter/crash_check.cpp
> +    if (attitude_control->get_att_error_angle_deg() <= CRASH_CHECK_ANGLE_DEVIATION_DEG) {
This doesn't look right...

```suggestion
    if (attitude_control->get_att_error_angle_deg() <= PARACHUTE_CHECK_ANGLE_DEVIATION_DEG) {
```

2022-02-14 23:54 UTC, tridge commented
this doesn't look like an improvement and makes debugging harder

2022-02-14 23:54 UTC, closed without merging