Clock H750 at 480Mhz when using 8Mhz crystal
ArduPilot/ardupilot pull request #20109
Opened 2022-02-17 17:08 UTC by andyp1per

This saves a solid 5-6% on the SPRacing H7, which is really pretty significant

I was unable to find clock combinations to make this work with 24Mhz and 25Mhz crystals

2022-02-22 00:13 UTC, tridge commented
> I was unable to find clock combinations to make this work with 24Mhz and 25Mhz crystals

we should be able to fix that for 8,16,24

2022-02-22 00:14 UTC, tridge requested changes
i'd like to fix it for 16 and 24 too

2022-02-22 14:02 UTC, andyp1per commented
Somehow I must have been driving CubeMX badly because actually the same change works for 16Mhz and 24Mhz

2022-02-23 07:19 UTC, tridge approved these changes

2022-02-23 07:19 UTC, merged