Update mode_auto.cpp
ArduPilot/ardupilot pull request #20153
Opened 2022-02-23 14:27 UTC by Hasi123

Change to relative frame to avoid terrain bug with takeoff. Fixes #20142

2022-02-24 13:56 UTC, Hasi123 commented
I have tested it yesterday in the simulator and today on my own copter. Works just as expected. Here are some logs (before/after behaviour):
[logs_before_after_fix.zip](https://github.com/ArduPilot/ardupilot/files/8132946/logs_before_after_fix.zip)

2022-02-28 17:35 UTC, IamPete1 requested changes

2022-02-28 17:35 UTC, IamPete1 commented on ArduCopter/mode_auto.cpp
> +    dest.set_alt_cm(alt_target , Location::AltFrame::ABOVE_HOME);
```suggestion
```
I think this makes it slightly clearer. It changes to always set after the sanity check.

```
    // sanity check
 target
    int32_t alt_target_min_cm = copter.current_loc.alt + (copter.ap.land_complete ? 100 : 0);
    alt_target = MAX(alt_target, alt_target_min_cm);

    // set updated altitude in location structure
    dest.set_alt_cm(alt_target, Location::AltFrame::ABOVE_HOME);
```

2022-03-01 00:07 UTC, tridge commented
assigned to @rmackay9

2022-03-11 04:31 UTC, rmackay9 commented
I've got an updated fix here https://github.com/ArduPilot/ardupilot/pull/20285.  @Hasi123 would you be able to confirm this resolves the issue you've seen?  Thanks again for finding this important bug!

2022-03-11 04:31 UTC, closed without merging