AP_VideoTX, ArduCopter : Modifying the case label code
ArduPilot/ardupilot pull request #20245
Opened 2022-03-07 15:55 UTC by RuffaloLavoisier

* Case label indentation
* Change it to single line

2022-03-07 16:03 UTC, andyp1per requested changes
Please remove the SmartAudio changes, there is a big change pending that will remove all of this

2022-03-07 21:11 UTC, khancyr approved these changes
fixing indent. LGTM

2022-05-12 00:24 UTC, rmackay9 approved these changes

2022-05-12 00:24 UTC, merged

2022-05-12 00:24 UTC, rmackay9 commented
Merged, txs