Convert constant divides into multiplies
ArduPilot/ardupilot pull request #20290
Opened 2022-03-11 19:48 UTC by Hwurzburg

I did not convert /2 or constant on constant since they  would not be run time divides (I think compiler is smart enough to convert /2 to shift instead of divide so did not change those)...

I am a bit confused as to when to use the "f"ending on constants....

btw.... #20289 made me do it!

2022-03-11 20:10 UTC, WickedShell requested changes
A lot of these look incorrect, you are forcing things from integer types into floating point types then back to integer types at the end. I stopped commenting on them after the first couple, but a lot of these need to be redone, because they aren't improvements.

2022-03-11 20:10 UTC, WickedShell commented on ArduPlane/GCS_Mavlink.cpp
> +        new_home_loc.alt = packet.altitude * 0.1f;
This is wrong, it was an integer before, this is forcing a promotion to floating point type, then casting back down to an integer.

2022-03-11 20:10 UTC, WickedShell commented on ArduPlane/GCS_Mavlink.cpp
> +        return wrap_360_cd(nav_controller->target_bearing_cd() ) * 0.05f;
Same thing this is forcing something to a float that was not before.

2022-03-11 20:12 UTC, WickedShell commented on libraries/AP_RSSI/AP_RSSI.cpp
> +                return rssi * 0.00392; // divide by 255
```suggestion
                return rssi * (1/255f);
```

Same result, but it's much clearer where the constant came from, and will compile to the same thing

2022-03-11 20:13 UTC, WickedShell commented on ArduPlane/tiltrotor.cpp
> +                const float right = gain * SRV_Channels::get_output_scaled(SRV_Channel::k_elevon_right) * 0.0002222; // 0.0002222 = 1/4500
Just include the constant you want as an actual floating point calculation. This is very hard to read, and arbitrarily limits accuracy of the result due to truncation of the provided constant.

2022-03-11 20:14 UTC, WickedShell commented on ArduPlane/mode_loiter.cpp
> +    const int32_t expanded_acceptance = 1000 * (labs(plane.loiter.sum_cd) * 0.00002777f; // 0.00002777 = divide by 36,000
Floating point problems, plus out of scope with the above comment, needs a bit more looking at the usage and less mechanical replacement.

2022-03-12 01:12 UTC, Hwurzburg commented
reverted anything that forced floats and adopted suggestions for how to show fractions instead of single constant...sorry still learning

2022-03-14 23:32 UTC, IamPete1 commented on ArduPlane/tiltrotor.cpp
> +                const float right = gain * SRV_Channels::get_output_scaled(SRV_Channel::k_elevon_right) * (1/4500.0);
we have a `SERVO_MAX` define for the 4500 somewhere. But whatever.

2022-03-14 23:32 UTC, tridge requested changes

2022-03-14 23:35 UTC, Hwurzburg commented on ArduPlane/tiltrotor.cpp
> +       float settilt = constrain_float((SRV_Channels::get_output_scaled(SRV_Channel::k_throttle)-MAX(plane.aparm.throttle_min.get(),0)) / 0.02, 0, 1);
fixed

2022-03-18 04:26 UTC, tridge approved these changes

2022-03-18 04:26 UTC, merged