AP_GPS: UBlox: configure and log TIM-TM2
ArduPilot/ardupilot pull request #20335
Opened 2022-03-19 17:40 UTC by IamPete1

This adds logging of TIM TM2 message useful for precise sync of signals to GPS time. 

See: https://github.com/ArduPilot/ardupilot/issues/15428, https://github.com/ArduPilot/ardupilot/issues/10369, https://github.com/ArduPilot/ardupilot/issues/7892

Tested on m8p, I have verified the logged message is the same as that reported in u-center. 

![image](https://user-images.githubusercontent.com/33176108/159131892-7ff0e8c5-cbfc-4cf4-b2ce-d4ab94fe8917.png)

I have not checked if this message is supported by all UBlox variants, or what happens if it is not supported, I presume the GPS will not respond to the request for message rate in that case. So this new message will not be added to `_unconfigured_messages` and will not cause a arming failure.

2022-03-22 00:17 UTC, peterbarker commented on libraries/AP_GPS/AP_GPS_UBLOX.cpp
> +    struct log_UbxT pkt = {
```suggestion
    const struct log_UbxT pkt {
```

2022-03-22 00:20 UTC, tridge requested changes
move to optional config, and only on >1M boards? also would be good to move RXM logging to be optional
better to use inline logging method so we don't consume a log slot for a rare msg

2022-04-02 11:33 UTC, IamPete1 commented
![image](https://user-images.githubusercontent.com/33176108/161380858-f7b9d3a3-d5d7-4f03-a1a8-88540ef0fb53.png)

I left this logging for 9 and a half hours. A ~0.3Hz trigger signal connected to the ExtInt pin of the GPS and the CAM feedback pin. 

Firstly its clear that the `CAM.GPSTime` is useless. It is just the last received GPS time, there is no projection based on time since that message was received.  Unsurprisingly when the GPS rate is 5hz this results in a 0.2 second error range. I'm not sure why we also see a 17 second offset, could be some difference between timebase's used?

The final graph shows the CAM log time vs TM2 GPS time (offset to start at 0). This shows good agreement, although a linear drift. Works out to 2.533 ms per minute.

2022-04-04 23:55 UTC, tridge requested changes

2022-04-04 23:55 UTC, tridge commented on libraries/AP_GPS/AP_GPS_UBLOX.cpp
> +        "s#s#----ss-sss",
wrong length?

2022-04-04 23:55 UTC, tridge commented on libraries/AP_GPS/AP_GPS_UBLOX.cpp
> +        "F-----CI-CII",
is accEst mult really 1e-9?

2022-04-05 17:11 UTC, IamPete1 commented on libraries/AP_GPS/AP_GPS_UBLOX.cpp
> +        "s#s#----ss-sss",
yep, fixed

2022-04-06 07:22 UTC, tridge approved these changes

2022-04-06 07:22 UTC, merged