Add comments
ArduPilot/ardupilot pull request #20334
Opened 2022-03-19 15:52 UTC by Rockev1n

2022-03-19 17:58 UTC, amilcarlucas commented
This needs a `git rebase master` and non-english will make the code harder to read.

2022-03-27 15:40 UTC, nkruzan reviewed
I don't feel that comments that are translating other comments are really needed. Some of the comments may have value helping to understand what the code is doing if they were in English, but others are explaining C++ library functions or attempting to explain math. A couple are just noise.

2022-03-27 15:40 UTC, nkruzan commented on ArduPlane/quadplane.cpp
> +    roll_out_cd = 100 * degrees(atanf(cosf(radians(pitch_out_cd*0.01))*tanf(radians(roll_out_cd*0.01))));//不知道他在说啥
Translation: I don't know what he's talking about

Not really appropriate comment for the code.

2022-03-29 21:37 UTC, khancyr requested changes
This looks like only some comments in an asian type language (sorry I am unable to guess which one).
We only accept english contribution.
For a correct submission, I invite you to read https://ardupilot.org/dev/docs/contributing.html

2022-03-29 21:37 UTC, closed without merging

2022-03-29 21:38 UTC, khancyr commented
I am closing this for now. Feel free to reopen another PR with only your comments in english.