AP_HAL_ChibiOS: reversible DShot fix
ArduPilot/ardupilot pull request #20349
Opened 2022-03-22 11:14 UTC by rmackay9

This fixes the DShot output on Rovers (at least) when reversible DShot is used ([see wiki setup instructions here](https://ardupilot.org/rover/docs/common-blheli32-passthru.html#reversible-dshot-escs)).

This has been tested on a CubeOrange running Rover firmware with:

- BLHeli ESC connected to AUX2 (aka SERVO10)
- SERVO_BLH_3DMASK bitmask set for channel 10

Before this change the motor both spins in the wrong direction and when the throttle is just below 1500 (e.g. 1475) it spins at nearly full speed, when the throttle is near 1000 it spins at a low speed.

After this change the motor spins in the correct direction and at the correct speed as it did in 4.1.5.

This resolves issue https://github.com/ArduPilot/ardupilot/issues/19346

Thanks to @andyp1per for specifying the fix.

2022-03-22 11:29 UTC, andyp1per approved these changes

2022-03-22 11:48 UTC, IamPete1 commented
I notice we do it slightly differently again with the safety mask, https://github.com/ArduPilot/ardupilot/blob/73eabb1fd09d1ef28c6692d6746e4eeec4d027df/libraries/AP_HAL_ChibiOS/RCOutput.cpp#L1403

Looks like the difference is because we shift the reverse mask when we set them.
https://github.com/ArduPilot/ardupilot/blob/73eabb1fd09d1ef28c6692d6746e4eeec4d027df/libraries/AP_HAL_ChibiOS/RCOutput_serial.cpp#L114-L126

Maybe we should stop shifting on set so all the param mask comparisons are done in the same way. 

You could remove/move down this const:
https://github.com/ArduPilot/ardupilot/blob/73eabb1fd09d1ef28c6692d6746e4eeec4d027df/libraries/AP_HAL_ChibiOS/RCOutput.cpp#L1408

2022-03-23 07:35 UTC, tridge requested changes

2022-03-23 07:35 UTC, tridge commented on libraries/AP_HAL_ChibiOS/RCOutput.cpp
> +            if ((chan_mask & _reversible_mask) > 0) {
minor quibble, should be != 0

2022-03-23 07:47 UTC, rmackay9 commented on libraries/AP_HAL_ChibiOS/RCOutput.cpp
> +            if ((chan_mask & _reversible_mask) > 0) {
fixed, txs.

2022-03-23 23:01 UTC, merged