AC_Fence: add check for enabling non existant fence
ArduPilot/ardupilot pull request #20416
Opened 2022-03-31 23:32 UTC by timtuxworth

It's currently possible to Arm a vehicle with FENCE_AUTOENABLE = 1 but with no fence set up.
Once armed and flying - if an auto enable of a Geo Fence is triggered, the plane will send the message to the GCS that the fence is enabled, even if there is no fence to enable.
So either way, a pilot might think they have a geofence and it is enabled whereas there might be no fence.
This PR does two things.

adds a pre-arm check to prevent arming if FENCE_AUTOENABLE = 1 but there is no fence
if pre-arm checks are disabled, if a vehicle attempts to auto enable the geofence after takeoff, a warning message is sent to the GCS and the AC_Fence::enable() function is not called.

2022-03-31 23:40 UTC, timtuxworth commented
I'm already wondering about the pre-arm check. Maybe it's really only necessary if arming in auto mode?

2022-04-01 00:40 UTC, timtuxworth commented
I realized that this PR only deals correctly with AUTOENABLE, but the same problem exists with RC and GCS/MAV triggered fence enabled. I've got a new commit that I think is "better" - any thoughts? https://github.com/timtuxworth/ardupilot/commit/2df2da5e28ccb63aefd0a09b618b340382e2bba9

2022-04-01 09:31 UTC, amilcarlucas approved these changes
Looks good to me

2022-04-01 17:09 UTC, timtuxworth commented
After sleeping on it, I realized this definitely needed some improvements, so I have updated the PR to a new commit with some improvements.  I will do some more testing today and request a re-review.

2022-04-01 22:19 UTC, timtuxworth commented
New improved version. Now correctly performs pre-arm checks, and reports a GCS notification if fence is enabled via FENCE_ENABLE or FENCE_AUTOENABLE or by RC channel or by mavlink command. Tested in SITL for FENCE_ENABLE and AUTOENABLE cases, but not tested for RC or mavlink.

2022-04-19 08:08 UTC, amilcarlucas requested changes

2022-04-19 08:08 UTC, amilcarlucas commented on ArduPlane/fence.cpp
> +
Duplicated code, remove it.

```suggestion
```

2022-04-19 08:08 UTC, amilcarlucas commented on libraries/AC_Fence/AC_Fence.cpp
> +    }
This will log to much. I suggest you do not change the logging code

2022-04-28 19:23 UTC, timtuxworth commented
Updated autotest - one test changed to reflect that the plane will not arm if there isn't a fence present and then added several other tests to make sure that enable/disable was being reflected correctly after adding and removing various types in  test.Plane.FenceStatic

2022-06-03 21:42 UTC, IamPete1 requested changes
A formatting review only.

2022-06-03 21:42 UTC, IamPete1 commented on ArduPlane/fence.cpp
> +    if( !orig_breaches && new_breaches && plane.is_flying()) {
```suggestion
    if (!orig_breaches && new_breaches && plane.is_flying()) {
```

2022-06-03 21:42 UTC, IamPete1 commented on libraries/AC_Fence/AC_Fence.cpp
> +    if(AC_Fence::present()) {
```suggestion
    if (AC_Fence::present()) {
```

2022-06-03 21:42 UTC, IamPete1 commented on libraries/AC_Fence/AC_Fence.cpp
> +        if(new_enabled && !_enabled) {
```suggestion
        if (new_enabled && !_enabled) {
```

2022-06-03 21:42 UTC, IamPete1 commented on libraries/AC_Fence/AC_Fence.cpp
> +        else {
```suggestion
        } else {
```

2022-06-03 21:42 UTC, IamPete1 commented on libraries/AC_Fence/AC_Fence.cpp
> +        if(new_enabled) {
```suggestion
        if (new_enabled) {
```

2022-06-03 21:42 UTC, IamPete1 commented on libraries/AC_Fence/AC_Fence.cpp
> +    else {
```suggestion
    } else {
```

2022-06-03 21:42 UTC, IamPete1 commented on libraries/AC_Fence/AC_Fence.cpp
> +        if(new_enabled) {
```suggestion
        if (new_enabled) {
```

2022-06-03 21:42 UTC, IamPete1 commented on libraries/AC_Fence/AC_Fence.cpp
> +        else {
```suggestion
        } else {
```

2022-06-03 21:59 UTC, timtuxworth commented
Thanks for the suggestions @IamPete1 - I'll make some updates, just me getting up to speed with the coding standards, which is always a good thing.
I'm also thinking that maybe FENCE_AUTOENABLE shouldn't be a pre-arm check as it really only applies if the plane is about to do an auto takeoff and would not be a problem in other cases. There will still be a warning that "Enabled fence failed (no fence found" if the autoenable is triggered during the flight.

2024-07-25 04:53 UTC, peterbarker commented
@timtuxworth @andyp1per 's just completely rejigged fencing.

Can you see if this is still relevant, please?

2024-07-25 14:24 UTC, timtuxworth commented
I'm sure this is completely obsolete now.

2024-07-25 14:24 UTC, closed without merging