hwdef: KakuteH7 bluetooth switch
ArduPilot/ardupilot pull request #20419
Opened 2022-04-01 05:24 UTC by chobitsfan

KakuteH7 integrates a bluetooth chip for serial2 telemetry.  This PR does 2 things:
1. turn off bluetooth as default, to avoid possible rf interference. 
2. allow users to turn on bluetooth just like relay switch

tested on KakuteH7

2022-04-01 22:10 UTC, Hwurzburg commented
BT module already off by default....since it does not work with any ArduPilot GCS (BLE protocol) this does not provide any function at the present time.....doesnt hurt, but doesnt help either, unfortunately

2022-04-02 12:47 UTC, chobitsfan commented
Thank you @Hwurzburg 

> BT module already off by default

I am afraid it is not exactly true. Flash kakute h7 with master, I can find a "KakuteH7 V1 DB4D" bluetooth device with my android phone.

2022-04-02 20:31 UTC, Hwurzburg commented
if you looked when it had BF firmware it would be on (since its disarmed) and the phone would remember it in its scan list...if you load ArduPilot firmware it will be off and if you try to find it on a "clean" system it will not appear since its off in Ardupilot....all gpios default to low, if not assigned, in ArduPilot...the module needs an active high to turn on...just verified on the bench with my Kakute H7....

2022-04-05 12:37 UTC, chobitsfan commented
Thank you @Hwurzburg 

I tested it on a clean android phone. using BLE Scanner (https://play.google.com/store/apps/details?id=com.macdom.ble.blescanner). It not only find kakute h7 but also able to discover available services.
![Screenshot_20220405-173652_BLE Scanner](https://user-images.githubusercontent.com/19793511/161755003-f6ea7c6c-855a-4d58-a6e3-9d8b88af3090.jpg)

2022-04-09 21:39 UTC, Autonomost commented
Hey there. about to test, so this does or doesn't work?

2022-04-09 22:02 UTC, Hwurzburg commented
it does...my PCs were not detecting BLE....I have loaded the PR and tested it...

2022-04-09 22:02 UTC, Hwurzburg approved these changes

2022-04-09 22:38 UTC, Autonomost commented
@Hwurzburg Awesome! I'm going to test it out as well. Sweet! Thanks a lot @chobitsfan and @Hwurzburg!

2022-04-09 23:04 UTC, Hwurzburg commented
Unfortunately no ArduPilot GCS accept connections to BLE modules....wish QGC did

2022-04-09 23:09 UTC, Autonomost commented
@Hwurzburg agreed. that's what I'm trying to use this with. Do I need to set a relay pin high for this to work? could you please tell me which relay corresponds to pin 81?

2022-04-10 06:35 UTC, chobitsfan commented
Hi @Hwurzburg and @Autonomost thank you for helping

> Unfortunately no ArduPilot GCS accept connections to BLE modules

I agree with @Hwurzburg, it seems ble module on kakute h7 is the same as speedy bee. It use its own custom profile rather than serial profile. I can not find any ardupilot compatible gcs support this ble module. The main purpose of this pr is to make sure bluetooth turned off, avoid rf interference.

2022-04-13 08:31 UTC, chobitsfan commented
Hi @Autonomost Thank you

> Do I need to set a relay pin high for this to work? could you please tell me which relay corresponds to pin 81?

I set relay_pin to 81, and set rc8_option to 28 (relay on/off)

2022-05-31 14:03 UTC, khancyr approved these changes
This looks good and restraint to one board.
Two person have test this already, so it should  be safe to merge.

2022-06-01 07:09 UTC, tridge requested changes
nice idea!

2022-06-01 10:50 UTC, chobitsfan commented on libraries/AP_HAL_ChibiOS/hwdef/KakuteH7/hwdef.dat
> +PE13 EVENT-OUT OUTPUT LOW PUSHPULL GPIO(81)
Thank you @tridge 

Maybe we also need to fix this?

https://github.com/ArduPilot/ardupilot/blob/c02aef8a503393ff277eade4f067656468c9c2f1/libraries/AP_HAL_ChibiOS/hwdef/scripts/STM32H743xx.py#L821

2022-06-01 10:58 UTC, chobitsfan commented
> maybe you want it on in the bootloader so you can load new fw over bluetooth?

Thank you @tridge 

I am afraid that I can not find any GCS that support update ardupilot fw over ble (bluetooth on kakute h7 do not support serial port profile).  I think it would be better to turn it off to avoid any interference for now.

2022-08-01 06:42 UTC, andyp1per commented
This is going to cause conflicts with https://github.com/ArduPilot/ardupilot/pull/21261 because we are using the same pin. @chobitsfan can I suggest you move to pin 82 and setup relay 3 to this pin as I have done with the VTX power. I am happy to do this and pull this change into my PR and rebuild the bootloaders if you want.

2022-08-01 12:32 UTC, chobitsfan commented
Hi @andyp1per Thank you very much for suggestions. I have changed it.

2022-08-01 13:03 UTC, andyp1per approved these changes

2022-08-03 03:59 UTC, tridge approved these changes

2022-08-03 03:59 UTC, merged

2023-08-02 05:20 UTC, Saleh-At commented
This means I can't connect with Bluetooth by ardupilot firmware?!

2023-08-14 13:00 UTC, Hwurzburg commented
and it wont work with any ArduPilot GCS unfortunately....it uses BLE instead of normal BT.....so far QGC and MP dont support that as a connect protocol...