Tools: add airspeed defaults to vehicle defaults files
ArduPilot/ardupilot pull request #20423
Opened 2022-04-02 00:54 UTC by Hwurzburg

2022-04-04 23:58 UTC, tridge approved these changes

2022-04-05 00:04 UTC, rmackay9 commented on Tools/autotest/default_params/blimp.parm
> +ARSPD_TYPE 0
remove the ARSPD_TYPE

2022-04-05 00:05 UTC, hendjoshsr71 requested changes
Thanks Henry!

2022-04-05 00:05 UTC, hendjoshsr71 commented on Tools/autotest/default_params/copter.parm
> +ARSPD_TYPE 0
remove the types so that it matches as close as possible to a real vehicle. 

```suggestion
```

2022-04-05 00:11 UTC, rmackay9 commented on Tools/autotest/default_params/sailboat.parm
> +ARSPD_TYPE 0
@Hwurzburg one more here too..

2022-04-06 21:52 UTC, Hwurzburg commented on Tools/autotest/default_params/sailboat.parm
> +ARSPD_TYPE 0
sorry...got it

2022-04-06 22:08 UTC, hendjoshsr71 approved these changes
lgtm

2022-04-11 23:52 UTC, tridge approved these changes

2022-04-11 23:53 UTC, merged