AP_AHRS_DCM: fix normalization reset
ArduPilot/ardupilot pull request #20475
Opened 2022-04-06 23:50 UTC by hendjoshsr71

Closes https://github.com/ArduPilot/ardupilot/issues/20284

Fixes the issue above. Seems like the renormalization check is incorrect or at least needs a smaller window as is used in `renorm()` below

2022-04-07 09:06 UTC, amilcarlucas commented
I think this will cause the reset too often.

2022-04-07 11:42 UTC, khancyr requested changes
Theorically speaking the PR should be right.
But according to this comment : https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_AHRS/AP_AHRS_DCM.cpp#L281

The large value is expected.
This seems to have been settled and tested on the old APM board. It is probable that we won't have this kind of issue anymore. But that would need a significant effort to look after for close to no gain.
I would propose to just add a comment to this 10 number to explain where it comes from unless somebody want to make proper investigations

2022-04-07 23:00 UTC, peterbarker commented
We seriously need to log errors or events to dataflash in here; it's only half-a-dozen lines to add something to the error/event enumerations in AP_Logger and a call to `Log_Error`

2022-04-16 06:32 UTC, khancyr approved these changes
LGTM

2022-04-18 14:27 UTC, IamPete1 approved these changes

2022-04-18 23:26 UTC, tridge approved these changes

2022-04-18 23:27 UTC, merged