AP_InertialSensor: change name of NOTCH to HNTC2
ArduPilot/ardupilot pull request #20516
Opened 2022-04-12 12:59 UTC by Hwurzburg

Changed name of NOTCH as discussed in devcall.....
verified (I think) that existing static notches would still be static upon upgrade to 4.2 since the REF param is 0 by default, disabling freq changes...

2022-04-12 13:37 UTC, andyp1per commented
This is not actually correct - its still a static notch, the difference is it allows harmonics and double notches on a static notch. We should therefore remove the MODE from the documentation and change the docs for OPTS to remove dynamic harmonic and loop rate update

2022-04-12 13:38 UTC, andyp1per requested changes
Needs a doc change instead

2022-04-12 14:36 UTC, Hwurzburg commented
then the mode param for NOTCH should be removed from the code
it will appear in GCS and in wiki docs otherwise
and REF

2022-04-12 18:44 UTC, Hwurzburg commented
so re-doing to fix metadata for NOTCH....phase 1 move up metadata one layer....next will modify

2022-04-12 19:10 UTC, Hwurzburg commented
okay should be good to go now

2022-04-12 19:30 UTC, andyp1per approved these changes
LGTM!

2022-04-12 23:23 UTC, tridge commented
> its still a static notch, the difference is it allows harmonics and double notches on a static notch. We should therefore remove the MODE from the documentation and change the docs for OPTS to remove dynamic harmonic and loop rate update

what?!? it uses the harmonic notch params.
I don't actually understand why it isn't a full harmonic notch filter already, but if that is the case let's fix it to be a full harmonic notch. I really want two full harmonic notch filters for quadplanes with petrol motors, so one for VTOL and the other for EFI fwd motor

2022-04-13 03:55 UTC, tridge commented
see #20521 for implementing dual harmonic properly

2022-04-13 12:51 UTC, closed without merging