hwdef: disable serially-attached actuators on SkyViper
ArduPilot/ardupilot pull request #20523
Opened 2022-04-13 04:57 UTC by peterbarker

2022-04-13 20:45 UTC, amilcarlucas requested changes

2022-04-13 20:45 UTC, amilcarlucas commented on libraries/AP_HAL_ChibiOS/hwdef/skyviper-v2450/hwdef.dat
>  define HAL_WITH_ESC_TELEM 0
This line is duplicated
```suggestion
```

2022-04-15 07:43 UTC, peterbarker commented on libraries/AP_HAL_ChibiOS/hwdef/skyviper-v2450/hwdef.dat
>  define HAL_WITH_ESC_TELEM 0
Fixed, thanks.

2022-04-16 05:56 UTC, magicrub approved these changes

2022-04-16 23:10 UTC, merged