AP_AHRS: View: return invalid rotation if pitch trim is set
ArduPilot/ardupilot pull request #20533
Opened 2022-04-14 14:47 UTC by IamPete1

This is disables the new trim functionality added in https://github.com/ArduPilot/ardupilot/pull/18311 in the case that there is a pitch offset. 

Of course we could workout the correct trim including the pitch offset, but that would be significantly more effort. Pitch offset being set is relatively uncommon, this stops us getting the wrong answer in the case it is set. 

Extract from https://github.com/ArduPilot/ardupilot/pull/20074

2022-04-18 10:05 UTC, khancyr approved these changes
I would say that is ok.
My only interogation is that _pitch_trim_deg comes from the eeprom as float, I wonder if the  is_zero check isn't too tight on a float param that may move ?

2022-04-18 23:06 UTC, tridge requested changes
it looks like this would mean a user can't do AHRS trim operation for tailsitters with a non-zero Q_TRIM_PITCH. I think this may confuse people

2022-04-18 23:23 UTC, IamPete1 commented
@tridge It means you cant to a tailsitter nose up trim, Plane view trim should still work fine, as before your update.

2022-04-19 22:53 UTC, IamPete1 commented
@tridge This now asks quadplane which rotation it should be trying to calibrate. This removes the ambiguity on whether or not none zero `Q_TRIM_PITCH` matters. I also think its more logical for the users to calibrate for the mode there in and allows us to do a better job in the future. 

The issue with the existing "try both" method is that we cannot tell the difference between failing because the user is trying to calibrate VTOL and have `Q_TRIM_PITCH` set or failing because there trying to calibrate FW and are more than 10 deg out.

Tested on the bench, normal quadplane and tailsitter. 

Will need to update the wiki to tell users they need to be in a mode that matches the view there trying to calibrate.

2022-04-26 00:02 UTC, tridge approved these changes

2022-04-26 00:03 UTC, merged