Plane: remove support for alt wait
ArduPilot/ardupilot pull request #20548
Opened 2022-04-16 22:37 UTC by IamPete1

This removes support for altitude wait mission command, used for high altitude balloon launches. Very rarely used functionality that can now be replicated with scripting.

2022-04-17 00:02 UTC, IamPete1 commented
saves ~500 bytes on plane and a handful on everything else.

2022-04-18 22:55 UTC, tridge requested changes
i wouldn't want to remove this until we have a working replacement lua script, perhaps with NAV_SCRIPT_TIME, with the same features
This feature is being actively used by balloon drop projects

2022-04-23 17:43 UTC, IamPete1 commented
This now adds the ability to run commands from scripting. It lays a frame works for more generic way-point support in the future. Behavior with new script is same as before. Only unexpected thing that might happen would be if one were to switch out of auto and back while the nav command is running.

2022-04-27 07:43 UTC, tridge requested changes
i need to do some testing on this

2022-04-27 07:43 UTC, tridge commented on libraries/AP_Mission/AP_Mission.cpp
> +    case MAV_CMD_NAV_ALTITUDE_WAIT:
i think we need to keep the compatibility with the existing storage format

2022-04-27 07:43 UTC, tridge commented on libraries/AP_Scripting/examples/Nav_Altitude_Wait.lua
> +  loc:change_alt_frame(ABOVE_HOME)
need to check if original handled absolute/terrain frames

2023-10-30 10:59 UTC, IamPete1 commented
https://github.com/ArduPilot/ardupilot/pull/25391 achieves the core of what I was after, removing the odd early return. I do think generic scripting waypoints is a good idea in the future.

2023-10-30 10:59 UTC, closed without merging