Fix setup
ArduPilot/ardupilot pull request #20615
Opened 2022-04-24 07:54 UTC by scherbatey

I run:
$ vagrant up jammy-desktop
and faced two issues:
- could not access repository github.com/JSBSim-Team/jsbsim.git via ssh
- dbus-launch executable was missing

So I'm providing the fix for these

2022-04-24 10:06 UTC, peterbarker requested changes
Please adjust the commit message to be "Vagrant: fix jammy installation"

Thanks for doing this.

2022-04-24 10:06 UTC, peterbarker commented on Tools/vagrant/initvagrant-desktop.sh
> +apt-get install -y ubuntu-desktop dbus-x11
Please test a vagrant-up of our oldest supported LTS release to make sure this doesn't kill it - or adjust the patch so it is only installed under jammy.

2022-05-01 04:27 UTC, peterbarker commented
@scherbatey I've tested this locally,fixed the commit message, made changed to avoid anything bad happening to older platforms by adding a specific check for jammy.

I've also added a couple of patches to get X working.

I've force-pushed over your branch here.  In future I suggest creating a git "topic branch" to create your PRs from, rather than PR'ing from your master branch.  You will probably want to `git reset --hard origin/master` in your local repository to fix the mess :-)

Thanks for looking at this - I intend to merge after CI passes.

2022-05-01 07:13 UTC, scherbatey commented
@peterbarker , thank you!

2022-05-01 22:05 UTC, merged