My fixes to #18624
ArduPilot/ardupilot pull request #20695
Opened 2022-05-04 14:29 UTC by Hwurzburg

I am still lost on how terrain following really works and altitude  ref frames,etc.    but I played around with @IamPete1 PR for days until I got it to work.....probably inefficient, but it does work now...added the ability to use therc switch for terrain  disable in Loiter also....had a hard time making things work on every entry into Loiter in every situation...
SITL tested using the elev stick and changing into and out of Loiter for every case:
-normal mode
-terrain follow in Loiter
-the above with and without alt control

I also felt that we need to maintain current behavior,unless the option bit is set to allow alt control,instead of changing default behavior to have it enabled by default

purposely left each commit unsquashed so that they could be modified easily....as I said, I wacked at it until it worked,not knowinng in depth what I was doing...but I want this functionality for FPV video work

2022-05-10 00:10 UTC, tridge requested changes

2022-05-10 00:10 UTC, tridge commented on ArduPlane/Attitude.cpp
> +    int16_t elevator = SRV_Channels::get_output_scaled(SRV_Channel::k_elevator);
should be float

2022-05-10 00:12 UTC, tridge commented
please adjust comment on update_fbwb_speed_height to include LOITER

2022-05-10 12:57 UTC, Hwurzburg commented on ArduPlane/Attitude.cpp
> +    int16_t elevator = SRV_Channels::get_output_scaled(SRV_Channel::k_elevator);
done

2022-05-22 02:09 UTC, tridge approved these changes

2022-05-22 02:09 UTC, tridge commented
flight tested on a striver mini quadplane, with and without FLIGHT_OPTIONS bit set
all good!

2022-05-22 02:09 UTC, merged