Copter: fix bug for heli takeoff in guided mode
ArduPilot/ardupilot pull request #20742
Opened 2022-05-11 22:40 UTC by bnsgeyer

This fixes the bug identified [here](https://discuss.ardupilot.org/t/heli-frame-prearm-internal-error-0x100000-l-602-flow-of-ctr/85172).  The issue was an internal error that occurred when attempting a guided mode takeoff for heli.  The user determined that the position controller was not being initialized.  It was further discovered that this was also occurring when attempting auto takeoff when the aircraft was armed in auto mode and interlock was enable to initiate takeoff.

This has been tested in SITL and verified that it fixes both issues.

2022-05-12 03:44 UTC, rmackay9 commented on ArduCopter/takeoff.cpp
> +        pos_control->update_xy_controller();
maybe there should be a relax_z_controller() call here as well?  Maybe some or all of these?

        pos_control->relax_velocity_controller_xy();
        pos_control->update_xy_controller();
        pos_control->relax_z_controller(0.0f);   // forces throttle output to decay to zero
        pos_control->update_z_controller();
        attitude_control->reset_yaw_target_and_rate();
        attitude_control->reset_rate_controller_I_terms();
        attitude_control->input_thrust_vector_rate_heading(pos_control->get_thrust_vector(), auto_yaw.rate_cds());

2022-05-12 04:12 UTC, rmackay9 commented on ArduCopter/takeoff.cpp
> +            pos_control->relax_velocity_controller_xy();
I think "pos_control->update_xy_controller()" can be removed here because it will be called a few lines lower down.

2022-05-13 14:32 UTC, lthall requested changes

2022-05-13 14:32 UTC, lthall commented on ArduCopter/takeoff.cpp
> +        if (!pos_control->is_active_xy()) {
This should not be needed. We only call this from Auto and Guided so both should already be initialised.

How do we get here in throttle unlimited without initialising? That is where we need to fix this.

2022-05-13 15:10 UTC, lthall commented
Ok, after chatting to Bill I understand the problem. We need to add this:

        pos_control->relax_velocity_controller_xy();
        pos_control->update_xy_controller();

here:
https://github.com/ArduPilot/ardupilot/blob/53f931c98dbd4441ce4b7130e76a8334d50eea0c/ArduCopter/mode.cpp#L546

I think this is all we need to do but there are two places where I suspect we should remove the following init linies:
https://github.com/ArduPilot/ardupilot/blob/53f931c98dbd4441ce4b7130e76a8334d50eea0c/ArduCopter/mode_auto.cpp#L903
https://github.com/ArduPilot/ardupilot/blob/53f931c98dbd4441ce4b7130e76a8334d50eea0c/ArduCopter/mode_auto.cpp#L1000
https://github.com/ArduPilot/ardupilot/blob/53f931c98dbd4441ce4b7130e76a8334d50eea0c/ArduCopter/mode_brake.cpp#L40

This one may need a make_safe_ground_handling();:
https://github.com/ArduPilot/ardupilot/blob/53f931c98dbd4441ce4b7130e76a8334d50eea0c/ArduCopter/mode_auto.cpp#L1026

2022-05-13 20:02 UTC, andyp1per commented
Given that the fix affects all frames in all modes it might be worth changing the title :)

2022-05-13 23:05 UTC, bnsgeyer commented
> Given that the fix affects all frames in all modes it might be worth changing the title :)

Title of the PR or the commit. I’m assuming PR

2022-05-13 23:46 UTC, lthall approved these changes
I think this is good with the extra line removed that I highlighted.

2022-05-13 23:46 UTC, lthall commented on ArduCopter/mode_brake.cpp
>          pos_control->relax_z_controller(0.0f);
We can remove this line too.

2022-05-14 03:16 UTC, merged

2022-05-14 03:16 UTC, rmackay9 commented
Merged, thanks!