Ap get autotune channel from r cx option
ArduPilot/ardupilot pull request #20755
Opened 2022-05-13 22:21 UTC by muramura

#20303
I changed the AUTOTUNE channel to get it from RCx_OPTION.

2022-05-14 13:20 UTC, amilcarlucas approved these changes
looks good

2022-05-16 09:41 UTC, IamPete1 requested changes
Need to remove this check:
https://github.com/ArduPilot/ardupilot/blob/069b81819d434a0111df223856b6f78fc0dbeb73/ArduCopter/tuning.cpp#L24-L27

2022-05-16 09:41 UTC, IamPete1 commented on ArduCopter/radio.cpp
> +    }
Doesn't look like setting the deadzone does anything as we use the `get_radio_in()` method.

2024-06-05 01:38 UTC, peterbarker requested changes
@muramura I've wanted this for a long time, it would be nice to see it progress.

Even better would be adding support for `KNOB_TUNE2` so people can tune multiple things at once - but that's into the future...

2024-06-05 01:38 UTC, peterbarker commented on ArduCopter/tuning.cpp
> +        rc6 = rc().channel(CH_6);
Let's set the default on RC6_OPTION to be KNOB_TUNE instead of doing this

2024-07-25 04:45 UTC, peterbarker commented
Sadly this one was neglected.

We've just merged a PR to master which adds this behaviour.

Thanks anyway!

2024-07-25 04:45 UTC, closed without merging