Copter: disallow air-mode rudder disarm
ArduPilot/ardupilot pull request #20770
Opened 2022-05-15 15:57 UTC by IamPete1

You can still disarm with airmode active, I guess for the most part the advice would be to disable rudder arming with the param. When enabling airmode with a switch you have both. I have added a message for the airmode switch so its easier to check. 

Of course this does mean that users may no longer be able to disarm....

At least I think the second commit is usefull.

2022-05-15 18:18 UTC, andyp1per commented
Er, why? I do this all the time. Dead against this.

2022-05-15 18:19 UTC, andyp1per requested changes
Please don't!

2022-05-15 18:41 UTC, IamPete1 commented
@andyp1per Do you not find the copter spins round? I was testing 0 throttle full yaw for another PR, I ended up disarming in flight (in SITL). I presume your OK with the second commit?

2022-05-15 19:04 UTC, Hwurzburg commented
this means when you crash in airmode (some fly airmode permanently...I do on many of my miniquads)  and do not use an arm/disarm switch, you can never stop the motors spinning while it sits in a bush? if so, I am against it also...

2022-05-15 19:40 UTC, andyp1per commented
@IamPete1 generally works fine for me - especially if landing has been detected.

Note that I think something has changed recently as I was having trouble with motors spooling down yesterday.

2022-05-15 19:41 UTC, andyp1per commented
Second commit is fine

2022-05-16 00:19 UTC, IamPete1 commented
Copter changes dropped, now only adds the message on switching.

2022-05-16 00:31 UTC, rmackay9 approved these changes

2022-05-16 00:34 UTC, rmackay9 commented
@andyp1per if you've seen problems spooling down recently could you check 4.2 as well to be sure the same issue doesn't happen there?  Not trying to add to your workload but we're getting very close to releasing 4.2 so any extra help in confirming it is OK is greatly appreciated.

2022-05-16 07:04 UTC, andyp1per commented
@rmackay9 when I was flying on Saturday I was definitely seeing issues on 4.3-dev, I can't remember whether I was seeing similar issues on 4.2 - possibly - I was flying rc3 + vib comp + autotune changes.

2022-05-16 07:13 UTC, merged