AP_HAL_ChibiOS: Add on-board baro support to iFlight BeastH7 V2 target.
ArduPilot/ardupilot pull request #20807
Opened 2022-05-19 21:44 UTC by jimsynz

iFlight's own website says that there is no barometer on this device,
however on my one there is a DPS310 connected on I2C.  This PR adds
support for the on-board baro but leaves it as optional.

2022-05-19 21:51 UTC, andyp1per commented
hi @jimsynz - there is already a PR for this, can you try it - https://github.com/ArduPilot/ardupilot/pull/20461
There appear to be more changes than just baro

2022-05-19 22:12 UTC, jimsynz commented
@andyp1per @20461 appears to be for the BeastF7 not the BeastH7

2022-05-20 07:05 UTC, andyp1per commented
My apologies, is it the same IMU? It is not on the F7. There seem to be at least 3 variants of each now.

2022-05-20 08:24 UTC, jimsynz commented
Yeah, their website says MPU6000 in the page title but BMI270 in the specs is right in my case.

2022-05-22 05:09 UTC, jimsynz commented
@andyp1per I've just rebased this against the latest master.  Is there anything else I need to do to get this merged? It'd be nice if it went into the 4.2 release.

2022-06-09 15:02 UTC, andyp1per requested changes

2022-06-10 23:30 UTC, jimsynz commented on libraries/AP_HAL_ChibiOS/hwdef/BeastH7v2/hwdef.dat
> +I2C_ORDER I2C1
Updated. Thanks!

2022-06-11 06:35 UTC, andyp1per approved these changes

2022-06-13 23:46 UTC, tridge approved these changes

2022-06-13 23:46 UTC, merged

2022-06-14 06:47 UTC, andyp1per commented
@rmackay9 probably a candidate for 4.2