Battery: Add Tattu CAN driver
ArduPilot/ardupilot pull request #20824
Opened 2022-05-23 05:50 UTC by magicrub

This adds the proprietary CAN driver for TATTU batteries. Tested by @CraigElder and @alexscheck and @jmachuca77.

2022-05-23 07:08 UTC, rmackay9 commented
I guess this will work with any of the "Smart" Tattu batteries including [this one](https://www.genstattu.com/tattu-plus-1-0-compact-version-16000mah-44-4v-15c-12s1p-lipo-smart-battery-pack-with-as150u-plug/).

2022-05-23 07:57 UTC, jmachuca77 commented
That’s what I tested with

2022-05-23 12:44 UTC, amilcarlucas commented on libraries/AP_BattMonitor/AP_BattMonitor.h
> +    friend class AP_BattMonitor_TattuCAN;
This should be placed after torquedo, for consistency

2022-05-23 13:17 UTC, muramura commented
Why don't you do CRC checks on incoming messages?

2022-05-23 17:05 UTC, hendjoshsr71 commented
Which model #s of batteries does this work on? Need that for documentation so users don't select the wrong driver.

2022-05-23 17:26 UTC, magicrub commented
This driver is hard-coded for the 12S flavor via ```TATTUCAN_CELL_COUNT_12S``` but with minor work from @jmachuca77 it could be more flexible to handle and auto-detect 6S and 14S without needing params.

2022-05-23 17:29 UTC, magicrub commented
> Why don't you do CRC checks on incoming messages?

yup, good point. It's being ignored for now, like all the other non-DroneCAN drivers. It should be easy to add, just need to call ```crc_xmodem()``` . @jmachuca77 I didn't have a battery to test against which is why I ignored it, can you add that in?

2022-05-23 18:09 UTC, WickedShell requested changes

2022-05-23 18:09 UTC, WickedShell commented on libraries/AP_BattMonitor/AP_BattMonitor_TattuCAN.cpp
> +    memcpy((uint8_t*)&_message, data, _message_offset);
Why do we need this memcpy? Why not just have _message and data be a union, and then the only other things you need to store are just the cycle/remaining percentages, which are both currently being read without a semaphore anyway, and could be corrupt readings.

2022-05-23 18:09 UTC, WickedShell commented on libraries/AP_BattMonitor/AP_BattMonitor_TattuCAN.cpp
> +    percentage = _message.remaining_percent;
Same as below, use a copy aside during read rather then directly accessing the `_message` struct which is a memcpy target.

2022-05-23 18:16 UTC, magicrub commented
@jmachuca77 can you take a look at the comments from @WickedShell

2022-05-31 21:54 UTC, magicrub commented on libraries/AP_BattMonitor/AP_BattMonitor_TattuCAN.cpp
> +    percentage = _message.remaining_percent;
This really just needs to be added to AP_BattMonitor::BattMonitor_State since UAVCAN also suffers from this. I can't do a semephore lock here because the backend is declares this function as const so even if it's added to the status (and therefore interim_state) we'll still need to change the backend

2022-05-31 22:45 UTC, WickedShell commented on libraries/AP_BattMonitor/AP_BattMonitor_TattuCAN.cpp
> +    percentage = _message.remaining_percent;
If you have to deconst the function that's still better then the random interrupt. But on first glance I'm not opposed to moving it into the state either, as it does seem odd to split it.

2022-07-01 14:44 UTC, Rataillon commented
Hello, I tried your CAN Drivers with a Smart Tattu 12S battery on a CubePilot Orange but without success. It seems to me that I did not receive any data. Which board did you use for testing it and/or did I miss anything for using it?

2022-07-01 18:52 UTC, magicrub commented
@Rataillon sorry about that, I should close this. This branch is actually an older version of the driver. Try this newer version on my branch magicrub/pr/tattu_can3. I think there's still some testing that is pending on it before I make a new PR for it. Please test!

2022-07-01 18:52 UTC, closed without merging

2022-07-03 21:50 UTC, CraigElder commented
@Rataillon After working with GREPOW directly to support this TattuCAN protocol, we are now helping them implement DroneCAN in their batteries. It is quite close to working. Soon they will only sell DroneCAN batteries and the TattuCAN protocol will be deprecated