Mamba H743v4 Support
ArduPilot/ardupilot pull request #20902
Opened 2022-06-04 11:58 UTC by andyp1per

Fixes #20587

2022-06-08 07:57 UTC, tridge requested changes

2022-06-08 07:57 UTC, tridge commented on libraries/AP_InertialSensor/AP_InertialSensor_BMI270.cpp
> +            return false;
need the continue to cope with bad read of registers

2022-06-08 09:27 UTC, tridge approved these changes

2022-06-08 09:27 UTC, tridge approved these changes

2022-06-08 11:44 UTC, merged

2023-06-22 07:41 UTC, mikhail-kgd commented
Hello

The [Diatone Mamba MK4 H743 v2 Flight Control]( https://www.diatone.us/products/mamba-mk4-h743-v2-flight-control-30mm-m3l)  have moved from the BMP280 barometer to using SPL06 (DPS310).

Please add support to hwdef.dat
BARO DPS310 I2C:0:0x76

[BF Target：MAMBA H743_2022B](https://github.com/betaflight/unified-targets/blob/master/configs/default/DIAT-MAMBAH743_2022B.config)

Thank you a lot!

2023-07-31 18:23 UTC, redbananamoon commented
Hi, is the Mamba MK4 H743 v2 fully supported by this firmware?

2023-07-31 18:49 UTC, andyp1per commented
Yes fully supported. No idea where it went.

2023-07-31 18:51 UTC, redbananamoon commented
That's great! thanks. Are both IMUs used / taken advantage of?