Have AHRS update its own orientation
ArduPilot/ardupilot pull request #20921
Opened 2022-06-06 10:48 UTC by peterbarker

We can have the library do this itself rather than having the vehicles each do it separately.

2022-06-06 11:06 UTC, peterbarker commented
We have an autotest for this.  I also tested with MAVProxy's horizon module, setting AHRS_ORIENTATION to 42 and then back to 0.

2022-06-07 00:35 UTC, tridge requested changes

2022-06-07 00:35 UTC, tridge commented on libraries/AP_AHRS/AP_AHRS_Backend.cpp
> +    // never update while armed - unless we've never updated
breaks changes to custom orientations?

2022-06-07 01:43 UTC, peterbarker commented on libraries/AP_AHRS/AP_AHRS_Backend.cpp
> +    // never update while armed - unless we've never updated
Fixed.

2022-06-07 01:43 UTC, peterbarker commented
This does have a behavioral change.  Like blimp, sub and Copter, Rover, Plane and Tracker won't update the board orientation while armed.

2022-06-08 07:04 UTC, tridge commented
what testing has been done?

2022-06-08 07:05 UTC, tridge approved these changes

2022-06-12 07:32 UTC, merged

2022-06-12 12:11 UTC, Hwurzburg commented
@peterbarker this does not determine the orientation automatically during cal does it?