AP_SCripting: POC using Lua for arming checks
ArduPilot/ardupilot pull request #20930
Opened 2022-06-07 23:33 UTC by timtuxworth

This is a proof of concept for comment for an approach to using lua script to implement arming-checks.

This will allow arming checks to be customizable, and configurable. Checks can be flagged individually as "ERROR" (prevents arming) or WARNING - notifies the grounds station, but arming is allowed. 

It will also be possible to easily add or remove checks, for example some partners may want very strict arming checks, some developers may want a more "buyer beware" approach. This accommodates both.

2022-06-08 08:37 UTC, amilcarlucas requested changes

2022-06-08 08:37 UTC, amilcarlucas commented on libraries/AP_Scripting/applets/arming-checks.lua
> +-- so we don't want to bake them into the firmward. Requres SCR_ENABLE =1 so must
```suggestion
-- so we don't want to bake them into the firmware. Requires SCR_ENABLE =1 so must 
```

2022-06-08 08:37 UTC, amilcarlucas commented on libraries/AP_Scripting/generator/description/bindings.desc
> -
This change is probably unintended

2022-06-08 14:27 UTC, timtuxworth commented on libraries/AP_Scripting/generator/description/bindings.desc
> -
agreed - thanks

2025-04-23 01:51 UTC, timtuxworth commented
Replaced by https://github.com/ArduPilot/ardupilot/pull/29657

2025-04-23 01:51 UTC, closed without merging