Adds fixes for CubeOrange+ and Parameter updates for CubeOrange and related boards
ArduPilot/ardupilot pull request #20931
Opened 2022-06-08 02:59 UTC by bugobliterator

```
2 EKFs
START=0x30000000 LEN=256k FREE=   328 LRG=   328 TYPE=0
START=0x20000000 LEN=128k FREE= 50760 LRG= 50760 TYPE=2
START=0x24000000 LEN=512k FREE=315360 LRG=315344 TYPE=4
START=0x00000400 LEN= 63k FREE= 64504 LRG= 64504 TYPE=2
START=0x30040000 LEN= 32k FREE= 32760 LRG= 32760 TYPE=0
START=0x38000000 LEN= 64k FREE= 56296 LRG= 55448 TYPE=1

3EKFs
START=0x30000000 LEN=256k FREE=   328 LRG=   328 TYPE=0
START=0x20000000 LEN=128k FREE= 39424 LRG= 39424 TYPE=2
START=0x24000000 LEN=512k FREE=315360 LRG=315344 TYPE=4
START=0x00000400 LEN= 63k FREE= 64504 LRG= 64504 TYPE=2
START=0x30040000 LEN= 32k FREE= 32760 LRG= 32760 TYPE=0
START=0x38000000 LEN= 64k FREE= 56296 LRG= 55448 TYPE=1
```

2022-06-08 03:52 UTC, rmackay9 commented
No need to default the GPS_TYPE = 9?

2022-06-08 04:15 UTC, bugobliterator commented
> GPS_TYPE

Might be a good idea  to add UAVCAN GPS as part of autodetection as well, what do you think?

2022-06-08 06:07 UTC, rmackay9 commented
@bugobliterator that sounds like a good idea to me if it can be done.  I know we took NMEA out of the auto detection but I think maybe that was because of false positives.

2022-06-22 08:02 UTC, tridge commented on libraries/AP_HAL_ChibiOS/hwdef/CubeOrange/defaults.parm
> +BATT2_MONITOR 4
this will give arming failure after this PR:
https://github.com/ArduPilot/ardupilot/pull/21012

2022-06-22 08:03 UTC, tridge commented on libraries/AP_HAL_ChibiOS/hwdef/CubeOrange/defaults.parm
> +GPS_TYPE2 9
please check this doesn't lead to arming check failure with 1 GPS

2022-07-13 07:36 UTC, tridge approved these changes

2022-07-13 07:47 UTC, tridge commented on libraries/AP_HAL_ChibiOS/hwdef/CubeOrange/defaults.parm
> +GPS_TYPE 9
this will break a lot of existing setups that use serial GPS (eg. F9P) on CubeOrange

2022-07-13 07:47 UTC, tridge requested changes
need to think more about GPS_TYPE

2022-07-25 02:52 UTC, bugobliterator commented
> need to think more about GPS_TYPE

I have added patch to do UAVCAN GPS auto detection as well. This way the GPS_TYPE can stay as AUTO DETECT.

There is one TODO here I think, basically as it stands now, user can't have GPS connected at Serial_GPS1 and CAN GPS as GPS1 work at the same time. That has always been the case, so its not a functional change, just something we might want to add support for at some point.

2024-01-22 05:08 UTC, closed without merging