AP_RangeFinder: Add TeraRanger Neo Rangefinder
ArduPilot/ardupilot pull request #20983
Opened 2022-06-15 17:06 UTC by Hwurzburg

New rangefinder....sample will be sent to me for testing in early July...@tridge will share spec directly to you...would appreciate a cursory review since this is my first driver....thanks

2022-07-31 13:40 UTC, Hwurzburg commented
Works perfectly on the bench....will flight test for autoland next

2022-08-01 23:29 UTC, tridge requested changes

2022-08-01 23:29 UTC, tridge commented on libraries/AP_RangeFinder/AP_RangeFinder.cpp
> +#if AP_RANGEFINDER_TERARANGER_SERIAL_ENABLED
the #if needs to be one line down

2022-08-01 23:42 UTC, Hwurzburg commented on libraries/AP_RangeFinder/AP_RangeFinder.cpp
> +#if AP_RANGEFINDER_TERARANGER_SERIAL_ENABLED
done

2022-08-04 15:36 UTC, Hwurzburg commented
@tridge ready to merge....flight tested....matches terrain height very well...leads baro alt a bit as expected ....height clamp works as expected....while it can measure the 30m max, its really only reliable to 22m, which is still pretty good...

![Screenshot from 2022-08-04 10-29-58](https://user-images.githubusercontent.com/6076534/182887622-b770136f-21cd-49d0-84eb-3909a8c134af.png)
![Screenshot from 2022-08-04 10-31-03](https://user-images.githubusercontent.com/6076534/182887625-207b573a-3884-4036-a4b7-d29ec197c959.png)

2022-08-08 23:01 UTC, tridge approved these changes

2022-08-08 23:01 UTC, merged