Triple harmonic notch
ArduPilot/ardupilot pull request #21026
Opened 2022-06-23 16:58 UTC by andyp1per

Just experimenting for now

2022-06-28 09:49 UTC, lthall commented
I have looked at the performance of the triple notch compared to the double and single.
Fs = 2000; 
filter_Hz = 100;
band_Hz = filter_Hz*(1/2);
attenuation_dB = 40;

![image](https://user-images.githubusercontent.com/100896/176149313-44ac2f58-3f58-4f29-8381-8fda52c85678.png)

![image](https://user-images.githubusercontent.com/100896/176149500-17810daa-f227-47ce-98c5-3ee86fbda1c6.png)

2022-06-28 09:53 UTC, lthall reviewed
Love it.

2022-06-28 09:53 UTC, lthall approved these changes

2022-06-28 11:40 UTC, Hwurzburg requested changes

2022-06-28 11:40 UTC, Hwurzburg commented on libraries/Filter/HarmonicNotchFilter.cpp
> +    // @Bitmask: 0:Double notch,1:Dynamic harmonic,2:Update at loop rate,3:EnableOnAllIMUs,4:Triple notch
```suggestion
    // @Bitmask: 0:Double notch,1:Dynamic harmonic,2:Update at loop rate,3:EnableOnAllIMUs,4:Triple notch-overrides bit 0
```

2022-06-28 14:46 UTC, Hwurzburg approved these changes

2022-07-03 08:21 UTC, tridge approved these changes

2022-07-03 08:21 UTC, merged