Run MatekH743 at 480Mhz
ArduPilot/ardupilot pull request #21036
Opened 2022-06-25 09:40 UTC by andyp1per

The board uses rev V exclusively and so can be run at the default clock of 480Mhz

2022-06-25 13:48 UTC, MallikarjunSE commented
> The board uses rev V exclusively and so can be run at the default clock of 480Mhz

I have MatekH743 mini. It already runs quite hot. Probably should consider temps at 480Mhz?

2022-06-25 13:54 UTC, andyp1per commented
Seems strange that the MCU temp would be a problem - it's supposed to run at 480Mhz

2022-06-26 01:26 UTC, muramura commented
Will this 480 MHz continue to operate as is?
CUBEORANGE uses the STM32H7.
However, it is set to 400MHz from the guarantee of operation due to self-heat.
If the heat dissipation fins are necessary due to self-heat, it is better not to increase the clock.

2022-06-26 08:04 UTC, andyp1per commented
> However, it is set to 400MHz from the guarantee of operation due to self-heat.

I believe that actually its set to 400Mhz because some chips are rev X and Y - and these revs have a bug which mean they don't work at 480Mhz.

2022-06-26 10:50 UTC, muramura commented
@andyp1per san
I would like this FC without heat dissipation fins, running at 480 MHz, if that's ok.
However, if it is necessary to add heat dissipation fins by clocking up, I think it is better not to clock up.

2022-06-26 11:46 UTC, andyp1per commented
> I would like this FC without heat dissipation fins, running at 480 MHz, if that's ok.

There is no need for cooling fins - this part is rated up to 85C ambient at full power.

2022-06-26 23:53 UTC, muramura commented
Does 85 degrees mean operating temperature?
This is not the maximum self-heating temperature.

2022-06-27 06:38 UTC, andyp1per commented
Ambient - the surrounding air temperature

2022-07-06 07:39 UTC, tridge commented
I think this needs to be a Tools/scripts/build_options.py option

2022-07-06 07:44 UTC, tridge requested changes
better as a custom build server option, AP_H743_FAST_ENABLE = 0/1

2024-09-28 16:53 UTC, closed without merging