SIM_Precland: set z component of origin vector separately
ArduPilot/ardupilot pull request #21133
Opened 2022-07-06 15:50 UTC by shiv-tyagi

This change serves as a workaround for the problem of different EKF origin altitudes for rovers and copters.
The position vector passed to update method is relative to home and the origin height is also relative to home. Hence, we
can set the height of origin center separately which when subtracted from position vector will give position of vehicle
relative to home.

2022-08-02 04:21 UTC, peterbarker requested changes
commit message should be prefixed with SITL

2022-08-02 09:50 UTC, peterbarker approved these changes
LGTM

2022-08-02 23:21 UTC, khancyr reviewed
So with this change we cannot simulate base station where the precland beacon isn't on the ground but at some alt, right ?
That looks a regression

2022-08-03 02:21 UTC, shiv-tyagi commented
@khancyr No, we can of course set it. This change just make the calculations independent of ekf origin alt value (which is different for copter and rover right now). The `_origin_height` is already relative to home, so we can just set it directly in a 3D vector for position of beacon relative to home. So, the x,y components come from a 2D vector relative to home and the z is set directly to `-_origin_height` (which is already relative to home).

2022-08-05 00:17 UTC, merged