20220706 landing limits bug
ArduPilot/ardupilot pull request #21131
Opened 2022-07-06 12:08 UTC by lthall

This PR fixes a confusing naming convention that resulted in limits being ignored when they shouldn't have been and visa versa.

It also adds total velocity limits to ensure maximums are not exceeded after position errors are created.

2022-07-26 00:24 UTC, lthall commented on libraries/AP_Math/control.cpp
> + The correction acceleration can is limited to accel_max to accel_min. If limit_total_accel is true the total acceleration is limited to accel_max to accel_min.
Fix comment to remove: limit_total_accel

2022-07-26 00:27 UTC, tridge commented
need to test on quadplanes, see if this negative impact on quadplane back transition

2022-07-28 09:07 UTC, lthall commented
Before:
![image](https://user-images.githubusercontent.com/100896/181466676-50b850a6-b9bd-4bad-9462-8ddc1d00e105.png)
After:
![image](https://user-images.githubusercontent.com/100896/181467553-cf5aeb90-e3dd-479d-a01b-ce2a72d8925b.png)

2022-07-31 21:03 UTC, IamPete1 approved these changes
Looks good. I don't think this will affect quadplane because it is only used in position input methods `input_pos_xyz` and `input_pos_vel_accel_xy`. Quadplane does use them, but only in final landing not transition/approach stuff. Always worth double checking in the sim tho....

2022-08-01 01:53 UTC, lthall commented on libraries/AP_Math/control.h
> + The correction acceleration can is limited to accel_max to accel_min. If limit_total_accel is true the total acceleration is limited to accel_max to accel_min.
yuck! Nice catch!

2022-08-01 01:53 UTC, lthall commented on libraries/AP_Math/control.h
> + The correction acceleration can is limited to accel_max to accel_min. If limit_total_accel is true the total acceleration is limited to accel_max to accel_min.
yuck! Nice catch!

2022-08-01 01:54 UTC, lthall commented on libraries/AP_Math/control.cpp
> +    if (limit_total && is_negative(vel_min) && is_positive(vel_max)){
Thanks, I did this in a few places.

2022-08-02 00:02 UTC, davidbuzz commented
@lthall offered beers to ppl that fix his comments, i heard him say it.  honest. :-)

2022-08-02 00:05 UTC, tridge requested changes

2022-08-02 00:05 UTC, tridge commented on libraries/AP_Math/control.cpp
> +    maximum acceleration - accel_min, accel_max,
there is no accel_min or accel_max in this function?

2022-08-02 00:05 UTC, tridge commented on libraries/AP_Math/control.cpp
> +    maximum velocity - vel_min, vel_max,
there is no vel_min and vel_max

2022-08-02 00:05 UTC, tridge commented on libraries/AP_Math/control.h
> +    maximum acceleration - accel_min, accel_max,
there is no accel_min and accel_max

2022-08-02 00:05 UTC, tridge commented on libraries/AP_Math/control.h
> +    maximum velocity - vel_min, vel_max,
there is no vel_min and vel_max

2022-08-02 21:31 UTC, IamPete1 approved these changes

2022-08-05 08:32 UTC, closed without merging