AP_Motors: reuse spool_step for code refactoring
ArduPilot/ardupilot pull request #21143
Opened 2022-07-08 02:42 UTC by chobitsfan

I think it may improve code readability
tested on CubeBlack
[2022-07-08 10-28-02.zip](https://github.com/ArduPilot/ardupilot/files/9068482/2022-07-08.10-28-02.zip)

2022-07-08 03:56 UTC, rmackay9 approved these changes

2022-07-08 03:56 UTC, rmackay9 commented
Looks good to me thanks!

2022-07-08 10:55 UTC, IamPete1 approved these changes
Change looks good, you could make it const if you like.

2022-07-08 10:55 UTC, IamPete1 commented on libraries/AP_Motors/AP_MotorsMulticopter.cpp
> +    float spool_step = 1.0f / (_spool_up_time * _loop_rate);
```suggestion
    const float spool_up_step = 1.0f / (_spool_up_time * _loop_rate);
```

2022-07-08 13:35 UTC, chobitsfan commented on libraries/AP_Motors/AP_MotorsMulticopter.cpp
> +    float spool_step = 1.0f / (_spool_up_time * _loop_rate);
Yes, it is better with const. Thank you

2022-07-08 18:32 UTC, Gone4Dirt requested changes

2022-07-09 05:23 UTC, chobitsfan commented on libraries/AP_Motors/AP_MotorsMulticopter.cpp
> +    const float spool_up_step = 1.0f / (_spool_up_time * _loop_rate);
Thank you. it is a typo

2022-07-10 23:39 UTC, merged

2022-07-10 23:39 UTC, rmackay9 commented
Merged, thanks!