Add build option for Ublox
ArduPilot/ardupilot pull request #21175
Opened 2022-07-13 12:12 UTC by Hwurzburg

mate to #20528

2022-07-14 08:38 UTC, amilcarlucas approved these changes

2022-07-14 22:38 UTC, peterbarker requested changes
Thanks for doing this, Henry.

I wonder if we really should default this to on.... probably....

2022-07-14 22:38 UTC, peterbarker commented on Tools/scripts/build_options.py
> +    Feature('GPS Drivers', 'Ublox', 'AP_GPS_UBLOX_ENABLED', 'Enable Ublox GPS', 1, 'None'),
```suggestion
    Feature('GPS Drivers', 'UBLOX', 'AP_GPS_UBLOX_ENABLED', 'Enable u-blox GPS', 1, None),
```

(that's apparently they way they branch their GPS, caps-wise...)

2022-07-16 03:32 UTC, peterbarker requested changes
commit message needs to be prefixed with `Tools: build_options.py: `

2022-07-16 03:40 UTC, Hwurzburg commented
duh, sorry...fixed

2022-07-16 03:43 UTC, peterbarker approved these changes
LGTM

2022-07-18 15:50 UTC, merged