Copter: takeoff check that motors are spinning at TKOFF_RPM_MIN
ArduPilot/ardupilot pull request #21223
Opened 2022-07-19 11:16 UTC by rmackay9

This is an alternative implementation of PR https://github.com/ArduPilot/ardupilot/pull/20856

This adds a Copter takeoff check that all motors are spinning at at least TKOFF_RPM_MIN

- AP_ESC_Telem gets new is_telemetry_active() and are_motors_running() methods
- AP_Motors gets new get/set_spoolup_block() methods to allow an external caller to stop the motors from spooling up to THROTTLE_UNLIMITED.  This is done by ignoring calls to get_desired_spool_state(THROTTLE_UNLIMITED) if the block is true.  This should be safe because it essentially only blocks the motors from spooling up if they haven't spooled up already.  Even if the block is set while the vehicle is armed and flying, it won't immediately cause the motors to spool down.
- Copter::takeoff_check is added to set the motors block if the vehicle is armed and landed AND ESC telemetry is inactive or the RPM is below TKOFF_RPM_MIN
- Stabilize and Acro are modified to send zero throttle to the attitude control until the spool state has created unlimited

This has been lightly tested in SITL.  We need to test all modes for both multicopter and helicopter to confirm it really does keep the vehicle on the ground.

2022-07-19 13:17 UTC, andyp1per requested changes
Needs an autotest, you should be able to leverage the one I had

2022-07-19 13:17 UTC, andyp1per commented on ArduCopter/Copter.h
> +    uint32_t takeoff_check_warning_ms;  // system time since user was warning of takeoff check failure
comment typo

2022-07-20 00:37 UTC, rmackay9 commented
@andyp1per,

Txs for the review and feedback.  Yes, OK, we could modify the check so that it only runs for the first takeoff after arming.  So it would not run again if the vehicle landed and took off again (without a disarm in between).

2022-07-21 11:05 UTC, rmackay9 commented on ArduCopter/Copter.h
> +    uint32_t takeoff_check_warning_ms;  // system time since user was warning of takeoff check failure
great, thanks, fixed.

2022-07-21 11:37 UTC, rmackay9 commented
@andyp1per,

OK, I think I have changed the feature so it only triggers the takeoff check on the first takeoff after arming.

2022-07-21 19:46 UTC, andyp1per commented
I tested this by disabling ESC telemetry and setting bdshot to only 3 channels. This worked quite well - as soon as I armed I got repeated messages about takeoff block and I could not takeoff. I was expecting the error when I raised the through though - is this how you intended it to work?

2022-07-21 23:24 UTC, rmackay9 commented
@andyp1per,

Thanks very much for giving it a try.

Yes, that's how it's written at least.  The message appears every 3 seconds and it starts appearing 3 seconds after arming.  It doesn't wait until the pilot actually tries to takeoff but I didn't think that was necessary because the motors should spool up to the TKOFF_RPM_MIN as part of arming.

Maybe we should slow down the messages to once every 5 sec..

2022-07-22 07:05 UTC, andyp1per commented
I can't approve until it has a test 😄

2022-07-22 07:42 UTC, rmackay9 commented
@andyp1per,

It's hard for me not to be snarky considering I've attempted to get this working PR to pass the existing tests at least 4 times..

2022-07-22 08:09 UTC, andyp1per commented
> It's hard for me not to be snarky considering I've attempted to get this working PR to pass the existing tests at least 4 times.. know anything about the "DynamicRpmNotches" test?

LOL. I do and actually your PR affects the SITL behaviour that is used for that test, so it could be related. Of all of the noise type tests that one should be the most reliable - so if it is failing there may be a genuine problem

2022-07-22 08:10 UTC, andyp1per commented
Note that the test is retried 8 times, so if it still failing I think there is likely a genuine problem

2022-08-22 01:28 UTC, rmackay9 commented
Closing in favour of @andyp1per PR https://github.com/ArduPilot/ardupilot/pull/21499

2022-08-22 01:28 UTC, closed without merging