AP_Motors: refactor motor matrix to cleanup and make symbols
ArduPilot/ardupilot pull request #21327
Opened 2022-08-01 22:32 UTC by Hwurzburg

Allows searching for frame type build options in the ELF file

2022-08-02 20:25 UTC, IamPete1 requested changes
Costing more flash than I would have guessed, I suppose the whole point was to add symbols to the elf....

2022-08-02 20:25 UTC, IamPete1 commented on libraries/AP_Motors/AP_MotorsMatrix.cpp
> +        _mav_type = MAV_TYPE_GENERIC;
I'm not a fan of this change.

2022-08-02 20:25 UTC, IamPete1 commented on libraries/AP_Motors/AP_MotorsMatrix.cpp
> +        break;
again not a fan of the above white space changes.

2022-08-02 20:25 UTC, IamPete1 commented on libraries/AP_Motors/AP_MotorsMatrix.cpp
> +    bool success = true;
don't need this bool, the same for all of them.

2022-08-02 20:25 UTC, IamPete1 commented on libraries/AP_Motors/AP_MotorsMatrix.cpp
> +        break;
```suggestion
        return false;
```

2022-08-02 20:25 UTC, IamPete1 commented on libraries/AP_Motors/AP_MotorsMatrix.cpp
> +    return success;
```suggestion
    return true;
```

2022-08-02 20:25 UTC, IamPete1 commented on libraries/AP_Motors/AP_MotorsMatrix.cpp
> +        _mav_type = MAV_TYPE_QUADROTOR;
why not move these two down into the new method? (same for all)

2022-08-02 20:25 UTC, IamPete1 commented on libraries/AP_Motors/AP_MotorsMatrix.h
> +
unneeded white space change.

2022-08-02 21:20 UTC, Hwurzburg commented on libraries/AP_Motors/AP_MotorsMatrix.h
> +
removed

2022-08-03 21:53 UTC, Hwurzburg commented
rebased after @andyp1per recent changes

2022-08-05 16:22 UTC, IamPete1 approved these changes
LGTM, thanks

2022-08-09 00:06 UTC, merged

2022-08-09 00:08 UTC, rmackay9 approved these changes