AP_Periph: can_printf() to send longer strings using multiple packets
ArduPilot/ardupilot pull request #21335
Opened 2022-08-02 23:29 UTC by magicrub

can_printf() to send longer strings using multiple packets.

Sends multiple debug_LogMessage packets if the fmt string is too long.

2022-08-23 00:23 UTC, tridge requested changes
i don't think this is worth the flash space

2022-08-23 00:30 UTC, magicrub commented
per devcall, change to define opt-in

2022-08-23 00:31 UTC, peterbarker commented
This will be good if it comes in as an hwdef-enabled option

2022-10-12 21:11 UTC, bugobliterator commented
@magicrub can you enable this on CubeOrange-periph and periph-heavy as well?

2022-10-13 18:19 UTC, magicrub commented
> @magicrub can you enable this on CubeOrange-periph and periph-heavy as well?

By default all 1 MB periph boards have this enabled.
```#define HAL_PERIPH_SUPPORT_LONG_CAN_PRINTF (BOARD_FLASH_SIZE >= 1024)```

2022-10-13 18:25 UTC, magicrub commented
I just touched up the code comment at the define to help explain the feature

2022-10-19 13:14 UTC, bugobliterator approved these changes

2022-10-24 04:47 UTC, merged