Fast ICM42xxx performance
ArduPilot/ardupilot pull request #21342
Opened 2022-08-03 11:31 UTC by andyp1per

At faster gyro backend rates (e.g. 4khz) the per-tick CPU load becomes quite important. This change reduces the CPU load a couple of ways:

- Increases the SPI clock on the MatekH743 to 24Mhz for the ICM42xxx gyros which are rated at this speed. This gives about a 30% reduction in per-tick time.
- Synchronizes the ticks with the data. Before there were a lot of redundant ticks because data wasn't quite ready. Now the next tick is calculated from the time at which data is received.
- Reduces the FIFO buffer size since only 1 sample is ever needed
- Increases the RCOUT priority to make sure that the motors are not starved of CPU cycles when the gyros are operating at a very fast frequency.

2022-08-03 14:34 UTC, timtuxworth commented
Would this also apply for the Zealot H743 which has a ICM-42688-P?

2022-08-03 14:37 UTC, andyp1per commented
> Would this also apply for the Zealot H743 which has a ICM-42688-P

Yes, but manufacturer would need to confirm it is safe

2022-08-03 14:40 UTC, timtuxworth commented
> > Would this also apply for the Zealot H743 which has a ICM-42688-P
> 
> Yes, but manufacturer would need to confirm it is safe

I've checked with QIo-Tek, they say this fix isn't necessary because their design doesn't have the problem this is fixing.

2022-08-03 14:44 UTC, andyp1per commented
> I've checked with QIo-Tek, they say this fix isn't necessary because their design doesn't have the problem this is fixing.

Which can only mean they are not using this chip

2022-08-03 15:24 UTC, QioTek commented
> > I've checked with QIo-Tek, they say this fix isn't necessary because their design doesn't have the problem this is fixing.
> 
> Which can only mean they are not using this chip

It needs to be tested. Will higher sampling make the sampling accuracy of the sensor different? We haven't conducted actual hardware testing yet. We need to compare with the previous sampling speed.

2022-08-03 15:30 UTC, andyp1per commented
> It needs to be tested. Will higher sampling make the sampling accuracy of the sensor different? We haven't conducted actual hardware testing yet. We need to compare with the previous sampling speed.

For the 42688 the sampling is all done at 32Khz regardless of ODR. Higher ODR allows higher AP filter settings. This issue is addressing some issues that might be seen with higher ODR - mostly because the tick latency becomes more important

2022-08-07 16:25 UTC, andyp1per commented
Flew four batteries on this today - all worked great

2022-08-10 07:07 UTC, tridge requested changes

2022-08-10 07:07 UTC, tridge commented on libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.cpp
> +#define INV3_FIFO_BUFFER_LEN 2
i'd be worried about getting behind

2022-08-10 07:15 UTC, andyp1per commented on libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.cpp
> +#define INV3_FIFO_BUFFER_LEN 2
Fixed

2022-08-12 10:53 UTC, tridge approved these changes

2022-08-12 10:53 UTC, tridge commented
tested on Pixhawk6X, works well!

2022-08-12 10:53 UTC, merged