AP_Scripting: support int32 userdata
ArduPilot/ardupilot pull request #21391
Opened 2022-08-10 00:23 UTC by IamPete1

Adds int32 userdata support, sill need to add the magic uint32 function to convert to a arbitrary length int. Found a few flash savings in the existing bindings, but this still costs a fair bit.

Not tested at all.

2022-08-10 01:21 UTC, WickedShell commented
The motivator appears to be some oddities with using literals in scripts, aggravated by rejecting negative integer values. Given the need to have useful literals it might be better to just remove this negative check for uint32_t boxed types.

2022-08-10 22:26 UTC, IamPete1 commented
Example test script: 

```
  local f = uint32_t(4157483647)
  gcs:send_text(0, string.format("uint32_t(4157483647):toint() = %i", f:toint()) .. " string: " .. tostring(f))

  local f = uint32_t(10472251) * uint32_t(397)
  gcs:send_text(0, string.format("(uint32_t(10472251) * uint32_t(397)):toint() = %i", f:toint()) .. " string: " .. tostring(f))


  local f = uint32_t(-137483649)
  gcs:send_text(0, string.format("uint32_t(-137483649):toint() = %i", f:toint()) .. " string: " .. tostring(f))
```

2022-08-11 00:04 UTC, WickedShell requested changes

2022-08-11 00:04 UTC, WickedShell commented on libraries/AP_Scripting/lua_boxed_numerics.cpp
> +        if (success && v >= INT32_MIN) {
```suggestion
        if (success) {
```

I'm pretty sure you are accidentally forcing a number of things into the float path at the moment? I was suggesting as long as we were passed an integer we just cast it, what you have here is ignoring many integer cases....

2022-08-11 00:04 UTC, WickedShell commented on libraries/AP_Scripting/lua_boxed_numerics.cpp
> +        if (success && v >= float(INT32_MIN) && v <= float(UINT32_MAX)) {
Same question as above.

2022-08-11 20:26 UTC, IamPete1 commented on libraries/AP_Scripting/generator/src/main.c
> +  fprintf(source, "int binding_argcheck(lua_State *L, int expected_arg_count) {\n");
To get it to build without lots of fiddling. Any reason it needs to be static?

2022-08-12 09:20 UTC, IamPete1 commented
```
Binary Name      Text [B]         Data [B]     BSS (B)        Total Flash Change [B] (%)      Flash Free After PR (B)
---------------  ---------------  -----------  -------------  ----------------------------  -------------------------
antennatracker   -988 (-0.0729%)  0 (0.0000%)  -4 (-0.0015%)  -988 (-0.0728%)                                  610524
arducopter-heli  -988 (-0.0553%)  0 (0.0000%)  -4 (-0.0015%)  -988 (-0.0552%)                                  175748
ardurover        -988 (-0.0615%)  0 (0.0000%)  4 (+0.0015%)   -988 (-0.0615%)                                  359660
arducopter       -988 (-0.0555%)  0 (0.0000%)  4 (+0.0015%)   -988 (-0.0554%)                                  182956
ardusub          -988 (-0.0631%)  0 (0.0000%)  -4 (-0.0015%)  -988 (-0.0630%)                                  398760
blimp            -988 (-0.0762%)  0 (0.0000%)  4 (+0.0015%)   -988 (-0.0761%)                                  668376
arduplane        -988 (-0.0560%)  0 (0.0000%)  4 (+0.0015%)   -988 (-0.0559%)                                  200196
```

2022-08-12 09:24 UTC, IamPete1 commented on libraries/AP_Scripting/generator/src/main.c
> +  fprintf(source, "int binding_argcheck(lua_State *L, int expected_arg_count) {\n");
I would argue that none of the other functions we define in the header are static, that is the new and check functions for userdata and the load functions.

2022-08-16 01:40 UTC, tridge commented
local foo = uint32(0xF000,0x7)

2022-08-16 12:56 UTC, IamPete1 commented
Dropped controversial signed vs unsigned thing, now just the flash savings.

I will investigate the cost of moving to doubles in lua vs keeping uint32.

2022-08-16 16:49 UTC, WickedShell commented
> we could check if the constructor has 2 arguments we can do: local foo = uint32_t(0xF000, 0x0007) that would create 0xF0000007

Why not accept 0xFFFFFFFF directly? The compiler will turn it into -1 but that will be an integer literal? That's how normal lua code works at that point, and is far clearer...

2022-08-17 07:18 UTC, tridge approved these changes

2022-08-17 07:18 UTC, merged