AP_NavEKF3: Enable External Nav feature if Visual Odometry enabled
ArduPilot/ardupilot pull request #21445
Opened 2022-08-15 04:34 UTC by stephendade

Turns out that Visual Odometry doesn't work if ``EK3_FEATURE_EXTERNAL_NAV`` is not enabled.

This is primarily for any custom-build boards, where the user has selected the "Enable Visual Odometry" option, or has defined ``HAL_VISUALODOM_ENABLED``. Saves them _also_ having to define ``EK3_FEATURE_EXTERNAL_NAV``.

2022-08-15 05:52 UTC, peterbarker commented
> Turns out that Visual Odometry doesn't work if `EK3_FEATURE_EXTERNAL_NAV` is not enabled.

Does everything compile?  If so, that's a fair indication that we shouldn't link the two things intrinsically as you are here.
 
> This is primarily for any custom-build boards, where the user has selected the "Enable Visual Odometry" option, or has defined `HAL_VISUALODOM_ENABLED`. Saves them _also_ having to define `EK3_FEATURE_EXTERNAL_NAV`.

That information should be encoded into `build_options.py`, I think.  There's a field in the for additional dependencies - we'd need to add a line for `EK3_FEATURE_EXTERNAL_NAV`.

Pretty sure this is correct for the way we're currently doing things.  I'm thinking this is getting a little silly, however.  I can't think of a case where you'd want to enable HAL_VISUALODOM_ENABLED but not feed EK3 with it.  OTOH, it would allow you to feed visualodom into only EK3 and not (e.g.) EK4.

BTW - were you really trying to get this onto a 1MB board?

2022-08-15 06:40 UTC, stephendade commented
> Does everything compile? If so, that's a fair indication that we shouldn't link the two things intrinsically as you are here.

Yes, compiles fine

>  I'm thinking this is getting a little silly, however. I can't think of a case where you'd want to enable HAL_VISUALODOM_ENABLED but not feed EK3 with it

That was pretty much my thought process for putting here, rather than in build_options.py. Though happy to put it in build_options.py instead.

> BTW - were you really trying to get this onto a 1MB board?

Yep, for Rover anyway :) Works pretty well on a Pixhawk1-1M

2022-08-15 07:17 UTC, rmackay9 commented
This seems fine to me.  Perhaps I'd vote for just merging the two definitions together but I don't feel strongly about it.

2022-08-17 01:06 UTC, stephendade commented
> That information should be encoded into build_options.py, I think. There's a field in the for additional dependencies - we'd need to add a line for EK3_FEATURE_EXTERNAL_NAV.

@peterbarker - I've updated the PR to do this. Should be good to go in now.

2022-08-17 04:03 UTC, rmackay9 requested changes
If "EKF3_EXTERNAL" means External Nav could we use "EKF3_EXTNAV" as the short form?

2022-08-17 04:58 UTC, stephendade commented
> If "EKF3_EXTERNAL" means External Nav could we use "EKF3_EXTNAV" as the short form?

Sure - I've now fixed that up.

2022-08-18 23:02 UTC, merged