Rename OpticalFlow -> AP_OpticalFlow
ArduPilot/ardupilot pull request #21442
Opened 2022-08-15 01:31 UTC by peterbarker

Brings us in-line with other classes in ArduPilot.

Removes ambiguity with AP_HAL::OpticalFlow which can cause compilation errors as we start to make code more portable across targets

2022-08-15 02:06 UTC, peterbarker commented
I compiled this and put it onto a CubeOrange.  DroneCAN sensor still works.

2022-08-17 07:22 UTC, rmackay9 commented on libraries/AP_OpticalFlow/AP_OpticalFlow.cpp
> +    AP_GROUPINFO_FLAGS("_TYPE", 0,  AP_OpticalFlow,    _type,   (float)OPTICAL_FLOW_TYPE_DEFAULT, AP_PARAM_FLAG_ENABLE),
This change to cast to a float seems odd to me because the parameter is an AP_Int8

2022-08-17 07:24 UTC, rmackay9 commented on libraries/AP_OpticalFlow/AP_OpticalFlow.h
> +    enum class Type {
I'm not a huge fan of using "Type" which is so close to the reserved word, "type".  Not a blocker perhaps but ..

2022-08-17 07:29 UTC, tridge requested changes
nice, thanks!

2022-08-17 07:29 UTC, tridge commented on libraries/AP_OpticalFlow/AP_OpticalFlow.cpp
> +    if ((_type == (int8_t)Type::NONE) || (backend != nullptr)) {
no cast needed now we use enum?

2022-08-17 07:29 UTC, rmackay9 approved these changes
In general this looks good to me thanks.

2022-08-18 04:24 UTC, merged