AP_Mount: correct handling of mav-cmd-do-mount-control
ArduPilot/ardupilot pull request #21530
Opened 2022-08-24 05:27 UTC by rmackay9

This PR resolves https://github.com/ArduPilot/ardupilot/issues/21528 by doing the following:

- MOUNT_CONTROL and MAV_CMD_DO_MOUNT_CONTROL are separated into different methods to remove confusion over which fields should be used and their scaling
- This corrects the MAV_CMD_DO_MOUNT_CONTROL scaling for roll, pitch and yaw angles.  These were interpreted as centi-degrees when they should have been interpreted as degrees
- This also corrects how MAV_CMD_DO_MOUNT_CONTROL can be used for setting a location target
    - latitude moved from param1 to param5 (scaling unchanged)
    - longitude moved from param2 to param6 (scaling unchanged)
    - altitude moved from param1 to param4 (scaling changed from cm to m)
- "deprecated" warnings are sent for both MOUNT_CONTROL and MOUNT_CONFIGURE

This has been thoroughly tested in SITL.  I performed before-vs-after comparisons of both MOUNT_CONTROL and MAV_CMD_DO_MOUNT_CONTROL in every mode (retracted, neutral, mavlink targeting, rc targeting, gps-point, sysid-target, home-location) and only the expected changes (see above) were found.

MAV_CMD_DO_MOUNT_CONTROL mavlink-targeting mode angle scaling before vs after
![mav-cmd-do-mount-control-mavlink-targeting-before-bad](https://user-images.githubusercontent.com/1498098/186335455-1fe14b8d-f551-458f-a4d7-bbe8ed3a5d41.png)
![mav-cmd-do-mount-mavlink-targeting-after-good](https://user-images.githubusercontent.com/1498098/186335421-e1bd7c80-36ad-4e6c-982d-c0b05da998c1.png)

MAV_CMD_DO_MOUNT_CONTROL gps-location testing before vs after
![mav-cmd-do-mount-control-gps-location-before](https://user-images.githubusercontent.com/1498098/186336062-eb6ab1c8-3e50-4893-aff9-5bdab7630c54.png)
![mav-cmd-do-mount-gps-location-after](https://user-images.githubusercontent.com/1498098/186335925-7b9bb161-4d27-4380-b20d-f44f618e7c0b.png)
![map-of-gps-point-testing](https://user-images.githubusercontent.com/1498098/186336196-bc45db01-9f48-40ff-b910-7400eb394cbd.png)

2022-08-24 07:59 UTC, tridge requested changes
i think we need a degrees range check, and either disable gimble or give a text warning

2022-08-24 08:02 UTC, tridge submitted a review, later dismissed

2022-08-24 08:02 UTC, tridge commented on libraries/AP_Mount/AP_Mount_Backend.cpp
> +        // param6: longitude in degrees * 1E7
warn non-zero param 1,2,3 ?

2022-08-24 11:34 UTC, olliw42 commented
that's fantastic ... maybe more than 5 years too late, but at last

I'm somewhat surprised the changes are only in the mount library, I am in vaccation currently and can't work out which places I think there are in addition but only can work from memory, but there should be few "higher up", e.g. in the GCS libs (this is what I believe to recall, and it's also explicitely mentioned in https://github.com/ArduPilot/ardupilot/issues/7384)
to just give a gist of what it might be, e.g., if the copter should yaw and the gimbal has no pan
it seems that your SITL testing has not caught such aspects

anyway, again, great to see that such a long standing and annoying issue gets finally adressed :+1:

2022-08-24 21:33 UTC, amilcarlucas commented
It would be great if https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L1162 would get updated with this new info and this PR would include the mavlink submodule update

2022-08-25 12:25 UTC, rmackay9 commented on libraries/AP_Mount/AP_Mount_Backend.cpp
> +        // param6: longitude in degrees * 1E7
txs for the review, warning added

2022-08-25 12:29 UTC, rmackay9 commented
As discussed on the dev call I've added two warnings if the caller attempts to use the old scaling or fields when sending MAV_CMD_DO_MOUNT_CONTROL.

- "Mount: invalid angle targets" appears if fabs(pitch) > 90, fabsf(roll) > 180 or fabsf(yaw) > 360.
- "Mount: GPS_POINT target invalid" appears if param1 and param2 are non-zero (e.g. have lat,lon) while param5 and 6 are zero.

I've tested this in SITL to confirm the warnings appear correctly and no more often than once every 30 seconds.

![image](https://user-images.githubusercontent.com/1498098/186663895-1b01e11b-ef10-4985-bab0-a38e40212cde.png)

2022-08-26 00:28 UTC, merged