Copter: Disable throw mode
ArduPilot/ardupilot pull request #21533
Opened 2022-08-24 20:57 UTC by muramura

There are no videos of the mode of throwing vehicles, except for ArduPilot members.
There are almost no scenes that use the vehicle throw mode.
I would disable this flight mode.

2022-08-31 10:48 UTC, rishabsingh3003 commented
Ah, I really like the throw mode. Here is a video for you where I run the "drop" version of throw mode: https://youtube.com/shorts/uUK8zFFb0Z0?feature=share
It works really well!
But yeah, I haven't seen many people use it, so disabling by default seems okay to me

2022-08-31 19:55 UTC, khancyr requested changes
I don't thing there is much use of the the throw/drop mode. it is really usefull for small vehicle like skyviper but we should be able to handle the inclusion manually

2022-08-31 19:55 UTC, khancyr commented on ArduCopter/config.h
> +#ifndef MODE_THROW_ENABLED
#if MODE_THROW_ENABLED

2022-08-31 20:55 UTC, muramura commented on ArduCopter/config.h
> +#ifndef MODE_THROW_ENABLED
Thanks. I will change.

2022-08-31 23:37 UTC, rmackay9 commented
I've been quiet on this but I'm not sure I'm going to merge this.. It's true that Throw mode is not very widely used but it is a bit unique and fun...

2022-09-01 04:03 UTC, MichelleRos commented
I've used throw mode. Is very fun/amusing, however I can see how it can't really be used on the majority of Copters people use ArduPilot for (given how most aren't really "throwable"). Mine's a 7 inch which is already small enough that various parts of AP struggles with it, yet it's unnerving enough to try throw mode on it that I wouldn't wanna try it with anything bigger...

I agree @rmackay9 that we shouldn't get rid of the mode totally, but given flash space limitations and the fact that this saves ~2.2k it looks like, perhaps we should think about disabling it on 1MB boards by default? (And allow people to use the custom build server if they want it.)

2024-06-05 01:33 UTC, peterbarker commented
I'd think the 1MB copters are where this is most likely to be used.

I *do* use this mode on SkyViper and have mucked around with it on other vehicles.  This PR would obviously remove it from SkyViper.

I really don't think this is one to merge, myself.

2024-06-05 06:53 UTC, andyp1per commented
Yes I agree, closing

2024-06-05 06:53 UTC, closed without merging

2024-06-05 10:59 UTC, muramura commented
Thank you for the review. I understand the reasons for the close.