Add relay support to PCA9685
ArduPilot/ardupilot pull request #21571
Opened 2022-08-29 18:55 UTC by Williangalvani

This enables all RCOutput drivers to implement Relay support, and it is only enabled if `PCA9685_ENABLE_RELAYS` is set.

It uses the "always on" bit that can be seen in the datasheet's Table 7 (page 21).

[Datasheet link for convenience](https://cdn-shop.adafruit.com/datasheets/PCA9685.pdf).

This PR also enables the feature on Navigator boards.
Tested on Navigator.

closes #21563

2022-08-30 01:14 UTC, rmackay9 commented on libraries/AP_Relay/AP_Relay.cpp
> +      hal.rcout->write_relay(_pin[instance], value);
small indenting issue..

2022-08-30 01:16 UTC, tridge requested changes
should be done in GPIO.cpp in HAL_Linux, with magic range of pin numbers, so it works with all GPIOs, not just relay

2022-08-30 06:06 UTC, ES-Alexander commented
@tridge / @IamPete1 out of interest, are there likely to be usability issues / unintuitive behaviour caused by presenting an output-only set of pins as GPIO? Is there some way to flag or mark a GPIO pin as input or output only?

2022-08-30 09:10 UTC, IamPete1 commented
@ES-Alexander The IOMCU GPIO are also output only, we don't really have a great way to document this ATM. We can only put them in relevant param descriptions, which is probably only relay....

2022-09-05 23:33 UTC, tridge approved these changes

2022-09-05 23:34 UTC, merged