Plane: quadplane: improve mav_type reporting for GCS
ArduPilot/ardupilot pull request #21596
Opened 2022-08-31 19:07 UTC by tajisoft

I am using QGC. When connected to QuadPlane, it is recognized as Fixed-Wing. This happens setting Q_MAV_TYPE to the default 0. You can work around this by setting it to something other than 0.
I know this issue has been discussed in https://github.com/ArduPilot/ardupilot/issues/7137 but it doesn't seem to be fixed. 0 is auto so I would expect it to report correctly. I don't know if my suggestion is good, but I'll make a PR. Please give me your comments and advice.

2022-08-31 20:07 UTC, IamPete1 commented on ArduPlane/quadplane.cpp
> +        if (enabled()) {
This would have to be:
```suggestion
        if (available()) {
```

2022-09-01 06:58 UTC, tajisoft commented on ArduPlane/quadplane.cpp
> +            return vtol_mav_type;
Thank you for your comment! I tried to use that function too, but it reports MAV_TYPE for copters except for TailSitter. What about converting here?
```
MAV_TYPE QuadPlane::get_mav_type(void) const
{
    if (mav_type.get() == 0) {
        if (available()) {
            if (tiltrotor.enabled()) {
                return MAV_TYPE_VTOL_TILTROTOR;
            }
            MAV_TYPE motor_mav_type = motors->get_frame_mav_type();
            switch (motor_mav_type)
            {
                case MAV_TYPE_VTOL_DUOROTOR:
                    return MAV_TYPE_VTOL_DUOROTOR;
                case MAV_TYPE_QUADROTOR:
                    return MAV_TYPE_VTOL_QUADROTOR;
                default:
                    return MAV_TYPE_VTOL_RESERVED5;
            }
        }
        return MAV_TYPE_FIXED_WING;
    }
    return MAV_TYPE(mav_type.get());
}
```

2022-09-01 06:59 UTC, tajisoft commented on ArduPlane/quadplane.cpp
> +        if (enabled()) {
Thank you very much!!

2022-09-01 10:30 UTC, peterbarker commented on ArduPlane/quadplane.cpp
> +            return vtol_mav_type;
@tajisoft why not
```
MAV_TYPE QuadPlane::get_mav_type(void) const
{
    if (mav_type.get() != 0) {
        return MAV_TYPE(mav_type.get());
    }
    if (!available()) {
        return MAV_TYPE_FIXED_WING;
    }
    if (tiltrotor.enabled()) {
        return MAV_TYPE_VTOL_TILTROTOR;
    }
    return motors->get_frame_mav_type();
```

2022-09-01 12:01 UTC, tajisoft commented on ArduPlane/quadplane.cpp
> +            return vtol_mav_type;
@peterbarker Thanks for the great suggestions! Next I'm facing an issue with copters appearing in SITL on quadplane. 

`sim_vehicle.py -v Plane --frame quadplane --map --console`

What do you think about converting MAV_TYPE_QUADROTOR to MAV_TYPE_VTOL_QUADROTOR.
```
MAV_TYPE QuadPlane::get_mav_type(void) const
{
    if (mav_type.get() != 0) {
        return MAV_TYPE(mav_type.get());
    }
    if (!available()) {
        return MAV_TYPE_FIXED_WING;
    }
    if (tiltrotor.enabled()) {
        return MAV_TYPE_VTOL_TILTROTOR;
    }
    if (motors->get_frame_mav_type() == MAV_TYPE_QUADROTOR) {
        return MAV_TYPE_VTOL_QUADROTOR;
    }
    return motors->get_frame_mav_type();
}
```

2022-09-02 01:41 UTC, peterbarker commented on ArduPlane/quadplane.cpp
> +            return vtol_mav_type;
>     if (motors->get_frame_mav_type() == MAV_TYPE_QUADROTOR) {
>         return MAV_TYPE_VTOL_QUADROTOR;
>     }

Yep, this is a good solution if there's only one or two of them.

If there turns out to be a whole bunch (which by orthogonality there should be) we'd probably move the logic into a `motors->get_frame_mav_vtol_type()` - but right now that would be overkill and cost bytes on Copter where we don't need to.

2022-09-02 12:47 UTC, tajisoft commented on ArduPlane/quadplane.cpp
> +            return vtol_mav_type;
Thanks, I agree with you.

2022-09-02 13:03 UTC, tajisoft commented
@IamPete1 @peterbarker Thank you for your wonderful support! I pushed a fix. Solved the problem I was facing with my quadplane being misidentified as fixed wing. No further changes are required for this issue at this time. Thank you again.

2022-09-02 16:11 UTC, IamPete1 commented
Looks like this is confusing MAVProxy.

2022-09-02 17:27 UTC, tajisoft commented
@IamPete1 It seems so. I think I need to add MAV_TYPE handling to pymavlink and MAVProxy. Adding VTOL is expensive, so I would like to modify MAV_TYPE_VTOL_* to be treated as FIXED_WING as before. What do you think?

2023-06-02 08:03 UTC, tajisoft commented
Fixed pymavlink and MAVProxy. Verified that the following commands display correctly on the simulator.
https://github.com/ArduPilot/pymavlink/pull/823
https://github.com/ArduPilot/MAVProxy/pull/1187

`./Tools/autotest/sim_vehicle.py -v Plane --frame quadplane --map --console`

2023-06-02 08:12 UTC, tajisoft commented
I found this confusing Mission Planner. I am looking into it.

2023-06-02 08:24 UTC, tajisoft commented
> I found this confusing Mission Planner. I am looking into it.

I was mistaken. The mode was displayed correctly in Mission Planner.

2024-09-11 13:02 UTC, peterbarker requested changes, later dismissed
I can see `TILTROTOR` being a thing here.

I don't think we should generally be changing MAV_TYPE mid-flight, however.

Upstream now has `MAV_TYPE_VTOL_FIXEDROTOR` which would be relevant for many of our motors-frames.

@tajisoft did you want to pursue this?

2025-06-05 02:52 UTC, peterbarker commented
I have adjusted this PR to only magically change our vehicle type to a known-good subset of the types.  So VTOL_QUADROTOR and VTOL_TILTROTOR.

MAVProxy is going to do odd things on other frames, so continuing to use FIXEDWING is the safer solution here until more elaborate GCS changes are made.

Tested in SITL.

2025-06-09 18:35 UTC, IamPete1 submitted a review, later dismissed

2025-06-09 18:35 UTC, IamPete1 commented on ArduPlane/quadplane.cpp
>      }
I think this quadplane check needs to before the `mav_type` param check. Otherwise I could enable quadplane, set a mav type and disable quadplane again and still have `Q_MAV_TYPE` taking affect.

2025-06-09 18:36 UTC, IamPete1 commented
Need to double check mission planner and QGC still detect the correct vehicle type after this change.

2025-06-09 18:39 UTC, IamPete1 commented on ArduPlane/quadplane.cpp
> +        return MAV_TYPE_VTOL_QUADROTOR;
This one is now tailsitter specific upstream.

https://github.com/mavlink/mavlink/blob/ebfa4609db60c8ce9c2aa6917f4c12373ee34e2c/message_definitions/v1.0/minimal.xml#L133-L135

https://github.com/mavlink/mavlink/pull/1818

2025-06-25 01:07 UTC, IamPete1 commented on ArduPlane/quadplane.cpp
>      }
Correct.

2025-06-25 01:11 UTC, IamPete1 commented on ArduPlane/quadplane.cpp
> +        return MAV_TYPE_VTOL_QUADROTOR;
You would need to check tailsitter is enabled. Something like:
```
if (tailsitter.enabled() && (motors->get_frame_mav_type() == MAV_TYPE_QUADROTOR)) {
    return MAV_TYPE_VTOL_QUADROTOR; // This is MAV_TYPE_VTOL_TAILSITTER_QUADROTOR upstream
}
```

2026-07-26 18:05 UTC, IamPete1 commented
I have rebased and fixedup my review comments.

2026-07-26 18:06 UTC, IamPete1 commented on ArduPlane/quadplane.cpp
> +        return MAV_TYPE_VTOL_QUADROTOR;
I have fixed this.

2026-07-26 18:06 UTC, IamPete1 commented on ArduPlane/quadplane.cpp
>      }
Fixed

2026-07-26 18:07 UTC, IamPete1 commented
I have done a quick test on Mission planner and QGC, they both seem fine with the new MAV TYPEs.

2026-07-27 23:29 UTC, tridge approved these changes

2026-07-27 23:29 UTC, merged

2026-07-27 23:37 UTC, tridge commented
**Automated review note — AI-generated (Claude), validated against the live diff.** Please sanity-check before acting.

### Review verdict: COMMENT

A long-standing gap between the parameter documentation and the code, now partly closed. Worth deciding whether AUTO should cover plain quadplanes too.

#### Findings
- **ISSUE** — **"AUTO" still reports FIXED_WING for ordinary quadplanes.** `Q_MAV_TYPE`'s documentation already advertises `0:AUTO` (`ArduPlane/quadplane.cpp:256`), and this PR finally implements it — but only for tiltrotors and tailsitters. A conventional quad+wing VTOL with `Q_MAV_TYPE=0` falls through to `MAV_TYPE_FIXED_WING`, which is the most common quadplane configuration and arguably the one an "AUTO" setting should classify. Either extend AUTO to return `MAV_TYPE_VTOL_QUADROTOR` (or the frame-appropriate type from `motors->get_frame_mav_type()`) for the enabled-but-plain case, or document that AUTO deliberately keeps FIXED_WING for compatibility with GCSes that key off it. [quadplane.cpp:4067](https://github.com/ArduPilot/ardupilot/pull/21596/files#diff-ArduPlane/quadplane.cppR4067)
- NOTE — **The `available()` guard is placed correctly.** Checking it first means `motors` is guaranteed non-null before `motors->get_frame_mav_type()` is reached (`AP_Motors_Class.h:273`), and a quadplane-capable firmware with `Q_ENABLE=0` now correctly reports FIXED_WING regardless of a left-over `Q_MAV_TYPE`. That last part is a small behaviour change worth mentioning in the description: previously a non-zero `Q_MAV_TYPE` was honoured even with the quadplane disabled.
- NOTE — **Deprecated MAVLink enumerator names.** `MAV_TYPE_VTOL_DUOROTOR` and `MAV_TYPE_VTOL_QUADROTOR` were renamed upstream to `MAV_TYPE_VTOL_TAILSITTER_DUOROTOR` / `MAV_TYPE_VTOL_TAILSITTER_QUADROTOR` (same values, 19 and 20). Both spellings still compile against ArduPilot's mavlink module, but new code should prefer the current names. [quadplane.cpp:4055](https://github.com/ArduPilot/ardupilot/pull/21596/files#diff-ArduPlane/quadplane.cppR4055)

---

_Generated from an automated review of all PRs labelled `DevCallTopic` on 2026-07-28. Full report: https://uav.tridgell.net/DevCallReviews/DevCallTopic/devcall_pr_reviews.html_