AP_Mount: split servo driver, parameters to degrees
ArduPilot/ardupilot pull request #21602
Opened 2022-09-01 00:52 UTC by rmackay9

This includes the following changes

- Parameters are moved to a separate AP_Mount_Params class similar to what we've done for RangeFinders and Proximity sensors.  Structurally this is nice and it also makes increasing the number of mount instances very easy,  This leads to MNT_xxx parameters being renamed to MNT1_ although we could leave the first instance as MNT_ because there are currently no class-level parameters.
- Parameters for angle limits are renamed and scaled in degrees (instead of centi-degrees) 
    - MNT_ANGMIN_ROL -> MNT1_ROLL_MIN
    - MNT_ANGMAX_ROL -> MNT1_ROLL_MAX
    - MNT_ANGMIN_TIL -> MNT1_PITCH_MIN
    - MNT_ANGMAX_TIL -> MNT1_PITCH_MAX
    - MNT_ANGMIN_PAN -> MNT1_YAW_MIN
    - MNT_ANGMAX_PAN -> MNT1_YAW_MAX
- RC channels used to control of the mount(s) (in RC_TARGETTING mode) are specified using RCx_OPTION parameters instead of MNT_RC_IN_ROLL,  MNT_RC_IN_TILT and MNT_RC_IN_PAN
- A new "BrushlessPWM" mount type is added that uses the existing Servo backend.  This allows users to more simply specify that their gimbal does not need roll and pitch stabilization instead of setting the MNT_STAB_ROLL and MNT_STAB_TILT parameters.  The MNT_STAB_PAN parameter has also been removed along with some complex rotation code because it is no longer necessary since earlier PRs have cleaned up the earth-frame vs body-frame confusion and given users the ability to switch between these two frames in real time (see "Mount Lock" RC option)

This has been lightly tested in SITL on a Gremsy gimbal

To-Do:

- [ ] Add parameter conversion
- [ ] Test SToRM32, AlexMos and Solo gimbals

2022-09-02 01:59 UTC, rmackay9 commented
I've now added in the parameter conversion and tested it thoroughly

Below are screen shots of the three parameter conversions tests that were done.

The top image shows the changes from centi-degrees to degrees and also how MNT_TYPE may change from 1/Servo to 7/BrushlessPWM.  The 2nd image shows how MNT_TYPE may stay as 1.
![mnt-params-before-vs-after-annotated](https://user-images.githubusercontent.com/1498098/188042423-103923ed-0828-4396-ae4b-22a15c7b1ffa.png)

The next image shows the successful conversion from the RC controls from MNT_RC_IN_PAN/ROLL/TILT to RCx_OPTION
![mnt-rc-conversion-before-vs-after](https://user-images.githubusercontent.com/1498098/188042489-57bd3397-9778-4679-89e3-7cdf6bcd5255.png)

2022-09-05 23:57 UTC, peterbarker commented on libraries/AP_Mount/AP_Mount.cpp
> +    const AP_Param::ConversionInfo mnt_param_conversion_info[] = {
```suggestion
    static const AP_Param::ConversionInfo mnt_param_conversion_info[] {
```

2022-09-05 23:57 UTC, peterbarker commented on libraries/AP_Mount/AP_Mount.cpp
> +    const AP_Param::ConversionInfo mnt_param_deg_conversion_info[] = {
```suggestion
    static const AP_Param::ConversionInfo mnt_param_deg_conversion_info[] {
```

2022-09-06 00:02 UTC, tridge requested changes

2022-09-06 00:02 UTC, tridge commented on libraries/AP_Mount/AP_Mount_Servo.h
> +    bool requires_stabilization;
const

2022-09-06 00:39 UTC, rmackay9 commented on libraries/AP_Mount/AP_Mount.cpp
> +    const AP_Param::ConversionInfo mnt_param_conversion_info[] = {
fixed, txs.

2022-09-06 00:39 UTC, rmackay9 commented on libraries/AP_Mount/AP_Mount.cpp
> +    const AP_Param::ConversionInfo mnt_param_deg_conversion_info[] = {
fixed, txs.

2022-09-06 00:40 UTC, rmackay9 commented on libraries/AP_Mount/AP_Mount_Servo.h
> +    bool requires_stabilization;
ok txs.  made "requires_stabilization" const.

2022-09-06 04:53 UTC, merged