GCS_MAVLink: Rate limit blocking accel calibrations
ArduPilot/ardupilot pull request #21653
Opened 2022-09-06 23:46 UTC by WickedShell

This allows us to drop any queued commands that may have arrived while we were calibrating. Rather then entering a second and unexpected calibration.

2022-09-06 23:49 UTC, peterbarker requested changes
LGTM apart from whitespace.  Specify testing done in PR, please.

2022-09-06 23:49 UTC, peterbarker commented on libraries/GCS_MAVLink/GCS_Common.cpp
> +            last_accel_cal_ms = AP_HAL::millis();
Indenting
```suggestion
        last_accel_cal_ms = AP_HAL::millis();
```

2022-09-06 23:52 UTC, WickedShell commented on libraries/GCS_MAVLink/GCS_Common.cpp
> +            last_accel_cal_ms = AP_HAL::millis();
Fixed, sorry.

2022-09-07 08:00 UTC, tridge approved these changes

2022-09-07 08:02 UTC, peterbarker requested changes
Needs to pass CI, but otherwise acceptable.

2022-09-08 22:52 UTC, merged