RC_Channel:make mount control metadata match param names
ArduPilot/ardupilot pull request #21674
Opened 2022-09-08 19:49 UTC by Hwurzburg

2022-09-08 22:11 UTC, amilcarlucas commented
Are the libcanard changes meant to be? Or an accident?

2022-09-08 22:17 UTC, Hwurzburg commented
accident...will fix

2022-09-09 20:15 UTC, Hwurzburg commented
> Looks ok. Should we rename "Retract Mount" to "Mount1 Retract"? (or Retract Mount1)
its not Mount1....its the primary mount, could be Mount2....I think we should add a switch for the second mount, and force them to only operate on a specific instance instead of whichever backend is created first....would remove ambiguity of primary, secondary, and eventually tertiary...
I added changes for the mount output servos...

2022-09-09 23:24 UTC, rmackay9 commented
@Hwurzburg,

yes, I agree we should change the unnumbered mount switches to always act on the first mount.

2022-09-12 00:00 UTC, rmackay9 approved these changes

2022-09-12 00:02 UTC, rmackay9 requested changes
@Hwurzburg,

Looking pretty good but a couple of small adminy type things:

1. split the commit into two commits.  One that affects RC_Channel and the other that affect SRV_Channel
2. prefix each commit with either "RC_Channel: " or "SRV_Channel: "

2022-09-12 00:29 UTC, Hwurzburg commented
yep...forgot...done

2022-09-13 01:29 UTC, tridge requested changes

2022-09-13 01:29 UTC, tridge commented on libraries/RC_Channel/RC_Channel.cpp
> +                mount->set_mode_to_default(1);
should be zero I think

2022-09-13 01:29 UTC, tridge commented on libraries/RC_Channel/RC_Channel.cpp
> +                mount->set_mode(1,MAV_MOUNT_MODE_RETRACT);
should be zero

2022-09-13 01:30 UTC, tridge commented on libraries/RC_Channel/RC_Channel.cpp
> +                mount->set_mode_to_default(1);
should be zero

2022-09-13 01:38 UTC, Hwurzburg commented on libraries/RC_Channel/RC_Channel.cpp
> +                mount->set_mode_to_default(1);
fixed

2022-09-13 01:38 UTC, Hwurzburg commented on libraries/RC_Channel/RC_Channel.cpp
> +                mount->set_mode(1,MAV_MOUNT_MODE_RETRACT);
fixed

2022-09-13 01:38 UTC, Hwurzburg commented on libraries/RC_Channel/RC_Channel.cpp
> +                mount->set_mode_to_default(1);
fixed

2022-09-14 08:29 UTC, merged