Tools: add ardupilot_gazebo to install-ROS-ubuntu script
ArduPilot/ardupilot pull request #21680
Opened 2022-09-09 23:46 UTC by rmackay9

This is a replacement for PR  https://github.com/ArduPilot/ardupilot/pull/21678 which adds gazebo to the AP-ROS install scripts.  This is all @snktshrma's work, I've raise the PR just to get over some merge issues.

The purpose of all of this of course is to make it easy to get AP and ROS running at least in SITL.

2022-09-10 00:36 UTC, jmachuca77 requested changes
The ardupilot_ros package should form part of the ardupilot workspace. This just clones the repo into the Tools folder and compiles in there.... I'll submit a change.

2022-09-10 00:36 UTC, jmachuca77 commented on Tools/environment_install/install-ROS-ubuntu.sh
> +git clone https://github.com/SwiftGust/ardupilot_gazebo
this should point to https://github.com/ardupilot/ardupilot_gazebo
If that repo is missing something when we should make pull requests to that repo to bring it up to date.

2022-09-10 00:36 UTC, jmachuca77 commented on Tools/environment_install/install-ROS-ubuntu.sh
> +git clone https://github.com/SwiftGust/ardupilot_gazebo
this whole section is duplicated.

2022-09-10 00:36 UTC, jmachuca77 commented on Tools/environment_install/install-ROS-ubuntu.sh
> +git clone https://github.com/SwiftGust/ardupilot_gazebo
Actually this is incorrect... this should be cloned into the workspace and be part of the ardupilot_ws .....

2022-09-10 06:37 UTC, rmackay9 commented on Tools/environment_install/install-ROS-ubuntu.sh
> +git clone https://github.com/SwiftGust/ardupilot_gazebo
replaced with your new version.

2022-09-15 06:31 UTC, peterbarker commented
@jmachuca77 happy with this now?

2022-09-16 00:34 UTC, rmackay9 commented
@peterbarker,

Thanks for the follow-up.  A number of issues have appeared with this script.  I've created an issue and @snktshrma is working on some fixes.  .. so for now I've changed this to a WIP.

References PRs and issues:

- https://github.com/ArduPilot/ardupilot/issues/21722
- https://github.com/ArduPilot/ardupilot/pull/21723
- https://github.com/ArduPilot/ardupilot/pull/21730

2023-01-06 08:04 UTC, rmackay9 commented
Closing in favour of https://github.com/ArduPilot/ardupilot/pull/22598

2023-01-06 08:04 UTC, closed without merging