AP_Mission: Initialize return variables
ArduPilot/ardupilot pull request #21797
Opened 2022-09-25 05:33 UTC by muramura

I initialize the return variable.
This method does not initialize the return variable.
I initialize the return value variable with FALSE.
By this process, if the return value variable is not set in the loop process, it becomes FALSE.
Initializing an automatic variable means that I do not need to be aware of whether or not it is undefined in subsequent processing.

2022-09-26 22:13 UTC, WickedShell requested changes
If you're going to do this, the existing spots that set it to false should already be false.

2022-09-26 23:06 UTC, muramura commented
@WickedShell san. Thanks for the comment. I will reflect on the review comments.

2023-02-01 11:32 UTC, khancyr approved these changes
LGTM, need rebase

2023-02-01 13:33 UTC, peterbarker commented
Rebased it

2023-02-01 15:06 UTC, khancyr approved these changes
LGTM after rebase

2023-02-01 22:29 UTC, magicrub approved these changes

2023-02-02 20:14 UTC, merged