modified Copter-4.1.5 for JFB-100
ArduPilot/ardupilot pull request #21807
Opened 2022-09-26 07:12 UTC by jfbblue0922

It is a program for the development board JFB-100 for JAE. The IMU is equipped with SCHA63T (MURATA).

2022-09-26 09:21 UTC, amilcarlucas requested changes

2022-09-26 09:21 UTC, amilcarlucas commented on libraries/AP_HAL_ChibiOS/hwdef/JFB100/README.md
> +# Pixhawk4 Flight Controller
This should be JB100 right?

2022-09-26 09:21 UTC, amilcarlucas commented on libraries/AP_HAL_ChibiOS/hwdef/JFB100/defaults.parm
> +# Pixhawk4 does not have hw flow control on radios
Pixhawk4 ????

2022-09-28 10:03 UTC, jfbblue0922 commented on libraries/AP_HAL_ChibiOS/hwdef/JFB100/README.md
> +The Pixhawk4 flight controller is sold by [Holybro](http://www.holybro.com/product/pixhawk-4)
Thank you.
I will Modify and commit.

2022-09-28 10:03 UTC, jfbblue0922 commented on libraries/AP_HAL_ChibiOS/hwdef/JFB100/defaults.parm
> +# Pixhawk4 does not have hw flow control on radios
Thank you.
I will Modify and commit.

2022-09-29 03:40 UTC, rmackay9 commented
I don't know the background of this PR but in general I agree with @amilcarlucas that it is normally best to raise PRs against master instead of a branch.

2022-11-07 10:53 UTC, jfbblue0922 commented
Sorry, I made a mistake with the pull request.
I will Close pull request and retry soon.

2022-11-07 10:53 UTC, closed without merging