Plane: if RTL with VTOL active and within QRTL radius and alt then QRTL
ArduPilot/ardupilot pull request #21883
Opened 2022-10-04 22:08 UTC by IamPete1

If VTOL is active and within RTL radius and under QRTL alt then switch to QRTL. 

For example if you takeoff in Qloiter to 5m and then switch to RTL currently we will transition into forward flight, climb and circle. This will now switch to QRTL and it will return home and land.

Also tidy's up the `switch_QRTL` function a little.

2022-10-07 00:29 UTC, tridge commented
hoping to get some test logs for this from Arace

2022-10-07 16:09 UTC, pompecukor commented
@tridge 
Tested and working. Logs send in partner channel. Thank you

2022-10-11 00:06 UTC, tridge requested changes
this may break ship landing, needs careful thought

2022-10-18 20:05 UTC, pompecukor commented
> this may break ship landing, needs careful thought

Will you consider some kind of disable this behavior, if one of the "Foll" parameter enabled (ie using ship landing). As I think the safety this provides is way more imperative than the 99.99% of users (who are all not running ship landing).
The thing is that currently if the system goes into RTL at 2m AGL, the it can take someone head-off.
I think you will agree that typical expected behaviors for most user with VTOL at low AGL and inside home radius, while hovering airplane when switched to RTL, it not for it to start to transition.

2022-11-09 10:47 UTC, pompecukor commented
@tridge 
Can we move with this in any direction. It is very dangerous in current state. I understand it breaks ship landing, but we could add some override or something?
Not only are we having potentially dangerous events. But we also have a recurring problem where the Griffin if powered on without GCS/RC. Then it would go into failsafe. And failsafe is set to RTL, however while not flying and on the ground we need it to go the QRTL. Cause in RTL the props tilt forward and potential brake or burn the BEC of the tilt servo.

2022-11-09 15:13 UTC, timtuxworth commented
> Not only are we having potentially dangerous events. But we also have a recurring problem where the Griffin if powered on without GCS/RC. Then it would go into failsafe. And failsafe is set to RTL, however while not flying and on the ground we need it to go the QRTL. Cause in RTL the props tilt forward and potential brake or burn the BEC of the tilt servo, if the props are in the wrong direction and the drone is on the ground.

It is quite unfortunate that a plane will failsafe to RTL when first turned on, when working with it on the bench or in the field before everything has come up.

2022-11-09 15:36 UTC, pompecukor commented
> > Not only are we having potentially dangerous events. But we also have a recurring problem where the Griffin if powered on without GCS/RC. Then it would go into failsafe. And failsafe is set to RTL, however while not flying and on the ground we need it to go the QRTL. Cause in RTL the props tilt forward and potential brake or burn the BEC of the tilt servo, if the props are in the wrong direction and the drone is on the ground.
> 
> It is quite unfortunate that a plane will failsafe to RTL when first turned on, when working with it on the bench or in the field before everything has come up.

@IamPete1 @tridge 

This is actually the second problem that we are facing and unfortunately even this PR does not fix that. We found out the hard way today. The BEC burnt as we were not fast enough. This PR only works when armed/in flight.
I think it was the ship-landing that may have actually broken this as I do not remember this behaviors from before that.

Right now if the drone is turned out without GCS connected (hence it goes to Failsafe). As failsafe is set to RTL, it goes directly to RTL, even though it is at home, not armed and on the ground. It should got to QRTL... Why? Cause the tilt servos tilt down immediately undesirably and the props dig into the ground and in our case try to raid the aircraft up and overload the BEC.
Same happens if we switch to RTL mode on RC, it will got to RTL, not QRTL.

VTOL MUST always go to QRTL when it is on the ground. There is not situation where it would need to be otherwise.

Can we please fix this ASAP?

2022-11-09 17:07 UTC, timtuxworth commented
I'd argue that if the vehicle it is at home, not armed (or maybe has not previously armed since boot) and on the ground, it should not failsafe.

2022-11-09 18:49 UTC, pompecukor commented
> I'd argue that if the vehicle it is at home, not armed (or maybe has not previously armed since boot) and on the ground, it should not failsafe at all.

I don't see any con with going into FS on the ground/disarmed. Maybe you can tell me one.
I do see one main advantage. Which is an easy way to pre-flight check for failsafe working properly. turn of GCS and if all works properly, then you will here the sharp beep of the FC changing mode and vice versa, then you turn on, the beep comes on again, for going out of failsafe. Without this, on many of our drones which has GCS failsafe, there is not real way of know that it works. Except checking the logs after the fact.

2022-11-09 19:02 UTC, timtuxworth commented
> I don't see any con with going into FS on the ground/disarmed. Maybe you can tell me one? 

The problem is that it will always failsafe - even when there is actually no problem, because typically the GPS or RC or some other component takes a bit of time to come up. So you always get a failsafe and RTL when you boot, which is very misleading because there may actually be nothing wrong with your vehicle.
Even if your transmitter is set to a particular mode on boot, the FC will have switched to RTL, so you might think you have booted into e.g. FBWA for takeoff, but the vehicle has decided to failsafe to RTL, even though there is nothing wrong.

I've learned to live with it, but honestly I consider it 'flakey' behavior that every new user has to learn to ignore.

2022-11-09 19:17 UTC, pompecukor commented
> > I don't see any con with going into FS on the ground/disarmed. Maybe you can tell me one?
> 
> The problem is that it will always failsafe - even when there is actually no problem, because typically the GPS or RC or some other component takes a bit of time to come up. So you always get a failsafe and RTL when you boot, which is very misleading because there may actually be nothing wrong with your vehicle. Even if your transmitter is set to a particular mode on boot, the FC will have switched to RTL, so you might think you have booted into e.g. FBWA for takeoff, but the vehicle has decided to failsafe to RTL, even though there is nothing wrong.
> 
> I've learned to live with it, but honestly I consider it 'flakey' behavior that every new user has to learn to ignore.

Ok, for just bootup it does make sense to not FS. I agree with that. But you kind of changed you statement. What you said in you first argument is _"...**.if the vehicle it is at home, not armed** (or maybe has not previously armed since boot) and **on the ground.**.."_. I do not agree with that.

2022-11-09 22:39 UTC, timtuxworth commented
> Ok, for just bootup it does make sense to not FS. I agree with that. But you kind of changed you statement. What you said in your first argument is "....if the vehicle it is at home, not armed (or maybe has not previously armed since boot) and on the ground...". I do not agree with that.

I literally copied it directly from your original comment :-)

2022-11-09 23:45 UTC, IamPete1 commented
@timtuxworth What failsafe's are you seeing at boot? No GPS lock will not cause a failsafe nor will no GCS. No RC could, but that is solved by switching on your transmitter first. Copter does only trigger RC failsafe after it has first seen RC, we could change to that behaviour.

2022-11-24 22:52 UTC, IamPete1 commented
@tridge I have added a VTOL landing check, that is if a VTOL landing is expected at the end of the RTL. In the case of ship landing `Q_RTL_MODE` must be 0 I think? Otherwise the vehicle would go straight into the landing sequence rather than holding off.

2022-12-10 23:32 UTC, IamPete1 commented
rebased and re-tested. I'm happy for this to be merged once it is passed checks.

2022-12-11 23:25 UTC, pompecukor commented
> rebased and re-tested. I'm happy for this to be merged once it is passed checks.

Yes please! We have been rocking this PR for 70 days not and very happy. Now even more so with the ship landing option not being affected anymore.

2022-12-12 23:32 UTC, tridge approved these changes

2022-12-12 23:32 UTC, merged

2023-01-07 06:56 UTC, rmackay9 commented
This is included in 4.3.3-rc1