AP_BattMoniter: allow runtime alocation
ArduPilot/ardupilot pull request #21902
Opened 2022-10-06 16:01 UTC by IamPete1

This allows runtime allocation of battery monitors meaning there is no longer any need to reboot too see var pointer params, although of course params will have to be fetched again. ~This is allocation only, you cannot change from one type to another at run time.~

2022-10-06 17:26 UTC, WickedShell reviewed
I'm not fully sold on the utility of this. It saves you reboots for the case where you go from None -> Something, but Anything -> Anything won't work, and still requires a reboot.

It actually seems to me like it may make it more confusing then it otherwise would be, because now there are two different cases to consider.

2022-10-06 17:39 UTC, IamPete1 commented
@WickedShell There was some discussion about how to make first time setup easier. Users mostly get the idea of having to refresh params after setting a enable/type that now mostly works.

We could also de-allocate I did have a look at that, It should work trivially, except for DroneCAN which new's stuff and registers call backs and stuff.

2022-10-07 19:44 UTC, IamPete1 commented
Now allocates and de-allocates. Seems to work in SITL. Stuff might get a bit racy with the CAN backend that has callbacks that could happen as were deleting it. We could wrap everything in a semaphore I guess....

2022-10-07 19:45 UTC, WickedShell commented on libraries/AP_BattMonitor/AP_BattMonitor.cpp
> +            delete drivers[instance];
How does this deregister the I2C timer callbacks?

2022-10-07 19:51 UTC, WickedShell requested changes
I'm seeing a lot of serious race conditions and memory corruption with deleting both I2C and CAN backends.

2022-10-07 20:12 UTC, IamPete1 commented
Conclusion is that de-allocation is a no-go without a lots of work making i2c and CAN callbacks safe. Allocation is OK except that most boards have analog setup as the default monitor, so we cant change that. So your going to have to reboot anyway.

2022-10-07 20:12 UTC, closed without merging