AP_Logger: don't log POWR if there will be nothing in it
ArduPilot/ardupilot pull request #21983
Opened 2022-10-16 21:33 UTC by IamPete1

Saves lots of empty logs fields. 

Quite tempted to split into multiple messages.

The only change here is that we would no longer log the safety flag, it would be the only none-zero thing.

2022-10-16 22:16 UTC, peterbarker commented
From a recent Plane flight:
```
POWR 0.89%
```

There may be bigger fish to fry.

2022-10-17 16:28 UTC, andyp1per submitted a review, later dismissed

2022-10-17 19:07 UTC, IamPete1 commented
The safety flag is in `STAT` on plane. We don't have that on other vehicles tho.

2023-01-21 15:06 UTC, IamPete1 commented
This now just removes the fields if they are unused.

2023-01-21 15:07 UTC, IamPete1 commented
Not a massive saving in either flash or log size, but does setup a pattern that we could use elsewhere.

2023-01-21 15:11 UTC, IamPete1 commented
Not tested IRL, but have greped the binarys to make sure the labels ect are coming out correctly.

2023-01-22 22:03 UTC, IamPete1 commented
@peterbarker This upsets the c++ parsing in the logger documentation test. I got it working as far as this regex and then gave up and added a white list.

https://github.com/ArduPilot/ardupilot/blob/15ae88db9e078c0aa37895669602e9596ac892df/Tools/autotest/common.py#L2764

We should probably decide if we actually want this before fixing the test in anycase...

2023-01-22 22:36 UTC, IamPete1 commented
Saves a bit of flash on MatekF405 where the extra items are not available. 
```
Binary Name      Text [B]         Data [B]     BSS (B)        Total Flash Change [B] (%)      Flash Free After PR (B)
---------------  ---------------  -----------  -------------  ----------------------------  -------------------------
arduplane        -108 (-0.0113%)  0 (0.0000%)  4 (+0.0031%)   -108 (-0.0113%)                                   28944
ardurover        -108 (-0.0130%)  0 (0.0000%)  -4 (-0.0031%)  -108 (-0.0130%)                                  153168
ardusub          -108 (-0.0136%)  0 (0.0000%)  -4 (-0.0031%)  -108 (-0.0136%)                                  189068
antennatracker   -108 (-0.0171%)  0 (0.0000%)  -4 (-0.0031%)  -108 (-0.0171%)                                  352016
arducopter-heli  -108 (-0.0117%)  0 (0.0000%)  4 (+0.0031%)   -108 (-0.0117%)                                   58888
arducopter       -108 (-0.0118%)  0 (0.0000%)  -4 (-0.0031%)  -108 (-0.0118%)                                   67848
blimp            -108 (-0.0166%)  0 (0.0000%)  4 (+0.0031%)   -108 (-0.0166%)                                  332948
```

2023-01-25 08:46 UTC, tridge requested changes

2023-01-25 08:46 UTC, tridge commented on libraries/AP_Logger/LogStructure.h
> +#if HAL_WITH_MCU_MONITORING
having a separate MCU msg would likely give more flash savings and would fit our current structure

2023-01-27 23:23 UTC, IamPete1 commented
Rebased and tested on CubeOrange, get both log messages.

2023-01-31 04:43 UTC, tridge commented
tested on CUAV-X7, all good

2023-01-31 04:43 UTC, tridge approved these changes

2023-01-31 04:43 UTC, merged