AP_Scripting: generation flash savings
ArduPilot/ardupilot pull request #21980
Opened 2022-10-16 02:39 UTC by IamPete1

A number of efficiency improvements that each save a bit of flash. 4e2ed27d804278e345844494aaf5b1d49d48fdd3 and 32c27e06886e214579f0ffd58691a6b8a79d26fb make of the majority of the saving.

The best way to review is probably a compare of the generated bindings before and after. 

There is still some more that could be saved, but its getting harder to find.

2022-10-16 12:57 UTC, IamPete1 commented
```
Binary Name      Text [B]          Data [B]     BSS (B)       Total Flash Change [B] (%)      Flash Free After PR (B)
---------------  ----------------  -----------  ------------  ----------------------------  -------------------------
arduplane        -7432 (-0.4196%)  0 (0.0000%)  0 (0.0000%)   -7432 (-0.4188%)                                 199048
ardusub          -7120 (-0.4506%)  0 (0.0000%)  0 (0.0000%)   -7120 (-0.4500%)                                 390900
blimp            -7120 (-0.5461%)  0 (0.0000%)  0 (0.0000%)   -7120 (-0.5452%)                                 667372
arducopter-heli  -7572 (-0.4214%)  0 (0.0000%)  4 (+0.0015%)  -7572 (-0.4205%)                                 173128
arducopter       -7556 (-0.4221%)  0 (0.0000%)  4 (+0.0015%)  -7556 (-0.4213%)                                 179952
antennatracker   -7120 (-0.5235%)  0 (0.0000%)  0 (0.0000%)   -7120 (-0.5228%)                                 611288
ardurover        -7120 (-0.4388%)  0 (0.0000%)  0 (0.0000%)   -7120 (-0.4382%)                                 348544
```

2022-10-16 14:10 UTC, andyp1per commented on libraries/AP_Scripting/generator/src/main.c
> +  emit_feild(field, ud_name, ud_access);
emit_field

2022-10-16 14:10 UTC, andyp1per commented on libraries/AP_Scripting/generator/src/main.c
> +      fprintf(source, "%s * check_%s(lua_State *L) {\n", node->name, node->sanatized_name);
sanitized

2022-10-16 14:29 UTC, IamPete1 commented on libraries/AP_Scripting/generator/src/main.c
> +  emit_feild(field, ud_name, ud_access);
fixed

2022-10-16 14:52 UTC, IamPete1 commented
I have done a elf diff with and without the AP bindings. Manual bindings in red. Supporting functions in dark blue. Function names (just big tables of strings) in green. Generated bindings in light blue. 

![image](https://user-images.githubusercontent.com/33176108/196041899-ec3f9172-e9af-4b5d-92ef-00a9656fb9a5.png)

Most generic bindings cost about 100 bytes or so. Ones that use specially added C++ getter/setter pay twice. 

Userdata is less, even with set and get:
![image](https://user-images.githubusercontent.com/33176108/196042118-74ad3e1e-d48c-4aa9-9f74-b2504913c037.png)

Write only user data is less again, saving 48 bytes per field:
![image](https://user-images.githubusercontent.com/33176108/196042199-181b317a-3153-42ea-8ce1-b2eee0c20924.png)


I had another poke about, but its quite hard to find anymore savings.

2022-10-16 15:08 UTC, IamPete1 commented
This is our largest genrated binding:
```
static int AP_Vehicle_set_target_posvelaccel_NED(lua_State *L) {
    AP_Vehicle * ud = check_AP_Vehicle(L);
    binding_argcheck(L, 9);
    Vector3f & data_2 = *check_Vector3f(L, 2);
    Vector3f & data_3 = *check_Vector3f(L, 3);
    Vector3f & data_4 = *check_Vector3f(L, 4);
    const bool data_5 = static_cast<bool>(lua_toboolean(L, 5));
    const float raw_data_6 = get_number(L, 6, MAX(-360, -INFINITY), MIN(+360, INFINITY));
    const float data_6 = raw_data_6;
    const bool data_7 = static_cast<bool>(lua_toboolean(L, 7));
    const float raw_data_8 = luaL_checknumber(L, 8);
    const float data_8 = raw_data_8;
    const bool data_9 = static_cast<bool>(lua_toboolean(L, 9));
    AP::scheduler().get_semaphore().take_blocking();
    const bool data = static_cast<bool>(ud->set_target_posvelaccel_NED(
            data_2,
            data_3,
            data_4,
            data_5,
            data_6,
            data_7,
            data_8,
            data_9));

    AP::scheduler().get_semaphore().give();
    lua_pushboolean(L, data);
    return 1;
}
```
It can be simplified to this by hand:
```
static int AP_Vehicle_set_target_posvelaccel_NED(lua_State *L) {
    AP_Vehicle * ud = check_AP_Vehicle(L);
    binding_argcheck(L, 9);

    Vector3f & data_2 = *check_Vector3f(L, 2);
    Vector3f & data_3 = *check_Vector3f(L, 3);
    Vector3f & data_4 = *check_Vector3f(L, 4);
    const bool data_5 = lua_toboolean(L, 5);
    const float data_6 = get_number(L, 6, -360, +360);
    const bool data_7 = lua_toboolean(L, 7);
    const float data_8 = luaL_checknumber(L, 8);
    const bool data_9 = lua_toboolean(L, 9);

    AP::scheduler().get_semaphore().take_blocking();
    const bool data = static_cast<bool>(ud->set_target_posvelaccel_NED(
            data_2,
            data_3,
            data_4,
            data_5,
            data_6,
            data_7,
            data_8,
            data_9));
    AP::scheduler().get_semaphore().give();

    lua_pushboolean(L, data);
    return 1;
}
```
Its esayer to read, but the flash cost is the same.  I cant see any flash savings to be had.

This is our largest (jointly) userdata read/write binding:
```
static int AP_MotorsMatrix_Scripting_Dynamic__factor_table_yaw(lua_State *L) {
    AP_MotorsMatrix_Scripting_Dynamic::factor_table *ud = check_AP_MotorsMatrix_Scripting_Dynamic__factor_table(L, 1);

    const lua_Integer raw_index = get_integer(L, 2, 0, MIN(AP_MOTORS_MAX_NUM_MOTORS, UINT8_MAX));
    const uint8_t index = static_cast<uint8_t>(raw_index);

    switch(lua_gettop(L)-1) {
        case 1:
            lua_pushnumber(L, ud->yaw[index]);
            return 1;
        case 2: {
            const float raw_data_3 = luaL_checknumber(L, 3);
            const float data_3 = raw_data_3;
            ud->yaw[index] = data_3;
            return 0;
         }
        default:
            return luaL_argerror(L, lua_gettop(L), "too many arguments");
    }
}
```
Again we can simplify by hand for the same flash cost:
```
static int AP_MotorsMatrix_Scripting_Dynamic__factor_table_yaw(lua_State *L) {
    AP_MotorsMatrix_Scripting_Dynamic::factor_table *ud = check_AP_MotorsMatrix_Scripting_Dynamic__factor_table(L, 1);
    const uint8_t index = get_integer(L, 2, 0, AP_MOTORS_MAX_NUM_MOTORS);
    const int num_args = lua_gettop(L);
    switch(num_args-1) {
        case 1:
            lua_pushnumber(L, ud->yaw[index]);
            return 1;
        case 2: {
            ud->yaw[index] = luaL_checknumber(L, 3);
            return 0;
         }
    }
    return luaL_argerror(L, num_args, "too many arguments");
}
```

Of course we could save flash by giving up functionality, for example we could stop checking the number of arguments, just error out on the wrong type for a expected argument, but not if there were too many.

2022-10-16 18:27 UTC, IamPete1 commented
There is another few hundred bytes in adding a "full range" keyword allowing all the getters without range checks each type to share min and max limits. But this PR is getting big enough already.

2022-10-31 23:36 UTC, tridge requested changes
use WITH_SEMAPHORE() if we can

2022-10-31 23:56 UTC, IamPete1 commented
Using `WITH_SEMAPHORE` is none trivial because it also restricts the scope of the returns. For example we currently have:
```
    AP::scheduler().get_semaphore().take_blocking();
    const bool data = static_cast<bool>(ud->clear());
    AP::scheduler().get_semaphore().give();

    lua_pushboolean(L, data);
```
The trivial change would be:
```
    {
        WITH_SEMAPHORE(AP::scheduler().get_semaphore());
        const bool data = static_cast<bool>(ud->clear());
    }
    lua_pushboolean(L, data);
```
However than then means `data` goes out of scope. So we would need:
```
    bool data;
    {
        WITH_SEMAPHORE(AP::scheduler().get_semaphore());
        data = static_cast<bool>(ud->clear());
    }
    lua_pushboolean(L, data);
```

2022-11-01 06:03 UTC, tridge approved these changes

2022-11-01 06:03 UTC, tridge commented
@IamPete1 ok, fair enough, I thought it would be trivial
I tested with aerobatics script, works well, this can be merged, nice savings!

2022-11-01 06:03 UTC, merged