AP_SOARING: correct metadata for speed params
ArduPilot/ardupilot pull request #21982
Opened 2022-10-16 12:39 UTC by Hwurzburg

Corrects and expands metadata for SOARING speed parameters

2022-10-16 23:12 UTC, peterbarker requested changes

2022-10-16 23:12 UTC, peterbarker commented on libraries/AP_Soaring/AP_Soaring.cpp
> +    // @Values: -1, Use speed-to-fly computed value, 0: Use TRIM_ARSPD_CM, >0: Use this value in m/s instead of TRIM_ARSPD_CM.
```suggestion
    // @Values: -1: Use speed-to-fly computed value, 0: Use TRIM_ARSPD_CM, >0: Use this value in m/s instead of TRIM_ARSPD_CM.
```

2022-10-17 09:28 UTC, samuelctabor approved these changes
Looks good, nice clarifications.

2022-10-18 00:44 UTC, peterbarker approved these changes

2022-10-18 00:44 UTC, merged