AP_InertialSensor: add fast reset for ICM20602 instead of full reset on bad temp sample
ArduPilot/ardupilot pull request #22035
Opened 2022-10-22 04:51 UTC by bugobliterator

This is to resolve a potential bug on ICM20602 where data on all sensor modules randomly jumps to a very high offset. The fix seems to be doing a FIFO reset via USER_CTRL register.

2022-10-22 07:39 UTC, tridge requested changes
thanks Sid, needs some testing by @WickedShell

2022-10-22 07:39 UTC, tridge commented on libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp
> +        _enable_fast_fifo_reset = false;
no need for all these = false, just wastes flash

2022-10-22 08:17 UTC, andyp1per commented on libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp
> +                return true;
You are still going to lose data from the fifo surely so this needs to return false?

2022-10-22 08:17 UTC, andyp1per commented on libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp
> +                _fast_fifo_reset();
return false?

2022-10-22 09:15 UTC, bugobliterator commented on libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp
> +                _fast_fifo_reset();
yes, you are right.

2022-10-22 18:33 UTC, andyp1per commented on libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp
> +#if HAL_GCS_ENABLED
Do we really need this level of debug? It's 300+ bytes on all boards and this seems like a significant contribution

2022-10-26 08:16 UTC, tridge requested changes

2022-10-26 08:16 UTC, tridge commented on libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp
> +                mavlink_msg_named_value_int_send(
can use gcs send_named_float() and no need to loop

2022-10-26 08:16 UTC, tridge commented on libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp
> +        if (AP_HAL::millis() - last_fast_reset_count_report_ms > 1000 ||
const uint32_t now_ms = AP_HAL::millis()

2022-10-31 23:52 UTC, tridge approved these changes

2022-10-31 23:53 UTC, merged