Moves warning about multiple UARTs with RC protocol to a pre-arm so its visible to users
ArduPilot/ardupilot pull request #22031
Opened 2022-10-21 17:08 UTC by Hwurzburg

2022-10-21 17:08 UTC, Hwurzburg commented
tested in SITL

2022-10-21 17:18 UTC, IamPete1 commented on libraries/AP_SerialManager/AP_SerialManager.cpp
> +                    AP::RC().add_uart(uart);
```suggestion
                    if (!AP::RC().has_uart()) {
                        AP::RC().add_uart(uart);
                    }
```
Just to maintain current behaviour.

2022-10-21 17:19 UTC, IamPete1 commented on libraries/AP_Arming/AP_Arming.cpp
> +       check_failed(display_failure, "Multiple UARTs configured for RC input");
```suggestion
       check_failed(display_failure, "Multiple serial ports configured for RC input");
```
Serial better aligns with the param names for serial functions .

2022-10-21 18:40 UTC, andyp1per requested changes
@IamPete1 's comments are correct

2022-10-21 18:42 UTC, Hwurzburg commented on libraries/AP_SerialManager/AP_SerialManager.cpp
> +                    AP::RC().add_uart(uart);
right

2022-10-25 00:33 UTC, tridge approved these changes

2022-10-25 00:34 UTC, rmackay9 approved these changes

2022-10-25 00:34 UTC, merged