Backport ICM20602 Fast Reset and make it optional
ArduPilot/ardupilot pull request #22091
Opened 2022-11-01 00:04 UTC by bugobliterator

Enabled only on CubeOrange and related boards

2022-11-01 11:57 UTC, andyp1per requested changes

2022-11-01 11:57 UTC, andyp1per commented on libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp
> +#define HAL_ENABLE_FAST_FIFO_RESET_ICM20602 false
I think this should be 1/0 or TRUE/FALSE - I don't think we use lower case anywhere

2022-11-01 11:57 UTC, andyp1per commented on libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp
> +#define HAL_ENABLE_FAST_FIFO_RESET_ICM20602 false
Not seeing where this is actually used?

2022-11-01 11:57 UTC, andyp1per commented on libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp
> +void AP_InertialSensor_Invensense::_fast_fifo_reset()
#if out with HAL_ENABLE_FAST_FIFO_RESET_ICM20602

2022-11-01 11:57 UTC, andyp1per commented on libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp
> +    if (fast_reset_count) {
#if out with HAL_ENABLE_FAST_FIFO_RESET_ICM20602

2022-11-16 07:37 UTC, tridge requested changes

2022-11-16 07:37 UTC, tridge commented on libraries/AP_HAL_ChibiOS/hwdef/CubeOrange/hwdef.inc
> +IMU Invensense SPI:icm20602_ext ROTATION_ROLL_180_YAW_270
need to use EK3_PRIMARY and EK2_PRIMARY

2022-11-16 07:37 UTC, tridge commented on libraries/AP_HAL_ChibiOS/hwdef/CubeOrange/hwdef.inc
> +define HAL_ENABLE_FAST_FIFO_RESET_ICM20602 true
prefer 1 and 0 for true and false

2022-11-21 00:34 UTC, tridge commented
@bugobliterator we're about to do copter 4.3.1beta1 - can you update this PR to be ready for backport?

2022-11-21 00:40 UTC, bugobliterator commented
> @bugobliterator we're about to do copter 4.3.1beta1 - can you update this PR to be ready for backport?

@tridge done.

2022-12-24 06:58 UTC, rmackay9 commented
@tridge @bugobliterator,

Shall we merge this one to the 4.3 branch now?  I'm thinking about pushing out 4.3.3-rc1 in the coming days.

2022-12-24 09:48 UTC, bugobliterator commented
> @tridge @bugobliterator,
> 
> Shall we merge this one to the 4.3 branch now?  I'm thinking about pushing out 4.3.3-rc1 in the coming days.

@rmackay9 I am fine with this coming into next rc.

2023-01-07 07:42 UTC, rmackay9 commented
This is included in 4.3.3-rc1

2023-01-09 01:17 UTC, rmackay9 commented
I'm going to close this PR because it's been cherry-picked into the 4.3 branch (or will be shortly)

2023-01-09 01:17 UTC, closed without merging