Plane: Quadplane: correct units used in rate_bf_yaw_target
ArduPilot/ardupilot pull request #22127
Opened 2022-11-05 12:44 UTC by IamPete1

`get_gyro` is rad/sec `rate_bf_yaw_target` is expecting centi-deg/sec.

This is the original intent, but the current code is effectively setting to 0. Changing to that might be a better fix.  

Thanks to @skoch1s for finding the issue. https://github.com/ArduPilot/ardupilot/pull/22109 https://github.com/ArduPilot/ardupilot/issues/22103

2022-11-14 23:00 UTC, tridge commented
@IamPete1 I think changing it to zero is safest, but we could do some flight testing with the original intended value and see what it is like. It would need a lot of testing in different conditions and frames

2022-11-14 23:35 UTC, tridge commented
or possibly use the coordinated turn yaw rate?

2022-11-16 07:34 UTC, tridge requested changes
i'd prefer to either use zero, or calculate the coordinated turn yaw rate from the demanded roll angle and airspeed

2022-11-24 23:29 UTC, IamPete1 commented
@tridge Changed to 0 because it require no extra testing. Possibly we should revisit at some point, but I think this is better than using the wrong units.

2022-11-25 07:12 UTC, tridge approved these changes

2022-11-25 07:13 UTC, merged