Fast sampling for ICM45686
ArduPilot/ardupilot pull request #22144
Opened 2022-11-07 16:24 UTC by andyp1per

2022-11-09 07:42 UTC, tridge requested changes
maybe ifdef for CLKIN pin? need a define in hwdef.dat for OrangePlus

2022-11-09 07:43 UTC, tridge commented
@bugobliterator Andy says the accel scale was wrong? do you have flight test logs?

2022-11-10 03:31 UTC, bugobliterator commented
[log3.zip](https://github.com/ArduPilot/ardupilot/files/9977102/log3.zip)

Here is the log with master. @tridge

2023-02-22 07:06 UTC, tridge approved these changes

2023-02-22 07:06 UTC, merged