Accept MAV_CMD_NAV_WAYPOINT with COMMAND_LONG and COMMAND_INT in GUIDED mode
ArduPilot/ardupilot pull request #22229
Opened 2022-11-18 07:18 UTC by mustafa-gokce

2022-11-18 12:03 UTC, amilcarlucas requested changes

2022-11-18 12:03 UTC, amilcarlucas commented on ArduCopter/GCS_Mavlink.cpp
> +    case MAV_CMD_NAV_WAYPOINT:
Indentation

2022-11-18 12:03 UTC, amilcarlucas commented on libraries/GCS_MAVLink/GCS_Common.cpp
> +    case MAV_CMD_NAV_WAYPOINT:
Indentation

2022-11-18 12:09 UTC, peterbarker commented on ArduCopter/GCS_Mavlink.cpp
> +        return handle_command_int_do_reposition(packet_int);
Isn't the function you're calling here going to ascribe special meaning to param2 which `NAV_WAYPOINT` doesn't have, or has different meanings for?

2022-11-18 17:00 UTC, WickedShell requested changes
Why support `COMMAND_LONG` at all for this? Anything that uses a position for lat/lon is going to experience a fairly significant loss in accuracy. In general anything that could be used to ingest a position like this we should be trying to not add any new paths that are a guaranteed low input accuracy.

I'm also wondering what the value is of using `NAV_WAYPOINT` instead of `DO_REPOSITION` ? As @peterbarker notes theres differences from the spec for what should happen with param2.

2022-11-18 20:30 UTC, mustafa-gokce commented
@amilcarlucas @peterbarker @WickedShell with this update, I tried to implement this without changing any parameters of both commands.
I think this version should supports param2 (and others) now.
Also added protections for zero fields.

2022-11-18 20:42 UTC, WickedShell commented
What is the value/advantage of using this over `MAV_CMD_DO_REPOSITION` which we already support?

I'm just struggling at the moment to see what this enables that we were missing before.

2023-02-20 15:09 UTC, khancyr requested changes
I don't understand why use this kind of message on copter , specially when we already have a lot of message to so. This is looks an old hack from when the setpoints weren't things.

Is there some good advantage to use those messages as commands ?

2024-02-15 09:31 UTC, amilcarlucas commented
@peterbarker didn't you implement this already in 4.5.0? I think this can be closed.

2024-02-17 18:21 UTC, closed without merging

2024-02-17 22:05 UTC, peterbarker commented
@amilcarlucas No, that chunk of work was wround commands rather than nav-waypoint-in-guided mode.

'though I most definitely do want to kill nav-waypoint-in-guided-mode!  A cominbation of `MAV_CMD_DO_REPOSITION`, fixing Plane's change-altitude stuff to solely use set-position-target, and for Copter something to do with changing yaw should allow us to kill the abomination.

Thanks anyway, @mustafa-gokce .

2024-02-19 08:33 UTC, amilcarlucas commented
Should this be reopened and rebased then?