Copter: Reserve G2 63 for Ship Operations
ArduPilot/ardupilot pull request #22251
Opened 2022-11-21 13:06 UTC by lthall

Reserve parameter 63 for use in ship operations mode.

2022-11-21 19:27 UTC, hendjoshsr71 commented on ArduCopter/Parameters.cpp
> +    // ID 63 is reserved for the SHIP_OPS
Yeah that is correct 63 == 0 i believe.  Could drop a comment to that effect? 

However, ship operations are used by plane too. So why not have this at the vehicle level? 

Also should an extension field be reserved for future use?

2022-11-22 00:26 UTC, tridge requested changes

2022-11-22 00:26 UTC, tridge commented on ArduCopter/Parameters.cpp
> +    // ID 63 is reserved for the SHIP_OPS
yes, please use 61

2022-12-12 23:33 UTC, tridge approved these changes

2022-12-12 23:33 UTC, merged

2022-12-12 23:33 UTC, rmackay9 approved these changes