AP_GPS: added support for Unicore GPS modules with AGRICA
ArduPilot/ardupilot pull request #22261
Opened 2022-11-22 05:14 UTC by tridge

This adds support for Unicore GPS modules such as the UM982 which can provide single module, dual antenna moving baseline yaw
It also supports GPS vertical velocity and velocity accuracy, bringing it up to par with other GNSS module drivers like UBLOX

2022-11-23 22:01 UTC, peterbarker requested changes
Didn't spot anything seriously bad.

2022-11-24 06:02 UTC, tridge commented on libraries/AP_GPS/AP_GPS_NMEA.cpp
> +#define AP_GPS_NMEA_CONFIG_PERIOD_MS 15000U
i really doubt it will do any harm. Config commands can generally be sent at any time on a GPS

2022-11-24 06:04 UTC, tridge commented on libraries/AP_GPS/AP_GPS_NMEA.cpp
> +        const bool crc_ok = _is_unicore? (_crc32 == crc) : (_parity == crc);
why? we have thousands of places we do ? without a space before it (about 2x as many as with the space)

2022-11-24 06:06 UTC, tridge commented on libraries/AP_GPS/AP_GPS_NMEA.cpp
> +#if AP_GPS_NMEA_UNICORE_ENABLED
it means we avoid doing the division multiple times

2022-11-24 06:07 UTC, tridge commented on libraries/AP_GPS/AP_GPS_NMEA.h
> +    } _agrica;
personally I'd like all the underscores gone, but the way it works now is top level vars have _ and in structure they don't.

2022-11-24 06:08 UTC, tridge commented on libraries/AP_GPS/GPS_Backend.h
>      // return iTOW of last message, or zero if not supported
comment is still correct - time_week_ms is an iTOW

2022-11-24 06:09 UTC, tridge commented on libraries/AP_GPS/AP_GPS_NMEA.cpp
> +    // subtract 8 to align term numbers with reference manual
i've added a comment - no direct link I can find on vendors website, but can be found with google and some digging

2022-11-24 06:09 UTC, tridge commented on libraries/AP_GPS/AP_GPS_NMEA.cpp
> +                auto &ag = _agrica;
done

2022-12-19 00:14 UTC, tatsuy commented
@tridge Thanks a lot!
I have confirmed that the last two commits work correctly.

2022-12-19 23:23 UTC, peterbarker approved these changes
LGTM

2022-12-19 23:23 UTC, merged