AP_Baro: restore GND_TEMP reset in init()
ArduPilot/ardupilot pull request #22334
Opened 2022-12-02 13:43 UTC by robertlong13

This was accidentally removed in 16f0df0

2022-12-02 13:45 UTC, robertlong13 commented
Should there be an autotest for all parameters that are supposed to reset each boot? I haven't added a test before, but this may be a good first one.

2022-12-06 00:32 UTC, tridge requested changes

2022-12-06 00:32 UTC, tridge commented on libraries/AP_Baro/AP_Baro.cpp
> +    if (!is_zero(_user_ground_temperature)) {
we want to allow users to set the temperature and have it persist

2022-12-06 00:34 UTC, tridge commented
it was a deliberate change to persist this value between reboots

2022-12-06 00:36 UTC, tridge requested changes

2022-12-06 00:36 UTC, tridge commented on libraries/AP_Baro/AP_Baro.cpp
> +    if (!is_zero(_user_ground_temperature)) {
we need to fix the param docs to remove this:
```
This parameter is not persistent and will be reset to 0 every time the vehicle is rebooted
```

2022-12-06 02:03 UTC, robertlong13 commented
Ah, I made the mistake of only looking at the commit, and forgot to look for an associated pull request to see justification for that.

Makes sense.

2022-12-09 21:34 UTC, closed without merging