Copter: Add MANUAL_CONTROL to telemetry
ArduPilot/ardupilot pull request #22349
Opened 2022-12-05 18:20 UTC by muramura

I want to get the value of the propo as a joystick value.
I can operate the vehicle with MANUAL_CONTROL by getting this value.
The advantage is that the CC can operate the vehicle without being aware of the PWM value.

RC1-4: 1000 PWM
![Screenshot from 2022-12-06 02-44-30](https://user-images.githubusercontent.com/646194/205712127-76789553-d5ec-4d3f-b253-9452183f3a30.png)

RC1-4: 1500 PWM
![Screenshot from 2022-12-06 02-46-49](https://user-images.githubusercontent.com/646194/205712567-bad72625-f953-4a9b-b9df-522409af6ee3.png)

RC1-4: 2000 PWM
![Screenshot from 2022-12-06 02-47-34](https://user-images.githubusercontent.com/646194/205712610-2b0c5218-78e8-4d64-8d63-fd293a4125d8.png)

2022-12-05 23:24 UTC, WickedShell requested changes
Why does this help a companion computer? Normalized inputs should be possible to be used directly.

I do like the idea of normalized monitoring, but I'm not sure that I am seeing how this helps us in the application, particularly enough to justify the extra bandwidth usage by default.

2022-12-05 23:24 UTC, WickedShell commented on ArduCopter/GCS_Mavlink.cpp
> +        1,
Needs to be the GCS id, not hard coded. In fact by default this actually would target the same autopilot that sends the message, particularly bad if you have any routing loops.

2022-12-05 23:24 UTC, WickedShell commented on ArduCopter/GCS_Mavlink.cpp
> +    MSG_MANUAL_CONTROL,
There's too many things in this stream. I'm not sure if we should be sending this by default, and leave it up to the stream rate request handling.

2024-09-27 12:51 UTC, peterbarker commented
This is a message used to control vehicles - it's right there in the `description` field.

It's *not* a reporting message.  If we wanted one of those we'd make one - in the same way that we have "RC_CHANNELS".  Alternatively, you could try to convince upstream mavlink to change the description of this message to also allow for reporting - but I think such re-use would be a terrible idea when a new message would be relatively straight-forward.

Sorry, wrong use of this message, closing this.

2024-09-27 12:51 UTC, closed without merging