Gh update
ArduPilot/ardupilot pull request #22370
Opened 2022-12-09 11:48 UTC by khancyr

Update github action to fix: 
```
 build (base, sitltest-can)
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/cache@v2, coverallsapp/github-action@master
```

add ccache config to test_size as it is missing

2022-12-10 00:12 UTC, peterbarker requested changes

2022-12-10 00:12 UTC, peterbarker commented on .github/workflows/test_size.yml
> +          . .github/workflows/ccache.env
This seems to have broken things?

2023-01-16 15:17 UTC, khancyr commented
@peterbarker update and corrected

2023-01-19 21:27 UTC, peterbarker approved these changes

2023-01-31 06:58 UTC, merged

2023-01-31 06:59 UTC, peterbarker commented
Merged this, thanks!

Let's keep a it of an eye on CI to see if everything still runs smoothly...