Plane: move adjust_altitude_target functionality to per mode functions
ArduPilot/ardupilot pull request #22380
Opened 2022-12-11 13:36 UTC by IamPete1

A none functional re-work of the `adjust_altitude_target` function, moving functionality down into the existing per-mode `update_target_altitude` function. This simplifys code by keeping mode specific functionality in mode files.

The if's for fbwb, cruise, loiter and guided have been moved down. The remaining functionality is then moved to the base `Mode` class. Currently this is left in `altitude.cpp` to minimize the diff (just lots of `plane.` due to the namespace change), but it should be moved into `mode.cpp` in the future.

2022-12-11 15:45 UTC, IamPete1 commented on ArduPlane/mode_guided.cpp
> +#endif
Cant just not override in `mode.h` as including `config.h` to get `OFFBOARD_GUIDED` breaks the build in lots of exciting ways.

2022-12-14 08:39 UTC, tridge requested changes

2022-12-14 08:39 UTC, tridge commented on ArduPlane/altitude.cpp
> +        plane.set_target_altitude_location(plane.next_WP_loc);
can we have the adding of the plane. as a separate commit? that should make the diff a lot more readable

2022-12-14 12:43 UTC, IamPete1 commented
@tridge Split into two commits and left the guided function in `altitude.cpp` for the time being. Per commit diff is now much easier to work out.

2022-12-19 23:36 UTC, tridge approved these changes

2022-12-19 23:37 UTC, merged