Correct gcs-channel-offset check
ArduPilot/ardupilot pull request #22399
Opened 2022-12-14 02:10 UTC by peterbarker

Off-by-one error.

The equivalent change was made by tridge at some stage, but it is not in master or Pl;ane-4.3.1 and I can't find a PR....

Corrected two places that were relying on being able to get a nullptr back from `chan(i)`.

Built on top of https://github.com/ArduPilot/ardupilot/pull/22398

2022-12-14 07:45 UTC, tridge requested changes
we may need some nullptr checks

2022-12-14 07:45 UTC, tridge commented on libraries/GCS_MAVLink/GCS.h
> +            INTERNAL_ERROR(AP_InternalError::error_t::gcs_offset);      \
we should remove this INTERNAL_ERROR(), it makes no sense to fail for normal API usage

2022-12-14 07:45 UTC, tridge commented on libraries/GCS_MAVLink/GCS.h
> +            INTERNAL_ERROR(AP_InternalError::error_t::gcs_offset);      \
should remove internal error, and check nullptr

2022-12-15 21:49 UTC, peterbarker commented
Hopefully replaced by https://github.com/ArduPilot/ardupilot/pull/22411

2023-02-07 08:28 UTC, closed without merging