GCS_MAVLink: Ensure serial tunnel avoids nullptr
ArduPilot/ardupilot pull request #22397
Opened 2022-12-14 00:39 UTC by stephendade

This solves an ``Internal errors 0x40000 l:15 gcs_offset`` caused by trying to access a nonexistent MAVLink channel.

Tested on a CubeOrange.

2022-12-14 01:20 UTC, peterbarker requested changes
This will make for a smaller patch.

We have plenty of cases already in the code where we don't have the nullptr check you're removing, so that's some good bytes saved :-)

2022-12-14 01:20 UTC, peterbarker commented on libraries/GCS_MAVLink/GCS_serial_control.cpp
> +                break;
```suggestion
            if (link->get_uart() != port) {
                continue;
            }
            link->lock(exclusive);
            break;
```

2022-12-14 01:28 UTC, stephendade commented on libraries/GCS_MAVLink/GCS_serial_control.cpp
> +                break;
Fixed!

2022-12-14 01:29 UTC, peterbarker approved these changes
LGTM

2022-12-14 07:43 UTC, tridge commented
we should just remove the internal error, we should not be throwing an internal error on the intended use of the PR

2022-12-21 08:54 UTC, tridge commented
@peterbarker still want this to go in?

2023-01-23 09:15 UTC, khancyr commented
@peterbarker @stephendade ping on this ? I looks fine to me

2023-01-23 21:34 UTC, stephendade commented
@peterbarker's got an alternative fix in https://github.com/ArduPilot/ardupilot/pull/22411 - if that fix goes in, I'm happy to close this one.

2023-01-23 23:26 UTC, rmackay9 commented
@stephendade, @peterbarker

PeterB's alternative fix got stuck because it uses a new pattern that I'm not sure we want to introduce.  I think if we want to get this fix in in the near future we should consider this PR again.

2023-02-08 22:02 UTC, stephendade commented
This is included in the now-merged #22469, so closing this PR.

2023-02-08 22:02 UTC, closed without merging