set RemoteID status to Emergency if vehicle is lost
ArduPilot/ardupilot pull request #22448
Opened 2022-12-19 16:13 UTC by BluemarkInnovations

According to the FAA MoC, the drone should set the location status to emergency  in case of Uncontrolled descent or loss of control. See also https://github.com/ArduPilot/ArduRemoteID/issues/34

In this PR, the location status is set to emergency when the vehicle is set to vehicle_lost. Not sure if there are other emergency cases in which we also need to set the location status to emergency.

@tridge

2022-12-19 19:00 UTC, IamPete1 commented
You could check if the parachute has deployed. Advanced failsafe also has the option to terminate the vehicle.

2022-12-19 19:12 UTC, muramura commented
AP_HAL::panic method rules infinitely.
The state to access this method is also emergency.

2022-12-19 19:55 UTC, BluemarkInnovations commented
> You could check if the parachute has deployed. Advanced failsafe also has the option to terminate the vehicle.
@IamPete1 

Added.



> AP_HAL::panic method rules infinitely. The state to access this method is also emergency.
@muramura I did check the panic methods in the AP_HAL library. So far they are only triggered in an init function or in a simulation function. Therefore I have not added this to the emergency check.

2022-12-19 20:10 UTC, muramura commented
This code is incorporated in FMUV3.

https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_InternalError/AP_InternalError.cpp#L112
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_InternalError/AP_InternalError.cpp#L129

2022-12-20 09:42 UTC, BluemarkInnovations commented
added the Advanced failsafe and use the internal fault_type to cover the AP_HAL::panic.

2023-01-16 04:24 UTC, tridge requested changes
i've incorporated the watchdog check into the other PR, along with a GPS check with a new option bit for non-GPS operation

2023-01-16 04:24 UTC, tridge commented on libraries/AP_OpenDroneID/AP_OpenDroneID.cpp
> +#ifdef ADVANCED_FAILSAFE
this ifdef doesn't work as the define is at the vehicle level

2023-01-16 04:24 UTC, closed without merging