Copter: Use wp_start() in do_nav_wp()
ArduPilot/ardupilot pull request #22446
Opened 2022-12-19 14:39 UTC by lthall

This PR removes code duplication and reduced the chance of bug introduction by using wp_start(target_loc) in do_nav_wp() like other DO functions.

2022-12-20 01:17 UTC, tridge commented
@rmackay9 needs your review, looks good to me

2022-12-22 04:19 UTC, rmackay9 requested changes
There's a small change in behaviour here in that the wp_start can actually fail to set the location. Because we do not handle this subsequent calls may end up setting the next waypoint.  I think we need to add a boolean to wp_start and exit early if it fails.

2022-12-24 07:03 UTC, rmackay9 approved these changes

2022-12-24 07:03 UTC, merged

2022-12-24 07:03 UTC, rmackay9 commented
Merged, thanks!