UARTDriver: add option to create uart connection to file
ArduPilot/ardupilot pull request #22479
Opened 2022-12-23 01:19 UTC by peterbarker

2022-12-23 08:23 UTC, khancyr commented on libraries/AP_HAL_SITL/UARTDriver.cpp
> +            if(_connected) {
space

2022-12-23 23:09 UTC, peterbarker commented on libraries/AP_HAL_SITL/UARTDriver.cpp
> +            if(_connected) {
Fixed.

2023-01-01 01:26 UTC, peterbarker commented
@khancyr are you happy with this now?  I'll probably do a bit of a Wiki mod to show how to use it.

That's basically this:
```
pbarker@fx:~/rc/ardupilot(pr/hwing-telem)$ ./Tools/autotest/sim_vehicle.py --gdb --debug -v plane -f plane -A --uartF=file:ESC_RAW_V3.bin --speedup=1 --console
```

2023-01-01 13:29 UTC, Hwurzburg requested changes
perhaps extend comment block to include this?

also, I think we should take a few minutes sometime to go thru the options for sim_vehicle together so that I can update the wiki on all the missing options...when you have a chance

2023-01-02 23:22 UTC, tridge approved these changes

2023-01-03 04:21 UTC, peterbarker commented
> perhaps extend comment block to include this?
> 
> also, I think we should take a few minutes sometime to go thru the options for sim_vehicle together so that I can update the wiki on all the missing options...when you have a chance

Comment added.  Where do you think we should document this in the Wiki?  Ping me on Discord with that answer to that ;-)

2023-01-04 01:29 UTC, merged