AP_Scripting: fixed derry turn in aerobatics
ArduPilot/ardupilot pull request #22508
Opened 2022-12-27 07:52 UTC by tridge

![image](https://user-images.githubusercontent.com/831867/209631857-a1b67a05-5101-4d13-b0ad-5c425f06fca1.png)

2022-12-27 09:31 UTC, andypnz requested changes
The scale example Derry Turn is missing the roll length parameter... But with this added it works great :-)

align_center
message: DerryTurn
derry_turn 140 60 XX

2022-12-27 09:59 UTC, andypnz commented
And the final roll angle direction here should not be negative........


{ path_horizontal_arc(-radius, 90), roll_angle_exit(-direction*abs_bank) },

2022-12-27 10:06 UTC, tridge commented
@andypnz thanks, fixed

2022-12-28 09:50 UTC, andypnz approved these changes

2022-12-28 20:49 UTC, merged