Tools/autotest: automate sim_vehicle in WSL2
ArduPilot/ardupilot pull request #22557
Opened 2023-01-03 02:10 UTC by magicrub

This allows sim_vehicle to know we're in WSL2 and auto-forward mavproxy's --out on 14550 and 14551 to the host IP. This makes MissionPlanner automagically work without having to add any flags to sim_vehicle

2023-01-03 02:44 UTC, peterbarker requested changes
Nice!

2023-01-03 02:44 UTC, peterbarker commented on Tools/autotest/sim_vehicle.py
> +    return ""
```suggestion
    if not under_wsl2():
        return None
    pipe = subprocess.Popen(
        "grep -m 1 nameserver /etc/resolv.conf | awk '{print $2}'",
         shell=True,
         stdout=subprocess.PIPE)
    output_lines = pipe.stdout.read().decode('utf-8').strip(' \r\n')
    ret = pipe.wait()

    if ret == 0:
         // add a comment here about what hit means
        return None

    if not output_lines:
         // add a comment here about what hit means
        return None

    return str(output_lines)
```

2023-01-04 00:38 UTC, magicrub commented on Tools/autotest/sim_vehicle.py
> +    return ""
yup, sounds good. changed

2023-01-04 09:03 UTC, peterbarker approved these changes
Great stuff, thanks!

2023-01-04 09:03 UTC, merged