AP_BattMoniter: don't allow equal low and critical FS thresholds
ArduPilot/ardupilot pull request #22631
Opened 2023-01-11 17:08 UTC by IamPete1

Fix for the issues from: https://discuss.ardupilot.org/t/no-rtl-engagement-after-a-fail-safe-battery/95312

In that case both low and critical voltage thresholds were the same so the low action of RTL was skipped for the critical action of none.

This is one way to fix of course, if the voltages are not the same but very close the same thing might happen if the battery is dropping fast. Maybe we should enforce some minimum split? Maybe low must be 1v above critical. Not really sure what threshold for capacity should be. We could use a percentage....

The other fix would be to take the low battery action if not in low failsafe and critical action is none, but that makes the failfafe behavior less clear for users.

2023-01-11 19:52 UTC, andyp1per approved these changes
LGTM

2023-01-11 20:04 UTC, Hwurzburg commented
I do not know why this is an issue.....its doing what its programmed to do by the user....by default low volt is 10.5, with no action, crit volt and action are disabled....to get the issue you talk about the user had to intentionally change things...do not undue his changes....he may have had a reason to skip the low (testing...whatever)

2023-01-11 20:05 UTC, Hwurzburg requested changes
I do not think this is correct

2023-01-11 20:19 UTC, IamPete1 commented
@Hwurzburg If the low and critical voltages are the same it bypasses the low voltage action, yes that is a miss configuration, but this is a trivial change to catch that. If this was intentional the user can zero low voltage threshold and bypass this arming check.

2023-01-13 15:03 UTC, IamPete1 commented
Another log with the same issue, https://discuss.ardupilot.org/t/rtl-did-not-triggered-while-the-batter-failsafe-was-triggerd/95402/2

2023-01-13 17:26 UTC, WickedShell commented
@IamPete1 thinking about it a bit more, I'm still happy with your proposed changes here, but an additional fix that probably makes sense would be to say if we just triggered both failsafes, but one of the actions is none (which I think is the same on all vehicles), we should still go to critical, but we should invoke the failsafe handler that actually does something. Because there's always the situation where the arming check passes something with a difference of say 0.01 V, but that we happen to step past that in a single update call and end up in the same scenario.

2023-01-16 23:34 UTC, tridge approved these changes

2023-01-16 23:36 UTC, merged