AP_OSD: Add Average Cell Rest Volt item
ArduPilot/ardupilot pull request #22660
Opened 2023-01-15 01:11 UTC by MichelleRos

Adds an OSD item for the average cell's resting voltage. Really useful in FPV to be able to check the voltage without first having to make sure to be at a low throttle.

Tested on my quad. Works as expected.

2023-01-15 09:28 UTC, andyp1per commented
I like the idea, but it's 1/2k for a fairly esoteric feature - you might need to limit to 2Mb boards

2023-01-15 20:44 UTC, Hwurzburg requested changes
just use an OSD_OPTION to make the avgcell display be either current or resting voltage...should save a lot of code duplication

2023-01-17 03:17 UTC, MichelleRos commented
@andyp1per I think it would be really confusing to users to have just a single osd element be limited to 2MB boards. We either need to pick a set of OSD parameters that are only available on 2MB boards (and document that 1MB boards only have limited OSD features) or we need to have them all available on 1MB boards.

@Hwurzburg The three existing OSD voltage options don't use that mechanism, probably because people may want to see both voltages separately. I was just following the precedent. If we wanted to go that path we'd have to remove the OSD element for resting voltage for the whole battery as well and have both of them in the OSD_OPTIONs.

2023-01-17 04:06 UTC, Hwurzburg commented
I was actually against the code used for average cell as being a bit esoteric and not used by many....obviously main and secondary voltage would be displayed together if you have two batteries....and I can see the use for resting voltage instead of main battery voltage (I think Tridge actually prefers that), but having both cell and resting cell at the same time is a bit much to my thinking...at this point code versus a less used element is the primary consideration....it was not two years ago...
-my first position would be again that resting cell does not warrant any code at all
-my compromise position would be that you get either cell or resting cell, not both, and use an option to minimize the impact

2023-01-17 04:18 UTC, MichelleRos commented
@Hwurzburg I meant there's three items just for the single battery already: main voltage, main resting voltage and avg cell voltage. So my position is the same: If we want resting to be an option instead of a separate item, then we need to do that with the main voltage as well, rather than having different mechanisms for the main voltage and the per-cell voltage. 

As I noted in the PR description, having the resting option is really useful because with FPV you might be at high throttle with the battery pulled down to 3.6 or lower even though it's still 90% charged. Then it's much better to have the resting voltage tell you it's at 4.0v than having to stop what you're doing and lower the throttle before you can do something as simple as checking the battery voltage. And with quads where your total flight time is only a few minutes, this has to be done quite frequently.

2023-01-17 06:13 UTC, Hwurzburg commented
I would like to see a code reduction by using an option to select either the current voltage or resting voltage  for any voltage panel and eliminate the resting voltage panel code ....however that would break existing setups, and is scope creep...

2023-01-22 03:49 UTC, tridge requested changes

2023-01-22 03:49 UTC, tridge commented on libraries/AP_OSD/AP_OSD_Screen.cpp
> +{
maybe make a draw_avgcellrestvolt_common() and pass a boolean for which to display

2023-01-27 16:46 UTC, andyp1per commented
I feel like we should only be displaying a single voltage - all these options are highly confusing. I am confused and I fly FPV a lot. Maybe the problem is not in the OSD but in the battery monitor. We already know that sag compensation is not useful for punch outs because the update is too slow and I am planning to fix this sometime relatively soon. If we do this does the OSD issue go away?

2023-01-27 22:01 UTC, Hwurzburg commented
I agree that I dont see why one needs more than one OSD voltage panel per battery, which could be cell/resting/cell/voltage/resting voltage depending on a param or option....but it would have to be done at a major release....breaking someone's old setup (does not warrant param conversion ...wont be saving flash that way) is not major regarding OSD IMO and is easily fixed in with one or two parameter changes by the user....I was against the cell panel originally anyway since most people flying know the low cell for their battery voltage and can do the math in their head.... 
I always fly with battery voltage and know that 12V is 3.0/cell on 4s and 9V is for 3s, etc....easy head math....but we added it...
I personally would be in favor a single voltage panel per batt and save the code space

2023-02-05 21:57 UTC, tridge commented
@MichelleRos can you make a common function like I suggested above? It should make for less flash space

2023-02-06 03:36 UTC, MichelleRos commented
@tridge Yup, I just haven't had the time to make that change yet. Will do that soon.

Would've been useful to know that the PR was gonna be on the Dev Call... Annoyingly, GitHub doesn't seem to send any notifications about it.

2023-02-06 04:14 UTC, MichelleRos commented
@tridge I just hadn't gotten around to it. I've now updated it with that change.

Would've been useful to know that the PR was gonna be on the Dev Call (I missed it as I can usually only make the EU dev call)... Annoyingly, GitHub doesn't seem to send any notifications about it.

2023-02-12 11:41 UTC, MichelleRos commented
Closed in favour of #22843

2023-02-12 11:41 UTC, closed without merging