SITL:make GPS param consistent names
ArduPilot/ardupilot pull request #22664
Opened 2023-01-15 21:25 UTC by Hwurzburg

all other first instance GPS names are just GPS

2023-01-15 21:38 UTC, tridge requested changes

2023-01-15 21:38 UTC, tridge commented on libraries/SITL/SITL.cpp
> +    AP_GROUPINFO("MAG_1ODI",        8, SIM,  mag_offdiag[0], 0),
type, should be MAG1_ODI

2023-01-15 22:06 UTC, Hwurzburg commented on libraries/SITL/SITL.cpp
> +    AP_GROUPINFO("MAG_1ODI",        8, SIM,  mag_offdiag[0], 0),
already caught that and pushed fix

2023-01-16 01:31 UTC, peterbarker approved these changes
LGTM

2023-01-16 04:49 UTC, tridge commented
there are some tests in Tools/autotest/common.py that need updating for the new name

2023-01-16 21:45 UTC, tridge approved these changes

2023-01-16 21:45 UTC, merged