AP_RCTelemetry: Change GCC12.2 warning
ArduPilot/ardupilot pull request #22700
Opened 2023-01-20 22:08 UTC by muramura

I tried to build with GCC 12.2.
I found the warning.
I changed the warning.
I could free up 9K bytes by going to GCC 12.2.

GCC 12.2
Waf: Leaving directory `/home/muramura/work2/ardupilot/build/CubeOrangePlus'

BUILD SUMMARY
Build directory: /home/muramura/work2/ardupilot/build/CubeOrangePlus
Target          Text (B)  Data (B)  BSS (B)  Total Flash Used (B)  Free Flash (B)
---------------------------------------------------------------------------------
bin/arducopter   1791313      3472   258900               1794785          171276

GCC 11.3
Waf: Leaving directory `/home/muramura/work2/ardupilot/build/CubeOrangePlus'

BUILD SUMMARY
Build directory: /home/muramura/work2/ardupilot/build/CubeOrangePlus
Target          Text (B)  Data (B)  BSS (B)  Total Flash Used (B)  Free Flash (B)
---------------------------------------------------------------------------------
bin/arducopter   1799649      3472   258900               1803121          162940

2023-01-20 23:36 UTC, muramura commented
I saw the following build warning.
I responded with this PR.

../../libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp: In member function 'void AP_CRSF_Telem::update_vtx_params()':
../../libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp:828:21: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
  828 |         crcptr[len] = crc;
      |         ~~~~~~~~~~~~^~~~~
In file included from ../../libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp:16:
../../libraries/AP_RCTelemetry/AP_CRSF_Telem.h:114:17: note: at offset [5, 6] into destination object 'AP_CRSF_Telem::CommandFrame::destination' of size 1
  114 |         uint8_t destination;
      |                 ^~~~~~~~~~~
../../libraries/AP_RCTelemetry/AP_CRSF_Telem.h:114:17: note: at offset [5, 6] into destination object 'AP_CRSF_Telem::CommandFrame::destination' of size 1
../../libraries/AP_RCTelemetry/AP_CRSF_Telem.h:114:17: note: at offset [5, 6] into destination object 'AP_CRSF_Telem::CommandFrame::destination' of size 1
../../libraries/AP_RCTelemetry/AP_CRSF_Telem.h:114:17: note: at offset [5, 6] into destination object 'AP_CRSF_Telem::CommandFrame::destination' of size 1
../../libraries/AP_RCTelemetry/AP_CRSF_Telem.h:114:17: note: at offset [5, 6] into destination object 'AP_CRSF_Telem::CommandFrame::destination' of size 1
../../libraries/AP_RCTelemetry/AP_CRSF_Telem.h:114:17: note: at offset [5, 6] into destination object 'AP_CRSF_Telem::CommandFrame::destination' of size 1
../../libraries/AP_RCTelemetry/AP_CRSF_Telem.h:114:17: note: at offset [5, 6] into destination object 'AP_CRSF_Telem::CommandFrame::destination' of size 1
../../libraries/AP_RCTelemetry/AP_CRSF_Telem.h:114:17: note: at offset [5, 6] into destination object 'AP_CRSF_Telem::CommandFrame::destination' of size 1
../../libraries/AP_RCTelemetry/AP_CRSF_Telem.h:114:17: note: at offset [5, 6] into destination object 'AP_CRSF_Telem::CommandFrame::destination' of size 1
../../libraries/AP_RCTelemetry/AP_CRSF_Telem.h:114:17: note: at offset [5, 6] into destination object 'AP_CRSF_Telem::CommandFrame::destination' of size 1
../../libraries/AP_RCTelemetry/AP_CRSF_Telem.h:114:17: note: at offset [5, 6] into destination object 'AP_CRSF_Telem::CommandFrame::destination' of size 1

2023-01-21 09:25 UTC, andyp1per requested changes
I don't believe this is correct. You need to find a way to satisfy the compiler without changing the packed structure

2023-01-25 00:01 UTC, peterbarker commented
> I don't believe this is correct. You need to find a way to satisfy the compiler without changing the packed structure

I don't believe this PR changes the result of the function; it's just eliminating an intermediate variable.  Adding a bytes array to the union isn't an unusual thing in ArduPilot.

2023-06-16 10:16 UTC, khancyr commented
fixed by https://github.com/ArduPilot/ardupilot/pull/22971

2023-06-16 10:16 UTC, closed without merging