AP_Compass: add and use AP_COMPASS_LSM303D_ENABLED
ArduPilot/ardupilot pull request #22753
Opened 2023-01-27 04:52 UTC by peterbarker

2023-01-27 05:10 UTC, peterbarker commented
```
Board              AP_Periph  blimp  bootloader  copter  heli  iofirmware  plane  rover  sub
Durandal                      0      *           0       0                 0      0      0
Hitec-Airspeed     0                                                                     
KakuteH7-bdshot               0      *           0       0                 0      0      0
MatekF405                     0      *           0       0                 0      0      0
Pixhawk1-1M                   0      *           0       0                 0      0      0
f103-QiotekPeriph  *                                                                     
f303-Universal     0                                                                     
iomcu                                                          *                         
revo-mini                     0      *           0       0                 0      0      0
skyviper-v2450                                   -1424                                   
```

2023-01-31 00:03 UTC, tridge requested changes

2023-01-31 00:03 UTC, tridge commented on Tools/autotest/test_build_options.py
> +                'AP_COMPASS_LSM303D_ENABLED',
odd CubeOrange doesn't have a LSM303D ....

2023-01-31 00:08 UTC, merged

2023-01-31 00:08 UTC, tridge commented on Tools/autotest/test_build_options.py
> +                'AP_COMPASS_LSM303D_ENABLED',
peter explained ...