AC_AttitudeControl: change to using ticks for is_active
ArduPilot/ardupilot pull request #22766
Opened 2023-01-28 09:47 UTC by tridge

this fixes a bug if scheduling is very uneven. The particular case I hit was with XPlane simulating a quadplane, and the timing is erratic enough that the XY controller was continually reset during back transitions causing the quadplane to crash. This can happen when you have a very slow loop followed by a fast loop

Using ticks is a much better approach, and tests what is_active means to test

2023-01-28 12:35 UTC, lthall requested changes
The idea of this check is to make sure we run this on every loop. In that case we should be using:
dt_ticks == 1

Unless I misunderstand something here?

2023-01-28 12:35 UTC, lthall commented on libraries/AC_AttitudeControl/AC_PosControl.cpp
> +    return dt_ticks < 3;
can't we just use dt_ticks == 1 now?

2023-01-28 19:43 UTC, tridge commented
> In that case we should be using: dt_ticks == 1

I was trying to make it match existing behaviour approximately. I've now changed it to <= 1. We can't use == 1 as it could be zero depending on call order

2023-01-28 19:43 UTC, tridge commented on libraries/AC_AttitudeControl/AC_PosControl.cpp
> +    return dt_ticks < 3;
i've changed it to <= 1

2023-01-29 00:47 UTC, lthall approved these changes
Nice!

2023-01-29 04:28 UTC, merged