Copter: Add option to resume precland after reposiiton
ArduPilot/ardupilot pull request #22773
Opened 2023-01-29 10:14 UTC by rishabsingh3003

Currently, if the user were to reposition the vehicle during a Prec Land manually, it would cancel Prec Land and not resume it even if the target was in view (i.e Copter just does a normal land). 
By using PLND_OPTIONS parameter, one can now allow resuming prec land even after a manual reposition. 

This has been tested on SITL

2023-01-29 17:13 UTC, khancyr requested changes
Need a #if guard again precland to work.

Otherwise, the feature can be interesting and the implementation won't impact much the code if the option isn't enabled. So that is fine.

2023-01-29 17:13 UTC, khancyr commented on ArduCopter/mode.cpp
> +                if (copter.ap.land_repo_active && copter.precland.allow_precland_after_reposition()) {
Copter.ap.land_repo_active is totally redundant here.

2023-01-29 17:13 UTC, khancyr commented on ArduCopter/mode.cpp
> +                if (copter.ap.land_repo_active && copter.precland.allow_precland_after_reposition()) {
Probably need a guard to check that precland is available otherwise the copter.precland object won't exist

2023-01-30 15:53 UTC, rishabsingh3003 commented
@khancyr thanks! I have fixed those things, however, the RTL land_repo_active isn't related to precland in any way. For prec land, RTL calls the same controller, which we have already fixed in this PR.

2023-01-30 16:33 UTC, khancyr commented
yep, my bad on this, was looking at the wrong codebase. that is fine then as indeed descent_run() don't use precland yet

2023-01-31 10:56 UTC, merged

2023-01-31 10:56 UTC, rmackay9 commented
Merged thanks!

2023-02-09 05:27 UTC, rmackay9 commented
This is included in Copter-4.3.4-rc1