Update pyenv for new MacOS Clang13
ArduPilot/ardupilot pull request #22821
Opened 2023-02-03 13:53 UTC by rbeall

https://bugs.python.org/issue45405

Version of pyenv 2.3.12 has patched most versions of python to properly compile with Mac clang 13.  This version is required to properly install python on new machine.

2023-02-03 14:57 UTC, andyp1per approved these changes

2023-02-03 16:50 UTC, khancyr requested changes
should be ok.
Could you start your commit with : `Tools:` we alsways start commit with the name of the system/directory impacted

2023-02-06 11:18 UTC, khancyr commented
can be merged safely, it pass MACOS test that is the only one impacted

2023-02-07 10:14 UTC, peterbarker commented
I've rebased this and amended the commit comment.

The first CI run went badly - let's see how it goes this time...

2023-02-07 21:54 UTC, merged

2023-02-07 21:54 UTC, peterbarker commented
Merged, thanks!