AP_OSD:Add avg resting cell and refactor
ArduPilot/ardupilot pull request #22843
Opened 2023-02-06 17:15 UTC by Hwurzburg

Co-authored-by: MichelleRos

this implements the functionality of #22660 but save almost 500 bytes instead of costing flash

2023-02-06 22:16 UTC, tridge requested changes

2023-02-06 22:16 UTC, tridge commented on libraries/AP_OSD/AP_OSD.h
> +    enum {
make this an enum class

2023-02-06 22:16 UTC, tridge commented on libraries/AP_OSD/AP_OSD_Screen.cpp
> +void AP_OSD_Screen::draw_bat_volt(uint8_t instance,uint8_t type,uint8_t x, uint8_t y)
uint8_t type should be the enum class type

2023-02-06 23:45 UTC, tridge approved these changes

2023-02-06 23:46 UTC, tridge commented
@MichelleRos can you test this? Should have your feature and saves flash

2023-02-06 23:48 UTC, peterbarker commented on libraries/AP_OSD/AP_OSD.h
> +
whitespace aded

2023-02-06 23:48 UTC, peterbarker commented on libraries/AP_OSD/AP_OSD_Screen.cpp
> +        }
```suggestion
    case VoltageType::VOLTAGE:
        break;
```

2023-02-12 11:39 UTC, MichelleRos approved these changes
Tested on my quad. Works well. Thanks. 🙂

2023-02-13 13:21 UTC, Hwurzburg commented on libraries/AP_OSD/AP_OSD_Screen.cpp
> +        }
not according to astyle

2023-02-14 00:06 UTC, merged