AP_BattMonitor: Allow manual control of MPPT power on/off state via new param
ArduPilot/ardupilot pull request #22869
Opened 2023-02-08 20:16 UTC by magicrub

Current DroneCAN MPPT driver power ONN/OFF state is entirely event driven (boot on arm/disarm events). There is no way to manually set it on or off, for example, during flight. The PR adds a new param BATTx_MPPT_EN which shows the state of the mppt and if you change that then it sets the MPPT's state to that.

Disabled on <=1 MB boards. Uses 80 bytes flash on CubeOrange.

This is a follow on to PR https://github.com/ArduPilot/ardupilot/pull/22868 .

2023-02-14 00:58 UTC, Hwurzburg requested changes

2023-02-14 00:58 UTC, Hwurzburg commented on Tools/scripts/build_options.py
> +    Feature('Battery', 'BATTMON_MPPT_EN_PARAM', 'AP_BATTMONITOR_UAVCAN_MPPT_USE_STATUS_AND_OVERRIDE_PARAM', 'Enable param BATTn_MPPT_EN to manually set the ON/Off power state', 0, None), # noqa: E501
extract_featuress.py addition needed

2023-02-14 01:01 UTC, tridge requested changes
this looks like it would be better to add a lua binding for get/set and a script

2023-02-14 01:01 UTC, tridge commented on libraries/AP_BattMonitor/AP_BattMonitor_UAVCAN.cpp
> +    AP_GROUPINFO("MPPT_EN", 31, AP_BattMonitor_UAVCAN, _mppt.powered_state_param, -1),
could add this param in scripting

2023-02-14 01:06 UTC, magicrub commented
options from devcall:
- move to scripting
- maybe aux functions
- name valued pair
- whole new concept to turn on/ff a battery backend

2023-02-17 22:49 UTC, magicrub commented
replaced by https://github.com/ArduPilot/ardupilot/pull/22965 using an AUX_FUNC

2023-02-17 22:49 UTC, closed without merging