Missions: Enhanced JUMP_TAG
ArduPilot/ardupilot pull request #22873
Opened 2023-02-08 22:54 UTC by magicrub

This extends PR https://github.com/ArduPilot/ardupilot/pull/22421 to give it a concept of an active jump tag for scripting.

Logic:
- we execute a DO_JUMP_TAG and jump to that tag's mission index (which completes immediately like a DO_JUMP)
- Set active flag to true
- start executing next NAV command, flag stays true
- start executing next NAV command, flag set to false

Basically, if you do a DO_JUMP_TAG then while executing the NAV you can know that you've started or triggered some sort of event.

See included lua script that uses a few tags to:
- know when we're starting to fly over the runway to start sampling lidar distance data
- know when we're done to get an avg 'true' altitude compared to baro
- offset baro altitude by that averaged alt
- check the wind and decide to continue with current landing pattern or jump to the alternate/reversed pattern/direction

2023-02-13 23:39 UTC, tridge requested changes

2023-02-13 23:39 UTC, tridge commented on libraries/AP_Scripting/generator/description/bindings.desc
> +singleton AP_Mission method get_current_tag boolean uint16_t'Null
i'd like to make this not auto-clear the flag, and instead return the number of NAV commands executed since the tag was started

2023-02-13 23:39 UTC, tridge commented on ROMFS/scripts/jump_tags_into_wind_landing.lua
> +
should be in examples/ not ROMFS/

2023-02-14 00:06 UTC, rmackay9 commented
The jumps can be complex so let's be sure to test as many edge cases as we can think of including:

1. do-jump-tag to a tag that doesn't exist (mission should continue without jumping)
2. do-jump-tag to a tag that appears just before another do-jump-tag
3. do-jump-tag to a tag that appears just before another do-jump
4. do-jump that points to a do-jump-tag
5. do-jump that points to a do-jump-tag with an invalid tag (mission should continue without jumping)

We should also add an autotest.

2023-02-14 04:15 UTC, IamPete1 commented
Lua CI error is because you need to add your new functions to the documentation. Here somewhere:

https://github.com/ArduPilot/ardupilot/blob/b26d771c9f2c4028e3ff16a2b267242f35bdf06c/libraries/AP_Scripting/docs/docs.lua#L1308

You can build with AP `--scripting-docs` and it will auto generate for you, just need to discard all the other changes except your new bindings. Bonus points for making the arguments useful names and adding extra info in the description. 

Also setup this extension to get docs in VS code. https://www.youtube.com/watch?v=rB5YuC-maDA

2023-02-15 06:00 UTC, closed without merging