Add EKF3 feature for optflow fusion
ArduPilot/ardupilot pull request #22895
Opened 2023-02-10 08:14 UTC by peterbarker

This should automatically remove the EKF3 Optical fusion code based on the presence of OpticalFlow sensors.

The builds looks like this:
```
Board              AP_Periph  blimp   bootloader  copter  heli    iofirmware  plane   rover   sub
Durandal                      *       *           *       *                   *       *       *
Hitec-Airspeed     0                                                                          
KakuteH7-bdshot               *       *           *       *                   *       *       *
MatekF405                     -10392  *           -10384  -10392              -10384  -10336  -10392
Pixhawk1-1M                   *       *           *       *                   *       *       *
f103-QiotekPeriph  *                                                                          
f303-Universal     0                                                                          
iomcu                                                             *                           
revo-mini                     *       *           *       *                   *       *       *
skyviper-v2450                                    -10400                                      
```

I believe that means we should test-fly this on a board this is not included on a rangefinder attached (RangeFinder and OpticalFlow are intertwined a little in EKF3).  Should test with everybody's least favorite height source.

2023-02-10 13:56 UTC, khancyr approved these changes
nice one.
The issue on CI looks legit, but I didn't look yet why only one target failed ?

2023-02-10 23:34 UTC, peterbarker commented
> nice one. The issue on CI is right, you need to add this to AP_DAL too as this using some EKF functions!

Thanks, I've pushed a patch for the DAL up.

Interestingly I couldn't run the CI test which failed locally - even on master (`./Tools/scripts/build_ci.sh MatekF405-Wing`)

2023-02-17 10:20 UTC, khancyr approved these changes
OK for me. doesn't change behavoir.

2023-05-09 03:47 UTC, rmackay9 commented
From a casual review this looks good to me.

2023-05-11 05:19 UTC, peterbarker commented
I've built all branches and it all seems correct - boards without optflow save a bunch of bytes.

2023-05-11 05:23 UTC, peterbarker commented
I've flown this on a SkyViper without incident

2024-08-26 23:10 UTC, tridge requested changes

2024-08-26 23:10 UTC, tridge commented on libraries/AP_DAL/AP_DAL.cpp
> +#if EK3_FEATURE_OPTFLOW_FUSION
this would break flow on EKF2 or other estimators

2024-09-01 13:41 UTC, peterbarker commented
I've run this through the test-features build and fixed unrelated bugs in this PR now

2024-09-02 01:53 UTC, merged