Fix baud rate handling in AP_Winch_Daiwa
ArduPilot/ardupilot pull request #23084
Opened 2023-03-02 15:38 UTC by ohitstarik

Removed if statement forcing baud rate of 115200 to be consistent with documentation, and to avoid issues in future if manufacturer changes baud rate again. Correct baud rate is 38400. Documentation needs to be updated as well. 

Confirmed with manufacturer, and with a winch on v1.02. Also confirmed w/ manufacturer that newest winches on v1.04 also use 38400. 

From issue: https://discuss.ardupilot.org/t/daiwa-winch-not-working-prearm-winch-unhealthy-documentation-drivers-outdated-for-current-units/97532

2023-03-02 23:36 UTC, rmackay9 requested changes
@ohitstarik,

Ah, great.  This looks correct.  You've tested this of course?

One thing though, could you change the commit to be prefixed with "AP_Winch:"?  If you look at our other commits you'll see that we always prefix them with the subsystem being changed because this allows us to see at a glance what a commit affects which makes backporting easier.

2023-03-03 00:40 UTC, ohitstarik commented
for sure, i'm happy to learn how things are done around here. 

And yes, I tested with the winch we have. Tests and results are in the discuss.ardupilot link. 

I have to correct myself, from the newest email that i got it seems like the newest winches use 115200, although at this point I can't be entirely sure without testing myself. I think its still in our best interest to allow the "Serialx_baud" parameter to select the baud rate as there's a version of the unit that only works with 38400 baud rate. 

If we ever get the newest winches i'll get around to updating documentation to reflect my findings.

2023-03-03 01:05 UTC, magicrub approved these changes

2023-03-03 01:27 UTC, rmackay9 commented
@ohitstarik,

OK, we can merge once you've managed to update the commit.  It looks like you've updated the PR title.

2023-03-03 05:52 UTC, ohitstarik commented
@rmackay9 

Okay, that should've done it. Does this look right now?

2023-03-03 06:25 UTC, rmackay9 approved these changes
Yes, looking good now, thanks!

2023-03-03 20:38 UTC, peterbarker commented
> I guess we don't need a begin right? I see in some of our libraries we have a begin after the find and sometimes we don't.

You get one free `begin()` from AP_SerialManager based on the `SERIALn_` parameters.  I'm not a great fan of that - and I've played around with better patterns, as has Sid)

2023-03-03 22:59 UTC, merged

2023-03-03 22:59 UTC, rmackay9 commented
Merged, thanks!

It looks like the wiki already says that the SERIALx_BAUD should be set 115 even though that wouldn't have had any effect!

2023-03-03 23:01 UTC, rmackay9 commented
I've added "WikiNeeded" label because we need to update the [Daiwa Winch page](https://ardupilot.org/copter/docs/common-daiwa-winch.html) to specify that SERIALx_BAUD should be 115 or 38 depending upon the version of the winch (newer versions use 38 apparently).

2023-03-27 19:19 UTC, ohitstarik commented
Hey @rmackay9 , I've updated the wiki. Let me know if it works or if i need to make any changes.