AP_BatteryMonitor: add max of type
ArduPilot/ardupilot pull request #23082
Opened 2023-03-02 11:55 UTC by IamPete1

Adds a battery monitor that takes the max voltage from the remaining/mask of other monitors. 

Useful for diode or ideal diode setups where the max voltage is needed for voltage scaling of motors.

2023-03-02 19:35 UTC, IamPete1 commented
Yeah, a extra physical monitor would be better. If you can only have one or the other you need up stream of the diode so you can tell if one source has failed. In this case we had battery and a "none battery voltage source". 

I wasn't really sure what to do with current, we could sum current, or take the current associated with the max voltage battery. In the end I decided to just not do current and be a voltage only backend.

2023-03-02 22:44 UTC, IamPete1 commented on libraries/AP_BattMonitor/AP_BattMonitor_Sum.cpp
> +        _state.healthy = true;
Should probably set this to `got_voltage` outside the if.

2023-03-02 22:45 UTC, IamPete1 commented on libraries/AP_BattMonitor/AP_BattMonitor_Sum.cpp
> +        }
Could combine this into a shared helper for flash saving.

2023-03-06 23:44 UTC, tridge requested changes
should either be 2M with ifdef in AP_Batt*_config.h only or done via scripting

2023-03-06 23:45 UTC, closed without merging