Copter: Add Radio Failsafe Break option
ArduPilot/ardupilot pull request #23110
Opened 2023-03-06 08:53 UTC by lthall

This PR provides an option to change mode to Break Mode in the event of a Radio Failsafe. If GPS is not available a no-gps land is done.

This is required for some industrial operations where the aircraft is connected to tethers and carrying a load. In this case an RTL or payload release could both be dangerous. By changing to Break Mode the operators have the remaining battery capacity to solve the problem. This may be achieved by moving the pilot radio to a better line of sight position, moving to GCS controlled operations, or simply clearing the area of personnel and detaching or securing tethers.

2023-03-06 10:20 UTC, IamPete1 commented on ArduCopter/events.cpp
> +    set_mode_RTL_or_land_with_pause(reason);
```suggestion
    set_mode_land_with_pause(reason);
```

2023-03-06 10:24 UTC, IamPete1 commented
We do have a couple of issues in this direction. https://github.com/ArduPilot/ardupilot/issues/13101, https://github.com/ArduPilot/ardupilot/issues/20962, https://github.com/ArduPilot/ardupilot/issues/9409

2023-03-06 10:25 UTC, lthall commented on ArduCopter/events.cpp
> +    set_mode_RTL_or_land_with_pause(reason);
Opps, Thanks!!

2023-03-07 01:11 UTC, rmackay9 approved these changes

2023-03-07 01:12 UTC, rmackay9 requested changes
break should be brake

2023-03-07 01:15 UTC, peterbarker commented on ArduCopter/events.cpp
> +// Sets mode to Auto and jumps to DO_LAND_START, as set with AUTO_RTL param
Nope :-)

2023-03-07 01:17 UTC, CraigElder commented
Please update your spelling from Break to Brake

2023-03-07 01:22 UTC, bnsgeyer reviewed
I think I got them all

2023-03-07 01:22 UTC, bnsgeyer commented on ArduCopter/Copter.h
> +        BREAK_LAND         = 7
```suggestion
        BRAKE_LAND         = 7
```

2023-03-07 01:22 UTC, bnsgeyer commented on ArduCopter/Copter.h
> +    void set_mode_break_or_land_with_pause(ModeReason reason);
```suggestion
    void set_mode_brake_or_land_with_pause(ModeReason reason);
```

2023-03-07 01:22 UTC, bnsgeyer commented on ArduCopter/Parameters.cpp
> +    // @Values:  0:Disabled,1:Enabled always RTL,2:Enabled Continue with Mission in Auto Mode (Removed in 4.0+),3:Enabled always Land,4:Enabled always SmartRTL or RTL,5:Enabled always SmartRTL or Lan
```suggestion
    // @Values:  0:Disabled,1:Enabled always RTL,2:Enabled Continue with Mission in Auto Mode (Removed in 4.0+),3:Enabled always Land,4:Enabled always SmartRTL or RTL,5:Enabled always SmartRTL or Land,6:Enabled Auto DO_LAND_START or RTL,7:Enabled always Brake or Land
```

2023-03-07 01:22 UTC, bnsgeyer commented on ArduCopter/defines.h
> +#define FS_THR_ENABLED_BREAK_OR_LAND               7
```suggestion
#define FS_THR_ENABLED_BRAKE_OR_LAND               7
```

2023-03-07 01:22 UTC, bnsgeyer commented on ArduCopter/events.cpp
> +        case FS_THR_ENABLED_BREAK_OR_LAND:
```suggestion
        case FS_THR_ENABLED_BRAKE_OR_LAND:
```

2023-03-07 01:22 UTC, bnsgeyer commented on ArduCopter/events.cpp
> +            desired_action = FailsafeAction::BREAK_LAND;
```suggestion
            desired_action = FailsafeAction::BRAKE_LAND;
```

2023-03-07 01:22 UTC, bnsgeyer commented on ArduCopter/events.cpp
> +void Copter::set_mode_break_or_land_with_pause(ModeReason reason)
```suggestion
void Copter::set_mode_brake_or_land_with_pause(ModeReason reason)
```

2023-03-07 01:22 UTC, bnsgeyer commented on ArduCopter/events.cpp
> +        case FailsafeAction::BREAK_LAND:
```suggestion
        case FailsafeAction::BRAKE_LAND:
```

2023-03-07 01:22 UTC, bnsgeyer commented on ArduCopter/events.cpp
> +            set_mode_break_or_land_with_pause(reason);
```suggestion
            set_mode_brake_or_land_with_pause(reason);
```

2023-03-07 02:52 UTC, rmackay9 approved these changes

2023-03-07 11:13 UTC, IamPete1 approved these changes

2023-03-08 22:25 UTC, merged