HAL_ChibiOS: fix a memory corruption bug on STM32H757
ArduPilot/ardupilot pull request #23228
Opened 2023-03-16 02:05 UTC by tridge

this fixes an issue where a variable in SRAM1 gets set to a bad value when we reset AHB1 with the top bit (a reserved bit)

the bug was only reproducible with this particular commit:

https://github.com/tridge/ardupilot/commits/cubeorangplus-crash-boot-bisect

but likely is just luck that it triggered on that commit. In this instance it triggered as AP_OSD::singleton was reset to non-nullptr, causing a panic() in AP_OSD::AP_OSD()

compiler was gcc 10.2-2020-q4

2023-03-16 02:16 UTC, peterbarker approved these changes

2023-03-16 07:51 UTC, andyp1per commented
I think we should fix this in ChibiOS. Will be pretty easy to get it into the new branch

2023-03-16 08:15 UTC, andyp1per requested changes
We should do this: https://github.com/ArduPilot/ChibiOS.svn/pull/2/commits/16cfb7be92973f31ad15e1e841f108d9a1bd93c7

2023-03-17 21:35 UTC, merged

2023-03-17 21:37 UTC, tridge commented
> We should do this: [ArduPilot/ChibiOS.svn@16cfb7b](https://github.com/ArduPilot/ChibiOS.svn/commit/16cfb7be92973f31ad15e1e841f108d9a1bd93c7)

I've merged the change in this PR as it is the smaller change - we don't know what the other bits do. I agree your PR matches the reference manual, but I want something for 4.4.x now, and make the smallest possible change. I did it in the ArduPilot repo to make it easier to backport

2023-05-24 00:23 UTC, rmackay9 commented
Tridge and I discussed this and came to the tentative conclusion that this is not a common enough issue to warrant backporting to 4.3.7 at least.