Add support for new fields in MISSION_CURRENT message
ArduPilot/ardupilot pull request #23230
Opened 2023-03-16 07:09 UTC by peterbarker

- mission state (useful for "complete")
 - number of commands
 

@auturgy this might be problematic in that I've implemented the spec as-written which is the number of commands - but we consider the home location a command, so your current squence number is never going to equal this new "total" field.

2023-03-16 07:22 UTC, auturgy commented
The waypoint 0 / home thing is a little problematic (in this context: mostly it is actually good to have it as a waypoint). I've been thinking about whether it's worth burning a capability bit on that issue, to support both styles of reporting/recording home.

2023-03-16 08:41 UTC, peterbarker commented
> The waypoint 0 / home thing is a little problematic (in this context: mostly it is actually good to have it as a waypoint). I've been thinking about whether it's worth burning a capability bit on that issue, to support both styles of reporting/recording home.

I'd like to transition away from having the home location as a waypoint :-)  But, separate issue.

I think if we can change the wording on this message to "maximum expected waypoint number" rather than "total number of mission items" (regardless of the name), we can just send the highest sequence number in this packet.

2023-03-16 17:24 UTC, magicrub commented
And here's the PR for the mavlink change https://github.com/ArduPilot/mavlink/pull/271

2023-03-16 21:33 UTC, peterbarker commented
Oh, @hamishwillee on that total-number-of-waypoints thing.

2023-03-16 21:55 UTC, peterbarker commented
> And here's the PR for the mavlink change [ArduPilot/mavlink#271](https://github.com/ArduPilot/mavlink/pull/271)

More likely this one: https://github.com/ArduPilot/mavlink/pull/306 :-)

2023-04-19 06:58 UTC, peterbarker commented
I've adjusted this PR on the assumption that we'll change the wording on the mavlink message to exclude the home point from "total".

I've also allowed Copter to say it is paused when it is.

2023-04-19 08:12 UTC, tridge requested changes
ok to merge once in_auto fixed

2023-04-19 08:12 UTC, tridge commented on libraries/GCS_MAVLink/GCS_Common.cpp
> +        0); // mission_mode (0 means unknown, need vehicle callback for this)
could fill this in? current_mode_requires_mission()

2023-04-19 22:59 UTC, hamishwillee commented
I've added note to the upstream mavlink correction. In essence, yes - on the last mission item `sequence === total`. 

My bad - while I know that ardupilot keeps home location is the 0 position I don't think of it as a mission item. Any objection to me merging that update (or my slight proposed amendment)?

2023-04-20 05:45 UTC, peterbarker commented
I've merged the associated mavlink change after updating it from mavlink/mavlink.

I've added setting of the mode field based on whether the vehicle is in a mode which requires the mission (pre-existing method to do that for AP_Arming).

2023-04-20 23:49 UTC, merged