Add SpeedyBeeF405WING
ArduPilot/ardupilot pull request #23428
Opened 2023-04-07 13:15 UTC by Hwurzburg

2023-04-07 19:52 UTC, andyp1per requested changes
The pin mapping on this is essentially the same as the regular speedybee F405, you should base the config on that, otherwise its just more maintenance

2023-04-07 21:28 UTC, Hwurzburg commented
> The pin mapping on this is essentially the same as the regular speedybee F405, you should base the config on that, otherwise its just more maintenance

sorry I disagree....just going thru side by side, and only thru the first half of the file, over 50% of the pins are different....I gave up trying to list the differences at that point...

2023-04-08 07:49 UTC, andyp1per commented
Ok if that's the case then what you have done makes sense

2023-04-11 00:15 UTC, tridge approved these changes

2023-04-11 00:22 UTC, tridge approved these changes

2023-04-11 00:22 UTC, merged