AP_DroneCAN: add lenght specifier to format print to keep  g++ 7.5.0 happy
ArduPilot/ardupilot pull request #23494
Opened 2023-04-14 23:42 UTC by IamPete1

Fixes:
```
../../libraries/AP_DroneCAN/AP_DroneCAN.cpp:190:6: error: ‘%u’ directive output may be truncated writing between 1 and 10 bytes into a region of size 4 [-Werror=format-truncation=]
```
Related to:
```
snprintf(_thread_name, sizeof(_thread_name), "dronecan_%u", driver_index);
```

Problem seems semi genuine, `_thread_name` is only 13 characters long `dronecan_` takes up 9 so the warning is that were trying to print a uint32 with `u` but only have 4 characters left. The fix is to add the length specifier `hh` so the compiler knows its a uint8 not a uint32. 

I guess newer compilers are clever enough to know its a uint8 from inspection of the variable rather than only the format string. 

In any case this means I don't have to update my compiler to build SITL.

2023-04-15 21:08 UTC, magicrub commented
This is a better solution than https://github.com/ArduPilot/ardupilot/pull/23492 because it's addressing the problem instead of just handling an error which will never happen, at the cost of flash.

That said the array is still already 2 chars too long. A better way to change *ALL* the ways to do this is to just allocate it instead of pre-define a hopefully-long-enough array size.

2023-04-18 01:08 UTC, tridge requested changes

2023-04-18 01:08 UTC, tridge commented on libraries/AP_DroneCAN/AP_DroneCAN.cpp
> +    snprintf(_thread_name, sizeof(_thread_name), "dronecan_%hhu", driver_index);
need to use hal.util->snprintf() and use %01u, and test

2023-04-18 01:14 UTC, tridge approved these changes

2023-04-18 16:44 UTC, merged