AP_Periph: add node locate function
ArduPilot/ardupilot pull request #23503
Opened 2023-04-15 08:01 UTC by mirkix

This add a new function to AP_Periph. If a heartbeat LED is defined, a new DroneCAN parameter `locate` will appear. When set `locate` to 1 the heartbeat LED starts flashing rapidly. This can be used to locate the node in your hardware setup if you have more than one DroneCan node in your setup.

2023-04-17 17:16 UTC, MallikarjunSE commented
> This add a new function to AP_Periph. If a heartbeat LED is defined, a new DroneCAN parameter `locate` will appear. When set `locate` to 1 the heartbeat LED starts flashing rapidly. This can be used to locate the node in your hardware setup if you have more than one DroneCan nodes in your setup.

I think different pattern would be nice since fast blinking indicates bootloader. Probably like double blink with pause.

2023-12-31 15:14 UTC, magicrub commented
I definitely lent the idea, but I agree with @mirkix . It needs to not look like the bootloader. Also, might be nice to have a dedicated LED option too.

2024-01-02 00:41 UTC, tridge requested changes

2024-01-02 00:41 UTC, tridge commented on Tools/AP_Periph/Parameters.cpp
> +#ifdef HAL_GPIO_PIN_LED
this adds a LOCATE param to every peripheral, I think users would find it confusing as to why their GPS has a LOCATE param
please use a DEBUG bit to change the existing LED flashing code to flash at a high rate

2025-04-21 11:47 UTC, closed without merging