Add convenient Quaternion::to_euler(Vector3f &rpy)
ArduPilot/ardupilot pull request #23514
Opened 2023-04-16 00:57 UTC by peterbarker

This isn't an exhaustive list of changes to the calls - there's quite a few more in the EKFs, for example.

(also adds the double equivalent)

```
Board               AP_Periph  blimp  bootloader  copter  heli  iofirmware  plane  rover  sub
Durandal                       0      *           8       0                 8      8      8
HerePro             0                                                                     
Hitec-Airspeed      *                                                                     
KakuteH7-bdshot                0      *           -80     -80               -80    0      -80
MatekF405                      8      *           -72     -80               -80    0      -80
Pixhawk1-1M-bdshot             *                  -80     -80               -80    *      -80
f103-QiotekPeriph   *                                                                     
f303-Universal      *                                                                     
iomcu                                                           *                         
revo-mini                      8      *           -80     -80               -80    8      -80
skyviper-v2450                                    -80                                     
```

2023-04-17 00:02 UTC, rmackay9 approved these changes

2023-04-18 01:38 UTC, tridge requested changes

2023-04-18 01:38 UTC, tridge commented on libraries/AP_Math/quaternion.h
> +        to_euler(rpy[0], rpy[1], rpy[2]);
should be the x,y,z

2023-04-18 01:38 UTC, tridge commented on libraries/AP_Math/quaternion.h
> +        to_euler(rpy[0], rpy[1], rpy[2]);
should be x,y,z

2023-04-18 02:37 UTC, peterbarker commented on libraries/AP_Math/quaternion.h
> +        to_euler(rpy[0], rpy[1], rpy[2]);
Done.

Code is zero-size-change

2023-04-18 02:37 UTC, peterbarker commented on libraries/AP_Math/quaternion.h
> +        to_euler(rpy[0], rpy[1], rpy[2]);
Done

2023-04-19 04:24 UTC, merged

2023-04-19 04:24 UTC, peterbarker commented
Merged as agreed at call.