AP_Arming: Determine the channel's MIN and MAX values as intermediate values
ArduPilot/ardupilot pull request #23552
Opened 2023-04-19 23:13 UTC by muramura

Add a judgment that the width of the channel is above and below 200 PWM with intermediate values plus and minus.
This is because there is a process to determine at 1300 and 1700.
The risk of accidents is high if the calibration is performed in a bullshit manner.

2023-04-19 23:21 UTC, amilcarlucas requested changes

2023-04-19 23:21 UTC, amilcarlucas commented on libraries/AP_Arming/AP_Arming.cpp
> +            check_failed(ARMING_CHECK_RC, report, "RC%d_MIN is greater than %d %d", i + 1, center);
Three %d but only two integer arguments. This variadic function call is missing an argument

2023-04-19 23:23 UTC, WickedShell requested changes
I don't understand what you are trying to check here. As far as I can see this would reject very valid configs like min 1500, max 2000.

Even past that you have to realize that using PPM with MP results in unused channels having a channel with min/max range of 1-2 us. Just because of signal jitter.

2023-04-19 23:23 UTC, WickedShell commented on libraries/AP_Arming/AP_Arming.cpp
> +        if (c->get_radio_max() < center) {
This is impossible to get to unless radio_min is 0 or 1.

2024-09-11 12:28 UTC, closed without merging

2024-09-11 12:28 UTC, peterbarker commented
Sorry, this can't ever have been tested to meet the stated goals, and @WickedShell has pointed out several problems.

Closing this now.  Remember we can't catch *everything* the user can do to themselves in ArduPilot - we'll stop compiling due to flash space limits!