AP_BattMonitor: Addition of AD7091R5 ADC I2C Read Driver
ArduPilot/ardupilot pull request #23564
Opened 2023-04-21 02:50 UTC by Lokesh-Carbonix

This is an ADC extender based on I2C which is used to read the current and voltage. This is disabled by default and need to be enabled in hwdef.

2023-04-21 02:57 UTC, tridge requested changes
looks good, just very minor issues

2023-04-21 10:23 UTC, IamPete1 requested changes
All the battery monitor backend param tables share indexes, so we have to be cairfull we don't conflict with a index in another file. We may need to rework the reserved ranges a little to fit these in. 

Need to point at the new param table here like the other examples:

https://github.com/ArduPilot/ardupilot/blob/0573a86fcf8185bfdf989fcd9631d85295efd959/libraries/AP_BattMonitor/AP_BattMonitor.cpp#L58-L59

2023-04-21 10:23 UTC, IamPete1 commented on libraries/AP_BattMonitor/AP_BattMonitor_AD7091R5.cpp
> +    AP_GROUPINFO("VOLT_PIN", 30, AP_BattMonitor_AD7091R5, _volt_pin, 0),
30 to 39 are reserved for the DroneCAN monitor. Looks like you would have to start at 56.

2023-04-21 10:23 UTC, IamPete1 commented on libraries/AP_BattMonitor/AP_BattMonitor_AD7091R5.cpp
> +    // Param indexes must be less than 10 to avoid conflict with other battery monitor param tables loaded by pointer
```suggestion
    // Param indexes must be between 56 and 61 to avoid conflict with other battery monitor param tables loaded by pointer
```

2023-04-21 23:27 UTC, Lokesh-Carbonix commented on libraries/AP_BattMonitor/AP_BattMonitor_AD7091R5.cpp
> +    // Param indexes must be less than 10 to avoid conflict with other battery monitor param tables loaded by pointer
Thanks, done

2023-04-24 00:21 UTC, Lokesh-Carbonix commented
@tridge  made the changes requested

2023-10-23 01:09 UTC, Jono453 commented
@tridge @IamPete1 are there any others changes requested at the moment for adding the AD7091R5 driver into BattMonitor?

2023-10-23 03:59 UTC, Jono453 commented
please disregard latest commit - made an error.

2023-10-31 02:47 UTC, Jono453 commented
Hi. Checking whether any other changes need to be made to this PR? Have tested it on our hardware and working correctly. Thanks

2023-11-08 05:45 UTC, tridge approved these changes

2023-11-08 07:24 UTC, merged

2023-11-08 13:31 UTC, Hwurzburg commented
@tridge @peterbarker  shouldn't this have entries in custom build server and feature list?