AP_HAL_CHIBIOS: move serial params from defaults to hwdef
ArduPilot/ardupilot pull request #23593
Opened 2023-04-24 18:13 UTC by Hwurzburg

2023-04-24 19:27 UTC, magicrub commented
I guess there's a define missing?
```
../../libraries/AP_SerialManager/AP_SerialManager.cpp:68:22: error: 'HAL_SERIAL6_BAUD' was not declared in this scope; did you mean 'HAL_SERIAL5_BAUD'?
   68 | #define SERIAL6_BAUD HAL_SERIAL6_BAUD
```

2023-04-24 20:13 UTC, Hwurzburg commented
the size CI does not include these boards...the size will grow for each character for each of these, since the text is stored in ROMFS for the hwdef now....but getting rid of the defaults.parm can eventually save 1K on 1MB boards and 8K on 2MB boards since we can get rid of the APJ reserved space for this...that is why we are moving things back into hwdef.dat

2023-04-24 21:04 UTC, Hwurzburg commented
@andypiper you might want to look this over for your boards....many boards inherited the serial protocols and adding them to their derivative hwdef was not needed.....

2023-04-25 10:36 UTC, andyp1per requested changes
Just one problem I found

2023-04-25 10:36 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/KakuteH7/hwdef.dat
Missing SERIAL7 protocol 16

2023-04-25 17:06 UTC, andyp1per approved these changes

2023-04-25 18:54 UTC, Hwurzburg commented
thanks...but still wip...have to change the hwdef names...after my SerialManage normalization PR gets in...that will allow move the serial options and make the bauds actually work...

2023-06-19 10:33 UTC, peterbarker commented
That's a lot of conflicts, @Hwurzburg !

2023-06-19 12:12 UTC, Hwurzburg commented
Yep....may eventually get around to working on this again...

2023-08-09 18:29 UTC, closed without merging