Add EchoPilot AI board id
ArduPilot/ardupilot pull request #23653
Opened 2023-05-01 14:20 UTC by climr

2023-11-09 20:17 UTC, tridge approved these changes

2023-11-09 20:43 UTC, tridge requested changes
sorry, you will need to change your board ID. We were negligent in not merging this earlier.

2023-11-09 20:43 UTC, tridge commented on Tools/AP_Bootloader/board_types.txt
> +AP_HW_EchoPilotAI                    1404
apologies, this is failing CI with:
  ValueError: Duplicate ID 1404 in file for (AP_HW_EchoPilotAI) and (AP_HW_VIMDRONES_FLOW)

2023-11-09 20:43 UTC, Hwurzburg requested changes

2023-11-09 20:43 UTC, Hwurzburg commented on Tools/AP_Bootloader/board_types.txt
> +AP_HW_EchoPilotAI                    1404
try 1408

2023-11-10 00:38 UTC, rmackay9 commented
It would be good to also modify the commit message to start with "Tools:" or "Bootloader:".  To be clear, I meant the commit message, no the PR title.

2024-04-11 03:07 UTC, peterbarker commented
@climr please open a fresh pull request if you still want to reserve a board ID.  We'll try to be a bit more diligent next time!

2024-04-11 03:07 UTC, closed without merging