AP_Compass: remove CAN auto replacement
ArduPilot/ardupilot pull request #23706
Opened 2023-05-06 16:32 UTC by IamPete1

Currently if you have multiple CAN compasses but only use and calibrate the first if that compass ever does not show up at boot it will be replaced by the second. This removes that ability so compasses cannot change ordering unexpectedly. This can happen if the flight controller is powered from USB and the primary compass from battery. 

Because the second compass had not been calibrated its dev-id is never saved, this means the `expected_dev_id` is 0 and it is detected as a replacement compass. 

This can be avoided by setting all to use and calibrating all and then deselecting use for the unwanted compasses.

A alternate solution would be to save all dev-id's in a calibration to "lock" the ordering, however we would then also need to force offsets to 0 for the un-calibrated compasses so they still show up as un-calibrated. 

TLDR: You have to got to a GCS to calibrate the new compass that has come in as a replacement anyway, I don't see that manually removing the old one and moving the new one up is significantly more effort.

2023-05-06 17:06 UTC, pompecukor commented
@IamPete1 Thank you for not giving up on this so easily. From you explanation, now I understand why you first found our problem hard to replicate. It need the other compasses not to be calibrated previously at all. Makes sense.

2023-05-09 01:17 UTC, tridge commented
@bugobliterator can you have a look like this?

2023-05-24 08:52 UTC, tridge requested changes

2023-05-24 08:52 UTC, tridge commented on libraries/AP_Compass/AP_Compass.cpp
> -#if COMPASS_MAX_UNREG_DEV > 0
I think a COMPASS_OPTIONS bit, maybe "DisableDroneCANReplacement" which can be set on vehicles where the GPS/compass combos are powered separately from the main flight control MCU

2023-06-18 17:53 UTC, IamPete1 commented
I have done some more playing about, QGC does not allow you to remove missing compasses. On this patch starting a calibration does not clear any missing compasses. So we cannot remove this code without requiring users who genuinely need to remove a mission compass to use mission planner.

I'm still of the view that this is strange and un-expected behavior. I suspect reports are going to become more common, especially with new devices, such as this, https://holybro.com/collections/flight-controller-accessories/products/can-hub

I'm happy to make this a parameter, but I don't think current behavior should be the default. Much better to cause a little extra effort to those who are replacing a compass than to cause compasses to disappear and calibrations to be lost for those who are operating normally.

2023-06-18 18:27 UTC, IamPete1 commented
I have added a compass option which defaults to not do auto replacement.

2023-06-26 23:23 UTC, tridge approved these changes

2023-06-26 23:24 UTC, rmackay9 approved these changes
We're worried about support load but we're going to give it a try.

2023-06-26 23:24 UTC, tridge commented
approved with some trepidation

2023-06-26 23:24 UTC, merged