Fix the issue of ST24 receiver not working
ArduPilot/ardupilot pull request #23742
Opened 2023-05-10 11:11 UTC by lipper-chengdu

Fix the issue of ST24 receiver not working

2023-05-10 11:14 UTC, peterbarker commented
> Fix the issue of ST24 receiver not working

Wow.  On the face of it you're fixing an absolutely terrible bug.  Did you have a look to see how the bug got there?!

2023-05-10 11:15 UTC, peterbarker requested changes
Commit will need a message of: `AP_RCProtocol: Fix the issue of ST24 receiver not working"

Let me know if you're going to have trouble changing the commit message.

2023-05-10 11:16 UTC, peterbarker commented
@lipper-chengdu suggest you not commit to your master branch.  See https://ardupilot.org/dev/docs/git-branch.html#creating-a-branch - always use a "topic" branch.

2023-05-10 11:27 UTC, lipper-chengdu commented
> @lipper-chengdu suggest you not commit to your master branch. See https://ardupilot.org/dev/docs/git-branch.html#creating-a-branch - always use a "topic" branch.

I have modified the PR name. Do I need to submit the PR again using a branch?

2023-05-10 11:34 UTC, lipper-chengdu commented on libraries/AP_RCProtocol/AP_RCProtocol_ST24.cpp
> +                add_input(num_values, values, false);
AP_RCProtocol: Fix the issue of ST24 receiver not working

2023-05-10 11:58 UTC, peterbarker commented
> > @lipper-chengdu suggest you not commit to your master branch. See https://ardupilot.org/dev/docs/git-branch.html#creating-a-branch - always use a "topic" branch.
> 
> I have modified the PR name. Do I need to submit the PR again using a branch?

The PR name is not the problem - it's the commit:
![image](https://github.com/ArduPilot/ardupilot/assets/7077857/f7b174e2-5973-4501-8339-877e111e1020)

You do not need to re-submit using a branch - but the problem is that it's tough for you to use your git tree for anything else until this one gets merged!

2023-05-10 12:44 UTC, lipper-chengdu commented
> > > @lipper-chengdu suggest you not commit to your master branch. See https://ardupilot.org/dev/docs/git-branch.html#creating-a-branch - always use a "topic" branch.
> > 
> > 
> > I have modified the PR name. Do I need to submit the PR again using a branch?
> 
> The PR name is not the problem - it's the commit: ![image](https://user-images.githubusercontent.com/7077857/237382962-f7b174e2-5973-4501-8339-877e111e1020.png)
> 
> You do not need to re-submit using a branch - but the problem is that it's tough for you to use your git tree for anything else until this one gets merged!

Oh, I understand. Thank you very much

2023-05-11 04:19 UTC, peterbarker commented
@lipper-chengdu I've taken the liberty of folding the commits and adjusting the commit message here.

This is now well-formed for merging into ArduPilot.

2023-05-11 04:33 UTC, lipper-chengdu commented
I am not familiar with using the tool and will try resubmitting it.

> @lipper-chengdu I've taken the liberty of folding the commits and adjusting the commit message here.
> 
> This is now well-formed for merging into ArduPilot.

Thank you, by the way https://github.com/ArduPilot/ardupilot/tree/master/Tools/IO_Firmware Will the files in the directory be automatically updated? Because the modification of AP_RCProtocol_ST24.cpp file needs to regenerate these files.

2023-05-16 00:06 UTC, tridge commented
@lipper-chengdu it would be great to get ST24 tested in our test harness:
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_RCProtocol/examples/RCProtocolTest/RCProtocolTest.cpp#L343
we need some captured serial bytes for the test harness. Can you get those?

2023-05-16 00:07 UTC, peterbarker approved these changes

2023-05-16 02:06 UTC, lipper-chengdu commented
> @lipper-chengdu it would be great to get ST24 tested in our test harness: https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_RCProtocol/examples/RCProtocolTest/RCProtocolTest.cpp#L343 we need some captured serial bytes for the test harness. Can you get those?
RC->FC
55 55 18 00 00 00 C4 00 00 08 00 80 08 00 80 08 00 80 08 00 80 08 00 2A 62 A6 7D //SR12
55 55 18 00 00 00 C1 00 00 08 00 80 08 00 80 08 00 80 08 00 80 08 00 2A 62 A6 E1 //SR12
55 55 2B 03 00 00 C1 00 00 08 00 80 08 00 80 08 00 80 08 00 80 08 00 2A 62 A6 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 5F//GPS.NO USE
FC->RC
55550804000042494E44B05A//BIND
55552602757800000000000000000000000000000000FFFF104000EEFFB7FFDE91FFFF110000000006//TelemetryData

I am trying to support the data retrieval function of ST24

2023-05-16 03:05 UTC, lipper-chengdu commented
@peterbarker

Did I click the wrong button again? There's an extra committee

2023-05-16 23:42 UTC, peterbarker commented
> @peterbarker
> 
> Did I click the wrong button again? There's an extra committee

Yep - need to rebase on master, not add a merge commit for it.  I've hit the rebase button again now so we can merge this one CI has passed.

2023-05-17 22:24 UTC, merged

2023-05-17 22:24 UTC, peterbarker commented
Merged, thanks!