Copter: Explicitly state that variable values are not to be used
ArduPilot/ardupilot pull request #23845
Opened 2023-05-21 11:18 UTC by muramura

Explicitly state that the variable is not used by the referent.
Essentially, the created variable is used.
The area of this variable is used by the referenced method.
Since this is different from the basic use, it is clarified in the comment.

2023-05-21 23:01 UTC, rmackay9 approved these changes

2023-05-22 01:40 UTC, peterbarker requested changes

2023-05-22 01:40 UTC, peterbarker commented on ArduCopter/takeoff.cpp
> +        Vector2f vel, accel;  // defined but not used in this scope
This comment is misleading.

We may not be using these methods in those scope, but their value - implicitly zero - is absolutely critical.  This is telling the position controller to set its input velocity acceleration to zero.  The fact we don't use vel and accel elsewhere in this scope is besides the point - they are *input values* to the method we are calling!

2023-05-22 02:36 UTC, rmackay9 commented
OK, well,  I think I'll go ahead and close this PR then.

2023-05-22 02:36 UTC, closed without merging