SITL: Value Semantics for TOW calc
ArduPilot/ardupilot pull request #23857
Opened 2023-05-23 04:32 UTC by Ryanf55

Change to use value sematics because then you can use const-return value. 

Now, the time is captured in a documented struct which makes it clearer too.

2023-05-23 04:37 UTC, peterbarker requested changes
`tow` is the nomenclature given to this pair of values.

`time` is kind of redundant within the structure.

2023-05-23 04:37 UTC, peterbarker commented on libraries/SITL/SIM_GPS.cpp
> +struct GPS_TimeWeek {
```suggestion
struct GPS_TOW {
```

2023-05-23 04:37 UTC, peterbarker commented on libraries/SITL/SIM_GPS.cpp
> +    uint16_t time_week;
```suggestion
    uint16_t week;
```

2023-05-23 04:37 UTC, peterbarker commented on libraries/SITL/SIM_GPS.cpp
> +    uint32_t time_week_ms;
```suggestion
    uint32_t ms;
```

2023-05-23 04:37 UTC, peterbarker commented on libraries/SITL/SIM_GPS.cpp
> +static GPS_TimeWeek gps_time()
```suggestion
static GPS_TOW gps_time()
```

2023-05-23 04:37 UTC, peterbarker commented on libraries/SITL/SIM_GPS.cpp
> +    const auto gps_weektime = gps_time();
```suggestion
    const auto gps_tow = gps_time();
```

2023-05-23 04:37 UTC, peterbarker commented on libraries/SITL/SIM_GPS.cpp
> +    pos.time = gps_weektime.time_week_ms;
```suggestion
    pos.time = gps_tow.ms;
```

etc

2023-05-23 04:37 UTC, peterbarker commented on libraries/SITL/SIM_GPS.cpp
> +    sol.week = gps_weektime.time_week;
```suggestion
    sol.week = gps_tow.week;
```

2023-05-23 04:44 UTC, Ryanf55 commented
> `tow` is the nomenclature given to this pair of values.
> 
> `time` is kind of redundant within the structure.

Done!

2023-05-24 05:32 UTC, Ryanf55 commented
Hi @peterbarker - friendly ping. Any further requests, or you happy to approve?

2023-05-31 05:01 UTC, peterbarker approved these changes
Much nicer :-)

2023-05-31 05:01 UTC, merged

2023-05-31 05:01 UTC, peterbarker commented
Merged, thanks!