Feature/ap_olc
ArduPilot/ardupilot pull request #23879
Opened 2023-05-24 15:45 UTC by khancyr

Use more static variable and AP_OLC 

cannot use constexpr for log and pow as Clang don't allow it as it is gcc extension.

add unit tests

2023-09-27 09:01 UTC, tridge requested changes

2023-10-03 07:07 UTC, khancyr commented on libraries/AP_OLC/AP_OLC.cpp
> +const int32_t AP_OLC::INITIAL_EXPONENT = floor(log(2 * (LON_MAX / OLC_DEG_MULTIPLIER)) / log(ENCODING_BASE));
reverted to float version

2023-10-03 07:10 UTC, khancyr commented on libraries/AP_OLC/AP_OLC.cpp
> +const int32_t AP_OLC::INITIAL_EXPONENT = floor(log(2 * (LON_MAX / OLC_DEG_MULTIPLIER)) / log(ENCODING_BASE));
doesn't matter in this case as the gcc extension make them constexpr and we have compile time calculation

2023-10-04 08:00 UTC, tridge approved these changes

2023-10-04 08:00 UTC, merged