AP_HAL_ChibiOS: minimize speedybeef, VRUbrain-v51 and MatekF405-TE
ArduPilot/ardupilot pull request #23887
Opened 2023-05-25 02:07 UTC by peterbarker

out of space for everything, or close to it

some reordering required to keep OSD and synthetic-current definitions happy.

2023-05-25 06:43 UTC, andyp1per commented
These boards are quite popular at the low end and we have just removed a ton of features with this PR. Any idea what is the root cause? I think we will get a lot of complaints and support questions.

2023-05-26 05:05 UTC, davidbuzz commented
would include/save_some_flash.inc  be a slightly less aggressive choice that helped ?

2023-05-29 00:06 UTC, peterbarker commented
> would include/save_some_flash.inc be a slightly less aggressive choice that helped ?

I authored that, and I'd rather not use it.

We have `minimal_GPS.inc`, `minimal_Airspeed.inc`, `minimal.inc`, `minimize_features.inc` and `save_some_features.inc`, all of which you include to try to get things to fit.  I'd really rather have *just* `minimize_features.inc`  As well as *many*, *many* boards doing their own bespoke include sets.

I don't have any interest in micro-managing every board.  It's time consuming and I don't find it particularly rewarding.

Micro-managing each board also makes for a difficult user story - try to explain to someone what's available on any particular board and you will struggle to do that.  Which is one of the reasons @Hwurzburg and I created this page, which is generated from master's features.txt files: https://ardupilot.org/copter/docs/binary-features.html#feature-beasth7 (@Hwurzburg I wonder if we should link to the custom build server from that page - "if you require one of the omitted features on your board then you can use the _link_to_custom_build_server")

2023-05-30 00:09 UTC, tridge commented
@andyp1per moved to EU dev call to allow you to comment

2023-05-30 00:11 UTC, tridge commented
we could potentially drop the ROMFS bootloader for the boards that have a DFU button

2023-05-30 00:15 UTC, hendjoshsr71 commented
We could create a minimize_features_fpv.inc ?  Many of these boards are fpv focused from the Betaflight community. So the normal minimize features of removing crsf, smart audio,  tramp, or osd is not good.

2023-05-30 06:08 UTC, Hwurzburg commented
@peterbarker added note/link re custom build server

2023-05-31 01:33 UTC, peterbarker commented
> @peterbarker added note/link re custom build server

Thanks Henry!

2023-05-31 02:49 UTC, peterbarker commented
> We could create a minimize_features_fpv.inc ? Many of these boards are fpv focused from the Betaflight community. So the normal minimize features of removing crsf, smart audio, tramp, or osd is not good.

I don't want to be micro-managing these boards.

Fair point on removing crsf etc from these boards, however.  I've changed this to include save_some_flash.inc on some boards, minimal.inc on others and just minimising VRUbrainv51 - as it was already both of those!

2023-05-31 07:30 UTC, andyp1per requested changes
Please use https://github.com/ArduPilot/ardupilot/pull/23935 for speedybee f4

2023-05-31 07:45 UTC, tridge commented
merge with VRBrain change only, @andyp1per or I will do bootloader ROMfs saving with 
```
define AP_BOOTLOADER_FLASHING_ENABLED = 0 
```

2023-06-01 01:37 UTC, merged