Pixhawk1-bdshot
ArduPilot/ardupilot pull request #23962
Opened 2023-06-03 15:25 UTC by andyp1per

2023-06-06 00:23 UTC, tridge requested changes

2023-06-06 00:23 UTC, tridge commented on libraries/AP_HAL_ChibiOS/hwdef/Pixhawk1-bdshot/hwdef.dat
> +include ../fmuv3-bdshot/hwdef.dat
why not derive from Pixhawk1?

2023-06-06 00:23 UTC, tridge approved these changes

2023-06-06 00:24 UTC, merged

2023-07-03 08:00 UTC, rmackay9 commented
this is included in Copter-4.4.0-beta3