Copter: The initial value of the ESC calibration specification is DISABLED
ArduPilot/ardupilot pull request #24065
Opened 2023-06-14 19:52 UTC by muramura

I believe ESC calibration is performed only during aircraft adjustment and maintenance.
Normally, it should be disabled.
In fact, a poor contact of the battery connector caused an ESC calibration condition.
The ESC was set to an incorrect value and the aircraft was damaged.
I would like to change the default value to DISABLED, so that the value is changed consciously.

I think this change will have the effect of increasing safety.

2023-06-15 00:15 UTC, Hwurzburg commented
this change would not have prevented the issue you state is the reason for the change...but I think it is a good change, nonetheless

2023-06-15 00:47 UTC, rmackay9 approved these changes

2023-06-15 06:43 UTC, IamPete1 requested changes
Also need to put it back to disabled after a calibration. https://github.com/ArduPilot/ardupilot/blob/251eb10cfa37e1c75096aff6c486a6e4ddd76e83/ArduCopter/esc_calibration.cpp#L72

2023-06-15 06:43 UTC, IamPete1 commented on ArduCopter/Parameters.cpp
> +    GSCALAR(esc_calibrate, "ESC_CALIBRATION",       9),
Better to use the enum

2023-06-25 08:31 UTC, muramura commented on ArduCopter/Parameters.cpp
> +    GSCALAR(esc_calibrate, "ESC_CALIBRATION",       9),
I have modified the ENUM definition.

2024-07-25 02:29 UTC, peterbarker commented on ArduCopter/Parameters.cpp
> +    GSCALAR(esc_calibrate, "ESC_CALIBRATION",       9),
Where?  I can't see that patch in here.

2025-04-30 04:51 UTC, peterbarker commented
No response from author, closing this one.  Re-open if you want to progress.

2025-04-30 04:51 UTC, closed without merging