AP_Scripting: add binding to block MAVLink commands
ArduPilot/ardupilot pull request #24091
Opened 2023-06-18 13:02 UTC by IamPete1

This adds the ability for scripting to block MAVLink commands, this means we can process a command long or int in the script without AP acking unsupported, or override the default behavior of commands (or just block commands all together).

This also does a little re-work to the existing MAVLink bindings so they work like the rest, from `mavlink.receive_chan` to `mavlink:receive_chan`. This is a breaking change, we could support both as we do for logger, but they have not been in that long.

This also changes the uint32 receive timestamp to return as a uint32 rather than a native int and fixes up the docs. 

I have added a example of receive a user command.

This does bring some generated code into tree for the new example.

2023-06-20 00:53 UTC, peterbarker requested changes

2023-06-20 00:53 UTC, peterbarker commented on libraries/GCS_MAVLink/GCS_Common.cpp
> +    if (scripting != nullptr && scripting->blocking_command(packet.command)) {
```suggestion
    if (scripting != nullptr && scripting->is_handling_command(packet.command)) {
```

2023-06-20 01:06 UTC, tridge requested changes

2023-06-20 01:06 UTC, tridge commented on libraries/AP_Scripting/AP_Scripting.cpp
> +        while (mavlink_command_block_list != nullptr) {
i think we need WITH_SEMAPHORE()

2023-06-20 01:06 UTC, tridge commented on libraries/AP_Scripting/lua_bindings.cpp
> +    if (new_item == nullptr) {
cope with the error? or return a boolean?

2023-06-20 21:40 UTC, IamPete1 commented
Added a semaphore, renamed the blocking method, returning a bool for the block binding and allowing both `:` and `.` access.

2023-07-04 00:11 UTC, tridge commented
still needs testing, sorry @IamPete1

2023-07-04 00:18 UTC, tridge approved these changes

2023-07-04 00:18 UTC, tridge commented
@IamPete1 I have tested with synchronised aerobatics, works nicely

2023-07-04 00:20 UTC, peterbarker approved these changes

2023-07-04 00:20 UTC, merged