If FW landing speed -1, set to halfway between min and trim aspd; FW only autolands
ArduPilot/ardupilot pull request #24095
Opened 2023-06-19 13:31 UTC by Hwurzburg

2023-06-25 18:18 UTC, IamPete1 requested changes
If `land_airspeed` is not set we will use this new value for the approach stage and then speed up to cruise airspeed again in the preflair and final stages?

I think this new value should be used in those stages too.

2023-06-25 19:37 UTC, Hwurzburg commented
and it save some flash too...thanks

2023-06-25 19:54 UTC, IamPete1 commented
There is a trap in that switch case, there is also a `SlopeStage::NORMAL` we should still use cruise speed for that I think. You if you added that to the switch you could remove the default case.

2023-06-25 20:08 UTC, Hwurzburg commented
That case doesn't exist, This function only gets called in those 3 cases

Sent from Yahoo Mail on Android 
 
  On Sun, Jun 25, 2023 at 2:54 PM, Peter ***@***.***> wrote:   


There is a trap in that switch case, there is also a SlopeStage::NORMAL we should still use cruise speed for that I think. You if you added that to the switch you could remove the default case.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-06-25 22:14 UTC, IamPete1 commented on libraries/AP_Landing/AP_Landing_Slope.cpp
>      int32_t target_airspeed_cm = aparm.airspeed_cruise_cm;
```suggestion
    int32_t target_airspeed_cm;
```

2023-06-25 22:16 UTC, IamPete1 submitted a review, later dismissed

2023-06-25 22:16 UTC, IamPete1 commented on libraries/AP_Landing/AP_Landing_Slope.cpp
> +        target_airspeed_cm = 0.5 * (aparm.airspeed_cruise_cm * 0.01 + aparm.airspeed_min);
Sorry, just spotted this. Airspeed min is in m/s.

```suggestion
        target_airspeed_cm = 0.5 * (aparm.airspeed_cruise_cm + aparm.airspeed_min * 100.0);
```

2023-06-25 22:19 UTC, Hwurzburg commented on libraries/AP_Landing/AP_Landing_Slope.cpp
>      int32_t target_airspeed_cm = aparm.airspeed_cruise_cm;
at least its not mine...

2023-06-25 22:20 UTC, Hwurzburg commented on libraries/AP_Landing/AP_Landing_Slope.cpp
>      int32_t target_airspeed_cm = aparm.airspeed_cruise_cm;
although I should have recognized it

2023-07-04 00:21 UTC, tridge approved these changes

2023-07-04 00:24 UTC, merged