HAL_SITL: fixed multicast UDP on cygwin
ArduPilot/ardupilot pull request #24111
Opened 2023-06-21 05:22 UTC by tridge

this will allow the SITL button on cygwin to work with multicast, allowing for complex vehicle interactions between machines

2023-06-21 17:59 UTC, magicrub commented on libraries/AP_HAL_SITL/UARTDriver.cpp
> +    sockaddr.sin_addr.s_addr = INADDR_ANY;
```suggestion
    sockaddr.sin_addr.s_addr = htonl(INADDR_ANY);
```

2023-06-21 18:01 UTC, magicrub requested changes
I know it doesn't change the number in this case but best to remove traps where possible.

2023-06-25 05:17 UTC, tridge commented on libraries/AP_HAL_SITL/UARTDriver.cpp
> +    sockaddr.sin_addr.s_addr = INADDR_ANY;
no, INADDR_ANY does no need bit-order switching

2023-06-25 05:19 UTC, peterbarker commented
> I know it doesn't change the number in this case but best to remove traps where possible.

That symbol, `INADDR_ANY` should already be in the correct byte order for the platform you're on, surely?!

2023-06-26 05:49 UTC, merged