EFI: added efi MavLink class
ArduPilot/ardupilot pull request #24147
Opened 2023-06-27 09:43 UTC by Max-001

I added a MavLink class to the EFI library to store EFI-data that is received over MavLink. There are EFI systems that don't use the Cube as their "computer", those systems have their own "computer" and forward the EFI-data over MavLink. It can be usefull to store this data (using the EFI library). For example: If the EFI-data is stored, it can accessed using a LUA script. The accessing of EFI-data using a LUA script is already programmed in to the main branch.

The new class called AP_EFI_MAV has a method called handle_EFI_message, that's the method that handles the MavLink data and stores it. This method gets called in GCS_Common.cpp at the moment that a MAVLINK_MSG_ID_EFI_STATUS message appears (this is done using the switch-case in the method GCS_MAVLINK::handle_common_message). To make this all work, the EFI_TYPE parameter has to be set to 9 (meaning MAV(link)).

As an example I have writen this LUA script:
```
function update()

  local EFI_state = efi:get_state()

  gcs:send_text(6, EFI_state:intake_manifold_temperature())
  gcs:send_text(6, EFI_state:throttle_out())
  gcs:send_text(6, EFI_state:cylinder_status():cylinder_head_temperature())

  -- run at 1hz
  return update, 10000
end

return update()
```

The result of this LUA script (using the code in this pull-request) is shown below:
![image](https://github.com/ArduPilot/ardupilot/assets/80035972/7a797314-7271-49a5-9849-424d981ca114)

You can see the incomming MavLink data of the EFI system on the MavLink inspector and you can see the output of the LUA script on the left side of the screenshot. Please notice that the shown data on the MavLink inspector is in Celsius while the data shown by the script is in Kelvin.

Please refer to this earlier pull request: https://github.com/ArduPilot/ardupilot/pull/24113

2023-07-04 08:14 UTC, peterbarker requested changes
Please roll the other PR into this one.

2023-07-04 08:14 UTC, peterbarker commented on libraries/AP_EFI/AP_EFI_config.h
> +#ifndef AP_EFI_MAV_ENABLED
Alphabetical order in here, by the looks of it.

2023-07-04 08:14 UTC, peterbarker commented on libraries/AP_EFI/AP_EFI.cpp
> +#if AP_EFI_MAV_ENABLED
#if around the `case`, please

2023-07-05 08:28 UTC, peterbarker commented on libraries/AP_EFI/AP_EFI_MAV.cpp
> +    //internal_state.??? = state.rpm;
Check my PR for mappings for this.

https://github.com/ArduPilot/ardupilot/commit/8d52efbf8c44353012455d66926a8d99cfa452a0#diff-fd3b580d602da071426c9e0387b1cc0283213a5d883b00a5ae7cf89467ea4e09R15

2023-07-05 11:37 UTC, peterbarker approved these changes

2023-07-05 13:04 UTC, IamPete1 commented
This could be done in completely scripting with 0 flash cost now we have MAVLink support.

2023-07-05 14:34 UTC, Max-001 commented
Thank you for the approval @peterbarker !

I have done some more testing, besides the test that is described above (please see the first comment). I tested everything using a real EFI system. I compared the MavLink inspector with the outcome of the following LUA script:
```
function update()

  local EFI_state = efi:get_state()

  gcs:send_text(6, "ecu_index: " .. EFI_state:ecu_index())
  gcs:send_text(6, "estimated_consumed_fuel_volume_cm3: " .. EFI_state:estimated_consumed_fuel_volume_cm3())
  gcs:send_text(6, "fuel_consumption_rate_cm3pm: " .. EFI_state:fuel_consumption_rate_cm3pm())
  gcs:send_text(6, "engine_load_percent: " .. EFI_state:engine_load_percent())
  gcs:send_text(6, "throttle_position_percent: " .. EFI_state:throttle_position_percent())
  gcs:send_text(6, "spark_dwell_time_ms: " .. EFI_state:spark_dwell_time_ms())
  gcs:send_text(6, "atmospheric_pressure_kpa: " .. EFI_state:atmospheric_pressure_kpa())
  gcs:send_text(6, "intake_manifold_pressure_kpa: " .. EFI_state:intake_manifold_pressure_kpa())
  gcs:send_text(6, "intake_manifold_temperature: " .. EFI_state:intake_manifold_temperature())
  gcs:send_text(6, "cylinder_head_temperature: " .. EFI_state:cylinder_status():cylinder_head_temperature())
  gcs:send_text(6, "ignition_timing_deg: " .. EFI_state:cylinder_status():ignition_timing_deg())
  gcs:send_text(6, "injection_time_ms: " .. EFI_state:cylinder_status():injection_time_ms())
  gcs:send_text(6, "exhaust_gas_temperature: " .. EFI_state:cylinder_status():exhaust_gas_temperature())
  gcs:send_text(6, "throttle_out: " .. EFI_state:throttle_out())
  gcs:send_text(6, "pt_compensation: " .. EFI_state:pt_compensation())
  gcs:send_text(6, "ignition_voltage: " .. EFI_state:ignition_voltage())

  -- run at 1hz
  return update, 10000
end

return update()
```

The MavLink inspector and the outcome of the LUA script are the same, please see the screenshot below. There are a few very small differences between the MavLink inspector and the outcome of the LUA script, that is because the MavLink inspector is updated much quicker than the LUA script (so the small differences is nothing to worry about).
![screenshot3](https://github.com/ArduPilot/ardupilot/assets/80035972/b38a8e32-bab4-4880-9198-e4bacf157d58)

I also compared the MavLink inspector and the outcome of the LUA script for a longer period of time and the values are continuously the same. This is done with and without running motor.

2023-07-11 00:04 UTC, rmackay9 approved these changes

2023-07-11 02:32 UTC, merged

2024-02-03 19:09 UTC, AliSeedg commented
Can you give me the code you used?

2024-02-04 13:25 UTC, Max-001 commented
> Can you give me the code you used?

Do you mean the LUA script?

```
function update()

  local EFI_state = efi:get_state()

  gcs:send_text(6, "ecu_index: " .. EFI_state:ecu_index())
  gcs:send_text(6, "estimated_consumed_fuel_volume_cm3: " .. EFI_state:estimated_consumed_fuel_volume_cm3())
  gcs:send_text(6, "fuel_consumption_rate_cm3pm: " .. EFI_state:fuel_consumption_rate_cm3pm())
  gcs:send_text(6, "engine_load_percent: " .. EFI_state:engine_load_percent())
  gcs:send_text(6, "throttle_position_percent: " .. EFI_state:throttle_position_percent())
  gcs:send_text(6, "spark_dwell_time_ms: " .. EFI_state:spark_dwell_time_ms())
  gcs:send_text(6, "atmospheric_pressure_kpa: " .. EFI_state:atmospheric_pressure_kpa())
  gcs:send_text(6, "intake_manifold_pressure_kpa: " .. EFI_state:intake_manifold_pressure_kpa())
  gcs:send_text(6, "intake_manifold_temperature: " .. EFI_state:intake_manifold_temperature())
  gcs:send_text(6, "cylinder_head_temperature: " .. EFI_state:cylinder_status():cylinder_head_temperature())
  gcs:send_text(6, "ignition_timing_deg: " .. EFI_state:cylinder_status():ignition_timing_deg())
  gcs:send_text(6, "injection_time_ms: " .. EFI_state:cylinder_status():injection_time_ms())
  gcs:send_text(6, "exhaust_gas_temperature: " .. EFI_state:cylinder_status():exhaust_gas_temperature())
  gcs:send_text(6, "throttle_out: " .. EFI_state:throttle_out())
  gcs:send_text(6, "pt_compensation: " .. EFI_state:pt_compensation())
  gcs:send_text(6, "ignition_voltage: " .. EFI_state:ignition_voltage())

  -- run at 1hz
  return update, 10000
end

return update()
```

2024-02-06 15:05 UTC, AliSeedg commented
Thank you really
But I have a problem. I send an efi status message via Arduino and it appears to me in the mavlink inspector, but it does not appear in quick. I want a solution. Is it by changing the main system code or via lua?

2024-02-06 15:29 UTC, AliSeedg commented
06/02/24 06:28:39 م : ll a nil value (method 'get_state')
06/02/24 06:28:39 م : Lua: /APM/scripts/MAX.lua:3: attempt to ca
I see this when I use your code

2024-02-07 06:44 UTC, AliSeedg commented
Yes

2024-02-08 06:31 UTC, Max-001 commented
> Yes

Ok, and I assume that it still doesn’t work.
Could you please share you’re setup in more detail (e.g. hardware connection from Arduino to Cube, Arduino code, ArduPilot setup, etcetera)?

2024-02-08 14:26 UTC, AliSeedg commented
Thank you. My problem was solved and my data appeared on the quick screen without using the Lua language, only via Arduino and Maflink. The problem was in the firmware file.