AP_BattMonitor: Allow INA2xx shunt resistor value to be configured as a parameter
ArduPilot/ardupilot pull request #24151
Opened 2023-06-27 20:26 UTC by Mf-ff99

The default value for the ina2xx current sensor shunt resistor is .0005, previously this was hard-coded. However, for vehicles with different hardware this value needs to be configurable. I have tested functionality by changing this parameter on several machines running two INA228 current sensors with a shunt resistor value different from the default of .0005.

2023-08-15 02:33 UTC, tridge requested changes
good idea!

2023-08-15 02:33 UTC, tridge commented on libraries/AP_BattMonitor/AP_BattMonitor_INA2xx.cpp
> +    // @RebootRequired: True
doesn't require a reboot

2023-08-15 02:33 UTC, tridge commented on libraries/AP_BattMonitor/AP_BattMonitor_INA2xx.cpp
> +#define DEFAULT_BATTMON_INA_SHUNT .0005
please use 0.0005 (ie. leading zero)

2023-08-23 20:50 UTC, Mf-ff99 commented
Resolved comments and squashed commits.

2023-09-06 03:08 UTC, vincentpoont2 commented
Good idea to have the shunt resistor value as a parameter.

2024-07-25 02:26 UTC, peterbarker commented
@Mf-ff99 looks like @tridge forgot this PR existed and implemented the same thing in e9fc3ab57030da7d293a0955f9cf841918736b48

Thanks for the PR, anyway!

2024-07-25 02:26 UTC, closed without merging