AP_ESC_Telem: Add ESC_TLM_LOG_MASK to control which motors are logged
ArduPilot/ardupilot pull request #24199
Opened 2023-07-02 23:19 UTC by mbuzdalov

My whoop flight controller has only 8Mb memory for logging, and with bidirectional DShot enabled it could not contain a flight of 6+ minutes long. By inspection, I found that a vast majority of the entries are ESC entries. After I realized that nothing controls whether and how these entries are logged, I decided to introduce a parameter to do that.

The new parameter `ESC_TLM_LOG_MASK` is a bitmask where the i-th bit enables logging of the (i+1)-th motor (i-th if counting from zero). The implementation is pretty straightforward and entirely contained within `AP_ESC_Telem.{h, cpp}`.

This has just been tested on my ArduWhoop build. Particularly with the parameter set to 0, the log size for 6 minutes was below 4.5 megabytes, whereas it reached 8 megabytes for some 4 minutes before the change.

- **Why bitmask**? I can imagine that in VTOLs one may be interested only in a subset of motors being logged.
- **Why not extending `LOG_BITMASK`**? It seems to be vehicle-dependent in a strong way.
- **Why is the default 255**? The default is to enable logging for backward compatibility, and covers 8 motors. Maybe this should be larger.

2023-07-03 06:57 UTC, andyp1per requested changes
@mbuzdalov thanks for this - at a minimum we should change the regular LOG_BITMASK to control logging of ESCs. LOG_BITMASK is already vehicle dependent so I think this should be possible. As for this change - I am not sure what the right solution is - I just worry that it is yet another bitmask for the user to get their head around. Is your use case that you want to only log one ESC to save logging space?

2023-07-03 07:53 UTC, mbuzdalov commented
@andyp1per my opinion is that:

- `LOG_BITMASK` is so messed up as of now, with same functionality sometimes mapped to different bits, that one should really think hard before considering adding a new option there.
- `AP_ESC_Telem.cpp` is vehicle independent and cannot include `<vehicle>/defines.h`, so it has no legal way of knowing which bit it should check.
- I could not find where we call `AP_ESC_Telem::update`, and this is definitely not called directly from one of the vehicle's loops.
- The way I did this is vehicle-independent, which I see as a good thing.
- I have seen some subsystem logging configuration in parameters, so I thought adding something like that to `ESC_TLM_*` is not too bad.
- If we set 2^31-1 as a default value for this parameter, users will never ever have to do anything, unless they explicitly want to cut down some logging.

My use case is to generally keep that ESC logging turned off, and be able to turn it on if I need, so my personal desire could have been satisfied by one-bit configuration - however, my current solution does not seem to be too expensive and is more future-proof.

2023-07-03 08:04 UTC, mbuzdalov commented
I have changed the default and force-pushed the changes. Now it is completely backwards-compatible.

2023-07-03 08:51 UTC, mbuzdalov commented
I have changed the default value to 0xFFFF. It appears that one cannot set it to 0xFFFFFFFF, because the result should be castable to `float`. I have seen that `AP_PiccoloCAN/AP_PiccoloCAN.cpp`, which uses the same 32-bit bitmask for one of its parameters, uses 0xFFFF.

So for `ESC_TLM_LOG_MASK` the default value would enable logging for first 16 motors. Probably this is enough.

Alternatively, it is possible to introduce instead a parameter which disables logging for chosen motors, with a default bitmask of 0. Is it better?

2023-07-03 11:30 UTC, IamPete1 commented
If the only goal is to reduce the log size I would much rather have all my motors logged at a lower rate than some of my motors at a high rate. 

Have you tried the the logging rate max parameter to lower you log sizes? (This will reduce the rate of all logging). Or we could add a new rate max param for ESCs.

2023-07-03 13:38 UTC, mbuzdalov commented
Ah, what an idiot I am...

So, well, I need to test rate limiting in my setup. If it works, then the entire PR seems unneeded, because one is unlikely to want to stop ESCs from logging (for memory reasons), but in the same time to have something else logged at high rate. Am I right?

2023-07-04 16:36 UTC, mbuzdalov commented
With a rate limit of 10Hz and complete ESC logging, the log file size is 4Mb for 6 minutes and 20 seconds. So my case is covered with existing tools. As other cases are not clear now, I am going to close this PR now. Thank you for the discussion!

2023-07-04 16:36 UTC, closed without merging

2023-07-05 20:14 UTC, andyp1per commented
@mbuzdalov we have slow/medium/fast logging for other subsystems - e.g. attitude logging, so you are not necessarily wrong here. Rate limiting limits *everything*, maybe you only want to limit ESCs