Feed-forward scaling based on angle gain ratio
ArduPilot/ardupilot pull request #24207
Opened 2023-07-03 18:52 UTC by andyp1per

An experiment

2023-07-18 03:15 UTC, tridge requested changes
RealFlight testing is not good for this. The fundamental issue that the scaling is doing is dealing with the fact that the maximum achievable roll/pitch rate of the vehicle is variable, not fixed. When you have significant airspeed the aircraft has more damping than it does when it is in hover, which effectively limits what the VTOL rate controllers can achieve. If you demand more than can be achieved then you end up with a very nasty angle P oscillation (limit cycle oscillation). I doubt RealFlight really models this accurately, but before we put this scaling in we did see this happen on real aircraft, particularly large quadplanes. They got into very dangerous oscillations during back transitions where VTOL throttle is low but we started to demand high rates, higher than it could physically achieve

2023-07-18 03:19 UTC, tridge commented
what we really need is limit cycle detection in the angle P loop, then we could automatically reduce gains.

2023-07-18 10:19 UTC, andyp1per commented
@tridge not sure I agree - limit cycle detection is just papering over the problem and is a lot more complexity, better to have a tune that doesn't hit the threshold. We already have limit cycle detection with SMAX, so would have thought that was sufficient for our protection. You mention the issue you had in the past - do you have the logs for that - it would be great to see them and compare?
I do agree that we have to be careful with significant airspeed and that perhaps scaling back angle P based on airspeed might be necessary - I did suggest this to @lthall but he suggested it was better to try the simple thing first. What is interesting about this change is that it has the most benefit at medium/low airspeed in particular when the existing scaler is active - in theory the control surfaces should not be providing much input - but they do and couple with the lowered VTOL angle P leads to very severe oscillation.
I do agree that at high speeds just before transition we need to be careful that the VTOL motors can provide the requested rates/position - Leonard seemed to think that the maths meant that the output was identical - I did query him about this several times :)
Finally this has been tested on a real vehicle with dramatic results (RF was just beta testing). It's hard to deny its having a very positive beneficial effect - https://youtu.be/8kuQ-YjRnSs

2023-07-18 13:27 UTC, andyp1per commented
One thing I am wondering is whether angle P should also be scaled based on the tilt angle. Without tilting the VTOL motors will always be able to deliver what they have been tuned for, but with tilting they can only deliver a proportion based on the amount of tilt and hence perhaps the fixed-wing FF needs to deliver more.

2023-07-20 19:54 UTC, andyp1per commented
Looking at the tiltrotor code and the way it scales back the motor thrust, particularly on roll, I'm more and more thinking that we should be using the "effective angle P" in the scaling - i.e. taking the tilting into account.

2023-07-22 04:02 UTC, lthall commented
When Tridge and I did this originally we made the assumption that we could pass the rate request between the plane and VTOL controllers from which ever was in control. However, when I was talking to Tridge about this I didn't consider that plane uses feed forward (at the time it was called something else).

So the dominant control path in many plane controllers is the product of angle P (time constant in plane) and FF. However when we pass the rate request from VTOL to plane the angle P can increase by a factor of 5 to 10. This could mean that on the back transition we are effectively reducing the plane roll/pitch time constant by a factor of 5 to 10 causing an oscillation.

This is why I think reducing the plane FF term to ensure the product of Angle_P and FF is not increased above FF / time constant.

2023-07-26 08:38 UTC, tridge commented
I need to try some flight tests on this and discuss with @priseborough

2023-07-30 00:11 UTC, tridge commented
@andyp1per the tests I'd like to see are with the AUTO landing sequence, or QRTL. That is what most quadplanes use. FBWA -> QLOITER is primarily used as an emergency transition, not normal flying

2023-08-22 20:19 UTC, andyp1per commented
Two back-to-back auto missions. First with the change:

[log94.zip](https://github.com/ArduPilot/ardupilot/files/12412673/log94.zip)

![image](https://github.com/ArduPilot/ardupilot/assets/2893260/9dc09a5b-630c-4189-89ab-566c38ab84f8)

Then without:

[log95.zip](https://github.com/ArduPilot/ardupilot/files/12412674/log95.zip)

![image](https://github.com/ArduPilot/ardupilot/assets/2893260/cf6ad23b-d6d0-4035-ad3e-6634e6ec2b18)

You can see that the FF is massively reduced in the first log but not the second

2023-09-01 09:29 UTC, tridge commented
@andyp1per I did a test flight on the Hero with 2 back-to-back AUTO landings, first with the new FF scaling enabled, 2nd without. 
Log here:
http://uav.tridgell.net/tmp/Hero-12.bin
As far as overall control during the landing it is very hard to pick a difference, but there was less FF activation with the patch enabled, it just didn't result in any significant change in the attitude control

2023-09-02 15:44 UTC, andyp1per commented
Thanks for testing @tridge ! I think this is the result I would expect, given that your aircraft is very well tuned and glad that nothing appeared worse. My argument would be that since this makes a more significant difference on less well tuned aircraft, it would be worth adopting to give users the best possible chance of getting something flying without crashing. The aircraft I am testing this on is hobby grade and I suspect we are going to see more hobby grade users with the level of expertise that goes with that - so this would likely benefit the new, less experienced user and give them a more positive view of ardupilot.

2023-09-13 08:02 UTC, tridge approved these changes

2023-09-13 08:02 UTC, merged