AP_NavEKF3: define Yaw alignment min GPS speed per vehicle
ArduPilot/ardupilot pull request #24206
Opened 2023-07-03 11:58 UTC by rmackay9

This improves GSF performance for Copter and Rover 4.4 by reducing the minimum speed the vehicle must be travelling at for a GSF reset to occur.

The minimum speed requirement issue (see https://github.com/ArduPilot/ardupilot/issues/24183) was introduced with PR https://github.com/ArduPilot/ardupilot/pull/23515 but the minimum (5m/s) was likely designed with Planes in mind.This PR reduces the limit to 2m/s for Copters and 0.5m/s for Rover.  These are somewhat arbitrary values .. perhaps Copter could be lowered further to 1m/s.

Related discussion: https://discuss.ardupilot.org/t/yaw-not-aligning-to-gsf-anymore-after-updating-from-4-2-3-to-4-4-0-beta1/101844/13

2023-07-03 18:09 UTC, IamPete1 commented
I wonder if we could automatically reduce the threshold based on the reported GPS accuracy, might be more trouble than its worth tho.

2023-07-04 02:27 UTC, tridge requested changes

2023-07-04 02:27 UTC, tridge commented on libraries/AP_NavEKF3/AP_NavEKF3_MagFusion.cpp
> +  #define GPS_VEL_YAW_ALIGN_MIN_SPD 2.0F
I'd like input from @priseborough on whether lowering this is safe for copters

2023-11-20 00:12 UTC, rmackay9 commented
I've rebased this on master and this [is being tested here](https://discuss.ardupilot.org/t/copter-4-4-1-released/107005/15).

2024-02-14 10:22 UTC, priseborough commented
There is no theoretical  reason why that threshold cant be lowered for copter and rover platforms. The GSF alignment is more a function of acceleration profile than it is velocity. The velocity threshold does indirectly enforce a prior speed change and therefore horizontal acceleration event which is why it was added. During the initial development of this algorithm I flew a copter with no minimum speed requirement and alignment was OK provided the GSF GPS data fusion didn't start running until alignment, but that was with a well isolated IMU and good GPs data. 

Has anyone else with a average HW quality copter tested this lower threshold?

2024-03-25 23:01 UTC, tridge approved these changes

2024-03-25 23:01 UTC, merged

2024-04-27 02:35 UTC, rmackay9 commented
This is included in 4.5.2-beta1