AP_Camera: add support for the user to specify which gimbal each camera is in
ArduPilot/ardupilot pull request #24398
Opened 2023-07-26 05:10 UTC by khanasif786

Draft

2023-07-26 05:25 UTC, rmackay9 commented on libraries/AP_Camera/AP_Camera_Mount.cpp
> +    } else {
nitpick: you can remove the else because of the return above it.

2023-07-26 05:26 UTC, rmackay9 commented on libraries/AP_Camera/AP_Camera_Mount.cpp
> +uint8_t AP_Camera_Mount::get_mount_instance_for_camera() const
Let's put a little comment above here just to match other methods.  It's all pretty obvious what it does but still, I like comments! :-)

2023-07-26 05:26 UTC, rmackay9 commented on libraries/AP_Camera/AP_Camera_Mount.h
> +    uint8_t get_mount_instance_for_camera() const;
let's put a short comment above here too.

2023-07-26 05:27 UTC, rmackay9 commented on libraries/AP_Camera/AP_Camera_Params.cpp
> +    // @DisplayName: Mount instance
Let's rename this to "Camera Mount instance".  It's good to have the subsystem name at the front when possible.

2023-07-26 05:29 UTC, rmackay9 commented on libraries/AP_Camera/AP_Camera_Params.cpp
> +    // @Description: Mount instace to which camera is associated with
Let's add something like this to the end, "If zero the camera instance number is used.  E.g. camera1 is assumed to be in mount1, etc."

2023-07-26 05:30 UTC, rmackay9 commented
I've put some comments in but this all looks very good to me, thanks!

2023-07-26 11:51 UTC, IamPete1 commented on libraries/AP_Camera/AP_Camera_Mount.cpp
> +        return _instance - 1;
```suggestion
        return _instance;
```

2023-07-26 11:56 UTC, rmackay9 commented on libraries/AP_Camera/AP_Camera_Mount.cpp
> +        return _instance - 1;
Indeed, @IamPete1's suggestion seems correct.  thanks!

2023-07-26 18:57 UTC, khanasif786 commented on libraries/AP_Camera/AP_Camera_Mount.cpp
> +        return _instance - 1;
@IamPete1, oops... my bad

2023-07-26 23:13 UTC, rmackay9 commented on libraries/AP_Camera/AP_Camera_Mount.cpp
> +        return mount->set_tracking(get_mount_instance(), tracking_type, p1, p2);
This all looks good.  I think with PR https://github.com/ArduPilot/ardupilot/pull/24346 being merged there's one more that needs to be added for the set_lens() method.

2023-07-31 10:53 UTC, rmackay9 commented
I did a search through AP_Camera for, "mount->" and found that we've probably missed:

- AP_Camera_Backend::Write_CameraInfo() uses the ca,era instance when it should use the newly added method
- send_camera_information() and send_camera_settings() seem to send for all mounts which doesn't seem correct.  Surely this should only be sending for one instance (this seems like my mistake, sorry!)

2023-08-02 01:06 UTC, rmackay9 commented on libraries/AP_Mount/AP_Mount.cpp
> -        set_angle_target(instance, 0, pitch_angle_deg, yaw_angle_deg, flags & GIMBAL_MANAGER_FLAGS_YAW_LOCK);
Nice find.  Can you fix the commit title to start with, "AP_Mount:"?

2023-08-02 01:06 UTC, rmackay9 commented
Looking good!

2023-08-03 05:17 UTC, peterbarker commented on libraries/AP_Camera/AP_Camera_Params.cpp
> +    // @Description: Mount instace to which camera is associated with. By default its 0 means camera and mount have identical instance numbers e.g. camera1 and mount1
```suggestion
    // @Description: Mount instance camera is associated with. 0 means camera and mount have identical instance numbers e.g. camera1 and mount1
```

2023-08-03 05:18 UTC, peterbarker commented on libraries/AP_Mount/AP_Mount.cpp
> +        backend->set_angle_target(0, pitch_rate_degs, yaw_rate_degs, flags & GIMBAL_MANAGER_FLAGS_YAW_LOCK);
```suggestion
        backend->set_rate_target(0, pitch_rate_degs, yaw_rate_degs, flags & GIMBAL_MANAGER_FLAGS_YAW_LOCK);
```

2023-08-03 05:20 UTC, peterbarker requested changes
A couple of things to fix in stand-alone comments.

2023-08-09 01:03 UTC, merged

2023-08-09 01:03 UTC, rmackay9 commented
Merged, thanks!