SITL: Increase max sats for UBX to 13
ArduPilot/ardupilot pull request #24523
Opened 2023-08-07 01:38 UTC by Ryanf55

since the autotest suite sets the SIM param to 13 sats in the test

2023-08-07 07:30 UTC, khancyr approved these changes
should be fine
unless we don't put les than 7, the number doesn't serve on ArduPilot side. Could impact some code using the GPS number on external program thus. 
But that is SITL, so not a big deal I think

2024-04-11 02:41 UTC, peterbarker requested changes
Needs a rebase.

We don't do anything with the data from svinfo apart from log it - and use the hardware ID from it.... on non-F9 boards.

... we should probably dynamically change the size of the array based on the number of simulated satellites, or just dynamically generate the data.  Makit it equal to the default value of the parameter doesn't really help.

2024-04-11 03:45 UTC, Ryanf55 commented
Hi Peter, feel free to push on top of the branch. I'm tied up this week.

2024-09-12 12:30 UTC, peterbarker commented
I'm not sure we need this patch; things seem to muddle along.

I actually like having these as separate numbers as it makes clear there's something askew.

@Ryanf55 did you want to pursue this one?

2024-09-21 04:36 UTC, closed without merging