DroneCAN: add get/set param timeout
ArduPilot/ardupilot pull request #24542
Opened 2023-08-08 05:57 UTC by rmackay9

This adds a 0.1 sec timeout while waiting for a response after attempting to get or set a parameter on a device/node which resolves issue https://github.com/ArduPilot/ardupilot/issues/24541

I've also attempted to improve the comments around the methods involved.

This has been tested on real hardware using a Xacti camera/gimbal which may fail to respond to get/set parameter requests if it is busy handling the latest gimbal target message.  Without this change once the device failed to respond, AP would never send another get/set request.
![image](https://github.com/ArduPilot/ardupilot/assets/1498098/189a9c3c-c59b-4aab-8413-1fc09c2e017e)

This was written after a discussion with @bugobliterator.

One small thing that I'm not completely happy with is that we assumption that the state of these variables is kept consistent:

- param_request_sent_ms == 0   <-- the system time that the caller requested to get or set a parameter 
- param_int_cb != nullptr  <-- the caller provided an integer parameter call back function
- param_float_cb != nullptr  <-- the caller provided an float parameter call back function

So for example in check_parameter_callback_timeout() we check the top one while in get_parameter_on_node() (and many other methods) we check the bottom two.  I think this is acceptable though especially with the improved comments.

2023-08-09 06:46 UTC, bugobliterator approved these changes

2023-08-09 06:50 UTC, tridge reviewed
looks good, but it likely is worth adjusting this code in AP_DroneCAN.cpp:
```
    param_save_client.set_timeout_ms(20);
    param_save_client.set_priority(CANARD_TRANSFER_PRIORITY_LOW);

    param_get_set_client.set_timeout_ms(20);
    param_get_set_client.set_priority(CANARD_TRANSFER_PRIORITY_LOW);
```
to raise the timeouts. It may be that the request never actually gets sent to the node, as we could be timing out and killing the request.

2023-08-09 06:58 UTC, bugobliterator requested changes

2023-08-09 06:58 UTC, bugobliterator commented on libraries/AP_DroneCAN/AP_DroneCAN.h
>      bool set_parameter_on_node(uint8_t node_id, const char *name, float value, ParamGetSetFloatCb *cb);
```suggestion
    // returning true from callback means the parameter needs to be modified, additional request
    // to do so will be made and the callback will be called again
    // if parameter is simply to be get or is set correctly already, callback should
    bool set_parameter_on_node(uint8_t node_id, const char *name, float value, ParamGetSetFloatCb *cb);
```

2023-08-09 08:07 UTC, tridge commented
@rmackay9 this is fine to merge without the set_timeout_ms() change, just thought you might like to check if that fixes the underlying problem

2023-08-09 08:10 UTC, merged

2023-08-09 11:05 UTC, rmackay9 commented
@tridge,

Thanks for the review and merge.  I increased the timeout to 200ms for the two items you mentioned above but the Xacti gimbal still didn't reply in 10% ~ 20% of tests.  I suspect this means that the gimbal really is busy and not listening to DroneCAN requests because it is busy with something else.  I'll pass this onto the manufacturer but they do say in their data sheet about how messages shouldn't be sent too close together.

2023-08-10 20:42 UTC, magicrub commented
Is this worth worrying about for a v4.4.1 backport?

2023-08-10 23:03 UTC, rmackay9 commented
Hi @magicrub,

We haven't seen any reports of issues perhaps because DroneCAN peripherals don't normally fail to respond.. in any case I've added it to the 4.4 projects so it'll be considered for backporting anyway.

2023-08-11 19:36 UTC, magicrub commented
@rmackay9 since Plane 4.4.0 release is so soon (PR https://github.com/ArduPilot/ardupilot/pull/24585), lets not complicate things with Copter and Plane diverging on this. If this is considered for backport, I suggest 4.4.1 on both platforms. For the record, I'm not necessarily suggesting it needs to be backported. I was just asking the question. As you said, since we haven't had any reports of it then maybe we shouldn't bother.