AP_DDS: Add AP_DDS_config.h for feature defines
ArduPilot/ardupilot pull request #24553
Opened 2023-08-09 05:22 UTC by Ryanf55

This will be expanded upon for visual odom and other optional features.

2023-08-10 20:33 UTC, Ryanf55 commented on libraries/AP_DDS/AP_DDS_config.h
> +#define AP_DDS_UDP_ENABLED (CONFIG_HAL_BOARD == HAL_BOARD_SITL)
To test: Make sure you can use UDP.

2023-08-11 21:44 UTC, tridge approved these changes

2023-08-15 07:27 UTC, peterbarker requested changes

2023-08-15 07:27 UTC, peterbarker commented on libraries/AP_DDS/AP_DDS_config.h
> +#include <AP_Common/AP_Common.h>
```suggestion
```

Bad idea in these _config.h files

2023-08-17 00:58 UTC, Ryanf55 commented on libraries/AP_DDS/AP_DDS_config.h
> +#include <AP_Common/AP_Common.h>
Fixed

2023-08-17 01:18 UTC, peterbarker submitted a review, later dismissed

2023-08-17 01:18 UTC, peterbarker commented on libraries/AP_DDS/AP_DDS_config.h
> +
```suggestion
#include <AP_HAL/AP_HAL_Boards.h>

```

2023-08-17 01:21 UTC, Ryanf55 commented on libraries/AP_DDS/AP_DDS_config.h
> +
Added.

2023-08-17 22:35 UTC, merged