AP_Follow: add and use AP_FOLLOW_ENABLED
ArduPilot/ardupilot pull request #24597
Opened 2023-08-11 17:06 UTC by shiv-tyagi

This adds a define AP_FOLLOW_ENABLED. It is needed to compile out AP_Follow library whenever required.

2023-08-12 00:38 UTC, peterbarker commented
LGTM.

```
Board               AP_Periph  blimp  bootloader  copter  heli  iofirmware  plane  rover  sub
Durandal                       *      *           *       *                 *      *      *
HerePro             *                                                                     
Hitec-Airspeed      *                                                                     
KakuteH7-bdshot                *      *           *       *                 *      *      *
MatekF405                      *      *           *       *                 *      *      *
Pixhawk1-1M-bdshot             *                  *       *                 *      -1384  *
f103-QiotekPeriph   *                                                                     
f303-Universal      *                                                                     
iomcu                                                           *                         
revo-mini                      *      *           *       *                 *      *      *
skyviper-v2450                                    *                                       
```

2023-08-12 00:38 UTC, peterbarker approved these changes

2023-08-14 22:48 UTC, tridge requested changes
need to explain why rover loses so much code on Pixhawk1M
![image](https://github.com/ArduPilot/ardupilot/assets/831867/fd47b683-3d57-4ea1-b93c-b16b84aeae52)

2023-08-14 23:57 UTC, tridge approved these changes

2023-08-14 23:57 UTC, merged

2023-08-14 23:57 UTC, rmackay9 reviewed
LGTM, thanks