Copter: Adding a class name
ArduPilot/ardupilot pull request #24621
Opened 2023-08-12 13:34 UTC by muramura

In other methods, the class name is appended.
I match the format.

2023-08-13 23:40 UTC, rmackay9 requested changes
I'm ok with this change but if we're going to change one, let's change all calls to micros() to specify the class.  So a single commit for Copter and Rover would be acceptable.  I'm less sure if the Blimp and Plane maintainers will accept the change.

2024-05-24 01:27 UTC, peterbarker commented on ArduCopter/failsafe.cpp
> -    failsafe_last_timestamp = micros();
I think I recall losing the namespace actually makes this faster.

2024-05-27 23:18 UTC, peterbarker commented on ArduCopter/failsafe.cpp
> -    failsafe_last_timestamp = micros();
Confirmed, this is faster and smaller.

2024-05-27 23:19 UTC, tridge commented
we deliberately have it in vehicles as faster and smaller

2024-05-27 23:19 UTC, closed without merging

2024-05-27 23:20 UTC, rmackay9 commented
@muramura, feel free to raise a PR to instead remove the AP_HAL:: part from other calls in the Copter code.