AP_Mount/GCS_MAVLink: move handling of all do-set-roi to AP_Mount library
ArduPilot/ardupilot pull request #24654
Opened 2023-08-15 14:43 UTC by khanasif786

In reference to issue #24571 
Initial Draft
(Not tested yet)

2023-08-16 00:58 UTC, peterbarker requested changes

2023-08-16 00:58 UTC, peterbarker commented on ArduCopter/GCS_Mavlink.cpp
> +MAV_RESULT GCS_MAVLINK_Copter::handle_command_long_mount(const mavlink_command_long_t &packet, const mavlink_message_t &msg)
This doesn't look right.  We should be accepting *anything* as *just* command_long.

2023-08-17 06:01 UTC, rmackay9 commented on libraries/GCS_MAVLink/GCS_Common.cpp
> +            return mount->handle_command_int(packet);
We should also send the "mavlink_message_t" as an argument.

2023-08-17 06:01 UTC, rmackay9 commented on libraries/GCS_MAVLink/GCS_Common.cpp
>  MAV_RESULT GCS_MAVLINK::handle_command_int_packet(const mavlink_command_int_t &packet)
This GCS_MAVLINK::handle_command_int_packet() method is going to need to be changed to include a new argument, "const mavlink_message_t &msg"

2023-08-17 06:04 UTC, rmackay9 commented
PeterB says, move this block from GCS_MAVLink::handle_command_long() to GCS_MAVLink::handle_command_int()..

   case MAV_CMD_DO_MOUNT_CONFIGURE:
    case MAV_CMD_DO_MOUNT_CONTROL:
    case MAV_CMD_DO_GIMBAL_MANAGER_PITCHYAW:
    case MAV_CMD_DO_GIMBAL_MANAGER_CONFIGURE:
        // some mount commands require the source sysid and compid
        result = handle_command_mount(packet, msg);
        break;

2023-08-17 06:04 UTC, peterbarker requested changes

2023-08-17 06:04 UTC, peterbarker commented on libraries/GCS_MAVLink/GCS_Common.cpp
> +            AP_Mount *mount = AP_Mount::get_singleton();
All of this should be moved into `void GCS_MAVLINK::handle_command_int(const mavlink_message_t &msg)` instead

2023-08-25 22:55 UTC, peterbarker approved these changes
LGTM

2023-08-25 23:39 UTC, rmackay9 commented
@khanasif786, thanks for this.  Can you clarify what testing has been done?  .. and maybe update the Description above..

2023-08-26 07:55 UTC, merged

2024-05-09 15:55 UTC, rajviCE commented
.