Support baroless boards correctly in the EKF
ArduPilot/ardupilot pull request #24656
Opened 2023-08-15 16:13 UTC by andyp1per

Currently boards without baros quickly accumulate large velocity errors while sitting on the bench. Here is an example from a MambaF405v2:
![log1](https://github.com/ArduPilot/ardupilot/assets/2893260/8b3b09e1-ed8f-40b4-b887-9c9c360f09de)

The reason is that the EKF is fusing completely invalid data (the columns are all zero?). @priseborough suggested that a way around this would be to provide a dummy baro on these boards. Fortunately we already have one which only needed some minor changes and using this yielded much more sane results:
![log2](https://github.com/ArduPilot/ardupilot/assets/2893260/d3fcac1d-6845-43b3-b71c-862edb7811ae)

The second part of the fix is to allow much larger values of EK3_ALT_M_NSE to be set since the baro will always be giving a constant fixed height, but the height of the copter will vary. This value is in meters so allowing a value for the maximum height of these copters (usually relatively small because of the lack of baro) is prudent.

Logs here:
[logs.zip](https://github.com/ArduPilot/ardupilot/files/12346163/logs.zip)

2023-08-16 05:16 UTC, peterbarker commented
Can you avoid the problem by changing the EKF3 sources to not use the baro?

If so, should we just change the defaults for boards which are allowed to boot without baro?

2023-08-16 07:28 UTC, tridge requested changes
better to add a new EK3_SRCn_POSZ as "nul", which says explicitly we have no height source

2023-08-16 12:41 UTC, andyp1per commented
Confirmed that setting EK3_SRC1_POSZ to 0 does *not* fix the issue

2023-08-16 15:23 UTC, andyp1per commented
This works great on a real vehicle! It's surprising how well AltHold does without a barometer! No issues flying.

2023-08-16 15:24 UTC, andyp1per commented
I looked into doing this in the EKF - it's way too complicated for me to tackle in a reasonable timeframe and I think this PR solves the problem nicely at minimal cost and risk.

2023-08-20 09:07 UTC, priseborough commented
I've worked out how to support EK3_SRCx_POSZ = 0  using a minimum code change inside the EKF - see https://github.com/priseborough/ardupilot/commits/ekfNoBaro-wip

@andyp1per has performed preliminary bench testing of those EKF patches and achieved stable position innovations, position staters and velocity state 

<img width="1039" alt="Screenshot 2023-08-20 at 7 04 05 pm" src="https://github.com/ArduPilot/ardupilot/assets/3596952/784900cb-a137-4b74-918b-739ec681ec1a">

<img width="1036" alt="Screenshot 2023-08-20 at 7 06 07 pm" src="https://github.com/ArduPilot/ardupilot/assets/3596952/1302a430-c55d-4f71-8b1f-487eaa92a62e">

<img width="1041" alt="Screenshot 2023-08-20 at 7 06 32 pm" src="https://github.com/ArduPilot/ardupilot/assets/3596952/894dfb16-bcdf-4568-a22c-c2a606370467">

2023-08-20 09:09 UTC, priseborough commented
@andyp1per if those EKF changes meet your requirements, feel free to pull them into this or another PR. I can follow up any test anomalies.

2023-08-20 12:31 UTC, andyp1per commented
Perfect, thanks @priseborough - looks great!

2023-08-23 08:22 UTC, tridge requested changes

2023-08-23 08:22 UTC, tridge commented on .github/workflows/test_ccache.yml
> +          Tools/scripts/build_tests/test_ccache.py --boards Durandal,Pixhawk6X --min-cache-pct=70
unnecessary?

2023-08-23 08:25 UTC, tridge approved these changes

2023-08-23 08:25 UTC, merged

2023-08-23 14:59 UTC, andyp1per commented
Since this affects so many of the smaller boards and there is no good solution I have marked this for 4.4 @rmackay9