AP_Networking: Delete entity class pointer
ArduPilot/ardupilot pull request #24685
Opened 2023-08-17 22:43 UTC by muramura

The generated class pointer variable is set to NULLPTR.
The generated class pointer is released before setting.

2023-08-21 08:47 UTC, peterbarker approved these changes
This looks right to me.

There *may* be unusual reasons this can't be done, but those would *really* need a comment.

2023-08-22 00:48 UTC, tridge requested changes

2023-08-22 00:48 UTC, tridge commented on libraries/AP_Networking/AP_Networking.cpp
> +        delete backend;
i think instead we add a comment explaining why we don't delete
we could have callbacks or interrupt handlers installed, or a thread relying on the backend

2023-08-22 01:48 UTC, peterbarker commented on libraries/AP_Networking/AP_Networking.cpp
> +        delete backend;
```suggestion
        // the backend init function creates a thread which references the backend pointer; that thread may be running so don't remove the backend allocation.
```

2023-08-22 16:25 UTC, merged