Use textual IDs for APJ_BOARD_ID in hwdef
ArduPilot/ardupilot pull request #24718
Opened 2023-08-21 11:58 UTC by peterbarker

... I'm wondering whether we should instead infer the ID from the directory name, and change `board_types.txt` to match the directory name.  Removing another unnecessary line from the hwdef....

2023-08-22 01:13 UTC, tridge commented
maybe check configure_all.py gets the same hwdef.h

2023-08-22 02:24 UTC, peterbarker commented
```
#!/usr/bin/perl -w

use strict;
use warnings;

use FileHandle;
use DirHandle;

my $fh = FileHandle->new("Tools/AP_Bootloader/board_types.txt");
my %board_id_to_name_map;
LINE: while (defined (my $line = <$fh>)) {
  chomp $line;
  $line =~ s/#.*//;
  if ($line =~ /^\s*$/) {
    next LINE;
  }
  if ($line =~ /^Reserved /) {
    next LINE;
  }
  if ($line !~ /^([-\w]+)\s+(\d+)/) {
    die "did not match ($line)";
  }
  print("Got ($line)\n");

  $board_id_to_name_map{$2} = $1;
}

my $hwdef_dir = "libraries/AP_HAL_ChibiOS/hwdef";
my $dh = DirHandle->new($hwdef_dir);
while (defined (my $de = $dh->read())) {
  foreach my $filetype ("hwdef.dat", "hwdef-bl.dat") {
    my $filepath = "$hwdef_dir/$de/$filetype";
    if (! -e $filepath) {
      next;
    }
    my $content = "";
    my $fh = FileHandle->new($filepath);
    while (defined (my $line = <$fh>)) {
      $content .= $line;
    }
    $fh->close();
    if ($content !~ s/^(APJ_BOARD_ID\s+)(\d+)/$1$board_id_to_name_map{$2}/m) {
      next;
    }
    if (not defined $board_id_to_name_map{$2}) {
      my %known_missing = (
	56 => 1,
      );
      if (exists($known_missing{$2})) {
	next;
      }
      die "Number $2 not found";
    }
    print("$content\n");
    my $fh = FileHandle->new($filepath, O_WRONLY|O_TRUNC);
    $fh->write($content);
    $fh->close();
  }
}
```

2025-02-28 05:45 UTC, peterbarker commented
This is a no-compiler-output change

2025-03-03 22:37 UTC, tridge requested changes
just needs update to the "# board ID for firmware load" comment I think

2025-03-03 22:37 UTC, tridge commented on libraries/AP_HAL_ChibiOS/hwdef/ARK_CANNODE/hwdef.dat
>  # board ID for firmware load
I think we should add the words "see Tools/AP_Bootloader/board_types.txt" to the comment in each of these hwdef.dat, as I know people get confused about where these come from

2025-03-03 23:49 UTC, merged