Feature/docker update
ArduPilot/ardupilot pull request #24715
Opened 2023-08-21 10:01 UTC by khancyr

switch github action workers to latest ubuntu (22.04) : impact only test that aren't into a container so esp32 build

Change our docker container to Ubuntu 22.04, this brings :
- gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 for SITL build and all testing as this is more in sync with developpers environements and newcomers.
- remove arm-none-eabi-gcc6 from the container as we are using gcc-10 as default toolchain now and don't use gcc6 on test
- move to clang-14
- update flake8 to flake8==6.1.0 to match new install and install script, so it will need some fixing on our master branch

2023-08-21 20:32 UTC, khancyr commented
legit cacche workflow error, need new parser on 22.04. will fix this

2023-08-23 08:14 UTC, tridge requested changes

2023-08-23 08:14 UTC, tridge commented on .github/workflows/test_sitl_copter.yml
> +    runs-on: ubuntu-latest
probably better to say ubuntu-22.04

2023-08-23 08:14 UTC, tridge commented on Tools/autotest/arducopter.py
> +            if type(defaults) is not list:
should is isinstance(defaults,list)

2023-08-23 08:14 UTC, tridge commented on Tools/autotest/arduplane.py
> +            if type(defaults) is not list:
isinstance()

2023-08-23 08:14 UTC, tridge commented on Tools/autotest/autotest.py
> +            if type(success) is tuple:
isinstance()

2023-09-06 07:15 UTC, tridge approved these changes

2023-09-06 21:48 UTC, merged