AP_HAL_ChibiOS: Update readme for RADIX2HD
ArduPilot/ardupilot pull request #24724
Opened 2023-08-21 23:01 UTC by mluessi

Updated the readme for the RADIX2HD target with better instruction for how to obtain or create firmware files.

Also changed SERIAL4 to ESC telemetry, as this is now the default.

2023-08-21 23:03 UTC, mluessi commented
@Hwurzburg this should be helpful for the wiki page. Please let me know if anything is unclear.

2023-09-03 21:08 UTC, Hwurzburg requested changes
yes...looking good..a few nits//..but the download site still has no ArduPilot firmware so until that is in place, I cant post the wiki...but will work on the wip in the meantime

2023-09-03 21:08 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/RADIX2HD/README.md
> +Make sure you download the file for the "RADIX2HD" target. The ELF file for ArduCopter
```suggestion
Make sure you download the file for the "RADIX2HD" target. For example, the ELF file for ArduCopter
```

2023-09-03 21:08 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/RADIX2HD/README.md
> +is called "arducopter.elf".
```suggestion
is called "arducopter.elf". At this time only the 4.5 ("latest") versions are available.
```

2023-09-03 21:08 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/RADIX2HD/README.md
> +After installing it, you can use the following command to convert the "arducopter.elf"
```suggestion
After installing it, you can use the following command to convert the "arducopter.elf" (or other vehicle elf file)
```

2023-09-03 21:08 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/RADIX2HD/README.md
```suggestion
other vehicles can be built, but the RADIX2HD is targetted primarily for copter applications.
```

2023-09-06 20:34 UTC, mluessi commented
@Hwurzburg  thanks for the comments. I included them.

2023-09-11 17:33 UTC, Hwurzburg approved these changes

2023-09-11 17:55 UTC, Hwurzburg commented
@mluessi you need to squash to one commit for the AP_HAL_ChibiOS library

also, what uart RX is the DJI connector's "SBUS" pin really connected to? figure show UART7, but there is no UART7

2023-10-21 13:24 UTC, mluessi commented
@Hwurzburg please excuse the delay. I just went over this again, made some edits and squashed the commits. 

Note that support for it is now included in the 4.4 version, so I removed the part where it said it was only supported in 4.5. 

Support for UART7 is being added in #24485

2024-06-05 01:15 UTC, peterbarker commented
@Hwurzburg OK to merge this?

2024-06-06 12:18 UTC, Hwurzburg approved these changes

2024-06-10 23:11 UTC, merged