AP_Mount: Siyi absolute zoom simplification
ArduPilot/ardupilot pull request #24795
Opened 2023-08-28 11:31 UTC by rmackay9

Siyi's recent firmware for the A8 includes absolute zoom control so we can remove the simple absolute-to-rate-zoom controller we required previously.

It seems this addition was made to Siyi firmware ver 1.3 or 1.4 (released July 2023).  The latest firmware is ver 1.5 (released Aug 2023).

This has been tested on the A8 but still needs testing on ZR10 (it should be fine)

2023-08-28 20:26 UTC, khanasif786 commented
@rmackay9 , tested on my zr10.

2023-08-29 01:36 UTC, tridge requested changes

2023-08-29 01:36 UTC, tridge commented on libraries/AP_Mount/AP_Mount_Siyi.cpp
> +    gcs().send_text(MAV_SEVERITY_INFO, "Siyi: send zoom mult int:%u frac:%u",(unsigned)intpart, (unsigned)fracpart);
is this needed?

2023-08-29 01:38 UTC, rmackay9 commented
As discussed on the call, I'll merge after removing the silly debug that I forgot to remove after testing.

2023-08-29 01:40 UTC, rmackay9 commented on libraries/AP_Mount/AP_Mount_Siyi.cpp
> +    gcs().send_text(MAV_SEVERITY_INFO, "Siyi: send zoom mult int:%u frac:%u",(unsigned)intpart, (unsigned)fracpart);
oops, removed, thanks!

2023-08-30 07:00 UTC, merged

2023-08-30 07:01 UTC, rmackay9 commented
This was failing the Rover do-set-reverse autotest but it's hard to believe that this PR could be the cause so merged!