AP_DDS: use /tf and /tf_static instead of /ap/tf and /ap/tf_static
ArduPilot/ardupilot pull request #24819
Opened 2023-08-30 16:23 UTC by pedro-fuoco

This PR is part of a group of PRs with focus on eliminating the excessive remaps in `ardupilot_gz`, `AP_DDS` and `ardupilot_ros`

https://github.com/ArduPilot/ardupilot_gz/pull/27
https://github.com/ArduPilot/ardupilot_ros/pull/14

2023-09-01 18:32 UTC, pedro-fuoco commented on libraries/AP_DDS/dds_xrce_profile.xml
> +    <name>rt/tf_static</name>
Fair point! I will just change `/ap/tf` to `/tf` for now, since it is a subscriber and the data is not coming from `AP_DDS`

2023-09-01 18:51 UTC, Ryanf55 approved these changes

2023-09-01 18:52 UTC, Ryanf55 requested changes

2023-09-01 18:52 UTC, Ryanf55 commented on libraries/AP_DDS/dds_xrce_profile.xml
> +    <name>rt/tf</name>
Update the README if you change topics please.

2023-09-01 19:16 UTC, Ryanf55 approved these changes
LGTM. Squash and I'll mark merge on CI pass..

2023-09-02 08:15 UTC, srmainwaring approved these changes

2023-09-05 02:30 UTC, merged