SITL Params for GPS_NUMSATS and GPS_BYTELOSS
ArduPilot/ardupilot pull request #24814
Opened 2023-08-29 18:09 UTC by antholuo

No output yet (will update when I get it up), very small PR just making sure I'm doing this right.

Not sure on when "USER: Advanced" is needed either.

2023-08-30 00:50 UTC, peterbarker requested changes
This should be just two commits:
`SITL: document SIM_GPS_BYTELOS and SIM_GPS_NUMSATS` and
`Tools: document SIM_GPS_BYTELOS and SIM_GPS_NUMSATS` and

You can do this by (see https://ardupilot.org/dev/docs/git-interactive-rebase.html):
 - making a backup of your git directory
 - making sure everything is committed
 - git checkout master
 - git pull
 - git checkout ALUO_SITL_params
 - git rebase -i master
 - a text  editor should pop up
 - change "pick" on the first line to "r" in the editor
 - change "pick" on all subsequent lines to "f"
 - save the file and exit the editor
 - a text editor should pop up
 - change the commit message to "document SIM_GPS_BYTELOS and SIM_GPS_NUMSATS"
 - save the file and quit the editor
 - ./Tools/gittools/git-subsystems-split
 - git push -f YOURREMOTENAME

2023-08-30 00:50 UTC, peterbarker commented on libraries/SITL/SITL.cpp
> +    // @Description: Percent of packages lost from GPS 1
```suggestion
    // @Description: Percent of bytes lost from GPS 1
```

2023-08-30 00:50 UTC, peterbarker commented on libraries/SITL/SITL.cpp
> +    // @Description: Percent of packages lost from GPS 2
```suggestion
    // @Description: Percent of bytes lost from GPS 2
```

2023-08-30 02:34 UTC, peterbarker requested changes
@antholuo need to do the `./Tools/gittools/git-subsystems-split` step

2023-08-30 04:39 UTC, peterbarker approved these changes
LGTM

2023-08-30 20:23 UTC, antholuo commented
Updated onto master & did an interactive rebase.

2023-08-30 23:51 UTC, peterbarker commented on libraries/SITL/SITL.cpp
>      AP_GROUPINFO("GPS2_BYTELOS",  33, SIM,  gps_byteloss[1],  0),
> Noticed that for GPS2 it is `GPS2_BYTELOS` while for GPS1 it is `GPS_BYTELOSS`.
> 
> wanted to confirm this is intended?

parameter-name-length limit :-(

2023-08-30 23:52 UTC, peterbarker requested changes

2023-08-30 23:52 UTC, peterbarker commented on libraries/SITL/SITL.cpp
> +    // @Param: GPS_BYTELOSS
```suggestion
    // @Param: GPS_BYTELOS
```

2023-08-31 03:18 UTC, peterbarker approved these changes

2023-08-31 06:58 UTC, merged

2023-08-31 06:58 UTC, peterbarker commented
Merged, thanks!