AP_L1_Control: check vehicle yaw (heading) and ground track agree
ArduPilot/ardupilot pull request #24834
Opened 2023-08-31 21:45 UTC by magate

## Context
It appears that the L1 navigation controller assume the vehicle heading (yaw) is always in a direction that will close the distance to the desired ground track between waypoints.

In the case of an aircraft flying into a large headwind (higher than `TRIM_ARSPD_CM`), the controller will begin to swing between left and right roll.

This is possibly related to: https://github.com/ArduPilot/ardupilot/issues/20080 ; however, this is more of a corner case than general wrapping of the calculation.

### SITL quadplane with 30 m/s wind from 180 deg
**SITL command from top level directory**: `python ./Tools/autotest/sim_vehicle.py --vehicle ArduPlane --out=tcpin:localhost:5760 --out=tcpin:127.0.0.1:14550 --frame quadplane -D -w`

**Waypoints**: [canberra_180.txt](https://github.com/ArduPilot/ardupilot/files/12490556/canberra_180.txt)
![image](https://github.com/ArduPilot/ardupilot/assets/69254089/34d59384-9250-449a-931e-3730d04c116c)

**BIN log (remove .txt extension)**:
[canberra_left_hand_180_baseline_30wind.BIN.txt](https://github.com/ArduPilot/ardupilot/files/12490563/canberra_left_hand_180_baseline_30wind.BIN.txt)

![image](https://github.com/ArduPilot/ardupilot/assets/69254089/82cbde4a-7294-48c1-8cce-9e6a73e8b248)
_Figure: Roll begins commanding left and right when GPS speed changes direction. GPS speed is always positive, zero indicates where the direction changed._

![image](https://github.com/ArduPilot/ardupilot/assets/69254089/b59911f0-72a9-48a1-9fa9-da47b03c337d)
_Figure: Ground course is oscillating about north because the winds are out of 180 degrees._

## Proposal
Check that vehicle yaw (heading) is within 90 degrees of the ground track (any greater than this means we are moving away from the ground track and will not be able to close). In the event we are moving backwards, use the existing code for small groundspeeds where we use the vehicle heading to adjust the ground track path.

This will not do anything to progress the flight plan. Ideally it will keep the aircraft stable while the operator can take an appropriate course of action.

### SITL quadplane with 30 m/s wind from 180 deg
**SITL command from top level directory**: `python ./Tools/autotest/sim_vehicle.py --vehicle ArduPlane --out=tcpin:localhost:5760 --out=tcpin:127.0.0.1:14550 --frame quadplane -D -w`

**Waypoints**: [canberra_180.txt](https://github.com/ArduPilot/ardupilot/files/12490556/canberra_180.txt)

**BIN log (remove .txt extension)**:
[canberra_left_hand_180_new_30wind.BIN.txt](https://github.com/ArduPilot/ardupilot/files/12490628/canberra_left_hand_180_new_30wind.BIN.txt)

![image](https://github.com/ArduPilot/ardupilot/assets/69254089/f9763c89-a076-4623-90e8-832bf0493ee5)
_Figure: Roll remains smooth when GPS speed changes direction. GPS speed is always positive, zero indicates where the direction changed._

![image](https://github.com/ArduPilot/ardupilot/assets/69254089/0abea6aa-7c99-4d0d-87a2-2a5a5614b9d1)
_Figure: Ground course swings from 0 to 360 degrees and roll remains constant._

## Simulation results with zero wind to check behavior

A flight plan with 180 degrees waypoint difference was used to ensure this does not affect the current `_prevent_indecision(Nu)` code.

**Baseline**: https://drive.google.com/file/d/1x7_GJDk8OymB14a0-PHF1HqWN7079t4e/view?usp=drive_link
**New**: https://drive.google.com/file/d/1z0hhpeV6oGJCSEggN1ptlwXUbgpwdB5B/view?usp=drive_link

![image](https://github.com/ArduPilot/ardupilot/assets/69254089/0e8379f5-c042-46d9-ba0c-73a11b1af882)
_Figure: Baseline results. At 180 degree waypoint turn, aircraft decided left hand turn._

![image](https://github.com/ArduPilot/ardupilot/assets/69254089/56a6f3e3-433e-407d-ae6e-00848c88b5ef)
_Figure: New code results. At 180 degree waypoint turn, aircarft decided right hand turn._

## Additional simulation results
### Wind direction 270 degrees, step increase to 30 m/s
**Waypoints**: [canberra_270dir.txt](https://github.com/ArduPilot/ardupilot/files/12490705/canberra_270dir.txt)
![image](https://github.com/ArduPilot/ardupilot/assets/69254089/79f05734-0651-4d96-aeb7-c29972a1d11b)

**Baseline log (remove .txt extension)**: 
[canberra_left_hand_winddir270_30_baseline.BIN.txt](https://github.com/ArduPilot/ardupilot/files/12490708/canberra_left_hand_winddir270_30_baseline.BIN.txt)

![image](https://github.com/ArduPilot/ardupilot/assets/69254089/d6ea1e76-5086-44b6-b10f-2f27f3aca717)
_Figure: DesRoll alternates left and right when groundspeed reverses. Indicated by the zero point._

![image](https://github.com/ArduPilot/ardupilot/assets/69254089/5bda049a-7e4d-459f-a08e-65bfa194f241)
_Figure: Ground course reverses and DesRoll starts changing between left and right roll._

**New log (remove .txt extension)**: 
[canberra_left_hand_winddir270_30_new.BIN.txt](https://github.com/ArduPilot/ardupilot/files/12490721/canberra_left_hand_winddir270_30_new.BIN.txt)

![image](https://github.com/ArduPilot/ardupilot/assets/69254089/443e9172-1dab-4204-a7e4-dd49901ebbcc)
_Figure: GPS speed reverses direction (indicated by zero point) and DesRoll stays smooth._

![image](https://github.com/ArduPilot/ardupilot/assets/69254089/308bee3c-0f18-4e61-9c56-c78023acf1b4)
_Figure: Ground course reverses direcition (270 degrees to 90 degrees). DesRoll remains smooth and vehicle yaw (heading) remains constant._

2023-09-01 13:34 UTC, IamPete1 commented
I was able to provoke a fly away on the downwind leg with this patch, it got stuck using yaw and just kept flying off in a straight line.
![image](https://github.com/ArduPilot/ardupilot/assets/33176108/e2e88a7d-50be-4f19-ab8e-8c7def4d15be)

However this is what the current code does in that case, so its probably no worse.
![image](https://github.com/ArduPilot/ardupilot/assets/33176108/4ccd7129-da96-4686-a5db-e7e1bd83eaf0)

2023-09-01 13:36 UTC, IamPete1 commented on libraries/AP_L1_Control/AP_L1_Control.cpp
> +    float _groundspeed_yaw = wrap_2PI(_ahrs.groundspeed_vector().angle());
Don't need to wrap this

2023-09-01 13:41 UTC, IamPete1 requested changes
I think you would be better to just inline the function, you can do it as one line.

```
const bool moving_forwards = fabsf(wrap_PI(_groundspeed_vector.angle() - get_yaw())) < M_PI_2
```

2023-09-01 14:58 UTC, magate commented
> I was able to provoke a fly away on the downwind leg with this patch, it got stuck using yaw and just kept flying off in a straight line. ![image](https://user-images.githubusercontent.com/33176108/265035247-e2e88a7d-50be-4f19-ab8e-8c7def4d15be.png)
> 
> However this is what the current code does in that case, so its probably no worse. ![image](https://user-images.githubusercontent.com/33176108/265035428-4ccd7129-da96-4686-a5db-e7e1bd83eaf0.png)

Thanks @IamPete1 . I think I recreated the fly-away using winds from 225 degrees and 35 m/s. I am not sure how to handle this.

Very much like the inline; great suggestion.

## New baseline
**Log**: https://drive.google.com/file/d/19OVZ95or7pu-_C4tkmjALtUmGy-nLR_k/view?usp=drive_link
![image](https://github.com/ArduPilot/ardupilot/assets/69254089/71adfad3-dd32-4963-a817-90d313c6aed2)
_Figure: New baseline results with inline function. Right hand run initiated at 180deg waypoint change._

## New negative ground speed check
**Log**: https://drive.google.com/file/d/1UVu8EizHVh0lJTzI7SLUjetplMQAtP1q/view?usp=drive_link
![image](https://github.com/ArduPilot/ardupilot/assets/69254089/bf3935c4-d76d-4dce-97ca-5924f68eebdd)
_Figure: GPS speed changes direction (backwards); DesRoll remains smooth._

![image](https://github.com/ArduPilot/ardupilot/assets/69254089/9cb38cc2-92ab-4986-ae9f-501767efc32d)
_Figure: Ground course changes direction (180 degrees). DesRoll remains smooth._

2023-09-01 14:58 UTC, magate commented on libraries/AP_L1_Control/AP_L1_Control.cpp
> +    float _groundspeed_yaw = wrap_2PI(_ahrs.groundspeed_vector().angle());
Thanks.

2023-09-01 14:59 UTC, magate commented on libraries/AP_L1_Control/AP_L1_Control.cpp
> +    float _ahrs_yaw = wrap_2PI(_ahrs.get_yaw());
Excellent point. Missed that, good catch.

2023-09-01 14:59 UTC, magate commented on libraries/AP_L1_Control/AP_L1_Control.cpp
> +    }
Much cleaner. Thanks.

2023-09-01 22:49 UTC, IamPete1 approved these changes
This fixes one edge case with higher wind speed than airspeed. We still do not handle this case well but this results in more consistent behavior, I think a step in the right direction.

2023-09-05 00:06 UTC, tridge approved these changes

2023-09-05 00:07 UTC, merged