AP_Compass: Compare with string
ArduPilot/ardupilot pull request #24832
Opened 2023-08-31 16:53 UTC by muramura

If you get a string from a device, determine it by the string.

2023-09-11 02:38 UTC, peterbarker requested changes
Saves a few bytes, which is a bit of a surprise:
```
Board,AP_Periph,blimp,bootloader,copter,heli,iofirmware,plane,rover,sub
Durandal,,0,*,-8,0,,0,-8,-8
HerePro,*,,,,,,,,
Hitec-Airspeed,*,,,,,,,,
KakuteH7-bdshot,,-8,*,-8,-8,,-8,-8,-8
MatekF405,,-8,*,-8,-8,,-8,-8,-8
Pixhawk1-1M-bdshot,,-8,,-8,-8,,-8,-8,-8
f103-QiotekPeriph,*,,,,,,,,
f303-Universal,-8,,,,,,,,
iomcu,,,,,,*,,,
revo-mini,,-8,*,-8,-8,,-8,-8,-8
skyviper-v2450,,,,*,,,,,
```

The `strncmp` isn't a natural fit for this data as they're not actually null-terminated strings.  The `strncmp` saves the situation, but still, we can do better.

Please change this to use `memcmp`.  `memcmp` can be *much* more efficient than `strncmp` and is more appropriate for this buffer.

2023-09-29 09:40 UTC, khancyr requested changes
memcmp is indeed the way to go in this one.

2023-09-29 09:40 UTC, khancyr commented on libraries/AP_Compass/AP_Compass_HMC5843.cpp
> +    if (strncmp((const char*)id, "H43", sizeof(id)) != 0) {
```suggestion
    if (memcmp(id, "H43", 3) != 0) {
```

2024-09-22 03:23 UTC, peterbarker commented
Replaced by https://github.com/ArduPilot/ardupilot/pull/28191

2024-09-22 03:23 UTC, closed without merging