DroneCAN: make himark servos an optional build item
ArduPilot/ardupilot pull request #24852
Opened 2023-09-02 06:40 UTC by tridge

this came out of this PR for 4.4.1:
https://github.com/ArduPilot/ardupilot/pull/24713

2023-09-03 09:59 UTC, peterbarker requested changes

2023-09-03 09:59 UTC, peterbarker commented on Tools/scripts/build_options.py
> +    Feature('Actuators', 'HimarkServo', 'AP_DRONECAN_HIMARK_SERVO_SUPPORT', 'Enable Himark DroneCAN servos', 0, None),
```suggestion
    Feature('Actuators', 'HimarkServo', 'AP_DRONECAN_HIMARK_SERVO_ENABLED', 'Enable Himark DroneCAN servos', 0, None),
```

2023-09-03 09:59 UTC, peterbarker commented on Tools/scripts/build_options.py
> +    Feature('Actuators', 'HobbywingESC', 'AP_DRONECAN_HOBBYWING_ESC_SUPPORT', 'Enable Hobbywing DroneCAN ESCs', 0, None),
```suggestion
    Feature('Actuators', 'HobbywingESC', 'AP_DRONECAN_HOBBYWING_ESC_ENABLED', 'Enable Hobbywing DroneCAN ESCs', 0, None),
```

2023-09-03 09:59 UTC, peterbarker commented on Tools/scripts/extract_features.py
> +            ('AP_DRONECAN_HOBBYWING_ESC_SUPPORT', 'AP_DroneCAN::hobbywing_ESC_update()'),
```suggestion
            ('AP_DRONECAN_HOBBYWING_ESC_SUPPORT', 'AP_DroneCAN::hobbywing_ESC_update'),
```

2023-09-04 04:39 UTC, tridge commented on Tools/scripts/build_options.py
> +    Feature('Actuators', 'HimarkServo', 'AP_DRONECAN_HIMARK_SERVO_SUPPORT', 'Enable Himark DroneCAN servos', 0, None),
done

2023-09-04 04:39 UTC, tridge commented on Tools/scripts/extract_features.py
> +            ('AP_DRONECAN_HOBBYWING_ESC_SUPPORT', 'AP_DroneCAN::hobbywing_ESC_update()'),
done

2023-09-05 00:28 UTC, peterbarker approved these changes
LGTM

2023-09-06 22:44 UTC, merged