AP_HAL_ChibiOS: Fix H7 PLL1 Q clock for 480 MHz clock (4.4 backport)
ArduPilot/ardupilot pull request #24896
Opened 2023-09-06 20:56 UTC by mluessi

There is a mistake in the H7 clock tree that results in an incorrect clock for the FDCAN peripheral when a core clock of 480 MHz is used. This changes the PLL1 Q divider such that the 80 MHz clock needed for FDCAN can be generated.

Note: The same values for `STM32_PLL1_DIVQ_VALUE` are also used in the `master` branch.

2023-09-06 21:28 UTC, andyp1per approved these changes
I agree this is the right change. I removed it from the original backport because it made it almost impossible to prove binary equivalence. Hopefully now that this change is on its own this can go in. Note that the clock trees in general were changed in master, so it simply being in master is not quite a good enough reason - but in this instance it is obviously correct. Hopefully @tridge agrees

2023-09-06 21:35 UTC, mluessi commented
@andyp1per thanks :)

2023-09-07 09:08 UTC, andyp1per requested changes
@mluessi I discussed this with @tridge and what he would like you to do for 4.4 is simply put in a ```#ifndef STM32_PLL1_DIVQ_VALUE``` and then define the alternative in your hwdef - that way we can guarantee no impact on other boards in 4.4

2023-09-07 13:34 UTC, mluessi commented
@andyp1per yes, that is definitely safer. I changed the commit and force-pushed the branch.

2023-09-07 13:39 UTC, andyp1per approved these changes

2023-09-07 14:11 UTC, andyp1per commented
> I assume this should also go to plane 4.4 as well?

yes

2023-09-09 08:50 UTC, tridge commented
We just need to check if any other periphs are using this divq output
Check the mcuconf for H7 and see what else uses this clock
I

2023-09-09 10:56 UTC, andyp1per commented
The other peripherals using this are:

SDMMC
SPDIF
FDCAN
SPI123
SAI23
SAI1
SAI4B
SAI4A

2023-09-09 19:26 UTC, mluessi commented
So currently all those peripherals have a 96 MHz clock on H7's that use the 480 MHz core clock and 80 MHz on H7's that use 400 MHz. Is this intended or would  it be better to adopt the fix I first had where the divider is changed to 12 and the peripheral clock would always be 80 MHz?

2023-09-09 20:47 UTC, tridge approved these changes

2023-09-09 20:48 UTC, merged

2023-09-09 21:18 UTC, andyp1per commented
> So currently all those peripherals have a 96 MHz clock on H7's that use the 480 MHz core clock and 80 MHz on H7's that use 400 MHz. Is this intended or would it be better to adopt the fix I first had where the divider is changed to 12 and the peripheral clock would always be 80 MHz?

This is why I changed the clock tree in master