SITL: Document Airspeed Params
ArduPilot/ardupilot pull request #25005
Opened 2023-09-16 17:18 UTC by antholuo

Unsure how to document ARSPD2 Params

2023-09-16 17:19 UTC, antholuo commented on Tools/autotest/common.py
>              "SIM_ARSPD2_FAILP",
For ex, ARSPD2_FAIL exists in common.py but doesn't explicitly exist in SITL.cpp

2023-09-16 17:27 UTC, IamPete1 commented on libraries/SITL/SITL.cpp
> +    // @Param: ARSPD_FAILP
The prefix is in the wrong spot, This should just be FAILP. The one level up where these are included you add the prefix. Like gripper for example. 

https://github.com/ArduPilot/ardupilot/blob/9b0639557338792356f50e39046e216d215be32b/libraries/SITL/SITL.cpp#L217-L219

Then the documentation should work for both airspeed 1 and 2.

2023-09-17 10:07 UTC, peterbarker requested changes

2023-09-17 10:07 UTC, peterbarker commented on libraries/SITL/SITL.cpp
> +    // @Param: FALIP
```suggestion
    // @Param: FAILP
```

2023-09-17 10:07 UTC, peterbarker commented on libraries/SITL/SITL.cpp
> +    // @Group: ARPSD_
```suggestion
    // @Group: ARSPD_
```

2023-09-17 23:03 UTC, peterbarker requested changes
OK, so the parser isn't coping with the setup for these parameters, and I don't think it will be easy to make it do so.

It believes that anything that looks like a parameter or group in this file is at the same level.  So here we get `SIM_PITOT`, `SIM_FAILP` etc etc.  The `ARSPD` group parameter declaration comment is missing `@Path`, and we can't specify "this file" in there as that's infinite recursion.  It's the @Path and recursion thing which would tack on `ARSPD_` to the parameter name base to get `SIM_ARSPD_FAILP`.

Easiest fix is to move the definition of `const AP_Param::GroupInfo SIM::AirspeedParm::var_info[] = {` into a SITL_airspeed.cpp into `AP_HAL_SITL/sitl_airspeed.cpp` - and I don't think that's a terrible thing.  Then just add `@Path` to point to that file.

2023-10-04 21:18 UTC, merged

2023-10-04 21:18 UTC, peterbarker commented
Merged, thanks!