Correct prescaler calculation for BLHeli_S
ArduPilot/ardupilot pull request #25009
Opened 2023-09-17 11:31 UTC by andyp1per

2023-09-17 12:08 UTC, Hwurzburg commented
how does this error impact users? what versions of firmware? what conditions?

2023-09-17 12:24 UTC, andyp1per commented
It's only a bug in master - currently in master BLHeli_S motors will not spin due to this issue

2023-09-19 02:25 UTC, tridge commented
@andyp1per does this explain the de-syncs you've seen?

2023-09-19 06:45 UTC, andyp1per commented
@tridge - no, this only affects 4.5 and I have been flying 4.4

2023-09-19 06:45 UTC, andyp1per commented
also my Chimera has BLHeli32 which is unchanged

2023-09-19 22:19 UTC, tridge requested changes

2023-09-19 22:19 UTC, tridge commented on libraries/AP_HAL/RCOutput.cpp
> +uint32_t AP_HAL::RCOutput::calculate_bitrate_prescaler(uint32_t timer_clock, uint32_t target_frequency, bool at_least_freq)
the callers pass in an is_dshot. The test suite sometimes passes true and sometimes false for this variable. So the users of this function don't seem to match the test suite or the new function form?

2023-09-19 22:20 UTC, tridge commented
if this is supposed to be based on the ESC type parameter then I don't see how this parameter gets into the function that is changing

2023-09-20 07:35 UTC, tridge approved these changes

2023-09-20 07:35 UTC, merged