attempt 1 at a fix
ArduPilot/ardupilot pull request #25000
Opened 2023-09-16 16:31 UTC by antholuo

Attempting to fix https://github.com/ArduPilot/ardupilot/issues/11284

Not sure if I'm doing this correctly since it looks like the TurnRate and GuidedLoiter have been fixed already?

Unsure what the comment on LAT_ACCEL means....

2023-09-18 00:18 UTC, rmackay9 commented
Hi @antholuo,

This looks correct to me, thanks!  If possible could you test it in SITL?

The heading-and-speed control isn't used very much so the only way to get the vehicle into this mode is to send a COMMAND_LONG (or COMMAND_INT) with the command field set to MAV_CMD_SET_YAW_SPEED (or something like that).

We've got other commands documented on our [Rover mavlink interface page](https://ardupilot.org/dev/docs/mavlink-rover-commands.html) but not this one.

2023-09-19 02:42 UTC, antholuo commented
Hi @rmackay9 !

I'm having a bit of trouble understanding how to send the command (MAV_CMD_SET_YAW_SPEED and MAV_CMD_SET_NAV_YAW_SPEED)?

It's saying that the command is unknown 
<img width="539" alt="image" src="https://github.com/ArduPilot/ardupilot/assets/45152791/e3471c1d-61c1-4ccf-8b67-ebd35d9d6f50">

But the command should be of this format: https://mavlink.io/en/messages/common.html#MAV_CMD_NAV_SET_YAW_SPEED?

2023-09-19 03:21 UTC, rmackay9 commented
Hi @antholuo,

if you're using mavproxy then I think the easiest way is to use the "long" command.  Another possibility is to type "module load message" and then use the "message" command.  simply typing one of these commands should lead to MAVProxy display a simple "usage" of the command.  Beyond that it could be good to look at examples of how these are used on some of the [AP MAVLink Interface wiki pages](https://ardupilot.org/dev/docs/mavlink-commands.html).

2023-10-02 02:08 UTC, antholuo commented
@rmackay9 I ran this through the SITL a few times, and it seems that sending a move command before the previous command has finished will cause the rover to drift quite far from origin: https://youtu.be/yfZ7hb4EYbQ

Doing this on my branch waiting between commands results in a small position error, but doing this on master does not...

Any thoughts on why that might be?
![image](https://github.com/ArduPilot/ardupilot/assets/45152791/4c11f992-943e-4349-9181-c9979624e7d4)
Rover far away from origin after multiple successive commands

![image](https://github.com/ArduPilot/ardupilot/assets/45152791/44b4deb5-5d7c-410c-98c3-81df535b7229)
Rover close, but not exactly on origin after multiple commands with wait time between them.

![image](https://github.com/ArduPilot/ardupilot/assets/45152791/3681031a-8ea6-4a0c-8a76-ba0754593e69)
Master, which shows no change in position of the rover....

2023-10-17 23:38 UTC, peterbarker requested changes
Your changes here are modifying wp_bearing, where they should be modifying nav_bearing.  We don't have a waypoint to give a bearing to, but we do have a bearing we are trying to acrhieve - so nav_bearing, not wp_bearing

2023-10-17 23:38 UTC, peterbarker commented on Rover/mode_guided.cpp
> +        return _desired_yaw_cd;
This must return centidegrees (see clause above this one)

2024-09-22 22:46 UTC, closed without merging