AP_GPS:SBF using COMx data response as actual COM port id value inste…
ArduPilot/ardupilot pull request #25036
Opened 2023-09-19 17:38 UTC by Huibean

SBF using COMx data response as actual COM port id value instead of using AP_GPS instance id
ie. Connect Mosaic UART2 with ardupilot GPS1, the code will config COM 1 instead COM 2(actual port) since using GPS instance id

2023-10-02 16:55 UTC, WickedShell requested changes
It doesn't use the instance id, it uses the `GPS_COM_PORT` parameter, which you are expected to set to match the used com port on the GPS.

This PR reduces the amount of configuration a user needs to do, however it doesn't seem like it would wake up an unassigned UART reliably. Also since the first command run is a setting of the baud rate this PR as it currently stands would change a different random COM port to be the wrong settings potentially. We would need the PR to include an extra set of steps that gets this ID first before ever sending any commands that change a port related setting.

2023-10-03 08:02 UTC, Huibean commented
Hi I have test, it should be working good, the first SSSSSSSSSS/n wake-up
command didn’t change any setting, and I think the Steam id need to be a AP
param in stead of the SBF COM port id

WickedShell ***@***.***>于2023年10月3日 周二00:55写道：

> ***@***.**** requested changes on this pull request.
>
> It doesn't use the instance id, it uses the GPS_COM_PORT parameter, which
> you are expected to set to match the used com port on the GPS.
>
> This PR reduces the amount of configuration a user needs to do, however it
> doesn't seem like it would wake up an unassigned UART reliably. Also since
> the first command run is a setting of the baud rate this PR as it currently
> stands would change a different random COM port to be the wrong settings
> potentially. We would need the PR to include an extra set of steps that
> gets this ID first before ever sending any commands that change a port
> related setting.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ArduPilot/ardupilot/pull/25036#pullrequestreview-1653141907>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACY7IIL7WNWTVTMHXZPSOODX5LWZDAVCNFSM6AAAAAA46VK6PKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMNJTGE2DCOJQG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-12 18:02 UTC, WickedShell commented
What ensures that you haven't manipulated the wrong COM port after the wakeup command? I'm still not a huge fan of grabbing the port id like this, as there is no checksum, and it's not read once.

The assumption on stream is that ArduPilot gets first priority in the system. This is particularly emphasized because we are changing receiver dynamics, not just the rate of what comes out the port. The COM id was parameterized because of hardware changes meant that we had to cope with a wider range, and it isn't unreasonable for a user to know.

2023-10-13 01:39 UTC, Huibean commented
Yes, there is no checksum with the com port string

2023-10-13 01:39 UTC, closed without merging