Support high-resolution sampling on ICM4xxxx IMUs
ArduPilot/ardupilot pull request #25069
Opened 2023-09-21 20:03 UTC by andyp1per

2023-09-23 19:12 UTC, andyp1per commented
Flown on my 5" quad no issues

2023-09-24 08:54 UTC, tridge commented
@andyp1per I'd like a discuss a bit, particularly regarding testing on all the v3 variants, and if we need the parameter or should just always enable

2023-09-27 08:37 UTC, tridge requested changes
a few changes:
 - needs to be under an #if, enabled in hwdef.dat
 - needs careful testing on all supported IMUs
 - need to test with raw 32kHz fifo logging to ensure this is really a benefit, with logging of the raw 32bit signed number
 - we need to check if enabling high res changes gyro or accel offsets

2023-10-18 07:20 UTC, tridge requested changes
moving to an enum class will help

2023-10-18 07:20 UTC, tridge commented on libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.cpp
>      default:
better without the default

2023-10-18 07:20 UTC, tridge commented on libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.cpp
> -        accel_scale = (GRAVITY_MSS / 1024);
this looks like it changes accel_scale for 40609

2023-10-19 16:28 UTC, andyp1per commented on libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.h
> +    bool highres_sampling;
Fixed

2023-10-25 08:22 UTC, tridge approved these changes

2023-10-25 08:23 UTC, merged