Fix GCS DPS310 HWID issue
ArduPilot/ardupilot pull request #25087
Opened 2023-09-24 08:35 UTC by lida2003

[DPS310 baro on I2C](https://discuss.ardupilot.org/t/dps310-baro-on-i2c/65179)

DPS310 was very similar with DPS280.
And current driver do support DPS310, but GCS was hard to tell if correct chip is founded.

So just make this work for GCS(Mission planner).

![1c2271790b6bb2f2786739e713be5789217e7f35](https://github.com/ArduPilot/ardupilot/assets/1296171/93bd1cd4-8a83-426e-9763-1f2c1271cbb4)

2023-09-25 08:06 UTC, peterbarker requested changes
Commit message needs to be prefixed with `AP_Baro: `

2023-09-25 09:58 UTC, peterbarker approved these changes
LGTM

2023-09-26 01:33 UTC, peterbarker commented
https://github.com/ArduPilot/ardupilot/pull/25099

2023-09-26 01:34 UTC, tridge commented
this can go into master now with the PR from @peterbarker then add this in a later 4.4.x release

2023-10-11 22:20 UTC, closed without merging