AP_EFI: Rate limit the megasquirt driver
ArduPilot/ardupilot pull request #25095
Opened 2023-09-25 19:21 UTC by WickedShell

This fixes it up so that the driver actually works on things like AP_Periph that poll at a high rate. This was never a problem with the main firmware as EFI was run at a lower rate, but on AP_Periph this was much to fast. This lead to spamming fresh requests and keeping the buffer completly stuffed with requests. To compound it, the EFI device would start over when there was a fresh request, and eventually our buffer writes become corrupted leading to bad checksums, and a complete failure of the comms. This prevents that situation from happening.

Tested with a HFE engine, and custom AP_Periph.

2023-09-26 20:19 UTC, magicrub requested changes

2023-09-26 20:19 UTC, magicrub commented on libraries/AP_EFI/AP_EFI_Serial_MS.cpp
> +        ((now - last_request_ms > 90) && (port->available() == 0))) { // we requested something over 90 ms ago, but didn't get any data
```suggestion
    const uint32_t last_request_delta = (now - last_request_ms);
    const uint32_t available = port->available();
    if (((last_request_delta > 150) && (available > 0)) || // nothing in our input buffer 150 ms after request
        ((last_request_delta > 90) && (available == 0))) { // we requested something over 90 ms ago, but didn't get any data
```

2023-09-28 18:21 UTC, WickedShell commented on libraries/AP_EFI/AP_EFI_Serial_MS.cpp
> +        ((now - last_request_ms > 90) && (port->available() == 0))) { // we requested something over 90 ms ago, but didn't get any data
Done.

2023-10-03 00:31 UTC, tridge approved these changes

2023-10-03 00:32 UTC, merged