Copter: Make ALT HOLD mode an option
ArduPilot/ardupilot pull request #25123
Opened 2023-09-27 21:47 UTC by muramura

Many microdrones weighing less than 100 g are flying in Japan.
Microdrones are flying with ArduPilot.
The base of this micro drone is without GPS and barometric sensor.
For this drone, a barometric sensor is not essential.
I make ALT HOLD mode an option.

ARDUWHOOP
https://youtu.be/eG3bwLJz_a8?si=Joaq2iIjQX6ZKcVm

2023-09-27 22:01 UTC, peterbarker reviewed
These should all go in into `build_options.py`

2023-09-27 22:01 UTC, peterbarker commented on ArduCopter/mode_althold.cpp
> +#endif
```suggestion
#endif  // MODE_ALTHOLD_ENABLED
```

2023-09-28 00:36 UTC, muramura commented
@peterbarker saan.  Added ALTHOLD to build_options.py.

2023-11-02 09:12 UTC, khancyr approved these changes
LGTM
@peterbarker ok to merge ?

2023-11-02 09:23 UTC, peterbarker requested changes
the definition for the class should be commented out in `mode.h`

2023-11-02 12:01 UTC, Hwurzburg requested changes
missing extract_features  change?

2024-09-12 12:55 UTC, peterbarker commented
Ping @muramura .

This needs a rebase.

Henry's pointed out build_options.py would need a change.

I pointed out the class definition shouldn't be present.

Did you still want to pursue this?

2025-04-30 04:52 UTC, peterbarker commented
No response from author.  I don't mind the change, but this is now conflicting.

Please re-open after resolving issues if you want to progress.

2025-04-30 04:52 UTC, closed without merging