AP_Scripting: add missing defines to build on Periph
ArduPilot/ardupilot pull request #25183
Opened 2023-10-04 17:36 UTC by IamPete1

This work is sponsored by Spektreworks.

This adds defines such that scripting can run on periph with most everything else disabled, obviously we already run on vehicles with everything else enabled, I have not tested all possible combinations in between.

With everything else turned off the flash cost is around 100k but as you add back in more library's the extra bindings means the over head increases. Its only really practical with 512kB flash or more. To use you would have to enable romfs and embed the script into the firmware. 

I have tested a "hello world" script on a CubeBlack periph heavy build.

2023-10-04 21:05 UTC, peterbarker requested changes
I reviewed a single patch...

2023-10-04 21:05 UTC, peterbarker commented on libraries/AP_Scripting/AP_Scripting_config.h
> +    #if !(AP_FILESYSTEM_FATFS_ENABLED || AP_FILESYSTEM_ROMFS_ENABLED)
```suggestion
    #if AP_FILESYSTEM_FILE_READING_ENABLED
```

2023-10-04 21:05 UTC, peterbarker commented on libraries/AP_Scripting/AP_Scripting_config.h
> +    #if !AP_FILESYSTEM_SYS_ENABLED
What's this one here for?

2023-10-05 21:16 UTC, IamPete1 commented on libraries/AP_Scripting/AP_Scripting_config.h
> +    #if !AP_FILESYSTEM_SYS_ENABLED
I have no idea... fixed.

2023-10-05 21:17 UTC, IamPete1 commented on libraries/AP_Scripting/AP_Scripting_config.h
> +    #if !(AP_FILESYSTEM_FATFS_ENABLED || AP_FILESYSTEM_ROMFS_ENABLED)
done, thanks.

2023-10-09 23:35 UTC, rmackay9 commented
Looks great but maybe we need a simple autotest to be sure we get a warning when a new binding breaks this again?

2023-10-16 23:23 UTC, tridge approved these changes

2023-10-16 23:23 UTC, merged