add board canzero
ArduPilot/ardupilot pull request #25206
Opened 2023-10-08 05:05 UTC by karu2003

add board canzero small RPi board with CAN bus. https://github.com/ipmgroup/canzero-board_hardware

2023-10-22 00:25 UTC, peterbarker requested changes
@karu2003 the commit list needs cleaning up; should have a single commit per logical ArduPilot section - se "Preparing commits" here: https://ardupilot.org/dev/docs/submitting-patches-back-to-master.html

2023-10-22 00:26 UTC, peterbarker requested changes

2023-10-22 00:26 UTC, peterbarker commented on .github/workflows/test_linux_sbc.yml
> +            canzero
```suggestion
            canzero,
```

... to simplify future diffs

2023-10-25 17:39 UTC, magicrub commented
@karu2003 instead of merge, please use rebase.
try ```git rebase ardupilot/master``` or ```git rebase origin/master```, whichever you have pointing to this repo

2023-11-20 18:09 UTC, karu2003 commented
Is there any hope that the PR will be accepted?

2023-11-20 19:10 UTC, lucasdemarchi commented
@karu2003  why are there so many updates to this PR? Is this working on the HW and ready to be reviewed?

2023-11-20 19:49 UTC, karu2003 commented
> @karu2003 why are there so many updates to this PR? Is this working on the HW and ready to be reviewed?

This is working HW.  https://www.youtube.com/watch?v=7-TG8SYGsUo   https://www.youtube.com/watch?v=TGlhYWIwu8A

2023-11-22 19:35 UTC, magicrub commented
You don't need to constantly rebase. When it merges it will be on top

2023-11-28 20:28 UTC, lucasdemarchi commented
@karu2003  see https://github.com/ArduPilot/ardupilot/pull/25206#pullrequestreview-1691351416
You still need to split this commit to be acceptable and as @magicrub said, no need to keep rebasing it.

Let me know if you know how to do it, otherwise I can help.

2023-11-29 06:29 UTC, karu2003 commented
> @karu2003 see [#25206 (review)](https://github.com/ArduPilot/ardupilot/pull/25206#pullrequestreview-1691351416) You still need to split this commit to be acceptable and as @magicrub said, no need to keep rebasing it.
> 
> Let me know if you know how to do it, otherwise I can help.

Fine. I won't rebase and push in this branch. But. I made one commit as you asked. With all the proposed changes.

2023-12-04 15:43 UTC, lucasdemarchi commented
@karu2003 just pushed here the same changes you had, but with separate commits per dir as required by Ardupilot. I also cleaned up some whitespaces that do not follow the coding style, but otherwise the diff is empty: https://github.com/ArduPilot/ardupilot/compare/ed4faf351f67d9a2a7740dc514a5ffba8f53d002..ff45b28f11b96efee4bbde28450d8d4889a19652

2023-12-04 15:43 UTC, lucasdemarchi approved these changes

2023-12-05 06:16 UTC, karu2003 commented
> @karu2003 just pushed here the same changes you had, but with separate commits per dir as required by Ardupilot. I also cleaned up some whitespaces that do not follow the coding style, but otherwise the diff is empty: https://github.com/ArduPilot/ardupilot/compare/ed4faf351f67d9a2a7740dc514a5ffba8f53d002..ff45b28f11b96efee4bbde28450d8d4889a19652

thank you more, I understood the ideology of your rules. I'll take this into account in the next RP.

2023-12-05 13:41 UTC, merged

2023-12-07 01:15 UTC, rmackay9 commented
By the way, recently we've had @Hwurzburg also approve (or at least review) our new board PR to AP.  The reason is that he nearly always turns up a problem as part of his effort to get new boards on the wiki.  This is Linux so not a blocker but you may want to add HenryW as a review in the future.