Copter: choose RC channel for Transmitter Based Tuning
ArduPilot/ardupilot pull request #25203
Opened 2023-10-07 11:19 UTC by be-ska

This PR add the ability to choose which RC channel controls the Transmitter Based Tuning, instead of the hard coded channel 6.
If a user want to use channel x for transmitter based tuning, the parameter RCx_OPTION should be set to 177 (Transmitter Tuning), as discussed in issue #25186.

The changes has been tested in SITL after setting parameters:
- `TUNE` 21
- `TUNE_MIN` 0
- `TUNE_MAX` 0.03
- `RC9_OPTION` 177

Changing the PWM value of CH8 results in different `ATC_RAT_RLL_D` values.

2023-10-07 22:04 UTC, Hwurzburg commented
why not just adopt the tx tune used by plane? adding a single vehicle aux function seems like the wrong approach to me

2023-10-07 22:22 UTC, peterbarker commented
> why not just adopt the tx tune used by plane? adding a single vehicle aux function seems like the wrong approach to me

Because that's a different issue, and Randy was opposed last time it came up.  tridge's oldest PR adds that support: https://github.com/ArduPilot/ardupilot/pull/4065

This PR adds flexibility we don't currently don't have, and the problem vexed the author of this PR enough that he made a PR to fix it.  I think this PR is well-justified.

2023-10-07 22:25 UTC, peterbarker requested changes
Looks right.  Just a stylistic thing of doing an early-return rather than complicating a compound expression.

Please state what testing has been done.

2023-10-07 22:25 UTC, peterbarker commented on ArduCopter/tuning.cpp
> +    const RC_Channel *rc_tuning = rc().find_channel_for_option(RC_Channel::AUX_FUNC::TRANSMITTER_TUNING);
```suggestion
    const RC_Channel *rc_tuning = rc().find_channel_for_option(RC_Channel::AUX_FUNC::TRANSMITTER_TUNING);
    if (rc_tuning == nullptr) {
        return;
    }
```

2023-10-07 22:25 UTC, peterbarker commented on ArduCopter/tuning.cpp
> +    if ((g.radio_tuning <= 0) || (is_zero(g2.tuning_min.get()) && is_zero(g2.tuning_max.get())) || rc_tuning == nullptr) {
```suggestion
    // exit immediately if the tuning function is not set or min and max are both zero
    if ((g.radio_tuning <= 0) || (is_zero(g2.tuning_min.get()) && is_zero(g2.tuning_max.get()))) {
```

2023-10-08 12:59 UTC, be-ska commented
@peterbarker I've applied the style fix as requested. 
At the moment I've only tested in SITL: I've tried assigning different channels changing the RCx_OPTION to 177 and it works as it supposed to: I can see the ATC_* parameters changing and the controller overshoot if setting gains too high via transmitter. I also tested the `return` when `rc_tuning == nullptr` and it works.

2023-10-08 13:17 UTC, be-ska commented
@Hwurzburg Sorry, I'm not a Plane user and I didn't know there was a different transmitter based tuning for Plane. Just my personal opinion, but I think it would be more intuitive if all the RC input settings were in the same place. This could avoid confusion: just looking at all the RCx_OPTION values, users know which transmitter inputs are enabled and for which function. So maybe also Plane could use the same RCx_OPTION value instead of the TUNE_CH parameter.

2024-06-14 16:07 UTC, tpwrules commented
Are you still interested in working on this? I would like it as well but it needs to be rebased and some of the comments cleaned up.

2024-07-20 13:32 UTC, be-ska commented
@tpwrules sorry for the late reply, I was quite busy on other projects this month. I can easily rebase it, but as @Hwurzburg pointed out Transmitter Tuning for Plane has a different way to choose the RC channel, so it doesn't seem right to have a different way to set the same function on Copter.

2024-07-21 23:36 UTC, rmackay9 commented
I agree with others that this PR looks correct. The only change I'd recommend is that the enum used be changed to 219 because that's where we are putting the items that are really sliders/knobs instead of switches.

2024-07-22 13:59 UTC, be-ska commented
I've rebased it and changed the used enum to 219 as @rmackay9 suggested.

2024-07-22 22:59 UTC, rmackay9 approved these changes
LGTM, nice, thanks!

2024-07-23 13:52 UTC, Georacer commented
I believe we'll need a wiki update on https://ardupilot.org/copter/docs/common-transmitter-tuning.html#common-transmitter-tuning

2024-07-23 23:18 UTC, rmackay9 commented
It looks like it's failing the Ch6TuningWPSpeed autotest and [the code is here](https://github.com/ArduPilot/ardupilot/blob/master/Tools/autotest/arducopter.py#L11311).  We will just need to add a new parameter setting to the table, probably like this:

```
        self.set_parameters({
            "RC6_OPTION": 219,  #RC6 used for tuning
            "TUNE": 10,  # 10 is waypoint speed
            "TUNE_MIN": 0.02,  # 20cm/s
            "TUNE_MAX": 1000,  # 10m/s
            "AUTO_OPTIONS": 3,
        })
```

2024-07-24 07:26 UTC, tridge commented
@be-ska this can be merged when you make the one line change in Tools/autotest/arducopter.py to set the parameter

2024-07-24 10:46 UTC, be-ska commented
Hey @tridge, I've rebased it and modified the `autotest` script, it should now pass the test

2024-07-24 23:40 UTC, merged

2024-07-24 23:40 UTC, peterbarker commented
Fantastic, thanks @be-ska !