AP_Arming: Defined by the process used
ArduPilot/ardupilot pull request #25207
Opened 2023-10-08 06:29 UTC by muramura

The array of strings is far from the actual processing used.
Define this array in the process that will use it.

2023-10-08 06:47 UTC, peterbarker commented
@muramura you're right, but the definition is right next to the definition of the array we are iterating over.

This is purposeful, as you *really* don't want these arrays to be of different length!  Note there's no assertion these are of the same length anywhere, so if you modify one you really do need to modify the other.  Having them close together in the code helps that.

2023-10-09 07:32 UTC, khancyr commented
adding a constant to remove the magic number would solve the size issue !

2023-10-09 17:59 UTC, WickedShell requested changes
This seems less useful/more confusing. The only thing I'd actually really support here is a static assert that the arrays are the same length.

2023-10-09 22:08 UTC, magicrub commented
I prefer it defined up where it is now but having all 3 using a define like @khancyr said is the better way to go.

2024-09-22 02:39 UTC, peterbarker commented
Doesn't look like a lot of love for this rearrangement.

https://github.com/ArduPilot/ardupilot/pull/25207/files makes this no longer required. (we stop using indexes, rather a little structure to relate the channel with the name)

Closing this one - thanks anyway!

2024-09-22 02:39 UTC, closed without merging