AP_RangeFinder: Add new driver for TOFSense F I2C
ArduPilot/ardupilot pull request #25268
Opened 2023-10-15 04:32 UTC by rishabsingh3003

2023-10-17 00:40 UTC, tridge requested changes

2023-10-17 00:40 UTC, tridge commented on libraries/AP_RangeFinder/AP_RangeFinder_TOFSenseF_I2C.cpp
> +        le32_t distance_mm;
can just use uint32_t, we are always little endian

2023-10-17 00:40 UTC, tridge commented on libraries/AP_RangeFinder/AP_RangeFinder_TOFSenseF_I2C.cpp
> +        reading_mm = le32toh(packet.distance_mm);
next line assumes little endian, no need to convert

2023-10-17 00:40 UTC, tridge commented on libraries/AP_RangeFinder/AP_RangeFinder_TOFSenseF_I2C.cpp
> +        start_reading();
this looks like if transfer fails, then no new start_reading() is done ever again

2023-10-17 00:41 UTC, tridge commented on libraries/AP_RangeFinder/AP_RangeFinder_TOFSenseF_I2C.cpp
> +        start_reading();
same bug in maxsonar i2c

2023-10-17 00:41 UTC, tridge commented
both nooploops should be in build_options.py

2023-10-23 23:36 UTC, tridge approved these changes

2023-10-24 23:03 UTC, peterbarker reviewed
No simulator for this kind of sucks.

2023-10-24 23:03 UTC, merged