AP_HAL_ChibiOS: fix setting APP_RAM size
ArduPilot/ardupilot pull request #25297
Opened 2023-10-18 04:34 UTC by bugobliterator

* also allows passing APP_RAM_START index through hwdef, this could be to add support for old bootloaders which used different app ram map.

2023-10-18 06:02 UTC, tridge commented
@bugobliterator it isn't clear what the use case for this is

2023-10-18 06:21 UTC, bugobliterator commented
> @bugobliterator it isn't clear what the use case for this is

updated the reason in the initial comments

2023-10-18 08:10 UTC, tridge approved these changes

2023-10-18 08:13 UTC, tridge requested changes
need to check no binary change on spracing with external flash

2023-10-19 03:49 UTC, peterbarker commented
Post-filtered output from `rm -rf /tmp/tmp* && time \./Tools/scripts/size_compare_branches.py --all-boards --all-vehicles -j 32 --parallel=4 --exclude-board-glob=*JHE* --exclude-board-glob=*crazy* --exclude-board-glob=VRBrain-v51`; 
took ~3 hours to run.  Need to fix the linux builds to add the consistent-build arguments to the build system...


```
------------------------  ---------  -----  ----------  ------  ----  ----------  -----  -----  ---
Board                     AP_Periph  blimp  bootloader  copter  heli  iofirmware  plane  rover  sub
CubeRedPrimary                       *      0           *       *                 *      *      *
H757I_EVAL                                  0
SITL_arm_linux_gnueabihf             0                  0       0                 0      0      0
SITL_x86_64_linux_gnu                0                  0       0                 0      0      0
------------------------  ---------  -----  ----------  ------  ----  ----------  -----  -----  ---
```

New filter script here: https://github.com/ArduPilot/ardupilot/pull/25311

2023-10-19 20:42 UTC, peterbarker approved these changes

2023-10-22 23:43 UTC, tridge approved these changes

2023-10-22 23:43 UTC, merged