Lua: flight surface mixer script for PLUS and X configuration - X elevons
ArduPilot/ardupilot pull request #25321
Opened 2023-10-19 23:55 UTC by magicrub

New servo mixer LUA applet for "X Elevons"

Tested and co-authored-by Joe Aletky (@rotomobile) to mix a Plane Roll/Pitch/Yaw into 4 flight surfaces at the rear in either a PLUS or an X configuration. Of note, two of the flight surfaces for PLUS are good candidates for forward canards (with pitch gain = -1) that will give pitch and roll authority.

2023-10-20 00:22 UTC, tridge requested changes
looks good, but needs a md file (all applets are required to have a md file as documentation)
I presume this is for tailsitters?

2023-10-20 00:24 UTC, magicrub commented
> I presume this is for tailsitters?

Had something like this in mind
![image](https://github.com/ArduPilot/ardupilot/assets/4782875/ef17414d-b7d6-4662-a8d4-603c842b2998)

2023-10-20 00:39 UTC, tridge commented
> > I presume this is for tailsitters?
> 
> Had something like this in mind ![image](https://user-images.githubusercontent.com/4782875/276784059-ef17414d-b7d6-4662-a8d4-603c842b2998.png)

ok, thanks

2023-10-23 17:36 UTC, magicrub commented
Looks like @Rotomobile is still tinkering with this. He wants to add an Airbrake too so I'll mark this WIP until he's done poking at it. For the record, he flew this on fixed with that also had traditional ailerons mapped and it flew well without having to add any gains at all!

2023-11-26 05:28 UTC, closed without merging