Make it possible to surrpress the status text on arming/disarming the aircraft.
ArduPilot/ardupilot pull request #25345
Opened 2023-10-23 18:03 UTC by WickedShell

I don't find the status text of "Throttle armed" useful at all on plane, particularly because I have both generally good tracking of that, and on a ICE plane where you may be starting the throttle while disarmed this is particularly misleading. Interestingly both copter and sub actually only sent text messages in SITL, so presumably this isn't a unique opinion.

This adds an opt in behavior to not send the message. SITL tested on plane.

2023-10-23 20:50 UTC, IamPete1 commented
We could swap to SITL only on plane too?

2023-10-24 01:00 UTC, WickedShell commented
> We could swap to SITL only on plane too?

That would change the current behaviour and hide the message from everyone. (It's admittedly my preferred setup, but definitely would change what happens). In the SITL case I'm actually still honoring the option flag.

2023-10-24 01:28 UTC, tridge approved these changes

2023-10-24 01:30 UTC, peterbarker requested changes

2023-10-24 01:30 UTC, peterbarker commented on Rover/AP_Arming.cpp
> +    }
```suggestion
   send_arm_disarm_statustext(MAV_SEVERITY_INFO, "Throttle disarmed");
```

... and that method looks at the arming bit.  Much smaller patch, probably save some flash

2023-10-25 00:51 UTC, peterbarker commented on Rover/AP_Arming.cpp
> +    }
This was done

2023-10-25 00:52 UTC, peterbarker commented
```
Board               AP_Periph  blimp  bootloader  copter  heli  iofirmware  plane  rover  sub
Durandal                       40     *           *       *                 32     24     *
HerePro             *                                                                     
Hitec-Airspeed      *                                                                     
KakuteH7-bdshot                32     *           *       *                 40     32     *
MatekF405                      40     *           *       *                 40     32     *
Pixhawk1-1M-bdshot             40                 *       *                 40     32     *
f103-QiotekPeriph   *                                                                     
f303-Universal      *                                                                     
iomcu                                                           *                         
revo-mini                      40     *           *       *                 40     32     *
skyviper-v2450                                    *                                       
```

2023-10-25 16:39 UTC, merged