hwdef: added files for Airvolute DCS2 onboard FMU
ArduPilot/ardupilot pull request #25354
Opened 2023-10-24 12:03 UTC by vrsanskytom

2023-11-27 12:42 UTC, vrsanskytom commented
Added some default parameters. Device tested and all of the features works properly.

2023-12-04 23:04 UTC, Ryanf55 commented
MacOS failures are unrelated. I performed a rebase.

2023-12-04 23:40 UTC, Ryanf55 commented on libraries/AP_HAL_ChibiOS/hwdef/Airvolute-DCS2/README.md
> +
Does it only have 3 UARTs?

2023-12-04 23:41 UTC, tridge commented
marked for doc review by Henry - needs pinout information in the README

2023-12-04 23:56 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/Airvolute-DCS2/README.md
> +
and one used as RC....

2023-12-04 23:58 UTC, Hwurzburg commented
@vrsanskytom can you send me the wiring diagram so I can review? I will need that and a pinout list for the board to review for wiki page...and other suggestions, like default protocols,etc.

2023-12-05 06:46 UTC, vrsanskytom commented
@Hwurzburg OK, we will update wiki today and try to make it containing everything important.

2023-12-05 13:19 UTC, Hwurzburg commented
making a wiki page like : https://ardupilot.org/copter/docs/common-holybro-pixhawk6X.html is certainly appreciated, but I usually make that page based off the README.md file here. Its important that it be accurate and complete not only to assist in the wiki page production, but also as a code document for other developer's reference. I check the README.md versus the hwdef for consistency and completeness, and check the wiring diagram and pinouts like a user to be sure nothing is confusing...for example, you specify UART3 as the only RC input but do not default its protocol to RCin which would be expected by a user (also since its only RX pinned out,it wont support RC like CRSF,ELRS, or SRXL2)...

2023-12-05 14:29 UTC, vrsanskytom commented
@Hwurzburg  We just updated the readme, now it should contain all of the important information. 

I`m not sure if I understand properly what does it mean to remove hwdef line. But the whole board definitely is offered commercially, and we would like users to have the possibility to upgrade the firmware (firmware updates are handled from companion computer).

2023-12-05 16:13 UTC, Hwurzburg requested changes

2023-12-05 16:13 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/Airvolute-DCS2/hwdef.dat
> +AUTOBUILD_TARGETS None
delete this line or it wont be autobuild on the the firmware server for all vehicle types

2023-12-07 15:52 UTC, Hwurzburg requested changes
a few suggested changes

2023-12-08 07:51 UTC, vrsanskytom commented
Thanks for review. To what parts do you need to split it ?

2023-12-08 13:21 UTC, Hwurzburg approved these changes

2023-12-12 00:08 UTC, tridge approved these changes

2023-12-12 00:09 UTC, merged