ardupilot: Update BUILD.md
ArduPilot/ardupilot pull request #25372
Opened 2023-10-25 23:48 UTC by 4O6FPV

added binding for ap_periph for building waf

2023-10-25 23:49 UTC, peterbarker requested changes
LGTM, thanks!

2023-10-25 23:49 UTC, peterbarker approved these changes

2023-10-26 04:08 UTC, magicrub approved these changes

2023-10-27 03:17 UTC, merged

2023-10-27 03:17 UTC, peterbarker commented
Merged, thanks!