AP_WindVane: Optionalize the WINDVANE device
ArduPilot/ardupilot pull request #25379
Opened 2023-10-26 17:51 UTC by muramura

Optionalize the WINDVANE device.
Not all WINDVANE devices need to be built in.
I want to implement only the devices I use.

2023-10-26 18:04 UTC, magicrub requested changes

2023-10-26 18:04 UTC, magicrub commented on libraries/AP_WindVane/AP_WindVane_config.h
> +#define AP_WINDVANE_SITL_ENABLED AP_WINDVANE_ENABLED
Wouldn't the ```CONFIG_HAL_BOARD == HAL_BOARD_SITL``` check make sense here?

2023-10-26 18:04 UTC, magicrub commented on libraries/AP_WindVane/AP_WindVane_config.h
> +#define AP_WINDVANE_BACKEND_ENABLED AP_WINDVANE_ENABLED
AP_WINDVANE_BACKEND_ENABLED should be move up and all the other libraries should check if backend is enabled, not the frontend library. See [AP_Baro_config.h](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Baro/AP_Baro_config.h) as an example.

2023-10-26 18:06 UTC, magicrub commented on libraries/AP_WindVane/AP_WindVane_config.h
> +#define AP_WINDVANE_SITL_ENABLED AP_WINDVANE_ENABLED
Actually, it looks like we're migrating to use AP_SIM_ENABLED so use that here.

2023-10-26 19:36 UTC, Hwurzburg requested changes
needs entries in build_options.py and extract_features.py

2024-09-21 09:22 UTC, peterbarker commented
Sorry, looks like this has already be done in master.

Thanks anyway!

2024-09-21 09:22 UTC, closed without merging