Plane: move servo wiggle to mode auto
ArduPilot/ardupilot pull request #25391
Opened 2023-10-28 20:09 UTC by IamPete1

More plane tidy ups. This removes the early return in the `set_servos` function. New auto test added to look for the wiggle, it passes before and after the plane changes.

2023-10-28 20:14 UTC, IamPete1 commented
This change also means that the wiggles will propagate onto elevons and other derived control surfaces.

It still does not work for twin engine planes.

2023-10-30 07:08 UTC, tridge requested changes
looks good, thanks! 
fine to merge when idle_mode removed

2023-10-30 07:08 UTC, tridge commented on ArduPlane/commands_logic.cpp
> -        auto_state.idle_mode = false;
can remove idle_mode variable now?

2023-10-30 10:53 UTC, IamPete1 commented on ArduPlane/commands_logic.cpp
> -        auto_state.idle_mode = false;
yep, done.

2023-10-31 03:06 UTC, tridge approved these changes

2023-10-31 03:06 UTC, merged