AP_ADSB: avoid using GPS and RTC libraries in backend
ArduPilot/ardupilot pull request #25427
Opened 2023-11-01 03:22 UTC by peterbarker

instead, add fields to canonical AP_ADSB location "_my_loc" to hold all of the information backends might want.  This will allow consistent presentation of data regardless of backend type, and for the sources of the information to change more easily.

This work sponsored by SpektreWorks

2023-11-01 07:07 UTC, tridge requested changes
ok with concept

2023-11-01 07:07 UTC, tridge commented on libraries/AP_ADSB/AP_ADSB.h
> +            return true;;
more ; are good ; ?

2023-11-01 07:07 UTC, tridge commented on libraries/AP_ADSB/AP_ADSB.h
> +        Vector2f groundspeed_vector() const { return vel_ned.xy(); }
const ref?

2023-11-01 07:07 UTC, tridge commented on libraries/AP_ADSB/AP_ADSB.h
> +        Vector3f velocity() const {
const ref?

2023-11-01 07:07 UTC, tridge commented on libraries/AP_ADSB/AP_ADSB.h
> +        bool speed_accuracy(float &sacc) const {
better in cpp?

2023-11-01 07:07 UTC, tridge commented on libraries/AP_ADSB/AP_ADSB.h
> +        bool horizontal_accuracy(float &hacc) const {
in cpp

2023-11-01 11:16 UTC, peterbarker reviewed
Fixed review comments

2023-11-06 23:29 UTC, tridge approved these changes

2023-11-06 23:30 UTC, merged