AP_Mount: In Siyi, add handler for CAMERA_CAPTURE_STATUS request
ArduPilot/ardupilot pull request #25496
Opened 2023-11-09 04:36 UTC by nexton-winjeel

Following #24953, this PR adds support for the `CAMERA_CAPTURE_STATUS` message to the Siyi driver.

Tested on Siyi A8.

2023-11-09 11:46 UTC, rmackay9 requested changes
Hi @nexton-winjeel, thanks very much for this PR.  I think we should try to avoid this subtraction which could confuse a ground station.  It's a bit tricky but basically we need to add another way for feedback to arrive besides the existing GPIO trigger pin.  I thought about this a fair bit recently because I was going to add support for the feedback to arrive via DroneCAN but in the end, I found the Xacti supports the GPIO trigger pin for feedback so it was not necessary.

2023-11-09 21:43 UTC, nexton-winjeel commented
@rmackay9:
> I think we should try to avoid this subtraction which could confuse a ground station. It's a bit tricky but basically we need to add another way for feedback to arrive besides the existing GPIO trigger pin.

Sorry, I don't understand what you mean. Can you please provide a bit more detail?

2023-11-11 04:02 UTC, rmackay9 commented
@nexton-winjeel,

A key issue with this change is that while we can correct the total number of images taken, the CAM log message will have already been written.  This will lead to multiple CAM messages with the same image number so if users then try to geotag the images (e.g. save EXIF lat,lon,alt into the image file) using MP, it likely won't work.

To properly handle the Siyi cameras, we shouldn't log the CAM message nor report to the GCS that a picture has been taken until we get a positive ACK back from the camera.  The problem is that I don't think the Siyi cameras send an ACK in response to a take photo request.. they only send a NACK on failure.  I think we probably need to ask Siyi to send an ACK and ideally include the total number of pictures taken within that ACK.

2023-11-14 22:01 UTC, nexton-winjeel commented
OK, I understand. This isn't touching the `image_count` in the backend, it's keeping it's own internal counter. So the CAM log message will be OK, but it will be inconsistent with the `CAMERA_CAPTURE_STATUS` message sent by the Siyi.

As far as I'm aware, the Siyi doesn't report a successful snapshot, but I haven't looked at their recent updates. You're right, the `FUNCTION_FEEDBACK_INFO` message might be in response to another message.

I'll move this back to draft state and look at it again when I get back to Siyi development.

2023-11-14 23:09 UTC, rmackay9 commented
Hi @nexton-winjeel, I've chatted with Siyi and they say that the FUNCTION_FEEDBACK_INFO message's 0/success response will only be sent when a picture is successfully taken.  So this means we could use it to log the CAM message, increment the image_count, etc.  I don't think we should maintain two separate image counts.

2024-07-25 01:47 UTC, closed without merging