AP_Scripting: add checksum of running and loaded scripts with arming check
ArduPilot/ardupilot pull request #25521
Opened 2023-11-12 23:08 UTC by IamPete1

This allows a arming check that the correct scripts are running and loaded preventing a missing SD card from meaning critical scripts are missing. 

This does a crc32 on the each file and XOR's the result for multiple files. The crc caculation gives the same result per file as the `crc32` command on linux and pages such as this one:  https://emn178.github.io/online-tools/crc32_checksum.html

However, because of float parameter transport we can't actually set the CRC we want into parameters, so this is still a draft. 

We could move to a 16 bit checksum, or add a "lock in scripts" command to set the current value to the parameters.

This is also very much a pass/fail arming check, we can only tell that the check sum failed, we cannot tell which script is missing. 

I the future this would allow a fail safe action to be taken if the running scripts do not match the expected checksum.

2023-11-12 23:09 UTC, IamPete1 commented on libraries/AP_Scripting/lua_scripts.cpp
> +        // XOR output to give same result as standard crc32
There could be a case for moving this up to `AP_Filesystem`.

2023-11-25 21:26 UTC, IamPete1 commented on libraries/AP_Filesystem/AP_Filesystem.cpp
> +    uint8_t buf[buff_len];
In the case of the GCS FTP were now using a second buffer rather than re-using the FTP one. We could also pass in a buffer and size I guess....

2023-11-27 23:40 UTC, tridge requested changes
I think a SCR_OPTIONS bit, which when set will lock-in the parameters and unset the bit

2023-11-28 18:43 UTC, IamPete1 commented
> I think a SCR_OPTIONS bit, which when set will lock-in the parameters and unset the bit

This is harder than it might seem. Scripting has currently no periodic callback to check from. If we check from the scripting thread its's self were stuck with whatever update rate the script is using which could be annoyingly slow for this use or wastefully fast.

2023-11-28 18:49 UTC, IamPete1 commented on libraries/AP_Filesystem/AP_Filesystem.cpp
> +    uint8_t buf[buff_len];
We decided this was OK on the dev all.

2023-11-30 16:27 UTC, IamPete1 commented
I have added a bit to `DEBUG_OPTS` to auto set the checksums. 

It does bring up a few ways a script could bypass.

- The script could turn off the arming check with the debug options bit. We could make the  new checksum check ignore that option.
- The script could set the new bit to "self certify" itself. Of course the script could also just set the checksum directly, but that would take a fair bit of messing about to because the script would have to include the checksum of itself.

Of course the user can bypass in all the above ways and also just by turning off scripting.

On the whole I think this fits the goal of protecting against accidental issues causing the scripts to not run.

I don't think we need to protect against either users, or scripts designed to bypass.

2023-12-05 00:02 UTC, tridge approved these changes

2023-12-05 00:03 UTC, merged