AP_HAL: clean up UART driver storage/access
ArduPilot/ardupilot pull request #25589
Opened 2023-11-21 02:33 UTC by tpwrules

Eliminates UB and saves 108 bytes on CubeOrangePlus. See commits for details.

No functional change.

2023-11-21 02:47 UTC, peterbarker approved these changes
LGTM.

It's progress (removing `uartX` as members is good), but there's obviously still more to do here.

Next step would probably be to push that mapping back down into each of the HALs, so the HALs can push the devices into here in a 1-1 order.

2023-11-21 02:47 UTC, peterbarker commented on libraries/AP_HAL/HAL.h
> +    if (sernum >= num_serial) {
```suggestion
    if (sernum >= ARRAY_SIZE(uart_array)) {
```

2023-11-21 06:29 UTC, tridge requested changes
I want to get rid of the old mapping completely, just needs some work in HAL_SITL, HAL_Linux etc

2023-11-21 17:12 UTC, tpwrules commented
> I want to get rid of the old mapping completely, just needs some work in HAL_SITL, HAL_Linux etc

I looked into this but the old mapping still is user-visible as command line options with those. Is it finally time for those options to be removed? That could break people's scripts.

2023-11-22 07:12 UTC, rmackay9 commented
@tridge how do you feel about merging this now and then do the AP_HAL changes in a follow-up PR?  Just thinking of scope creep and helping devs cut their teeth on this smaller change.

2023-12-11 20:23 UTC, tpwrules commented
I spent some cathartic time with Ctrl+F and I think I've managed to eliminate virtually every trace the old mapping. A couple things remain which might break users if removed. It shouldn't be much effort to remove them for good if desired.

2023-12-11 20:52 UTC, tridge commented
@tpwrules wow, this is great! I've been putting this off for ages, and you did it exactly the way I wanted it done. I think you deserve for medal for taking this on.
We just need some testing of this on ChibiOS and SITL at least before merging. I can't spot any errors, but it is such a tricky conversion I think we need to do some careful testing

2023-12-11 22:44 UTC, tpwrules commented
Thank you very much for the kind words. Glad to be able to help.

I did test one serial port with a serial GPS on my own CubeOrange to make sure that ordering did not change. SITL should be covered by the CI. I did also launch and fly around a bit a SITL system on my computer using MAVProxy and `sim_vehicle.py` but was not particularly exhaustive.

2023-12-12 17:44 UTC, tpwrules commented
Warnings have been added. Should be ready to merge once you are happy with ChibiOS testing.

2023-12-13 16:14 UTC, tpwrules commented
Final rebase, mostly to clean up some super minor things and make CI green.

2023-12-18 19:52 UTC, tridge approved these changes

2023-12-18 19:52 UTC, tridge commented
@tpwrules I tested all uarts on cubeorange with no issues

2023-12-18 19:53 UTC, merged