AP_Networking: Allow Broadcast
ArduPilot/ardupilot pull request #25593
Opened 2023-11-22 00:39 UTC by magicrub

Add define AP_NETWORKING_SOCKETS_BROADCAST_ALLOWED to enable Broadcast IP (255.255.255.255) on sockets.

2023-11-22 20:36 UTC, tridge requested changes
I think we should have a new NET_Pn_TYPE for UDP_BROADCAST. Note that we should be doing subnet broadcast, so 192.168.13.255 for example, not 255.255.255.255

2023-11-23 05:28 UTC, magicrub commented
Why not just let the user set the IP to whatever they want and allow broadcast at any time?

2023-11-25 21:44 UTC, magicrub commented
Changed to have the Socket detect IP address 255.255.255.255 and auto-set the broadcast flag. A future PRs can add fancier broadcast detecting that involves the NetMask

2023-11-25 21:55 UTC, tridge approved these changes

2023-11-26 00:28 UTC, merged