EKF3: allow earth-frame fields to be estimated with an origin but no GPS
ArduPilot/ardupilot pull request #25666
Opened 2023-11-29 16:00 UTC by Williangalvani

This is my attempt at fixing https://github.com/ArduPilot/ardupilot/issues/18229

Here's a log using it:
https://github.com/ArduPilot/ardupilot/issues/18229
I am using a script to set the origin so we can use the earth field database.
[00000228.zip](https://github.com/ArduPilot/ardupilot/files/13502545/00000228.zip)

I can see that XKF2 fields are all populated for magnetic field in body frame and earth frame.

![image](https://github.com/ArduPilot/ardupilot/assets/4013804/4d97de56-8818-462b-98bf-2e6a66020247)

2023-11-30 00:13 UTC, rmackay9 commented
Hi, if the issue is the earth magnetic field (aka WMM) is not being estimated then the EKF also shouldn't be trying to use the WWM to reject the compass, instead it should accept it I think.

As a side note, it's naughty that the EKF is using the GPS status at all.  This presumably means the same problem could happen when using a non-GPS navigation source while also using a compass which is very possible (e.g. Beacons).

2023-11-30 02:52 UTC, lixiaowei123 commented
![af113c5725f37d8b81e856b1ebd5435](https://github.com/ArduPilot/ardupilot/assets/16605202/bc8cc02a-4a68-46bc-aebd-cebf4d5f4d4e)
I have been saying that there is a bug in the estimation of EKF3 acceleration velocity increment offset

2023-11-30 02:53 UTC, lixiaowei123 commented
@rmackay9 You can view all the latest version logs to see if this is sometimes very large, and normally it should not exceed 0.3

2023-12-05 00:25 UTC, tridge approved these changes

2023-12-05 00:25 UTC, tridge commented on libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp
> +        return;
why the early return? this seems to defeat some of the code
maybe only return if the xy position source type is none?

2023-12-05 00:27 UTC, tridge commented on libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp
> +    if (gps.status() == AP_DAL_GPS::NO_GPS && validOrigin && !stateStruct.quat.is_zero()) {
maybe this should be in the function that sets the origin?

2023-12-05 00:29 UTC, tridge commented on libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp
> +    if (gps.status() == AP_DAL_GPS::NO_GPS && validOrigin && !stateStruct.quat.is_zero()) {
NavEKF3_core::setOrigin()

2023-12-05 00:37 UTC, rmackay9 commented
As discussed on the dev call we should investigate why the EKF3 is unable to fuse the compass when it doesn't have a position estimate.  It really should be able to although it won't be as accurate.

2024-07-01 23:22 UTC, tridge requested changes

2024-07-01 23:22 UTC, tridge commented on libraries/AP_NavEKF3/AP_NavEKF3_Control.cpp
> +    Vector3f magNED;
2 unused lines?

2024-07-01 23:22 UTC, tridge commented on libraries/AP_NavEKF3/AP_NavEKF3_Control.cpp
> +                stateStruct.earth_magfield = table_earth_field_ga;
I think you need to fill in these: ```
    // earth field from WMM tables
    bool have_table_earth_field;   // true when we have initialised table_earth_field_ga
    Vector3F table_earth_field_ga; // earth field from WMM tables
    ftype table_declination;       // declination in radians from the tables
```

2024-07-01 23:24 UTC, tridge commented on libraries/AP_NavEKF3/AP_NavEKF3_Control.cpp
> +            compass.auto_declination_enabled()) {
don't need to check auto_declination_enabled

2024-07-01 23:30 UTC, tridge commented on libraries/AP_NavEKF3/AP_NavEKF3_Control.cpp
> +        if (compass.have_scale_factor(magSelectIndex) &&
could be a common function with the code in readGpsData()

2024-07-01 23:31 UTC, tridge commented on libraries/AP_NavEKF3/AP_NavEKF3_Control.cpp
> +        if (compass.have_scale_factor(magSelectIndex) &&
maybe setEarthFieldFromLocation()

2024-07-01 23:34 UTC, rmackay9 commented
We discussed on the July 2nd dev call and decided that we should move the shared code to a new function and then call it from within setOrigin and readGPSData.

2024-07-02 00:07 UTC, rmackay9 approved these changes

2024-07-03 06:49 UTC, tridge approved these changes

2024-07-03 06:49 UTC, merged