Don't Switch to DCM to get Better GPS if DCM Isn't Using GPS
ArduPilot/ardupilot pull request #25707
Opened 2023-12-05 08:04 UTC by njwhite

Look at the parameter to see if DCM uses GPS; if not don't prefer DCM for using GPS.

2023-12-11 08:00 UTC, tridge approved these changes

2023-12-17 22:57 UTC, njwhite commented
@tridge CI has passed - could you merge please? Thanks  -

2023-12-27 21:36 UTC, IamPete1 requested changes
Need to drop the merge commit

2024-01-01 02:16 UTC, merged

2024-01-01 14:02 UTC, njwhite commented
@tridge @IamPete1 thanks for you help getting this merged!