AP_HAL_SITL: add packet loss and delay to all uart
ArduPilot/ardupilot pull request #25775
Opened 2023-12-15 00:17 UTC by robertlong13

I am working on a redundant link manager plugin for Mission Planner that tries to intelligently select the "best" link to the aircraft. While developing it, I needed a way to simulate:
1) Packet loss rate on a per-link basis
2) Comm latency

Before this, there was only a way to simulate single-byte losses, and the setting applied to all serial ports. This switches to dropping full packets (I may extend this to allow partial packets at some point, to catch any issues caused by dropped data not aligning with packet boundaries, but I'm trying to figure out how to do that without introducing a million parameters), and it allows you to set the drop rate per serial port. In conjunction with a lua script, this could be used to cause burst losses for multiple seconds or could steadily increase the loss rate as you fly further from home.

I also added two queues to delay packets for a period of time both in and out. This is to simulate, for example, the ping time of a 4G link, or maybe even a satcom. This could even be used with a lua script that randomly sets this high and then low to simulate a TCP link that lost signal for 5 seconds, then dumps the last 5 seconds of data all at once when it comes back.

Here's a little animation of me testing that the latency works two-ways. Three instances of Mission Planner running on three different links. The left has no delay, and the two on the right have a delay of 500ms both ways. 500ms after I click the button on the right, the status message on the left updates (because the RX latency of that SITL link), and then 500ms after that, the status message on the right updates (because the TX latency of that SITL link)

![CommLatencySim](https://github.com/ArduPilot/ardupilot/assets/14059190/dae18833-4ee9-4a1b-8db4-0702629ddd63)

2024-05-20 11:45 UTC, IamPete1 commented
I did a similar (ish) thing for the ELRS sim here: https://github.com/ArduPilot/ardupilot/pull/26663. The key difference is that it does all the limiting in the "radio" sim rather in the UART driver.

2024-05-20 23:15 UTC, tridge requested changes

2024-05-20 23:15 UTC, tridge commented on libraries/AP_HAL_SITL/UARTDriver.cpp
> +    // simulate whole packet loss rate per uart driver
it would be nice to break this out to a separate function

2025-06-10 09:27 UTC, robertlong13 commented
Old stale PR I should have closed a while ago. If I recall the dev call correctly, there are ways to achieve all of this with existing external command-line tools that don't require changes to ArduPilot.

2025-06-10 09:27 UTC, closed without merging