AP_Relay:correct function param metadata
ArduPilot/ardupilot pull request #25829
Opened 2023-12-24 14:58 UTC by Hwurzburg

NFC

2023-12-24 15:10 UTC, IamPete1 approved these changes
Thanks.

2023-12-24 15:14 UTC, IamPete1 commented on libraries/AP_Relay/AP_Relay_Params.cpp
> +    // @Values:{Copter, Rover, Plane, Blimp} 1:Relay
```suggestion
    // @Values{Copter, Rover, Plane, Blimp}: 0:None
    // @Values{Copter, Rover, Plane, Blimp}: 1:Relay
```

2023-12-24 15:14 UTC, IamPete1 commented on libraries/AP_Relay/AP_Relay_Params.cpp
> +    // @Values:{Copter, Rover, Plane, Blimp} 4:Camera
```suggestion
    // @Values{Copter, Rover, Plane, Blimp}: 4:Camera
```

2023-12-26 21:40 UTC, peterbarker requested changes

2023-12-26 21:40 UTC, peterbarker commented on libraries/AP_Relay/AP_Relay_Params.cpp
> +    // @Description: Should the relay default to on or off, this only applies to RELAY_FUNC Relay (1). All other uses will pick the appropriate default output state from within the controlling functi
```suggestion
    // @Description: Should the relay default to on or off, this only applies to RELAYn_FUNCTION 1 ("Relay"). All other uses will pick the appropriate default output state from within the controlling function's parameters.
```

2023-12-26 21:40 UTC, peterbarker commented on libraries/AP_Relay/AP_Relay_Params.cpp
> +    // @Values{Copter, Rover, Plane, Blimp}: 0:None
```suggestion
    // @Values{Copter, Rover, Plane, Blimp, Sub}: 0:None
```

2023-12-26 21:40 UTC, peterbarker commented on libraries/AP_Relay/AP_Relay_Params.cpp
> +    // @Values{Copter, Rover, Plane, Blimp}: 1:Relay
```suggestion
    // @Values{Copter, Rover, Plane, Blimp, Sub}: 1:Relay
```

2023-12-26 21:40 UTC, peterbarker commented on libraries/AP_Relay/AP_Relay_Params.cpp
> +    // @Values{Copter, Rover, Plane, Blimp}: 4:Camera
```suggestion
    // @Values{Copter, Rover, Plane, Blimp, Sub}: 4:Camera
```

2023-12-26 21:54 UTC, Hwurzburg commented on libraries/AP_Relay/AP_Relay_Params.cpp
> +    // @Description: Should the relay default to on or off, this only applies to RELAY_FUNC Relay (1). All other uses will pick the appropriate default output state from within the controlling functi
done

2023-12-26 21:57 UTC, Hwurzburg commented on libraries/AP_Relay/AP_Relay_Params.cpp
> +    // @Values{Copter, Rover, Plane, Blimp}: 0:None
done

2023-12-26 21:57 UTC, Hwurzburg commented on libraries/AP_Relay/AP_Relay_Params.cpp
> +    // @Values{Copter, Rover, Plane, Blimp}: 4:Camera
done

2023-12-26 21:57 UTC, Hwurzburg commented on libraries/AP_Relay/AP_Relay_Params.cpp
> +    // @Values{Copter, Rover, Plane, Blimp}: 1:Relay
done

2023-12-26 22:52 UTC, magicrub commented
Is this ready to merge? Seems OK to me now..

2023-12-26 23:04 UTC, Hwurzburg commented
I think so....

2023-12-27 05:28 UTC, magicrub approved these changes

2023-12-27 05:28 UTC, merged

2023-12-27 14:02 UTC, Hwurzburg commented
thanks!