AP_Network:add reboot req'd metadata to params missing it
ArduPilot/ardupilot pull request #25904
Opened 2024-01-05 21:26 UTC by Hwurzburg

plus some minor tweaks....NFC...checked param_parse.py

2024-01-06 05:03 UTC, magicrub approved these changes

2024-01-06 07:39 UTC, tridge requested changes
Looks good but has a merge commit

2024-01-06 13:33 UTC, Hwurzburg commented
@tridge interesting...used the update button on the PR to bring it up to master so the CI fixes would run....so we cant use that button apparently....
rebased locally and re-pushed

2024-01-07 09:15 UTC, magicrub approved these changes

2024-01-07 09:15 UTC, merged

2024-01-07 14:01 UTC, Hwurzburg commented
thanks