RC_Channel: options in alphabetical order
ArduPilot/ardupilot pull request #25963
Opened 2024-01-12 07:48 UTC by rmackay9

Our list of RCx_OPTION parameter values is very long and users struggle to find what they are looking for.

This PR reorders them mostly in alphabetical order with some exceptions:

1. "Do Nothing" remains at the top
2. Flight modes are at the top
3. Developer only items (or perhaps dangerous options) are right at the bottom including (e.g. "GPS Disable", "KillIMU")

There are some small issues that I could have fixed but put off for a follow-up PR to keep it easier to verify and merge:

a. some lines still have multiple items on them (e.g. "300:Scripting1, 301:Scripting2.." and "166:Camera Record Video, 167:Camera Zoom)
b. some items are badly named, (e.g. "use Custom Controller")
c. some are used to define the channel is used for control (e.g. Roll, Walking Height).  We could group these, perhaps below the modes

I have carefully verified that no items have been lost in this change.  I asked ChatGPT to do it first but it failed so I resorted to a spreadsheet with multiple cross checks.

2024-01-12 08:47 UTC, andyp1per commented
This is purely a doc change so it looks better in MP, right?

2024-01-12 08:49 UTC, rmackay9 commented
@andyp1per,

Yes, that's right.  It has no functional change in terms of the flight code.  It's just for the GCSs.

2024-01-12 13:10 UTC, Hwurzburg commented
will require considerable wiki work on this page: common-auxiliary-functions.rst, but its a good change...have made a suggestion while we are at it.

2024-01-12 13:12 UTC, Hwurzburg requested changes

2024-01-12 13:12 UTC, Hwurzburg commented on libraries/RC_Channel/RC_Channel.cpp
>      // @Description: Function assigned to this RC channel
```suggestion
    // @Description: Function assigned to this RC channel. Normally intended as a 2 or 3 position switch, functions in the 200/300 ranges are normally intended for continuous input range control.
```

2024-01-15 13:58 UTC, IamPete1 commented
I wonder if we could just have the param parser do this for us automatically....

2024-01-15 22:56 UTC, tridge commented
> I wonder if we could just have the param parser do this for us automatically....

we could have an optional "@SortedOptions" line which would cause it sort

2024-01-16 00:03 UTC, rmackay9 commented
I'm happy with the SortedOptions idea if we're happy not to have the flight modes at the top.

2024-01-16 05:22 UTC, rmackay9 commented
An alternative change is here https://github.com/ArduPilot/ardupilot/pull/25996

2024-01-17 07:34 UTC, rmackay9 commented
Closing in favour of PeterB's PR.

2024-01-17 07:34 UTC, closed without merging