AP_Logger: RXLQ in RSSI is in percent
ArduPilot/ardupilot pull request #26084
Opened 2024-01-26 09:44 UTC by olliw42

this is very tiny tidy up: Link quality (LQ) is pretty universally given in units of 0...100%.

2024-01-26 12:40 UTC, peterbarker requested changes
I'm fine with presenting it that way in the log, but the code that actually fills this packet needs to be updated to x100 the value before logging it (LogFile.cpp ~line 263)

2024-01-27 07:20 UTC, olliw42 commented
> the code that actually fills this packet needs to be updated to x100 the value before logging it (LogFile.cpp ~line 263)

really? This would explain why the field RXLQ in the log_RSSI is `float`, but the code has then a bug:

your comment suggests that the intended range for LQ is 0.0 ... 1.0, but the code that fills the packet calls the function `rssi->read_receiver_link_quality()`, which in turn calls the function `RC_Channels::get_receiver_link_quality()`, which returns LQ as `int16`, and moreover the comment says it returns LQ as 0...100 %. `RC_Channels::get_receiver_link_quality()` in turn calls HAL functions, which are also int16.

- https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Logger/LogFile.cpp#L253-L267
- https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_RSSI/AP_RSSI.cpp#L161-L168
- https://github.com/ArduPilot/ardupilot/blob/master/libraries/RC_Channel/RC_Channel.h#L474

!?!? 

so, if `RC_Channels::get_receiver_link_quality()` is supposed to return a value in range 0...1, it only would return 0 or 1, and we would have a clear bug. Morever it's in contradiction to the comment.

ergo, the code as is I think is logging 0...100 in %. 
If it was supposed to do 0..1 a conversion `* 0.01f` in `rssi->read_receiver_link_quality()` is missing, which would have to be undone as you say in the caller.

2024-01-31 22:17 UTC, peterbarker commented
> Morever it's in contradiction to the comment

Thanks for delving.  I'd prefer 0-1 myself, but it's probably the comment and `float` return value that needs fixing in the short term.  This is all more complicated than it should be, too - I'm trying to move us towards removing RCInput from the HAL entirely, which would eliminate one layer!

2024-01-31 22:17 UTC, peterbarker approved these changes

2024-01-31 22:18 UTC, merged

2024-01-31 22:18 UTC, peterbarker commented
Merged, thanks!