Optional (CHUTE_OPTIONS:1) disarm debore parachute release
ArduPilot/ardupilot pull request #26129
Opened 2024-02-02 10:49 UTC by python36

Based on discussion of PR #25570 and #25562.

Disarm before parachute release to avoid parachute tangling if parameter CHUTE_OPTIONS:1 = 0.

2024-02-02 23:38 UTC, IamPete1 commented
We have a option to enable safety switch on disarm, if that was set disarm would cause safety to come on which could in-turn inhibit your parachute release servo.

I'm not really sure how we can overcome that. It maybe such a edge case that is does not matter. Of course it only affects those methods that don't currently disarm.

2024-02-14 09:14 UTC, python36 commented
Hi @IamPete1 . Please write a set of parameters and actions that will lead to this. I have tested many cases and cannot inhibit the parachute servo with the safety buttons.

2024-04-06 08:16 UTC, tridge commented
> if that was set disarm would cause safety to come on which could in-turn inhibit your parachute release servo.

@IamPete1 we currently always disarm on release, so this is adding an option to not do that. The exact order is likely not important as setting the PWM for a server isn't instantaneous anyway

2024-04-06 08:17 UTC, tridge approved these changes

2024-04-06 08:17 UTC, tridge commented
I think this is good, marked for dev call topic for discussion

2024-04-08 23:10 UTC, tridge commented
@Hwurzburg for docs, we need to note that BRD_SAFETY_MASK needs to be setup to allow chute servo when disarmed if you have the option to set safety on when you disarm

2024-04-08 23:15 UTC, peterbarker approved these changes

2024-04-08 23:15 UTC, rmackay9 approved these changes

2024-04-08 23:16 UTC, peterbarker requested changes
Needs a split

2024-04-08 23:16 UTC, rmackay9 commented
We should fix the commit message.

2024-04-08 23:18 UTC, tridge commented
I split the commits into subsystems and rebased

2024-04-10 11:55 UTC, merged

2024-04-12 15:37 UTC, python36 commented
Many thanks