Copter: improved follow at close distances
ArduPilot/ardupilot pull request #26138
Opened 2024-02-04 04:38 UTC by tridge

we need to add the target velocity after we scale for being close to the target or we end up with a large offset lag
This makes a huge difference with 3 copters following with offsets of 5m

2024-02-06 09:58 UTC, Georacer requested changes
I believe this is not correct yet, as the Z-velocity limitation to `get_max_speed_down_cms()` hasn't been moved after the slowdown calculations and the addition of the target velocity (like the XY component have).

Other than that, I proposed a small comment re-wording.

Finally, not strictly part of the code changes, but I think the part at L76-81 is unused, so it'd be nice to delete it:
```cpp
        // unit vector towards target position (i.e. vector to lead vehicle + offset)
        Vector3f dir_to_target_neu = dist_vec_offs_neu;
        const float dir_to_target_neu_len = dir_to_target_neu.length();
        if (!is_zero(dir_to_target_neu_len)) {
            dir_to_target_neu /= dir_to_target_neu_len;
        }
```

2024-02-06 09:58 UTC, Georacer commented on ArduCopter/mode_follow.cpp
> +          not want to scale it when we get close to the target
I'd say "We add this at the end as we don't want to apply the slowdown calculations to the baseline target velocity too" is a more accurate reasoning. How close we are to the target doesn't play a role in the slowdown calculations.

2024-02-06 09:58 UTC, Georacer commented on ArduCopter/mode_follow.cpp
>          desired_velocity_neu_cms.z = constrain_float(desired_velocity_neu_cms.z, -fabsf(pos_control->get_max_speed_down_cms()), pos_control->get_max_speed_up_cms());
This vertical velocity limitation shouldn't be here, before the slowdown calculations, but after ~L112, like the XY limitations.

2024-02-12 23:07 UTC, tridge commented
closing in deference to https://github.com/ArduPilot/ardupilot/pull/26142

2024-02-12 23:07 UTC, closed without merging