AP_HAL: remove deprecated --uartX options
ArduPilot/ardupilot pull request #26156
Opened 2024-02-06 22:19 UTC by tpwrules

Code remains to check for use of these options and give an error which contains the correct option to use, due to the non-intuitive mapping between --uartX and --serialN.

A future version will remove that code too.

Tested that the arguments are correctly rejected.

2024-04-06 08:10 UTC, tridge requested changes
I think there are some uses of --uartX left in our code, sim_Loweheiser.h is one example, and SIM_InertialLabs.h

2024-04-08 23:16 UTC, Williangalvani commented
This would be an issue in BlueOS. possibly in other Companion computers as well?

This would make us change to --serialN, but doing so would break our support for the [current stable Sub (4.1.2)](https://github.com/ArduPilot/ardupilot/blob/Sub-4.1/libraries/AP_HAL_Linux/HAL_Linux_Class.cpp#L311-L320). I think we should allow both to coexist for a while longer.

In BluOS, we should parse the binary output in case of errors to check if the option was refused, but that would still require some time to roll out...

2024-04-08 23:22 UTC, tridge commented
@tpwrules until BlueOS is updated lets leave the compatibility in place for HAL_Linux, then remove in a month or two after @Williangalvani has rolled out a new stable BlueOS

2024-04-09 00:13 UTC, tpwrules commented
Okay, I dropped the Linux changes. I'm fine waiting until all the vehicles have a stable release before converting to an error in Linux. But doing the changes in SITL now is good to prevent new users from creeping in.

2024-05-27 23:23 UTC, tridge approved these changes

2024-05-27 23:23 UTC, Ryanf55 approved these changes

2024-05-27 23:23 UTC, merged