Fixed InertialLabs External AHRS driver
ArduPilot/ardupilot pull request #26153
Opened 2024-02-06 17:51 UTC by VSheleverIL

2024-02-06 23:20 UTC, rmackay9 commented on libraries/AP_ExternalAHRS/AP_ExternalAHRS_InertialLabs.cpp
> -#endif
Removing these definitions doesn't look right.  I suspect this change was unintentional.

2024-02-06 23:21 UTC, rmackay9 commented on libraries/AP_ExternalAHRS/AP_ExternalAHRS_InertialLabs.cpp
> +            ins_data.accel = u.accel_data_hr.tofloat().rfu_to_frd()*9.8106f*1.0e-6;
nitpick: white space at the end.

2024-02-06 23:23 UTC, rmackay9 requested changes
Hi @VSheleverIL,

Thanks for this.  Could you correct the commit title so that it starts with "AP_ExternalAHRS:"?  If you look through [our commit history](https://github.com/ArduPilot/ardupilot/commits/master/) you'll see we always prefix our commits with the subsystem to make it easier to see what is affected by the commit.  This is especially important during backports.  To be clear I meant the commit title, not the PR title.

Could you also fill in the PR description including testing that has been performed?

2024-02-07 15:18 UTC, VSheleverIL commented
> Hi @VSheleverIL,
> 
> Thanks for this. Could you correct the commit title so that it starts with "AP_ExternalAHRS:"? If you look through [our commit history](https://github.com/ArduPilot/ardupilot/commits/master/) you'll see we always prefix our commits with the subsystem to make it easier to see what is affected by the commit. This is especially important during backports. To be clear I meant the commit title, not the PR title.
> 
> Could you also fill in the PR description including testing that has been performed?

2024-02-07 15:20 UTC, VSheleverIL commented
> Hi @VSheleverIL,
> 
> Thanks for this. Could you correct the commit title so that it starts with "AP_ExternalAHRS:"? If you look through [our commit history](https://github.com/ArduPilot/ardupilot/commits/master/) you'll see we always prefix our commits with the subsystem to make it easier to see what is affected by the commit. This is especially important during backports. To be clear I meant the commit title, not the PR title.
> 
> Could you also fill in the PR description including testing that has been performed?

Hi @rmackay9,

Thank you for your feedback. I have made changes according to your comments. Please review the outcome. Thank you!

2024-08-14 10:37 UTC, closed without merging