Copter: run rate loop at full filter rate in its own thread
ArduPilot/ardupilot pull request #26189
Opened 2024-02-11 05:28 UTC by tridge

This adds FLIGHT_OPTIONS=8 which creates a rate loop thread, allowing rate updates at the full filtered gyro rate (2kHz on most copters)
This was test flown successfully on a 5" quad from @MichelleRos, the rate loop did run at 2kHz (I added a send text for average rate every 2s)

2024-02-12 16:14 UTC, andyp1per commented
I had a go at flying this but nearly had a fly away due to frame resonance. My guess would be that the PID notch sample frequency is not being updated correctly with the right values but have not looked in detail at what is going on.

2024-02-12 22:36 UTC, tridge commented
> I had a go at flying this but nearly had a fly away due to frame resonance. My guess would be that the PID notch sample frequency is not being updated correctly with the right values

you're right, it was using the wrong frequency for PID notch, I've fixed it in the PR

2024-02-13 15:18 UTC, andyp1per requested changes
Looks good. I think the main thing for me is that we should call AP_Vehicle::update_dynamic_notch_at_specified_rate() from the rate loop thread since these are all filtering related. Also without this people will not be able to significantly lower their loop rate without losing update rates. We obviously would need some options to control the actual rate.

2024-02-13 15:18 UTC, andyp1per commented on ArduCopter/Attitude.cpp
> +        if (!flight_option_is_set(FlightOptions::USE_RATE_LOOP_THREAD)) {
I think in the final PR you should make this a boot time option only. It increases the complexity of the code and I'm not sure it really adds a lot of value.

2024-02-13 15:18 UTC, andyp1per commented on ArduCopter/Copter.cpp
> +                                         "rate_controller",
Please can we shorten the thread name as it gets truncated in ```@SYS/threads.txt```

2024-02-14 06:51 UTC, tridge commented
> I think the main thing for me is that we should call AP_Vehicle::update_dynamic_notch_at_specified_rate() from the rate loop thread since these are all filtering related

easy to do, we just need to assess the CPU cost to see how often we can call it reasonably

2024-02-14 06:58 UTC, MichelleRos commented
> we just need to assess the CPU cost to see how often we can call it reasonably

I'd actually be curious to test how much this impacts performance - maybe updating the notches at the rate loop rate gives better performance than leaving the notches updating slowly and running the PIDs faster.

2024-02-16 20:04 UTC, andyp1per commented
Quick test - now seems to fly fine. Couple of issues:
- Log download seems to be twice as slow
- Dshot tone commands seem to be missing, still get tones but some are missing

2024-02-17 12:35 UTC, amilcarlucas commented on ArduCopter/Attitude.cpp
> +        const float dt = dt_us * 1.0e-6;
```suggestion
        const float dt = dt_us * 1.0e-6f;
```

2024-05-04 15:51 UTC, andyp1per commented
I tried running autotune on my copter with this change and it completely failed. Very strange noises coming from the motors on twitches. Autotune picked minimum gains for everything. So there is definitely something not right in the implementation that needs to be resolved before I can dig in to whether it makes a worthwhile difference or not.

2024-05-06 17:00 UTC, andyp1per commented
So the problem appeared to be extreme jitter in the motor outputs cause by extreme jitter in the SPI reads which never actually got anywhere the required rate (running at about 1.6Khz vs 4Khz), so I thin that made all the maths be messed up. This was ultimately caused by the SPI thread not having a high enough priority and the device scheduler introducing arbitrary delays. I have made some changes to resolve these and the branch is here - https://github.com/andyp1per/ardupilot/tree/pr-fast-rate-thread (includes a rebase). The output now looks pretty regular at 4Khz. Too wet to fly, but indoor testing looks promising.

2024-05-06 18:44 UTC, andyp1per commented
Did a quick flight test outside - certainly the grinding noises are all but gone. Will need to see if I can successfully do an autotune but the log looks promising

2024-05-06 20:41 UTC, tridge commented
@andyp1per interesting! hope a full flight test goes well

2024-05-07 16:33 UTC, andyp1per commented
Still wouldn't tune. Its certainly a lot better, but still something strange going on. I also tried using the actual dt rather than the average and had a flyaway - would barely respond to RC input. There is a real danger of thread starvation of the main loop with the higher priority threads which is what I just saw 😮

2024-05-09 11:16 UTC, andyp1per commented
@lthall has pointed out that autotune is not zeroing D_FF (which I will fix) and the target is showing spurious changes:

![image](https://github.com/ArduPilot/ardupilot/assets/2893260/702eaaec-d41d-41c4-b6ff-bf4ee72a2ea4)

2024-08-04 06:03 UTC, tridge commented
replaced by #27029

2024-08-04 06:03 UTC, closed without merging