High speed VTOL flight fixes
ArduPilot/ardupilot pull request #26212
Opened 2024-02-13 20:29 UTC by priseborough

2024-02-13 20:46 UTC, tridge requested changes
minor spelling error ...
has this been flight tested? It looks like something we would want in 4.5.0

2024-02-13 20:46 UTC, tridge commented on ArduPlane/quadplane.cpp
> +    // @Description: This sets the maximum number of degrees of back or pitch up in Q modes when the airspeed is at AIRSPEED_FBW_MIN and is used to prevent excessive sutructural loads when pitching u
note that AIRSPEED_FBW_MIN is now called AIRSPEED_MIN

2024-02-13 22:52 UTC, priseborough commented
> > has this been flight tested? It looks like something we would want in 4.5.0
I'm trying to get a cygwin binary to a tester that has a representative model of their quadplane before they go and fly it on hardware. The artifacts produced by the build server don't contain the cygwin binaries I was expecting.

https://github.com/priseborough/ardupilot/actions/runs/7892856368

2024-02-14 00:35 UTC, tridge commented
> The artifacts produced by the build server don't contain the cygwin binaries I was expecting.

thanks, fix here:
https://github.com/ArduPilot/ardupilot/pull/26215
maybe cherry-pick that into this PR?

2024-02-15 02:44 UTC, tridge commented
@priseborough I've rebased this on the cygwin fix

2024-02-20 12:41 UTC, pompecukor commented
Again thank you, we been collaborating with Paul on this and very happy for the solution. Tested in SITL and we are seeing what we wanted. Looking forward for it in 4.5 as it is a safety "must" for the new forward VTOL speed PR.

2024-02-20 20:39 UTC, priseborough commented
Here are the results from the last round of simulation testing with Q_BCK_PIT_LIM reduced fro 10 to 5 degrees so that the pitch is being limited during high speed braking manoeuvres. This test was into zero wind. During the decel, the nav pitch upper pitch limit FWDT.npulcd is limiting the pitch angle during the intial phase of trhe braking maneouvre. 

<img width="1041" alt="Screenshot 2024-02-21 at 7 22 31 am" src="https://github.com/ArduPilot/ardupilot/assets/3596952/62ebf666-565e-41be-83d8-5355bf943c60">

The velocity loop handles the limiting, noting that during decel at higher airspeeds the deceleration achieved has a lot of rotor momentum and other drag contributing to it which the position controller ignores with its assumption that the only forces are rotor thrust and gravity.

<img width="1022" alt="Screenshot 2024-02-21 at 7 23 13 am" src="https://github.com/ArduPilot/ardupilot/assets/3596952/be98e1bf-4c48-4c2e-907a-23f540bc178f">
<img width="1047" alt="Screenshot 2024-02-21 at 7 23 05 am" src="https://github.com/ArduPilot/ardupilot/assets/3596952/6cf6f61c-7753-4fe8-9199-eb5345139a48">

The same manoeuvre was also tested  into a high wind speed:

<img width="1062" alt="Screenshot 2024-02-21 at 7 18 02 am" src="https://github.com/ArduPilot/ardupilot/assets/3596952/e2c568d4-5303-4e70-8ee7-a918e6ab9147">

The duration of pitch limiting is longer. Note that the vehicle gets blown back a few metres at the end of the braking phase before stopping. This pre-exisiting characteristic.

<img width="1033" alt="Screenshot 2024-02-21 at 7 18 11 am" src="https://github.com/ArduPilot/ardupilot/assets/3596952/e2f7fb36-9223-4770-82ae-5a6203f43804">

<img width="1032" alt="Screenshot 2024-02-21 at 7 18 21 am" src="https://github.com/ArduPilot/ardupilot/assets/3596952/42702dda-df07-439f-9b78-43d5d3f5f5f4">

We are now at a point were flight testing is required.

2024-02-21 01:01 UTC, tridge commented
@priseborough looks good!

2024-02-21 01:03 UTC, tridge requested changes

2024-02-21 01:03 UTC, tridge commented on ArduPlane/quadplane.cpp
> +    // @Description: This sets the maximum number of degrees of back or pitch up in Q modes when the airspeed is at AIRSPEED_MIN and is used to prevent excessive sutructural loads when pitching up de
need to replace AIRSPEED_FBW_MIN with AIRSPEED_MIN in the description in 2 places, also PTCH_LIM_MAX
is now PTCH_LIM_MAX_DEG

2024-02-22 16:14 UTC, pompecukor commented
Now flight tested on real craft @priseborough and @tridge have the logs

2024-02-23 04:26 UTC, tridge approved these changes

2024-02-23 04:26 UTC, merged

2024-02-24 04:45 UTC, priseborough commented
Here are the flight test results from a high QLOITER speed dash into wind with a braking manoeuvre. The up pitch is limited in part of the decel manoeuvre using Q_BCK_PIT_LIM = 5. I would rather leave the value at 10 by default and leave it o users to reduce the value if they think the braking manoeuvre is overloading the wing rather than have a value that could be excessively restrictive and reduce braking performance for other users.

<img width="1032" alt="Screenshot 2024-02-24 at 3 39 16 pm" src="https://github.com/ArduPilot/ardupilot/assets/3596952/a1bcd5a9-5672-4475-a127-a543c300a362">

<img width="1053" alt="Screenshot 2024-02-24 at 3 39 26 pm" src="https://github.com/ArduPilot/ardupilot/assets/3596952/ea3bded8-8f9b-42a7-b81a-7d3f39eaff49">