AP_RCProtocol: CRSF: use subtraction with times, not time+timedelta
ArduPilot/ardupilot pull request #26274
Opened 2024-02-21 01:44 UTC by peterbarker

These methods are kind of unfortunate because for the first `CRSF_RX_TIMEOUT` microseconds they will return true even if we've never seen a receiver.

2024-02-21 06:01 UTC, tridge requested changes

2024-02-21 06:01 UTC, tridge commented on libraries/AP_RCProtocol/AP_RCProtocol_CRSF.h
> +        return AP_HAL::micros() - _last_rx_frame_time_us < CRSF_RX_TIMEOUT;
also needs a != 0 check

2024-02-21 08:24 UTC, peterbarker commented on libraries/AP_RCProtocol/AP_RCProtocol_CRSF.h
> +        return AP_HAL::micros() - _last_rx_frame_time_us < CRSF_RX_TIMEOUT;
Done

2024-02-22 09:48 UTC, andyp1per commented
This was included in https://github.com/ArduPilot/ardupilot/pull/26183

2024-02-22 09:48 UTC, closed without merging