Correct Periph compilation if Check Firmware is not enabled
ArduPilot/ardupilot pull request #26543
Opened 2024-03-17 03:01 UTC by peterbarker

```
Board                    AP_Periph  blimp  bootloader  copter  heli  iofirmware  plane  rover  sub
CubeOrange-periph-heavy  *                                                                     
Durandal                            *      *           *       *                 *      *      *
Hitec-Airspeed           *                                                                     
KakuteH7-bdshot                     *      *           *       *                 *      *      *
MatekF405                           *      *           *       *                 *      *      *
Pixhawk1-1M-bdshot                  *                  *       *                 *      *      *
f103-QiotekPeriph        *                                                                     
f303-Universal           *                                                                     
iomcu                                                                *                         
revo-mini                           *      *           *       *                 *      *      *
skyviper-v2450                                         *                                       
```

app_descriptor is guarded behing AP_CHECK_FIRMWARE_ENABLED, and that's only enabled by default when AP_OPENDRONEID_ENABLED is true.

Given the app descriptor seems to contain useful information useful in places where  AP_OPENDRONEID_ENABLED is false, this is maybe a bit unfortunate.

2024-03-18 20:08 UTC, tridge commented
> app_descriptor is guarded behing AP_CHECK_FIRMWARE_ENABLED, and that's only enabled by default when AP_OPENDRONEID_ENABLED is true.

it is enabled by default on periph.

2024-03-18 20:09 UTC, tridge requested changes

2024-03-18 20:09 UTC, tridge commented on Tools/AP_Periph/AP_Periph.cpp
> +#if AP_CHECK_FIRMWARE_ENABLED
I think we should assert that AP_CHECK_FIRMWARE_ENABLED is enabled in AP_Periph. It is unsafe to have a peripheral without it. We need the crc checking or the user can brick their board

2024-03-19 04:15 UTC, peterbarker reviewed
There's no compiler output change for peripheral firmware after this PR.

2024-03-20 07:01 UTC, tridge commented on Tools/AP_Periph/AP_Periph.cpp
> +#if AP_CHECK_FIRMWARE_ENABLED
why not an assert? periph just won't work properly without it

2024-03-20 07:21 UTC, tridge requested changes
i'd much prefer a #error and no #if

2024-03-20 10:31 UTC, closed without merging