iFlight Blitz F745 Mini
ArduPilot/ardupilot pull request #26789
Opened 2024-04-12 15:31 UTC by andyp1per

https://shop.iflight.com/BLITZ-Mini-F745-Flight-Controller-Pro2142

2024-04-14 16:56 UTC, Hwurzburg commented
why is the Blitz745 in this PR??...its already in its own...will review only the mini portion

2024-04-14 18:34 UTC, andyp1per commented
> why is the Blitz745 in this PR??...its already in its own...will review only the mini portion

Because one is based on the other

2024-04-14 23:07 UTC, Hwurzburg requested changes
All the readme changes I suggested for the BlitzF745 should be made on this one also

2024-04-15 09:52 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/BlitzF745Mini/defaults.parm
> +# setup for LEDs on chan9
Fixed

2024-04-15 13:18 UTC, Hwurzburg approved these changes
the change to base will need to be added....cant you kill the BlitzF745 and just change the commit title to both boards? or is that not allowed....normally I just make sure the PRs are separate and need to be merged in order

2024-04-17 07:34 UTC, merged

2024-04-27 02:44 UTC, rmackay9 commented
This is included in 4.5.2-beta1