Support for MicoAir743
ArduPilot/ardupilot pull request #26854
Opened 2024-04-20 08:34 UTC by Minderring

Support for [MicoAir743](https://micoair.com/index.php/flightcontroller_micoair743/), a flight controller designed and produced by [MicoAir Tech.](https://micoair.com/).

2024-04-21 12:11 UTC, Hwurzburg requested changes
I few minor nits....this autopilot looks very good for small planes!
 I, myself, have two projects coming up for a tiny VTOL and a backpackable wing that this autopilot would be ideal for...when will it be available??

2024-04-21 12:11 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/MicoAir743/README.md
> + - SERIAL6 -> UART7 (ESC Telemetry, DMA-enabled)
```suggestion
 - SERIAL6 -> UART7 (TX only,ESC Telemetry, DMA-enabled)

```

2024-04-21 12:11 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/MicoAir743/README.md
> + - SERIAL7 -> UART8 (DMA-enabled)
```suggestion
 - SERIAL7 -> UART8 (User,DMA-enabled)

```

2024-04-21 12:11 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/MicoAir743/README.md
> +The MicoAir743 supports onboard OSD using OSD_TYPE 1 (MAX7456 driver).
```suggestion
The MicoAir743 supports onboard OSD using OSD_TYPE 1 (MAX7456 driver). Simultaneously,  DisplayPort OSD is available on the HD VTX connector, See below.

```

2024-04-21 12:44 UTC, Minderring commented
> Just a few minor nits....this autopilot looks very good for small planes! I, myself, have two projects coming up for a tiny VTOL and a backpackable wing that this autopilot would be ideal for...when will it be available??

Thanks for your suggestion and MicoAir743 is coming soon.

2024-04-21 13:45 UTC, Hwurzburg commented
let us know when you have completed testing and we can merge
I suggest you send a board to a few devs for support issues if they arise in the future

2024-04-21 13:46 UTC, Hwurzburg approved these changes

2024-04-21 15:52 UTC, Minderring commented
> let us know when you have completed testing and we can merge I suggest you send a board to a few devs for support issues if they arise in the future

Okay. I will do it in few days.

2024-04-22 15:47 UTC, Minderring commented
I have completed testing and it works well.

2024-04-22 23:56 UTC, merged