SDMODEL H7 V2
ArduPilot/ardupilot pull request #26935
Opened 2024-04-30 20:33 UTC by andyp1per

2024-05-01 12:37 UTC, okok125 commented
Thank You . Andy

2024-05-05 14:42 UTC, okok125 commented
[README.md.txt](https://github.com/ArduPilot/ardupilot/files/15213368/README.md.txt)

2024-05-05 15:15 UTC, Hwurzburg requested changes
rather than me correcting the readme, why not just make the README.md have the two  board images that are different from the V1, mention the addition of the compass, and refer directly to the V1 readme file on github....will avoid ommisissions and mistakes

2024-05-05 16:08 UTC, okok125 commented
Change the default value for UART4 to GPS and for UART3 to Telem3. Added built-in IST8310 compass.
It is still possible to add a 2nd compass via SCL and SDA.
[README.md.txt](https://github.com/ArduPilot/ardupilot/files/15213606/README.md.txt)

2024-05-05 18:06 UTC, okok125 commented
> rather than me correcting the readme, why not just make the README.md have the two board images that are different from the V1, mention the addition of the compass, and refer directly to the V1 readme file on github....will avoid ommisissions and mistakes

Everything follows your instructions

2024-05-08 00:33 UTC, peterbarker commented on libraries/AP_HAL_ChibiOS/hwdef/SDMODELH7V2/hwdef.dat
> +# builtin compass on Holybro 6X
Bad comment?

2024-05-08 07:32 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/SDMODELH7V2/hwdef.dat
> +# builtin compass on Holybro 6X
Fixed thanks

2024-05-08 07:32 UTC, andyp1per commented
README updated

2024-05-13 12:08 UTC, Hwurzburg requested changes

2024-05-13 12:08 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/SDMODELH7V2/README.md
> + - SERIAL2 -> UART2 (Telem2) (connected to internal BT module)
```suggestion
 - SERIAL2 -> UART2 (Telem2) (connected to internal BT module, not useable by ArduPilot)
```

2024-05-13 12:10 UTC, Hwurzburg commented
Andy, I can make the readme changes if you wish

2024-05-13 12:45 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/SDMODELH7V2/defaults.parm
> +SERIAL7_PROTOCOL 16
Yes they do

2024-05-13 16:08 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/SDMODELH7V2/README.md
> + - SERIAL3 -> UART3 (Telem3)
```suggestion
 - SERIAL3 -> UART3 (GPS)
```

2024-05-13 16:09 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/SDMODELH7V2/README.md
> + - SERIAL7 -> UART7
```suggestion
 - SERIAL7 -> UART7 RX pin only, ESC telem)
```

2024-05-13 17:18 UTC, Hwurzburg approved these changes

2024-05-14 21:27 UTC, merged