Move IOMCU RC input to AP_RCProtocol library
ArduPilot/ardupilot pull request #26977
Opened 2024-05-04 23:57 UTC by peterbarker

2024-05-05 10:16 UTC, andyp1per requested changes
I struggle to get my head around the subtleties of this - will need careful testing

2024-05-05 10:16 UTC, andyp1per commented on libraries/AP_RCProtocol/AP_RCProtocol_IOMCU.cpp
> +    uint16_t rcin_values[IOMCU_MAX_CHANNELS] {};
This should be IOMCU_MAX_RC_CHANNELS

2024-05-05 22:54 UTC, peterbarker commented on libraries/AP_RCProtocol/AP_RCProtocol_IOMCU.cpp
> +    uint16_t rcin_values[IOMCU_MAX_CHANNELS] {};
Fixed, thanks!

2024-05-26 04:54 UTC, peterbarker commented
Flew this today without issue on both fixed-wing (no IOMCU) and multicopter (with IOMCU)

2025-02-19 04:31 UTC, peterbarker commented
Pixhawk1-1M:

![image](https://github.com/user-attachments/assets/73f2f141-cb9a-4e22-bb41-6f5da2ee5f34)

2025-02-19 23:32 UTC, peterbarker commented
```
Board                    AP_Periph  blimp  bootloader  copter  heli  iofirmware  plane  rover  sub
CubeOrange-periph-heavy  -144              *
CubeRedPrimary                      0      *           0       0                 0      0      0
Durandal                            72     *           72      72                72     72     80
Hitec-Airspeed           -8                *
KakuteH7-bdshot                     -48    *           -48     -48               -48    -48    -48
MatekF405                           -40    *           -40     -40               -40    -40    -40
Pixhawk1-1M-bdshot                  80                 80      72                72     80     72
f103-QiotekPeriph        -8                *
f303-Universal           -8                *
iomcu                                                                -24
revo-mini                           -48    *           -48     -48               -48    -48    -48
skyviper-journey                                       -48
skyviper-v2450                                         -48
```

2025-02-25 07:51 UTC, peterbarker commented
I've now extensively tested the multi-receiver support (again), and we do prioritise the IOMCU over port23, and we move between the inputs as we should.  Failsafes still work appropriately.

2025-02-26 08:21 UTC, tridge commented
@tpwrules can you check that R/C input works on ESP32 for this PR?

2025-03-05 17:39 UTC, tpwrules approved these changes
It took Quite some effort to get the right hardware and stack of patches to show that ESP32 RMT (pulse-based) decoding worked before, but I managed (in partnership with Rhys).

And so I am able to say that merging this patch into that does not break it. Happy to see this cleanup.

2025-03-05 22:54 UTC, peterbarker commented
> It took Quite some effort to get the right hardware and stack of patches to show that ESP32 RMT (pulse-based) decoding worked before, but I managed (in partnership with Rhys).
> 
> And so I am able to say that merging this patch into that does not break it. Happy to see this cleanup.

Many thanks for delving!

2025-03-06 04:47 UTC, merged