Heli Swashplate: Make motor numbers const
ArduPilot/ardupilot pull request #27012
Opened 2024-05-07 21:56 UTC by MattKear

A minor PR to make the motor numbers in heli swashplate const.  This provides additional protection so that we cannot accidently change the motor numbers.

2024-05-07 23:04 UTC, IamPete1 requested changes

2024-05-07 23:04 UTC, IamPete1 commented on libraries/AP_Motors/AP_MotorsHeli_Swash.cpp
> +    _motor_num{mot_0, mot_1, mot_2, mot_2}
```suggestion
    _motor_num{mot_0, mot_1, mot_2, mot_3}
```

2024-05-08 17:50 UTC, IamPete1 approved these changes

2024-05-09 19:19 UTC, bnsgeyer approved these changes
Thanks! Merged

2024-05-09 19:19 UTC, merged