AP_HAL_ChibiOS/hwdef: PodmanH7 FC board target
ArduPilot/ardupilot pull request #27035
Opened 2024-05-10 08:58 UTC by burgeruser

Burgeruser will release a new flight controller (PodmanH7).
we added a board definition file and etc.

Thank you.

![PodmanH7-pinout](https://github.com/ArduPilot/ardupilot/assets/93718551/5614bd48-795e-4f4c-ab0a-f5a45614754f)

[README.md](https://github.com/ArduPilot/ardupilot/files/15272782/README.md)

2024-05-10 14:08 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/PodmanH7/i2c_gpio.inc
> +PE14 TIM1_CH4 TIM1 PWM(1) GPIO(50)
You have an H7 you will want to make some of these bi-directional dshot capable

2024-05-10 14:08 UTC, andyp1per requested changes
Add bi-dir support

2024-05-10 14:55 UTC, burgeruser commented
Thank you. 
It's interesting! Just now, I was indeed testing a bi-directional ESC (Electronic Speed Controller), and after thorough testing, I confirmed that it is indeed viable. The ESC can successfully communicate via the D-Shot protocol in both directions, enabling us to retrieve the motor's RPM (Revolutions Per Minute) information.

2024-05-11 00:34 UTC, peterbarker commented
From a glance I'd suggest JST-GH and CAN, at least.

2024-05-11 01:03 UTC, burgeruser commented
> From a glance I'd suggest JST-GH and CAN, at least.

JST-GH is a highly professional interface, equipped with self-locking functionality. Initially, my design utilized the JST-GH1.25 connector, along with a CAN interface. However, for the sake of ease of use for beginners, many of whom are familiar with the Pixhawk design, I aimed to make it more user-friendly. My intention with this version of the flight controller is to facilitate a smoother introduction to Ardupilot for newcomers. Currently, I am working on an extensive Wiki tutorial to encourage more people to join the Ardupilot community, expanding its pool of contributors.

2024-05-17 06:28 UTC, closed without merging