Adds Flywoo/Goku F405 HD 1-2S ELRS AIO v2 flight controller support
ArduPilot/ardupilot pull request #27036
Opened 2024-05-10 09:00 UTC by rotorman

Adds support for https://flywoo.net/products/goku-f405-hd-1-2s-elrs-aio-v2

2024-05-10 14:05 UTC, andyp1per requested changes
This looks almost identical to FLYWOO_F405S_AIO if so can you include that defn and just redefine the parts that need it.

2024-05-18 08:53 UTC, andyp1per approved these changes

2024-05-20 23:43 UTC, tridge commented
pending review by @Hwurzburg

2024-05-20 23:43 UTC, tridge commented
needs commit msg cleanup

2024-05-21 16:24 UTC, rotorman commented
> needs commit msg cleanup

Should I just leave the first sentence, or do you have something else in mind?

2024-05-22 08:35 UTC, andyp1per commented
> > needs commit msg cleanup
> 
> Should I just leave the first sentence, or do you have something else in mind?

https://ardupilot.org/dev/docs/submitting-patches-back-to-master.html#preparing-commits

2024-05-23 23:53 UTC, Hwurzburg requested changes

2024-05-23 23:53 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/FlywooF405HD-AIOv2/hwdef-bl.dat
> +APJ_BOARD_ID 1180
```suggestion
APJ_BOARD_ID 1180

#required to prevent ELRS from changing modes at boot
PD6 USART2_RX USART2 OUTPUT HIGH
```

2024-05-23 23:53 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/FlywooF405HD-AIOv2/defaults.parm
> +SERIAL1_PROTOCOL 23
can be removed...SERIAL1 protocol already defined in hwdef from included V1

2024-05-23 23:53 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/FlywooF405HD-AIOv2/README.md
> +|SERIAL2|TX2/RX2|USART2 (GPS, DMA on RX)|
```suggestion
|SERIAL2|TX2/RX2|USART2 (Telem, DMA on RX)|
```

2024-05-23 23:53 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/FlywooF405HD-AIOv2/README.md
> +|SERIAL3|TX3/RX3|USART3 (RC Input/Output, DMA-enabled)|
```suggestion
|SERIAL3|TX3/RX3|USART3 (USER, DMA-enabled)|
```

2024-05-23 23:53 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/FlywooF405HD-AIOv2/README.md
> +|SERIAL4|TX4/RX4|UART4 (TELEM)|
```suggestion
|SERIAL4|TX4/RX4|UART4 (GPS)|
```

2024-05-23 23:53 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/FlywooF405HD-AIOv2/README.md
> +|SERIAL6|TX6/RX6|UART6 (VTX)|
```suggestion
|SERIAL6|TX6/RX6|UART6 (DisplayPort)|
```

2024-05-23 23:53 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/FlywooF405HD-AIOv2/README.md
> +RC input is configured on UART1 or UART3, which supports serial RC protocols. This board does not support PPM.
```suggestion
RC input is configured  as ELRS by default using UART1. Alternatively, UART3 could be used for RC inputs other than ELRS but its protocol would need to be changed to 23 and UART1 disabled by setting its protocol as -1. This board does not support PPM.
```

2024-05-23 23:53 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/FlywooF405HD-AIOv2/README.md
> +
```suggestion
.. note:: for users migrating from BetaflightX quads, the first four outputs M1-M4 have been configured for use with existing motor wiring using these default parameters:

- :ref:`FRAME_CLASS<FRAME_CLASS>` = 1 (Quad)
- :ref:`FRAME_TYPE<FRAME_TYPE>` = 12 (BetaFlightX) 
```

2024-05-24 11:39 UTC, Hwurzburg requested changes
I will squash and library split for you and mark for devcal once this last change it made

2024-05-24 11:39 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/FlywooF405HD-AIOv2/defaults.parm
> +RC_OPTIONS 8704
sorry somehow these changes (which match the readme changes) that make it match the wiring diagram got lost during my review
```suggestion
RC_OPTIONS 8704
OSD_TYPE 5
SERIAL3_PROTOCOL -1
SERIAL2_PROTOCOL 2
SERIAL6_PROTOCOL 42
```

2024-05-24 21:36 UTC, Hwurzburg approved these changes
squashed,rebased, library split....think its ready for Devcall if @andyp1per agrees

2024-05-27 23:57 UTC, merged