AP_Bootloader: Reserve ID range for UAV-DEV GmbH
ArduPilot/ardupilot pull request #27105
Opened 2024-05-20 18:12 UTC by mirkix

Reserve ID range for UAV-DEV GmbH

2024-05-20 18:58 UTC, Hwurzburg requested changes

2024-05-20 18:58 UTC, Hwurzburg commented on Tools/AP_Bootloader/board_types.txt
> +# IDs 5220-5239 reserved for UAV-DEV GmbH
should put these down lower in numerical order to allow someone in the future to easily determine whats available

2024-05-20 22:37 UTC, peterbarker commented on Tools/AP_Bootloader/board_types.txt
> +AP_HW_UAV-DEV-Sensorboard-G4         5526
These ones are out-of-order numerically.  Did you mean to have all of these consecutive?

2024-05-21 11:46 UTC, peterbarker approved these changes
LGTM

2024-05-21 14:17 UTC, Hwurzburg approved these changes

2024-05-22 01:45 UTC, merged