Tools: Scripts: run_lua_language_check: give hint about github-release-downloader
ArduPilot/ardupilot pull request #27112
Opened 2024-05-21 00:04 UTC by IamPete1

This gives a hint about how to fix the missing import.

2024-05-22 08:11 UTC, tridge requested changes

2024-05-22 08:11 UTC, tridge commented on Tools/scripts/run_lua_language_check.py
> +            print("Install with: python -m pip install github-release-downloader")
should be: python3 -m pip ....

2024-05-22 12:59 UTC, IamPete1 commented on Tools/scripts/run_lua_language_check.py
> +            print("Install with: python -m pip install github-release-downloader")
done

2024-05-28 00:03 UTC, peterbarker approved these changes

2024-05-28 00:03 UTC, tridge approved these changes

2024-05-28 00:04 UTC, merged