AP_DDS: Use common quaternion initialization function
ArduPilot/ardupilot pull request #27161
Opened 2024-05-26 00:56 UTC by Ryanf55

A common initialization function. Follow up to the previous PR.
https://github.com/ArduPilot/ardupilot/pull/27140#discussion_r1614957993

2024-05-28 00:28 UTC, tridge requested changes

2024-05-28 00:28 UTC, tridge commented on libraries/AP_DDS/AP_DDS_Client.cpp
> +static inline void initialize(geometry_msgs_msg_Quaternion& q)
should not be inline

2024-05-28 06:12 UTC, Ryanf55 commented
Needs squash  unless you can autosquash on merge.

2024-05-29 02:52 UTC, Ryanf55 commented
> Needs squash unless you can autosquash on merge.

Squashed. Ready for final check.

2024-05-30 06:57 UTC, merged