Updated the README
ArduPilot/ardupilot pull request #27173
Opened 2024-05-27 10:52 UTC by tsubashchandar

2024-05-30 08:41 UTC, tsubashchandar commented
@Hwurzburg  can you review this

2024-05-30 14:51 UTC, Hwurzburg requested changes

2024-05-30 14:51 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/PixFlamingo-F767/README.md
> +**SERIAL5**
this is a 5 pin, not 6 pin connector as shown on pinout diagram

2024-06-05 00:23 UTC, peterbarker reviewed
Commit message needs to be fixed - something like:
`hwdef: update PixFlamingo_f767 README`

2024-06-06 12:03 UTC, Hwurzburg approved these changes
squashed the commits for you...commit is now in proper form

2024-06-10 22:42 UTC, merged