LUA: Add a function to retrieve the landed state
ArduPilot/ardupilot pull request #27222
Opened 2024-06-02 08:19 UTC by muramura

I want to get the value of LANDED_STATE to determine the landing status in LUA. I will add a method to retrieve the LANDED_STATE. This ticket is related to #27221 .

2024-06-02 15:34 UTC, IamPete1 requested changes

2024-06-02 15:34 UTC, IamPete1 commented on libraries/AP_Scripting/docs/docs.lua
> +function vehicle:get_landed_state() end
Full descriptions please. 

You can enumerate the return states like this:

https://github.com/ArduPilot/ardupilot/blob/eb8eeba8516f5fc3a83b82a7f03235c2ca6578ae/libraries/AP_Scripting/docs/docs.lua#L1416-L1423

2024-06-02 17:46 UTC, olliw42 commented
this is a bit strange. There is already a landed_state() in GCS_MAVlink which does exactly the same, so it's a good part code duplication. Also, why should only Copter get this lua. 

Note that there had been this PR https://github.com/ArduPilot/ardupilot/pull/25459, proposing to move em to the vehicle class, which should also adress this here.

2024-06-03 15:41 UTC, olliw42 commented
you do not need to use either to call it in lua
the function you define newly here is exactly identical to the function I mentioned is already there. Whatever name you give it, it doesn't change that fact :)

2024-06-03 17:57 UTC, muramura commented
I have implemented the process to determine the LAND state in the COPTER.
By doing this, multiple methods are no longer needed.
I have added a description of the return value to the LUA function.

2024-09-04 13:39 UTC, closed without merging