AP_Math: added comments and a test for euler ordering
ArduPilot/ardupilot pull request #27329
Opened 2024-06-18 21:52 UTC by tridge

our main euler functions did not have a comment on the ordering convention

2024-06-18 22:51 UTC, rmackay9 approved these changes

2024-06-18 23:36 UTC, peterbarker approved these changes

2024-06-18 23:36 UTC, peterbarker commented on libraries/AP_Math/matrix3.h
> +      create a rotation matrix from Euler angles in 321 euler orderin
```suggestion
      create a rotation matrix from Euler angles in 321 euler ordering
```

2024-06-19 07:40 UTC, andyp1per commented
Having scratched my head against this for some time it would be great to see the additional clarifying commentary:

- Say whether rotations are intrinsic or extrinsic? (https://github.com/ArduPilot/ardupilot/pull/27335)
- Say what the positive direction is for each axis
- This doc in matrix3.cpp now gives a 404 - http://gentlenav.googlecode.com/files/EulerAngles.pdf

2024-06-19 07:43 UTC, andyp1per reviewed
I think its great as far as it goes, but possible could do with some additional commentary

2024-06-19 13:09 UTC, isso11 commented
> * positive direction is for each axis
I think so too. In the context of Euler angles and the North-East-Down (NED) coordinates frame:
Yaw (ψ): Positive is clockwise when viewed from above, around the Down (Z) axis.
Pitch (θ): Positive is nose up, around the East (Y) axis.
Roll (𝜙): Positive is right wing down, around the North (X) axis.

2024-06-19 21:27 UTC, andyp1per commented
@tridge I manually checked one of these and either euler 321 means something different to what I think it does or these rotations are euler 123. An easy example take ROTATION_ROLL_90_YAW_90, this means roll 90 followed by yaw 90. The code swaps around vector values so that [x, y, z] -> [z, x, y] which indeed is roll 90 followed by yaw 90 it is *not* yaw 90 followed by roll 90. So either the meaning of euler 321 is very weird - which I am prepared to believe - or your documentation is actually wrong.

2024-06-19 21:29 UTC, andyp1per requested changes
Need to resolve my very confused understanding of the meaning of euler 321

2024-06-19 21:51 UTC, isso11 commented
> euler 321

Aren't these rotations basically for transformations between body fixed and local inertial NED frames? If so, then the rotations 321 should, by standard definition, mean  [Yaw (3, around the 3rd axis, Z), Pitch (2, around the 2nd axis, Y), Roll(1, around the 1st axis, X)] in that order.

2024-06-20 10:45 UTC, andyp1per commented
> Aren't these rotations basically for transformations between body fixed and local inertial NED frames? If so, then the rotations 321 should, by standard definition, mean [Yaw (3, around the 3rd axis, Z), Pitch (2, around the 2nd axis, Y), Roll(1, around the 1st axis, X)] in that order.

That is my understanding

2024-06-21 11:03 UTC, Georacer commented
> That is my understanding

Mine as well.

2024-06-21 23:22 UTC, tridge commented
@andyp1per @Georacer see the rotate_ordered() function in this PR

2024-06-21 23:24 UTC, tridge commented
> * Say whether rotations are intrinsic or extrinsic?

as demonstrated by the rotate_ordered() function it is intrinsic

2024-06-21 23:25 UTC, tridge commented
> * This doc in matrix3.cpp now gives a 404

it is common that URLs like this disappear. If we can find the PDF we could put it in https://github.com/ArduPilot/Datasheets

2024-06-22 08:54 UTC, andyp1per commented
@tridge I have pushed a test that fails to prove my point.

2024-06-22 09:07 UTC, tridge commented on libraries/AP_Math/matrix3.h
> +      create a rotation matrix from Euler angles in 321 euler orderin
changed

2024-06-22 09:09 UTC, tridge commented
@andyp1per I've found the original EulerAngles.pdf from Bill Premerlani and added it to out Datasheets repo and updated the link in the code in this PR

2024-07-24 08:26 UTC, peterbarker commented
Ping @andyp1per can we merge this one?

2024-07-26 20:40 UTC, andyp1per approved these changes

2024-07-26 23:27 UTC, peterbarker commented
Merged, thanks!

2024-07-27 01:14 UTC, merged