Constellation choice for septentrio gnss
ArduPilot/ardupilot pull request #27373
Opened 2024-06-24 14:05 UTC by chiara-septentrio

# Changes
## General overview
This pull request adds the feature to chose the system used for Septentrio receivers through the GPS_GNSS_MODE parameter. 
Any configuration is possible outside of IMES only (see below) and will take effect on start-up.

## Special case : IMES
The IMES system is not implemented as there is no feature for it on the Septentrio receivers. The same way, NavIc and L-Band that can be configured on the receiver but are not present in the current parameters are not implemented.
If the user choses to use only IMES, it is treated as an absence of choice and the system is left as is.

## SBAS parameter 
The Septentrio driver also uses the GPS_SBAS_MODE parameter, this parameter takes precedence over this new feature. To take only this new feature into account, the parameter can be left as NoChange. Redundant choices should not cause any issue.

## Tests
This new feature has been tested with the CubeOrangePlus connected to one mosaic-go through its com2 port, and the copter build. It has been tested with all possible configurations. It has also been tested to work as intended with the SBAS parameter.
RxControl has been used to monitor the receiver and confirm the drop in satellites used corresponded to the right systems.

  Example of corresponding parameter and receiver configuration:
![image](https://github.com/ArduPilot/ardupilot/assets/165775238/406570ce-dfd0-4c90-9a1a-799fa4ae3fb0)
*Parameter on mission planner*

![image](https://github.com/ArduPilot/ardupilot/assets/165775238/961d1af0-7a2f-44a9-8394-083fc4fcb3b4)
*Configuration on RxControl*

2024-06-24 14:22 UTC, andyp1per requested changes
Commits need to be squashed into a single commit with a commit message that starts with "AP_GPS: "

2024-06-25 07:10 UTC, chiara-septentrio commented
The commit issue has been amended

2024-07-15 09:44 UTC, chiara-septentrio commented
I updated the pull request to the main, would it be possible to have a new review @andyp1per ?

2024-07-18 15:27 UTC, andyp1per approved these changes
Looks ok to me - what testing has been done?

2024-07-19 08:35 UTC, chiara-septentrio commented
I've tested it with a CubeOrangePlus and mosaic-go, all configurations worked as expected (if you want to test it yourself, just note GLONASS alone will not provide PVT but it's expected with the Seprentrio receivers)

2024-07-23 00:28 UTC, tridge requested changes

2024-07-23 00:28 UTC, tridge commented on libraries/AP_GPS/AP_GPS_SBF.cpp
> +                                        config_string=nullptr;
this looks like a memory leak, we should add a private fn free_config_string() which does this:

 ```
 void AP_GPS_SBF::free_config_string(void)
{
  free(config_string);
  config_string = nullptr;
}
```

2024-07-23 00:32 UTC, peterbarker approved these changes

2024-07-23 00:32 UTC, tridge approved these changes

2024-07-23 00:32 UTC, merged