Allow full compass calibration with location sources other than GPS
ArduPilot/ardupilot pull request #27409
Opened 2024-06-28 02:51 UTC by Williangalvani

Not having a GPS connected currently causes compass calibration to skip the fix_radius step, which prevents using the WMM in the ekf.

I also added a warning so users can know something is wrong.

this is a step towards fix #18229, and is extracted from #26506

2024-07-02 00:26 UTC, tridge approved these changes

2024-07-02 00:29 UTC, tridge requested changes

2024-07-02 00:29 UTC, tridge commented on libraries/AP_Compass/CompassCalibrator.cpp
> +    if (!AP::ahrs().get_location(loc)) {
i think we need to accept either AHRS location or GPS location, so lack of healthy compass doesn't prevent compass calibration to fix the issue

2024-07-02 00:29 UTC, rmackay9 commented on libraries/AP_Compass/CompassCalibrator.cpp
> +        gcs().send_text(MAV_SEVERITY_WARNING, "MagCal: No location, fix_radius skipped");
We should probably use GCS_SEND_TEXT and I think we should check the prefix is consistent with other text messages from this library.

2024-07-02 00:30 UTC, tridge commented on libraries/AP_Compass/CompassCalibrator.cpp
> +    if (!AP::ahrs().get_location(loc)) {
could also do AP::ahrs().get_origin()

2024-07-09 00:13 UTC, tridge approved these changes

2024-07-09 00:13 UTC, merged