AP_NavEKF3: log mag fusion selection to XKMF
ArduPilot/ardupilot pull request #27430
Opened 2024-07-01 14:35 UTC by Williangalvani

This helps us better understand what kind of yaw fusion the ekf is doing.
It was very useful while debugging  #18229 

No real hope of merging this one straight away, but I do like the functionality of it a lot.

2024-07-02 01:11 UTC, tridge requested changes

2024-07-02 01:11 UTC, tridge commented on libraries/AP_NavEKF3/AP_NavEKF3_MagFusion.cpp
> +    const struct log_XKMF pkt{
quite an expensive way to log 1 byte, could be a field in XKFS, or could jst document how to tell using XKF3.IYAW vs XKF3.IMX/IMY/IMZ

2024-07-09 12:45 UTC, peterbarker requested changes

2024-07-09 12:45 UTC, peterbarker commented on libraries/AP_NavEKF3/LogStructure.h
> +    LOG_XKMF_MSG, \
No longer required?

2024-07-09 13:27 UTC, Williangalvani commented on libraries/AP_NavEKF3/LogStructure.h
> +    LOG_XKMF_MSG, \
oops, removed

2024-07-11 04:22 UTC, peterbarker approved these changes

2024-07-11 06:16 UTC, merged