SITL: add simulated slung payload
ArduPilot/ardupilot pull request #27536
Opened 2024-07-12 06:32 UTC by rmackay9

This adds SITL support for a slung payload and is implemented similarly to how the Ship landing ship was implemented.

The payload can be enabled by setting a new SIM_SLUP_ENABLE parameter to 1.  In addition the payload's weight, line length and air resistance (aka drag) can also be adjusted through new parameters

This [Physics Classroom wiki page](https://www.physicsclassroom.com/class/waves/Lesson-0/Pendulum-Motion) was used as a reference to come up with this method for updating the payload and vehicle's movements:

1. update the payload's position, velocity using the previous iterations acceleration
2. check that the payload does not fall below the terrain
3. check if the line is taught and that the payload does not move more than the line length from the vehicle
4. calculate gravity and drag forces on the payload
5. calculate the tension force between the payload and vehicle including force countering gravity, drag and centripetal force
6. update the payload's acceleration using the sum of the above forces
7. update the vehicle's acceleration using the opposite of the above forces

2024-07-23 00:41 UTC, tridge commented on libraries/SITL/SIM_SlungPayload.cpp
> +    AP_GROUPINFO("ENABLE",  1, SlungPayloadSim,  enable, 0),
mark as an enable param?

2024-07-23 00:46 UTC, peterbarker requested changes

2024-07-23 05:38 UTC, rmackay9 commented on libraries/SITL/SIM_SlungPayload.cpp
> +    AP_GROUPINFO("ENABLE",  1, SlungPayloadSim,  enable, 0),
thanks, done in a follow-up commit

2024-07-23 05:39 UTC, rmackay9 commented on libraries/SITL/SIM_Multicopter.cpp
> +    // add forces from slung payload
great, thanks.  ifs added

2024-07-23 05:39 UTC, rmackay9 commented on libraries/SITL/SIM_SlungPayload.cpp
> +    // @DisplayName: Slung Payload MAVLink sysmtem ID
spelling fixed, thanks!

2024-07-23 05:40 UTC, rmackay9 commented on libraries/SITL/SIM_Aircraft.cpp
> +#if AP_SIM_SLUNGPAYLOAD_ENABLED
thanks, moved to outside of fn

2024-07-24 07:07 UTC, tridge approved these changes

2024-07-24 07:09 UTC, merged