Do PPP networking between Primary and Secondary MCU
ArduPilot/ardupilot pull request #27577
Opened 2024-07-17 06:55 UTC by bugobliterator

* also adds support for TCP reconnection

2024-07-17 08:38 UTC, tridge requested changes
nice to see this come together!

2024-07-17 08:40 UTC, tridge commented on libraries/AP_HAL_ChibiOS/UARTDriver.h
> +        bool low_noise_line;
can this be under ifdef?

2024-07-24 06:31 UTC, bugobliterator commented on libraries/AP_HAL_ChibiOS/UARTDriver.h
> +        bool low_noise_line;
fixed

2024-07-24 07:49 UTC, tridge approved these changes

2024-07-24 23:37 UTC, merged