AP_InertialSensor: Check the gyro/accel id has not been previously registered
ArduPilot/ardupilot pull request #27584
Opened 2024-07-17 21:39 UTC by joshanne

Discovered on CubeOrangePlus BG3 in a production environment.

On the very first boot of the CubeOrangePlus-BG3 after a parameter wipe, 4 IMU instances are registered. These register under the Parameters with the IDs:
* INS_ACC_ID       3867682
* INS_ACC2_ID      3867938
* INS_ACC3_ID      3867658
* INS4_ACC_ID      3867658 **<< NOTICE DUPLICATE OF INS_ACC3_ID**

On subsequent boots, it appears the macro `ADD_BACKEND_AUX` filters the AUX IMU so it is never probed or registered in the first place.

The problem arises if you take the BG3 out of the box, flash AP and go straight into an accelcal, since IMU4 is registered, it calibrates for IMU4 as well. The next reboot then fails pre-arm check requiring 3D Accel Calibration (even though it's already been performed, because now IMU4 is not present).

I've tested this on CubeOrangePlus BG _**and**_ BG3 - and all the IMUs I expect to be present are present.

2024-07-18 07:51 UTC, andyp1per approved these changes

2024-07-23 02:04 UTC, tridge requested changes

2024-07-23 02:04 UTC, tridge commented on libraries/AP_InertialSensor/AP_InertialSensor.cpp
> +            GCS_SEND_TEXT(MAV_SEVERITY_WARNING, "Failed to register - gyro id %u already registered", unsigned(id));
we should drop the warnings

2024-07-23 02:18 UTC, joshanne commented
To be very clear - this occurs because on the COP-BG3, the third IMU (3867658) is also the same ID as the Aux IMU (3867658).

On the first boot, there is no filtering of what is added to the probe list, because there are no parameters in storage to filter against. On subsequent boots, the filtering takes place normally.

HOWEVER, if you accelcal on that very first boot after a parameter wipe, you calibrate the "_4_" (3 is real, 1 is false and a duplicate detected) IMUs. Then on subsequent boots, prearm will fail because only the 3 real IMUs are detected (thanks to filtering of the probe list).

@bugobliterator - I'm unavailable to discuss during the devcall tomorrow, but feel free to discord message me privately or in our partner chat

2024-07-23 02:28 UTC, joshanne commented on libraries/AP_InertialSensor/AP_InertialSensor.cpp
> +            GCS_SEND_TEXT(MAV_SEVERITY_WARNING, "Failed to register - gyro id %u already registered", unsigned(id));
Warnings have been removed.

2024-07-24 23:49 UTC, merged

2024-08-19 00:36 UTC, rmackay9 commented
This is included in 4.5.6-beta1

2024-08-19 01:00 UTC, joshanne commented
Thanks!