Fix for unhandled TKOFF_THR_MAX
ArduPilot/ardupilot pull request #27693
Opened 2024-07-29 20:27 UTC by Georacer

This patches a bug that was introduced via https://github.com/ArduPilot/ardupilot/pull/27174.

It fixes an unhandled case of `TKOFF_THR_MAX=0`, where `THR_MAX` would not be sourced as a value for the minimum throttle limit during takeoff.
The relevant conditions are:
- TKOFF_OPTIONS=0 (default)
- TKOFF_THR_MAX=0 (default)

This would result in incorrect backing-off of the minimum throttle during the climb, which @Hwurzburg spotted:
![image](https://github.com/user-attachments/assets/319b1dac-8ad4-44a1-a04e-6627f033749e)

Now it behaves as it should:
![image](https://github.com/user-attachments/assets/56cefdfe-c75b-4590-89ec-b0efff4d6e1a)
Log: https://www.dropbox.com/scl/fi/akdqr9o5niv3qleexh3yd/122221_TakeoffTakeoff4.bin?rlkey=o9uykk6cm7785oxctkj17txxq&dl=0

---
Side-note:

I notice that there was significant pitch and throttle oscillation in Henry's log.
I don't think this is related to #27174, as the oscillation persists even after TAKEOFF mode has finished climbing, where TECS operates in a regime which I haven't edited.
I believe that a sudden pitch-down and throttle-cut was triggered (because of this bug) during the climb and the default tuning and model physics would yield bad control behaviour.

2024-07-30 07:39 UTC, Hwurzburg commented
This makes it safe from my sitl testing...
in another PR we need to get the model fixed so as not to go unstable
and , more importantly, get the takeoff leveling working again to prevent the overshoots in altitude on auto takeoffs

2024-07-30 07:39 UTC, Hwurzburg approved these changes

2024-07-30 07:42 UTC, peterbarker commented
Pretty sure this is breaking several Plane autotests.

2024-07-30 10:18 UTC, Georacer commented
@peterbarker I believe the latest commit fixed it.
It was a case of the minimum throttle during a transition being set to TAKEOFF_THR_MAX. This is because in servos.cpp the transition throttle limits were historically being treated the same as the takeoff throttle limits. And this resulted in a back-transition getting a **minimum** throttle allowance of TAKEOFF_THR_MAX.

For now I have reverted to the behaviour before #27174.
@tridge I'll have to find another way to introduce the minimum throttle during a transition (and find a way to tell between a forward and backward transition).

The failing autotests passed locally, but let's see what the CI server says about it.

2024-07-30 22:26 UTC, tridge requested changes
i think we can make min takeoff throttle work for fwd transition

2024-07-30 22:26 UTC, tridge commented on ArduPlane/servos.cpp
> +    if (quadplane.in_transition()) {
why not this?
![image](https://github.com/user-attachments/assets/d629479a-0e16-443b-8c74-8bbf3be24e7d)

2024-07-30 22:27 UTC, tridge commented on ArduPlane/servos.cpp
> +    if (quadplane.in_transition()) {
note that in_transition() is only true for fwd transitions

2024-07-31 08:23 UTC, tridge approved these changes

2024-07-31 08:23 UTC, tridge commented on ArduPlane/servos.cpp
> +    if (quadplane.in_transition()) {
turns out in_transiton() is true for tailsitters all the time, which doesn't seem right
I think we need a new in_forward_transition() which is only true for the fwd transition

2024-07-31 08:23 UTC, merged