ArduCopter: add logging for land detector
ArduPilot/ardupilot pull request #27703
Opened 2024-07-30 08:15 UTC by peterbarker

Logging is done whenever either the count or the flags change, but not > 50Hz

This is using `test.Copter.Landing`:
![image](https://github.com/user-attachments/assets/a55140bb-7516-4541-b4e1-dce3aa512b1b)
![image](https://github.com/user-attachments/assets/9f6f5829-75a6-4bcb-b51f-b7f7021a5090)

```
2024-07-30 17:54:22.905: LDET
    TimeUS: 178104563 µs
    Flags: 242 
      ! LANDED
        LANDED_MAYBE
      ! LANDING
      ! STANDBY_ACTIVE
        WOW
        RANGEFINDER_BELOW_2M
        DESCENT_RATE_LOW
        ACCEL_STATIONARY
      ! LARGE_ANGLE_ERROR
      ! MOTOR_AT_LOWER_LIMIT
      ! THROTTLE_MIX_AT_MIN
    Count: 361 
2024-07-30 17:54:22.925: LDET
    TimeUS: 178124555 µs
    Flags: 242 
      ! LANDED
        LANDED_MAYBE
      ! LANDING
      ! STANDBY_ACTIVE
        WOW
        RANGEFINDER_BELOW_2M
        DESCENT_RATE_LOW
        ACCEL_STATIONARY
      ! LARGE_ANGLE_ERROR
      ! MOTOR_AT_LOWER_LIMIT
      ! THROTTLE_MIX_AT_MIN
    Count: 369 
2024-07-30 17:54:22.945: LDET
    TimeUS: 178144547 µs
    Flags: 242 
      ! LANDED
        LANDED_MAYBE
      ! LANDING
      ! STANDBY_ACTIVE
        WOW
        RANGEFINDER_BELOW_2M
        DESCENT_RATE_LOW
        ACCEL_STATIONARY
      ! LARGE_ANGLE_ERROR
      ! MOTOR_AT_LOWER_LIMIT
      ! THROTTLE_MIX_AT_MIN
    Count: 377 
2024-07-30 17:54:22.965: LDET
    TimeUS: 178164539 µs
    Flags: 242 
      ! LANDED
        LANDED_MAYBE
      ! LANDING
      ! STANDBY_ACTIVE
        WOW
        RANGEFINDER_BELOW_2M
        DESCENT_RATE_LOW
        ACCEL_STATIONARY
      ! LARGE_ANGLE_ERROR
      ! MOTOR_AT_LOWER_LIMIT
      ! THROTTLE_MIX_AT_MIN
    Count: 385 
2024-07-30 17:54:22.985: LDET
    TimeUS: 178184531 µs
    Flags: 242 
      ! LANDED
        LANDED_MAYBE
      ! LANDING
      ! STANDBY_ACTIVE
        WOW
        RANGEFINDER_BELOW_2M
        DESCENT_RATE_LOW
        ACCEL_STATIONARY
      ! LARGE_ANGLE_ERROR
      ! MOTOR_AT_LOWER_LIMIT
      ! THROTTLE_MIX_AT_MIN
    Count: 393 
2024-07-30 17:54:23.005: LDET
    TimeUS: 178204523 µs
    Flags: 243 
        LANDED
        LANDED_MAYBE
      ! LANDING
      ! STANDBY_ACTIVE
        WOW
        RANGEFINDER_BELOW_2M
        DESCENT_RATE_LOW
        ACCEL_STATIONARY
      ! LARGE_ANGLE_ERROR
      ! MOTOR_AT_LOWER_LIMIT
      ! THROTTLE_MIX_AT_MIN
    Count: 0 
2024-07-30 17:54:23.025: LDET
    TimeUS: 178224515 µs
    Flags: 19 
        LANDED
        LANDED_MAYBE
      ! LANDING
      ! STANDBY_ACTIVE
        WOW
      ! RANGEFINDER_BELOW_2M
      ! DESCENT_RATE_LOW
      ! ACCEL_STATIONARY
      ! LARGE_ANGLE_ERROR
      ! MOTOR_AT_LOWER_LIMIT
      ! THROTTLE_MIX_AT_MIN
    Count: 0 
```

2024-07-31 07:25 UTC, tridge requested changes
looks reasonable (apart from magic 16), but needs a look by @rmackay9

2024-07-31 07:25 UTC, tridge commented on ArduCopter/land_detector.cpp
> +    uint8_t logging_flags = 16;
you like 16?

2024-08-01 00:13 UTC, peterbarker commented on ArduCopter/land_detector.cpp
> +    uint8_t logging_flags = 16;
Fixed

2024-08-05 23:28 UTC, tridge approved these changes

2024-08-05 23:28 UTC, rmackay9 approved these changes

2024-08-05 23:28 UTC, merged