Disable LTM and Hott telem by default
ArduPilot/ardupilot pull request #27717
Opened 2024-07-31 09:22 UTC by peterbarker

We have a custom build server for seldom-used features

2024-07-31 09:24 UTC, tridge requested changes
needs to build on SITL

2024-07-31 09:28 UTC, peterbarker commented
> needs to build on SITL

Done

2024-07-31 10:56 UTC, amilcarlucas approved these changes

2024-08-05 23:29 UTC, tridge approved these changes

2024-08-05 23:30 UTC, merged