Add support for Orionv1
ArduPilot/ardupilot pull request #27723
Opened 2024-07-31 14:21 UTC by peterbarker

2024-09-10 11:55 UTC, Hwurzburg requested changes
needs images,pinout, readme

2024-11-06 13:15 UTC, Hwurzburg commented
@peterbarker is this still active? needs info

2024-12-25 16:37 UTC, Hwurzburg commented
@peterbarker ping again

2025-05-13 23:59 UTC, closed without merging

2025-05-13 23:59 UTC, peterbarker commented
No response from vendor, closing this one.