TECS improvements
ArduPilot/ardupilot pull request #27758
Opened 2024-08-05 15:45 UTC by Georacer

This PR fixes TECS oscillations that would occur once mode TAKEOFF would reach `TKOFF_ALT`.

## Changes

1. `TECS::set_pitch_max_limit()` is now split into `TECS::set_pitch_max()` and `TECS::set_pitch_min()`. Its usage in `quadplane.cpp` has been modified accordingly.
2. `mode_takeoff.cpp` is now prevented from switching behaviours from past `TKOFF_ALT`-2m back to climb behaviour. This would cause behaviour switching if the plane would drop slightly lower than 2m from `TKOFF_ALT`.
3. There are many occasions were TECS is overridden both in pitch and throttle. When that happens, TECS is effectively inactive and will reset itself.
4. Changed behaviour of `TECS_PITCH_MIN` to match description.

2024-08-05 15:54 UTC, Georacer commented
This is the new behaviour of arming in mode TAKEOFF in stock SITL:
![image](https://github.com/user-attachments/assets/0e212431-51bd-4cb0-88f3-0c3ae5503092)

2024-08-07 20:09 UTC, Georacer commented on libraries/AP_TECS/AP_TECS.cpp
> +
The offset is now a little smarter:
If TECS is externally overridden, there's little point in having it.

In normal operation, we don't want to have the offset bring the demanded height above the raw target, as it leads to altitude overshoots in general. And we also don't want it to become negative.

Here;s a small opening to a potential bug. This offset is the only mechanism for adding throttle (energy) during `FlightStage::TAKOFF`. As it becomes zero as the altitude error becomes zero, throttle would also become zero and could lead to the altitude error never actually closing.
`TKOFF_THR_MIN` (default=0.6) is necessary to ensure that we will reach the altitude.

2024-08-07 20:09 UTC, Georacer commented on libraries/AP_TECS/AP_TECS.cpp
> -    use_takeoff_throttle = use_takeoff_throttle && (use_throttle_range == 1) && (aparm.takeoff_throttle_min != 0);
`use_throttle_range` was a bug here on my part. When `TKOFF_OPTIONS=1` is irrelevant to using `TKOFF_THR_MIN`.

Granted, this section would be better if it was identical to how `TKOFF_THR_MAX` is used above.

2024-08-07 20:22 UTC, Georacer commented
Selected responses:

`ARSPD_USE=1`, `TKOFF_OPTIONS=0`:
![image](https://github.com/user-attachments/assets/25171212-c8f6-4fc9-ac47-58488badbbd4)

`ARSPD_USE=1`, `TKOFF_OPTIONS=1`:
![image](https://github.com/user-attachments/assets/19796a0d-9af6-49f1-ac9b-16addbecb472)

`ARPSD_USE=0`
![image](https://github.com/user-attachments/assets/07b8f64a-b76c-4915-b1ee-06083f7d54d2)

2024-08-09 06:39 UTC, Hwurzburg approved these changes

2024-08-14 08:07 UTC, tridge requested changes
I think there should be only one call into TECS to give the limits for the next loop, not two calls giving different limits

2024-08-14 08:13 UTC, tridge commented on libraries/AP_TECS/AP_TECS.cpp
> +
@priseborough are you ok with this re-ordering?

2024-08-15 18:02 UTC, Georacer commented
This is me thinking out loud and writing down my thought process:

In the [last dev call](https://discuss.ardupilot.org/t/ardupilot-eu-dev-call-2024-08-14/122304) one of the review points was that TECS throttle limits should be set (through the `TECS.set_throttle_min/max()` in one place in the codebase.
The current situation where multiple places invoke this and affect the limits is confusing.

Currently there are 3 places in the codebase that make decisions on the throttle limits and 2 places where the throttle is actually written.
- `Plane::update_control_mode()` runs as a FAST_TASK, on every loop, calling the `update()` of each throttle-controlling flight mode.
	- This invokes eventually `Plane::takeoff_calc_throttle()`, which writes throttle limits to TECS,
	- then asks TECS for the throttle output in `Plane::calc_throttle(),
	- then writes on
```c++
SRV_Channels::set_output_scaled(SRV_Channel::k_throttle, commanded_throttle);
```
- `servos.cpp:set_servos()` runs as a FAST_TASK, on every loop.
	- These will overwrite the `SRV_Channel::k_throttle` values (assuming it runs after `update_control_mode()`, as it has lower priority).
	- They will also set the new, final limits to TECS.
- TECS control updates occur under the `update_alt()` task, at 10Hz.

Regarding which piece of code enacts which piece of logic:

TECS logic takes into account:
- `THR_MAX/MIN`
- `TKOFF_THR_MAX/MIN`
- `TKOFF_THR_MAX_T`
- `FlightStage`, as a dependency of the above.
- `landing.is_flaring()` to set min to 0.

`Plane::takeoff_calc_throttle()` logic takes into account:
- `TKOFF_THR_MAX/MIN`
- `TKOFF_OPTIONS`

`Plane::apply_throttle_limits()` logic takes into account:
- `THR_MAX/MIN`
- `TKOFF_THR_MAX/MIN`
- `landing.is_flaring()` to set min to 0.

What I think I'll do is:

1. Move all usage of `THR_MAX/MIN` to `Plane::apply_throttle_limits()`
1. Move all usage of `landing.is_flaring()` to `apply_throttle_limits()`.
1. Move all usage of `TKOFF_THR_MAX/MIN`, `TKOFF_THR_MAX_T`,`TKOFF_OPTIONS` to `takeoff_calc_throttle()`. After all the takeoff part of the codebase is the one that should logically apply the takeoff-related parameters.
1. `takeoff_calc_throttle()` will calculate throttle limits and store them in `_tkoff_thr_max/min`. These will also be retrievable via `get_tkoff_thr_max/min`. Care is needed that they will get restored when `takeoff_calc_throttle()` is no longer called.
1. `apply_throttle_limits()` will bring in `get_tkoff_thr_max/min()` and take it into account towards calculating the `limited_throttle`. It will then set those limits to TECS. This will be the only place to do so, because it knows the final limits that are used.

2024-08-16 17:07 UTC, Georacer commented
I've pushed another pair of commits to address the review comments in the last Dev Call:
The throttle limits logic has been refactored such that:
- TECS is now completely agnostic of the throttle limits. On every control iteration `servos.cpp:apply_throttle_limits()` is expected to set them.
- `servos.cpp:apply_throttle_limits()` does not take into account takeoff-related throttle parameters. They have all been moved to `takeoff.cpp`. `apply_throttle_limits()` is expected to query `takeoff.cpp` for the limts, where applicable.
- `takeoff_calc_throttle()` now writes the takeoff related throttle limits into `takeoff_state` new struct members.

2024-08-20 07:40 UTC, Georacer commented
I went over @peterbarker 's flight test logs.
All went as expected: he had set up `ARSPD_USE=0` and `TKOFF_OPTIONS=0`, so the aircraft climbed at full throttle until `TKOFF_ALT` or until `TKOFF_DIST`
It followed the takeoff profile desired pitch exactly, except for the intervals where the pilot mixed pitch input, as expected.

Thanks Peter!

2024-08-20 16:54 UTC, Georacer commented
> this is failing a flapping copter fence test that I thin @andypiper has a PR to disable

Ah, thanks for mentioning it. It did pass on my PC locally, but failing twice in a row in CI server got me a bit worried.

2024-08-28 07:22 UTC, tridge requested changes

2024-08-28 07:22 UTC, tridge commented on ArduPlane/mode_takeoff.cpp
> +        && altitude_cm >= level_alt
this seems to be comparing a cm value with a meter value

2024-09-04 08:25 UTC, tridge requested changes

2024-09-04 08:25 UTC, tridge commented on libraries/AP_TECS/AP_TECS.h
> +    bool _flag_pitch_forced;
i'm not keen on the reset code as a special case for under 1 degree pitch range, it implies we have some bad behaviour at narrow pitch ranges, eg. 1.5 degrees. If we don't have any bad behaviour then why do we need the special case?

2024-09-04 08:25 UTC, tridge commented on ArduPlane/takeoff.cpp
> +            TECS_controller.set_pitch_min(0.01f*nav_pitch_cd);
this doesn't look right, this is using fixed pitch after rotate and before cruise speed. That doesn't sound right at all, we won't be able to rotate

2024-09-04 08:25 UTC, tridge commented on ArduPlane/takeoff.cpp
> +            TECS_controller.set_pitch_min(0.01f*nav_pitch_cd);
we've lost the case of with an airspeed sensor and doing rotating rolling takeoff

2024-09-18 08:36 UTC, tridge requested changes

2024-09-18 08:36 UTC, tridge commented on ArduPlane/Plane.h
> +        float throttle_lim_max;
my concern is these variables may persist longer than we want them to, we could reset them in Plane::update_control_mode() to ensure we can't use stale values

2024-09-18 08:36 UTC, tridge commented on ArduPlane/mode_takeoff.cpp
> -         start_loc.get_distance(plane.current_loc) >= dist)) {
i think we need to keep this safety mechanism, and the comment that explains why it is needed (eg. user doesn't fully charge battery, or sets a silly level alt)

2024-09-18 08:36 UTC, tridge commented on ArduPlane/takeoff.cpp
> -            nav_pitch_cd = (gps.ground_speed() / (float)aparm.airspeed_cruise) * auto_state.takeoff_pitch_cd;
why is this being removed?

2024-09-18 08:36 UTC, tridge commented
@Hwurzburg If you have the time, a set of SITL tests on this PR would be very worthwhile!

2024-09-18 13:04 UTC, Hwurzburg commented
Everything looks good to me....alt overshoot is about 4m...within expectations I think for TECS...
Auto with and without AS
![Auto_noAS](https://github.com/user-attachments/assets/22d4fc06-5200-489c-b7eb-89d3f06a2374)
![Auto](https://github.com/user-attachments/assets/c1b803fb-4502-42f2-b089-bd17a4950e20)
Mode Takeoff with and without AS
![modetkoff_50_noAS](https://github.com/user-attachments/assets/bdaaf50f-3497-4cfc-94ec-312711eb85f3)
![modetkoff_50](https://github.com/user-attachments/assets/3eda1d3e-9987-4d3e-a3b2-5738c93970b5)

also verified that rotation speed and level alt works in both auto and mode takeoff

I did not check George's option, just default operation which 99% of users will use

2024-09-19 19:41 UTC, Hwurzburg commented
@tridge per your request, I ran the SITL tests above in RF using your AeroScout (am PRing a move to Released models also)....everything seemed fine with those physics and model

2024-09-20 15:35 UTC, Hwurzburg approved these changes

2024-09-24 22:30 UTC, tridge approved these changes

2024-09-24 22:32 UTC, tridge commented
many thanks to @Hwurzburg and @Georacer for all your great work and testing on this PR!

2024-09-25 13:43 UTC, peterbarker commented
I'm concerned that the glider-pull-up stuff is breaking in here...

2024-09-25 13:46 UTC, Georacer commented
> I'm concerned that the glider-pull-up stuff is breaking in here...

Henry told me a couple of days ago that might be an issue with the recent pullup PR itself; so I didn't pay much attention.
But I can take another look, of course, in the next few days.

2024-09-25 22:41 UTC, tridge commented
@Hwurzburg we do need to work out why GliderPullup is failing

2024-09-26 14:41 UTC, Georacer commented
The `GliderPullup` test should now pass on my latest commit.
What changed is that now pitch target is (as in master) first capped by min/max and then rate-limited. **(CASE M)**
Instead of being rate-limited first and then capped **(CASE P)**.

Case M can lead to the TECS pitch target being outside of the externally passed min/max.

---

In my opinion that test is only accidentally passing, thanks to this TECS "quirk".
In Case M, the TECS pitch reference only gradually rises to compensate for altitude, even though the mission Takeoff item force a positive minimum pitch
This gives enough time for the vehicle to gain forwards velocity:
![image](https://github.com/user-attachments/assets/2a34db65-f486-4471-951f-2428c2e056df)

In Case P, when the Takeoff mission item is processed (t~=271) the TECS minimum pitch is set to 15deg and the demanded pitch is immediately set there.
Thus the aircraft pulls the nose up earlier and never gains forward velocity.
It falls flat all the way to the ground.

---

In any case... I'm happy to forfeit this change for now to make the test content.

2024-10-02 07:09 UTC, merged

2024-10-02 07:09 UTC, peterbarker commented
Would be nice to update the documentation to note that the pitch-max should be negative on a glider like this, @Hwurzburg

2024-10-02 18:24 UTC, Hwurzburg commented
> Would be nice to update the documentation to note that the pitch-max should be negative on a glider like this, @Hwurzburg (`TECS_PITCH_MAX`)

@Georacer has a  wiki PR for this and it should be incorporated into his PR

2024-10-02 18:59 UTC, Georacer commented
> > Would be nice to update the documentation to note that the pitch-max should be negative on a glider like this, @Hwurzburg (`TECS_PITCH_MAX`)
> 
> @Georacer has a wiki PR for this and it should be incorporated into his PR

@Hwurzburg what Peter is talking about is something different:

We were discussing in the dev call today that pure gliders (no motor) should probably be set with a maximum pitch angle that is close to zero (or negative), such that they can't pull their nose up and stall.

2024-10-02 19:55 UTC, Hwurzburg commented
okay will add to TECS page where that param is discussed

2024-10-12 03:52 UTC, timtuxworth commented
I tested this today. Definitely much improved "overshoot" behavior on auto takeoff. It no longer hits the top of the climb and then dives back down like it was doing before this.

2024-10-12 07:58 UTC, Georacer commented
@timtuxworth that's great to hear!