Add a new target HolybroF4_PMU
ArduPilot/ardupilot pull request #27751
Opened 2024-08-05 05:34 UTC by jamming

Add a new target HolybroF4_PMU. It uses STM32F405 MCU and ALLEGRO ACS772 current sensor.

2024-08-05 05:51 UTC, vincentpoont2 commented
Hi @peterbarker @tridge , This is for our Holybro DroneCAN Power Module. 
we have tested the preset parameter is working with this https://github.com/ArduPilot/ardupilot/pull/27735.

Please review and merge.

2024-08-05 10:20 UTC, peterbarker requested changes
There should be two commits here.

One for the bootloaders directory, e.g.: `bootloaders: add HolybroF4_PMU bootloader`
One for the hwdef directory: `hwdef: add HolyBroF4_PMU`

@Hwurzburg is currently on holidays but does like to review these PRs before they're merged.

2024-08-05 10:20 UTC, peterbarker commented on libraries/AP_HAL_ChibiOS/hwdef/HolybroF4_PMU/README.md
> +- Flashing quickly continuously: MCU is in the bootloader stage, waiting for firmware to be flash
```suggestion
- Flashing quickly continuously: MCU is in the bootloader stage, waiting for firmware to be flashed

```

2024-08-05 10:20 UTC, peterbarker commented on libraries/AP_HAL_ChibiOS/hwdef/HolybroF4_PMU/README.md
> +- Size: 45mm��41mm��26mm (Not Include Cable)
```suggestion
- Size: 45mm��41mm��26mm (not including cable)

```

2024-08-05 10:20 UTC, peterbarker commented on libraries/AP_HAL_ChibiOS/hwdef/HolybroF4_PMU/hwdef.dat
> +define HAL_LED_ON 0
I don't think this LED will blink at the moment.  You need to set things like this now:
define AP_NOTIFY_GPIO_LED_1_ENABLED 1
define AP_NOTIFY_GPIO_LED_1_PIN 90

2024-08-05 10:20 UTC, peterbarker commented on libraries/AP_HAL_ChibiOS/hwdef/HolybroF4_PMU/hwdef.dat
> +define HAL_DISABLE_LOOP_DELAY
No longer used - this line is not effective

2024-08-05 10:20 UTC, peterbarker commented on libraries/AP_HAL_ChibiOS/hwdef/HolybroF4_PMU/hwdef.dat
> +define HAL_NO_MONITOR_THREAD
This line doesn't do anything

2024-08-06 03:10 UTC, jamming commented
I have already made all the modifications according to your suggestions.

2024-08-06 04:32 UTC, Hwurzburg approved these changes

2024-08-08 01:30 UTC, vincentpoont2 commented
Hi @peterbarker is it good to merge now?

2024-09-04 00:27 UTC, peterbarker commented
I've created https://github.com/ArduPilot/ardupilot/pull/27998 to replace this.

I was unable to force-push over this branch - probably a repo setting or someone unchecked the "allow force push" option when creating the PR.

The commits needed fixing to conform to our standards - check that other PR to see the shape they need to be.

Please note that the many-repo pattern you're using for these developments is a little vexing to work with as the remote needs to be updated for this sort of tidy-up.

I've marked my other PR as merge-on-ci-pass, so I'm going to close this one.

Thanks!

2024-09-04 00:27 UTC, closed without merging

2024-09-05 22:50 UTC, peterbarker commented
> Hi @peterbarker is it good to merge now?

I've merged the PR I created to replace this one.