Flywoo H743 pro
ArduPilot/ardupilot pull request #27785
Opened 2024-08-07 11:16 UTC by andyp1per

2024-08-09 14:32 UTC, Hwurzburg requested changes
need  to add readme sections on VTX power control and camera switch also

2024-08-09 14:32 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/FlywooH743Pro/README.md
> + - BEC 10V 3A
```suggestion
 - BEC 10V 3A for video, gpio controlled
 - Dual switchable camera inputs
```

2024-08-09 14:32 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/FlywooH743Pro/README.md
> + - SERIAL3 -> UART3
```suggestion
 - SERIAL3 -> UART3 (User)
```

2024-08-09 14:32 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/FlywooH743Pro/README.md
> + - SERIAL8 -> UART8 (DJI/MSP, DMA-enabled)
```suggestion
 - SERIAL8 -> UART8 (DisplayPort, DMA-enabled)
```

2024-08-09 14:32 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/FlywooH743Pro/README.md
> + - SERIAL7 -> UART7
```suggestion
 - SERIAL7 -> UART7 (User)
```

2024-08-09 14:32 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/FlywooH743Pro/README.md
> +## RC Input
replace RC section with this:
RC input is configured by default via the USART1 RX input. It supports all unidirectional RC protocols except PPM. 

Note: If the receiver is FPort the receiver must be tied to the USART1 TX pin ,  RSSI_TYPE set to 3, and SERIAL2_OPTIONS must be set to 7 (invert TX/RX, half duplex). For full duplex like CRSF/ELRS use both RX1 and TX1 and set RSSI_TYPE also to 3.

2024-08-09 14:32 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/FlywooH743Pro/README.md
> +The Flywoo H743 Pro supports OSD using OSD_TYPE 1 (MAX7456 driver).
```suggestion
The Flywoo H743 Pro supports OSD using OSD_TYPE 1 (MAX7456 driver) and simultaneously DisplayPort using TX8/RX8 on the HD VTX connector.
```

2024-08-09 14:32 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/FlywooH743Pro/README.md
> +The board has a builting voltage and current sensor. The current
```suggestion
The board has a built-in voltage sensor and external current sensor input. The current
```

2024-08-09 14:32 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/FlywooH743Pro/README.md
> +*.apj firmware files.
```suggestion
\*.apj firmware files.
```

2024-08-09 14:32 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/FlywooH743Pro/README.md
> +FrSky Telemetry is supported using the T5 pin (UART5 transmit). You need to set the following parameters to enable support for FrSky S.PORT
```suggestion
FrSky Telemetry is supported using  and unused UART,such as the T3 pin (UART3 transmit). You need to set the following parameters to enable support for FrSky S.PORT
```

2024-08-09 14:32 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/FlywooH743Pro/README.md
> +  - SERIAL5_PROTOCOL 10
```suggestion
  - SERIA3_PROTOCOL 10
```

2024-08-09 14:32 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/FlywooH743Pro/README.md
> +  - SERIAL5_OPTIONS 7
```suggestion
  - SERIAL3_OPTIONS 7
```

2024-08-09 14:32 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/FlywooH743Pro/README.md
> +The Flywoo H743 Pro supports up to 13 PWM outputs. The pads for motor output
```suggestion
The Flywoo H743 Pro supports up to 13 PWM or DShot outputs. The pads for motor output
```

2024-08-10 17:39 UTC, andyp1per commented
All fixed, @Hwurzburg

2024-08-11 06:21 UTC, Hwurzburg commented
@andyp1per  missed a few

2024-08-11 08:09 UTC, andyp1per commented
Arg, github and its hidden conversations! Fixed now.

2024-08-11 09:01 UTC, Hwurzburg approved these changes

2024-08-13 00:20 UTC, merged