AP_Mission: do not use float functions on integers
ArduPilot/ardupilot pull request #27788
Opened 2024-08-08 02:16 UTC by peterbarker

pitch is int8_t, yaw is int16_t

Completely untested.  Well, CI will make sure it compiles.

2024-08-12 17:09 UTC, IamPete1 reviewed
This must be correct. But I do wonder if this means were missing the NaN check on the command write. The incomming MAVLink could be NaN here:

https://github.com/ArduPilot/ardupilot/blob/748fe538eac62046b7cb65ec8c70c0570136db84/libraries/AP_Mission/AP_Mission.cpp#L1360-L1367

Presumably if NaN the intended behavior would be that it is not used. So we could set to a out of range value so it is ignored via the abs. I guess we would also have to return a NaN in the MAVLink read....

edit: It looks like NaNs are not in the spec, so we might be OK. https://mavlink.io/en/messages/common.html#MAV_CMD_DO_GIMBAL_MANAGER_PITCHYAW

2024-08-12 22:49 UTC, peterbarker commented
This is probably the wrong way to fix this.  We should probably add a `uint8_t field_invalid` field to `struct PACKED gimbal_manager_pitchyaw_Command`.

We have the same problem with the handle-rate-commands block below the one I've modified here.

2024-08-12 23:12 UTC, rmackay9 commented
I'm pretty sure that the caller is meant to set the unused fields to NaN

2024-08-13 00:31 UTC, tridge requested changes

2024-08-13 00:31 UTC, tridge commented on libraries/AP_Mission/AP_Mission_Commands.cpp
> +    const bool pitch_angle_valid = abs(cmd.content.gimbal_manager_pitchyaw.pitch_angle_deg) <= 90;
a simple change would be to use -128 as a magic value meaning invalid for int8 rates, and set to -128 for NaN in the mavlink msg. If someone asks for -128 then instead set -127

2024-08-14 00:20 UTC, nexton-winjeel commented
@peterbarker 
> edit: It looks like NaNs are not in the spec, so we might be OK.

It's in the message description, not the field descriptions.

> ### MAV_CMD_DO_GIMBAL_MANAGER_PITCHYAW (1000)
> Set gimbal manager pitch/yaw setpoints (low rate command). It is possible to set combinations of the values below. E.g. an angle as well as a desired angular rate can be used to get to this angle at a certain angular rate, or an angular rate only will result in continuous turning. **NaN is to be used to signal unset.** Note: only the gimbal manager will react to this command - it will be ignored by a gimbal device. Use [GIMBAL_MANAGER_SET_PITCHYAW](https://mavlink.io/en/messages/common.html#GIMBAL_MANAGER_SET_PITCHYAW) if you need to stream pitch/yaw setpoints at higher rate.

2024-11-09 06:01 UTC, peterbarker commented
We currently bounce NaN values in mission upload.  The Mount backend doesn't cope if either value is NaN.

I've created a branch which preserves NaN values in storage using INT8_MIN and INT16_MIN, but I reckon that's probably just a waste of flash space at this point.

2024-11-12 00:22 UTC, tridge approved these changes

2024-11-12 00:22 UTC, merged