AUAV Airspeed Sensor Driver
ArduPilot/ardupilot pull request #27802
Opened 2024-08-10 02:15 UTC by Tdogb

Drivers for the Amphenol AUAV airspeed sensor. This is a relatively new UAV specific airspeed sensor. I don't know why Amphenol didn't write their own Ardupilot drivers, but I did it for them since this looks like a really awesome sensor.

https://www.mouser.com/new/amphenol/amphenol-auav-air-speed-altitude-sensors/

2024-08-10 03:45 UTC, MallikarjunSE commented
These actually provide absolute pressure measurement too.

2024-08-10 04:25 UTC, Tdogb commented
> These actually provide absolute pressure measurement too.

Nice! Although I'm going to leave that to someone else to implement if they want :)

2024-08-10 06:07 UTC, Hwurzburg requested changes
needs extract_features.py also

2024-08-10 06:07 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/include/minimize_common.inc
> +define AP_AIRSPEED_AUAV_ENABLED 1
uncommon airspeed drivers should not be included in minimize

2024-08-13 11:29 UTC, peterbarker requested changes

2024-08-13 11:29 UTC, peterbarker commented on libraries/AP_Airspeed/AP_Airspeed_AUAV.cpp
> +#if AP_AIRSPEED_AUAV_ENABLED
```suggestion
#include "AP_Airspeed_config.h"

#if AP_AIRSPEED_AUAV_ENABLED

#include "AP_Airspeed_AUAV.h"
```

2024-08-13 11:29 UTC, peterbarker commented on libraries/AP_Airspeed/AP_Airspeed_AUAV.cpp
> +
```suggestion
```

2024-08-13 11:29 UTC, peterbarker commented on libraries/AP_Airspeed/AP_Airspeed_AUAV.cpp
> +    if (!_dev) {
```suggestion
    if (_dev == nullptr) {
```

2024-08-13 11:29 UTC, peterbarker commented on libraries/AP_Airspeed/AP_Airspeed_AUAV.cpp
> +    return true;
```suggestion
    return false;
```

2024-08-20 20:58 UTC, peterbarker commented
Ping @Tdogb - also needs to pass CI :-)

2024-08-20 21:01 UTC, Tdogb commented
Hey guys, I think it would be super cool to implement the absolute pressure sensing capability. Does anyone have strong opinions on how this is implemented? I don't want someone to unknowingly have it override their baro

2024-08-21 09:16 UTC, tridge commented
just as an airspeed sensor initially is the way to go

2024-09-11 11:57 UTC, peterbarker commented
@Tdogb did you need assistance on this one, or still plugging away at it?

2024-09-11 12:24 UTC, MallikarjunSE commented
@peterbarker i tried this pr. Was able to get differential pressure output. But temperature didn't work for me.

2024-09-22 20:47 UTC, Tdogb commented
> @peterbarker i tried this pr. Was able to get differential pressure output. But temperature didn't work for me.

Temperature is compensated for but the real temperature value isn't read because there isn't documentation on it.

I had accidentally pushed some other dev code I have to this branch so I removed it. Although if anyone has interest in using multiple of the same i2c sensors, I can revive the code, it works well.

2024-11-08 01:51 UTC, peterbarker requested changes
There are still changes requested from my previous review

2024-11-08 01:51 UTC, peterbarker commented on libraries/AP_Airspeed/AP_Airspeed.cpp
> +            break;
```suggestion
            break;
```

2024-11-08 01:51 UTC, peterbarker commented on libraries/AP_Airspeed/AP_Airspeed_AUAV.cpp
> +#if AP_AIRSPEED_AUAV_ENABLED
```suggestion
#include "AP_Airspeed_config.h"

#if AP_AIRSPEED_AUAV_ENABLED

#include "AP_Airspeed_AUAV.h"
#include "AP_Logger/AP_Logger.h"
```

2025-01-30 08:15 UTC, tridge commented on libraries/AP_HAL_ChibiOS/hwdef/include/minimize_common.inc
> +define AP_AIRSPEED_AUAV_ENABLED 1
fixed

2025-01-30 08:17 UTC, tridge commented on libraries/AP_Airspeed/AP_Airspeed_AUAV.cpp
> +
needs constructor for the pressure range in fixed driver

2025-01-30 08:19 UTC, tridge commented on libraries/AP_Airspeed/AP_Airspeed_AUAV.cpp
> +#if AP_AIRSPEED_AUAV_ENABLED
fixed

2025-01-30 08:19 UTC, tridge commented on libraries/AP_Airspeed/AP_Airspeed_AUAV.cpp
> +    if (!_dev) {
can't do that with OwnPtr

2025-01-30 08:19 UTC, tridge commented on libraries/AP_Airspeed/AP_Airspeed_AUAV.cpp
> +    return true;
fixed to return real temperature

2025-01-30 08:20 UTC, tridge commented on libraries/AP_Airspeed/AP_Airspeed.cpp
> +            break;
fixed

2025-01-30 08:20 UTC, tridge commented on libraries/AP_Airspeed/AP_Airspeed_AUAV.cpp
> +#if AP_AIRSPEED_AUAV_ENABLED
fixed

2025-01-30 08:21 UTC, tridge commented
@MallikarjunSE @Tdogb I've force pushed some fixes:
 - temperature now works
 - supports 3 pressure ranges
 - removed the absolute code
 - use 8x sampling for lower noise

I've bench tested buy not flight tested. Please test!

2025-01-30 09:03 UTC, MallikarjunSE commented
> @MallikarjunSE @Tdogb I've force pushed some fixes:
> 
> * temperature now works
> * supports 3 pressure ranges
> * removed the absolute code
> * use 8x sampling for lower noise
> 
> I've bench tested buy not flight tested. Please test!

Hey @tridge 
Tested on DroneCAN periph device. Works! 
Thank you! 
![image](https://github.com/user-attachments/assets/ca92f1d6-90fa-42a4-a780-ad2755c52894)

2025-01-30 12:07 UTC, MallikarjunSE commented
@tridge  tested on L30D. Works! 
![image](https://github.com/user-attachments/assets/8eb37416-e008-41ed-aa89-db22c323e6dd)

2025-01-30 19:17 UTC, MallikarjunSE commented
Hey @tridge 
below is temperature comparison between DroneCAN periph vs I2C directly plugged in. Temperature update rate seems to be too low on DroneCAN? Or it's sufficient?

![image](https://github.com/user-attachments/assets/3f34609d-4e16-43d9-91ea-203bb8b00940)

2025-01-30 19:38 UTC, tridge commented
> Temperature update rate seems to be too low on DroneCAN? Or it's sufficient?

the reason the graph looks weird is the DroneCAN RawAirData message uses a float16 for temperature, which means it doesn't have much resolution. It is sufficient for how it is used though

2025-01-30 20:09 UTC, Tdogb commented
Thanks for helping push this across the finish line guys! 

I have some code on my personal branch for absolute pressure, however, I've been running into issues with the sensor not acking some of the calibration coefficients. Looking at it on the scope makes it seem like an issue with the sensor itself. I'll send photos when I get home

2025-02-02 06:39 UTC, peterbarker commented on libraries/AP_Airspeed/AP_Airspeed_AUAV.cpp
> +        // behaviour of probing all buses, external first
"same behaviour as other dirvers"?

2025-02-02 06:39 UTC, peterbarker commented on libraries/AP_Airspeed/AP_Airspeed_AUAV.cpp
> +        FOREACH_I2C_INTERNAL(bus) {
I wonder if we should actually have a force-probe-internal-buses we can enable on those boards which screw this up?  Might save flash on boards which are not stuffed...

2025-02-02 06:39 UTC, peterbarker commented on libraries/AP_Airspeed/AP_Airspeed_AUAV.cpp
> +    uint32_t PComp;
Would be nice to initialise these as we declare them.

2025-02-02 12:56 UTC, Hwurzburg approved these changes

2025-02-03 03:19 UTC, tridge commented
@Tdogb @MallikarjunSE I've changed it to require ARSPD_BUS to be set correctly, which is how other drivers work except for the MS4525 (which was a legacy compatibility hack)
I've also added status checking so the probe is more reliable, and ensures that we don't use invalid data

2025-02-03 03:20 UTC, tridge commented on libraries/AP_Airspeed/AP_Airspeed_AUAV.cpp
> +    uint32_t PComp;
done

2025-02-03 03:20 UTC, tridge commented on libraries/AP_Airspeed/AP_Airspeed_AUAV.cpp
> +        FOREACH_I2C_INTERNAL(bus) {
i've changed it to require the bus to be set

2025-02-03 03:20 UTC, tridge commented on libraries/AP_Airspeed/AP_Airspeed_AUAV.cpp
> +        // behaviour of probing all buses, external first
fixed

2025-02-03 10:16 UTC, MallikarjunSE commented
> @Tdogb @MallikarjunSE I've changed it to require ARSPD_BUS to be set correctly, which is how other drivers work except for the MS4525 (which was a legacy compatibility hack) I've also added status checking so the probe is more reliable, and ensures that we don't use invalid data

Tested with CubeOrange and Periph device and works. I2C bus selection works as expected. Previously it used to probe without setting bus number. Now works with bus number set correctly. 
![image](https://github.com/user-attachments/assets/b71e62d5-b0b7-490f-acdc-32d0e794282e)

2025-02-04 05:17 UTC, merged

2025-02-26 16:04 UTC, criegit commented
tested it with L05D on the bench with Pix32 v6 and Matek L431-Cannode. Seems to work very good.
Comparisons with DLVR sensor and with a reference pressure system planned in the near future.

I did my own driver integration of this airspeed sensor to learn how to do that. I was not that far off, so thanks a lot for the code to compare, correct and learn!

I would love to participate in the barometer integration as much as i can. (limited)
As far as i understand, the barometer option of the board are as of now hardcoded in the hwdef file.
So there would be a easy way to implement this sensor for an AP_Periph device that ships with this sensors, but this does notwork for flexible selection of sensors in the Autopilot Parameter list.

I hope to be more present in the upcoming devtalks.

2025-03-15 21:09 UTC, IamPete1 commented
I have done a PR to add a baro driver. https://github.com/ArduPilot/ardupilot/pull/29535

However, my sensor always fails to read the extended calibration coefficients for that channel despite working fine on the differential channel. I can do builds if anyone else wants to give it a try.

2025-03-15 21:11 UTC, Tdogb commented
> I have done a PR to add a baro driver. https://github.com/ArduPilot/ardupilot/pull/29535
> 
> 
> 
> However, my sensor always fails to read the extended calibration coefficients for that channel despite working fine on the differential channel. I can do builds if anyone else wants to give it a try.

I have independently written a driver for abs pressure and have ran into the exact issue. Putting it on the scope the fc is outputting the correct command but the sensor just doesn't respond, it seems like an issue with the sensor itself.

2025-03-15 21:35 UTC, IamPete1 commented
> I have independently written a driver for abs pressure and have ran into the exact issue. Putting it on the scope the fc is outputting the correct command but the sensor just doesn't respond, it seems like an issue with the sensor itself.

I'm not going crazy then! I did find that it works fine if we just don't bother with the extended calibration. Maybe that is a solution,  but it is certainly strange. 

I did notice the other team has a driver, I wonder if it works there. https://github.com/PX4/PX4-Autopilot/blob/main/src/drivers/differential_pressure/auav/AUAV.cpp

2025-04-20 22:59 UTC, IamPete1 commented
@Tdogb I now have the baro driver working. It turns out its very sensitive to timings because its clocked much slower than the differential channel for some reason. https://github.com/ArduPilot/ardupilot/pull/29535