Support reversible mask in iomcu
ArduPilot/ardupilot pull request #27828
Opened 2024-08-13 16:32 UTC by andyp1per

We were sending the command but not coping when actually sending the dshot packet

2024-08-14 09:31 UTC, tridge requested changes
I think we also need the armed state? so we can send dshot value 0 when disarmed. Not doing that for 3D ESCs is dangerous
We have the flag P_SETUP_ARMING_FMU_ARMED left over from earlier versions of IOMCU but we don't seem to use it, I think we need to check hal.util->get_soft_armed() and send that flag over to the IOMCU, otherwise reversible ESCs are too dangerous

2024-08-14 13:45 UTC, andyp1per commented
> I think we also need the armed state? so we can send dshot value 0 when disarmed. Not doing that for 3D ESCs is dangerous We have the flag P_SETUP_ARMING_FMU_ARMED left over from earlier versions of IOMCU but we don't seem to use it, I think we need to check hal.util->get_soft_armed() and send that flag over to the IOMCU, otherwise reversible ESCs are too dangerous
> 
> Note we do this: ![image](https://private-user-images.githubusercontent.com/831867/357758404-079dd4c2-ab3c-4b71-b55a-1637625c0389.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2Mzk1ODcsIm5iZiI6MTcyMzYzOTI4NywicGF0aCI6Ii84MzE4NjcvMzU3NzU4NDA0LTA3OWRkNGMyLWFiM2MtNGI3MS1iNTVhLTE2Mzc2MjVjMDM4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQxMjQxMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmM2NTczOTQ3MTVjNjBlNmZkNDUxMDgxYjUzMDM2MmQ1YmFhYTEwNGIzMGI1MTU1NDQyODZjMjhiZDI2MTQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AYtuJVAj_sTGSPNj590GTgHz3rHUVMNekCtRkEmCUBk) so on FMU we do send 0 always when not armed, on IOMCU we don't as far as I can see

Good catch! Now I understand why @bugobliterator commented this out on IOMCU. It's a little more subtle as the armed state needs to be propagated as well, but certainly doable.

2024-08-14 16:19 UTC, andyp1per commented
I verified with a Saleae that:
- disarmed + safety - no output
- disarmed + safety disabled - zeros output
- armed - zero throttle output

2024-08-18 23:34 UTC, tridge requested changes
minor changes, but main problem is that the resulting DShot signal is wrong on IOMCU, it is idle high whereas DShot is supposed to be idle low

2024-08-18 23:35 UTC, tridge commented
testing on Pixhawk6x-bdshot with Sub, with 10% throttle:
![image](https://github.com/user-attachments/assets/5295e9d8-ee7f-44f7-8617-059586dfc4ec)

2024-08-20 12:25 UTC, andyp1per commented on libraries/AP_IOMCU/AP_IOMCU.cpp
> +    bool armed = AP::arming().is_armed();
I guess I don't understand the difference and I will point out that this is a pre-existing bug - but happy to change.

2024-08-20 17:19 UTC, andyp1per commented on libraries/AP_IOMCU/AP_IOMCU.cpp
> +    bool armed = AP::arming().is_armed();
Fixed

2024-08-20 17:19 UTC, andyp1per commented on libraries/AP_IOMCU/iofirmware/iofirmware.cpp
> +    hal.util->set_soft_armed(reg_setup.arming & P_SETUP_ARMING_FMU_ARMED);
Fixed

2024-08-20 17:19 UTC, andyp1per commented
I have now tested this successfully on a CubeOrangePlus

2024-08-28 08:12 UTC, tridge approved these changes

2024-08-29 03:28 UTC, tridge commented
@andyp1per I've been testing this with both BLHeli32 and AM32 ESCs on a Pixhawk6X-bdshot board, testing with rover
It all works on FMU, but on IOMCU we never send the command code to set the ESC to 3D mode.

2024-09-04 08:34 UTC, tridge approved these changes

2024-09-04 08:34 UTC, merged

2024-09-25 10:45 UTC, rmackay9 commented
I discussed with @andyp1per and it only affects rover and sub and he thinks it's best that we wait for 4.6 which will start beta testing soon anyway

2024-12-10 06:20 UTC, xfacta commented
I've got a result and a fail - the SERVO_BLH_RVMASK now works BUT the bitmask seems to be mapped randomly to servo channels or motor positions. Using a Quad X8 I couldnt tell what bit would affect which motor without first testing all individually.
When I last used SERVO_BLH_RVMASK it was on a FC without IOMCU and I seem to remember the "bitmask channels" aligned to the Servo channels regardless of which motor function was assigned to which servo channel.

RCOut: DS300:1-8 PWM:9-13
IOMCU: 420 1001 411FC231
CubeOrange 00330033 3131510E 31363832
ChibiOS: 88b84600
ArduCopter V4.6.0-beta1 (8d4976cd)

I am using the standard Octaquad (X8) motor positions and wiring, to the Main Out servo connections as follows:

Letter    Servo    Dir       needs reversing
A            1          CCW
B            6          CW      reverse
C           4           CW      reverse
D           7           CCW   reverse
E           3           CCW
F           8           CW
G          2           CW
H          5           CCW

Tests of each bitmask value produced:
bitmask "channel" (decimal value) => letter/servo ch
1 (1)   =>   D 7
2 (2)   =>   C 4
3 (4)   =>   E 3
4 (8)   =>   F 8
5 (16)   =>   G 2
6 (32)   =>   H 5
7 (64)   =>   A 1
8 (128)   =>   B 6
which appears to have no relationship, such as bit 0 mapping to Servo 1 would be nice and logical.

I had to use this bitmap to reverse motors B/6 , C/4 , D/7, => 1,2,8 bitmask for SERVO_BLH_RVMASK,131

I would have expected 4,6,7 = SERVO_BLH_RVMASK,104 decimal