Support MAV_CMD_EXTERNAL_WIND_ESTIMATE
ArduPilot/ardupilot pull request #27847
Opened 2024-08-15 13:42 UTC by python36

When flying without a GPS receiver, drift correction does not work properly because the autopilot does not have information about the wind speed and direction.
I can get wind information using online services (e.g. windy.com) and with this command set a custom wind speed and direction, which will greatly improve drift correction.

This is very important when flying without GPS.

2024-08-17 00:11 UTC, peterbarker requested changes

2024-08-17 00:11 UTC, peterbarker commented on libraries/AP_AHRS/AP_AHRS.h
> +#if AP_AHRS_EXTERNAL_WIND_ESTIMATE_ENABLED
```suggestion
#if AP_AHRS_EXTERNAL_WIND_ESTIMATE_ENABLED
    void external_wind_estimate(float speed, float direction) {
```

2024-08-17 00:11 UTC, peterbarker commented on libraries/AP_AHRS/AP_AHRS_DCM.cpp
> +void AP_AHRS_DCM::external_wind_estimate(float speed, float direction) {
Needs compile `#ifdef`

2024-08-20 09:40 UTC, python36 commented
@peterbarker I make a new commit taking into account your proposals.

2024-08-27 07:49 UTC, peterbarker requested changes
Should we have a timeout on the use of this wind estimate?

In your testing, how long does the use of this estimate last during a flight?

An autotest for this would be nice.

2024-08-31 22:11 UTC, LupusTheCanine commented
> Should we have a timeout on the use of this wind estimate?

IMHO it is likely that the estimate will be closer to truth than 0 wind velocity unless the wind is rapidly changing which will mess with dead reckoning no mater what you do.

2024-09-02 03:08 UTC, peterbarker commented
Playing with MAVProxy command: `long EXTERNAL_WIND_ESTIMATE 10 0 30`

`AHRS_EKF_TYPE` of 0 (DCM)

On ground With `AIRSPEED_USE` of zero:
![image](https://github.com/user-attachments/assets/4b388a61-c4da-455b-baff-6e5124ef4b95)

On ground With `AIRSPEED_USE` of one:
![image](https://github.com/user-attachments/assets/015c669f-fd17-46de-8b90-cefed3ceab80)

In-flight when loitering with a 5m/s wind from 180 (with airspeed)
![image](https://github.com/user-attachments/assets/ea1adcee-a09c-4ada-9f01-59eb96e5e102)

In-flight when loitering with a 5/m/s wind from 180, without airspeed:
![image](https://github.com/user-attachments/assets/de211251-71f9-4fe4-bbc2-d1377fb13359)

2024-09-02 03:11 UTC, peterbarker requested changes
Solid autotest.

Needs to be broken into several commits, one-per-subsystem with appropriate commit commits.

See https://ardupilot.org/dev/docs/git-interactive-rebase.html and `Tools/gittools/git-subsystems-split`

2024-09-02 14:40 UTC, python36 commented on Tools/autotest/arduplane.py
> +        self.reboot_sitl()
Without rebooting it crashes with the problem:
```python
2024-09-02T10:59:42.8273703Z AT-1454.7: mavproxy_start was called 3 times
2024-09-02T10:59:42.8274525Z AT-1454.7: Supplied terrain data to autopilot in 1176 messages
2024-09-02T10:59:42.8275279Z Had to force-reset SITL 1 times
2024-09-02T10:59:42.8276256Z AT-1454.7: Writing test result in jUnit format to autotest_result_ArduPlane_test.Plane_junit.xml
2024-09-02T10:59:42.8277039Z 
2024-09-02T10:59:42.8277325Z >>>> FAILED STEP: test.Plane at Mon Sep  2 10:59:42 2024
2024-09-02T10:59:42.8277981Z Failure Summary:
2024-09-02T10:59:42.8278383Z   test.Plane:
2024-09-02T10:59:42.8278959Z     TakeoffAuto3 (Test the behaviour of an AUTO takeoff, pt3.
2024-09-02T10:59:42.8279511Z 
2024-09-02T10:59:42.8279661Z         Conditions:
2024-09-02T10:59:42.8280127Z         - ARSPD_USE=1
2024-09-02T10:59:42.8280609Z         - TKOFF_OPTIONS[0]=1
2024-09-02T10:59:42.8281646Z         ) (Wrong value) (see /tmp/buildlogs/ArduPlane-TakeoffAuto3.txt) (duration 1.3573386669158936 s)
2024-09-02T10:59:42.8284539Z     MAV_CMD_EXTERNAL_WIND_ESTIMATE (test MAV_CMD_EXTERNAL_WIND_ESTIMATE as a mavlink command) (Failed to set wind speed or/and direction: speed != 1 or direction != 45) (see /tmp/buildlogs/ArduPlane-MAV_CMD_EXTERNAL_WIND_ESTIMATE.txt) (duration 0.09662985801696777 s)
2024-09-02T10:59:42.8286841Z FAILED 1 tests: ['test.Plane']
2024-09-02T10:59:42.9402933Z ##[error]Process completed with exit code 1.```

2024-09-02 23:14 UTC, tridge commented
@priseborough I notice in your branch here: https://github.com/priseborough/ardupilot/commits/pr-ekfWindStateUpdate-rebase04/ that you seem to be doing the same thing, but with EKF3 instead of DCM
how close is that to being ready? Should we merge the DCM only PR first and then layer yours on top?

2024-09-02 23:16 UTC, tridge commented on libraries/AP_AHRS/AP_AHRS_config.h
> +#define AP_AHRS_EXTERNAL_WIND_ESTIMATE_ENABLED AP_AHRS_DCM_ENABLED
should be 2M boards only

2024-09-02 23:18 UTC, tridge commented
@tridge do you want to try Pauls branch in SITL, with DCM fallback disabled?

2024-09-02 23:18 UTC, peterbarker commented
@python36 what sorts of boards are you running this on?  We're wondering how to guard the feature compilation-wise, whether to say >1024MB instead of DCM (need to change the latter when EKF3 supports it).

2024-09-03 01:31 UTC, priseborough commented
> @priseborough I notice in your branch here: https://github.com/priseborough/ardupilot/commits/pr-ekfWindStateUpdate-rebase04/ that you seem to be doing the same thing, but with EKF3 instead of DCM how close is that to being ready? Should we merge the DCM only PR first and then layer yours on top?

@tridge My branch is very close. I'm in the process of finalising autotests. I vote we merge this first and I'll rebase and deal with the AHRS library conflicts.

2024-09-03 01:58 UTC, priseborough commented
FYI the https://github.com/priseborough/ardupilot/commits/pr-ekfWindStateUpdate-rebase04/ branch bundles  a few dead reckoning inprovements:

Enables a VTOL to fly using dead reckoning when GPS is unavailable provided the origin is set before flight.
Keeps the last known local position after dropping out of dead reckoning when going from forward flight to VTOL modes. 
Uses MAV_CMD_EXTERNAL_POSITION_ESTIMATE messages to update the wind estimate.
Uses MAV_CMD_EXTERNAL_WIND_ESTIMATE messages to update EKF3 wind estimates also using the accuracy fields to set the wind state covariances. Vehicle velocity is also updated to be consistent with the wind and airspeed.

2024-09-03 06:37 UTC, python36 commented
> @python36 what sorts of boards are you running this on? We're wondering how to guard the feature compilation-wise, whether to say >1024MB instead of DCM (need to change the latter when EKF3 supports it).

I am using fmuv3 board so I have 2MB of flash on board. I created a new commit.

2024-09-04 00:14 UTC, merged

2024-09-04 00:14 UTC, peterbarker commented
Merged, thanks!

2024-09-04 05:51 UTC, python36 commented
> Merged, thanks!

🎉🎉🎉 Thanks all.
@peterbarker Thank you very much

2024-11-06 02:53 UTC, rmackay9 commented
This is a very interesting feature but one question I have about the implementation is why was MAV_CMD_EXTERNAL_WIND_ESTIMATE used?  It's really not a command so it probably should have been provided using a new mavlink message.