AP_Baro:add driver for the SPA06
ArduPilot/ardupilot pull request #27905
Opened 2024-08-23 02:46 UTC by radiolinkW

The SPA06 is a high resolution low noise barometer pin-to-pin compatible with the SPL06.
I have been flight testing this baro on RadiolinkPIX6 and driver it seems to work well.
Here is the datasheet: [SPA06-003_datasheet.pdf](https://github.com/radiolinkW/binary/blob/master/SPA06-003_datasheet.pdf)

2024-08-23 09:46 UTC, peterbarker commented
Needs to compile

This looks *very* similar to the SPL06 driver.

This looks like we should be re-using the SPLP06 driver for the SPA, particularly if they can be distinguished by their WHOAMI registers or some other fingerprinting we can do.

We *seriously* can't afford to copy a driver sideways - we're fast running out of flash on boards, and baros make their way into a lot of boards.

Can you think about whether it would be possible to augment the SPL driver, please?

I'm happy to take this to a DevCall to see if other devs disagree, but I don't think they will.

2024-08-26 07:32 UTC, radiolinkW commented
> Needs to compile
> 
> This looks _very_ similar to the SPL06 driver.
> 
> This looks like we should be re-using the SPLP06 driver for the SPA, particularly if they can be distinguished by their WHOAMI registers or some other fingerprinting we can do.
> 
> We _seriously_ can't afford to copy a driver sideways - we're fast running out of flash on boards, and baros make their way into a lot of boards.
> 
> Can you think about whether it would be possible to augment the SPL driver, please?
> 
> I'm happy to take this to a DevCall to see if other devs disagree, but I don't think they will.

I also think it should be made into a driver, but the class name should not be SPL06.
What do you think the class name should be?

2024-08-27 02:02 UTC, peterbarker commented
> > Needs to compile
> > This looks _very_ similar to the SPL06 driver.
> > This looks like we should be re-using the SPLP06 driver for the SPA, particularly if they can be distinguished by their WHOAMI registers or some other fingerprinting we can do.
> > We _seriously_ can't afford to copy a driver sideways - we're fast running out of flash on boards, and baros make their way into a lot of boards.
> > Can you think about whether it would be possible to augment the SPL driver, please?
> > I'm happy to take this to a DevCall to see if other devs disagree, but I don't think they will.
> 
> I also think it should be made into a driver, but the class name should not be SPL06. What do you think the class name should be?SPX06？So the SPL06 driver needs to be rewritten.

Yes indeed, you could rename  `SPL06` to `SPx06` (lower-case x) and *only after creating a commit for that* adjust it to support the SPA06

2024-08-27 02:03 UTC, peterbarker commented
To be clear, if you rename a file, to it in a completely separate commit to everything else, including adjusting `#include`s.  This ensures the history on the file is preserved.

2024-08-29 03:08 UTC, radiolinkW commented
> To be clear, if you rename a file, to it in a completely separate commit to everything else, including adjusting `#include`s. This ensures the history on the file is preserved.

@peterbarker The SPA06 and SPL06 baro have been merged into an SPx06 driver and tested for narmal flight on the latest Copter4.5 branch.

2024-09-02 04:41 UTC, peterbarker requested changes
Partial review only.

This is looking good.   I might look at pulling out the renaming into a separate PR as, based on your work here, re-using the same code for the two devices it viable.

2024-09-02 04:41 UTC, peterbarker commented on libraries/AP_Baro/AP_Baro_SPx06.h
> +	};
```suggestion
	enum class Type {
	                UNKNOWN,
			SPL06,
			SPA06,
	};
```

... can do away with the is_spl06 and is_spa06 booleans after this change

2024-09-02 04:41 UTC, peterbarker commented on libraries/AP_Baro/AP_Baro_SPx06.h
> +    enum SPx06 _spx06_type;
```suggestion
    Type type;
```

2024-09-02 04:41 UTC, peterbarker commented on libraries/AP_Baro/AP_Baro_SPx06.cpp
> +
```suggestion
```

2024-09-02 04:41 UTC, peterbarker commented on libraries/AP_Baro/AP_Baro_SPx06.cpp
> +				is_SPL06=true;
```suggestion
				type = Type::SPL06;
```

etc

2024-09-02 04:41 UTC, peterbarker commented on libraries/AP_Baro/AP_Baro_SPx06.cpp
> +		if(is_SPL06 || is_SPA06)
```suggestion
		if (type != Type::UNKNOWN) {
```

2024-09-02 04:41 UTC, peterbarker commented on libraries/AP_Baro/AP_Baro_SPx06.cpp
> +    if(!is_SPL06 && !is_SPA06) {
```suggestion
    if (type == Type::UNKNOWN) {
```

2024-09-02 04:41 UTC, peterbarker commented on libraries/AP_Baro/AP_Baro_SPx06.cpp
> +	if(_spx06_type == BARO_SPL06)
```suggestion
	if(_spx06_type == BARO_SPL06) {
```

... we require braces even on one-line bodies - fix them all, please.

... also an indenting problem

2024-09-02 04:41 UTC, peterbarker commented on libraries/AP_Baro/AP_Baro_SPx06.cpp
> +	if(_spx06_type == BARO_SPL06)
Use a `switch`

2024-09-02 12:46 UTC, Hwurzburg commented
does this need an extract_features.py update or will a REGEX catch the change?

2024-09-03 02:55 UTC, radiolinkW commented on libraries/AP_Baro/AP_Baro_SPx06.cpp
> +	if(_spx06_type == BARO_SPL06)
> Use a `switch`

fixed them all.

2024-09-03 03:00 UTC, radiolinkW commented
> does this need an extract_features.py update or will a REGEX catch the change?

It should be updated, I replaced everything related to SPL06 with SPx06.

2024-09-03 03:01 UTC, radiolinkW commented
> Partial review only.
> 
> This is looking good. I might look at pulling out the renaming into a separate PR as, based on your work here, re-using the same code for the two devices it viable.

Updated and committed.

2024-09-03 08:00 UTC, peterbarker commented
@radiolinkW I've extracted those rename commits over here: https://github.com/ArduPilot/ardupilot/pull/27992/commits - I should be able to get that in soon which will let me take this to DevCallEU tomorrow for a merge, hopefully.

2024-09-03 10:13 UTC, radiolinkW commented
> @radiolinkW I've extracted those rename commits over here: https://github.com/ArduPilot/ardupilot/pull/27992/commits - I should be able to get that in soon which will let me take this to DevCallEU tomorrow for a merge, hopefully.

Thanks, won't the other three commits be merged?

2024-09-04 00:51 UTC, peterbarker commented
> > @radiolinkW I've extracted those rename commits over here: https://github.com/ArduPilot/ardupilot/pull/27992/commits - I should be able to get that in soon which will let me take this to DevCallEU tomorrow for a merge, hopefully.
> 
> Thanks, won't the other three commits be merged?

Oh yes - but we'll get the other ones in first.  That will make this one much easier to review on a DevCall to get it merged.

2024-09-05 08:12 UTC, peterbarker commented
> I also think it should be made into a driver, but the class name should not be SPL06. What do you think the class name should be?SPX06？So the SPL06 driver needs to be rewritten.

Unfortunately we both got this wrong, as it turns out.

tridge was very resistant to renaming this driver, and gave several good reasons why it would be a bad idea - mostly breaking things out-of-tree.  He pointed out several places in our codebase where we simply add comments indicating what devices a driver handles.

I've taken the liberty of removing the rename of the files and the rename of the class commits from your branch and fixing the conflicts

I've force-pushed over your branch here.

If you're happy to proceed from this point I'll leave a review so we can get this merged... also, testing that I haven't broken anything when I resolved those conflicts would be a good idea!

2024-09-06 08:43 UTC, radiolinkW commented
> > I also think it should be made into a driver, but the class name should not be SPL06. What do you think the class name should be?SPX06？So the SPL06 driver needs to be rewritten.
> 
> Unfortunately we both got this wrong, as it turns out.
> 
> tridge was very resistant to renaming this driver, and gave several good reasons why it would be a bad idea - mostly breaking things out-of-tree. He pointed out several places in our codebase where we simply add comments indicating what devices a driver handles.
> 
> I've taken the liberty of removing the rename of the files and the rename of the class commits from your branch and fixing the conflicts
> 
> I've force-pushed over your branch here.
> 
> If you're happy to proceed from this point I'll leave a review so we can get this merged... also, testing that I haven't broken anything when I resolved those conflicts would be a good idea!



> > I also think it should be made into a driver, but the class name should not be SPL06. What do you think the class name should be?SPX06？So the SPL06 driver needs to be rewritten.
> 
> Unfortunately we both got this wrong, as it turns out.
> 
> tridge was very resistant to renaming this driver, and gave several good reasons why it would be a bad idea - mostly breaking things out-of-tree. He pointed out several places in our codebase where we simply add comments indicating what devices a driver handles.
> 
> I've taken the liberty of removing the rename of the files and the rename of the class commits from your branch and fixing the conflicts
> 
> I've force-pushed over your branch here.
> 
> If you're happy to proceed from this point I'll leave a review so we can get this merged... also, testing that I haven't broken anything when I resolved those conflicts would be a good idea!

That's also good, there won't be much change.

But I didn't see  a comment in the top of the SPL06 driver saying it supports SPA06 as well, also, RadiolinkPIX6 does not enable Background mode by default.

2024-09-06 08:43 UTC, radiolinkW commented
> > I also think it should be made into a driver, but the class name should not be SPL06. What do you think the class name should be?SPX06？So the SPL06 driver needs to be rewritten.
> 
> Unfortunately we both got this wrong, as it turns out.
> 
> tridge was very resistant to renaming this driver, and gave several good reasons why it would be a bad idea - mostly breaking things out-of-tree. He pointed out several places in our codebase where we simply add comments indicating what devices a driver handles.
> 
> I've taken the liberty of removing the rename of the files and the rename of the class commits from your branch and fixing the conflicts
> 
> I've force-pushed over your branch here.
> 
> If you're happy to proceed from this point I'll leave a review so we can get this merged... also, testing that I haven't broken anything when I resolved those conflicts would be a good idea!

That's also good, there won't be much change.

But I didn't see a comment in the top of the SPL06 driver saying it supports SPA06 as well, also, RadiolinkPIX6 does not enable Background mode by default.

2024-09-07 09:58 UTC, peterbarker requested changes
Have you tested an SPL06 device to ensure it continues to function normally after these changes?

Please outline the advantages of using the "background" mode of the SPA06...

2024-09-07 09:58 UTC, peterbarker commented on libraries/AP_Baro/AP_Baro_SPL06.cpp
> +		break;
```suggestion
```

by omitting the default case we help someone adding the next `Type::SPx06` driver as they're forced to fill in each of the switch statements.

2024-09-07 09:58 UTC, peterbarker commented on libraries/AP_Baro/AP_Baro_SPL06.cpp
> +#ifdef SPL06_BACKGROUND_ENABLE
```suggestion
#if AP_BARO_SPL06_BACKGROUND_ENABLE
```

And ensure this is always define

2024-09-07 09:58 UTC, peterbarker commented on libraries/AP_Baro/AP_Baro_SPL06.cpp
> +		press_temp_comp= _temp_raw * ((float)_c01 + press_raw_sc * ((float)_c11 + press_raw_sc * _c21));
```suggestion
		press_temp_comp = _temp_raw * ((float)_c01 + press_raw_sc * ((float)_c11 + press_raw_sc * _c21));
```

2024-09-07 09:58 UTC, peterbarker commented on libraries/AP_Baro/AP_Baro_SPL06.cpp
> +		press_temp_comp= _temp_raw * ((float)_c01 + press_raw_sc * ((float)_c11 + press_raw_sc * ((float)_c21) + press_raw_sc * _c31));
```suggestion
		press_temp_comp = _temp_raw * ((float)_c01 + press_raw_sc * ((float)_c11 + press_raw_sc * ((float)_c21) + press_raw_sc * _c31));
```

2024-09-07 09:58 UTC, peterbarker commented on libraries/AP_Baro/AP_Baro_SPL06.cpp
> +    float press_temp_comp;
```suggestion
    float pressure_cal = 0;
    float press_temp_comp = 0;
```

2024-09-07 09:58 UTC, peterbarker commented on libraries/AP_Baro/AP_Baro_SPL06.cpp
> +		break;
```suggestion
```

2024-09-07 09:58 UTC, peterbarker commented on libraries/AP_Baro/AP_Baro_SPL06.cpp
> +    uint8_t SPL06_CALIB_COEFFS_LEN;
```suggestion
    uint8_t SPL06_CALIB_COEFFS_LEN = 18;
```

2024-09-09 10:44 UTC, radiolinkW commented
> Have you tested an SPL06 device to ensure it continues to function normally after these changes?
> 
> Please outline the advantages of using the "background" mode of the SPA06...

The latest commit has been tested for narmal flight on the latest Copter4.5 branch.

Background mode only measures continuously, without manually enabling measurements periodically.

2024-09-11 08:03 UTC, radiolinkW commented
> @radiolinkW have you tested a device with an SPL06 in it?
> 
> I'm marking this for discussion DevCallEU, and that question _will_ be asked :-)

Tested on RadiolinkPIX6 with SPA06.

2024-09-11 08:27 UTC, tridge approved these changes

2024-09-11 08:27 UTC, peterbarker approved these changes

2024-09-11 08:27 UTC, merged

2024-09-11 08:28 UTC, peterbarker commented
Merged, thanks!

2024-11-10 13:22 UTC, menschel commented
Hello, does this change also influence the SPL001 update rate?

I have Baro-0 /Baro-4 i.e. Baro Bad Health issues on a plane while circling over a field for 30minutes and I believe it is due to the baro having the same value for 2 seconds.

Meaning to ask, does it make sense to test with AP4.6Beta1 or write an Issue Report directly?