board-types.txt:reserve IDs for VIEWPRO
ArduPilot/ardupilot pull request #27946
Opened 2024-08-28 10:11 UTC by LCaiJie

2024-08-28 10:22 UTC, peterbarker requested changes

2024-08-28 10:22 UTC, peterbarker commented on Tools/AP_Bootloader/board_types.txt
> +# IDs 7100-7199 reserved for VIEWPRO
```suggestion
# IDs 7100-7109 reserved for VIEWPRO
```

2024-08-28 10:26 UTC, LCaiJie commented on Tools/AP_Bootloader/board_types.txt
> +# IDs 7100-7199 reserved for VIEWPRO
Ok, I'll edit and push it.

2024-08-28 10:31 UTC, peterbarker approved these changes
LGTM

2024-08-29 00:20 UTC, rmackay9 commented
Could we fixup the commit messages?  I think they should start with "AP_HAL_ChibiOS:"

2024-08-29 22:51 UTC, merged