Run tests sequentially and enforce tests in ROS 2
ArduPilot/ardupilot pull request #28024
Opened 2024-09-05 23:51 UTC by Ryanf55

h1. Purpose

Use sequential testing in ROS to prevent multiple tests from communicating traffic.
We also were only testing the test package, rather than ardupilot_sitl and ardupilot_msgs. 
Because pre-commit isn't enforced, we had some style regressions I fixed, and now it's enforced in CI.

2024-09-06 01:51 UTC, peterbarker approved these changes

2024-09-06 01:51 UTC, peterbarker requested changes
Commit messages need fixing

2024-09-06 01:57 UTC, Ryanf55 commented
> Commit messages need fixing

Fixed, oops.

2024-09-06 04:48 UTC, peterbarker approved these changes

2024-09-06 11:28 UTC, merged

2024-09-07 18:13 UTC, Ryanf55 commented
Without this, you see this when testing:
```
[dds_udp.parm --synthetic-clock -14] bind port 5760 for SERIAL0
[dds_udp.parm --synthetic-clock -14] bind failed on port 5760 - Address already in use
[mavproxy.py -13] /bin/sh: 1: mavproxy.py: not found
[ERROR] [mavproxy.py -13]: process has died [pid 433252, exit code 127, cmd 'mavproxy.py  --out 127.0.0.1:14550  --out  127.0.0.1:14551  --master tcp:127.0.0.1:5760  --sitl 127.0.0.1:5501  --non-interactive '].
```