Fix Static Notches
ArduPilot/ardupilot pull request #28034
Opened 2024-09-07 15:48 UTC by andyp1per

Bug introduced in https://github.com/ArduPilot/ardupilot/pull/25442
I will note in passing that my review indicated this shouldn't be removed.
I have added a test to make sure this can't regress

2024-09-07 17:27 UTC, IamPete1 commented
I think we should still remove the check here: https://github.com/ArduPilot/ardupilot/blob/3dd44dd8e07230f03c87302211498184dcdab6b3/libraries/AP_InertialSensor/AP_InertialSensor.cpp#L1871

It will allow runtime param changes to take affect for static notch as they do for the others.

2024-09-07 17:50 UTC, andyp1per commented
> It will allow runtime param changes to take affect for static notch as they do for the others

This was/is covered by the init() above. The reason not to do it here is the cost of updating the static notch all the time when it doesn't need it.

2024-09-07 18:16 UTC, IamPete1 commented
> This was/is covered by the init() above.

The init allows runtime change in frequency/bandwidth/attenuation but not runtime change in harmonics or double/triple notch.

> The reason not to do it here is the cost of updating the static notch all the time when it doesn't need it.

I guess I don't really understand why we carefully check if we should re-init due to param change. It seems to be the update is the costly one we just do that all the time (except static). Why don't we check for a change in options or harmonic too and then call init and update at once?

2024-09-07 19:25 UTC, andyp1per commented
> The init allows runtime change in frequency/bandwidth/attenuation but not runtime change in harmonics or double/triple notch.

I mean this is true, but I don't think what you are suggesting fixes this does it? I agree that allowing runtime changes to these properties would be convenient.


> I guess I don't really understand why we carefully check if we should re-init due to param change. It seems to be the update is the costly one we just do that all the time (except static). Why don't we check for a change in options or harmonic too and then call init and update at once?

Really just copying the pattern that was there for the LPF. It is true that calculating A&Q is expensive, so avoiding doing that all the time makes sense. However, we have made a lot of effort into making update cheap, so it may be that simply removing the check is not such a big deal anymore.

2024-09-08 06:00 UTC, tridge requested changes
good find, thanks!

2024-09-08 08:11 UTC, tridge requested changes

2024-09-08 08:11 UTC, tridge commented on libraries/Filter/HarmonicNotchFilter.cpp
> +    update(center_freq_hz);
fix here: https://github.com/tridge/ardupilot/commits/pr-static-notch/

2024-09-08 09:05 UTC, andyp1per commented
Thanks @tridge I've pulled in the change

2024-09-08 09:11 UTC, tridge approved these changes

2024-09-08 22:35 UTC, IamPete1 approved these changes
I think this is correct.

2024-09-08 23:29 UTC, merged