Tools: stop requiring python-is-python3 packets
ArduPilot/ardupilot pull request #28055
Opened 2024-09-10 02:59 UTC by peterbarker

2024-09-10 03:09 UTC, Ryanf55 commented
If you uninstall this, you find that waf can't run.
```
$ ./Tools/autotest/sim_vehicle.py -v ArduPlane -DG --console --enable-dds
SIM_VEHICLE: Start
SIM_VEHICLE: Killing tasks
SIM_VEHICLE: Starting up at SITL location
SIM_VEHICLE: WAF build
SIM_VEHICLE: Configure waf
SIM_VEHICLE: "/home/ryan.friedman/Dev/ardu_ws/src/ardupilot/modules/waf/waf-light" "configure" "--board" "sitl" "--debug" "--enable-dds"
/usr/bin/env: ‘python’: No such file or directory
SIM_VEHICLE: (Configure waf) exited with code 32512
SIM_VEHICLE: Killing tasks
```

It was the python team's recommendation to update shebangs if a script could run on python3, to say python3. 
This shouldn't be a huge change, and you can run python3 on Ubuntu 18 (bionic) which is EOL. On Ubuntu 20 (focal), python3 is the default.


```
docker run --net host -it ubuntu:18.04 bash
#apt update
#apt install python-dev
# which python
/usr/bin/python
# python --version
Python 2.7.17
# apt install python3-dev
# python3 --version
Python 3.6.9
```

To me, the risk of impacting people is low because we already install `python3-dev` in ubuntu 18.
https://github.com/ArduPilot/ardupilot/blob/33d75f10e71844913023c10907f6e33b82347419/Tools/environment_install/install-prereqs-ubuntu.sh#L85-L89

2024-09-10 10:02 UTC, khancyr approved these changes
We don't support py2 anymore (or not actively), so yes let's go into this direction !

2024-09-11 05:12 UTC, Ryanf55 approved these changes
When we do this, we can also remove the `# encoding: utf-8` line, that's only needed in python2 scripts.

2024-09-11 07:37 UTC, peterbarker commented
OK, all good, full-steam ahead.

2024-09-12 05:15 UTC, peterbarker commented
> First action seems to go request to the waf maintainer if they would be interested in following these recommendations: https://peps.python.org/pep-0394/#for-python-script-publishers

What entry-point are you worried about?  `waf-light`?  I usually use `./waf` so I wouldn't get the problem :-)

Have you checked to see if it has been updated upstream?

We could probably also carry a trivial patch for it if required.

2024-09-12 05:20 UTC, Ryanf55 commented
> > First action seems to go request to the waf maintainer if they would be interested in following these recommendations: https://peps.python.org/pep-0394/#for-python-script-publishers
> 
> What entry-point are you worried about? `waf-light`? I usually use `./waf` so I wouldn't get the problem :-)

I removed python-is-python3 and it errored out in the waf submodule when building, so that's why I thought to start there.

> Have you checked to see if it has been updated upstream?

Yea, I checked upstream, it's still using `/usr/bin/env python` and there's nothing on the issue tracker about it.

> We could probably also carry a trivial patch for it if required.

For sure! It should be easy to whip up. I'll give it a go unless you're bored.

2024-09-14 09:51 UTC, peterbarker commented
>>     We could probably also carry a trivial patch for it if required.
> For sure! It should be easy to whip up. I'll give it a go unless you're bored.

Please go ahead.  See what happens if you PR upstream too?

2024-10-03 00:19 UTC, peterbarker commented
@Ryanf55 I've created a trivial PR against our waf fork to use python3 and referenced it in here.

I think past this we don't require `python` to be in your path.

I've left the environment install stuff alone, on the basis that without it you can't check out 4.5 and expect things to work without more hackery.  Maybe in 4.7 we can get rid of those.

2024-10-07 20:55 UTC, peterbarker commented
Needs https://github.com/ArduPilot/waf/pull/19

2024-10-07 23:08 UTC, tridge requested changes

2024-10-07 23:08 UTC, tridge commented on Tools/environment_install/install-prereqs-windows-andAPMSource.ps1
> +Start-Process -wait -FilePath "C:\cygwin64\bin\bash" -ArgumentList "--login -i -c 'pip3 install empy==3.3.4 pyserial pymavlink intelhex dronecan pexpect'"
change to python3 -m pip

2024-10-07 23:08 UTC, tridge commented on Tools/environment_install/install-prereqs-windows.ps1
> +Start-Process -wait -FilePath "C:\cygwin64\bin\bash" -ArgumentList "--login -i -c 'pip3 install empy==3.3.4 pyserial pymavlink intelhex dronecan pexpect'"
should be python3 -m pip

2024-10-07 23:10 UTC, tridge commented
can be merged after module update and pip3 -> python3 -m pip

2024-10-08 16:35 UTC, Ryanf55 commented on Tools/environment_install/install-prereqs-windows-andAPMSource.ps1
> +Start-Process -wait -FilePath "C:\cygwin64\bin\bash" -ArgumentList "--login -i -c 'pip3 install empy==3.3.4 pyserial pymavlink intelhex dronecan pexpect'"
```suggestion
Start-Process -wait -FilePath "C:\cygwin64\bin\bash" -ArgumentList "--login -i -c 'python3 -m pip install empy==3.3.4 pyserial pymavlink intelhex dronecan pexpect'"
```

2024-10-08 16:35 UTC, Ryanf55 commented on Tools/environment_install/install-prereqs-windows.ps1
> +Start-Process -wait -FilePath "C:\cygwin64\bin\bash" -ArgumentList "--login -i -c 'pip3 install empy==3.3.4 pyserial pymavlink intelhex dronecan pexpect'"
```suggestion
Start-Process -wait -FilePath "C:\cygwin64\bin\bash" -ArgumentList "--login -i -c 'python3 -m pip install empy==3.3.4 pyserial pymavlink intelhex dronecan pexpect'"
```

2024-10-08 16:36 UTC, Ryanf55 commented
> can be merged after module update and pip3 -> python3 -m pip

I applied those changes. Just needs that fixup squashed into `Tools.`

2024-10-10 23:19 UTC, peterbarker commented
> > can be merged after module update and pip3 -> python3 -m pip
> 
> I applied those changes. Just needs that fixup squashed into `Tools.`

Ah, whoops.  Sorry, I didn't see this 'til now, and I've force-pushed.

Please ping me if you want to force-push one of my branches - I force-push and ask questions later on my own branches!

I think this one is good to merge now and have marked it as such.

2024-10-15 00:11 UTC, merged