Rover: reject position targets if acceleration supplied
ArduPilot/ardupilot pull request #28076
Opened 2024-09-11 02:06 UTC by peterbarker

Replaces https://github.com/ArduPilot/ardupilot/pull/26955/files which simply factored the check out.

This both factors the check out and stops us accepting the position target if acceleration is set.

We should probably also reject if other bits and pieces are set.

2024-09-11 02:32 UTC, rmackay9 commented
Thanks @peterbarker for this.  I guess this has been tested in some way?

2024-09-11 02:35 UTC, peterbarker commented
```
Board                    AP_Periph  blimp  bootloader  copter  heli  iofirmware  plane  rover  sub
CubeOrange-periph-heavy  *                                                                     
Durandal                            *      *           *       *                 *      -24    *
Hitec-Airspeed           *                                                                     
KakuteH7-bdshot                     *      *           *       *                 *      8      *
MatekF405                           *      *           *       *                 *      0      *
Pixhawk1-1M-bdshot                  *                  *       *                 *      0      *
f103-QiotekPeriph        *                                                                     
f303-Universal           *                                                                     
iomcu                                                                *                         
revo-mini                           *      *           *       *                 *      0      *
skyviper-v2450                                         *                                       
```

2024-09-11 02:49 UTC, peterbarker commented
Tested in SITL with these commands:
```
# this one should move the vehicle:
# message set_position_target_local_ned 0 1 1 1 0b1111111111111000 10 10 0 0 0 0 0 0 0 0 0

# this one should be ignored as acceleration is supplied along with position:
# message set_position_target_local_ned 0 1 1 1 0b1111111000111000 10 10 0 0 0 0 0 0 0 0 0

# should work:
# message set_position_target_global_int 0 1 1 0 0b1111111111111000 -353630399 1491652946 0 0 0 0 0 0 0 0 0 

# acceleration not ignored:
# message set_position_target_global_int 0 1 1 0 0b1111111000111000 -353630399 1491652946 0 0 0 0 0 0 0 0 0 
```

(and gdb and breakpoints)

2024-09-17 00:00 UTC, rmackay9 approved these changes

2024-09-17 00:20 UTC, rmackay9 requested changes
We discussed on the dev call and decided that we should add some text feedback to the user if their message is rejected because it's malformed

2024-09-17 00:21 UTC, Ryanf55 commented
Relates to #23430 which has the same inability to share errors back to users for silently dropping invalid commands

2024-09-17 11:54 UTC, peterbarker commented
As requested:

```
GUIDED> message set_position_target_global_int 0 1 1 0 0b1111111000111000 -353630399 1491652946 0 0 0 0 0 0 0 0 0 
GUIDED> AP: Ignoring SET_POSITION_TARGET_GLOBAL_INT; set ACC_IGNORE in mask
```

2024-09-23 23:32 UTC, rmackay9 commented on Rover/GCS_Mavlink.cpp
> +void GCS_MAVLINK_Rover::send_acc_ignore_must_be_set_message(const char *msgname)
sorry to be annoying but can you add a comment above the method?  Just copying the method from the .h is fine.

2024-09-23 23:33 UTC, rmackay9 approved these changes
after the comment update, feel free to merge, thanks!

2025-05-01 04:26 UTC, peterbarker commented on Rover/GCS_Mavlink.cpp
> +void GCS_MAVLINK_Rover::send_acc_ignore_must_be_set_message(const char *msgname)
Done

2025-05-02 06:06 UTC, merged