AP_OSD: don't go via RCMap singleton to get RPTY RC channels
ArduPilot/ardupilot pull request #28095
Opened 2024-09-13 08:20 UTC by peterbarker

Tested in SITL using `--osd`

Extracted from https://github.com/ArduPilot/ardupilot/pull/28089

2024-09-13 08:30 UTC, peterbarker commented
```
Board                    AP_Periph  blimp  bootloader  copter  heli  iofirmware  plane  rover  sub
CubeOrange-periph-heavy  *                                                                     
Durandal                            *      *           -8      -8                -8     -8     *
Hitec-Airspeed           *                                                                     
KakuteH7-bdshot                     *      *           0       0                 0      0      *
MatekF405                           *      *           0       0                 0      0      *
Pixhawk1-1M-bdshot                  *                  *       *                 *      *      *
f103-QiotekPeriph        *                                                                     
f303-Universal           *                                                                     
iomcu                                                                *                         
revo-mini                           *      *           0       0                 0      0      *
skyviper-v2450                                         *                                       
```

2024-09-17 00:34 UTC, tridge requested changes

2024-09-17 00:34 UTC, tridge commented on libraries/AP_OSD/AP_OSD_ParamScreen.cpp
> +    const auto chan = &chanref;
i'd prefer const auto *chan = &chanref;

2024-09-17 03:55 UTC, peterbarker commented on libraries/AP_OSD/AP_OSD_ParamScreen.cpp
> +    const auto chan = &chanref;
Done

2024-09-17 12:10 UTC, merged