SkySakura H743 fc Support
ArduPilot/ardupilot pull request #28094
Opened 2024-09-13 08:08 UTC by BloodSakura3774

SkySakura H743 fc Support

2024-10-04 09:25 UTC, BloodSakura3774 commented
May I ask if this will be merged and included in copter 4.5.7?

2024-10-08 13:42 UTC, Hwurzburg requested changes
in addition to comments, this needs a bootloader and you should consider enabling SD card in thee bootloader for updating firmware via SD card

as to backports, that can be decided after this gets merged since 4.6 is about to release

also, it would be good to send a few boards to support devs in case something arises that needs board testing .... @andyp1per , @petebarker, and or myself would be good potential recipients, if you desire...

2024-10-08 13:42 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/SkySakuraH743/README.md
> + - BATT2_MONITOR 4
```suggestion
 - set BATT2_MONITOR 4
```

2024-10-08 13:42 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/SkySakuraH743/README.md
> +These are set by default in the firmware and shouldn't need to be adjusted
remove this line 87

2024-10-08 13:42 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/SkySakuraH743/README.md
> +
```suggestion
 - se BATT2_AMP_PERVLT set to appropriate value for second current sensor
```

2024-10-08 13:42 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/SkySakuraH743/README.md
> +The SkySakura H743 have a builtin IST8310 compass.
```suggestion
The SkySakura H743 have a builtin IST8310 compass. Due to motor interference, users often disable this compass and use an external compass attached via the external SDA/SCL pins.
```

2024-10-08 13:42 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/SkySakuraH743/README.md
> +*.apj firmware files.
```suggestion
\*.apj firmware files.
```

2024-10-08 13:42 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/SkySakuraH743/README.md
> +
```suggestion

##Firmware

Firmware can bee found on the `firmware server < https://firmware.ardupilot.org`__ in the "SkySakuraH743"  folders

```

2024-10-08 13:42 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/SkySakuraH743/README.md
> +|SERIAL6|TX6/RX6|UART6 (VTX, DMA-enabled)|
```suggestion
|SERIAL6|TX6/RX6|UART6 (DisplayPort, DMA-enabled)|
```

2024-10-08 13:42 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/SkySakuraH743/README.md
> +|SERIAL7|TX8/RX8|UART8 (ESC-Telemetry)|
```suggestion
|SERIAL7|TX8/RX8|UART8 (ESC-Telemetry, RX8 on ESC connectors, TX8 can be used if protocol is change from ESC telem|
```

2024-10-08 13:42 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/SkySakuraH743/README.md
> +
```suggestion

## VTX Power Control

The 12VSW output voltage on the HD VTX connector is controlled by GPIO 85, via RELAY1 by default. Low activates the voltage.

```

2024-10-08 13:42 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/SkySakuraH743/hwdef.dat
> +PD11 SAFETY_IN INPUT PULLDOWN
```suggestion
PD11 SAFETY_IN INPUT PULLDOWN
#disable safety button by default
define BOARD_SAFETY_ENABLE_DEFAULT 0
```

2024-10-08 13:42 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/SkySakuraH743/hwdef.dat
> +# USART1 (SPARE)
```suggestion
# USART1 (TELEM2)
```

2024-10-08 13:42 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/SkySakuraH743/hwdef.dat
> +# USART2 (SPARE)
```suggestion
# USART2 (USER)
```

2024-10-08 13:42 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/SkySakuraH743/hwdef.dat
> +PD6 USART2_RX USART2 NODMA
```suggestion
PD6 USART2_RX USART2 NODMA
define DEFAULT_SERIAL3_PROTOCOL SerialProtocol_None 
```

2024-10-08 13:42 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/SkySakuraH743/hwdef.dat
> +PB8 UART4_RX UART4
```suggestion
PB8 UART4_RX UART4 
define DEFAULT_SERIAL5_PROTOCOL SerialProtocol_RCIN
```

2024-10-08 13:42 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/SkySakuraH743/hwdef.dat
> +# USART6 (VTX)
```suggestion
# USART6 (DisplayPort)
```

2024-10-08 13:42 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/SkySakuraH743/hwdef.dat
> +PC6 USART6_TX USART6
```suggestion
PC6 USART6_TX USART6 
define DEFAULT_SERIAL6_PROTOCOL SerialProtocol_MSP_DisplayPort
```

2024-10-08 13:42 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/SkySakuraH743/hwdef.dat
> +PE1 UART8_TX UART8 NODMA
```suggestion
PE1 UART8_TX UART8 NODMA
define DEFAULT_SERIAL7_PROTOCOL SerialProtocol_ESCTelemetry

```

2024-10-08 13:42 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/SkySakuraH743/hwdef.dat
> +PE15 PINIO1 OUTPUT GPIO(85) LOW
to conform to pattern this would be
```suggestion
PE15 VTX_PWR OUTPUT LOW GPIO(85)
define RELAY1_PIN_DEFAULT 85
```

2024-10-08 13:42 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/SkySakuraH743/defaults.parm
> +# SERIAL1 is MAVLink2 by default
delete all items.....they are in hwdef to not consume flash....only these are needed:
SERVO13_FUNCTION 120
NTF_LED_TYPES 257

2024-10-08 15:25 UTC, BloodSakura3774 commented on libraries/AP_HAL_ChibiOS/hwdef/SkySakuraH743/README.md
> + - BEC output: 5V 5A & 12V 5A (MAX 60W total)
12v not only available at vtx port, but also has its own pads.

2024-10-08 15:54 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/SkySakuraH743/README.md
> + - BEC output: 5V 5A & 12V 5A (MAX 60W total)
is the pad switched with gpio?

2024-10-08 16:06 UTC, BloodSakura3774 commented on libraries/AP_HAL_ChibiOS/hwdef/SkySakuraH743/README.md
> + - BEC output: 5V 5A & 12V 5A (MAX 60W total)
No, we have 12vsw pad and 12v normal pad, 12vsw is switched with gpio, 12v is directly connected to bec output.

2024-10-10 16:47 UTC, BloodSakura3774 commented
> in addition to comments, this needs a bootloader and you should consider enabling SD card in thee bootloader for updating firmware via SD card
Added, but I'm not sure if the defines are correct.

> also, it would be good to send a few boards to support devs in case something arises that needs board testing .... @andyp1per , @PeteBarker, and or myself would be good potential recipients, if you desire...
We have contacted Andy and got his address month ago, but we are still waiting for first batches to arrive. Will be providing samples to other devs.

2024-10-18 16:00 UTC, BloodSakura3774 commented
Sorry, but the bootloader is added now. Is there any other problem with this pr?

2024-10-22 12:25 UTC, Hwurzburg commented
has this been tested now on final hardware?

2024-10-23 07:39 UTC, BloodSakura3774 commented
Yes it is, this is the last commit for correcting the hwdef.

2024-10-26 19:13 UTC, Hwurzburg approved these changes

2024-10-28 07:15 UTC, BloodSakura3774 commented
Should I do a squash now or later when you are finish reviewing it?

2024-11-04 09:20 UTC, BloodSakura3774 commented
website is currently not ready, we have not planned to sell is outside of china yet, will add once its ready

2024-11-07 23:50 UTC, merged