CI: build CubeBlack-EKF2 not CubeOrange-EKF2 in CI
ArduPilot/ardupilot pull request #28128
Opened 2024-09-17 06:04 UTC by peterbarker

we really just care that EKF2 builds here, the board really isn't that important

2024-09-17 13:28 UTC, Ryanf55 approved these changes

2024-09-18 08:42 UTC, tridge requested changes

2024-09-18 08:42 UTC, tridge commented on .github/workflows/test_chibios.yml
> +            CubeBlack-EKF2,
let's make this CubeRed

2024-09-18 09:20 UTC, peterbarker commented on .github/workflows/test_chibios.yml
> +            CubeBlack-EKF2,
Done

2024-09-19 01:42 UTC, merged