Ensure all peripherals define HAL_PERIPH_ENABLE_GPS to 1 or 0
ArduPilot/ardupilot pull request #28127
Opened 2024-09-17 05:49 UTC by peterbarker

2024-11-10 04:01 UTC, peterbarker commented
It was generally agreed this was a good idea, but we should take the opportunity to rename HAL_PERIPH_ENABLE_GPS to `AP_PERIPH_GPS_ENABLED` etc

2025-01-14 23:24 UTC, peterbarker commented
This is a no-compiler-output change.

2025-01-20 23:59 UTC, tridge requested changes

2025-01-20 23:59 UTC, tridge commented on libraries/AP_HAL_ChibiOS/hwdef/scripts/defaults_periph.h
> +#define AP_PERIPH_MSP_ENABLED 1
why the MSP change?

2025-01-21 00:01 UTC, tridge commented
ok to merge with MSP fixup

2025-01-23 04:22 UTC, peterbarker commented on libraries/AP_HAL_ChibiOS/hwdef/scripts/defaults_periph.h
> +#define AP_PERIPH_MSP_ENABLED 1
Fixed

2025-01-23 06:47 UTC, peterbarker commented
This is still a no-compiler-output-change.

Merging.

2025-01-23 06:47 UTC, merged

2025-01-23 06:52 UTC, shiv-tyagi commented
Thankyou so much @peterbarker.