TBS LUCID Pro
ArduPilot/ardupilot pull request #28146
Opened 2024-09-18 16:03 UTC by andyp1per

2024-09-18 20:12 UTC, Hwurzburg commented
@andyp1per missing image

2024-09-18 20:17 UTC, andyp1per commented
> @andyp1per missing image

Very draft right now - don't review until its out of draft

2024-11-01 12:06 UTC, Hwurzburg commented
Need pinots for GH connectors

2024-12-25 17:06 UTC, Hwurzburg commented
@andyp1per started looking at this...some questions before a I post a formal  review since there are some big disconnects:
1. UART1, RCin, is not pinned out in the images...where is it?
2. Images show UART7/8 which are not defined
3. is inverted SBus really connected to RX5? just checking since the other UARTs are iffy and hwdef says there is no TX5 but its shown on pinout
4. if UART1 really is RCin, shouldn't it be in the DMA priority list rather than UART5?
5. if PWM5/6 are not DShot, shouldn't you tag them NODMA?

2024-12-25 21:40 UTC, andyp1per commented
> * UART1, RCin, is not pinned out in the images...where is it?

Need new images. It's the CRSF port.

> * Images show UART7/8 which are not defined

Need new images.

> * is inverted SBus really connected to RX5? just checking since the other UARTs are iffy and hwdef says there is no TX5 but its shown on pinout

That's what the schematic says

> * if UART1 really is RCin, shouldn't it be in the DMA priority list rather than UART5?

The DMA mapping works out fine - I checked. You only need to add to DMA_PRIORITY to move things about.

> * if PWM5/6 are not DShot, shouldn't you tag them NODMA?

They could be used for dshot. Can't be NODMA because one is the LED which needs DMA.

2025-01-13 10:33 UTC, andyp1per commented
Silk screen updated @Hwurzburg

2025-01-14 00:49 UTC, Hwurzburg requested changes
the image has several errors, in addition to my other comments:
- UART5_RX should be UART2_RX
- CAMC should be CAMC/PWM5

2025-01-14 00:49 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO/README.md
> + - SERIAL5 -> UART5 (SBUS RX)
```suggestion
 - SERIAL5 -> UART5 (User, RX5 is SBUS input and is inverted from pin)
```
it better be inverted from pin to UART5 RX or sbus wont work!

2025-01-14 00:49 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO/README.md
> +use SERIAL5.
```suggestion
use SERIAL5, set its protocol to RCIN ("23") and change SERIAL1_PROTOCOL to something other than RCIN ("23")..
```

2025-01-14 00:49 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO/README.md
> +FrSky Telemetry is supported using an unused UART, such as the T3 pin (UART3 transmit).
```suggestion
FrSky Telemetry is supported using an unused UART, such as the T5 pin (UART5 transmit).
```

2025-01-14 00:49 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO/README.md
> +  - SERIAL3_PROTOCOL 10
```suggestion
  - SERIAL5_PROTOCOL 10
```

2025-01-14 00:49 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO/README.md
> +  - SERIAL3_OPTIONS 7
```suggestion
  - SERIAL5_OPTIONS 7
```

2025-01-14 00:49 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO/README.md
> + - PWM 1-2   in group1
@andyp1per does this work for BDShot? this timer shares DMA with SPI

2025-01-14 00:49 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO/README.md
> + - BATT_VOLT_PIN 12
```suggestion
 - BATT_VOLT_PIN 10
```

2025-01-14 00:49 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO/README.md
> + - BATT_VOLT_MULT 11.1
```suggestion
 - BATT_VOLT_MULT 20
```

2025-01-14 00:49 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO/README.md
> + - BATT_AMP_PERVLT 25
```suggestion
 - BATT_AMP_PERVLT 40
```

2025-01-14 00:49 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO/README.md
> +
```suggestion

## Firmware
Firmware for this board can be found `here <https://firmware.ardupilot.org>`__ in sub-folders labeled “TBS_LUCID_PRO”
```

2025-01-14 00:49 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO/hwdef.dat
> +# Servos
the SPARE PC2 and PC3 solder pads are not defined in this hwdef

2025-01-15 18:29 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO/README.md
> + - SERIAL5 -> UART5 (SBUS RX)
Thanks, fixed

2025-01-15 18:29 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO/README.md
> +FrSky Telemetry is supported using an unused UART, such as the T3 pin (UART3 transmit).
Thanks, fixed

2025-01-15 18:29 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO/README.md
> +  - SERIAL3_PROTOCOL 10
Thanks, fixed

2025-01-15 18:29 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO/README.md
> +  - SERIAL3_OPTIONS 7
Thanks, fixed

2025-01-15 18:29 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO/README.md
> + - PWM 1-2   in group1
Yes it works

2025-01-15 18:29 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO/README.md
> + - BATT_VOLT_PIN 12
Thanks, fixed

2025-01-15 18:29 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO/README.md
> + - BATT_VOLT_MULT 11.1
Thanks, fixed

2025-01-15 18:29 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO/README.md
> + - BATT_AMP_PERVLT 25
Thanks, fixed

2025-01-15 18:29 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO/README.md
> +
Thanks, fixed

2025-01-15 18:29 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO/hwdef.dat
> +# Servos
Not used so not defined

2025-01-15 18:32 UTC, andyp1per commented
> the image has several errors, in addition to my other comments:
> 
>     * UART5_RX should be UART2_RX

I've asked them to fix

>     * CAMC should be CAMC/PWM5

I think this is ok - its a generic picture that covers BF as well which will not have PWM5

2025-01-15 18:34 UTC, Hwurzburg commented
so we should not tell AP users there is a PWM5?otherwise i think the image should show it

2025-01-16 08:10 UTC, andyp1per commented
> * UART5_RX should be UART2_RX

README is right, hwdef is wrong - I have fixed

2025-01-16 13:50 UTC, Hwurzburg requested changes

2025-01-16 13:50 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO/README.md
> +use SERIAL5, set its protocol to RCIN ("23") and change SERIAL1_PROTOCOL to something other than RCIN ("23").
```suggestion
use SERIAL2, set its protocol to RCIN ("23") and change SERIAL1_PROTOCOL to something other than RCIN ("23").
```

2025-01-16 13:50 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO/README.md
> +FrSky Telemetry is supported using an unused UART, such as the TT pin (UART5 transmit).
```suggestion
FrSky Telemetry is supported using an unused UART, such as the TX4 pin (UART4 transmit).
```

2025-01-16 13:50 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO/README.md
> +  - SERIAL5_PROTOCOL 10
```suggestion
  - SERIAL4_PROTOCOL 10
```

2025-01-16 13:50 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO/README.md
> +  - SERIAL5_OPTIONS 7
```suggestion
  - SERIAL4_OPTIONS 7
```

2025-01-16 13:50 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO/README.md
> + - PWM 5-6   in group3 (No DShot)
```suggestion
 - PWM 5-6   in group3 (No DShot). PWM5 marked as "CAMC", PWM6 as "LED"
```

2025-01-16 14:06 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO/README.md
> +use SERIAL5, set its protocol to RCIN ("23") and change SERIAL1_PROTOCOL to something other than RCIN ("23").
Thanks fixed

2025-01-16 14:06 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO/README.md
> +FrSky Telemetry is supported using an unused UART, such as the TT pin (UART5 transmit).
Thanks fixed

2025-01-16 14:06 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO/README.md
> +  - SERIAL5_PROTOCOL 10
Thanks fixed

2025-01-16 14:06 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO/README.md
> +  - SERIAL5_OPTIONS 7
Thanks fixed

2025-01-16 14:06 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO/README.md
> + - PWM 5-6   in group3 (No DShot)
Thanks fixed

2025-01-16 14:06 UTC, andyp1per commented
Thanks @Hwurzburg

2025-01-16 14:09 UTC, Hwurzburg approved these changes

2025-01-18 04:24 UTC, merged

2025-01-21 10:59 UTC, rmackay9 commented
this is included in ArduPilot-4.6.0-beta3