AP_BattMonitor: add option minimum volt option
ArduPilot/ardupilot pull request #28148
Opened 2024-09-19 01:58 UTC by loki077

Allows aggregate monitors like Sum and ESC to report the minimum voltage instead of the average voltage. This is useful for systems with multiple isolated batteries where the lowest voltage is the limiting factor.

@robertlong13

2024-09-19 10:54 UTC, IamPete1 commented
You can setup your low voltage failsafes on the individual battery monitors before combining them in the sum. That is not a option for ESC of course. 

I think the problem here is that the consumed energy calculation will be thrown off. Maybe you could apply the min voltage after the `update_consumed` call?

2024-09-19 11:37 UTC, robertlong13 commented
That works for failsafes, but we want to display the number easily to the pilot. That could be done with GCS customizations instead I suppose, but this felt nicer.

Good point about the consumed energy calculation. We can revise so that this option doesn't impact that calc.

2024-09-19 15:21 UTC, Hwurzburg requested changes
this should not be included on minimize boards..

2024-09-20 07:13 UTC, robertlong13 commented
> this should not be included on minimize boards..

If we need to go this route to prevent this 96 byte change (for Plane on Pixhawk1-1M), then I'd recommend we go further and save 200 bytes over the current master by disabling `BATT#_OPTIONS` entirely on minimized boards. That would certainly be a lot clearer from a documentation standpoint, since compiling out one bit of an options parameter can really lead to confusion. It also makes it much easier to explain in `build_options.py`

I can make that a part of this PR if we want.

2024-09-20 12:01 UTC, Hwurzburg commented
> > this should not be included on minimize boards..
> 
> If we need to go this route to prevent this 96 byte change (for Plane on Pixhawk1-1M), then I'd recommend we go further and save 200 bytes over the current master by disabling `BATT#_OPTIONS` entirely on minimized boards. That would certainly be a lot clearer from a documentation standpoint, since compiling out one bit of an options parameter can really lead to confusion. It also makes it much easier to explain in `build_options.py`
> 
> I can make that a part of this PR if we want.

I agree, the options are not used in the minimized boards since its difficult( if not impossible )on some boards to use more than one monitor or a non-analog one(usually built-in) ....thats why everything except analog is omitted from minimize builds....we should make the SUM backend a build option while we are at it like the others are

2024-09-22 01:30 UTC, peterbarker commented
Wait - getting rid of `BATTn_OPTIONS` would get rid of value 64, use-resting-voltage.  That would be a very bad change IMO.

I suggest we accept this PR without fussing too much about the 100 bytes.

2024-09-23 10:26 UTC, IamPete1 reviewed
Basically looks good.

2024-09-23 10:26 UTC, IamPete1 commented on libraries/AP_BattMonitor/AP_BattMonitor_ESC.cpp
> +    // (we do this after calculating consumed Wh so this doesn't affect that calculation
```suggestion
    // (we do this after calculating consumed Wh so this doesn't affect that calculation)
```

2024-09-23 10:26 UTC, IamPete1 commented on libraries/AP_BattMonitor/AP_BattMonitor_Params.cpp
> +    // @Bitmask: 0:Ignore DroneCAN SoC, 1:MPPT reports input voltage and current, 2:MPPT Powered off when disarmed, 3:MPPT Powered on when armed, 4:MPPT Powered off at boot, 5:MPPT Powered on at boot
I wonder if it would be better to call out sum and ESC specifically.

2024-09-23 10:26 UTC, IamPete1 commented on libraries/AP_BattMonitor/AP_BattMonitor_Sum.cpp
>          voltage_sum += _mon.voltage(i);
Add the fetched voltage as a const float just to prevent getting it three times.

2024-09-24 00:58 UTC, tridge requested changes

2024-09-24 00:58 UTC, tridge commented on libraries/AP_BattMonitor/AP_BattMonitor_Sum.cpp
> +    // Check if we want to report the minimum voltage instead of the average
race condition for scripting or DDS, I think we need to create a local float state_voltage and then set that once

2024-10-01 00:05 UTC, robertlong13 commented
Closed in favor of #28227

2024-10-01 00:05 UTC, closed without merging