Tools:clean up displayed build options
ArduPilot/ardupilot pull request #28208
Opened 2024-09-23 23:15 UTC by Hwurzburg

NFC cleans up test in some options so everything is consistent when displayed (ie starts with a Cap)

2024-09-23 23:57 UTC, peterbarker approved these changes
LGTM

2024-09-24 08:56 UTC, amilcarlucas requested changes

2024-09-24 08:56 UTC, amilcarlucas commented on Tools/scripts/build_options.py
> +    Feature('MAVLink', 'REQUEST_AUTOPILOT_CAPA', 'AP_MAVLINK_MAV_CMD_REQUEST_AUTOPILOT_CAPABILITIES_ENABLED', 'Enable Old REQUEST_AUTOPILOT_CAPABILITIES comman'd, 0, None),  # noqa
```suggestion
    Feature('MAVLink', 'REQUEST_AUTOPILOT_CAPA', 'AP_MAVLINK_MAV_CMD_REQUEST_AUTOPILOT_CAPABILITIES_ENABLED', 'Enable Old REQUEST_AUTOPILOT_CAPABILITIES command', 0, None),  # noqa
```

2024-09-24 23:21 UTC, peterbarker approved these changes
LGTM

2024-09-24 23:21 UTC, peterbarker commented on Tools/scripts/build_options.py
> +    Feature('GPS Drivers', 'UBLOX', 'AP_GPS_UBLOX_ENABLED', 'Enable U-blox GPS', 1, None),
```suggestion
    Feature('GPS Drivers', 'UBLOX', 'AP_GPS_UBLOX_ENABLED', 'Enable ublox GPS', 1, None),
```


... looking at their branding, I think this is what they go with?!

2024-09-25 00:16 UTC, peterbarker commented
Fixed a long-line python formatting problem

2024-09-25 13:44 UTC, merged