Use NaN is camera fields when no value known
ArduPilot/ardupilot pull request #28212
Opened 2024-09-24 04:29 UTC by peterbarker

per-spec

Replaces https://github.com/ArduPilot/ardupilot/pull/25010/files

Creates a global `NaNf` per @rmackay9 's suggestion

2024-09-24 04:36 UTC, rmackay9 commented
Great to see the arrival of NANf!

2024-09-24 04:38 UTC, peterbarker commented
There's no compiler output change right up until the changes to the mavlink packets in this PR.  Using NanF in those packets costs 16 bytes on some platforms.

2024-09-24 04:59 UTC, peterbarker commented
I've used SITL to test the base backend, but no simulators for any of three more-specific backends

2024-09-24 08:52 UTC, amilcarlucas requested changes

2024-09-24 08:52 UTC, amilcarlucas commented on libraries/AP_Mount/AP_Mount_Topotek.cpp
> +        NaNf);               // focusLevel float, percentage from 0 to 100, NaN if unknown
```suggestion
        NaNf,               // zoomLevel float, percentage from 0 to 100, NaN if unknown
        NaNf);              // focusLevel float, percentage from 0 to 100, NaN if unknown
```

2024-09-24 08:52 UTC, amilcarlucas commented on libraries/AP_Mount/AP_Mount_Viewpro.cpp
> +        NaNf);               // focusLevel float, percentage from 0 to 100, NaN if unknown
```suggestion
        NaNf);              // focusLevel float, percentage from 0 to 100, NaN if unknown
```

2024-09-24 08:52 UTC, amilcarlucas commented on libraries/AP_Mount/AP_Mount_Xacti.cpp
> +        NaNf,                    // sensor_size_v float (mm)
```suggestion
        NaNf,                   // focal_length float (mm)
        NaNf,                   // sensor_size_h float (mm)
        NaNf,                   // sensor_size_v float (mm)
```

2024-09-24 08:52 UTC, amilcarlucas commented on libraries/AP_Mount/AP_Mount_Xacti.cpp
> +        NaNf);               // focusLevel float, percentage from 0 to 100, NaN if unknown
```suggestion
        NaNf);              // focusLevel float, percentage from 0 to 100, NaN if unknown
```

2024-09-24 08:52 UTC, amilcarlucas commented on libraries/AP_Camera/AP_Camera_Backend.cpp
> +        NaNf);               // focusLevel float, percentage from 0 to 100, NaN if unknown
```suggestion
        NaNf,               // zoomLevel float, percentage from 0 to 100, NaN if unknown
        NaNf);              // focusLevel float, percentage from 0 to 100, NaN if unknown
```

2024-09-24 08:52 UTC, amilcarlucas commented on libraries/AP_Camera/AP_Camera_Backend.cpp
> +        NaNf,              // available storage capacity (ms)
```suggestion
        NaNf,             // available storage capacity (ms)
```

2024-09-24 08:52 UTC, amilcarlucas commented on libraries/AP_Mount/AP_Mount_Siyi.cpp
> +        NaNf);               // focusLevel float, percentage from 0 to 100, NaN if unknown
```suggestion
        NaNf);              // focusLevel float, percentage from 0 to 100, NaN if unknown
```

2024-09-25 05:52 UTC, peterbarker commented on libraries/AP_Mount/AP_Mount_Viewpro.cpp
> +        NaNf);               // focusLevel float, percentage from 0 to 100, NaN if unknown
Fixed

2024-09-25 05:52 UTC, peterbarker commented on libraries/AP_Mount/AP_Mount_Xacti.cpp
> +        NaNf,                    // sensor_size_v float (mm)
Fixed

2024-09-25 05:53 UTC, peterbarker commented on libraries/AP_Mount/AP_Mount_Xacti.cpp
> +        NaNf);               // focusLevel float, percentage from 0 to 100, NaN if unknown
Fixed

2024-09-25 05:53 UTC, peterbarker commented on libraries/AP_Camera/AP_Camera_Backend.cpp
> +        NaNf);               // focusLevel float, percentage from 0 to 100, NaN if unknown
Fixed

2024-09-25 05:53 UTC, peterbarker commented on libraries/AP_Mount/AP_Mount_Siyi.cpp
> +        NaNf);               // focusLevel float, percentage from 0 to 100, NaN if unknown
Fixed

2024-09-25 05:53 UTC, peterbarker commented on libraries/AP_Camera/AP_Camera_Backend.cpp
> +        NaNf,              // available storage capacity (ms)
Fixed

2024-09-25 05:53 UTC, peterbarker commented on libraries/AP_Mount/AP_Mount_Topotek.cpp
> +        NaNf);               // focusLevel float, percentage from 0 to 100, NaN if unknown
Fixed

2024-09-26 00:28 UTC, rmackay9 approved these changes

2024-09-26 09:26 UTC, merged