Copter/Plane/Rover/Tracker: add PilotPi support
ArduPilot/ardupilot pull request #28247
Opened 2024-09-27 13:22 UTC by heeplr

Adds "pilotpi" board to support https://docs.px4.io/main/en/flight_controller/raspberry_pi_pilotpi.html

2024-09-28 00:09 UTC, rmackay9 commented
Hi @heeplr,

Thanks for the contribution!

I'm not really qualified to review the changes but I can see that the single commit will need to be broken up into multiple commits with each affecting just a single directory.  We've got some info on this in [the developer wiki here](https://ardupilot.org/dev/docs/submitting-patches-back-to-master.html).

2024-09-28 00:15 UTC, heeplr commented
> I'm not really qualified to review the changes but I can see that the single commit will need to be broken up into multiple commits with each affecting just a single directory.

I saw this but I supposed it's meant for adding multiple features to different libraries. With this PR every commit msg would be "add pilotpi support" or "enable xy for pilotpi". Should I still do it although it doesn't really ease review?

2024-09-28 00:20 UTC, rmackay9 commented
@heeplr,

It's fine for the commit messages to have similar titles but they should have a different prefix.  So I think there should be commits with at least these prefixes:

- "Tools: "
- "AP_BattMonitor: "
- AP_HAL_Linux: "

2024-09-28 07:03 UTC, heeplr commented
@rmackay9 thank you for clarifying. 

I ran ```git-subsystems-split``` and it worked like a charm.

2024-09-29 16:27 UTC, heeplr commented
Please consider reviewing `GPIO_PilotPi` thoroughly. I copied `GPIO_Navigator` and adapted it to comply with [the convention](https://ardupilot.org/rover/docs/parameters.html#relay1-pin-relay-pin) of AUX pins being >= 50 and MainOut pins being >= 101, but I don't really know what I'm doing ;)

2024-11-06 13:27 UTC, Hwurzburg commented
@tridge @rmackay9 who is our Linux board reviewer.....I am not capable

2025-04-14 13:47 UTC, heeplr commented
just pushed updated version with `hwdef.dat`

2025-04-17 03:45 UTC, rmackay9 commented
I've added this to the EU dev call so it will be reviewed next Wed

2025-04-23 06:43 UTC, peterbarker requested changes

2025-04-23 06:43 UTC, peterbarker commented on libraries/AP_HAL_Linux/RCOutput_Multi.cpp
> +#define MIN(a,b) ((a)<(b)?(a):(b))
Use the one from AP_Math.h; it doesn't have the re-eval bug this formulation has

2025-04-23 06:43 UTC, peterbarker commented on libraries/AP_HAL_Linux/RCOutput_Multi.cpp
> +        std::get<0>(out_groups[g]).init();
avoid use of the standard library

2025-04-23 06:43 UTC, peterbarker commented on libraries/AP_HAL_Linux/RCOutput_Multi.cpp
> +        {
```suggestion
        if(ch < group_ch_count) {
```

similarly elsewhere

2025-04-23 06:43 UTC, peterbarker commented on libraries/AP_HAL_Linux/RCOutput_Multi.cpp
> +for( unsigned g = 0; g < n_out_groups; ++g)
```suggestion
for (unsigned g = 0; g < n_out_groups; ++g)
```

2025-04-23 06:43 UTC, peterbarker commented on libraries/AP_HAL_Linux/RCOutput_Multi.cpp
> +bool RCOutput_Multi::resolve_channel(uint8_t ch, unsigned & gid, unsigned &cid)
tighten the type from unsigned to something from the standard integer set (eg `uint8_t`)

2025-04-23 06:43 UTC, peterbarker commented on libraries/AP_HAL_Linux/RCOutput_Multi.cpp
> +    for( unsigned g = 0; g < n_out_groups; ++g )
```suggestion
    for (unsigned g = 0; g < n_out_groups; ++g)
```

tighten the types up throughout the PR to use standard integer types.

fix similar whitespace errors

2025-04-23 06:43 UTC, peterbarker commented on libraries/AP_HAL_Linux/RCOutput_Multi.h
> +    const std::tuple<AP_HAL::RCOutput&,int> * out_groups;
remove use of standard library

2025-04-23 06:43 UTC, peterbarker commented on libraries/AP_HAL_Linux/HAL_Linux_Class.cpp
> +static RCInput_Multi rcinDriver{2, NEW_NOTHROW RCInput_RCProtocol("/dev/ttyAMA0", NULL), NEW_NOTHROW RCInput_UDP()};
Use AP_RCProtocol, do not use RCInput_Multi

2025-04-23 09:10 UTC, heeplr commented on libraries/AP_HAL_Linux/HAL_Linux_Class.cpp
> +static RCInput_Multi rcinDriver{2, NEW_NOTHROW RCInput_RCProtocol("/dev/ttyAMA0", NULL), NEW_NOTHROW RCInput_UDP()};
I don't quite get this change. I'm basically copying [how DISCO does it](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_HAL_Linux/HAL_Linux_Class.cpp#L163) (and others using RCInput_Multi).

You mean drop `RCInput_UDP` support entirely?

2025-04-24 13:55 UTC, heeplr commented on libraries/AP_HAL_Linux/RCOutput_Multi.cpp
> +#define MIN(a,b) ((a)<(b)?(a):(b))
done

2025-04-24 13:55 UTC, heeplr commented on libraries/AP_HAL_Linux/RCOutput_Multi.cpp
> +        std::get<0>(out_groups[g]).init();
done

2025-04-24 13:56 UTC, heeplr commented on libraries/AP_HAL_Linux/RCOutput_Multi.cpp
> +        {
I ran Tools/CodeStyle/ardupilot-astyle.sh on the newly created files -> done

2025-04-24 13:57 UTC, heeplr commented on libraries/AP_HAL_Linux/RCOutput_Multi.cpp
> +bool RCOutput_Multi::resolve_channel(uint8_t ch, unsigned & gid, unsigned &cid)
done

2025-04-24 13:57 UTC, heeplr commented on libraries/AP_HAL_Linux/RCOutput_Multi.cpp
> +    for( unsigned g = 0; g < n_out_groups; ++g )
done

2025-04-24 13:57 UTC, heeplr commented on libraries/AP_HAL_Linux/RCOutput_Multi.h
> +    const std::tuple<AP_HAL::RCOutput&,int> * out_groups;
done

2025-04-24 13:57 UTC, heeplr commented on libraries/AP_HAL_Linux/HAL_Linux_Class.cpp
> +static RCInput_Multi rcinDriver{2, NEW_NOTHROW RCInput_RCProtocol("/dev/ttyAMA0", NULL), NEW_NOTHROW RCInput_UDP()};
done

2025-04-24 13:59 UTC, heeplr commented
I also switched from `GPIO_RPI` to `GPIO_Sysfs` since it got the the new `attach_interrupt()` support.

2025-04-24 14:03 UTC, heeplr commented on libraries/AP_HAL_Linux/RCOutput_Multi.cpp
> +for( unsigned g = 0; g < n_out_groups; ++g)
done

2025-06-12 21:53 UTC, tridge commented on libraries/AP_HAL_Linux/RCOutput_Multi.h
> +#if CONFIG_HAL_BOARD_SUBTYPE == HAL_BOARD_SUBTYPE_LINUX_DISCO || \
why DISCO and BLUE?

2025-06-12 21:53 UTC, tridge commented on libraries/AP_HAL_Linux/RCOutput_Multi.cpp
> +#if CONFIG_HAL_BOARD_SUBTYPE == HAL_BOARD_SUBTYPE_LINUX_DISCO || \
why is this adding DISCO and BLUE?

2025-06-12 22:17 UTC, heeplr commented on libraries/AP_HAL_Linux/RCOutput_Multi.cpp
> +#if CONFIG_HAL_BOARD_SUBTYPE == HAL_BOARD_SUBTYPE_LINUX_DISCO || \
I copied this from [RCInput_Multi.cpp](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_HAL_Linux/RCInput_Multi.cpp#L21) and since it's the same concept I thought it must work on those platforms aswell and included them to maximize usability.

While those platforms would profit, I see that it doesn't fit the PR "add PilotPi support". I asked in discord if adding RCOutput_Multi.cpp should be a separate PR since it's a generic linux feature and not restricted to the PilotPi platform and (iirc) the consent was to just include it.

2025-06-12 22:18 UTC, tridge commented
@Williangalvani have you had a look?

2025-06-12 22:23 UTC, heeplr commented
> but you've marked the PR as unable to be updated by maintainers.

Strange, I'm 100% sure I didn't uncheck that when sending the PR. Maybe the force-push caused this?

> If you rebase it should disappear

I'm not sure if that worked... maybe if you could give a git command (that a five year old could understand), I can enable write access for you ;-)

2025-06-13 06:34 UTC, tridge commented
> Strange, I'm 100% sure I didn't uncheck that when sending the PR. Maybe the force-push caused this?

I just re-checked and now I can update! I've just rebased it now

2025-06-13 06:37 UTC, tridge commented on libraries/AP_HAL_Linux/RCOutput_Multi.cpp
> +#if CONFIG_HAL_BOARD_SUBTYPE == HAL_BOARD_SUBTYPE_LINUX_DISCO || \
ok, thanks for explaining
It is really up to @Williangalvani as linux HAL maintainer, I'm happy for it to go in as-is

2025-06-13 06:37 UTC, tridge approved these changes
i'm happy with this, but @Williangalvani should look too

2025-06-17 02:03 UTC, tridge commented
@peterbarker I've made the changes for HAL_LINUX_RCOUTPUT_MULTI_ENABLED as discussed

2025-06-17 19:40 UTC, merged

2025-07-09 23:37 UTC, rmackay9 commented
Hi @heeplr, i wonder if we could create an AP wiki page for this autopilot?  So far we're just [planning to link back to the other team's page](https://github.com/ArduPilot/ardupilot_wiki/pull/6972) but it would be nice to have our own.

2025-07-10 16:14 UTC, heeplr commented
> i wonder if we could create an AP wiki page for this autopilot? 

Yes, I'm planning to do so. I currently have another pilot running i'm working on and shelfed the PilotPi. But not forever - next time I pull it out, I'll add a wiki page. Might take some weeks, tho.

> So far we're just [planning to link back to the other team's page](https://github.com/ArduPilot/ardupilot_wiki/pull/6972) but it would be nice to have our own.

Might be a good idea in the meantime until I can come around to write a wiki page.

(I'd also like to propose, that a missing wiki page could be made a merge-blocker or at least some sort of warning in the CI for new hardware.def's? If I had thought about that earlier, I would have documented from the beginning. I simply missed it.)