New Vehicle Heron USV for Webots
ArduPilot/ardupilot pull request #28251
Opened 2024-09-27 22:36 UTC by harunkurtdev

![heron_ocean](https://github.com/user-attachments/assets/1d28de41-a981-4b26-a4ea-793b967a5faf)

By connecting heron usv to ardupilot on webots.
A new vehicle type has been added. This vehicle type is a marine vehicle and is well known in the market.

2024-09-27 23:45 UTC, rmackay9 commented
Hi @harunkurtdev,

Thanks for this.  I actually didn't realise that Webots was still usable.  Good news that it is.

One thing is it would be best if the commits were squashed together somewhat and also if you peek at our commit history you'll see we always prefix commits with the subsystem (or folder) affected.  This makes it easier for us to backport features.

2024-09-28 09:12 UTC, harunkurtdev commented
> Hi @harunkurtdev,
> 
> Thanks for this. I actually didn't realise that Webots was still usable. Good news that it is.
> 
> One thing is it would be best if the commits were squashed together somewhat and also if you peek at our commit history you'll see we always prefix commits with the subsystem (or folder) affected. This makes it easier for us to backport features.

So sir, what should I do? Can you recommend me a guideline?

I look this [contributing](https://github.com/ArduPilot/ardupilot/blob/637aec00853015eaaccab40217a6338164cffce1/.github/CONTRIBUTING.md)

2024-09-28 19:23 UTC, harunkurtdev commented
Mr. @rmackay9, it is working,  what should I do now? I did not add any file confusion that would prevent Ardupilot from working.

2024-09-29 22:32 UTC, peterbarker commented
> > Hi @harunkurtdev,
> > Thanks for this. I actually didn't realise that Webots was still usable. Good news that it is.
> > One thing is it would be best if the commits were squashed together somewhat and also if you peek at our commit history you'll see we always prefix commits with the subsystem (or folder) affected. This makes it easier for us to backport features.
> 
> So sir, what should I do? Can you recommend me a guideline?
> 
> I look this [contributing](https://github.com/ArduPilot/ardupilot/blob/637aec00853015eaaccab40217a6338164cffce1/.github/CONTRIBUTING.md)

The information you're after is here: https://ardupilot.org/dev/docs/git-interactive-rebase.html

2024-09-29 22:37 UTC, peterbarker requested changes

2024-09-29 22:37 UTC, peterbarker commented on libraries/SITL/SIM_Webots_Python.cpp
> +
Bad whitespace change

2024-09-29 22:37 UTC, peterbarker commented on libraries/SITL/SIM_Webots_Python.cpp
> +
Removed change?

2024-09-29 22:37 UTC, peterbarker commented on libraries/SITL/SIM_Webots_Python.cpp
> +bool WebotsPython::is_wsl(){
Unused?

2024-09-29 22:37 UTC, peterbarker commented on libraries/SITL/SIM_Webots_Python.h
> +
Bad whitespace change

2024-09-29 22:37 UTC, peterbarker commented on libraries/SITL/SIM_Webots_Python.h
> +    bool is_wsl();
Unused?

2024-09-29 22:37 UTC, peterbarker commented on libraries/SITL/examples/Webots_Python/controllers/ardupilot_vehicle_controller/webots_vehicle.py
> -
bad whitespace change?

2024-09-29 22:37 UTC, peterbarker commented on libraries/SITL/examples/Webots_Python/controllers/ardupilot_vehicle_controller/webots_vehicle.py
> +        print(f"Listening for ardupilot SITL (I{self._instance}) at {sitl_address}:{port}")
Didn't we just bind 0.0.0.0?

I mean, the existing comment is wrong, but this one is also wrong.

I mean, *less* wrong :-)

2024-09-29 22:37 UTC, peterbarker commented on libraries/SITL/examples/Webots_Python/controllers/ardupilot_vehicle_controller/webots_vehicle.py
> +
bad whitespace change

2024-09-29 22:37 UTC, peterbarker commented on libraries/SITL/examples/Webots_Python/controllers/ardupilot_vehicle_controller/webots_vehicle.py
> +            command_motors = [v if v != -1 else 0.0 for v in command_motors]
Add a comment as to why this is needed, please.

2024-09-29 22:37 UTC, peterbarker commented on libraries/SITL/examples/Webots_Python/params/heron.parm
> +#ARMING_CHECK	 1045534    # No RC requirements
Why remove RC here?  Simulation has it by default?

If this was copied from elsewhere that's fine.

2024-11-09 00:59 UTC, peterbarker commented
@harunkurtdev still waiting for some of my comments to be addressed

2024-11-10 21:28 UTC, harunkurtdev commented
> @harunkurtdev still waiting for some of my comments to be addressed

Mr. @peterbarker,

 I removed the parts you took into consideration and the unused parts.

Which part do I need to edit? Could you please state it again?

2024-11-12 21:32 UTC, peterbarker requested changes
Ping @harunkurtdev - there are many un-addressed review comments in here.

2024-11-13 07:20 UTC, closed without merging