SITL: FlightAxis Improvements
ArduPilot/ardupilot pull request #28282
Opened 2024-10-02 09:36 UTC by robertlong13

Adds a new options parameter for the FlightAxis SITL frame:
- Option to automatically reset the aircraft position in RealFlight!!
- Move the existing framestring-passed options to option bits (but keep the existing framestring parsing for now)
- Option to silence the FPS reporting printf

2024-10-02 12:11 UTC, amilcarlucas requested changes

2024-10-02 12:23 UTC, robertlong13 commented on libraries/SITL/SIM_FlightAxis.h
> +        SilenceFPS  = (1U<<3),
Yeah, accidentally messed that up after renaming. Fixed

2024-10-14 23:17 UTC, tridge requested changes
good to merge after these changes

2024-10-14 23:17 UTC, tridge commented on libraries/SITL/SITL.cpp
> +    AP_SUBGROUPPTR(flightaxis_ptr, "FTAX_", 5, SIM::ModelParm, FlightAxis),
maybe RFL_ ?

2024-10-14 23:17 UTC, tridge commented on libraries/SITL/SIM_FlightAxis.h
> +    AP_Int16 _options;
make it an AP_Int32

2024-10-15 01:52 UTC, timtuxworth commented
It makes sense to not call it FlightAxis - RealFlight stopped calling it that in (I think) Evolution.

2024-10-15 02:13 UTC, robertlong13 commented
> It makes sense to not call it FlightAxis - RealFlight stopped calling it that in (I think) Evolution.

Agreed. It's an unfortunate historical holdover that we should fix in a future PR. That said, the param name we should go ahead and set correctly now.

2024-10-15 22:35 UTC, tridge approved these changes

2024-10-25 07:14 UTC, merged

2024-11-24 14:22 UTC, robustini commented
@robertlong13 sorry to comment here that a merge has already been done, but since even before the 4.5.7 release I have been noticing problems with Flightaxis and Realflight.
Never seen this behavior before: moving RC4 with the joystick I also have a shift of about 100 uS up and down of CH8.
Obviously on the controller panel of Realflight this thing by moving that channel does not happen, so I think it is attributable to flight axis.

2024-11-24 22:30 UTC, robertlong13 commented
@robustini, it's extremely unlikely that this has anything to do with this PR, but I can probably help. We should take this conversation to Discord though.