AP_BLHeli:correct RVMASK metadata
ArduPilot/ardupilot pull request #28318
Opened 2024-10-05 20:53 UTC by Hwurzburg

NFC....obviously a typo...assume it should refer to the only other BLH mask types

2024-10-06 11:50 UTC, andyp1per requested changes
Actually the sentence should be removed. It's just 3DMASK this applies to

2024-10-06 12:04 UTC, Hwurzburg commented
@andyp1per done

2024-10-06 13:03 UTC, andyp1per approved these changes

2024-10-07 23:51 UTC, tridge approved these changes

2024-10-08 09:58 UTC, merged