AP_DDS: Make GPS DDS features depend on GPS
ArduPilot/ardupilot pull request #28341
Opened 2024-10-08 00:01 UTC by Ryanf55

# Purpose

Make the DDS features that depend on GPS rely on `AP_GPS_ENABLED`. 

# Details

Follow up to https://github.com/ArduPilot/ardupilot/pull/28177 where we hard-coded navsatfix enable flag to `1`. 
If you disabled GPS on `master` now and enabled DDS, you would get a compile error,

2024-11-19 05:27 UTC, peterbarker commented
... this one definitely needs to compile :-)

Not really sure what you're doing with that "NEEDS" variable, either...

2024-11-19 19:39 UTC, Ryanf55 commented
> ... this one definitely needs to compile :-)
> 
> Not really sure what you're doing with that "NEEDS" variable, either...

`NEEDS` are a convenience to only have a single define to decide whether a header is needed. 

Before:

```c++
#if AP_DDS_NAVSATFIX_PUB_ENABLED || AP_DDS_STATIC_TF_PUB_ENABLED // And potentially more!
#include <AP_GPS/AP_GPS.h>
#endif
```

After:
```c++
#if AP_DDS_NEEDS_GPS
#include <AP_GPS/AP_GPS.h>
#endif
```

2025-01-06 23:41 UTC, tridge approved these changes

2025-01-06 23:42 UTC, tridge commented on libraries/AP_DDS/AP_DDS_Client.cpp
> +#include <AP_GPS/AP_GPS_config.h>
not needed

2025-01-06 23:42 UTC, Ryanf55 commented on libraries/AP_DDS/AP_DDS_Client.cpp
> +#include <AP_GPS/AP_GPS_config.h>
```suggestion
```

2025-01-06 23:43 UTC, peterbarker requested changes

2025-01-06 23:43 UTC, peterbarker commented on libraries/AP_DDS/AP_DDS_Client.cpp
> +#include <AP_GPS/AP_GPS_config.h>
```suggestion
```

2025-05-14 09:37 UTC, peterbarker approved these changes

2025-05-14 21:55 UTC, merged