Implement TKOFF_THR_IDLE
ArduPilot/ardupilot pull request #28351
Opened 2024-10-08 19:12 UTC by Georacer

I thought I'd tackle https://github.com/ArduPilot/ardupilot/issues/20754.

A new parameter `TKOFF_THR_IDLE` has been added and a new option bit 1 to `TKOFF_OPTIONS` to enable it (off by default).

In TAKEOFF and AUTO modes, while in `FlightStage::TAKEOFF` and while the throttle is suppressed, `TKOFF_THR_IDLE` is output to the throttle.

Here's how it looks like in a catapult takeoff:
![image](https://github.com/user-attachments/assets/402b91f3-4cdc-40d3-8ec7-f350487681f4)

2024-10-09 08:14 UTC, tridge requested changes

2024-10-09 08:14 UTC, tridge commented on ArduPlane/Parameters.cpp
> +    // @Bitmask: 1: When set the throttle will run at TKOFF_THR_IDLE before takeoff.
don't need the option bit, just use when non-zero

2024-10-16 08:00 UTC, tridge requested changes

2024-10-16 08:00 UTC, tridge commented on ArduPlane/servos.cpp
> +                    && !(aparm.takeoff_throttle_idle == 0)
is_positive(aparm.takeoff_throttle_idle.get())

2024-10-17 00:18 UTC, Georacer commented
Closes #20754 .

2024-11-13 08:31 UTC, tridge approved these changes

2024-11-13 08:32 UTC, merged

2026-07-22 20:27 UTC, rtm7777 commented
I see this PR in 4.7.0 release notes, did you test it on a plane? I've tried to implement something similar and I had to change much more things and have no time to finish and properly test

2026-07-23 00:14 UTC, Georacer commented
It has been tested in simulation. I'm not aware of real-life testing.
We discovered last week that it works only on TAKEOFF mode, not on AUTO, and [the fix](https://github.com/ArduPilot/ardupilot/pull/33784) will likely make its way into 4.7.1.