Pr/hal program size limit kb
ArduPilot/ardupilot pull request #28362
Opened 2024-10-09 07:10 UTC by peterbarker

2025-02-24 22:16 UTC, peterbarker commented
```
Board                     blimp   bootloader  copter  heli    plane
  rover   sub
CubeRedPrimary            9512    *           9456    9448    9536
  9424    4648
DevEBoxH7v2               305172  *           364640  366864  339180
  338092  323368
RADIX2HD                  356272              436324  430956  399936
  402160  383004
SITL_arm_linux_gnueabihf  0                   0       0       0
  0       0
SITL_x86_64_linux_gnu     0                   0       0       0
  0       0
SPRacingH7                326888  *           402692  397348  365184
  368848  348644
SPRacingH7RF              16      *           16      16      16
  16      16
YJUAV_A6SE                368400  *           447876  442348  412296
  412672  394740
```

CubeRedPrimary still boots in the same way that it does on master - poorly.

Since we can now actually use external flash, PROGRAM_SIZE_LIMIT >2048 and we now compile a few more things in by default (~10kB):

Master:
```
Target         Text (B)  Data (B)  BSS (B)  Total Flash Used (B)  Free Flash (B)  External Flash Used (B)
bin/arduplane   1649036      4116   258168               1558652          145280                    94500

```
This:
```
Target         Text (B)  Data (B)  BSS (B)  Total Flash Used (B)  Free Flash (B)  External Flash Used (B)
bin/arduplane   1658616      4116   258172               1568224          135704                    94508
```

2025-02-24 23:57 UTC, tridge requested changes

2025-02-24 23:57 UTC, tridge commented on libraries/Filter/AP_Filter_config.h
> +#define AP_FILTER_NUM_FILTERS 0
this breaks https://github.com/ArduPilot/ardupilot/pull/28787

2025-02-25 00:03 UTC, tridge approved these changes

2025-02-25 02:18 UTC, peterbarker commented on libraries/Filter/AP_Filter_config.h
> +#define AP_FILTER_NUM_FILTERS 0
Fixed

2025-02-25 23:06 UTC, merged