AP_InertialSensor: added IIM42653
ArduPilot/ardupilot pull request #28383
Opened 2024-10-11 21:05 UTC by dakejahl

Tested on the ARKV6X rev5.

This part is functionally equivalent to the iim42652 but with higher full scale range of 32g and 4000dps.

2024-11-08 01:29 UTC, peterbarker requested changes

2024-11-08 01:29 UTC, peterbarker commented on libraries/AP_InertialSensor/AP_InertialSensor_Backend.h
> +        DEVTYPE_INS_IIM42653 = 0x38,
I don't think we can renumber these - they're logged and tools like `decode_devid.py` would insta-break.

2024-11-09 01:19 UTC, peterbarker requested changes, later dismissed
OK, looks right now.

Will mark for DevCall, but:
 - please add to the `decode_devid.py` metadata
 - we should only have two commits, one in AP_InertialSensor and one in Tools (for `decode_devid.py`)
 -

2024-11-10 10:30 UTC, IamPete1 commented
> * please add to the `decode_devid.py` metadata

Also https://github.com/ArduPilot/WebTools/blob/main/Libraries/DecodeDevID.js please.

2024-11-10 21:39 UTC, dakejahl commented
Also https://github.com/mavlink/qgroundcontrol/blob/master/src/FirmwarePlugin/APM/APMSensorIdDecoder.qml

2024-11-12 01:08 UTC, tridge approved these changes

2024-11-12 17:15 UTC, andyp1per approved these changes

2024-11-12 19:39 UTC, merged

2024-11-12 19:39 UTC, peterbarker commented
Merged, thanks!