Plane: fixed guided VTOL command in terrain mode
ArduPilot/ardupilot pull request #28406
Opened 2024-10-15 08:19 UTC by tridge

if the GCS commands a guided re-position with an AGL frame and quadplane is in Q_GUIDED_MODE=1 then this prevents us adding the home altitude to the target terrain altitude

2024-10-16 09:02 UTC, peterbarker commented
> What we really need to do is change to using an alt_frame attribute on Location instead of using these booleans.

Yes, we do, I've had patches around it before.

There some subtleties around the terrain stuff in particularly - there's some weird persistence with terrain following which you have to be really careful around.

Nothing impossible, of course, but terrain is unforgiving :-)

The trick is to make `.alt` private in Location and fix what breaks.

2024-10-19 16:13 UTC, Ryanf55 commented
> > What we really need to do is change to using an alt_frame attribute on Location instead of using these booleans.
> 
> Yes, we do, I've had patches around it before.
> 
> There some subtleties around the terrain stuff in particularly - there's some weird persistence with terrain following which you have to be really careful around.
> 
> Nothing impossible, of course, but terrain is unforgiving :-)
> 
> The trick is to make `.alt` private in Location and fix what breaks.

@timtuxworth  Wanna figure this out at dev conference this week?

2024-10-19 16:28 UTC, timtuxworth commented
Absolutely

2024-11-06 07:26 UTC, peterbarker requested changes
Needs autotests

2025-03-13 04:12 UTC, tridge commented
> Needs autotests

test added

2025-03-17 23:48 UTC, peterbarker approved these changes
LGTM

2025-03-17 23:48 UTC, merged

2025-03-31 11:20 UTC, rmackay9 commented
I was unable to immediately include this in 4.6.0-beta5 due to merge conflicts

2025-04-01 05:47 UTC, rmackay9 commented
this is included in 4.6.0-beta5 via PR https://github.com/rmackay9/rmackay9-ardupilot/pull/40