ExternalAHRS: support variances in backends
ArduPilot/ardupilot pull request #28405
Opened 2024-10-15 03:25 UTC by tridge

simplifies backends, allows GCS to see variances in EKF message, and allows for copter EKF failsafe to work

2024-10-16 08:50 UTC, bugobliterator approved these changes

2024-10-17 11:16 UTC, Georacer requested changes
Left some comments.

Has there been any kind of testing?

2024-10-18 13:53 UTC, amilcarlucas commented
```
Binary Name      Text [B]         Data [B]     BSS (B)      Total Flash Change [B] (%)      Flash Free After PR (B)
---------------  ---------------  -----------  -----------  ----------------------------  -------------------------
arducopter-heli  -136 (-0.0075%)  0 (0.0000%)  0 (0.0000%)  -136 (-0.0075%)                                  142992
antennatracker   -136 (-0.0101%)  0 (0.0000%)  0 (0.0000%)  -136 (-0.0101%)                                  615516
arducopter       -136 (-0.0075%)  0 (0.0000%)  0 (0.0000%)  -136 (-0.0075%)                                  142464
ardurover        -136 (-0.0082%)  0 (0.0000%)  0 (0.0000%)  -136 (-0.0081%)                                  296648
arduplane        -136 (-0.0075%)  0 (0.0000%)  0 (0.0000%)  -136 (-0.0075%)                                  145904
blimp            -136 (-0.0099%)  0 (0.0000%)  0 (0.0000%)  -136 (-0.0099%)                                  593488
ardusub          -136 (-0.0084%)  0 (0.0000%)  0 (0.0000%)  -136 (-0.0084%)                                  352356
```

2024-10-19 23:02 UTC, tridge commented on libraries/AP_ExternalAHRS/AP_ExternalAHRS.cpp
> +                                       mag_var, 0, 0);
AP_AHRS::get_variances() maps to EKF2 and EKF3 getVariances() which returns innovation consistency test ratios, so they are actually scaled by the gates. The name isn't great, it isn't really a variance, but it is what the existing API calls it

2024-10-19 23:03 UTC, tridge commented on libraries/AP_ExternalAHRS/AP_ExternalAHRS_InertialLabs.cpp
> +    hgtVar = state2.kf_pos_covariance.z;
> Are you not filling in `magVar` on purpose?

right, it defaults to zero

2024-10-19 23:39 UTC, tridge commented on libraries/AP_ExternalAHRS/AP_ExternalAHRS_InertialLabs.cpp
> +    velVar = state2.kf_vel_covariance.length();
fixed, thanks!

2024-10-19 23:44 UTC, tridge commented
@Georacer I had stuffed up the scaling! Fixed up now

2024-10-22 21:46 UTC, merged