Scripting example to provide altitude callouts in feet defaulting to 400ft warnings
ArduPilot/ardupilot pull request #28426
Opened 2024-10-17 19:32 UTC by timtuxworth

Replaces #23368 

After @IamPete1 challenged me on this one, I rebased and then had to clean up/improve the example to reflect the code I'm flying now which has changed a bit since the original PR.

Hope it's still ok to merge Pete

2024-10-17 19:37 UTC, timtuxworth commented
I messed up GitHub somehow @peterbarker so I've created this new PR for the altitude callouts, I also renamed the script and updated it based on the one I'm actually flying.

2024-11-08 01:09 UTC, peterbarker requested changes
scripting linter detected a problem which needs fixing

2024-11-10 04:48 UTC, timtuxworth commented
> scripting linter detected a problem which needs fixing

Looks like it's fixed now @peterbarker

2024-11-23 20:17 UTC, merged

2024-11-23 20:17 UTC, peterbarker commented
Merged it - thanks!