AP_HAL_ChibiOS: add hwdef MFE_POS3_CAN
ArduPilot/ardupilot pull request #28515
Opened 2024-11-02 07:28 UTC by mikefenghao

This is the hwdef file for MFE_POS3_CAN. We've done a lot of testing and it's working fine.

2024-11-08 13:34 UTC, Hwurzburg requested changes

2024-11-08 13:34 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/MFE_POS3_CAN/hwdef.dat
> +APJ_BOARD_ID 6101
use logical id

2024-11-09 01:47 UTC, peterbarker submitted a review, later dismissed
Grab 10 IDs in board_types.txt while you're there - you can see how others are doing that in there.

2024-11-09 01:47 UTC, peterbarker commented on libraries/AP_HAL_ChibiOS/hwdef/MFE_POS3_CAN/hwdef.dat
> +APJ_BOARD_ID 6101
You need to reserve this board ID in `Tools/AP_Bootloader/board_types.txt` and then use the name you use in that file in here.

2024-11-18 21:56 UTC, tridge commented on libraries/AP_HAL_ChibiOS/hwdef/MFE_POS3_CAN/hwdef.dat
> +APJ_BOARD_ID 6101
fixed

2024-11-18 21:58 UTC, tridge approved these changes

2024-11-19 01:25 UTC, merged