Plane/Copter/Rover/Tracker: 4.6.0-beta1 release
ArduPilot/ardupilot pull request #28536
Opened 2024-11-06 04:23 UTC by rmackay9

This is the Copter, Rover, Tracker, Plane 4.6.0-beta1 release

To create the release notes I did this:

1. used Github to compile a full list of PRs in the ArduPilot-4.6 branch vs the Copter-4.5 branch.   The output from that can be found in [this spreadsheet](https://www.dropbox.com/scl/fi/yawmb18q7gwjpnses7shl/ardupilot-460-beta1.ods?rlkey=yq9ys5bldd8ona3shzyxx1t40&dl=0)
2. sorted the PRs by subsystem
3. manually reviewed each PR's title (and sometimes the content) in order to come up with a description of the change

Any and all feedback is greatly appreciated.  In particular I'd like to hear about:

a. changes that should be added or removed from the ReleaseNotes
b. corrections to change descriptions.  If possible please provide a copy-paste-able rewording
c. suggestions on re-ordering or moving changes within the ReleaseNotes

I haven't included Blimp or Sub but we could if maintainers of those vehicles would like (FYI @MichelleRos, @Williangalvani)

2024-11-06 04:38 UTC, Ryanf55 reviewed
Nice to see these put together!

2024-11-06 04:38 UTC, Ryanf55 commented on ArduCopter/ReleaseNotes.txt
> +- Support sending waypoints to Copter and Rover
```suggestion
- Support sending waypoints to Copter and Rover
- Remove the XML refs file in favor of binary entity creation
```

From 296cdc58a3b43e8cbe199d6feef42bc583073702. This is an important breaking change.

2024-11-06 05:30 UTC, tpwrules approved these changes
Thanks so much, great to see the list so big!

Added some wording nits for some stuff I've worked on.

2024-11-06 05:30 UTC, tpwrules commented on AntennaTracker/ReleaseNotes.txt
> +- uint64 support
```suggestion
- uint64 support
- Various performance and memory usage optimizations
```

2024-11-06 05:30 UTC, tpwrules commented on AntennaTracker/ReleaseNotes.txt
> +- REPL applet (read-evaluate-print-loop, see repl.lua)
```suggestion
- REPL applet (read-evaluate-print-loop, see repl.lua) for interactive testing and experimentation
```

2024-11-06 05:30 UTC, tpwrules commented on AntennaTracker/ReleaseNotes.txt
> +- "require" keyword works for modules in ROMFS (e.g. not on SD card)
```suggestion
- "require" function failures in rare circumstances fixed
- "require" function works for modules in ROMFS (e.g. not on SD card)
```

2024-11-06 05:30 UTC, tpwrules commented on AntennaTracker/ReleaseNotes.txt
> +- DroneCAN and scripting support FlexDebug messages (see CAN_OPTION, FlexDebug.lua)
```suggestion
- DroneCAN and scripting support FlexDebug messages (see CAN_Dn_UC_OPTION, FlexDebug.lua)
```

2024-11-06 05:30 UTC, tpwrules commented on AntennaTracker/ReleaseNotes.txt
> +- DroneCAN DNA server fixes including removing use of invalid node IDs, optimise id allocation
```suggestion
- DroneCAN DNA server fixes including removing use of invalid node IDs, faster ID allocation, elimination of rare inability to save info
```

2024-11-06 05:30 UTC, tpwrules commented on AntennaTracker/ReleaseNotes.txt
> +- Serial device loop back support (allows simulating a sensor using Lua)
```suggestion
- Serial device simulation support (allows Lua to feed data to any supported serial protocol for e.g. sensor simulation)
```

2024-11-07 11:25 UTC, bnsgeyer submitted a review, later dismissed
I only have one change.
otherwise it looks good to me.

2024-11-11 01:52 UTC, lthall approved these changes

2024-11-11 02:13 UTC, Hwurzburg approved these changes

2024-11-11 03:11 UTC, robertlong13 approved these changes

2024-11-12 17:24 UTC, andyp1per approved these changes

2024-11-12 20:40 UTC, tridge requested changes
really well done on the release notes, just found some minor issues

2024-11-12 20:40 UTC, tridge commented on ArduPlane/ReleaseNotes.txt
> +- DroneCAN ESCs and servos forced to zero when disarmed
only ESCs, servos work when disarmed

2024-11-12 20:40 UTC, tridge commented on ArduPlane/ReleaseNotes.txt
> +- DroneCAN fix for deadlock and saturation of CAN bus
this is in 4.5.7

2024-11-13 02:50 UTC, rmackay9 commented on ArduPlane/ReleaseNotes.txt
> +- DroneCAN ESCs and servos forced to zero when disarmed
txs, fixed

2024-11-13 02:51 UTC, rmackay9 commented on ArduPlane/ReleaseNotes.txt
> +- DroneCAN fix for deadlock and saturation of CAN bus
fixeed

2024-11-13 02:51 UTC, rmackay9 commented on ArduPlane/ReleaseNotes.txt
> +- NanoRadar MR72 CAN radar support
txs, removed

2024-11-13 02:52 UTC, rmackay9 commented on ArduPlane/ReleaseNotes.txt
> +- Allow multiple UDP clients to connect/disconnect/reconnect
ok, removed

2024-11-13 02:53 UTC, rmackay9 commented on ArduPlane/ReleaseNotes.txt
> +- Harmonic notch supports per-motor throttle-based harmonic notch
ok, I've added a new line, "- Harmonic notch is active in forward flight on quadplanes"

2024-11-13 02:53 UTC, rmackay9 commented on ArduPlane/ReleaseNotes.txt
> +- Throttle passthrough support while in VTOL modes removed
ok, removed

2024-11-13 03:03 UTC, rmackay9 commented on ArduPlane/ReleaseNotes.txt
> +- ESC telemetry works even when less than 4 ESCs
txs removed

2024-11-13 22:02 UTC, merged