HWDEF: add BETAFPV_F4_2-3S_20A
ArduPilot/ardupilot pull request #28635
Opened 2024-11-15 17:58 UTC by jonasniesner

Add all files for this board. The bootloader id has already reserved previously.
Since this is my first major commit to this repo, i open this PR as a draft and am waiting for feedback. If this PR is ready to be merged, i will do additional test with the hardware and all required changes and st it ready to be merged after those tests.

2024-11-15 18:59 UTC, jonasniesner commented
Looks like a build failed. It built fine locally for me. Is there a way to get logs to see why it failed?

2024-11-22 17:20 UTC, jonasniesner commented
Is there any additional action required from my side at the moment?

2024-11-22 17:50 UTC, Hwurzburg commented
you need to create the bootloader and add to Tools/bootloaders....

I would create a PR to reserve your board id...it can be merged quickly...see https://github.com/ArduPilot/ardupilot/pull/28628 as an example....then use the AP_HW_BETAFPV_F4_2-3S as the board name instead of number in hwdef and hwdef_bl

once this is done, you should be able to build and test, and  I will review the PR...thanks

2024-11-22 17:59 UTC, jonasniesner commented
I already opened #28333 and it was already merged. Did i make an error there?

2024-11-22 18:13 UTC, jonasniesner commented
I did not add the bootloader because the [wiki](https://ardupilot.org/dev/docs/porting.html) states that i shoud only add the files I added to this pr. Or is the wiki outdated and I should add the bootloader I built?

2024-11-22 18:35 UTC, andyp1per commented
You should add the bootloader

2024-11-22 19:38 UTC, Hwurzburg commented
yeah the wiki on porting needed a bit more explanation and details....I've done that...

2024-11-24 16:32 UTC, jonasniesner commented
I added the bootloader and all checks pass now :)

2024-12-02 16:16 UTC, Hwurzburg commented
@jonasniesner need pinout diagram/bd images in order for me to review for documentation acceptability

2024-12-02 16:24 UTC, jonasniesner commented
I have board images that also show part of the pinout. Should I add those to the readme?

2024-12-02 17:40 UTC, Hwurzburg commented
yes, with enough detail to identify all pins...like this https://github.com/ArduPilot/ardupilot/tree/master/libraries/AP_HAL_ChibiOS/hwdef/AET-H743-Basic

2025-01-29 17:23 UTC, Hwurzburg commented
Closing this since its already covered under the BETAFPVF405 hwdef which has recently been updated by @andyp1per ...

2025-06-19 12:37 UTC, jonasniesner commented
To be honest, I disagree with this being covered in BETAFPV-F405-I2C. The board has broken out i2c pins and there is no need to remove functionality to get I2C. Can this PR be opened again or can we merge the relevalt pins (PB8 I2C1_SCL I2C1  PB9 I2C1_SDA I2C1 ) into the BETAFPV-F405 hwdev?

2025-06-19 12:43 UTC, jonasniesner commented
![PXL_20250619_124016357](https://github.com/user-attachments/assets/68bac1fd-a927-4bfa-8328-663c2c9c0362)

That would be an Image of the pins labeled on the board

2025-06-22 08:04 UTC, andyp1per commented
Re-opened

2025-07-03 15:42 UTC, Hwurzburg commented
if it only differs by the I2C pins or sensors, you should just modify the F405 hwdef and include them, even though they are not pinned out on the base F405

2025-07-03 15:48 UTC, jonasniesner commented
Everything else on the board works with the f405 hwdef. So that is probably the best Idea to reuse that one. Should I open a new PR for that or reuse this one?

2025-07-03 16:18 UTC, Hwurzburg commented
a new one should be easy to review and will get rid of all the stale history

2025-07-10 13:45 UTC, Hwurzburg commented
-I started relooking at this...this board  is the betafpv f4 2s-3s **AIO** V1 and should be named as such
- the betafpv-f405 hwdef could be modified by adding:
- # I2C1
PB8 I2C1_SCL I2C1 
PB9 I2C1_SDA I2C1 
#define HAL_USE_I2C TRUE
#define STM32_I2C_USE_I2C1 TRUE
# I2C Buses
I2C_ORDER I2C1 
#define HAL_I2C_CLEAR_ON_TIMEOUT 0

2025-07-10 13:47 UTC, Hwurzburg requested changes
-I started relooking at this...this board is the betafpv f4 2s-3s AIO V1 and should be named as such

-this PR could be clossed and the betafpv-f405 hwdef could be modified by adding:

PB8 I2C1_SCL I2C1
PB9 I2C1_SDA I2C1


I2C_ORDER I2C1

2025-07-11 13:49 UTC, andyp1per requested changes
Few things need fixed

2025-07-11 13:49 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/BETAFPV_F4_2-3S_20A/hwdef-bl.dat
> +APJ_BOARD_ID 1175
Needs its own non-numeric ID

2025-07-11 13:49 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/BETAFPV_F4_2-3S_20A/hwdef.dat
> +APJ_BOARD_ID 1175
Ditto

2025-07-11 13:49 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/BETAFPV_F4_2-3S_20A/hwdef.dat
> +SPIDEV dataflash SPI2 DEVID1 FLASH1_CS     MODE3 104*MHZ 104*MHZ
This should be lower for F4. Probably 32MHz

2025-07-11 13:49 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/BETAFPV_F4_2-3S_20A/hwdef.dat
> +define HAL_BARO_ALLOW_INIT_NO_BARO 1
It has a baro, so remove this

2026-07-17 02:40 UTC, peterbarker commented
Ping @jonasniesner - still chasing this?

2026-08-15 11:57 UTC, Hwurzburg commented
@jonasniesner closing due to lack of activity/response

2026-08-15 11:57 UTC, closed without merging