Replace fabsF macro with std::abs call to avoid having float / double mismatch warnings
ArduPilot/ardupilot pull request #28642
Opened 2024-11-15 21:53 UTC by katzfey

The fabsF macro is defined as either the float version or double version in ftype.h depending on HAL_WITH_EKF_DOUBLE. If it is defined as the float version and a double is used as the argument then we get a compiler warning in the Qurt build. If those are replaced with std:abs calls then that clears up the warnings since it is overloaded for both floats and doubles.

2024-12-16 16:22 UTC, katzfey commented
Perhaps fabsF should be removed everywhere and replaced by std::abs?

2024-12-16 23:26 UTC, tridge requested changes

2024-12-16 23:26 UTC, tridge commented on ArduCopter/mode_guided.cpp
> +        pos_offset_z_buffer = MIN(copter.wp_nav->get_terrain_margin() * 100.0, 0.5 * std::abs(guided_pos_target_cm.z));
if the variable is a float, will it promote to double by making this change? That would slow things a lot on older boards

2024-12-16 23:27 UTC, tridge commented
cppreference shows only integer versions?
![image](https://github.com/user-attachments/assets/b519e431-b131-43a1-921f-8a71a7ad82b8)

2024-12-16 23:29 UTC, tridge commented
we could add a float cast to the float version of fabsF()
also note that we generally trying to avoid the std library, it often causes more pain than it fixes

2024-12-17 01:38 UTC, katzfey commented
The float versions are here: https://en.cppreference.com/w/cpp/numeric/math/fabs

2024-12-17 01:38 UTC, katzfey commented
But if you want to avoid using std library then let me try with the float cast

2024-12-17 17:09 UTC, katzfey commented
Closing this PR. Going with https://github.com/ArduPilot/ardupilot/pull/28897 instead with the cast method instead of the switch to std::abs proposed in this PR.

2024-12-17 17:09 UTC, closed without merging