AP_InertialSensor: fixed Q calculation for notch filters
ArduPilot/ardupilot pull request #28765
Opened 2024-11-28 05:44 UTC by tridge

when doing the init() we must use the reference frequency, not the current frequency. Using the current frequency leaves us with an incorrect value for Q. If the current frequency is below the reference frequency (which shouldn't happen in 4.5, but has been seen in 4.3) then the Q can be much too low and massive phase lag can happen.

The vulnerability in 4.5.x is that the current frequency could be well above the reference frequency. For example, the user may be doing a motor test at 30s after boot, which is when we stop the sensors_converging() test, and thus is the last time we call init(). In that case we can end up with a Q which is much larger than the one that should come from INS_HNTCH_FREQ and INS_HNTCH_BW, and thus end up with a filter that produces a lot less attenuation than is desired, potentially leading to instability due to high noise.

There are other scenarios that can cause this - for example a motor test of a fwd motor at 30s after boot, or a spurious FFT peak due to someone knocking the aircraft, or the vibration of a IC engine.

I am still investigating if this issue can impact 4.6.x

2024-11-28 07:51 UTC, andyp1per approved these changes
Nice catch!

2024-11-28 10:41 UTC, andyp1per commented
Still an issue - needs to pass CI

2024-11-28 11:31 UTC, andyp1per commented
If we put this in 4.5 it needs a very visible release note. We also should check that the attenuation problem does not exist in 4.6

2024-11-28 11:38 UTC, andyp1per commented
Hmmn, although my fix demonstrably fixes the issue, its not clear why the update after is not working. Maybe something to do with it being a notch per-motor.

2024-11-29 02:36 UTC, tridge commented
@andyp1per I've added an alternative fix that stops the converging logic if the motors are armed

2024-11-29 16:47 UTC, andyp1per requested changes
I verified that the noise looks correct, but the check for changes is still wrong

2024-11-29 20:24 UTC, tridge commented on libraries/AP_InertialSensor/AP_InertialSensor.cpp
>          last_center_freq_hz[instance] = center_freq;
ahh, yes, fixed now, and also removed the check for Fixed notch in the init

2024-11-29 21:14 UTC, andyp1per approved these changes
I have confirmed the filter is working in the test when it needs to

2024-12-02 05:27 UTC, tridge commented
using an additional dummy I have confirmed that the CI failure is not due to this PR
see https://github.com/ArduPilot/ardupilot/pull/28773

2024-12-03 00:07 UTC, merged