save some log structure flash when features disabled
ArduPilot/ardupilot pull request #28788
Opened 2024-12-01 04:51 UTC by tridge

this continues some work that @peterbarker has started. I ran across one of these while working on a different PR

2024-12-01 07:28 UTC, peterbarker requested changes
```
../../libraries/AC_Avoidance/AC_Avoidance_Logging.cpp: In member function 'void AP_OABendyRuler::Write_OABendyRuler(uint8_t, bool, float, float, bool, float, const Location&, const Location&) const':
../../libraries/AC_Avoidance/AC_Avoidance_Logging.cpp:23:46: error: 'ahrs' is not a member of 'AP'
   23 |         yaw         : (uint16_t)wrap_360(AP::ahrs().yaw_sensor * 0.01f),
      |                                              ^~~~
```


... that was the first error which popped up; consider using `./Tools/autotest/test_build_options.py` with `--define-match-glob` to see if it picks up the others.

2024-12-01 07:56 UTC, tridge commented
> ... that was the first error which popped up; consider using `./Tools/autotest/test_build_options.py` with `--define-match-glob` to see if it picks up the others.

ok, thanks. Started a run with "--define-match-glob=AP*" - does that sound right?

2024-12-01 19:59 UTC, tridge commented
> ../../libraries/AC_Avoidance/AC_Avoidance_Logging.cpp: In member function 'void AP_OABendyRuler::Write_OABendyRuler(uint8_t, bool, float, float, bool, float, const Location&, const Location&) const':
> ../../libraries/AC_Avoidance/AC_Avoidance_Logging.cpp:23:46: error: 'ahrs' is not a member of 'AP'
>    23 |         yaw         : (uint16_t)wrap_360(AP::ahrs().yaw_sensor * 0.01f),
>       |                                              ^~~~

that error also happens with master, it doesn't have anything to do with this PR
ie. this configure: 
```
./waf configure --disable-AC_AVOID --disable-MODE_FOLLOW
```
produces: 
```
../../libraries/AC_Avoidance/AC_Avoidance_Logging.cpp: In member function ‘void AP_OABendyRuler::Write_OABendyRuler(uint
8_t, bool, float, float, bool, float, const Location&, const Location&) const’:
../../libraries/AC_Avoidance/AC_Avoidance_Logging.cpp:23:46: error: ‘ahrs’ is not a member of ‘AP’
   23 |         yaw         : (uint16_t)wrap_360(AP::ahrs().yaw_sensor * 0.01f),
      |                                              ^~~~
```

2024-12-17 00:40 UTC, peterbarker commented
> > ... that was the first error which popped up; consider using `./Tools/autotest/test_build_options.py` with `--define-match-glob` to see if it picks up the others.
> 
> ok, thanks. Started a run with "--define-match-glob=AP*" - does that sound right?

Nope, `--define-match-glob=AP_AVOIDANCE_ENABLED` as that's the define in play in this PR

2025-01-14 00:46 UTC, merged