Add scripts for Fedora systems
ArduPilot/ardupilot pull request #28791
Opened 2024-12-01 18:47 UTC by radityankn

This script is basically the modification from OpenSUSE Tumbleweed environment install script. The only changes was about the python package names with awk and some renaming to match fedora packages. Tested and the resulting environment is able to compile ArduCopter for Pixhawk1 (STM32) and ESP32S3 Devkit without error. The resulting binaries have not been tested yet

2024-12-02 00:35 UTC, Ryanf55 commented
Always nice to see more of these! Do you mind amending your commit title to prefix it with "Tools: "

2024-12-02 09:12 UTC, radityankn commented
> Always nice to see more of these! Do you mind amending your commit title to prefix it with "Tools: "

No problem, I will add it

2024-12-02 22:54 UTC, Ryanf55 commented
By commit, I mean here:
<img width="607" alt="image" src="https://github.com/user-attachments/assets/d04cc67e-2a8e-4052-b084-1d58fe8cd7f2">


In CLI:
`git commit --amend`

change your commit title

Then, 

`git push -f`

2024-12-03 01:08 UTC, radityankn commented
sorry, accidentally deleted the branch while cleaning up my repo

2024-12-03 01:16 UTC, Ryanf55 commented
No worries. Looks like you also added a merge commit. ArduPilot uses a rebase workflow. I'll drop that off your branch and force push. Looks fine otherwise!

2024-12-03 03:29 UTC, Ryanf55 commented
Alrighty, all cleaned up. Approved! I requested final review from a maintainer.

If you have time, mind trying to add a job in CI to enforce this script can continue to work as you intended as a follow up PR?
We have run through many of the setup scripts in this workflow. 
It can be amended to support fedora.
https://github.com/ArduPilot/ardupilot/blob/master/.github/workflows/test_environment.yml

2024-12-03 03:30 UTC, Ryanf55 approved these changes

2024-12-03 03:46 UTC, Ryanf55 commented
Eh, maybe not, I don't think we can run these setup scripts tests on fedora in CI:
https://github.com/actions/runner-images/issues/10802

Maybe you know a way?

2024-12-03 13:01 UTC, radityankn commented
I'd like to help, but I don't think I have time to do the CI part. Still new to github, still have to learn more about the testing and CI part

anyway, thank you for reviewing the pr

2024-12-14 23:59 UTC, peterbarker commented
I'm a bit concerned by the fact that this is just the fedora install script which has been copied sideways and modified.

By contrast, our `install-prereqs-ubuntu.sh` script handles Ubuntu, debian and `Mint`.

Copying-sideways-and-modifying increases maintenance load on the project, so I would strongly prefer a modification (and perhaps rename) of the existing script to be able to handle both.  

Something like
```
REMOVE_PACKAGE="sudo dnf remove"  # OpenSUSE
if $IS_FEDORA; then
    REMOVE_PACKAGE="sudo zypper rm"
fi
```

would make it all reasonable clean, I think.

2024-12-22 19:01 UTC, radityankn commented
@peterbarker sorry for the late reply. So from your suggestion, it's better to merge the OpenSUSE and Fedora scripts into a single env install file to make maintenance easier, correct?

2024-12-22 19:02 UTC, radityankn commented
it can be done with some if statements though, to handle differences in package names and others

2025-04-30 05:16 UTC, peterbarker commented
> @peterbarker sorry for the late reply. So from your suggestion, it's better to merge the OpenSUSE and Fedora scripts into a single env install file to make maintenance easier, correct?

That's correct.

2025-04-30 05:18 UTC, peterbarker requested changes
Please rejig as a modification to the opensuse script.

I wouldn't mind if you started by `git mv` to a different filename first which is collective of both Fedora and OpenSUSE.  I'll note that our Ubuntu install script also handles base Debian and Mint, 'though, so it's already a matter of knowing which one to run from some other source, really....

2025-05-15 19:34 UTC, closed without merging

2025-05-15 23:58 UTC, peterbarker commented
> Since it has been quite old, I probably should start with a new script modification, though probably not soon as I'm also quite busy at the moment. Probably better to close this PR before I make a new one with a better script. Thank you for your input @peterbarker

No worries.  Sorry if it seems I'm being too finicky, but whatever goes in has to be maintained!

2025-07-31 16:17 UTC, Linjieqiang commented
Any idea? I use the fedora system now. And want to build the ardupilot firmware.

2025-12-18 19:42 UTC, Landrash commented
If this could be added without being included in the tests it would be a great addition for those who choose to run Fedora.

Runner image of fedora seems to be a nogo with Github not listening to community with Fedora and others.