Gsof bitmask flexible parser
ArduPilot/ardupilot pull request #28802
Opened 2024-12-04 08:28 UTC by Ryanf55

# Purpose

Refactor the GSOF parser to instead take in a bitmask of expected packets. Compared to before, where we used a counter for packets, which was not robust to duplicate packets, or flexible to different sets of packets, this now mirrors more commonly accepted ways of parsing such as in the inertial labs EAHRS by using a Bitmask to keep track of received packets. 

# Details

* Removed unused debug macro
* Clean up docs
* The GPS driver's expected packets now has to be set at runtime, since you can't initialize an AP bitmask at compile time

# Next Up

The upcoming Trimble External AHRS will re-use this parser, but with different packets. 

# Testing Performed

* Autotest covers GSOF quite well, including configuration
* Run the SITL driver per the instructions in AP_GPS_GSOF.cpp and fly around. Ensure the EKF tracks as expected by observing a stable loiter.

2024-12-05 10:01 UTC, andyp1per reviewed
It looks ok to me but the logic of the changes is a little hard to follow

2024-12-05 14:32 UTC, Ryanf55 commented
> It looks ok to me but the logic of the changes is a little hard to follow

Thanks for the review! I'm open to changes to improve readability too - if you had any recommendations, I'm happy to implement.

2024-12-08 17:58 UTC, tpwrules commented
The code looks okay. But it's not clear that the original problem exists, or that this solves it properly? The links have rotted but I looked through Trimble's documentation and this is what I surmise happens each "epoch" (assuming all the messages come at the same rate which we do configure):

1. Do GPS data processing
2. Build and concatenate the configured GSOF messages into a blob
3. Split the blob into 1-n GENOUT packets
4. Send all the packets

The documentation says "There can be various records in one GENOUT packet. There could be multiple GENOUT packets per epoch. Records may be split over two consecutive packets.". I'm further assuming that one "transmission number" is used for each time through this loop.

The current code assumes the above loop, but it only assumes 1 GENOUT packet. Can the transmitter put multiple messages of the same type into one packet? I assume the previous would fail because it should, according to my model, get 5 different GENOUT packets with 1 message each.

This also will fall apart if the set of requested messages ever exceeds 248 bytes (one GENOUT packet). I think this needs a deeper rework. The memory overflows should be fixed too.

2024-12-15 04:57 UTC, Ryanf55 commented
New plan:
* Remove the code that passes in the `expected` packets -> ie `void AP_GSOF::process_message()`
* Move the configuration request into AP_GSOF (now or later)
* Consider wrapping the parser packets in ifdefs for which is needed for which by which driver
* Note - the new the new packets all have timestamps

2024-12-31 04:10 UTC, Ryanf55 reviewed
I've reworked the PR a bit to make it a bit simpler and functionally robust to extranneous data. I tested it by enabling a few extra packets, and verified the parser still is happy. 

I also tested disabling one of the required packets, and it was no longer healthy as designed.

2024-12-31 04:10 UTC, Ryanf55 commented on libraries/AP_GPS/AP_GPS_GSOF.cpp
> +                parsed.get(AP_GSOF::POS_SIGMA)
This is now robust to extranneous packets being enabled. As long as the data we care about was parsed, we can pack the GPS state structure.

2025-01-02 11:33 UTC, andyp1per approved these changes
LGTM

2025-01-06 23:40 UTC, tridge requested changes

2025-01-06 23:40 UTC, tridge commented on libraries/AP_GPS/AP_GPS_GSOF.cpp
> -    static_assert(ARRAY_SIZE(gsofmsgreq) <= 10, "The maximum number of outputs allowed with GSOF is 10.");
prefer compile time assert if possible, happy to have new constructor for AP_Bitmask that takes const array

2025-01-07 01:17 UTC, Ryanf55 commented
I've spend 45 minutes trying to get a constructor working so we can static assert the size. I can't get the Bitmask to have a constructor that can take in an array and then another statement call `.count` for a static_assert.
![image](https://github.com/user-attachments/assets/979f57e9-c7b7-4bfb-aa29-d8d729119b6b)
There is no way a user will ever hit this because we have CI and unit tests will catch it before merge. 

Are we ok merging as-is with the internal error? I could wrap it in defines only for SITL if we are worried.

2025-01-07 01:23 UTC, tpwrules commented
I understood that the desire was to call static_assert on the array rather than bitmask.count(). You also don't necessarily need to add a constructor to AP_Bitmask, that could be done in a followup though.

2025-01-07 01:24 UTC, Ryanf55 commented
> I understood that the desire was to call static_assert on the array rather than bitmask.count(). You also don't necessarily need to add a constructor to AP_Bitmask, that could be done in a followup though.

You can't do a static assert if you don't have a constexpr constructor, unless I'm missing something.

2025-01-07 01:55 UTC, tpwrules commented
I think the idea was to keep the array and static_assert like they were before this PR, then add a little loop in the GSOF constructor which reads that array and sets up the bitmask.

2025-01-07 06:05 UTC, Ryanf55 commented on libraries/AP_GPS/AP_GPS_GSOF.cpp
> -    static_assert(ARRAY_SIZE(gsofmsgreq) <= 10, "The maximum number of outputs allowed with GSOF is 10.");
Done!

2025-01-07 08:40 UTC, Ryanf55 commented
> I think the idea was to keep the array and static_assert like they were before this PR, then add a little loop in the GSOF constructor which reads that array and sets up the bitmask.

Got it, sorry, was being dense. Take a look now.

2025-01-07 21:52 UTC, tridge approved these changes

2025-01-07 21:52 UTC, merged