Tuning indication on OSD(and GCS)
ArduPilot/ardupilot pull request #28831
Opened 2024-12-09 15:29 UTC by Yury-MonZon

This PR includes:

Displaying the current value of the parameter being tuned
![image](https://github.com/user-attachments/assets/a0164f60-5b6e-401c-907b-8e42c6bb215c)

When tuning knob is in the middle (note `>` instead of `:`):
![image](https://github.com/user-attachments/assets/ffafb0d5-d4ca-448d-a428-fe2da507e13c)

Adding PIDFF tuning sets for FixedWing mode:

1. D and P for Roll and Pitch (for quick post-autotune adjustments)
2. PIDFF for Roll
3. PIDFF for Pitch

These additions are primarily designed for tuning via FPV without requiring MAVLink modems.

I'll add PR for wiki once everything is settled, currently it is here https://github.com/Yury-MonZon/ardupilot_wiki/tree/patch-1

2024-12-09 17:49 UTC, andyp1per commented
Nice idea! @Hwurzburg may have an opinion

2024-12-09 19:36 UTC, Hwurzburg commented
not sure what you are talking about "0.5f"
....but 5% seems reasonable for any PID related value as a threshold to display a new message (remember OSD messages persist a while (10s is default)....and ultrafine adjustment of PIDs is a pointless exercise since noticeable changes only occur with larger changes and you need a wide margin of stability in order to prevent corner case flight points resulting in oscillations...for example, we take PIDS, to oscillation, when tuning in level flight and cut them by 1/3 to prevent instability in other flight extremes in our autotune algorithms...

2024-12-09 23:29 UTC, Hwurzburg commented
the wiki has lots of details on tuning process for each vehicle

the TX tuning is really a bit dated and for special cases (like default pids results in an unstable vehicle...highly unlikely)....in Plane the autotune for fixed wing and quicktune for quadplanes is the easy path, Copter: Autotune, Rover:is pretty straightforward....using manual PID tuning is really beyond most users and can even be dangerous...

most users will have a lot of difficulty using manual tuning and getting good results....sometimes even having a dangerous tune on big vehicles...

2024-12-25 13:22 UTC, Hwurzburg approved these changes

2024-12-30 23:46 UTC, tridge requested changes

2024-12-30 23:46 UTC, tridge commented on libraries/AP_Tuning/AP_Tuning.cpp
> +    static float old_value;
the static doesn't look right for when we change which parameter we are tuning, we'd need the variable in the class and reset on param change

2024-12-30 23:46 UTC, tridge commented on libraries/AP_Tuning/AP_Tuning.cpp
> +            "Tuning %s%s%0.4f",
if the intention is this comes out as speech in mavproxy it needs to start with "Tuning: " or an "@"

2024-12-30 23:47 UTC, peterbarker commented on libraries/AP_Tuning/AP_Tuning.cpp
> +    static float old_value;
Move initialisation of value to `check_selector` switch and `old_value` into the tuning class

2024-12-30 23:48 UTC, tridge commented on ArduPlane/tuning.h
> +        TUNING_SET_DP_ROLL_PITCH =          11,
on what aircraft does it make sense to link D and P?

2025-01-21 00:19 UTC, tridge approved these changes

2025-01-21 00:19 UTC, merged