SITL: add AP_MOTORS_FRAME_xxx_ENABLED guards
ArduPilot/ardupilot pull request #28885
Opened 2024-12-16 11:15 UTC by srmainwaring

Add `AP_MOTORS_FRAME_xxx_ENABLED` guards to `SIM_Frame.cpp` as they are applied in `AP_Motors_Matrix.cpp`. This does not change default behaviour and allows the majority of the motor mixes to be disabled in the `esp32xxempty` boards which frees up RAM.

### Related

- https://github.com/ArduPilot/ardupilot/pull/28848

### Testing

#### esp32empty

Before

```bash
Total sizes:
Used static DRAM:  147848 bytes (  32888 remain, 81.8% used)
      .data size:   19368 bytes
      .bss  size:  128480 bytes
Used static IRAM:  113718 bytes (  17354 remain, 86.8% used)
      .text size:  112691 bytes
   .vectors size:    1027 bytes
Used Flash size : 1856264 bytes
           .text: 1548788 bytes
         .rodata:  307220 bytes
Total image size: 1989350 bytes (.bin may be padded larger)
```

After

```bash
Total sizes:
Used static DRAM:  120488 bytes (  60248 remain, 66.7% used)
      .data size:   19368 bytes
      .bss  size:  101120 bytes
Used static IRAM:  113718 bytes (  17354 remain, 86.8% used)
      .text size:  112691 bytes
   .vectors size:    1027 bytes
Used Flash size : 1849596 bytes
           .text: 1545128 bytes
         .rodata:  304212 bytes
Total image size: 1982682 bytes (.bin may be padded larger)
```

#### esp32s3empty

Before

```bash
Total sizes:
Used stat D/IRAM:  236610 bytes ( 105150 remain, 69.2% used)
      .data size:   21960 bytes
      .bss  size:  109784 bytes
      .text size:  103839 bytes
   .vectors size:    1027 bytes
Used Flash size : 1636580 bytes
           .text: 1354860 bytes
         .rodata:  281464 bytes
Total image size: 1763406 bytes (.bin may be padded larger)
```

After

```bash
Total sizes:
Used stat D/IRAM:  209250 bytes ( 132510 remain, 61.2% used)
      .data size:   21960 bytes
      .bss  size:   82424 bytes
      .text size:  103839 bytes
   .vectors size:    1027 bytes
Used Flash size : 1629848 bytes
           .text: 1351152 bytes
         .rodata:  278440 bytes
Total image size: 1756674 bytes (.bin may be padded larger)
```

2024-12-16 12:09 UTC, IamPete1 approved these changes
LGTM

2024-12-16 20:59 UTC, peterbarker requested changes

2024-12-16 20:59 UTC, peterbarker commented on libraries/SITL/SIM_Frame.cpp
> +#if AP_MOTORS_FRAME_OCTA_ENABLED
Sorry, you're mixing the streams here!

We try not to rely on stuff from the "other side" here.  ie. you should be able to compile support for the frame out in ArduPilot but havesim support for it - and support it in AP nbut not in SIM.

That measn creating `AP_SIM_MOTORS_FRAME_OCTAQUAD_ENABLED` etc

2024-12-17 01:02 UTC, davidbuzz approved these changes
looks ok to me, if u can convince peter its ok. :-)

2025-04-30 05:50 UTC, peterbarker commented
I've narrowed this to just the ESP32 changes.

As mentioned in my review, need SITL defines for SITL-side.

Please create a fresh PR if you want to do the SITL-side, @srmainwaring :-)

2025-04-30 05:50 UTC, peterbarker approved these changes

2025-05-01 07:27 UTC, srmainwaring commented
> I've narrowed this to just the ESP32 changes.
> 
> As mentioned in my review, need SITL defines for SITL-side.
> 
> Please create a fresh PR if you want to do the SITL-side, @srmainwaring :-)

Thanks @peterbarker. I'll update that when I get back to the next round of profiling for ESP32 running SITL.

2025-05-02 06:05 UTC, merged