Plane: backport takeoff fix PR 28792
ArduPilot/ardupilot pull request #28901
Opened 2024-12-18 08:44 UTC by tridge

2025-01-22 02:24 UTC, rmackay9 commented
This one is failing CI so I didn't include it in 4.6.0-beta3.  I tried to restart it but somehow couldn't find the "restarted failed jobs" button in CI

2025-01-22 08:23 UTC, Georacer commented
I don't have rights to restart jobs. And I guess a re-base isn't an option in this case.

2025-01-22 09:07 UTC, Georacer requested changes

2025-01-22 09:07 UTC, Georacer commented on Tools/autotest/arduplane.py
> +        self.fly_home_land_and_disarm()
This test was apparently accidentally brought in.
It refers to https://github.com/ArduPilot/ardupilot/pull/28351, which is a feature not backported to 4.6.

2025-02-10 23:14 UTC, tridge commented
@Georacer I've removed the bad test, thanks
how critical do you think this backport is for 4.6.0 ?

2025-03-25 11:49 UTC, Georacer commented
@tridge my memory is a bit rusty, as I've overlooked your question. Sorry about that.

IIRC, we have said we wanted this in 4.6, because it fixes a bug/new-behaviour brought in by https://github.com/ArduPilot/ardupilot/pull/27758/commits, documented in [this PR](https://github.com/ArduPilot/ardupilot/pull/28792) which we have also brought in 4.6.

So, yes, we do want this in 4.6.

2025-04-28 03:58 UTC, merged

2025-04-28 03:59 UTC, rmackay9 commented
this is included in 4.6.0-beta6