Plane: log whether throttle is suppressed or not
ArduPilot/ardupilot pull request #28906
Opened 2024-12-19 12:38 UTC by peterbarker

This adds logging of whether the throttle is suppressed or not into the `STAT` message.

I've created a new field, "Bit" to hold a bitmask of boolean information about the vehicle - saves 40 bytes per message past me adding the new field.

I suggest we remove the old equivalent uint8_t fields in 4.8 - just have them in here for a bit of cross-over.

The new LogStatus class is perhaps overkill - but I think we might be able to templatise it and have a nice, compact way of doing similar bitmasks in log messages.

For this entire PR:
```
Board                    AP_Periph  blimp  bootloader  copter  heli  iofirmware  plane  rover  sub
CubeOrange-periph-heavy  *                                                                     
CubeRedPrimary                      *      *           *       *                 120    *      *
Durandal                            *      *           *       *                 72     *      *
Hitec-Airspeed           *                                                                     
KakuteH7-bdshot                     *      *           *       *                 120    *      *
MatekF405                           *      *           *       *                 120    *      *
Pixhawk1-1M-bdshot                  *                  *       *                 120    *      *
f103-QiotekPeriph        *                                                                     
f303-Universal           *                                                                     
iomcu                                                                *                         
revo-mini                           *      *           *       *                 120    *      *
skyviper-journey                                       *                                       
skyviper-v2450                                         *                                       
```

Without the new logging, just with the weird class and consolidating into status, removing the old fields:
```
Board                    AP_Periph  blimp  bootloader  copter  heli  iofirmware  plane  rover  sub
CubeOrange-periph-heavy  *                                                                     
CubeRedPrimary                      *      *           *       *                 -32    *      *
Durandal                            *      *           *       *                 -24    *      *
Hitec-Airspeed           *                                                                     
KakuteH7-bdshot                     *      *           *       *                 -32    *      *
MatekF405                           *      *           *       *                 -32    *      *
Pixhawk1-1M-bdshot                  *                  *       *                 -32    *      *
f103-QiotekPeriph        *                                                                     
f303-Universal           *                                                                     
iomcu                                                                *                         
revo-mini                           *      *           *       *                 -32    *      *
skyviper-journey                                       *                                       
skyviper-v2450                                         *                                       
```

2024-12-21 18:07 UTC, Georacer commented
I like the idea of a more compact logging of logic flags. Smaller logs is always better.

But as it stands, it would make reading the logs (e.g. via MAVExplorer) much harder.
How do you propose decoding the new `status` field to extract and plot individual bits?

2024-12-23 03:15 UTC, peterbarker commented
> I like the idea of a more compact logging of logic flags. Smaller logs is always better.
> 
> But as it stands, it would make reading the logs (e.g. via MAVExplorer) much harder. How do you propose decoding the new `status` field to extract and plot individual bits?

MissionPlanner already has a good interface for this - as do the web tools IIUC.

MAVExplorer you can log the bits with `graph STAT.Bit&1<<0` for the IS_FLYING bit.

2025-02-10 13:17 UTC, IamPete1 commented on ArduPlane/Log.cpp
> +        safety      : static_cast<uint8_t>(hal.util->safety_switch_state()),
Why not have safety state in the bitmask?

2025-02-10 23:48 UTC, tridge requested changes

2025-02-10 23:48 UTC, tridge commented on ArduPlane/Log.cpp
> +      "STAT", "QBfBBBBBBH",  "TimeUS,isFlying,isFlyProb,Armed,Safety,Crash,Still,Stage,Hit,Bit", "s---------", "F---------" , true },
I think a 'Sup' field is a better approach

2025-02-27 22:44 UTC, peterbarker commented on ArduPlane/Log.cpp
> +        safety      : static_cast<uint8_t>(hal.util->safety_switch_state()),
Three states and comes from an enumeration.  We've done that before in copter's `ap` and it sucked

2025-02-27 22:55 UTC, peterbarker commented
![image](https://github.com/user-attachments/assets/9c837e30-1d53-43cb-913e-f217668d1606)

2025-02-27 22:55 UTC, peterbarker commented on ArduPlane/Log.cpp
> +      "STAT", "QBfBBBBBBH",  "TimeUS,isFlying,isFlyProb,Armed,Safety,Crash,Still,Stage,Hit,Bit", "s---------", "F---------" , true },
Done

2025-02-28 10:53 UTC, peterbarker commented
Merging as agreed at DevCall.

2025-02-28 10:53 UTC, merged