Create separate option for bridging mcast and hw can
ArduPilot/ardupilot pull request #28913
Opened 2024-12-20 04:03 UTC by bugobliterator

* Bridging between mcast CAN and HW CAN needs to be turned off by default. The reason is if there are more than 2 devices on the same HW CAN and Ethernet network that will cause network loops and potentially choke the CAN bus.
* Bridging needs to be always turned off for Bootloaders, and in the case of AP_Periph and ardupilot, it should be enabled by the user.

Changes done:
* Change option name from  CAN1_MCAST_GATEWAY to CAN1_MCAST_ENDPOINT in NET_OPTIONS.
* Adds another option CAN1_MCAST_BRIDGED to enable bridging between MCAST and Hw CAN.

2025-01-13 22:50 UTC, tridge commented on libraries/AP_HAL/CANIface.h
> +        bool rx_cb_disable[3];
why do we need these disable flags? if we want to disable, why don't we just call unregister_frame_callback()?

2025-01-14 00:18 UTC, bugobliterator commented on libraries/AP_HAL/CANIface.h
> +        bool rx_cb_disable[3];
@tridge the disable is only to remove calling on rx, but we still call the callback on tx from CANIface. Basically we don't forward what we receive from CAN Bus, but we still transmit frames that are to be sent out. That's how we leave the interaction with the device itself functional. Unregistering will remove the call from both tx and rx.

2025-01-22 07:12 UTC, tridge commented
@bugobliterator could this be handled in the callback in the AP_Networking layer?

2025-01-22 22:59 UTC, bugobliterator commented
> @bugobliterator could this be handled in the callback in the AP_Networking layer?

I don't think there's a way to do this without changes to CANIface, there's a common callback for both RX and TX. We have to either pass the direction as callback parameter, make it part of each frame or the way I have done which is to have the direction selection per callback. First method will require wider changes, second one costs more memory and third one I think is a happy middle.

2025-01-29 07:13 UTC, tridge commented on libraries/AP_HAL/CANIface.cpp
> -            cb(get_iface_num(), out_frame);
adding an bool is_send as an additional field in the callback
maybe change
```
    FUNCTOR_TYPEDEF(FrameCb, void, uint8_t, const AP_HAL::CANFrame &);
```
to this:
```
    FUNCTOR_TYPEDEF(FrameCb, void, uint8_t, const AP_HAL::CANFrame &, uint8_t flags);
```

2025-01-29 07:15 UTC, tridge commented on libraries/AP_HAL/CANIface.cpp
> -            cb(get_iface_num(), out_frame);
or could be a bool

2025-01-29 07:17 UTC, peterbarker submitted a review, later dismissed

2025-01-29 07:17 UTC, peterbarker commented on libraries/AP_Networking/AP_Networking.cpp
>  #if AP_NETWORKING_CAN_MCAST_ENABLED && !defined(HAL_BOOTLOADER_BUILD)
```suggestion
#if AP_NETWORKING_CAN_MCAST_BRIDGING_ENABLED
```

2025-01-29 07:17 UTC, peterbarker commented on libraries/AP_Networking/AP_Networking.h
> +#if AP_NETWORKING_CAN_MCAST_ENABLED
This would make it onto the bootloader?  Maybe elided?

Separate define as suggested would make this clearly not a problem.

2025-01-29 07:17 UTC, peterbarker commented on libraries/AP_Networking/AP_Networking_CAN.cpp
> +#ifndef HAL_BOOTLOADER_BUILD
```suggestion
#if AP_NETWORKING_CAN_MCAST_BRIDGING_ENABLED
```

2025-01-29 07:17 UTC, peterbarker commented on libraries/AP_Networking/AP_Networking_CAN.cpp
> +#ifndef HAL_BOOTLOADER_BUILD
... use new define...

2025-01-30 01:04 UTC, bugobliterator commented on libraries/AP_HAL/CANIface.cpp
> -            cb(get_iface_num(), out_frame);
Moved to using CANIOFlags actually to keep things consistent.

Also changed IsMAVCAN flag to IsForwardedFrame. This flag is then used to check if the frame was forwarded from different physical iface.

2025-01-30 01:08 UTC, bugobliterator commented on libraries/AP_Networking/AP_Networking.cpp
>  #if AP_NETWORKING_CAN_MCAST_ENABLED && !defined(HAL_BOOTLOADER_BUILD)
done

2025-01-30 01:09 UTC, bugobliterator commented on libraries/AP_Networking/AP_Networking.h
> +#if AP_NETWORKING_CAN_MCAST_ENABLED
done using AP_NETWORKING_CAN_MCAST_BRIDGING_ENABLED

2025-01-30 01:10 UTC, bugobliterator commented on libraries/AP_Networking/AP_Networking_CAN.cpp
> +#ifndef HAL_BOOTLOADER_BUILD
not needed

2025-01-30 02:51 UTC, bugobliterator reviewed
requested changes made

2025-01-30 19:53 UTC, tridge requested changes
this looks much better, thank you!
just the one trivial fix needed then should be merged

2025-01-30 19:53 UTC, tridge commented on libraries/AP_Networking/AP_Networking_CAN.cpp
> +    if (flags & AP_HAL::CANIface::IsForwardedFrame && !bridged) {
I think we need parentheses around the bitmask test, or some compilers will complain

2025-02-03 01:18 UTC, bugobliterator commented on libraries/AP_Networking/AP_Networking_CAN.cpp
> +    if (flags & AP_HAL::CANIface::IsForwardedFrame && !bridged) {
fixed

2025-02-03 04:51 UTC, tridge approved these changes

2025-02-03 04:59 UTC, peterbarker commented on libraries/AP_Networking/AP_Networking.h
> +        CAN1_MCAST_BRIDGED=(1U<<3),
These could also be protected by `AP_NETWORKING_CAN_MCAST_ENABLED` to catch places that are trying to handle bridged stuff when they shouldn't.

2025-02-03 04:59 UTC, peterbarker commented on libraries/AP_Networking/AP_Networking_CAN.cpp
> +                    auto retcode = cbus->send(frame, AP_HAL::micros64() + timeout_us,
This is dead code on bootloader... I wonder if the compiler is smart enough to elide..
.

2025-02-03 04:59 UTC, peterbarker commented on libraries/AP_Networking/AP_Networking_Config.h
> +#define AP_NETWORKING_CAN_MCAST_BRIDGING_ENABLED AP_NETWORKING_CAN_MCAST_ENABLED && !defined(HAL_BOOTLOADER_BUILD)
The default for the bootloader should be in `libraries/AP_HAL_ChibiOS/hwdef/scripts/defaults_bootloader.h`

2025-02-04 00:15 UTC, bugobliterator commented on libraries/AP_Networking/AP_Networking_CAN.cpp
> +                    auto retcode = cbus->send(frame, AP_HAL::micros64() + timeout_us,
probably, but going to play it safe and forcing it out.

2025-02-04 00:15 UTC, bugobliterator commented on libraries/AP_Networking/AP_Networking_Config.h
> +#define AP_NETWORKING_CAN_MCAST_BRIDGING_ENABLED AP_NETWORKING_CAN_MCAST_ENABLED && !defined(HAL_BOOTLOADER_BUILD)
fixed

2025-02-04 00:18 UTC, peterbarker commented on libraries/AP_Networking/AP_Networking.h
> +        CAN1_MCAST_BRIDGED=(1U<<3),
> did you mean AP_NETWORKING_CAN_MCAST_BRIDGING_ENABLED ?

Yes, sorry

2025-02-04 00:21 UTC, peterbarker approved these changes
LGTM

2025-02-04 23:23 UTC, merged

2025-02-13 10:51 UTC, rmackay9 commented
I was unable to include this in AP-4.6.0-beta4 due to merge conflicts.  If we're keen to get this backported could @bugobliterator or someone else perhaps create a backport PR?

2025-02-14 15:55 UTC, bugobliterator commented
> I was unable to include this in AP-4.6.0-beta4 due to merge conflicts. If we're keen to get this backported could @bugobliterator or someone else perhaps create a backport PR?

@rmackay9 backport pr is here https://github.com/ArduPilot/ardupilot/pull/29297