AP_BattMonitor: Handle allocating too many analog channels
ArduPilot/ardupilot pull request #28910
Opened 2024-12-19 20:52 UTC by WickedShell

If you over allocate the number of analog channels this results in a crash. It's easy to trigger this if you have voltage only monitors as we still eat up a current input channel, regarless of if we use it. There are only 16 channels at this time on ChibiOS, so if you have 9 voltage only battery monitors you are out.

This PR improves that situation by only allocating channels when needed, and in the case where we run out we now set a ConfigError, which on a flight controller is much more friendly then a instant segfault the moment we read a battery monitor. NOTE: on AP_Periph this takes the node off the bus, rather then just sitting in the bootloader. This was consideted acceptable as the current behaviour was to segfault and then sit in the bootloader, unless you made new firmware that limited the number of channels allocated it wasn't possible to recover in this situation anyways.

Tested on CubeOrangePlus with plane firmware, as well as on AP_Periph.

2024-12-19 21:09 UTC, andyp1per approved these changes
LGTM

2024-12-20 00:17 UTC, peterbarker commented
How do you recover the periph if it never comes up on the bus?

2024-12-22 15:05 UTC, IamPete1 requested changes
This line needs deleting from `AP_BattMonitor_Synthetic_Current`which inherits from `AP_BattMonitor_Analog`

https://github.com/ArduPilot/ardupilot/blob/613b835d67f817bdf9a1b864e9d988fd819efa03/libraries/AP_BattMonitor/AP_BattMonitor_Synthetic_Current.cpp#L62-L63

Looks good apart from that.

2024-12-23 18:33 UTC, IamPete1 approved these changes
LGTM

2024-12-24 00:01 UTC, merged