add Stellar H7V2 target
ArduPilot/ardupilot pull request #28926
Opened 2024-12-21 17:26 UTC by cvetaevvitaliy

add Stellar H7V2 target

2024-12-21 19:11 UTC, Hwurzburg commented
Needs full readme with images and pinouts...see other recent hwdefs....should break out board id into separate PR that can be merged before this gets a review in order to reserve the board id...also use the text board name instead of number in the hwdefs

2024-12-21 19:39 UTC, cvetaevvitaliy commented
> Needs full readme with images and pinouts...see other recent hwdefs....should break out board id into separate PR that can be merged before this gets a review in order to reserve the board id...also use the text board name instead of number in the hwdefs

Done

#28929

2024-12-23 11:39 UTC, andyp1per requested changes
Commits need to be squashed per subsystem and labeled according to our coding standards. Please see https://ardupilot.org/dev/docs/submitting-patches-back-to-master.html

2024-12-23 11:39 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/hwdef.dat
> +SERIAL_ORDER OTG1 UART7 USART1 USART2 USART3 UART8 UART4 USART6
I would not recommend changing the order here unless the silkscreen has the same numbering

2024-12-23 11:39 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/hwdef.dat
> +# UART4 (spare)
RCIN according to the picture?

2024-12-23 11:39 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/hwdef.dat
> +PB0  TIM3_CH3  TIM3  PWM(1)  GPIO(50)
Should add bidir here

2024-12-26 12:27 UTC, cvetaevvitaliy commented on libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/hwdef.dat
> +# UART4 (spare)
UART4

2025-01-02 11:42 UTC, andyp1per requested changes

2025-01-02 11:42 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/Readme.md
> + - SERIAL1 -> USART1 (User)
These need some better descriptions I think

2025-01-02 11:42 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/hwdef.dat
> +PA0  TIM5_CH1  TIM5  PWM(3)  GPIO(52)
You should at least add it to PWM3 as well so that you can support a quad with bi-dir

2025-01-02 11:42 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/hwdef.dat
> +PA0  TIM5_CH1  TIM5  PWM(3)  GPIO(52)
Should come at the end of the line

2025-01-09 16:12 UTC, Hwurzburg requested changes
you will also need to squash the commits into one for the Tools library titled
Tools:add StellarH7V2

and one for the hwdef library titled
HWDEF: add StellarH7V2

2025-01-09 16:12 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/Readme.md
> +StellarH7V2 supports using its internal OSD using OSD_TYPE 1 (MAX7456 driver). External OSD support such as DJI or DisplayPort is supported using any spare UART. See :ref:`common-msp-osd-overview-4.2
```suggestion
StellarH7V2 supports using its internal OSD using OSD_TYPE 1 (MAX7456 driver). Simulatenous DisplayPort OSD operation  is preconfigured on SERIAL 6 but requires OSD_TYPE2 = 5. See :ref:`common-msp-osd-overview-4.2` for more info.
```

2025-01-09 16:12 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/Readme.md
> +
```suggestion
All the channels support DShot. Channels 1-4 support bi-directional DShot. PWM outputs are grouped and every group must use the same output protocol:

* 1, 2,are Group 1;
* 3 - 6 are Group 2;
* 7 - 9 are Group 3;
```

2025-01-09 16:12 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/Readme.md
> +
```suggestion
The voltage input is compatible with 2~8S LiPo batteries.

The default battery parameters are:

* :ref:`BATT_MONITOR<BATT_MONITOR>` = 4
* :ref:`BATT_VOLT_PIN<BATT_VOLT_PIN__AP_BattMonitor_Analog>` = 10
* :ref:`BATT_CURR_PIN<BATT_CURR_PIN__AP_BattMonitor_Analog>` = 11
* :ref:`BATT_VOLT_MULT<BATT_VOLT_MULT__AP_BattMonitor_Analog>` = 11
* :ref:`BATT_AMP_PERVLT<BATT_AMP_PERVLT__AP_BattMonitor_Analog>` = 10
* :ref:`BATT2_CURR_PIN<BATT2_CURR_PIN__AP_BattMonitor_Analog>` = 7
```

2025-01-09 16:12 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/Readme.md
> +
need to add section on Camera Switch:
```suggestion
## Camera Switch
GPIO 81 controls which camera input (CAM1 or CAM22 is applied to the internal OSD. A RELAY function can be enabled to control the switching.
```

2025-01-09 16:15 UTC, cvetaevvitaliy commented
No problem.
New Year's holidays are over, back to work.

чт, 9 січ. 2025 р. о 18:13 Henry Wurzburg ***@***.***> пише:

> ***@***.**** requested changes on this pull request.
>
> you will also need to squash the commits into one for the Tools library
> titled
> Tools:add StellarH7V2
>
> and one for the hwdef library titled
> HWDEF: add StellarH7V2
> ------------------------------
>
> In libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/Readme.md
> <https://github.com/ArduPilot/ardupilot/pull/28926#discussion_r1909057175>
> :
>
> > @@ -0,0 +1,94 @@
> +# StellarH7V2 Flight Controller
> +
> +https://stingbee.com.ua/flight_controllers/stellarh7v2
> +
> +
> +## Features
> +    Processor
> +        STM32H743VIH6 480 MHz, 2MB flash
> +    Sensors
> +        ICM-42688p Acc/Gyro with external clock feature
> +        DPS310/BMP280 barometer
> +        AT7456E OSD
> +        SD Card
> +        W25N02G/1G dataflash
>
> unless this will be on the autopilot when we merge this, remove this line
> ------------------------------
>
> In libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/Readme.md
> <https://github.com/ArduPilot/ardupilot/pull/28926#discussion_r1909057986>
> :
>
> > +# StellarH7V2 Flight Controller
> +
> +https://stingbee.com.ua/flight_controllers/stellarh7v2
> +
> +
> +## Features
> +    Processor
> +        STM32H743VIH6 480 MHz, 2MB flash
> +    Sensors
> +        ICM-42688p Acc/Gyro with external clock feature
> +        DPS310/BMP280 barometer
> +        AT7456E OSD
> +        SD Card
> +        W25N02G/1G dataflash
> +    Power
> +        8S Lipo input voltage with voltage monitoring
>
> 2S-8S?
> ------------------------------
>
> In libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/Readme.md
> <https://github.com/ArduPilot/ardupilot/pull/28926#discussion_r1909059036>
> :
>
> > +
> +## Features
> +    Processor
> +        STM32H743VIH6 480 MHz, 2MB flash
> +    Sensors
> +        ICM-42688p Acc/Gyro with external clock feature
> +        DPS310/BMP280 barometer
> +        AT7456E OSD
> +        SD Card
> +        W25N02G/1G dataflash
> +    Power
> +        8S Lipo input voltage with voltage monitoring
> +        12V, 3A BEC for powering Video Transmitter
> +        5V, 2A BEC for internal and peripherals
> +    Interfaces
> +        10x PWM outputs DShot capable
>
> I see only 8 outputs on the board, what am I missing?
> ------------------------------
>
> In libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/Readme.md
> <https://github.com/ArduPilot/ardupilot/pull/28926#discussion_r1909060987>
> :
>
> > +
> +## Features
> +    Processor
> +        STM32H743VIH6 480 MHz, 2MB flash
> +    Sensors
> +        ICM-42688p Acc/Gyro with external clock feature
> +        DPS310/BMP280 barometer
> +        AT7456E OSD
> +        SD Card
> +        W25N02G/1G dataflash
> +    Power
> +        8S Lipo input voltage with voltage monitoring
> +        12V, 3A BEC for powering Video Transmitter
> +        5V, 2A BEC for internal and peripherals
> +    Interfaces
> +        10x PWM outputs DShot capable
>
> ⬇️ Suggested change
>
> -        10x PWM outputs DShot capable
> +        10x PWM outputs DShot capable, 4 outputs BDShot capable
>
> ------------------------------
>
> In libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/Readme.md
> <https://github.com/ArduPilot/ardupilot/pull/28926#discussion_r1909062229>
> :
>
> > +        ICM-42688p Acc/Gyro with external clock feature
> +        DPS310/BMP280 barometer
> +        AT7456E OSD
> +        SD Card
> +        W25N02G/1G dataflash
> +    Power
> +        8S Lipo input voltage with voltage monitoring
> +        12V, 3A BEC for powering Video Transmitter
> +        5V, 2A BEC for internal and peripherals
> +    Interfaces
> +        10x PWM outputs DShot capable
> +        7x UARTs
> +        1x CAN
> +        1x I2C
> +        3x ADC
> +        SD card and 128/256MB NAND for logging
>
> ⬇️ Suggested change
>
> -        SD card and 128/256MB NAND for logging
> +       micro-SD card interface
>
> ------------------------------
>
> In libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/Readme.md
> <https://github.com/ArduPilot/ardupilot/pull/28926#discussion_r1909062829>
> :
>
> > +        USB-C port
> +    LED
> +        Red, 3.3V power indicator
> +        Blue and Green, FC status
> +    Size
> +        41 x 41mm PCB with 30.5mm M3 mounting
> +
> +
> +## Overview
> +
> +![StellarH7V2](Stellar_H7V2.png)
> +
> +![StellarH7V2](StellarH7V2.png)
> +
> +## Wiring Diagram
> +
>
> will this be provided?
> ------------------------------
>
> In libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/Readme.md
> <https://github.com/ArduPilot/ardupilot/pull/28926#discussion_r1909063597>
> :
>
> > +        41 x 41mm PCB with 30.5mm M3 mounting
> +
> +
> +## Overview
> +
> +![StellarH7V2](Stellar_H7V2.png)
> +
> +![StellarH7V2](StellarH7V2.png)
> +
> +## Wiring Diagram
> +
> +
> +## UART Mapping
> +
> +The UARTs are marked Rx* and Tx* in the above pinouts. The Rx* pin is the
> +receive pin for UART*. The Tx* pin is the transmit pin for UART*.
>
> ⬇️ Suggested change
>
> -receive pin for UART*. The Tx* pin is the transmit pin for UART*.
> +receive pin for UART*. The Tx* pin is the transmit pin for UART*. All UARTS are DMA capable.
>
> ------------------------------
>
> In libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/Readme.md
> <https://github.com/ArduPilot/ardupilot/pull/28926#discussion_r1909064580>
> :
>
> > +## Overview
> +
> +![StellarH7V2](Stellar_H7V2.png)
> +
> +![StellarH7V2](StellarH7V2.png)
> +
> +## Wiring Diagram
> +
> +
> +## UART Mapping
> +
> +The UARTs are marked Rx* and Tx* in the above pinouts. The Rx* pin is the
> +receive pin for UART*. The Tx* pin is the transmit pin for UART*.
> +
> + - SERIAL0 -> USB
> + - SERIAL1 -> USART1 (User)
>
> Why not use the default protocols for UART1 and UART2 of MAVLink2??
> ------------------------------
>
> In libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/Readme.md
> <https://github.com/ArduPilot/ardupilot/pull/28926#discussion_r1909065137>
> :
>
> > +![StellarH7V2](StellarH7V2.png)
> +
> +## Wiring Diagram
> +
> +
> +## UART Mapping
> +
> +The UARTs are marked Rx* and Tx* in the above pinouts. The Rx* pin is the
> +receive pin for UART*. The Tx* pin is the transmit pin for UART*.
> +
> + - SERIAL0 -> USB
> + - SERIAL1 -> USART1 (User)
> + - SERIAL2 -> USART2 (User)
> + - SERIAL3 -> USART3 (User)
> + - SERIAL4 -> UART4  (Serial RC input)
> + - SERIAL6 -> USART6 (User)
>
> ⬇️ Suggested change
>
> - - SERIAL6 -> USART6 (User)
> + - SERIAL5-> USART6 (GPS)
>
> ------------------------------
>
> In libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/Readme.md
> <https://github.com/ArduPilot/ardupilot/pull/28926#discussion_r1909067597>
> :
>
> > +
> +## Wiring Diagram
> +
> +
> +## UART Mapping
> +
> +The UARTs are marked Rx* and Tx* in the above pinouts. The Rx* pin is the
> +receive pin for UART*. The Tx* pin is the transmit pin for UART*.
> +
> + - SERIAL0 -> USB
> + - SERIAL1 -> USART1 (User)
> + - SERIAL2 -> USART2 (User)
> + - SERIAL3 -> USART3 (User)
> + - SERIAL4 -> UART4  (Serial RC input)
> + - SERIAL6 -> USART6 (User)
> + - SERIAL7 -> USART6 (User)
>
> ⬇️ Suggested change
>
> - - SERIAL7 -> USART6 (User)
> + - SERIAL6 -> USART7 (DisplayPort)
>
> ------------------------------
>
> In libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/Readme.md
> <https://github.com/ArduPilot/ardupilot/pull/28926#discussion_r1909068973>
> :
>
> > +## Wiring Diagram
> +
> +
> +## UART Mapping
> +
> +The UARTs are marked Rx* and Tx* in the above pinouts. The Rx* pin is the
> +receive pin for UART*. The Tx* pin is the transmit pin for UART*.
> +
> + - SERIAL0 -> USB
> + - SERIAL1 -> USART1 (User)
> + - SERIAL2 -> USART2 (User)
> + - SERIAL3 -> USART3 (User)
> + - SERIAL4 -> UART4  (Serial RC input)
> + - SERIAL6 -> USART6 (User)
> + - SERIAL7 -> USART6 (User)
> + - SERIAL8 -> USART6 (User)
>
> ⬇️ Suggested change
>
> - - SERIAL8 -> USART6 (User)
> + - SERIAL7 -> USART8 (RX pin only, ESC Telemetry)
>
> ------------------------------
>
> In libraries/AP_HAL_ChibiOS/ [...]

2025-01-14 00:21 UTC, cvetaevvitaliy commented on libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/Readme.md
> +        10x PWM outputs DShot capable
yes

2025-01-14 00:31 UTC, cvetaevvitaliy commented
@Hwurzburg @andyp1per could you look at the changes in open issues ? 
Thanks

2025-01-15 18:13 UTC, andyp1per requested changes
Henry's changes need to be addressed and the commit messages changed

2025-01-15 18:13 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/Readme.md
> +# StellarH7V2 Flight Controller
Needs to be two commits, one for each subsystem. The commit message should start with:
"bootloaders: " - for the bootloader changes and
"AP_HAL_ChibiOS: " - for the hwdef changes

2025-01-15 18:13 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/hwdef.dat
> +PA2  TIM5_CH3  TIM5  PWM(5)  GPIO(54)
You may as well add BIDIR to PWM(5) as well - there is no downside with this configuration

2025-01-16 19:06 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/Readme.md
> +        10x PWM outputs DShot capable
where is PWM8 and 9?

2025-01-31 13:50 UTC, Hwurzburg requested changes

2025-01-31 13:50 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/Readme.md
> + - SERIAL7 -> UART8 (ESC Telemetry)
```suggestion
 - SERIAL7 -> UART8 (ESC Telemetry, RX8 pin only)
```

2025-01-31 13:50 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/Readme.md
> +* 9, 10      are Group 3;
the above groups are incorrect

2025-01-31 13:50 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/Readme.md
> +* 9, 10      are Group 3;
where is M9 and M10 pinned out...not on board photo

2025-01-31 13:55 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/Readme.md
> +* 9, 10      are Group 3;
and Andy's request to reformat the bidir lines has not been made

2025-02-26 22:49 UTC, marchuks commented
Hi,

I’ll be taking responsibility for this PR as well as any related ones regarding Stellar boards. I’ve made an effort to consolidate feedback and comments from the associated PRs, but please feel free to point out if I’ve missed anything or if there are any additional concerns that need to be addressed.

Looking forward to collaborating with everyone to get this merged. Let me know if you have any questions or if further clarification is needed on any part of the changes.

2025-03-01 02:38 UTC, Hwurzburg requested changes
looking very good...a couple of minor things

2025-03-01 02:38 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/Readme.md
> +* CRSF also requires a TX4 connection, in addition to RX6, and automatically provides telemetry.
```suggestion
* CRSF also requires a TX4 connection, in addition to RX4, and automatically provides telemetry.
```

2025-03-01 02:38 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/Readme.md
> +* FPort requires connection to TX4 and RX4 via a bi-directional inverter. See :ref:`common-FPort-receivers`.
```suggestion
* FPort requires connection to TX4  and :ref:`SERIAL4_OPTIONS<SERIAL4_OPTIONS>` set to "7". See :ref:`common-FPort-receivers`.
```

2025-03-01 02:38 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/Readme.md
> +* :ref:`BATT_CURR_PIN<BATT_CURR_PIN__AP_BattMonitor_Analog>` = 11
```suggestion
* :ref:`BATT_CURR_PIN<BATT_CURR_PIN__AP_BattMonitor_Analog>` = 11 (CURR pin)
```

2025-03-01 02:38 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/Readme.md
> +* :ref:`BATT2_CURR_PIN<BATT2_CURR_PIN__AP_BattMonitor_Analog>` = 7
```suggestion
* :ref:`BATT2_CURR_PIN<BATT2_CURR_PIN__AP_BattMonitor_Analog>` = 7 (ADC2 pin)
```

2025-03-01 02:38 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/hwdef.dat
> +define DEFAULT_SERIAL1_PROTOCOL SerialProtocol_MAVLink2
remove, default already

2025-03-01 02:38 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/hwdef.dat
> +define DEFAULT_SERIAL1_PROTOCOL SerialProtocol_MAVLink2
remove, default already

2025-03-01 02:38 UTC, Hwurzburg commented on libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/hwdef.dat
> +PA2  TIM5_CH3  TIM5  PWM(5)  GPIO(54)       # M5
```suggestion
PA2  TIM5_CH3  TIM5  PWM(5)  GPIO(54) BIDIR     # M5
```

2025-03-03 23:18 UTC, marchuks commented
Thanks for your suggestions. I’ve applied all of them. 
It appears GitHub automatically added the merge commit, since I don’t see it locally. I’ll keep that in mind for next time.

2025-03-05 13:26 UTC, Hwurzburg commented
merge commits happen when you merge master into your local branch instead of REBASING it on master to update it....rebasing to update a local branch is rarely needed since changes to master USUALLY don't impact hwdef stuff

2025-03-05 13:28 UTC, Hwurzburg approved these changes
@andyp1per can you approve and I will mark for DEVCALL?

2025-03-10 16:15 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/hwdef.dat
> +PE1 UART8_TX UART8
I would make these NODMA as its not necessary for ESC telemetry

2025-03-10 16:16 UTC, andyp1per approved these changes
LGTM, but to avoid too much DMA sharing I would make some of UARTS NODMA

2025-03-10 23:09 UTC, Hwurzburg commented
what did you change after my and Andys' approvals? force pushing invalidates those approvals!

2025-03-11 08:12 UTC, marchuks commented
> what did you change after my and Andys' approvals? force pushing invalidates those approvals!

I added `NODMA` for `USART6` and `UART8` as per Andy's request.   [diff](https://github.com/ArduPilot/ardupilot/compare/4fff2ad8aeb8518cebb557f18a482a94f82e7f64..2d31af221954467017389fc81848ec692bc303c2)
I also added the bottom view picture. [diff](https://github.com/ArduPilot/ardupilot/compare/2d31af221954467017389fc81848ec692bc303c2..e801f03557a3931f13e14dc7ecce0029cbaad297)
Quick question - how can I apply the requested changes without creating a new commit?

2025-03-11 08:15 UTC, marchuks commented on libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/hwdef.dat
> +PE1 UART8_TX UART8
Added `NODMA` for `USART6` (ESC telemetry) and `UART8` (GPS).

2025-03-11 12:07 UTC, Hwurzburg commented
if you make changes after a reveiw approval you can create a separate commit that has not been squashed and split, add it, and force push ....then later squash and split and push....that gives a history of the changes in the PR that is easily checked....or, if the changes are minor like this, just list them as you have done.

2025-03-12 08:04 UTC, merged