Stellar f4
ArduPilot/ardupilot pull request #28925
Opened 2024-12-21 15:42 UTC by cvetaevvitaliy

Hi! I'm a developer at StingBee, I saw the reserved board_id StellarF4 #27615
Could you please Stellar F4 support for our users of the awesome Ardupilot firmware

Thanks!

2024-12-21 19:14 UTC, Hwurzburg commented
see my comments on your other board PR....they apply here also...in addition this needs the bootloader binary in Tools/bootloaders

2024-12-21 19:51 UTC, cvetaevvitaliy commented
> see my comments on your other board PR....they apply here also...in addition this needs the bootloader binary in Tools/bootloaders

Done

2025-01-02 11:40 UTC, andyp1per requested changes
Some comments unaddressed

2025-01-15 18:14 UTC, andyp1per commented on libraries/AP_HAL_ChibiOS/hwdef/StellarF4/hwdef.dat
> +PB6  TIM4_CH1 TIM4 PWM(1) BIDIR GPIO(50)
BIDIR should go on the end. Only having it for 2 motors is less than ideal

2025-01-16 11:27 UTC, closed without merging