AP_Mount: add CADDX gimbal support
ArduPilot/ardupilot pull request #28942
Opened 2024-12-24 05:30 UTC by rmackay9

This is a simplified version of @Hwurzburg's previous PR https://github.com/ArduPilot/ardupilot/pull/28373 to add support for the [CADDX GM3 gimbal](https://caddxfpv.com/products/caddxfpv-gm1-gm2-gm3?variant=48924891611438)

This simply adds support for the gimbal without trying to support the extra lock types that the gimbal provides.  These extra lock types add the ability to control each axis (roll, pitch and yaw) in earth or body frame independently.  For example roll control could be in body frame while pitch is in earth frame.  This new ability is **not** supported in this PR.

This has been tested on real hardware and seems OK.

The corresponding wiki PR is here https://github.com/ArduPilot/ardupilot_wiki/pull/6441

2024-12-24 12:29 UTC, Hwurzburg commented
why drop the lock types and control?

2024-12-25 04:22 UTC, rmackay9 commented
Hi @Hwurzburg,

I dropped the lock types and control because I couldn't get them to work and also they are really an enhancement so they naturally fall into a follow-up PR that could potentially affect other gimbals as well.  The Siyi gimbal for example also supports FPV mode and users have been asking for that for a long time so we could do the two together

2024-12-25 07:45 UTC, Lalbabu2001 commented
Hi please add support for this board
https://www.6sfull.cz/en/neutronrc-mini-f405-2-6s-20--20-30--30/

Don't forget to add Bmp 280 baro because new versions come with bmp280.
Also add support for PPM .
Thanks.

2024-12-25 11:32 UTC, rmackay9 commented
Hi @Lalbabu2001,

I've created an issue here to capture this enhancement request https://github.com/ArduPilot/ardupilot/issues/28945.  No promises on when/if it will be done though.  I'm not personally very experienced porting AP to new boards.

2024-12-30 23:53 UTC, peterbarker submitted a review, later dismissed
partial on-call review only :-)

2024-12-30 23:53 UTC, peterbarker commented on libraries/AP_Mount/AP_Mount_CADDX.h
> +#include "AP_Mount_Backend_Serial.h"
```suggestion
#include "AP_Mount_Backend_config.h"
```

2024-12-30 23:53 UTC, peterbarker commented on libraries/AP_Mount/AP_Mount_CADDX.h
> +#include <AP_HAL/AP_HAL.h>
#include "AP_Mount_Backend_Serial.h"

2024-12-30 23:53 UTC, peterbarker commented on libraries/AP_Mount/AP_Mount_CADDX.h
> +        GIMBAL_MODE_FOLLOW = 0,
```suggestion
        FOLLOW = 0,
```

etc

2025-01-02 03:00 UTC, rmackay9 commented on libraries/AP_Mount/AP_Mount_CADDX.h
> +#include "AP_Mount_Backend_Serial.h"
done, thanks for the review!

2025-01-02 03:00 UTC, rmackay9 commented on libraries/AP_Mount/AP_Mount_CADDX.h
> +#include <AP_HAL/AP_HAL.h>
txs,done

2025-01-02 03:01 UTC, rmackay9 commented on libraries/AP_Mount/AP_Mount_CADDX.h
> +        GIMBAL_MODE_FOLLOW = 0,
done, txs

2025-01-02 03:12 UTC, peterbarker requested changes
Looks pretty good.

2025-01-02 03:12 UTC, peterbarker commented on libraries/AP_Mount/AP_Mount_CADDX.h
> +#include <AP_HAL/AP_HAL.h>
```suggestion
```

2025-01-02 03:12 UTC, peterbarker commented on libraries/AP_Mount/AP_Mount_CADDX.h
> +#include <AP_Math/AP_Math.h>
```suggestion
```

2025-01-02 03:12 UTC, peterbarker commented on libraries/AP_Mount/AP_Mount_CADDX.h
> +    bool get_attitude_quaternion(Quaternion& att_quat) override;
```suggestion
    bool get_attitude_quaternion(class Quaternion& att_quat) override;
```

Not actually including the right header to get this - just getting it transitively somehow

2025-01-02 03:12 UTC, peterbarker commented on libraries/AP_Mount/AP_Mount_CADDX.h
> +        FOLLOW = 0,
This doesn't make a lot of sense!
```suggestion
```

2025-01-02 03:22 UTC, rmackay9 commented on libraries/AP_Mount/AP_Mount_CADDX.h
> +#include <AP_HAL/AP_HAL.h>
removed include, thanks

2025-01-02 03:22 UTC, rmackay9 commented on libraries/AP_Mount/AP_Mount_CADDX.h
> +#include <AP_Math/AP_Math.h>
removed include, thanks

2025-01-02 03:25 UTC, rmackay9 commented on libraries/AP_Mount/AP_Mount_CADDX.h
> +        FOLLOW = 0,
Hi @peterbarker, thanks for the review.  I've removed this line because we don't use it but I can imagine that we could use it as a default value so not sure why it doesn't makes sense?

2025-01-02 03:27 UTC, rmackay9 commented on libraries/AP_Mount/AP_Mount_CADDX.h
> +    bool get_attitude_quaternion(Quaternion& att_quat) override;
I'm going to skip this change I think because it leads to a compile failure and would make it inconsistent with the virtual method that it is overriding and also all other drivers.  Apologies, I'm probably misunderstanding something

2025-01-02 03:28 UTC, rmackay9 commented on libraries/AP_Mount/AP_Mount_CADDX.h
> +#include <AP_Math/AP_Math.h>
Actually I've put this back because AP_Math.h is where "quaternion" is included

2025-01-02 05:25 UTC, peterbarker commented on libraries/AP_Mount/AP_Mount_CADDX.h
> +        FOLLOW = 0,
Generally we don't use the same enumeration which is giving names to bit-offsets for *combinations* of those bits (AKA a "mask").

It would be nice to have some type-safety around this sort of thing, but I've never managed to propose a PR to add that....

2025-01-02 06:10 UTC, peterbarker approved these changes
LGTM

2025-01-02 06:10 UTC, peterbarker commented on libraries/AP_Mount/AP_Mount_CADDX.h
> +#include <AP_Math/AP_Math.h>
```
diff --git a/libraries/AP_Mount/AP_Mount_CADDX.h b/libraries/AP_Mount/AP_Mount_CADDX.h
index fe423f55459..3d831209bf7 100644
--- a/libraries/AP_Mount/AP_Mount_CADDX.h
+++ b/libraries/AP_Mount/AP_Mount_CADDX.h
@@ -8,8 +8,7 @@
 #if HAL_MOUNT_CADDX_ENABLED
 
 #include "AP_Mount_Backend_Serial.h"
-#include <AP_Math/AP_Math.h>
-#include <AP_Common/AP_Common.h>
+#include <AP_Math/quaternion.h>
 
 class AP_Mount_CADDX : public AP_Mount_Backend_Serial
 {
```

2025-01-02 06:10 UTC, peterbarker commented on libraries/AP_Mount/AP_Mount_CADDX.cpp
> +    uint16_t yaw_target_cmd = constrain_uint16(wrap_2PI(angle_target_rad.get_bf_yaw()) * scalar, AXIS_MIN, AXIS_MAX);
```suggestion
    const uint16_t roll_target_cmd = constrain_uint16(wrap_2PI(angle_target_rad.roll) * scalar, AXIS_MIN, AXIS_MAX);
    const uint16_t pitch_target_cmd = constrain_uint16(wrap_2PI(angle_target_rad.pitch) * scalar, AXIS_MIN, AXIS_MAX);
    const uint16_t yaw_target_cmd = constrain_uint16(wrap_2PI(angle_target_rad.get_bf_yaw()) * scalar, AXIS_MIN, AXIS_MAX);
```

2025-01-02 07:14 UTC, rmackay9 commented on libraries/AP_Mount/AP_Mount_CADDX.cpp
> +    uint16_t yaw_target_cmd = constrain_uint16(wrap_2PI(angle_target_rad.get_bf_yaw()) * scalar, AXIS_MIN, AXIS_MAX);
ha ha, thanks.  I was wondering if someone would notice the missing const .. added!

2025-01-02 07:19 UTC, rmackay9 commented on libraries/AP_Mount/AP_Mount_CADDX.h
> +#include <AP_Math/AP_Math.h>
ok thanks.  Updated to remove AP_Common.h and change to <AP_Math/quaternion.h>.  I'm surprised we don't need AP_Common.h in there.  We include that in every other AP_Mount backend so I guess we could remove it from many places

2025-01-02 07:20 UTC, rmackay9 commented
I've updated with @peterbarker's requests and marked as "MergeOnCIPass"

2025-01-02 11:17 UTC, peterbarker commented on libraries/AP_Mount/AP_Mount_CADDX.h
> +#include <AP_Math/AP_Math.h>
> ok thanks. Updated to remove AP_Common.h and change to <AP_Math/quaternion.h>. I'm surprised we don't need AP_Common.h in there. We include that in every other AP_Mount backend so I guess we could remove it from many places

Probably, yes - and that will save compile time, which everybody likes.

We're getting away with some shenanigans by having those all around the place - things like the stdint.h include come to mind :-)

2025-01-02 11:18 UTC, merged

2025-01-02 11:18 UTC, peterbarker commented
Merged it!

2025-01-21 10:45 UTC, rmackay9 commented
this is included in ArduPilot-4.6.0-beta3

2025-01-21 10:47 UTC, rmackay9 commented
I attempted to cherry-pick this into 4.6.0-beta3 but ran into merge conflicts so I've left it out for now