feat: add send_named_int function and Lua binding
ArduPilot/ardupilot pull request #28944
Opened 2024-12-24 19:08 UTC by ben-xD

This is useful to send NAMED_VALUE_INT mavlink messages in the same way as NAMED_VALUE_FLOAT, including in lua scripts:
```lua
local an_integer = 1
gcs:send_named_int("EXAMPLE", an_integer)
```

I've confirmed this works by building Arduplane in Docker and then running it my lua script.

2024-12-25 07:44 UTC, Lalbabu2001 commented
Hi please add support for this board
https://www.6sfull.cz/en/neutronrc-mini-f405-2-6s-20--20-30--30/

Don't forget to add Bmp 280 baro because new versions come with bmp280.
Also add support for PPM .
Thanks.

2024-12-25 11:44 UTC, rmackay9 commented
Hi @Lalbabu2001, please do not spam the pull requests.  That's definitely not a good way to achieve what you'd like.

2025-01-01 22:43 UTC, peterbarker approved these changes
LGTM, but would be nice to have an example script and autotest.

2025-01-03 03:23 UTC, peterbarker requested changes
Gah.  Just realised the commit messages need splitting.

Please run`./Tools/gittools/git-subsystems-split` and force-push your branch.

That example would still be nice ;-)

2025-01-03 11:10 UTC, ben-xD commented
That script doesn't seem to work on macOS (sed is slightly different?) but it worked on Debian.

I've also edited a simple script to include `send_named_int`

2025-01-14 14:33 UTC, ben-xD commented
@peterbarker I've updated the PR please have a look :)

2025-04-23 13:31 UTC, ben-xD commented
@peterbarker, I rebased onto the latest `master`, all checks have passed, could you take a look?

2026-06-11 10:32 UTC, khancyr commented
replaced by https://github.com/ArduPilot/ardupilot/pull/33409. thanks

2026-06-11 10:32 UTC, closed without merging